### ISSUE TITLE
mc cp doesn't use the correct exit code

### ISSUE THREAD

**Issue by kahing** [minio/mc#1153]
```
$ mc cp xout https://play.minio.io:9000/test/
xout:                                      130.81 KB / 130.81 KB
$ mc cp xout https://play.minio.io:9000/test/
mc: <ERROR> Failed to copy ‘xout’. Object #xout already exists.
xout:                                      130.81 KB / 130.81 KB 
$ echo $?
```

**Comment by harshavardhana** [comment]
> $ echo $?

Nope it does not, that is how it is intended. 

For a scriptability one should use  ``mc --json``

**Comment by harshavardhana** [comment]
Closing this for now...

**Comment by freeseacher** [comment]
I am using mc to upload build artifact to minio server. Most known ci system uses exit code to check if build failed. 
What is the best way to achieve "build failed" with `mc --json` behavior?

**Comment by harshavardhana** [comment]
> I am using mc to upload build artifact to minio server. Most known ci system uses exit code to check if build failed. 
> What is the best way to achieve "build failed" with mc --json behavior?

@freeseacher you could check for '.status' 

```
 $ mc ls --json s3/ | jq .status
"success"
"success"
"success"
"success"
"success"
```

```
$ mc ls --json -r /usr | jq .status
"success"
"success"
"success"
"success"
"success"
"success"
"success"
"success"
"success"
"success"
"error"
"error"
"error"
```
