### ISSUE TITLE
Plagiarism

### ISSUE THREAD

**Issue by Kafkamorph** [minio/mc#1206]
You /really/ couldn't find a better acronym/shortcut than one that WILL be in conflict with Midnight Commander?

mc (the original one) is 21 years old, btw. Check wikipedia.

**Comment by harshavardhana** [comment]
We really tried hard to make it shorter.  We addressed a similar question previously at #873

**Comment by harshavardhana** [comment]
We will discuss this again today internally. What would be the best way to address this..

**Comment by abperiasamy** [comment]
Minio's mc is a single static binary, typically copied to user's home dir (~/bin). We are not expecting Minio's mc to be bundled with the Unix or GNU/Linux distros. 

Besides, Minio Client is an object storage client.  Midnight Commander is a free software clone of Norton Commander. They both share no code or ideas. Only their abbreviation is same.

**Comment by harshavardhana** [comment]
Closing this.
