### ISSUE TITLE
unexpected "mc share" behavior

### ISSUE THREAD

**Issue by koolhead17** [minio/mc#1282]
I am trying to play with mc share command on google cloud, below are the steps i followed.

$ mc share download google/atulfolder/aj11.txt
mc: Successfully created ‘/Users/koolhead17/.mc/share/urls.json’
http://storage.googleapis.com/atulfolder/aj11.txt?AWSAccessKeyId=GOOGXWCJKOIYMYNRPFGJ&Expires=1447938629&Signature=HhrYRXOBgRxvWo26V%2Fov45%2BL28Q%3D

But when I am trying to access this URL via browser I am getting this error.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous callers do not have storage.objects.get access to object atulfolder/aj11.txt.
</Details>
</Error>
```

**Comment by harshavardhana** [comment]
```
baseURL + "?GoogleAccessId=" + GoogleAccessStorageId + "&Expires=" + Expiration + "&Signature=" + UrlEncodedSignature
```

Looks like setting AWSAccessKeyId is the issue here - compatibility problems :-)

**Comment by harshavardhana** [comment]
Click on this URL it should work 

http://storage.googleapis.com/atulfolder/aj11.txt?GoogAccessId=GOOGXWCJKOIYMYNRPFGJ&Expires=1447938629&Signature=HhrYRXOBgRxvWo26V%2Fov45%2BL28Q%3D
