### ISSUE TITLE
Trace unnecessary HTTP calls

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1293]
- Calculate and figure out minimum calls required for a given network operation.
- Figure out if connection is being re-used for subsequent calls.

**Comment by harshavardhana** [comment]
Fixed #1297 - https://github.com/minio/minio-go/commit/e41eab565369490db09a89fedd26d1eaec39ca90

**Comment by harshavardhana** [comment]
Reopening this for now.. while we fully verify other places inside 'mc' which needs to be optimized.

**Comment by krishnasrinivas** [comment]
code review shows that "diff" is the only place which does a lot of url2Stat() we can use List() instead of url2Stat() here

**Comment by harshavardhana** [comment]
> code review shows that "diff" is the only place which does a lot of url2Stat() we can use List() instead of url2Stat() here

Yes that is the right fix.

**Comment by krishnasrinivas** [comment]
I will check mc using --debug and see if there are any unnecessary http calls in any of the sub-commands

**Comment by krishnasrinivas** [comment]
* ls mb cat rm pipe access - look fine

* simple cp of a single file was doing HEAD on bucket 3 times
* diff does lot of HEAD calls as we do url2Stat instead of List
* mirror/cp etc sends 0 byte files as multiparts uploads

**Comment by harshavardhana** [comment]
> simple cp of a single file was doing HEAD on bucket 3 times

Ah this is due to the cpQueue doing NCPUS worth of go-routines..

**Comment by harshavardhana** [comment]
Fixed by #1324 #1314 #1313
