### ISSUE TITLE
Make cli package provide a callback for unknown flag, just as CommandNotFound.

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1347]

**Comment by mkash32** [comment]
What is the motive for doing this? What would we want to provide in the callback function for unknown flag?

**Comment by harshavardhana** [comment]
> What is the motive for doing this? What would we want to provide in the callback function for unknown flag?

The reason is that unknown flags today cannot be handled properly and there is no way for us to print convenient messages to the user - just like how we can do with 'sub-commands' instead. 

It is an older bug we might have to revisit if at all it's needed anymore.
