### ISSUE TITLE
mc cp on non existent bucket - error

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/mc#1376]
"/krisuplaod/aaa/mc/..." what's happening here?

mc: <DEBUG> PUT /krisuplaod/aaa/mc/... HTTP/1.1
Host: s3-us-west-2.amazonaws.com
User-Agent:  Minio/2015-11-17T02:56:00Z (mc; darwin; amd64)
Content-Length: 4962
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20151117/us-west-2/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: uWr3V2k5oXrEstS27bUM5w==
Content-Type: application/octet-stream
X-Amz-Content-Sha256: 615030803da6b0d0c8c90947477bc427fcaba9bb0141412a6bbc019cb5a7b705
X-Amz-Date: 20151117T061254Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 17 Nov 2015 06:12:54 GMT
Server: AmazonS3
X-Amz-Id-2: Rajrmd3bDettWzsTtONFyV8grPO4rc6QgwRq8aYn5Gndxaze6eeP9a9GqAnUvfIvbUReyazP9Ns=
X-Amz-Request-Id: 7941512FC2332574

**Comment by harshavardhana** [comment]
Not an issue.. superseded by migration from '...' to '-r'
