### ISSUE TITLE
mc session terminates for an invalid case on windows handle it. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1421]
![screen shot 2015-11-18 at 4 59 34 pm](https://cloud.githubusercontent.com/assets/622699/11259352/d93c3e62-8e15-11e5-905e-81b4f39694d1.png)

**Comment by krishnasrinivas** [comment]
before fix:
krishna@escape:~/gocode/src/github.com/minio/mc$ mc  cat https://testing.s3.amazonaws.com/aaaa
mc: <ERROR> Unable to read from ‘https://testing.s3.amazonaws.com/aaaa’. Access Denied


after fix:
krishna@escape:~/gocode/src/github.com/minio/mc$ mc  cat https://testing.s3.amazonaws.com/aaaa
mc: <ERROR> Unable to read from ‘https://testing.s3.amazonaws.com/aaaa’. Insufficient permissions to access this file ‘https://testing.s3.amazonaws.com/aaaa’

**Comment by harshavardhana** [comment]
Fixed by #1427
