### ISSUE TITLE
unexpected "mc update" behavior

### ISSUE THREAD

**Issue by koolhead17** [minio/mc#1440]
I updated my mc with 

$ go get -u github.com/minio/mc

I tried
$mc update
mc: <ERROR> Unable to read from update URL ‘https://dl.minio.io:9000/updates/updates.json’. dial tcp: lookup dl.minio.io: no such host

$ping dl.minio.io:9000
ping: cannot resolve dl.minio.io:9000: Unknown host
$ping dl.minio.io
PING dl.minio.io (162.243.132.171): 56 data bytes
64 bytes from 162.243.132.171: icmp_seq=0 ttl=55 time=252.320 ms
64 bytes from 162.243.132.171: icmp_seq=1 ttl=55 time=287.487 ms
$curl dl.minio.io:9000 [returns nothing]

This how my config.json looks like

$cat .mc/config.json
{
"version": "6",
"alias": {
"dl": "https://dl.minio.io:9000",
"gcs": "https://storage.googleapis.com",
"google": "http://storage.googleapis.com",
"local": "http://localhost:9000",
"localhost": "http://localhost:9000",
"play": "https://play.minio.io:9000",
"s3": "https://s3.amazonaws.com"
},
"hosts": {
"http://127.0.0.1:9000": {
"accessKeyId": "",
"secretAccessKey": "",
"api": "S3v4"
},
"http://localhost:9000": {
"accessKeyId": "",
"secretAccessKey": "",
"api": "S3v4"
},
"https://dl.minio.io:9000": {
"accessKeyId": "",
"secretAccessKey": "",
"api": "S3v4"
},
"https://play.minio.io:9000": {
"accessKeyId": "",
"secretAccessKey": "",
"api": "S3v4"
},
"https://s3.amazonaws.com": {
"accessKeyId": "YOUR-ACCESS-KEY-ID-HERE",
"secretAccessKey": "YOUR-SECRET-ACCESS-KEY-HERE",
"api": "S3v4"
},
"https://storage.googleapis.com": {
"accessKeyId": "MY-ACCESS-KEY-ID-HERE",
"secretAccessKey": "MY-SECRET-ACCESS-KEY-HERE",
"api": "S3v2"
}
}

**Comment by harshavardhana** [comment]
For me 'mc update' is working fine.. 

```
$ mc update
You are already running the most recent version of ‘mc’.
```

**Comment by koolhead17** [comment]
Closing this, it might have been because of my slow internet connection.
