### ISSUE TITLE
Fails to install: too many errors

### ISSUE THREAD

**Issue by kaihendry** [minio/mc#1470]
```
X1C3:~$  go get -u github.com/minio/mc
# github.com/minio/mc/pkg/client/s3
go/src/github.com/minio/mc/pkg/client/s3/s3.go:376: bucket.Stat undefined (type minio.BucketStat has no field or method Stat)
go/src/github.com/minio/mc/pkg/client/s3/s3.go:386: bucket.Stat undefined (type minio.BucketStat has no field or method Stat)
go/src/github.com/minio/mc/pkg/client/s3/s3.go:386: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
go/src/github.com/minio/mc/pkg/client/s3/s3.go:388: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
go/src/github.com/minio/mc/pkg/client/s3/s3.go:391: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
go/src/github.com/minio/mc/pkg/client/s3/s3.go:398: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
go/src/github.com/minio/mc/pkg/client/s3/s3.go:399: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
go/src/github.com/minio/mc/pkg/client/s3/s3.go:416: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
go/src/github.com/minio/mc/pkg/client/s3/s3.go:418: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
go/src/github.com/minio/mc/pkg/client/s3/s3.go:421: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
go/src/github.com/minio/mc/pkg/client/s3/s3.go:421: too many errors
```

I realise there are prebuilt binaries, but I want to build from source. Running 64bit Archlinux with `go version go1.5.1 linux/amd64`

**Comment by harshavardhana** [comment]
> go/src/github.com/minio/mc/pkg/client/s3/s3.go:399: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
> go/src/github.com/minio/mc/pkg/client/s3/s3.go:416: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
> go/src/github.com/minio/mc/pkg/client/s3/s3.go:418: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
> go/src/github.com/minio/mc/pkg/client/s3/s3.go:421: object.Stat undefined (type minio.ObjectMultipartStat has no field or method Stat)
> go/src/github.com/minio/mc/pkg/client/s3/s3.go:421: too many errors

Ah the limitation of Golang tooling, a perfectly vendorized package fails. The reason is that the referenced packages have changed a bit. 

Fixing it, give me a min :-). Sorry for the trouble.
