### ISSUE TITLE
Not making bucket remotely

### ISSUE THREAD

**Issue by kaihendry** [minio/mc#1472]
As you can see from http://s.natalian.org/2015-11-22/mc.log ... it's very confusing to errors when adding a configuration. I'm not sure what I am doing wrong.

I even try to make a bucket, but it appears to be local, not remote.
http://s.natalian.org/2015-11-22/1448163727_1912x1036.png

Where am I doing wrong?

**Comment by harshavardhana** [comment]
I think the problem is this.. you are missing http://192.168.88.96:9000

**Comment by harshavardhana** [comment]
mc config host add http://192.168.88.96:9000 accesskey secretkey

**Comment by harshavardhana** [comment]
There is another problem that I see. Looks like DEBUG is on by default. Let me get back to my laptop in couple of hrs. I will get it fixed.
