### ISSUE TITLE
Should not complain when endpoint is not in config.json

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/mc#1499]
For the situation where someone wants to give readonly access to their minio server.

```
krishna@escape:~$ mc ls https://random.minio.io
mc: <ERROR> Unable to stat ‘https://random.minio.io’. No matching host found for the given URL ‘https://random.minio.io’.
krishna@escape:~$ 
```

If the host is not found in config.json we can try for an anonymous access. If the call fails with `Access denied` then we can complain about config.json entry.

**Comment by harshavardhana** [comment]
> If the host is not found in config.json we can try for an anonymous access. If the call fails with Access denied then we can complain about config.json entry.

The reason to do that is we cannot avoid making a request to any server other than s3 compatible ones. 

For example allowing what you said makes the errors look more uglier

```
$ mc ls https://www.google.com
mc: <ERROR> Unable to stat ‘https://www.google.com’. XML syntax error on line 1: invalid character entity & (no semicolon)
```

**Comment by harshavardhana** [comment]
It is better left the way it is.. anonymous or not.  User can add what they wish to use.
