### ISSUE TITLE
mc uses incorrect credentials

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/mc#1501]
krishna@escape:/tmp$ mc ls https://peppadog.s3.amazonaws.com/
[2015-11-30 18:50:15 IST] 2.0KiB passwd
krishna@escape:/tmp$

I don't have an entry for https://peppadog.s3.amazonaws.com/ in config.json it is picking up the credentials of https://s3.amazonaws.com entry.

Is this expected behavior?

**Comment by harshavardhana** [comment]
Yes it expected.  s3.amazonaws.com is already defined so it will use that credential. If you specifically provide a new credential then it will work with that credential.
