### ISSUE TITLE
mc cp/mirror doesn't detect or preserve Content-Type

### ISSUE THREAD

**Issue by sanderhahn** [minio/mc#1516]
The Content-Type always becomes "application/octet-stream" at the destination when copying or mirroring from from local files or S3.

**Comment by harshavardhana** [comment]
It was on purpose to avoid content type detection since mime type detection is not common across all libraries.  Keeping this under discussion for now.

**Comment by harshavardhana** [comment]
We decided to fix this issue.. Thanks for your report @sanderhahn
