### ISSUE TITLE
handle non standard regions seamlessly

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/mc#1537]
krishna@escape:~/dev$ mc ls s3/krisupload/40mbfile
mc: <ERROR> Unable to stat ‘https://s3.amazonaws.com/krisupload/40mbfile’. The bucket you are attempting to access must be addressed using the specified endpoint https://s3-us-west-2.amazonaws.com. Send all future requests to this endpoint.
krishna@escape:~/dev$

Since the minio-go API now takes https://s3.amazonaws.com as endPoint in minio.New() and we do s3 operations on bucketName.s3.amazonaws.com we should be able to handle this situation.

**Comment by harshavardhana** [comment]
Minio go is not finished yet. Once it is done it will handle this situation. For the time being this is fine use the bucket name style.

**Comment by harshavardhana** [comment]
Fixed by - https://github.com/minio/minio-go/pull/250
