### ISSUE TITLE
mc config syntax verification should be added. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1543]
Verify config syntax validating, aliasnames, host config, endpoint.

**Comment by sreeram-boyapati** [comment]
Hey I would like to work on this. Can you add more details with an example?

**Comment by harshavardhana** [comment]
> Hey I would like to work on this. Can you add more details with an example?

What this needs is validating config file, if its intact. Currently it is done via 'checkConfig()'  - i.e it just validates if the config file can be read or not, what we need to validate is if the config entries are intact and have valid format for example 

To start by validating if version is correct.

```
	"version": "8",
	"hosts": {
```

Then next is to validate hosts for example 

Validating if 'aliases' were hand edited and contains unsupported characters,
```
    "church": {
			"url": "https://churchofminio.com",
			"accessKey": "W891COK7VCTZA55PY0PN",
			"secretKey": "ieStcv8GvbeqGdQrIdDutMicbymOuMYvj3jdlIyA",
			"api": "S3v4"
		},
``` 

Next is validating individual fields for example 

- 'api' can only have 'S3v2' or 'S3v4' and should always be non-empty.  
- 'url' should be of a proper URL format and should always be non-empty. 

All this is to validate existing config values and reporting to user if there are problems, exit 'mc' and giving valid suggestions to fix them accordingly.

**Comment by harshavardhana** [comment]
Thanks again @sreeram-boyapati for taking a look.

**Comment by sreeram-boyapati** [comment]
Ah! I get to write more LoC. cool on it.
