### ISSUE TITLE
confusing "error" while bucket not exist

### ISSUE THREAD

**Issue by koolhead17** [minio/mc#1550]
I was trying to add an object to a bucket which does not exist & got this output, the error should have mentioned "bucket does not exist" instead what i got as screenshot.
![158dc34e-a370-11e5-9369-41ce7d9987c4](https://cloud.githubusercontent.com/assets/41746/11816759/f3855e1c-a377-11e5-8e7d-07707f023f58.png)

**Comment by harshavardhana** [comment]
Yes this needs to be fixed . #1544  will fix this.
