### ISSUE TITLE
unexpected "mc ls" behavior with bucket name starting with number. 

### ISSUE THREAD

**Issue by koolhead17** [minio/mc#1552]
I have a bucket name  "12312buuuucker" & its empty. When I am trying to remove it, this is the error am getting.

```
$ mc ls s3/12312buuuucker
mc: <ERROR> Unable to stat ‘https://s3.amazonaws.com/12312buuuucker’. The specified bucket is not valid.
```

**Comment by harshavardhana** [comment]
Yes this is correct from current code, it will be fixed after #1544 merge.
