### ISSUE TITLE
used a as lib ?

### ISSUE THREAD

**Issue by joeblew99** [minio/mc#1557]
can this be used as a lib ?

**Comment by harshavardhana** [comment]
> can this be used as a lib ?

Nope it cannot be as of now, can you explain more on your requirement? - we have had a `libmc` idea before :-)

**Comment by harshavardhana** [comment]
> can this be used as a lib ?

On the other hand `--json` output is exactly for such a purpose.

**Comment by joeblew99** [comment]
The use case.
I have many remote servers that are behind  a WAN with a dynamic ip.
The wan connection is a bit on / off in some of the locations too.

I need to push data from the remote servers up to s3.
I could run mc from a bash script, with it always waiting for new log files to send up ?

But I would prefer to use mc as a library and wrap it as a golang server. It's easier to extend it because we have 100's of different logs that need to go to different endpoints etc. Within a proper golang programming it would be much easier to cognitively keep track off, than lots of bash scripts.

**Comment by harshavardhana** [comment]
> But I would prefer to use mc as a library and wrap it as a golang server. It's easier to extend it because we have 100's of different logs that need to go to different endpoints etc. Within a proper golang programming it would be much easier to cognitively keep track off, than lots of bash scripts.

Rather than 'mc',  minio-go will help in this case and is the right fit - did you see any issues with minio-go or does it need something that you think it lacks? - is libmc requirement largely because it abstracts concepts like mirroring, copying etc to multiple locations?

**Comment by joeblew99** [comment]
thanks that sounds good !
I am already trying out minio-go.
I dont know if it support the resiliency aspect of retry etc etc. Need to test first.

Will close for now, but wil let you know.
