### ISSUE TITLE
poor network connectivity, causes timing out

### ISSUE THREAD

**Issue by joeblew99** [minio/mc#1559]
i am using mc to upload data from remote sites.

```
# copy from local to s3
    ./mc cp --recursive $DIRROOT $S3_SERVER/$S3_BUCKET/
```

When this runs i get:
```
Bucket created successfully ‘https://s3.amazonaws.com/blah/’.
mc: <ERROR> Failed to copy ‘/Users/apple/workspace/go/src/bitbucket.org/blah/toolbin/.git/objects/00/b64172f461a7bf426dedf38106690240fa1e75’. Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
mc: Session safely terminated. To resume session ‘mc session resume oJzRscke’
```

Any ideas ?

Is there a way to tell it to backoff and retry until it knows for sure that everything has moved up ?

**Comment by harshavardhana** [comment]
> Is there a way to tell it to backoff and retry until it knows for sure that everything has moved up ?

We haven't implement a retry logic just yet, we are finalizing on where it should be ideally implemented - should it be minio-go or 'mc'

**Comment by harshavardhana** [comment]
> Is there a way to tell it to backoff and retry until it knows for sure that everything has moved up ?

Another approach is to use this - https://gist.github.com/harshavardhana/0bc3dea5ab2d41222930

**Comment by harshavardhana** [comment]
Closing this,  minio-go will implement a retry logic and opening a relevant issue there.

**Comment by joeblew99** [comment]
Cheers
