### ISSUE TITLE
mirror session resume does nothing

### ISSUE THREAD

**Issue by as6o** [minio/mc#1560]
Version: 2015-12-06T01:59:23Z

I run `mc mirror` which eventually fails in my case.  :(  But, when I go to try and restart the session nothing happens and the session goes away forcing me to rerun the command (and its expensive indexing phase).  Am I doing something wrong?

```
$ ./mc -C map.mc mirror  https://s3.amazonaws.com/md /mnt/data/s3-mapping-data
mc: <ERROR> Failed to mirror ‘https://s3.amazonaws.com/md/data.png’. read tcp 192.168.0.43:48304->54.231.15.24:443: read: connection reset by peer
mc: Session safely terminated. To resume session ‘mc session resume RCWZCfSG’
$ ./mc -C map.mc session list
RCWZCfSG -> [2016-01-07 17:27:29 UTC] mirror https://s3.amazonaws.com/md /mnt/data/s3-mapping-data
$ ./mc -C map.mc session resume RCWZCfSG
$ ./mc -C map.mc session list
$ ./mc version
```

**Comment by harshavardhana** [comment]
> $ ./mc -C map.mc mirror  https://s3.amazonaws.com/md /mnt/data/s3-mapping-data
> mc: <ERROR> Failed to mirror ‘https://s3.amazonaws.com/md/data.png’. read tcp 192.168.0.43:48304->54.231.15.24:443: read: connection reset by peer
> mc: Session safely terminated. To resume session ‘mc session resume RCWZCfSG’
> $ ./mc -C map.mc session list
> RCWZCfSG -> [2016-01-07 17:27:29 UTC] mirror https://s3.amazonaws.com/md /mnt/data/s3-mapping-data
> $ ./mc -C map.mc session resume RCWZCfSG
> $ ./mc -C map.mc session list
> $ ./mc version

We are going to make a new release to fix this issue. Thanks for your bug report.

**Comment by harshavardhana** [comment]
> $ ./mc -C map.mc mirror  https://s3.amazonaws.com/md /mnt/data/s3-mapping-data

You can still attempt the same by executing the same command. 

`./mc -C map.mc mirror  https://s3.amazonaws.com/md /mnt/data/s3-mapping-data`

It will continue from where it left off.

**Comment by as6o** [comment]
Yes - one of the benefits of the `mirror` command.  However, it still needs to do the up-front indexing which, in my case, takes a while.  I'm under the assumption that the resume command will not have to reindex.  Is that assumption correct?

**Comment by harshavardhana** [comment]
> Yes - one of the benefits of the mirror command. However, it still needs to do the up-front indexing which, in my case, takes a while. I'm under the assumption that the resume command will not have to reindex. Is that assumption correct?

You are right! that is the caveat it would re-index, if the session is not present.

**Comment by harshavardhana** [comment]
@as6o - just made a new release with the fix. - https://dl.minio.io/client/mc/release/

**Comment by as6o** [comment]
Works great!

**Comment by harshavardhana** [comment]
> Works great!

Thanks closing this.
