### ISSUE TITLE
mc mirror errors out but exit status is 0

### ISSUE THREAD

**Issue by as6o** [minio/mc#1562]
I'm running into a situation where `mc mirror` is frequently throwing "connection reset by peer" errors.  I'd like to write a simple script that'll just keep running `mc mirror` or `mc session resume` on error but without a meaningful error status it'll run indefinitely.

**Comment by harshavardhana** [comment]
> I'm running into a situation where mc mirror is frequently throwing "connection reset by peer" errors. I'd like to write a simple script that'll just keep running mc mirror or mc session resume on error but without a meaningful error status it'll run indefinitely.

Error codes generally should be avoided since there is no way to standardize them and many situations needs to have different kinds of exit codes, the best way we recommend is to use 'mc --json' output and 'jq' 

Here is an example on how to achieve this. 

```
$ mc ls --json non-existent-file
{"status":"error","error":{"message":"Unable to stat ‘non-existent-file’.","cause":{"message":"Requested file ‘’ not found","error":{"Path":""}},"type":"fatal","sysinfo":{"host.arch":"amd64","host.cpus":"4","host.lang":"go1.5.1","host.name":"command.local","host.os":"darwin","mem.heap.total":"2.8MB","mem.heap.used":"2.3MB","mem.total":"5.3MB","mem.used":"2.3MB"}}}
```

```
$ mc ls --json non-existent-file | jq .status
"error"
```

```
$ touch non-existent-file
$ mc ls --json non-existent-file | jq .status
"success"
``` 

Now this can be easily scripted and also nicely logged in case you wish to see how many times mc failed for what errors etc and it can be more discerning. 

'mc session' saves your CLI flags as well.

**Comment by as6o** [comment]
Doesn't look like resume outputs JSON in the event of an error (I tried putting `--json` before the `session` command as well):

```
$ ./mc -C map.mc session --json resume cCwjoyLl
mc: <ERROR> Failed to mirror ‘https://s3.amazonaws.com/md/map.png’. read tcp 192.168.0.67:42894->54.231.14.16:443: read: connection reset by peer
mc: Session safely terminated. To resume session ‘mc session resume cCwjoyLl’
$ 
```

**Comment by harshavardhana** [comment]
> $ ./mc -C map.mc session --json resume cCwjoyLl
> mc: <ERROR> Failed to mirror ‘https://s3.amazonaws.com/md/map.png’. read tcp 192.168.0.67:42894->54.231.14.16:443: read: connection reset by peer
> mc: Session safely terminated. To resume session ‘mc session resume cCwjoyLl’
> $

Can you paste the output for `mc -C map.mc cat map.mc/session/cCwjoyLl.json` ?

**Comment by as6o** [comment]
I noticed json is set to false in "globalBoolFlags" below but I am passing --json to the resume command.  Can --json not be set on resume?

```
{
        "version": "5",
        "time": "2016-01-07T21:29:03.153539661Z",
        "workingFolder": "/media/sda/s3-copy-work",
        "globalBoolFlags": {
                "debug": false,
                "json": false,
                "noColor": false,
                "quiet": false
        },
        "globalIntFlags": {},
        "globalStringFlags": {},
        "commandType": "mirror",
        "cmdArgs": [
                "https://s3.amazonaws.com/md",
                "/mnt/data/s3-mapping-data"
        ],
        "cmdBoolFlags": {
                "force": false
        },
        "cmdIntFlags": {},
        "cmdStringFlags": {},
        "lastCopied": "https://s3.amazonaws.com/md/random.png",
        "totalBytes": 48023470765494,
        "totalObjects": 2616459
}$
```

**Comment by as6o** [comment]
So - I set "json" to true in the session .json file and am now getting json output.  However, I really only wanted json at the end of the run to get exit information.  Now I've lost the nifty green progress bar and am getting a ton of json instead.  Is --json and --quiet mutually exclusive?  Can I use both to only get exit status at the end of the run?  I'm trying to copy a couple million files and the json can quickly get out of hand for me. :)

**Comment by harshavardhana** [comment]
> I noticed json is set to false in "globalBoolFlags" below but I am passing --json to the resume command. Can --json not be set on resume?

Session only saves previous CLI flags, there is no way to add new ones in current release.  ``--json`` is only meant to be used inside scripts it will make it inconsistent to parse json and also print progress bar at the same time. 

It is not possible in current release to only get '--json' during exit, since it is a global level option. It affects all printing functionality. 

For you to observe the progress bar as well, i will write a tiny python script to print progress bar while reading output from ``--json``

**Comment by abperiasamy** [comment]
Your mirror automation script is a common use case. Others in the community can also make use your script when it is done. I guess your script is run via tmux or screen rather an a cron job. It makes sense to keep the progress bar visually while the script runs endlessly.

Exit code and session json flag setting are both bugs. --quiet is used to suppress chatty console I/O (mainly useful for dumb terms). We could not find a better flag name.

**Comment by abperiasamy** [comment]
To just get exit status, what you need is exit status code. If mc doesnt respect exit code, it is a bug. --json is meant for script mode (with no console). --quiet is meant for dumb terms. If you want to keep the progress bar, checking exit code is the right approach.

**Comment by harshavardhana** [comment]
> To just get exit status, what you need is exit status code. If mc doesnt respect exit code, it is a bug. --json is meant for script mode (with no console). --quiet is meant for dumb terms. If you want to keep the progress bar, checking exit code is the right approach.

May be session can exit with an exit code. 

```
// Close a session and exit.
func (s sessionV6) CloseAndDie() {
        s.Close()
        console.Infoln("Session safely terminated. To resume session ‘mc session resume " + s.SessionID + "’")
        os.Exit(0)
}
```

**Comment by as6o** [comment]
Thanks for looking into this.  How soon before a new build?

**Comment by harshavardhana** [comment]
> Thanks for looking into this. How soon before a new build?

Soon! :-) ..
