### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by JensRantil** [minio/mc#1576]
I notice that your releases are only source code. Any change you'd be willing to also build binaries?

**Comment by harshavardhana** [comment]
> I notice that your releases are only source code. Any change you'd be willing to also build binaries?

Binaries are all available here - https://github.com/minio/mc#install-- and here https://dl.minio.io/client . where did you see this to be only source?

**Comment by JensRantil** [comment]
Ah, I see! I was looking here: https://github.com/minio/mc/releases

**Comment by harshavardhana** [comment]
> Ah, I see! I was looking here: https://github.com/minio/mc/releases

Those are perhaps added by github when we tag the branches, perhaps we can upload binaries at github releases as well.
