### ISSUE TITLE
constant fails on upload from local to s3 alway now. worked before

### ISSUE THREAD

**Issue by joeblew99** [minio/mc#1577]
golang 1.5
osx

i have a script to push up to S3, and its fails always now. It worked when there was only small amounts of data.
what it fails on is non deterministic.

´´´

BINARY="mc"

DIRROOT=$GOPATH"/src/bitbucket.org/xxx/toolbin"
S3_SERVER="s3.amazonaws.com"
S3_BUCKET="xxx-dev"

echo "Your S3_BUCKET path is: "     $S3_BUCKET

function pushs3() {
    echo "## PUSHING ##"
    
    echo "## Add S3 Configs ##"
    mc config host import https://s3.amazonaws.com credentials-aws.csv
    
    echo "## Listing Config ##"
    mc config host list
    
    # #./mc config host add https://s3.amazonaws.com $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY S3v4
    
    # Make bucket
    #./mc mb $S3_SERVER/$S3_BUCKET/
    
    echo "## Local files ##"
    ls -al $DIRROOT
    
    # copy from local to s3
    mc cp --recursive $DIRROOT $S3_SERVER/$S3_BUCKET/
}

´´´

Terminal:
````


## Local files ##
total 64
drwxr-xr-x  14 apple  staff    476 Jan 19 16:42 .
drwxr-xr-x  14 apple  staff    476 Jan 22 09:41 ..
-rw-r--r--@  1 apple  staff  24580 Jan 20 16:37 .DS_Store
drwxr-xr-x   7 apple  staff    238 Jan 19 16:42 bios-nuc
drwxr-xr-x   5 apple  staff    170 Dec 24 13:06 consul
drwxr-xr-x   6 apple  staff    204 Dec 29 22:39 godep
drwxr-xr-x   5 apple  staff    170 Dec 29 22:39 gof3r
drwxr-xr-x   4 apple  staff    136 Jan  2 14:06 goxc
drwxr-xr-x   6 apple  staff    204 Jan  4 17:49 mc
drwxr-xr-x   3 apple  staff    102 Jan 19 16:42 os-ubuntucore
drwxr-xr-x  14 apple  staff    476 Jan 20 17:05 os-windows
drwxr-xr-x   4 apple  staff    136 Dec 21 22:46 packer
-rw-r--r--   1 apple  staff    408 Jan  2 14:07 readme.md
drwxr-xr-x   5 apple  staff    170 Dec 23 13:18 terraform
mc: <ERROR> Failed to copy ‘/Users/apple/workspace/go/src/bitbucket.org/xxx/toolbin/packer/v0.8.6_darwin_amd64/packer-provisioner-file’. read tcp 192.168.0.100:64536->54.231.13.48:443: read: connection reset by peer
mc: Session safely terminated. To resume session ‘mc session resume FljzcYvB’
gedw99-MacBook-Pro:backend apple$ 

```

**Comment by joeblew99** [comment]
Any ideas on this ? I really like the concept of minio, but am needing to get this working. Deadlines :)

**Comment by joeblew99** [comment]
I tried Resume but it fails each time.

**Comment by harshavardhana** [comment]
> Any ideas on this ? I really like the concept of minio, but am needing to get this working. Deadlines :)

> mc: <ERROR> Failed to copy ‘/Users/apple/workspace/go/src/bitbucket.org/xxx/toolbin/packer/v0.8.6_darwin_amd64/packer-provisioner-file’. read tcp 192.168.0.100:64536->54.231.13.48:443: read: connection reset by peer

The issue seems to be network, where in the S3 server resets the connection, Can you copy using virtual style rather than path style like ? 

> mc cp --recursive $DIRROOT $S3_SERVER/$S3_BUCKET/

       mc cp --recursive $DIRROOT $S3_BUCKET.$S3_SERVER

**Comment by harshavardhana** [comment]
Closing this for now, re-open if you see further issues.
