### ISSUE TITLE
mc cp does not work well for the case one folder and one .zip have the same name.

### ISSUE THREAD

**Issue by philxia** [minio/mc#1578]
Here is my command try to upload the rac1 folder to bucket img, and there is a file - rac1.zip in I:\pictures folder as well. The result is both rac1 folder and rac1.zip file are uploaded to this bucket.
mc cp --recursive I:\pictures\rac1 http://127.0.0.1:9000/img

Is there a way I can only upload the folder in this case?

Thanks,
Phil

**Comment by harshavardhana** [comment]
> mc cp --recursive I:\pictures\rac1 http://127.0.0.1:9000/img

`mc` treats even file system to behave like S3 style prefixes, to allow for only directories to be copied use 

``mc cp --recursive I:\pictures\rac1\ http://127.0.0.1:9000/img`` or use 'mc mirror' which always defaults to 'directory' to 'directory'. 

``mc mirror --recursive I:\pictures\rac1 http://127.0.0.1:9000/img``

**Comment by harshavardhana** [comment]
> mc mirror I:\pictures\rac1 http://127.0.0.1:9000/img

mirror is recursive by default.

**Comment by harshavardhana** [comment]
This is working as designed, closing the issue. Please re-open if you want to change this behavior.
