### ISSUE TITLE
v2 signature: resource path for bucket should have form /bucketName/ (terminted by slash)

### ISSUE THREAD

**Issue by akiradeveloper** [minio/mc#1579]
I think mc is incorrect in v2 signature because in its StringToSign it has the wrong resource path for buckets.

It is now "/bucketName" but should be "/bucketName/"

such as 

* /johnsmith/
* /johnsmith/?acl

in the examples (http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html).

**Comment by harshavardhana** [comment]
> I think mc is incorrect in v2 signature because in its StringToSign it has the wrong resource path for buckets.

While the examples dictate as such, there is no hard requirement on should a bucket have a '/' or not '/' - for example as shown below with signature version '2'. 

```
$ mc access --debug get s3/t.-1
mc: <DEBUG> GET /t.-1?location= HTTP/1.1
Host: s3.amazonaws.com
User-Agent: Minio (darwin; amd64) minio-go/0.2.5 mc/2016-01-24T07:51:08Z
Authorization: AWS **REDACTED**:**REDACTED**
Date: Sun, 24 Jan 2016 23:59:25 GMT
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Sun, 24 Jan 2016 23:59:25 GMT
Server: AmazonS3
X-Amz-Id-2: iJjXO2Io7XivlSthQzb66UeaQCx5iHFNvctCc3u/IEz5Y17c3S3qTPGcSiE6fSxx
X-Amz-Request-Id: B63138E9707BD4D0

mc: <DEBUG> Response Time:  470.458747ms

mc: <DEBUG> GET /t.-1?acl= HTTP/1.1
Host: s3.amazonaws.com
User-Agent: Minio (darwin; amd64) minio-go/0.2.5 mc/2016-01-24T07:51:08Z
Authorization: AWS **REDACTED**:**REDACTED**
Date: Sun, 24 Jan 2016 23:59:26 GMT
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Sun, 24 Jan 2016 23:59:25 GMT
Server: AmazonS3
X-Amz-Id-2: oZJlcR+TN6Tr4oBqiZRlITukYIuPp1yv30HLf0+KMbRK7YdWAdFz6UAzlysxXTou
X-Amz-Request-Id: 0E781F0170818AE1

mc: <DEBUG> Response Time:  127.573695ms

Access permission for ‘s3/t.-1’ is ‘private’
``` 

Are you facing any issue? @akiradeveloper

**Comment by akiradeveloper** [comment]
@harshavardhana Yes. I am facing a problem. The s3 storage I am developing privately (https://github.com/akiradeveloper/akashic-storage) can't authenticate requests from mc although requests from aws-sdk-java is ok. With a little investigation I found it's due to mc's StringToSign doesn't strictly conform to documents.

You are saying that Amazon's S3 server doesn't care about the StringToSign conform to documents but I think it still should be fixed. That Amazon's S3 tries both slashed and non-slashed StringToSign may be the reason mc is successful now. But if so, the non-slashed path is slow-path and mc can improve performance with the fix.

At least, there is no reason to behave differently from aws-sdk-java.

**Comment by harshavardhana** [comment]
> @harshavardhana Yes. I am facing a problem. The s3 storage I am developing privately (https://github.com/akiradeveloper/akashic-storage) can't authenticate requests from mc although requests from aws-sdk-java is ok. With a little investigation I found it's due to mc's StringToSign doesn't strictly conform to documents.
> You are saying that Amazon's S3 server doesn't care about the StringToSign conform to documents but I think it still should be fixed. That Amazon's S3 tries both slashed and non-slashed StringToSign may be the reason mc is successful now. But if so, the non-slashed path is slow-path and mc can improve performance with the fix.

Okay sure, let me fix this,  It wasn't seen to be a particularly strong requirement. Let me verify if signature version '4' needs this as well. 

Thanks for reporting.

**Comment by akiradeveloper** [comment]
Thanks for the fix.

I am trying to test my software with the latest mc

I am being in trouble please help me.

Now my `/tmp/akashic-storage-mc/config.json` has a config for my akashic-storage.

```
{
        "version": "7",
        "hosts": {
                "akashic-storage": {
                        "url": "http://localhost:10946",
                        "accessKey": "CDQ8WH7DK7M0P7ZE42VW",
                        "secretKey": "6WhxdzjjYZvcpETtlfbUW5CxyeSfNqz7B0olNUV5",
                        "api": "S3v2"
                },
```

but ls with my alias fails. Any idea for this error?

```
$ mc --config-folder=/tmp/akashic-storage-mc ls akashic-storage
mc: <ERROR> Unable to stat ‘akashic-storage’. Requested file ‘akashic-storage’ not found
```

My guess is that `config-folder` option isn't working because `player` is in both `~/.mc` and `/tmp/akashic-storage-mc` and `mc --config-folder=/tmp/akashic-storage-mc ls player` succeeds. But once I remove player from `~/.mc`, the ls starts to fail.

**Comment by akiradeveloper** [comment]
I test without `--config-folder` option (so the config is written to ~/.mc)

I think this issue is nicely fixed. Thanks

**Comment by harshavardhana** [comment]
> My guess is that config-folder option isn't working because player is in both ~/.mc and /tmp/akashic-storage-mc and mc --config-folder=/tmp/akashic-storage-mc ls player succeeds. But once I remove player from ~/.mc, the ls starts to fail.

Let me take a look.
