### ISSUE TITLE
Giving 404 when trying to install mc update

### ISSUE THREAD

**Issue by unixbhaskar** [minio/mc#1581]
Problem: 

bhaskar@Fedora_18:11:39_Mon Jan 25:~> ./mc update

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  New update available, please execute the following command to update: ┃
┃  Download https://dl.minio.io/client/mc/releaselinux-amd64/mc          ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Once I clicked the url mentioned, it went to one of the browser tab and showing "404 Not Found" Please fix it.

**Comment by krishnasrinivas** [comment]
looks like `/` is missing here `releaselinux`

`downloadURL = updateURL + runtime.GOOS`
