### ISSUE TITLE
mc update returns broken url

### ISSUE THREAD

**Issue by molivier** [minio/mc#1589]
I'm testing Minio mc on Mac. mc updater seems to return a broken url for me:

```
$ ./mc version
Version: 2016-01-07T19:33:00Z
Release-tag: OFFICIAL.2016-01-07T19-33-00Z
Commit-id: 7ee79bc960f80687ae111c81b486b4c2112fafba

./mc update

┃  New update available, please execute the following command to update: ┃
┃  Download https://dl.minio.io/client/mc/releasedarwin-amd64/mc         ┃
```

The download url should be `https://dl.minio.io/client/mc/release/darwin-amd64/mc`with an additional slash.

**Comment by harshavardhana** [comment]
> The download url should be https://dl.minio.io/client/mc/release/darwin-amd64/mcwith an additional slash.

We fixed this in current master, thanks for reporting. @molivier

**Comment by molivier** [comment]
Thanks. That's why I couldn't find anything in source code. Next time I'll use master branch for testing. Best regards.
