### ISSUE TITLE
question about diff

### ISSUE THREAD

**Issue by joeblew99** [minio/mc#1593]
i am using json output, from the diff command.
But i want to do a diff and then parse the JSON, and then tell MC what to copy where.

What status possibilities are there in the JSON i wonder ?
I only get only-in-first", which is the local dir, even though i knwo there are some files that are exactly the same on both side. Maybe you ignore equals on both side ?

Also i could use the golang lib too it seems.
? Use the golang code to do it, but i did not see any diff command, but it seems you have some stats, and so from that i can easily write some code to work out the diff and then do a push pull.

thanks in advance !!

{"status":"success","first":"/Users/apple/workspace/go/src/bitbucket.org/app/toolbin/terraform/v0.6.8_windows_amd64/terraform-provisioner-remote-exec.exe","second":"https://s3.amazonaws.com/app-dev/terraform/v0.6.8_windows_amd64/terraform-provisioner-remote-exec.exe","diff":"only-in-first"}

**Comment by harshavardhana** [comment]
> What status possibilities are there in the JSON i wonder ?
> I only get only-in-first", which is the local dir, even though i knwo there are some files that are exactly the same on both side. Maybe you ignore equals on both side ?

'mc diff' is at the directory level, i wonder if this is a bug. Can you provide more details?

**Comment by harshavardhana** [comment]
> 'mc diff' is at the directory level, i wonder if this is a bug. Can you provide more details?

@joeblew99 - is this still a problem?
