### ISSUE TITLE
./mc session resume qzRVtAbT’

### ISSUE THREAD

**Issue by joeblew99** [minio/mc#1594]
i also get session not found.

Maybe i need to have MC on my path ?

**Comment by harshavardhana** [comment]
> i also get session not found.

@joeblew99 - we have fixed a bug regarding session handling are you using the latest version available on dl? can you paste more context, any other error message?

**Comment by joeblew99** [comment]
Yes am using latest version.

It does not give any error message. 
Its a 20 GB folder of files, going over a 10 MB/ sec uplink. Saying it will take one hour approx, but always fails after about 1 %.

If there a way to get more logging / errors from mc command line ?

**Comment by harshavardhana** [comment]
> If there a way to get more logging / errors from mc command line ?

Yes @joeblew99 - can you do 'mc --debug' - while transferring the data?

**Comment by joeblew99** [comment]
Ok here we go:


```

..nt/toolbin/consul/.DS_Store: 13.98 MB / 9.21 GB   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  0.15 % 2.89 MB/s 54m20smc: <DEBUG> PUT /appdif-dev/consul/.DS_Store HTTP/1.1
Host: s3.amazonaws.com
User-Agent:  Minio/2015-12-06T01:57:42Z (./mc; darwin; amd64) 
Content-Length: 6148
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160129/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: 68oHzt4GjEkWhksBWNoDlA==
Content-Type: application/octet-stream
X-Amz-Content-Sha256: c0a8cbbb8247cf22d59296a4bb9b1c2ca17d255b6839f8050dec52e4baaa74f9
X-Amz-Date: 20160129T175649Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
mc: <DEBUG> Response Time:  282.46948ms

mc: <DEBUG> GET /appdif-dev?delimiter=&max-uploads=1000&prefix=consul%2Fv0.6.0_darwin_amd64%2Fconsul&uploads= HTTP/1.1
Host: s3.amazonaws.com
User-Agent:  Minio/2015-12-06T01:57:42Z (./mc; darwin; amd64) 
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160129/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160129T175649Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 29 Jan 2016 17:56:51 GMT
Server: AmazonS3
X-Amz-Id-2: TIDWxRVTtYKecW5DQZAu3dNPD8aje1ksSLCLvY+EkrYIqpVc/DAfqkNET/ddwpXZ3eHUmLfvsBQ=
X-Amz-Request-Id: F09B40FC5E509E90

mc: <DEBUG> Response Time:  152.090349ms

mc: <DEBUG> POST /appdif-dev/consul/v0.6.0_darwin_amd64/consul?uploads= HTTP/1.1
Host: s3.amazonaws.com
User-Agent:  Minio/2015-12-06T01:57:42Z (./mc; darwin; amd64) 
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160129/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160129T175650Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Fri, 29 Jan 2016 17:56:51 GMT
Server: AmazonS3
X-Amz-Id-2: 1BgxxXDKww2xOzEBeJb1pLkRC+YkOwrvH10ozTzkHkS26yUTaiwCI/T/SXx8lFGJy1CEfFZ+yh4=
X-Amz-Request-Id: D8FE6018983A81D6

mc: <DEBUG> Response Time:  140.493633ms

.../v0.6.0_darwin_amd64/consul: 32.67 MB / 9.21 GB   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  0.35 % 5.71 MB/s 27m26smc: Session safely terminated. To resume session ‘mc session resume GCuKVfBJ’
gedw99-MacBook-Pro:backend apple$ 


```

**Comment by harshavardhana** [comment]
> Ok here we go:

May be i was not clear previously my bad, "--debug" with the error while transferring data would be helpful to see if the error originated inside minio or is it coming over the network. 

Right now it seems like it is copying files properly. 

Previously with the network errors were you able to test with virtual style rather than path style? Like rather than copying files like this i.e path style.

```
$ mc cp -r https://s3.amazonaws.com/appdif-dev 
```

But with virtual style. 

```
$ mc cp -r https://appdif-dev.s3.amazonaws.com/
```

**Comment by joeblew99** [comment]
ok got it. Its running now.... Let see what it does. Bash script below.

```
# virtual pathing
    $BINARY --debug cp --recursive $DIRROOT https://$S3_BUCKET.$S3_SERVER/
```

**Comment by harshavardhana** [comment]
> $BINARY --debug cp --recursive $DIRROOT https://$S3_BUCKET.$S3_SERVER/

Thanks..

**Comment by joeblew99** [comment]
Ok success - I mean failure :)
It ran for about 50 or 10 minutes i think, and did ok uploading a fair few files.
Below is the terminal output from the last file it tried to upload:

```

../toolbin/mc/darwin_amd64/mc: 116.25 MB / 9.21 GB  ▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  1.23 % 296.79 KB/s 8h55m51smc: <DEBUG> PUT /goxc/v0.18.1_darwin_amd64/goxc?partNumber=3&uploadId=EBLAgkK0U4QqzyKzTEfULSBgjxIlVbdoxlaLDUfMtposnnBw95AbOe0Y2bpvbziKA7exV_er_h2qxnUypSArfM_dOvE_wzS2vYD3cm7naNQLW26i85_Nc9mHOHjfYWnM HTTP/1.1
Host: appdif-dev.s3.amazonaws.com
User-Agent:  Minio/2015-12-06T01:57:42Z (./mc; darwin; amd64) 
Content-Length: 652932
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160130/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: RW5UzDyO7t9hDsZ8tjAVzg==
X-Amz-Content-Sha256: b834c9848fa788b2f8dee3b4f5e9a648575ebfb7adc0f2d07bf17c804f2804c2
X-Amz-Date: 20160130T203253Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
mc: <DEBUG> Response Time:  13.910450896s

mc: <DEBUG> PUT /gof3r/v0.5.0_linux_amd64/gof3r?partNumber=1&uploadId=BhqBdh7yHEgRIWCFZd7ehLOLXzXcB67NQD2FhGSxKQ3hnSqYunLXc1CxHF56inXB5hegBX.GbQ6H.aqR3.VRoKjSQZ9CQ_jdl18btg9vKqke5ZXWWkxlnmQHr6bC53xW HTTP/1.1
Host: appdif-dev.s3.amazonaws.com
User-Agent:  Minio/2015-12-06T01:57:42Z (./mc; darwin; amd64) 
Content-Length: 5242880
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160130/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: NQNW8KOh7WMqzqVAxQdkfQ==
X-Amz-Content-Sha256: e4f7bd7757e0cdbac539e8059d9d1b1c7aceeb2773db5ae0620e79d7e679a676
X-Amz-Date: 20160130T203117Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
mc: <DEBUG> Response Time:  1m52.278197568s

mc: <DEBUG> POST /gof3r/v0.5.0_linux_amd64/gof3r?uploadId=BhqBdh7yHEgRIWCFZd7ehLOLXzXcB67NQD2FhGSxKQ3hnSqYunLXc1CxHF56inXB5hegBX.GbQ6H.aqR3.VRoKjSQZ9CQ_jdl18btg9vKqke5ZXWWkxlnmQHr6bC53xW HTTP/1.1
Host: appdif-dev.s3.amazonaws.com
User-Agent:  Minio/2015-12-06T01:57:42Z (./mc; darwin; amd64) 
Content-Length: 383
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160130/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: 58c5ee50f8caf3fe5872f4172b84e74022606f2259783ac3d8a57558dbfa6ec9
X-Amz-Date: 20160130T203310Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Sat, 30 Jan 2016 20:33:10 GMT
Server: AmazonS3
X-Amz-Id-2: TQiAa1vlduMRwAxGBaCrBg8H4dk6oYT3dUf4Lhb9t2dCk4rH09fTDepLYrrER3H0YD1UokQpNh8=
X-Amz-Request-Id: 193DD727287FDEB3

mc: <DEBUG> Response Time:  160.795216ms

mc: <ERROR> Failed to copy ‘/Users/apple/workspace/go/src/bitbucket.org/apparently_different/toolbin/mc/linux_amd64/mc’. EOF
 (5) cp-main.go:327 main.doCopySession.func1(..) Tags: [/Users/apple/workspace/go/src/bitbucket.org/apparently_different/toolbin/mc/linux_amd64/mc]
 (4) cp-main.go:181 main.doCopy(..) Tags: [https://appdif-dev.s3.amazonaws.com/mc/linux_amd64/mc]
 (3) common-methods.go:63 main.putTarget(..) Tags: [https://appdif-dev.s3.amazonaws.com/mc/linux_amd64/mc]
 (2) url.go:63 main.url2Client(..) Tags: [https://appdif-dev.s3.amazonaws.com/mc/linux_amd64/mc]
 (1) common-methods.go:100 main.getNewClient(..) Tags: [https://appdif-dev.s3.amazonaws.com/mc/linux_amd64/mc]
 (0) pkg/client/s3/s3.go:71 s3.New(..)
 Release-Tag:OFFICIAL.2015-12-06T01-57-42Z | Commit:9fed1d73eed0 | Host:gedw99-MacBook-Pro.local | OS:darwin | Arch:amd64 | Lang:go1.5.1 | Mem:11MB/47MB | Heap:11MB/42MB
mc: Session safely terminated. To resume session ‘mc session resume CVqlAOqU’
gedw99-MacBook-Pro:backend apple$ 

```

**Comment by joeblew99** [comment]
I just tired ti resume function. It is running now, unlike last time. Maybe the virtual paths makes it much happier.

**Comment by joeblew99** [comment]
mc is using 12 MB nd 11 threads on my osx.
It seems to be using a thread per file its uploads ? just guessing from the number of files i see it working on in my terminal to the thread number i see.

**Comment by joeblew99** [comment]
whats quite funny is that the file it failed on is the mc binary file. 
The mc binary i am using to run the script is a copy, before you ask about locking.
just spooky co-incidence i guess ??

**Comment by harshavardhana** [comment]
> whats quite funny is that the file it failed on is the mc binary file. 
> The mc binary i am using to run the script is a copy, before you ask about locking.
> just spooky co-incidence i guess ??

On linux and darwin operating systems that is not an issue. File can be read by multiple threads, there is no locking. The EOF happened not because of that s3 on a regular basis throttles connections and large uploads coming its way.

**Comment by joeblew99** [comment]
whats weird is that the bucket is specified as Frankfurt, but the terminal debug says "us east"

```

.../toolbin/mc/darwin_amd64/mc: 116.25 MB / 9.21 GB  ▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  1.23 % 296.79 KB/s 8h55m51smc: <DEBUG> PUT /goxc/v0.18.1_darwin_amd64/goxc?partNumber=3&uploadId=EBLAgkK0U4QqzyKzTEfULSBgjxIlVbdoxlaLDUfMtposnnBw95AbOe0Y2bpvbziKA7exV_er_h2qxnUypSArfM_dOvE_wzS2vYD3cm7naNQLW26i85_Nc9mHOHjfYWnM HTTP/1.1
Host: appdif-dev.s3.amazonaws.com
User-Agent:  Minio/2015-12-06T01:57:42Z (./mc; darwin; amd64) 
Content-Length: 652932
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160130/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: RW5UzDyO7t9hDsZ8tjAVzg==
X-Amz-Content-Sha256: b834c9848fa788b2f8dee3b4f5e9a648575ebfb7adc0f2d07bf17c804f2804c2
X-Amz-Date: 20160130T203253Z
Accept-Encoding: gzip

```

**Comment by harshavardhana** [comment]
> mc is using 12 MB nd 11 threads on my osx.
> It seems to be using a thread per file its uploads ? just guessing from the number of files i see it working on in my terminal to the thread number i see.

Yes the version you are using uploads in parallel depending on number of CPUs, we have removed that functionality to keep the code simpler in the current code base.  Parallel uploads can leads to issues with session management etc.

**Comment by harshavardhana** [comment]
> whats weird is that the bucket is specified as Frankfurt, but the terminal debug says "us east"

Most probably the bucket is not in frankfurt , was this bucket created from aws console? or 'mc' ?

**Comment by joeblew99** [comment]
console

**Comment by joeblew99** [comment]
i can kill it and do it from console as a test if needed.... Its 10 GB but well its just light wasted in optics. no kittens hurt

**Comment by harshavardhana** [comment]
> I just tired ti resume function. It is running now, unlike last time. Maybe the virtual paths makes it much happier.

Not necessarily, i think i know the resume problem you saw. It is related to parallel uploads and a the combination of those races. We fixed the problem in our current repo to make overall flow serial, will be making a new release coming week.

**Comment by harshavardhana** [comment]
> i can kill it and do it from console as a test if needed.... Its 10 GB but well its just light wasted in optics. no kittens hurt

No don't delete and re-create, can you verify from aws console that your bucket is in frankfurt?

**Comment by joeblew99** [comment]
i did verify it 1 minute ago. definitly in Frankfurt

**Comment by joeblew99** [comment]
so i guess i wait for your next release...

can you do me a favour. in the golang lib repo of yours, i raised an issue regarding Sync. The APi has no sync, but you that ok, because you have stats, so from the stats i can work out what to sync and which way (upload or download). 
i need to be able to sync UP or down. 
It will work for me, because no one is working on the files during the sync, so there wil be no recursive state clashes etc. Like when you loop a collection, and change it as the same time :)

**Comment by harshavardhana** [comment]
> can you do me a favour. in the golang lib repo of yours, i raised an issue regarding Sync. The APi has no sync, but you that ok, because you have stats, so from the stats i can work out what to sync and which way (upload or download). 
> i need to be able to sync UP or down. 
> It will work for me, because no one is working on the files during the sync, so there wil be no recursive state clashes etc. Like when you loop a collection, and change it as the same time :)

Does 'mc mirror' work for your needs? why do you need to implement your own?

**Comment by harshavardhana** [comment]
> i did verify it 1 minute ago. definitly in Frankfurt

Hmm that is odd even previously path style it said 'us-east-1'  - So clearly bucket is not in Frankfurt region.  Path styles will not work if the region is set to 'us-east-1' if the buckets reside in different regions.

**Comment by joeblew99** [comment]
did not know mc mirror existed !! ah so dumb :)
so it will work out what the deltas are on each soe and just move files in each direcion ?
Of course just on file dateTime stamp.

I need to be able to run mirror from MC; but ALSO from the library though too. Hence why i raised this in the golang lib repo.

regarrding the AMZ east aspect... I screwd up sorry . Its US standard:
Bucket:	appdif-dev
Region:	US Standard

**Comment by harshavardhana** [comment]
> regarding the AMZ east aspect... I screwed up sorry; its US standard:
> Bucket: appdif-dev
> Region: US Standard

Yeah its a common problem of US Standard,  you should create a region based bucket. So that you can use end point directly. We are going to introduce retry mechanism in minio-go library which should transparently retry these type of network errors which are common for s3 buckets.

**Comment by harshavardhana** [comment]
> I need to be able to run mirror from MC; but ALSO from the library though too. Hence why i raised this in the golang lib repo.

No library doesn't provide that functionality.  'mirror' is a higher level functionality so it is implemented at 'mc' level.

**Comment by harshavardhana** [comment]
> did not know mc mirror existed !! ah so dumb :)
> so it will work out what the deltas are on each soe and just move files in each direcion ?
> Of course just on file dateTime stamp.

`mc mirror` is just like 'mc cp' but it will not copy already uploaded files which match size and name in the destination. If the size differs it still doesn't overwrite but you can use '--force' to overwrite, for files which are not fully uploaded - for example files larger than '5MB' are resumed automatically using multipart.

**Comment by joeblew99** [comment]
Thanks for the explanation.

So, for my use case, i need to push files to s3 that me and my dev team use every day. Other team members also change the files too.
It's our binary github if you will.
So if I fully get it, this is the correct usage below ?

So when I make a change I do :
mc mirror localpath s3path

So when I want to check if someone else mad a change on s3 I do:
mc mirror s3path localparh

Thanks heaps for your help on this BTW. You were Glusterfs team in a previous life ?

**Comment by harshavardhana** [comment]
> So, for my use case, i need to push files to s3 that me and my dev team use every day. Other team members also change the files too.
> It's our binary github if you will.
> So if I fully get it, this is the correct usage below ?
> 
> So when I make a change I do :
> mc mirror localpath s3path
> 

Yes that is correct. This is the most expected use case. 

> So when I want to check if someone else mad a change on s3 I do:
> mc mirror s3path localparh

Yes, just to check you can use 'mc diff' - 'mc diff' is exactly similar to 'mc mirror' without copying files. 

> 
> Thanks heaps for your help on this BTW. You were Glusterfs team in a previous life ?

Yes we were :-)

**Comment by joeblew99** [comment]
i made all the changes to the script and ran:

./mc mirror $DIRROOT https://$S3_BUCKET.$S3_SERVER_DOMAIN/

Now i got:
```
mc: <ERROR> Failed to mirror ‘/Users/apple/workspace/go/src/bitbucket.org/apparently_different/toolbin/os-windows/Git-2.7.0-64-bit.exe’. Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
```

I did not turn on debugging.
I guess its the threading again.

If you want me to run it with debugging i can.

**Comment by joeblew99** [comment]
with --debug:

```

...nglishInternational_x64.iso: 209.28 MB / 9.08 GB  ▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  2.25 % 1.15 MB/s 2h11m19smc: <DEBUG> PUT /appdif-dev/os-windows/Git-2.7.0-64-bit.exe?partNumber=3&uploadId=yB.Qi.VEq5Tkre7nrsaATdfL4jaZEJHHHZjMc43Eo8KEKpwRdPNzoL73zky3FGsI6XAydwGCWRwNclK0sWA.f5Ofuve_dHjHtcmnpk4yqvljnmOi3yhCQOpyaToJf0vS HTTP/1.1
Host: s3.amazonaws.com
User-Agent:  Minio/2015-12-06T01:57:42Z (./mc; darwin; amd64) 
Content-Length: 5242880
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160131/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: ngZACtfNmbwqY4OVVP8A6g==
X-Amz-Content-Sha256: 0ab7f5cd4f05969177110d425d98b2608390e40a868a80a4ddd5a8218f17881d
X-Amz-Date: 20160131T002506Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Sun, 31 Jan 2016 00:27:57 GMT
Server: AmazonS3
X-Amz-Id-2: D4dnhCsWKGb0GDbNU74NVK25kOpR7vIIph/vIu/5QnNfK8f+PDJ9/PFNy4CNMCufq5l04LG8jkI=
X-Amz-Request-Id: 837A2A83FE01699A

mc: <DEBUG> Response Time:  3m1.683850998s

mc: <ERROR> Failed to mirror ‘/Users/apple/workspace/go/src/bitbucket.org/apparently_different/toolbin/os-windows/Git-2.7.0-64-bit.exe’. Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
 (3) mirror-main.go:309 main.doMirrorSession.func1(..)
 (2) mirror-main.go:172 main.doMirror(..) Tags: [https://s3.amazonaws.com/appdif-dev/os-windows/Git-2.7.0-64-bit.exe]
 (1) common-methods.go:68 main.putTarget(..) Tags: [https://s3.amazonaws.com/appdif-dev/os-windows/Git-2.7.0-64-bit.exe]
 (0) pkg/client/s3/s3.go:184 s3.(*s3Client).Put(..)
 Release-Tag:OFFICIAL.2015-12-06T01-57-42Z | Commit:9fed1d73eed0 | Host:gedw99-MacBook-Pro.local | OS:darwin | Arch:amd64 | Lang:go1.5.1 | Mem:11MB/41MB | Heap:11MB/36MB
mc: Session safely terminated. To resume session ‘mc session resume zjhXwSls’
gedw99-MacBook-Pro:backend apple$ 

```

**Comment by harshavardhana** [comment]
> mc: <ERROR> Failed to mirror ‘/Users/apple/workspace/go/src/bitbucket.org/apparently_different/toolbin/os-windows/Git-2.7.0-64-bit.exe’. Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.

This is our bug, can you paste your 'mc' version?

**Comment by joeblew99** [comment]
./mc version
Version: 2015-12-06T01:57:42Z
Release-tag: OFFICIAL.2015-12-06T01-57-42Z
Commit-id: 9fed1d73eed07adf4406b5bc7cbdac58243a4629

**Comment by joeblew99** [comment]
./mc update
You are already running the most recent version of ‘mc’.

**Comment by joeblew99** [comment]
Shall i close this bug, or do you want to leave it open ?
I am happy to retry this stuff this once you do another release.

**Comment by harshavardhana** [comment]
> Shall i close this bug, or do you want to leave it open ?
> I am happy to retry this stuff this once you do another release.

We will keep this open.

**Comment by harshavardhana** [comment]
> I am happy to retry this stuff this once you do another release.

Can you retry now - we made a new release.

**Comment by joeblew99** [comment]
Will get a chance next week. Away at moment

**Comment by harshavardhana** [comment]
> Will get a chance next week. Away at moment

This bug is fixed. closing - please reopen if you observe it again.
