### ISSUE TITLE
Does not compile on Illumos distributions (and probably Solaris)

### ISSUE THREAD

**Issue by jblachly** [minio/mc#1603]
Illumos (formerly OpenSolaris) based distributions are becoming more popular because of built in ZFS, DTrace, etc. However, Illumos does not have an ioctl syscall.

mc will not compile on Illumos due to use of syscall.SYS_IOCTL (and probably also syscall.TIOCGETA). Unfortunately one of your dependencies (olekukonko/ts) also uses syscall.SYS_IOCTL.

```
# go get github.com/minio/mc
# github.com/olekukonko/ts
root/go/src/github.com/olekukonko/ts/ts_x.go:19: undefined: syscall.SYS_IOCTL
# github.com/minio/pb
root/go/src/github.com/minio/pb/pb_x.go:65: undefined: syscall.SYS_IOCTL
root/go/src/github.com/minio/pb/pb_x.go:74: undefined: syscall.SYS_IOCTL
root/go/src/github.com/minio/pb/pb_x.go:91: undefined: syscall.SYS_IOCTL
root/go/src/github.com/minio/pb/termios_bsd.go:7: undefined: syscall.TIOCGETA
root/go/src/github.com/minio/pb/termios_bsd.go:8: undefined: syscall.TIOCSETA
# github.com/minio/mc/pkg/client/s3
root/go/src/github.com/minio/mc/pkg/client/s3/s3.go:42: undefined: minio.CloudStorageClient
```

System information:
```
# uname -a
SunOS smartos-dev 5.11 joyent_20160121T174331Z i86pc i386 i86pc Solaris
```

**Comment by harshavardhana** [comment]
> # go get github.com/minio/mc
> # github.com/olekukonko/ts
> root/go/src/github.com/olekukonko/ts/ts_x.go:19: undefined: syscall.SYS_IOCTL
> # github.com/minio/pb
> root/go/src/github.com/minio/pb/pb_x.go:65: undefined: syscall.SYS_IOCTL
> root/go/src/github.com/minio/pb/pb_x.go:74: undefined: syscall.SYS_IOCTL
> root/go/src/github.com/minio/pb/pb_x.go:91: undefined: syscall.SYS_IOCTL
> root/go/src/github.com/minio/pb/termios_bsd.go:7: undefined: syscall.TIOCGETA
> root/go/src/github.com/minio/pb/termios_bsd.go:8: undefined: syscall.TIOCSETA
> # github.com/minio/mc/pkg/client/s3

We will have to fix the upstream packages for this to be handled, keeping this bug for future.

**Comment by harshavardhana** [comment]
@jblachly - can you test this patch - https://github.com/minio/mc/pull/1606  and validate on your Solaris machine?

**Comment by jblachly** [comment]
I tested and the build works great. Thanks for hammering that out so quickly!

However, there are a couple of problems.

First, and super minor, I did discover two bugs in your build scripts. 

1. In checkdeps.sh , the code evaluating whether the operating system examines the first part of $(uname -sm). Presently, it checks for Linux and Darwin and with your patch, Solaris. This should be SunOS ; both illumos as well as Oracle Solaris issue "SunOS" in response to uname -s

2. in checkdeps.sh , this didn't actually fail on my system amazingly because the code evaluating this never hits the 'exit 1'. I am not sure why this is. When comparing with the check_supported_arch function I notice you don't have a 'local os' and an if block after the esac.  So, no matter what uname -s reports, checkdeps.sh continues on its merry way. I only caught this by co-incidence.

3. mc compiles and runs, but after printing the version string hangs the terminal (or if logged into illumos/solaris zone with zlogin disconnects from the pty) 

In the last case, I narrowed this down to the range pipeline in the help template
```
{{range $key, $value := ExtraInfo}}
{{$key}}:
  {{$value}}
```

I note that in your patch `app.ExtraInfo` is now resulted from `pb.TerminalWidth` instead of `ts.GetSize`, but I am a Go novice and it's not clear to me if these functions are called lazily at the time the pipeline references ExtraInfo's key/values, or if they are called right away in main() as I expect; if the latter I am not sure how the template is hanging the terminal.

Anyway thank you again for working so quickly on this; I am tickled it now works on illumos (I am using smartos, but I am sure omnios, OpenIndiana, and other illumos distribution users will be thrilled as well)

**Comment by jblachly** [comment]
Ah, looks like bigger problem with `pb` -- although I tested by listing files on play and S3, copying in either direction hangs the terminal (or closes the connection to zone fi using zlogin) after printing filename: 0 B / size 0.00%

**Comment by harshavardhana** [comment]
> Ah, looks like bigger problem with pb -- although I tested by listing files on play and S3, copying in either direction hangs the terminal (or closes the connection to zone fi using zlogin) after printing filename: 0 B / size 0.00%

Yes this is what i wanted to know progress bar needs some work along with color printing. 

> In the last case, I narrowed this down to the range pipeline in the help template
> 
> {{range $key, $value := ExtraInfo}}
> {{$key}}:
>   {{$value}}
> I note that in your patch app.ExtraInfo is now resulted from pb.TerminalWidth instead of ts.GetSize, but I am a Go novice and it's not clear to me if these functions are called lazily at the time the pipeline references ExtraInfo's key/values, or if they are called right away in main() as I expect; if the latter I am not sure how the template is hanging the terminal.
> 

Yes that is because ts.GetSize() is not supported on Solaris, so i had to add code into progress bar to make it work and avoid the 'ts' dependency, since the upstream development has stopped.  It is hanging because it is writing some special terminal characters which are not supported. ANSI escape sequences might have different meaning altogether on Solaris. So it would require some work. 

Can you test with '--no-color' ? and see if that helps. 

> Anyway thank you again for working so quickly on this; I am tickled it now works on illumos (I am using smartos, but I am sure omnios, OpenIndiana, and other illumos distribution users will be thrilled as well)

No problem, we are excited to see this work for you as well :-). 

> Ah, looks like bigger problem with pb -- although I tested by listing files on play and S3, copying in either direction hangs the terminal (or closes the connection to zone fi using zlogin) after printing filename: 0 B / size 0.00%

This i need to see why it doesn't progress, i tried copying files locally from /usr/bin to test worked fine.  But it is the same problem of coloring which would largely cause more problems. 

Will test and report back.  Thanks for taking time and testing this.

**Comment by jblachly** [comment]
Unrelated to color -- even with the --no-color flag, the terminal hangs after printing the PB:

```
$ mc --no-color cp s3/bucketname/filename.PDF .
https://s3.amazonaws.com/bucketname/filename.PDF: 0 B / 1.16 GB    0.00 %
[Connection to zone '1e4817c2-9d59-ed14-f3bb-d90cc6439dc5' pts/3 closed]
```

I'll dig in and see what I can figure out on my end, although I am brand-new at Go. If it gets very complicated I could try to set up a illumos VM somewhere for you.

**Comment by jblachly** [comment]
The problem may be upstream - I am completely new to termio(s) programming as well as system calls so forgive my limited understanding.

The terminal freeze is 100% caused by the call to `unix.IoctlGetWinsize(syscall.Stdout, unix.TCSETA)`  in `vendor/github.com/minio/pb/pb_solaris.go`.

When commenting it out and simply returning a fixed width from that function (for example, 160), `mc` functions entirely normally as far as I can tell. **The progress bar looks and works great!**

I then wondered why the syscall being used was `TCSETA` instead of `TCGETA` (since we are trying to get a property not set a property). Unfortunately, changing it to `unix.TCGETA` causes a runtime panic and abort, even if the value is never used:

```
        _, err = unix.IoctlGetWinsize(syscall.Stdout, unix.TCGETA)
        //width = int(ws.Col)
        width = 160
        return width, err
```

**Comment by harshavardhana** [comment]
> I then wondered why the syscall being used was TCSETA instead of TCGETA (since we are trying to get a property not set a property). Unfortunately, changing it to unix.TCGETA causes a runtime panic and abort, even if the value is never used:

The syscall is correct TCSETA is for pulling the terminfo values to a pointer structure,  TCGETA means that terminal takes the value.  They are inverse of the meaning they infer from their names.

Looks like the ``unix.IoctlGetWinsize(syscall.Stdout, unix.TCSETA)`` hang is a Golang bug related to how the zones are managed on Solaris as below. 

> [Connection to zone '1e4817c2-9d59-ed14-f3bb-d90cc6439dc5' pts/3 closed]

Let me make the code simplers and return back a 80x25 value for Row and Cols.

**Comment by jblachly** [comment]
I think that is a reasonable workaround for now. I have learned from all of this that there is active discussion in the go community about making a platform independent (not exposing ioctls) term module once and for all but this probably won't be ready for another few Go versions.

To be clear, it only closes the connection when I am logged into the zone through teh global zone with `zlogin`; zones are effectively their own lightweight virtual machine, and if I ssh into the zone directly, the terminal hangs, instead of closing. 

Anyway, definitely upstream problem - thank you for helping with this.

**Comment by harshavardhana** [comment]
> To be clear, it only closes the connection when I am logged into the zone through teh global zone with zlogin; zones are effectively their own lightweight virtual machine, and if I ssh into the zone directly, the terminal hangs, instead of closing.

Thanks for your time, you have been really helpful in testing this.  Let me make that change.

**Comment by harshavardhana** [comment]
> I then wondered why the syscall being used was TCSETA instead of TCGETA (since we are trying to get a property not set a property). Unfortunately, changing it to unix.TCGETA causes a runtime panic and abort, even if the value is never used:
> 
>         _, err = unix.IoctlGetWinsize(syscall.Stdout, unix.TCGETA)
>         //width = int(ws.Col)
>         width = 160
>         return width, err

One possible fix if you want to try

```
var winSize unix.Winsize
err := unix.IoctlSetWinsize(int(fd), unix.TCGETA, &winSize)
return int(winSize.Col), err
``` 

Can you try this on your end?

**Comment by jblachly** [comment]
No dice, panic.

I talked to some illumos kernel guys on IRC and they think that Solaris may have diverged from illumos here in terms of termio struct being uint16_t while illumos termios is based on unsigned int. Golang desperately needs better platform independent terminal support. There is no way you should be making ioctls to draw a progress bar :|

I'll dive in with kernel debugging tools at some point ; I think setting fixed width under Solaris and derivatives is reasonable solution in the meantime.

**Comment by jblachly** [comment]
I should add that I also used as the first parameter int(tty.Fd()) after calling tty = open('/dev/tty') (as in the pb_x.go) as that was not in the Solaris version. Still nothing.

**Comment by harshavardhana** [comment]
From what I am able to gather setting terminal width to a lower bound will provide a good solution. Thanks for the inputs. There is an independent effort going on in upstream golang i.e golang.org/x/sys/unix

**Comment by harshavardhana** [comment]
But I guess it's still not ready to be usable.

**Comment by harshavardhana** [comment]
> I should add that I also used as the first parameter int(tty.Fd()) after calling tty = open('/dev/tty') (as in the pb_x.go) as that was not in the Solaris version. Still nothing.

Looks like this is what we need to do 

http://src.illumos.org/source/xref/illumos-gate/usr/src/cmd/ttymon/sttyparse.c#winsize
```
394	if (ioctl(fd, TIOCGWINSZ, winsize) == 0)
395		term |= WINDOW;
``

We are using wrong parameters to get this information and i see the pb_x.go - already does this, so a solaris specific code is not needed.

**Comment by harshavardhana** [comment]
> Looks like this is what we need to do
> 
> http://src.illumos.org/source/xref/illumos-gate/usr/src/cmd/ttymon/sttyparse.c#winsize
> 
> 394 if (ioctl(fd, TIOCGWINSZ, winsize) == 0)
> 395     term |= WINDOW;
> We are using wrong parameters to get this information and i see the pb_x.go - already does this, so a solaris specific code is not needed.

@jblachly - was able to fix the terminal issues, looks like now things are working fine.  Can you try the latest patch?

**Comment by jblachly** [comment]
It works great!

I notice the IOCTL syscall is now hardcoded == 54. I talked with some Illumos folks again on IRC and they reminded me that the system call table is not guaranteed to be stable and that the preferred method (i.e., will guarantee binary portability) in SunOS5 family OSes is to interface with libc.

I found package "runtime" syscall_solaris.go has a function syscall_ioctl(fd, req, arg uintptr) which I think will be the stable way to make ioctl syscalls. 

I think you can close this issue and merge for now; I will try my hand at modifying "pb" to use Solaris syscall_ioctl for portability and open a pull request =)

Thank you again

**Comment by harshavardhana** [comment]
> I notice the IOCTL syscall is now hardcoded == 54. I talked with some Illumos folks again on IRC and they reminded me that the system call table is not guaranteed to be stable and that the preferred method (i.e., will guarantee binary portability) in SunOS5 family OSes is to interface with libc.

That was because i looked at the IOCTL table, didn't know that it will be changed in the future. The golang.org/x/sys/unix has this pretty much standardized the libc binding. 

Also it's a bad idea that to not keep IOCTL stable, since it would break a lot of applications. 

> I found package "runtime" syscall_solaris.go has a function syscall_ioctl(fd, req, arg uintptr) which I think will be the stable way to make ioctl syscalls.

syscall_ioctl is not exposed that is what they are trying to fix in golang.org/x/sys/unix , it is little tricky and one shouldn't mess with this since the illuminos kernel has changed a lot underneath.

**Comment by harshavardhana** [comment]
We are ready to merge.
