### ISSUE TITLE
ls shows nothing or just few files of folder

### ISSUE THREAD

**Issue by nohitall** [minio/mc#1608]
Hi. trying minion locally. Sometimes I get 0 output on ls, sometimes it shows 2-3 files of 50+ in the folder but with 0 bytes e.g. In this case Downloads folder. Furthermore what I realized a) minion ignores uppercase files/folders b) filenames in ls output != original filenames, missing special chars + upper/lower case issues
Linux tp 4.3.3-2-ARCH 

no@tp ~/Downloads> ./mc ls me 
[2016-01-15 16:38:01 CET]     0B human.2015.720p.bluray.x264.aac-etrg/
[2016-01-28 18:15:58 CET]     0B cdist/

**with debug**

no@tp ~/Downloads> ./mc ls me --debug
mc: <DEBUG> GET / HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: Minio (linux; amd64) minio-go/0.2.5 mc/2016-02-08T02:14:28Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160215/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160215T174437Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Mon, 15 Feb 2016 17:44:37 GMT
Server: Minio/OFFICIAL.2016-02-08T00-13-49Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: JBRN749F38Z9NPNC

mc: <DEBUG> Response Time:  3.533054ms

mc: <DEBUG> GET / HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: Minio (linux; amd64) minio-go/0.2.5 mc/2016-02-08T02:14:28Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160215/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160215T174437Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Mon, 15 Feb 2016 17:44:37 GMT
Server: Minio/OFFICIAL.2016-02-08T00-13-49Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 509VI7CL019BVEM7

mc: <DEBUG> Response Time:  2.604544ms

**Comment by harshavardhana** [comment]
> Hi. trying minion locally. Sometimes I get 0 output on ls, sometimes it shows 2-3 files of 50+ in the folder but with 0 bytes e.g. In this case Downloads folder. Furthermore what I realized a) minion ignores uppercase files/folders b) filenames in ls output != original filenames, missing special chars + upper/lower case issues
> Linux tp 4.3.3-2-ARCH
> 
> no@tp ~/Downloads> ./mc ls me 
> [2016-01-15 16:38:01 CET] 0B human.2015.720p.bluray.x264.aac-etrg/
> [2016-01-28 18:15:58 CET] 0B cdist/

Top level directories are buckets and buckets have restrictions regarding their names 

- special characters are not supported
- upper case letters are not supported
- all top level files are ignored at <path>.

So we filter them out pro-actively, but they should be consistent in terms of their output. Can you paste outputs of two to three runs and also provide me the 'directory names' that you have at the top level by doing 'mc ls <local_path>'  ?

Thanks.

**Comment by nohitall** [comment]
Well I am trying this:
./minio server /home/no/TEMP/

no@tp ~/Downloads> ./mc ls me
produces nothing

output should be:
$buckets.json
deadbeef-static_devel-1_x86_64/
IMGP5681.jpg
$multiparts-session.json
Programming the Universe (Seth Lloyd) Retail epub mobi PDF [Itzy]/
TESTFILE
tresorsit_backup/
VegaBuild-linux.gtk.x86_64/

mc ls procudes the correct ls of the folder it is placed in, I rather not copy my whole Downloads content here :)

**Comment by harshavardhana** [comment]
> Well I am trying this:
> ./minio server /home/no/TEMP/
> 
> no@tp ~/Downloads> ./mc ls me
> produces nothing
> 
> output should be:
> $buckets.json
> deadbeef-static_devel-1_x86_64/
> IMGP5681.jpg
> $multiparts-session.json
> Programming the Universe (Seth Lloyd) Retail epub mobi PDF [Itzy]/
> TESTFILE
> tresorsit_backup/
> VegaBuild-linux.gtk.x86_64/

This the correct behavior for minio server. 

- files are ignored since top level can only be buckets (buckets are directories)
- directories cannot have special characters like "_" - is not supported for buckets. 
- directories cannot have " " in them as well - is not supported for buckets. 

So that is why you don't see any buckets being listed from top level, since they don't comply with S3 protocol bucket naming convention. This restriction only applies to buckets not for object names. 

Object names can be UTF-8 character which are supported. 

Here is an example 

```$ minio server ~/testdir``

```
$ mc ls localhost/
[2016-02-13 16:54:48 PST]     0B 1222/
[2016-02-06 04:23:31 PST]     0B 323123/
[2016-02-06 07:05:00 PST]     0B parallels/
```

```
$ mc cp test localhost/1222/本語.txt
$ mc ls localhost/1222/
[2016-02-13 16:54:48 PST] 1.0GiB bigfile
[2016-02-13 16:26:51 PST]  12MiB bigfile.12MB
[2016-02-13 16:44:25 PST] 500MiB bigfile.500MB
[2016-02-13 16:44:37 PST] 800MiB bigfile.800MB
[2016-02-15 02:50:21 PST]     0B 本語.txt
```

**Comment by nohitall** [comment]
Ah ok, understood. Thanks
