### ISSUE TITLE
Failure to pipe google cloud storage using `cat filename | minio pipe google/...`

### ISSUE THREAD

**Issue by yoavlt** [minio/mc#1610]
It had been succeeded to upload to google cloud storage. But when I upgraded to latest minio client, it failed. Why did it occur?

**Comment by harshavardhana** [comment]
> It had been succeeded to upload to google cloud storage. But when I upgraded to latest minio client, it failed. Why did it occur?

'mc pipe' will not work with new version to 'Google Cloud Storage' . Google Cloud Storage is not S3 compatible with their multipart API.

**Comment by yoavlt** [comment]
Thank you for your reply! Are you willing to support it in the future?

**Comment by harshavardhana** [comment]
> Thank you for your reply! Are you willing to support it in the future?

Yes if Google Cloud Storage implements S3 compatible multipart API then we will work transparently.

**Comment by yoavlt** [comment]
OK. I will request GCP sales staff tomorrow! :+1:
