### ISSUE TITLE
Can't use alternate config file location using --config-file

### ISSUE THREAD

**Issue by LaurieReeves** [minio/mc#1611]
When specifying an alternative config file location using --config-folder/-C, the configuration there is ignored and the default is always used (~/.mc).

However, the "config host add" command *is* able to write to the specified config path, but further commands cannot access it.

Some examples:
```
$ rm -rf ~/.mc
$ ./mc -C ./c ls play
mc: <ERROR> Unable to access configuration file. Invalid arguments provided, cannot proceed.
$ ./mc ls play
mc: Configuration written to ‘/home/laurie/.mc/config.json’. Please update your access credentials.
[...]
$ ./mc -C ./c config host add example http://s3.amazonaws.com XXXXXXXXXXXXXXXXXXXX xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Added ‘example’ successfully.
$ ./mc -C ./c ls example
mc: <ERROR> Unable to stat ‘example’. Requested file ‘example’ not found
$ grep example ./c/config.json 
		"example": {
$ ./mc ls example
mc: <ERROR> Unable to stat ‘example’. Requested file ‘example’ not found
$ ./mc config host add example http://s3.amazonaws.com XXXXXXXXXXXXXXXXXXXX xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Added ‘example’ successfully.
$ ./mc ls example
mc: <ERROR> Unable to stat ‘example’. The AWS Access Key Id you provided does not exist in our records.
```

Hope that all makes sense. Let me know if not and I can clarify.

**Comment by harshavardhana** [comment]
> When specifying an alternative config file location using --config-folder/-C, the configuration there is ignored and the default is always used (~/.mc).
> 
> However, the "config host add" command is able to write to the specified config path, but further commands cannot access it.

Thanks @LaurieReeves - found the problem fixing it right now.

**Comment by LaurieReeves** [comment]
Seems to be working. Thanks!
