### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by joeblew99** [minio/mc#1619]
I saw that things changed in the Config.

My migrated json config has all the normal stuff plus my own path:

"cloud1": {
			"url": "https://XXX.dev.s3.eu-central-1.amazonaws.com",
			"accessKey": "YYY",
			"secretKey": "ZZZ+H5oJzalXb",
			"api": "S3v4"
		},

Can you let me know what this needs to change to ?

Also the manual way of adding endpoints no longer works ? 

````

bash script i use
function push() {
    echo "## Pushing changes to S3 ##"
    
    ./mc config host add mycloud https://s3.amazonaws.com $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY S3v4
    
    # Make bucket
    #$BINARY mb $S3_SERVER_DOMAIN/$S3_BUCKET/
    
    echo "## Local files ##"
    ls -al $DIRROOT
    
    # copy from local to s3
    #$BINARY --debug cp --recursive $DIRROOT $S3_SERVER_DOMAIN/$S3_BUCKET/
    
    # non-virtual pathing
    $BINARY mirror --debug $DIRROOT $S3_SERVER_DOMAIN/$S3_BUCKET/
}

```

Terminal Output from that:
```

mc: <ERROR> Unable to stat https://s3.amazonaws.com/XXX-dev/ Use ‘mc config host add mycloud https://s3.amazonaws.com/XXX-dev/ ...’ to add an alias. Use the alias for S3 operations.
 (2) mirror-url.go:89 main.checkMirrorSyntax(..) Tags: [https://s3.amazonaws.com/XXX-dev/]
 (1) url.go:184 main.url2Stat(..) Tags: [https://s3.amazonaws.com/XXX-dev/]
 (0) common-methods.go:144 main.newClient(..) Tags: [https://s3.amazonaws.com/XXX-dev/]
 Release-Tag:RELEASE.2016-02-19T04-11-55Z | Commit:54761b22fdcc | Host:x-MacBook-Pro.local | OS:darwin | Arch:amd64 | Lang:go1.6 | Mem:734kB/4.5MB | Heap:734kB/1.7MB

```

**Comment by harshavardhana** [comment]
> "cloud1": {
> "url": "https://XXX.dev.s3.eu-central-1.amazonaws.com",
> "accessKey": "YYY",
> "secretKey": "ZZZ+H5oJzalXb",
> "api": "S3v4"
> },
> 
> Can you let me know what this needs to change to ?
> 

This was chosen after the migration, since there was no alias associated with "https://XXX.dev.s3.eu-central-1.amazonaws.com" it choose a default "cloud1" 

So you if you use "mc ls cloud1" you would get the same functionality as before, if you want to change this to something else then you can add a new alias of your choice. 

> Also the manual way of adding endpoints no longer works ?
> 
> ./mc config host add https://s3.amazonaws.com $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY S3v4

Yes this was deprecated in the new release, no more URL based access is allowed it will be always 'alias' based. This in-turn allowed us to support multiple S3 accounts simultaneously.

**Comment by joeblew99** [comment]
ok thanks i get it ...

**Comment by joeblew99** [comment]
mhh got stuck using the new alias method....

I have my JSON with:
"appdif-s3": {
			"url": "https://appdif.dev.s3.eu-central-1.amazonaws.com",
			"accessKey": "XXX",
			"secretKey": "YYY+H5oJzalXb",
			"api": "S3v4"
		},

then from terminal  i call:

mc ls appdif-s3/appdif-dev/

i get:

The specified bucket does not exist

**Comment by harshavardhana** [comment]
> mhh got stuck using the new alias method....
> 
> I have my JSON with:
> "appdif-s3": {
> "url": "https://appdif.dev.s3.eu-central-1.amazonaws.com",
> "accessKey": "XXX",
> "secretKey": "YYY",
> "api": "S3v4"
> },
> 
> then from terminal i call:
> 
> mc ls appdif-s3/appdif-dev/
> 
> i get:
> 
> The specified bucket does not exist, but it definitely does exist

Your bucket name looks like is 'appdif.dev' not 'appdif-dev' from what i gather from the alias entry. Can you check?

**Comment by harshavardhana** [comment]
> "appdif-s3": {
> "url": "https://appdif.dev.s3.eu-central-1.amazonaws.com",

Also this would make the request directly go to the bucket so perhaps it means that 'appdif.dev' doesn't exist anymore may be you have to change the url to 'appdif-dev.s3.eu-central-1.amazonaws.com'

**Comment by harshavardhana** [comment]
> Also this would make the request directly go to the bucket so perhaps it means that 'appdif.dev' doesn't exist anymore may be you have to change the url to 'appdif-dev.s3.eu-central-1.amazonaws.com'

For example

```
$ mc config host list
myphotos: https://miniocloud.s3.amazonaws.com | <-  xxxxxxxxx, |  xxxxxxxxxxx, |  S3v4
$ mc ls myphotos 
``` 

Lists the contents inside the bucket 'miniocloud' so if you are doing 'mc ls appdif-s3' it is trying to list the contents inside the bucket 'appdif.dev' ..

**Comment by harshavardhana** [comment]
For your exact use case of having bucket names with '.' in them 

```
$ mc config host list
pathstyle: https://my.minio.io.s3.amazonaws.com/ | <- xxxxxxx, |  xxxxxxxxxx, |  S3v4
$ mc ls pathstyle
[2016-02-23 10:25:03 PST]     0B restic/
```

Lists the contents inside 'my.minio.io'
