### ISSUE TITLE
Client.Timeout exceeded while awaiting headers when copying big files

### ISSUE THREAD

**Issue by F21** [minio/mc#1627]
I have the minio server and client both running on my computer locally. I tested copying a big file (2.74GB), but it keeps failing:

```
$ mc cp big.iso myminio/test
...big.iso: 2.74 GB / 2.74 GB [================================================] 100.00 % 12.24 MB/s 0
mc: <ERROR> Failed to copy ‘big.iso’. Post http://localhost:9000/test/big.iso?uploadId=OboTzSL0T4WbRoQZGF_ilixmRj5VDMbqW8lE_93KhDYD72e: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume VhBytFxm’

$ mc session resume VhBytFxm
...big.iso: 2.74 GB / 2.74 GB [===============================================] 100.00 % 100.71 MB/s 0
mc: <ERROR> Failed to copy ‘big.iso’. Post http://localhost:9000/test/big.iso?uploadId=OboTzSL0T4WbRoQZGF_ilixmRj5VDMbqW8lE_93KhDYD72e: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume VhBytFxm’
```

**Comment by harshavardhana** [comment]
> I have the minio server and client both running on my computer locally. I tested copying a big file (2.74GB), but it keeps failing:
> 
> $ mc cp big.iso myminio/test
> ...big.iso: 2.74 GB / 2.74 GB [================================================] 100.00 % 12.24 MB/s 0
> mc: <ERROR> Failed to copy ‘big.iso’. Post http://localhost:9000/test/big.iso?uploadId=OboTzSL0T4WbRoQZGF_ilixmRj5VDMbqW8lE_93KhDYD72e: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> mc: <ERROR> Session safely terminated. To resume session ‘mc session resume VhBytFxm’
> 
> $ mc session resume VhBytFxm
> ...big.iso: 2.74 GB / 2.74 GB [===============================================] 100.00 % 100.71 MB/s 0
> mc: <ERROR> Failed to copy ‘big.iso’. Post http://localhost:9000/test/big.iso?uploadId=OboTzSL0T4WbRoQZGF_ilixmRj5VDMbqW8lE_93KhDYD72e: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> mc: <ERROR> Session safely terminated. To resume session ‘mc session resume VhBytFxm’

This must be related to a recent change in timeouts, What is happening is that the total time taken for multipart to finish and reply back is slower 30secs is not enough.

**Comment by harshavardhana** [comment]
This has been fixed in current master.
