### ISSUE TITLE
unexpected "mc mirror" behaviour

### ISSUE THREAD

**Issue by koolhead17** [minio/mc#1629]
I am trying to execute this command, It would have been better for mc to provide me a meaningful output/error.

```
$ mc mirror s3/kline myminio/
mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/kline/ui-assets.go’. Object name cannot be empty.
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume EfAeJBYA’
```

**Comment by harshavardhana** [comment]
> mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/kline/ui-assets.go’. Object name cannot be empty.

`Object name cannot be empty.` is in-fact a wrong message but it is occurring due to the fact that an existing path was not specified on the target side.
