### ISSUE TITLE
mirror: Implement two-way sync

### ISSUE THREAD

**Issue by klausenbusk** [minio/mc#1637]
Will require some sort of local database to keep track of the files.
Not sure if it out of the scope for mc?

**Comment by GarimaKapoor** [comment]
Bi-directional mirroring can work reliably for immutable data. Detecting mutable changes on a large data set is hard. Best recommendation is to run two instances of mc, one in each direction. It will be users responsibility to ensure that objects are neither deleted or overwritten. Also we are working on async replication (mc mirror --continuos) which will make mirroring faster and efficient.
