### ISSUE TITLE
cp: Error using mc session resume

### ISSUE THREAD

**Issue by PriteshJain** [minio/mc#1642]
I tried uploading a file to minio server using mc client.
I killed the process in between.
then tried to resume the process with the command suggested by mc-client. failed

```
./mc cp /Users/priteshjain/Documents/akamai-demo.mov myminio/test-aws

...n/Documents/akamai-demo.mov: 90.00 MB / 2.70 GB  ▓▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    3.26 % 44.72 MB/s 58s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume eazhrKGq’

mc: <ERROR> Failed to copy ‘/Users/priteshjain/Documents/akamai-demo.mov’. parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
```

OS: Yosemite 10.10.5
Minio client version:  2016-02-19T04:11:55Z

[session-mc.zip](https://github.com/minio/mc/files/181160/session-mc.zip)

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/1246 - this patch fixes the problem, it was a server side issue.
