### ISSUE TITLE
question. tell mc to ignore stupid .DS_Store files on mac osx

### ISSUE THREAD

**Issue by joeblew99** [minio/mc#1648]
i am getting this in the terminal.
```
./mc mirror /usr/xxx/ s3/$bucketxxx/ 

mc: <ERROR> Unable to prepare URLs for mirroring. Overwrite not allowed for ‘/Users/apple/workspace/go/src/bitbucket.org/xx/toolbin/.DS_Store’. Use ‘--force’ to override this behavior.
```
i know its nuts how OSX makes these files, but is there a way to tell mc to ignore these files when performing mirrors ??

**Comment by harshavardhana** [comment]
> ./mc mirror /usr/xxx/ s3/$bucketxxx/ 
> 
> mc: <ERROR> Unable to prepare URLs for mirroring. Overwrite not allowed for ‘/Users/apple/workspace/go/src/bitbucket.org/xx/toolbin/.DS_Store’. Use ‘--force’ to override this behavior.
> i know its nuts how OSX makes these files, but is there a way to tell mc to ignore these files when performing mirrors ??

@joeblew99 - there is no way to exclude files right now, will see if it's easy enough . Keeping this here for further discussion.

**Comment by joeblew99** [comment]
Ok thanks. 

Its quite a big problem on OSX. I tried to tell OSX to stop doing it but it did not work.
If i write a little script to delete them, OSX gets in there 1 second later and makes them again !!
arrgrg :)

**Comment by abperiasamy** [comment]
Lets add code to automatically ignore .DS_Store under OSX. This way we can avoid adding another command-line flag. Eventually we may end up adding --ignore-dir and --ignore-files with glob pattern. For now lets try and avoid it.

**Comment by joeblew99** [comment]
+1

**Comment by harshavardhana** [comment]
@joeblew99 - reported this issue is not fixed yet.

**Comment by joeblew99** [comment]
I will watch this issue. If possible it would be awesome if this is fixed
ASAP, as it's causing huge problems for me .

**Comment by joeblew99** [comment]
Thanks. Will try it out now

**Comment by gedw99** [comment]
Fixed ! Thanks all ...
