### ISSUE TITLE
windows bug with "mc.exe mirror"

### ISSUE THREAD

**Issue by joeblew99** [minio/mc#1649]
````
mc.exe mirror s3\XXX\caddy _toolbin\caddy
0 B / 44.43 MB [                                                                                            ]   0.00 %
mc.exe: <ERROR> Failed to copy ‘https://s3.amazonaws.com/appdif-dev-toolbin/caddy’. The specified key does not exist.
mc.exe: <ERROR> Session safely terminated. To resume session ‘mc session resume wLfyAfDO’

````

on s3 "caddy" is a folder with other folders inside it.
on the local disk caddy exists as a folder, as the same level as the mc.exe and from where this is being run.
So it should work ?

**Comment by joeblew99** [comment]
just tried on osx and go same

## Mirroring down from s3 ##
mc: <ERROR> Source ‘s3/appdif-dev-toolbin/caddy/’ is not a folder. Only folders are supported by mirror command. Invalid arguments provided, cannot proceed.

So clearly its somehting i am doing wrong ?

I just want to copy a folder from inside a s3 bucket to a folder on local disk ..
What am i missing ?

**Comment by joeblew99** [comment]
I have made test cases for windows and osx.
steps to reproduce:

1. from OSX i mirror up to S3, and there are .DS_Store files, that messes up S3. I know this because S3 will refuse to delete folders at s3 then.

2. from Windows this then screws up MC when its tried to mirror them down to local.

**Comment by joeblew99** [comment]
actually from osx, doing the step2 also fails.
I ended up having to delete the folders inside the bucket to clean it up.

**Comment by vadmeste** [comment]
@joeblew99, do you confirm that you have this in your side?
x-MacBook-Pro:backend apple$ ./mc ls s3/appdif-dev-toolbin/caddy/
[2016-03-24 13:52:36 CET] 0B

it means ls gives one entry but without any name? if yes it is an important point and I guess it could solve all the problems that you are seeing

**Comment by harshavardhana** [comment]
> @joeblew99, do you confirm that you have this in your side?
> x-MacBook-Pro:backend apple$ ./mc ls s3/appdif-dev-toolbin/caddy/
> [2016-03-24 13:52:36 CET] 0B
> 
> it means ls gives one entry but without any name? if yes it is an important point and I guess solving this could fix all the problems that you are seeing

Yes i missed this, it also means that a '0Byte' file was created with 'caddy/' as the object name, which is possible on S3. But causes problems on local FS , i wonder if 'mc mirror' caused it? or did you upload this data outside of 'mc'.

**Comment by joeblew99** [comment]
I used MC mirror to upload it from windows.

When I redid it all from OSX I did not get the bug you have isolated.

Is a tough bug to reproduce, so I can see it being missed.

**Comment by GarimaKapoor** [comment]
@vadmeste can you test and see if this issue exists.

**Comment by vadmeste** [comment]
@GarimaKapoor, I tried to reproduce with similar conditions but the bug didn't show up:

````mc mirror s3\vadmeste-test-bucket\caddy _toolbin\caddy````

I guess you can close this.

**Comment by harshavardhana** [comment]
Closing, can be re-opened when reproduced again.

**Comment by sra** [comment]
I hit this yesterday. The `foo/` "folder" was created with a GUI app called Transmission by Panic. Cyberduck does it as well. They create this placeholder object to mean "folder". The behavior can be replicated easily with the `mc` command. The `aws s3 sync` command handles this issue without comment. Maybe `mc` could also, or adjust the error message a little. 

```
$ mc cat s3/bucket/foo/
mc: <ERROR> Unable to read from ‘s3/bucket/foo/’. The specified key does not exist.

$ echo "test" | mc pipe s3/bucket/foo/

$ mc cat s3/bucket/foo/
test

$ echo "test2" | mc pipe s3/bucket/foo/bar

$ mc cat s3/bucket/foo/bar
test2

$ mc mirror /s3/bucket/foo/ /tmp/f
mc: <ERROR> Source ‘/s3/bucket/foo/’ is not a folder. Only folders are supported by mirror command. Invalid arguments provided, cannot proceed.

$ mc ls /s3/bucket/foo/
[2017-03-04 08:44:42 EST]     5B

$ mc ls /s3/bucket/foo
[2017-03-04 08:45:57 EST]     0B foo/

$ mc cat s3/bucket/foo/bar
test2

$ mc rm /s3/bucket/foo/
Removed ‘/s3/bucket/foo/’.

$ mc mirror /s3/bucket/foo/ /tmp/f
...naws.com/bucket/foo/bar: 6 B / 6 B  100.00 ....
```
