### ISSUE TITLE
`--region` is ignored in `mc mb`

### ISSUE THREAD

**Issue by remohammadi** [minio/mc#1658]
I've just installed `mc` using `go get`:
```
$ TZ=PST8PDT date
Fri Apr  1 14:57:58 PDT 2016
$ go get -u github.com/minio/mc
$ mc version
Version: DEVELOPMENT.GOGET
Release-tag: DEVELOPMENT.GOGET
Commit-id: DEVELOPMENT.GOGET
```

I've configured a `minio` server and set its region value to `iran`. But when I try to create a bucket, I see that `mc` is ignoring `--region`:

```
$ mc --debug mb --region "iran" honarnama/store-logo
mc: <DEBUG> PUT /store-logo/ HTTP/1.1
Host: honarnama.net:9000
User-Agent: Minio (darwin; amd64) minio-go/1.0.1 mc/DEVELOPMENT.GOGET
Content-Length: 148
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160401/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: s+J1GGLmCWK8d7imoAXaSg==
X-Amz-Content-Sha256: bcb416bb8be498d68bebece7f8fe5ae49f39ff7d71c1925515d9bf71201b7dc2
X-Amz-Date: 20160401T220219Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 01 Apr 2016 22:02:21 GMT
Server: Minio/DEVELOPMENT.2016-04-01T21-19-20Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: JOT4TLE3LLP4BNZI

f0
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRegion</Code><Message>Region does not match.</Message><Key></Key><BucketName></BucketName><Resource>/store-logo/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  1.753994572s

mc: <ERROR> Unable to make bucket ‘honarnama/store-logo’. Region does not match.
```

As you can see, there is a `us-east-1` in the `Authorization` header, and there is no `iran` in the request.

Also, `mc ls` is trying to get the list of the buckets with the same `Authorization` header, and fails with the same server error, but prints the misleading message "Bucket name cannot be empty".

**Comment by harshavardhana** [comment]
> I've just installed mc using go get:
> 
> $ TZ=PST8PDT date
> Fri Apr  1 14:57:58 PDT 2016
> $ go get -u github.com/minio/mc
> $ mc version
> Version: DEVELOPMENT.GOGET
> Release-tag: DEVELOPMENT.GOGET
> Commit-id: DEVELOPMENT.GOGET
> I've configured a minio server and set its region value to iran. But when I try to create a bucket, I see that mc is ignoring --region:
> 
> $ mc --debug mb --region "iran" honarnama/store-logo
> mc: <DEBUG> PUT /store-logo/ HTTP/1.1
> Host: honarnama.net:9000
> User-Agent: Minio (darwin; amd64) minio-go/1.0.1 mc/DEVELOPMENT.GOGET
> Content-Length: 148
> Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160401/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> Content-Md5: s+J1GGLmCWK8d7imoAXaSg==
> X-Amz-Content-Sha256: bcb416bb8be498d68bebece7f8fe5ae49f39ff7d71c1925515d9bf71201b7dc2
> X-Amz-Date: 20160401T220219Z
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 400 Bad Request
> Transfer-Encoding: chunked
> Accept-Ranges: bytes
> Content-Type: text/xml; charset=utf-8
> Date: Fri, 01 Apr 2016 22:02:21 GMT
> Server: Minio/DEVELOPMENT.2016-04-01T21-19-20Z (linux; amd64)
> Vary: Origin
> X-Amz-Request-Id: JOT4TLE3LLP4BNZI
> 
> f0
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>InvalidRegion</Code><Message>Region does not match.</Message><Key></Key><BucketName></BucketName><Resource>/store-logo/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
> 0
> 
> mc: <DEBUG> Response Time:  1.753994572s
> 
> mc: <ERROR> Unable to make bucket ‘honarnama/store-logo’. Region does not match.
> As you can see, there is a us-east-1 in the Authorization header, and there is no iran in the request.
> 
> Also, mc ls is trying to get the list of the buckets with the same Authorization header, and fails with the same server error, but prints the misleading message "Bucket name cannot be empty".

Can you paste your minio server version?

**Comment by remohammadi** [comment]
```
$ minio version
Version: 2016-04-01T21:19:20Z
Release-Tag: DEVELOPMENT.2016-04-01T21-19-20Z
Commit-ID: 272c5165aa7beab21e58ae99e346f4c35505f692
```

(At the time of my first `mc config host add`, the server was one day older. But I upgraded the server and reinited and tried again before opening the issue)

**Comment by harshavardhana** [comment]
> $ minio version
> Version: 2016-04-01T21:19:20Z
> Release-Tag: DEVELOPMENT.2016-04-01T21-19-20Z
> Commit-ID: 272c5165aa7beab21e58ae99e346f4c35505f692
> (At the time of my first mc config host add, the server was one day older. But I upgraded the server and reinited and tried again before opening the issue)

@remohammadi - taking a look.

**Comment by harshavardhana** [comment]
> $ minio version
> Version: 2016-04-01T21:19:20Z
> Release-Tag: DEVELOPMENT.2016-04-01T21-19-20Z
> Commit-ID: 272c5165aa7beab21e58ae99e346f4c35505f692
> (At the time of my first mc config host add, the server was one day older. But I upgraded the server and reinited and tried again before opening the issue)
> @remohammadi - taking a look.

Looks like a bug @remohammadi - don't use regions for now. Just stick with default, will fix it. Can you open a bug against server? - this is a server side issue. 

Thanks closing this one.

**Comment by remohammadi** [comment]
Thank you. I'll.

What should I write for the title of the issue? I guess the region is lost in the authentication step, so is it a suitable one: "region is lost/misreported in the authentication step"?

**Comment by harshavardhana** [comment]
> What should I write for the title of the issue? I guess the region is lost in the authentication step, so is it a suitable one: "region is lost/misreported in the authentication step"?

Yes that shouldn't be a problem, we will fix it :-)
