### ISSUE TITLE
S3 access should allow alternate URLs (e.g. China)

### ISSUE THREAD

**Issue by awbacker** [minio/mc#1668]
I am working with AWS china in addition to 'normal' aws, and would like to be able to change the S3 url to `s3.cn-north-1.amazonaws.com.cn`, but `mc` requires that the URL be `s3.amazonaws.com`.  

I'm not sure why there is a URL options there in the config, if it is required to be a single value ;)  In any case, I can't use MC to upload to my bucket, so I'm going to look at `s3put` again.  I much prefer the way `mc` handles things, since I can make aliases like `s3-china` and set a specific config for that (or `s3-eu` and `s3-us` to handle those specific regions.  Or I could, if the URL was changeable :)

**Comment by harshavardhana** [comment]
> I am working with AWS china in addition to 'normal' aws, and would like to be able to change the S3 url to s3.cn-north-1.amazonaws.com.cn, but mc requires that the URL be s3.amazonaws.com.
> 
> I'm not sure why there is a URL options there in the config, if it is required to be a single value ;) In any case, I can't use MC to upload to my bucket, so I'm going to look at s3put again. I much prefer the way mc handles things, since I can make aliases like s3-china and set a specific config for that (or s3-eu and s3-us to handle those specific regions. Or I could, if the URL was changeable :)

Yeah mc and minio-go currently don't support China region due to the specific DNS conventions used by this region and requirement of different access keys which will only work for china region. 

Right now it's not possible we will see how we can this properly.

**Comment by awbacker** [comment]
Ah, I understand.  I think you'd need a profile like system, or allowing fully specified buckets like `s3://s3-eu-west-1.amazonaws.com/buckename/`.

I ended up going back to `aws s3 sync my-bucket --profile [ireland|china]` since s3put, s4put, and mc were _all_ failing to download a certain directory from the bucket (no idea why).

**Comment by harshavardhana** [comment]
> Ah, I understand. I think you'd need a profile like system, or allowing fully specified buckets like s3://s3-eu-west-1.amazonaws.com/buckename/.
> 
> I ended up going back to aws s3 sync my-bucket --profile [ireland|china] since s3put, s4put, and mc were all failing to download a certain directory from the bucket (no idea why).

We don't need a profile system, we automatically fetch endpoints based on the bucket location there is no need to provide an endpoint that is why just 's3.amazonaws.com' is good enough.  IMHO the problem with china region is that Access keys used in US region do not work on China region, you need to use a separate account, unless things have changed recently in this area.

**Comment by awbacker** [comment]
You have the china situation right, and that is almost certainly not going to change anytime soon (from discussion with them.)  Legal reasons, ICP registration, etc.  I have accounts at both, and do use different access keys.

I suppose using `cn-north-1` (etc) would be necessary, and maybe dropping or ignoring the URL.  

Thanks for thinking about this, even if it comes to naught.  I know there are few people in my position right now, and we can make `$ aws s3 ...` work for us.

**Comment by harshavardhana** [comment]
> You have the china situation right, and that is almost certainly not going to change anytime soon (from discussion with them.) Legal reasons, ICP registration, etc. I have accounts at both, and do use different access keys.
> 
> I suppose using cn-north-1 (etc) would be necessary, and maybe dropping or ignoring the URL.
> 
> Thanks for thinking about this, even if it comes to naught. I know there are few people in my position right now, and we can make $ aws s3 ... work for us.
>  
>                

Will have to add China region support specifically in https://github.com/minio/minio-go to make it work, we can get a patch ready quickly but wanted to see if you prefer a patch to test or a binary to test and validate on your end? 

Thanks let us know.

**Comment by awbacker** [comment]
No rush on it, but If you need testers for a patch then binary would work best for me at the moment (quickest).  

I'm happy to learn `go` a bit, if the docs for that are good enough that a newbie can build & run.  Just a branch name is fine in that case.

**Comment by harshavardhana** [comment]
> No rush on it, but If you need testers for a patch then binary would work best for me at the moment (quickest).
> 

Okay then binary it is, is there a specific platform? 

> I'm happy to learn go a bit, if the docs for that are good enough that a newbie can build & run. Just a branch name is fine in that case.

If it's not we will fix it, running 'go' at first is a little convoluted.

**Comment by awbacker** [comment]
Oh lawd, I forgot... Yeah, I'm on a Mac.

**Comment by harshavardhana** [comment]
> Oh lawd, I forgot... Yeah, I'm on a Mac.

Here you go - [mc.zip](https://github.com/minio/mc/files/209058/mc.zip), let us know how it goes.

**Comment by harshavardhana** [comment]
> Oh lawd, I forgot... Yeah, I'm on a Mac.
> Here you go - mc.zip, let us know how it goes.

Just checking @awbacker on were you able to validate the binary?

**Comment by harshavardhana** [comment]
> Oh lawd, I forgot... Yeah, I'm on a Mac.

Checking back were you able to test the binaries on Mac?

**Comment by awbacker** [comment]
Sorry, last weeks was a bit of a nightmare.  I did test it this weekend, but it seems to not quite work.  Perhaps I'm configuring it wrong, though.  I'm happy to send you a set of AWS credentials for china with access to our S3 buckets if that helps debugging.

```
[~/dev/st/s3]: ./mc ls s3-china
mc: <ERROR> Unable to stat ‘s3-china’. Amazon S3 endpoint should be 's3.amazonaws.com'.
```

```
"s3-china": {
    # have tried https://s3.cn-north-1.amazonaws.com.cn as well, to same result
    "url": "https://s3.amazonaws.com.cn",
    "accessKey": "AbC3Ef4Hi578BEEF",
    "secretKey": ".....",
    "api": "S3v4"
}
```

**Comment by harshavardhana** [comment]
@awbacker are you sure you are using the attached binary here because locally i am able to initiate a request without the complaints. 

```
$ mc ls --debug china/testbucket
mc: <DEBUG> HTTP/1.1 401 Unauthorized
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Mon, 18 Apr 2016 02:07:15 GMT
Server: AmazonS3
X-Amz-Id-2: ggsza/NvSjLjzw/cgJ2Bxj8luHZ5vVPVcn0kFbMpC0QKydBt2CMKUdD+qjnE6LdSXJQvd2LFpX0=
X-Amz-Request-Id: 8F0AF35A62135C79

11c
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>UnauthorizedAccess</Code><Message>You are not authorized to perform this operation</Message><RequestId>8F0AF35A62135C79</RequestId><HostId>ggsza/NvSjLjzw/cgJ2Bxj8luHZ5vVPVcn0kFbMpC0QKydBt2CMKUdD+qjnE6LdSXJQvd2LFpX0=</HostId></Error>
0
```

**Comment by harshavardhana** [comment]
```
	"s3-china": {
			"url": "https://s3.cn-north-1.amazonaws.com.cn",
			"accessKey": "",
			"secretKey": "",
			"api": "S3v4"
		}
```

**Comment by harshavardhana** [comment]
[mc.zip](https://github.com/minio/mc/files/222987/mc.zip)

Copied here once, more, let me know how it goes. Here is the result of course it didn't work since i don't have china keys.

```
$ mc ls china/testbucket
mc: <ERROR> Unable to stat ‘china/testbucket’. You are not authorized to perform this operation
```

**Comment by harshavardhana** [comment]
> I'm happy to send you a set of AWS credentials for china with access to our S3 buckets if that helps debugging.

This won't be necessary until as last resort, but thanks though 👍

**Comment by awbacker** [comment]
``` 
# config.json
"s3-uploader": {
    "url": "https://s3.cn-north-1.amazonaws.com.cn", 
    "accessKey": "xxx", "secretKey": "xxx",	"api": "S3v4"
}
```

```
./mc ls s3-uploader/www.scantrust.cn
mc: <ERROR> Unable to stat ‘s3-uploader/www.scantrust.cn’. The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'cn-north-1'
```

I have it all set up with s3 read only credentials.  We only store our public website in these buckets for now, so no need to worry.  It's all already publicly accessible.

**Comment by awbacker** [comment]
You are a hard man to track down, can't find an email address for you.  And github doesn't have a PM function yet.  Send me an email at `andrew.backer@scantrust.com` and I'll send over the config info including keys for `aws s3 ls`.

**Comment by harshavardhana** [comment]
> You are a hard man to track down, can't find an email address for you. And github doesn't have a PM function yet. Send me an email at andrew.backer@scantrust.com and I'll send over the config info including keys for aws s3 ls.

Sure thing - i didn't think it was that hard @awbacker :-)

**Comment by harshavardhana** [comment]
@awbacker - https://github.com/minio/minio-go/pull/381 this should fix the problem.

**Comment by harshavardhana** [comment]
> @awbacker - minio/minio-go#381 this should fix the problem.

[mc.zip](https://github.com/minio/mc/files/223094/mc.zip) - would you mind validating this binary for us? - Thanks.

**Comment by awbacker** [comment]
@harshavardhana Upload & list worked perfectly! Thanks!
