### ISSUE TITLE
cp/mirror: use CopyObject API to enable server side copy, optimizing client side network transfer.

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1673]
Caveats

- Can only do CopyObject on 5GB or lesser sized objects.
- Is within the same server.

**Comment by sreeram-boyapati** [comment]
I will take this up. Try to get a patch by saturday.

**Comment by harshavardhana** [comment]
> I will take this up. Try to get a patch by saturday.

This is already taken by @awwalker :-)

**Comment by sreeram-boyapati** [comment]
oh okay.
