### ISSUE TITLE
mc cannot treat file system files whose names contain odd but legitimate characters like '?'

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1677]
you can find below how to reproduce the problem:

```
$ touch /tmp/foo\?.txt
$ mc cp /tmp/foo\?.txt /tmp/foo.backup
mc: <ERROR> Unable to guess the type of copy operation. Invalid arguments provided, cannot proceed.
```

**Comment by harshavardhana** [comment]
One other form of bug is still there.. 

```
$ mc cp file\?.go s3/deflector/
$ mc ls s3/deflector/
[2016-04-10 15:42:04 PDT]     0B file
```

The ending '?' is stripped off, re-opening this to fix this issue as well.

**Comment by vadmeste** [comment]
yes.. but the bug should be in another place now, I guess ? should be
replaced by %hex in url, right?

On Sun, Apr 10, 2016, 23:43 Harshavardhana <notifications@github.com> wrote:

> One other form of bug is still there..
>
> $ mc cp file\?.go s3/deflector/
> $ mc ls s3/deflector/
> [2016-04-10 15:42:04 PDT]     0B file
>
> The ending '?' is stripped off, re-opening this to fix this issue as well.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/minio/mc/issues/1677#issuecomment-208086612>
>
-- 

Sent from my mobile

**Comment by harshavardhana** [comment]
> yes.. but the bug should be in another place now, I guess ? should be
> replaced by %hex in url, right?

No its in the same place, it just that the 'rest' after the splitSpecial removes the '?'

**Comment by harshavardhana** [comment]
> yes.. but the bug should be in another place now, I guess ? should be
> replaced by %hex in url, right?
> No its in the same place, it just that the 'rest' after the splitSpecial removes the '?'

It is tricky to fix this since, it would meddle with the URLs.

**Comment by vadmeste** [comment]
will see that tomorrow

On Sun, Apr 10, 2016, 23:51 Harshavardhana <notifications@github.com> wrote:

> yes.. but the bug should be in another place now, I guess ? should be
> replaced by %hex in url, right?
> No its in the same place, it just that the 'rest' after the splitSpecial
> removes the '?'
>
> It is tricky to fix this since, it would meddle with the URLs.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/minio/mc/issues/1677#issuecomment-208087116>
>
-- 

Sent from my mobile

**Comment by harshavardhana** [comment]
> will see that tomorrow

It is fixed.

**Comment by harshavardhana** [comment]
> will see that tomorrow

Can you validate this on your end? - https://github.com/minio/mc/pull/1679
