### ISSUE TITLE
api:   Document behaviour and change console message for `mc <command>`  without alias.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/mc#1682]
The following screenshot depicts the issue. 
<img width="721" alt="screen shot 2016-04-13 at 10 06 33 am" src="https://cloud.githubusercontent.com/assets/2609511/14482940/cb38c3f4-015f-11e6-910b-bc247e7b072d.png">

`mc mb my-bucket` when executed repeatedly succeeds. 
@sreeram-boyapati @harshavardhana

**Comment by sreeram-boyapati** [comment]
@hackintoshrao got a better idea of the issue now, will take this up. :)

**Comment by hackintoshrao** [comment]
@sreeram-boyapati : Please build from current master and verify this.

**Comment by harshavardhana** [comment]
> @sreeram-boyapati : Please build from current master and verify this.

This is current behavior, what is wrong in this? 'mc mb' creates a local directory.

**Comment by harshavardhana** [comment]
> The following screenshot depicts the issue. 
> 
> 
> mc mb my-bucket when executed repeatedly succeeds. 
> @sreeram-boyapati @harshavardhana

```
alias mkdir='mc mb'
```

**Comment by hackintoshrao** [comment]
`mc mb` without alias creates local directory?? Is that documented somewhere ?

**Comment by harshavardhana** [comment]
> mc mb without alias creates local directory?? Is that documented somewhere ?

It happens for all commands :-)

**Comment by hackintoshrao** [comment]
Sure :) May be this has to be documented in README.md .

**Comment by hackintoshrao** [comment]
Also may be the message has to be changed from  `Bucket created successfully` to something else.

**Comment by harshavardhana** [comment]
> Also may be the message has to be changed from Bucket created successfully to something else.

👍 

> Sure :) May be this has to be documented in README.md .

Please go ahead. 👍

**Comment by harshavardhana** [comment]
Fix the console printing in another bug. 'mc mb' is sufficiently documented. 

```
NAME:
   mc mb - Make a bucket or folder.
```

```
EXAMPLES:
   1. Create a bucket on Amazon S3 cloud storage.
      $ mc mb s3/mynewbucket

   2. Create a new bucket on Google Cloud Storage.
      $ mc mb gcs/miniocloud

   4. Create a new bucket on Amazon S3 cloud storage in region ‘us-west-2’.
      $ mc mb --region=us-west-2 s3/myregionbucket

   5. Create a new directory including its missing parents (equivalent to ‘mkdir -p’).
      $ mc mb /tmp/this/new/dir1
```
