### ISSUE TITLE
rsy

### ISSUE THREAD

**Issue by spdustin** [minio/mc#1683]
The tagline for `mc` says

> Minio Client is a replacement for ls, cp, mkdir, diff and ***rsync*** commands for filesystems and object storage.

But the help and source seem to not support this. Is `rsync`-style syncing to S3 a supported scenario, with checksums/hashes used to compare files? I understand that reproducing block storage isn't the goal, and thus, sending deltas over the wire would not be supported, so aside from that, is there a true "sync" operation?

**Comment by harshavardhana** [comment]
> But the help and source seem to not support this. Is rsync-style syncing to S3 a supported scenario, with checksums/hashes used to compare files? I understand that reproducing block storage isn't the goal, and thus, sending deltas over the wire would not be supported, so aside from that, is there a true "sync" operation?

It is rsync like,  since end to end there are checksum and signature validation. 'mc mirror' is rsync like.  There is no true 'rsync' operation ie transferring only deltas since object storage does not support any append like feature on an existing file or object offset specific update feature.

**Comment by spdustin** [comment]
> 'mc mirror' is rsync like.

Meaning:

| Source   |  Dest  |  Action             |
| -------- | ------ | ------------------- |
| YES      | NO     | UPLOAD from local   |
| NO       | YES    | DELETE from remote  |
| YES      | YES    | COMPARE, newer wins |

Is that right?

What if source file exists, and the target file doesn't exist, but it did during an earlier mirror... will it delete the source file in that case?

**Comment by harshavardhana** [comment]
> What if source file exists, and the target file doesn't exist, but it did during an earlier mirror... will it delete the source file in that case?

No it doesn't delete the source, every 'mc mirror' a new operation. There is no state stored anywhere regarding what was copied earlier. So if the files have changed it will copy, if there is an overwrite it will ask for user input i.e '--force'  

Right now deletes are not implemented we will be implementing it as '--remove' option where it will purge the extraneous entries on Dest which do not exist on Source.

**Comment by harshavardhana** [comment]
> Right now deletes are not implemented we will be implementing it as '--remove' option where it will purge the extraneous entries on Dest which do not exist on Source.

`--remove` implemented in latest master for 'mc mirror'
