### ISSUE TITLE
Minio Client doesn't throw warning while creating a bucket or saving files on an unconfigured alias

### ISSUE THREAD

**Issue by booleanhunter** [minio/mc#1689]
#### Steps to replicate this bug

- Run minio server - `minio server ~/Documents/miniobuckets/`

- Config Minio Client - `mc config host add alias1 http://localhost:9000 <AccessKey> <SecretKey>`

- Create bucket on alias - `mc mb alias1/bucket1`

- Save file to bucket1. Works as expected: 
```
$ mc cp index.html alias1/bucket1
 index.html:                   328 B / 328 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00 % 60.66 KB0
```
- Try listing buckets on an un-configured alias. Works fine:
```
$ mc ls randomalias/
mc: <ERROR> Unable to stat ‘randomalias/’. Requested file ‘randomalias/’ not found
```
- Try saving a file on a non-existing bucket on a un-configured alias. Should have thrown a warning / error, instead got this:
```
 $ mc cp index.html randomalias/bucket2
index.html:                   328 B / 328 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00 % 38.30 KB0
```
- Now try listing buckets once again on the un-configured alias.
```
$ mc ls randomalias/
[2016-04-18 11:31:00 IST]   328B bucket2
```

**Comment by vadmeste** [comment]
When you pass an alias that is not configured, mc will assume that you mean
a directory in your actual filesystem. In your case, mc created randomalias
directory with files that you've copied, you can check them with your
regular ls.

On Mon, Apr 18, 2016, 07:27 Ashwin Hariharan <notifications@github.com>
wrote:

> Steps to replicate this bug
>
>    -
>
>    Run minio server - minio server ~/Documents/miniobuckets/
>    -
>
>    Config Minio Client - mc config host add alias1 http://localhost:9000
>    <AccessKey> <SecretKey>
>    -
>
>    Create bucket on alias - mc mb alias/bucket1
>    -
>
>    Save file to bucket1. Works as expected:
>
> $ mc cp index.html alias/bucket1
>  index.html:                   328 B / 328 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00 % 60.66 KB0
>
>
>    - Try listing buckets on an un-configured alias. Works fine:
>
> $ mc ls randomalias/
> mc: <ERROR> Unable to stat ‘randomalias/’. Requested file ‘randomalias/’ not found
>
>
>    - Try saving a file on a non-existing bucket on a un-configured alias.
>    Should have thrown a warning / error, instead got this:
>
>  $ mc cp index.html randomalias/bucket2
> index.html:                   328 B / 328 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00 % 38.30 KB0
>
>
>    - Now try listing buckets once again on the un-configured alias.
>
> $ mc ls randomalias/
> [2016-04-18 11:31:00 IST]   328B bucket2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/minio/mc/issues/1689>
>
-- 

Sent from my mobile

**Comment by booleanhunter** [comment]
@vadmeste Got it! The directories got created in the same location where I typed the commands. But I was looking for them within the exported directory given while starting the minio server.

Thanks!

**Comment by harshavardhana** [comment]
> Thanks! I guess it might be helpful to print out a message which says that minio will create a directory within the local filesystem since we used an un-configured alias?

It would be nice but it is tricky to print a message and show a progress bar at the same time. There won't be enough time to see the message.

**Comment by booleanhunter** [comment]
Makes sense :+1:
