### ISSUE TITLE
[config] Ceph/Exoscale are not compatible with AWS standards for Access and Secret keys - relax the config check.

### ISSUE THREAD

**Issue by fredericofs** [minio/mc#1690]
I am trying to use it with DreamObjects (ceph) storage, but my access key it not accepet, I guess because ceph keys can have more special characters than aws standards.

Error output:

mc: <ERROR> Invalid access key ‘c67W2-r4MAyAYScRl’. Invalid arguments provided, cannot proceed.

**Comment by harshavardhana** [comment]
> I am trying to use it with DreamObjects (ceph) storage, but my access key it not accepet, I guess because ceph keys can have more special characters than aws standards.
> 
> Error output:
> 
> mc: Invalid access key ‘c67W2-r4MAyAYScRl’. Invalid arguments provided, cannot proceed.

Thanks for testing 'mc' -  we would like to stick to AWS standards.  Is it possible to change the keys to follow AWS standards on Ceph ?

**Comment by fredericofs** [comment]
I may try to generate random keys again and again, until I end up with something without special characters.
Why there is the need to check the entered key for valid characters before the auth process with the server?

**Comment by harshavardhana** [comment]
> I may try to generate random keys again and again, until I end up with something without special characters.
> Why there is the need to check the entered key for valid characters before the auth process with the server?

That is perhaps input parameter validation to make sure that we have valid values - it can be relaxed, since we didn't expect access keys to be anything other than AWS style. 

why does Ceph generate access keys which are not compatible with AWS standards?

**Comment by fredericofs** [comment]
why does Ceph generate access keys which are not compatible with AWS standards? 

Now that is a good question, I wonder why  they let include - and _ characters in the keys.

**Comment by fredericofs** [comment]
Just tried with a new key, without - and _ characters and still i got this msg:

mc: <ERROR> Invalid access key ‘u5AKxxxxxxxxEfGdoWE’. Invalid arguments provided, cannot proceed.

**Comment by harshavardhana** [comment]
> mc: Invalid access key ‘u5AKxxxxxxxxEfGdoWE’. Invalid arguments provided, cannot proceed.

Yeah it related to the length and the characters - it doesn't satisfy 

```
        regex := regexp.MustCompile(`^[A-Z0-9\\-\\.\\_\\~]{20}$`)
```

**Comment by harshavardhana** [comment]
> Yeah it related to the length and the characters - it doesn't satisfy
> 
>         regex := regexp.MustCompile(`^[A-Z0-9\\-\\.\\_\\~]{20}$`)

We will relax this.

**Comment by Eusebius1920** [comment]
I have a similar problem with exoscale API-keys:

Example key:
`EXOb76bfeb1234562iu679f11588`

They are fixed length (always 27 chars) and consisting of upper and lower case characters.

**Comment by fredericofs** [comment]
Is it already on the binary ARM version so I can test it?

**Comment by harshavardhana** [comment]
Not yet we havent made a release yet.
