### ISSUE TITLE
mirror: Transfer Reliability Features

### ISSUE THREAD

**Issue by shanemadden** [minio/mc#1693]
I've been using `mc mirror` to transfer a large amount of small files from an s3 bucket to a local system, and it's working great, though each of the parallel transfers I've been running has been needing a lot of babysitting. Every TCP handshake timeout, TLS handshake timeout, and connection reset exits the `mc` process, necessitating `mc session resume` (by hand or otherwise).

For transfers like this, having optional flags allowing for graceful handling of these errors would greatly reduce the amount of human intervention (or wrapper script writing) needed:

  - `--retries 5` - it'd be great to gracefully try again when a connection hiccup causes an error (but probably not on by default, since it could incur unexpected bandwidth costs?)
  - `--skip-missing` - I'm running into some legacy cruft in the s3 bucket which is causing `The specified key does not exist.` errors (and I'm guessing this might also happen if a file is scanned but then deleted before it can be copied?). Getting past these objects requires removing their line from the session's .data file, then resuming.

Thanks!

**Comment by harshavardhana** [comment]
> I've been using mc mirror to transfer a large amount of small files from an s3 bucket to a local system, and it's working great, though each of the parallel transfers I've been running has been needing a lot of babysitting. Every TCP handshake timeout, TLS handshake timeout, and connection reset exits the mc process, necessitating mc session resume (by hand or otherwise).
> 
> For transfers like this, having optional flags allowing for graceful handling of these errors would greatly reduce the amount of human intervention (or wrapper script writing) needed:
> 
> --retries 5 - it'd be great to gracefully try again when a connection hiccup causes an error (but probably not on by default, since it could incur unexpected bandwidth costs?)

Every such network error should already be retried inside https://github.com/minio/minio-go in a binomial fashion with Jitter,  if you can list these errors then we can possibly add them to the retry list or validate if they are missing. `mc` doesn't have any special command line option. 

> --skip-missing - I'm running into some legacy cruft in the s3 bucket which is causing The specified key does not exist. errors (and I'm guessing this might also happen if a file is scanned but then deleted before it can be copied?). Getting past these objects requires removing their line from the session's .data file, then resuming.

This we need to see can you show some examples ?

**Comment by shanemadden** [comment]
Sure, sorry for the incomplete information!

Example transient network errors that I've seen (so far:)

    mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/foo’. Get https://bucketname.s3.amazonaws.com/foo: net/http: TLS handshake timeout
    mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/foo’. dial tcp (aws IP):443: i/o timeout
    mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/foo’. read tcp (localsystem:port)->(aws IP):443: read: connection reset by peer

For the "key does not exist" errors, a little background on the bucket:

 - Filenames are hashes, and the path is the first 4 characters - so the file `435ed7e9f07f740abf511a62c00eef6e` would be at `4/3/5/e/435ed7e9f07f740abf511a62c00eef6e` in the bucket
 - We don't have write access, so we can't correct these broken objects by altering the bucket in any way

The errors come from these orphan paths, where the enumeration found something to exist but it is an empty path, no child objects - presumably a file existed there at some point and was deleted.

    mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/bucketname/4/3/5/e/’. The specified key does not exist.

In the session .data file, these objects have lines as if they're files in between all the others, at hash slots where a file used to exist.

    # good line, file exists
    {... "SourceContent":{"URL":{..."Path":"/foo/4/3/5/e/435ed7e9f07f740abf511a62c00eef6e"...
    # bad, this is invalid junk data from the enumerate, and will need to be removed by hand
    {... "SourceContent":{"URL":{..."Path":"/foo/4/3/5/d"...
    # good line again
    {... "SourceContent":{"URL":{..."Path":"/foo/4/3/5/f/435f0000000000000000000000000000"...

**Comment by harshavardhana** [comment]
> mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/bucketname/4/3/5/e/’. The specified key does not exist.

This error should be just reported and the mirror should continue without copying these files already, you want suppress these error messages? 

> mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/foo’. Get https://bucketname.s3.amazonaws.com/foo: net/http: TLS handshake timeout
> mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/foo’. dial tcp (aws IP):443: i/o timeout
> mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/foo’. read tcp (localsystem:port)->(aws IP):443: read: connection reset by peer

These errors we will add to be retried in minio-go client.

**Comment by shanemadden** [comment]
> This error should be just reported and the mirror should continue without copying these files already, you want suppress these error messages?

The behavior I'm seeing is that the `The specified key does not exist` errors are actually causing `mc` to exit with a status code of 1:

```
[root@hostname ~]# mc mirror s3/bucket/0/ /mnt/mirror/0/
# runs until encountering a bad key:
mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/bucket/0/f/3/e’. The specified key does not exist.
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume kOcaYyNu’

[root@hostname ~]# mc session resume kOcaYyNu
# resume works with the progress bar quickly jumping to where it was, then the key fails again immediately.
mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/bucket/0/f/3/e’. The specified key does not exist.
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume kOcaYyNu’

[root@hostname ~]# vi /root/.mc/session/kOcaYyNu.data
# remove the json line belonging to 0/f/3/e by hand

[root@hostname ~]# mc session resume kOcaYyNu
# proceeds past the missing key
```

> These errors we will add to be retried in minio-go client.

Great, thanks! One more for you that I just encountered for the first time, unsure whether it's common enough to add: `mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/foo’. Input reader closed pre-maturely. Expected ‘576044’ bytes, but only received ‘543997’ bytes.`

> This is already retried, do you not see that behavior?

I only ever saw that error once, so maybe in that one case it was erroring repeatedly (retry working as intended, but the network error was persisting on the retries too).

**Comment by harshavardhana** [comment]
> Great, thanks! One more for you that I just encountered for the first time, unsure whether it's common enough to add: mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/foo’. Input reader closed pre-maturely. Expected ‘576044’ bytes, but only received ‘543997’ bytes.

This is good that it failed, we need to why this happened in the first place it's almost like silently data transfer got stopped and but there was no error. Is there a consistent way to reproduce this? 

It also seems that the object was already re-written with a different size v/s session information about the previous object size. 

> I only ever saw that error once, so maybe in that one case it was erroring repeatedly (retry working as intended, but the network error was persisting on the retries too).

Yes that can happen, we can't do much in that case if the network error is persistent. 

> The behavior I'm seeing is that the The specified key does not exist errors are actually causing mc to exit with a status code of 1:
> 
> [root@hostname ~]# mc mirror s3/bucket/0/ /mnt/mirror/0/
> # runs until encountering a bad key:
> mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/bucket/0/f/3/e’. The specified key does not exist.
> mc: <ERROR> Session safely terminated. To resume session ‘mc session resume kOcaYyNu’
> 
> [root@hostname ~]# mc session resume kOcaYyNu
> # resume works with the progress bar quickly jumping to where it was, then the key fails again immediately.
> mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/bucket/0/f/3/e’. The specified key does not exist.
> mc: <ERROR> Session safely terminated. To resume session ‘mc session resume kOcaYyNu’

This shouldn't happen which version of 'mc' are you using?

**Comment by shanemadden** [comment]
> Is there a consistent way to reproduce this?

No, I believe it was a transient networking error (the connection closed early somehow) - the next attempt on that file worked correctly.

> This shouldn't happen which version of 'mc' are you using?

```
Version: 2016-04-01T00:22:11Z
Release-tag: RELEASE.2016-04-01T00-22-11Z
Commit-id: 12adf3be326f5b6610cdd1438f72dfd861597fce

```

**Comment by harshavardhana** [comment]
> No, I believe it was a transient networking error (the connection closed early somehow) - the next attempt on that file worked correctly.

Oh okay. 

> Version: 2016-04-01T00:22:11Z
> Release-tag: RELEASE.2016-04-01T00-22-11Z
> Commit-id: 12adf3be326f5b6610cdd1438f72dfd861597fce

This looks correct version, will verify this by deleting the file and see how it happens.

**Comment by harshavardhana** [comment]
```
mc: <ERROR> Failed to copy ‘test/xbuild’. Requested file ‘test1/xbuild’ not found
mc: <ERROR> Failed to copy ‘test/xsd’. Requested file ‘test1/xsd’ not found
mc: <ERROR> Failed to copy ‘test/xz’. Requested file ‘test1/xz’ not found
mc: <ERROR> Failed to copy ‘test/xzcat’. Requested file ‘test1/xzcat’ not found
mc: <ERROR> Failed to copy ‘test/xzcmp’. Requested file ‘test1/xzcmp’ not found
mc: <ERROR> Failed to copy ‘test/xzdec’. Requested file ‘test1/xzdec’ not found
mc: <ERROR> Failed to copy ‘test/xzdiff’. Requested file ‘test1/xzdiff’ not found
mc: <ERROR> Failed to copy ‘test/xzegrep’. Requested file ‘test1/xzegrep’ not found
mc: <ERROR> Failed to copy ‘test/xzfgrep’. Requested file ‘test1/xzfgrep’ not found
mc: <ERROR> Failed to copy ‘test/xzgrep’. Requested file ‘test1/xzgrep’ not found
mc: <ERROR> Failed to copy ‘test/xzless’. Requested file ‘test1/xzless’ not found
mc: <ERROR> Failed to copy ‘test/xzmore’. Requested file ‘test1/xzmore’ not found
mc: <ERROR> Failed to copy ‘test/yasm’. Requested file ‘test1/yasm’ not found
mc: <ERROR> Failed to copy ‘test/yo’. Requested file ‘test1/yo’ not found
mc: <ERROR> Failed to copy ‘test/ytasm’. Requested file ‘test1/ytasm’ not found
mc: <ERROR> Failed to copy ‘test/yuicompressor’. Requested file ‘test1/yuicompressor’ not found
test/yuicompressor:     206.09 MB / 1.34 GB  ▓▓▓▓▓▓▓▓▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   15.06 % 494.54 MB
``` 

Did not see the errors that you saw locally, verifying with s3 bucket.

**Comment by harshavardhana** [comment]
Was able to reproduce the error fixing it

```
$ mc session resume kAtciOBW
mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/andoria/bin/arecord’. The specified key does not exist.
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume kAtciOBW’
```
