### ISSUE TITLE
./mc update failed. Looks like your minio server is down ?

### ISSUE THREAD

**Issue by joeblew99** [minio/mc#1703]
ENV: OSX

````
chmod +x ./mc
x-MacBook-Pro:backend apple$ ./mc update
Removing unsupported session file ‘/Users/apple/.mc/session/BBvwqyxH.json’ version ‘7’.
Removing unsupported session file ‘/Users/apple/.mc/session/DiXdbYkK.json’ version ‘7’.
Removing unsupported session file ‘/Users/apple/.mc/session/KPmLmutq.json’ version ‘7’.
Removing unsupported session file ‘/Users/apple/.mc/session/LCRoztwS.json’ version ‘7’.
Removing unsupported session file ‘/Users/apple/.mc/session/OVENuhwS.json’ version ‘7’.
Removing unsupported session file ‘/Users/apple/.mc/session/WTbALpzc.json’ version ‘7’.
Removing unsupported session file ‘/Users/apple/.mc/session/cBlxlTRK.json’ version ‘7’.
Removing unsupported session file ‘/Users/apple/.mc/session/coMgMcSz.json’ version ‘7’.
Removing unsupported session file ‘/Users/apple/.mc/session/eStuxSQw.json’ version ‘7’.
Removing unsupported session file ‘/Users/apple/.mc/session/enlWdQYN.json’ version ‘7’.
Removing unsupported session file ‘/Users/apple/.mc/session/nevHRONm.json’ version ‘7’.
mc: <ERROR> Unable to read from update URL ‘https://dl.minio.io/client/mc/release/darwin-amd64/mc.shasum’. Get https://dl.minio.io/client/mc/release/darwin-amd64/mc.shasum: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

```

**Comment by harshavardhana** [comment]
Looks like a network issue. We can access https://dl.minio.io/

**Comment by joeblew99** [comment]
I have no problem accessing the DL.mini.IO either. That's likely not the problem

**Comment by vadmeste** [comment]
I have the same problem
```
mc: <ERROR> Unable to read from update URL ‘https://dl.minio.io/client/mc/release/linux-amd64/mc.shasum’. Get https://dl.minio.io/client/mc/release/linux-amd64/mc.shasum: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
will see that right now.

**Comment by vadmeste** [comment]
̀̀`̀`
diff --git a/update-main.go b/update-main.go
index 064240c..140269f 100644
--- a/update-main.go
+++ b/update-main.go
@@ -145,9 +145,9 @@ func getReleaseUpdate(updateURL string) {
        newUpdateURLPrefix := updateURL + "/" + runtime.GOOS + "-" + runtime.GOARCH
        newUpdateURL := newUpdateURLPrefix + "/mc.shasum"
 
-       // Instantiate a new client with 1 sec timeout.
+       // Instantiate a new client with 30 sec timeout.
        client := &http.Client{
-               Timeout: 500 * time.Millisecond,
+               Timeout: 30000 * time.Millisecond,
        }
 
        // Get the downloadURL.
̀`̀`

@harshavardhana, this will fix the problem

**Comment by vadmeste** [comment]
@harshavardhana, it was meant to be 500 seconds instead ?

**Comment by harshavardhana** [comment]
Yes it is on purpose. Looks like we need a bigger timeout may be server is busy.

**Comment by vadmeste** [comment]
Wait, in the current code, it is 500 ms not 500 seconds

**Comment by vadmeste** [comment]
why do you need it to be too short? are you planning to fetch update for each mc execution (and track users) ? :D

**Comment by harshavardhana** [comment]
No it is only for `mc update` all it requires us 500ms to fetch this file on a good enough connection. Looks like 3secs is a valid value.

**Comment by harshavardhana** [comment]
Can you send a fix @vadmeste ?
