### ISSUE TITLE
Insufficient permissions to access s3 file using IAM user credentials

### ISSUE THREAD

**Issue by accaldwell** [minio/mc#1705]
Attempting to use mc to copy a file to my s3 bucket gives the following error:

`mc: <ERROR> Failed to copy ‘/myfile’. Insufficient permissions to access this file ‘https://mybucket.s3.amazonaws.com/myfile’`

I am using credentials which work fine with the aws cli tools. I can list the bucket contents fine, so I know my keys aren't wrong. Even adding the "s3:*" permission to my user does not work. So the question is, what permission(s) does mc need to write to remote s3 files?

**Comment by harshavardhana** [comment]
> Attempting to use mc to copy a file to my s3 bucket gives the following error:
> 
> mc: <ERROR> Failed to copy ‘/myfile’. Insufficient permissions to access this file ‘https://mybucket.s3.amazonaws.com/myfile’
> 
> I am using credentials which work fine with the aws cli tools. I can list the bucket contents fine, so I know my keys aren't wrong. Even adding the "s3:*" permission to my user does not work. So the question is, what permission(s) does mc need to write to remote s3 files?

In sufficient permission seems to be local file not the remote file.  do you have access to '/myfile' ?

**Comment by harshavardhana** [comment]
Can you explain a bit more on what you are trying to do in detail?

**Comment by accaldwell** [comment]
I can: 
`mc cp myfile my_local_copy`

I can't:
`mc cp myfile mys3alias/myfile`

**Comment by accaldwell** [comment]
My temporarily very unrestrictive IAM policy is:

`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket"
            ]
        }
    ]
}
`

**Comment by harshavardhana** [comment]
> { "Version": "2012-10-17", "Statement": [ { "Effect": "Allow", "Action": [ "s3:*" ], "Resource": [ "arn:aws:s3:::mybucket" ] } ] }

@accaldwell - does a myfile already exist  at `mys3alias/myfile` ?

**Comment by accaldwell** [comment]
No.

**Comment by harshavardhana** [comment]
> No.

Can you print the "mc --debug" output of the operation - most probably it's a GetBucketLocation issue.

**Comment by accaldwell** [comment]
See attached file.

[mc_debug.txt](https://github.com/minio/mc/files/243021/mc_debug.txt)

**Comment by harshavardhana** [comment]
S3 returns back an error 

```
mc: <DEBUG> PUT /myfile?partNumber=1&uploadId=RNTckSSTX7dvMjLgA25vjxokNp3yDlwr5f05623kIweVMyJdYY8LbEZI3JiIb6JIdMNgfQ6W.kCyoxZ7z3AXSF29CkvSm32EhXS6ujq7CnKdmMWkxnI3Q4W60Vomjm.y HTTP/1.1
Host: mybucket.s3-us-west-2.amazonaws.com
User-Agent: Minio (freebsd; amd64) minio-go/1.0.1 mc/2016-04-01T00:22:11Z
Content-Length: 10485760
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160429/us-west-2/s3/aws4_request, SignedHeaders=content-md5;expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: vNgzGxPhmK5ewkRnPomdsQ==
Expect: 100-continue
X-Amz-Content-Sha256: 15c62edbc758a93277ae4886be2610eacc32a03ae876cc0c31d85779bb9fa0e1
X-Amz-Date: 20160429T184327Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 29 Apr 2016 18:43:27 GMT
Server: AmazonS3
X-Amz-Id-2: GxMylDNHjoQ3LSRC7v/mfTnrWLZdlnBooAcmBsMKckCMJyRwtI9ty76K9jnkPgzNzql8LRzwAhM=
X-Amz-Request-Id: C6E0DF817562BCAC

f3
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C6E0DF817562BCAC</RequestId><HostId>GxMylDNHjoQ3LSRC7v/mfTnrWLZdlnBooAcmBsMKckCMJyRwtI9ty76K9jnkPgzNzql8LRzwAhM=</HostId></Error>
0

mc: <DEBUG> Response Time:  206.266261ms

mc: <ERROR> Failed to copy ‘myfile’. Insufficient permissions to access this file ‘https://mybucket.s3.amazonaws.com/myfile’
 (3) cp-main.go:308 main.doCopySession.func1(..) Tags: [myfile]
 (2) cp-main.go:169 main.doCopy(..) Tags: [https://mybucket.s3.amazonaws.com/myfile]
 (1) common-methods.go:85 main.putTargetStreamFromAlias(..) Tags: [satels3, https://mybucket.s3.amazonaws.com/myfile]
 (0) client-s3.go:179 main.(*s3Client).Put(..)
```

You don't have enough permissions to do multipart upload operation, you need to have an IAM policy as below. 

```
{  
   "Version":"2012-10-17",
   "Statement":[  
      {  
         "Effect":"Allow",
         "Action":[  
            "s3:*"
         ],
         "Resource":[  
            "arn:aws:s3:::mybucket"
         ]
      },
      {  
         "Effect":"Allow",
         "Action":[  
            "s3:*"
         ],
         "Resource":[  
            "arn:aws:s3:::mybucket/*"
         ]
      }
   ]
}
```

**Comment by accaldwell** [comment]
My mistake that I omitted the second section when updating my policy. Your policy works, but my original one does not:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*"
            ]
        }
    ]
}`

So back to my original question, which permissions are required? My original IAM policy was sufficient for every other S3 tool I've used.

**Comment by harshavardhana** [comment]
> So back to my original question, which permissions are required? My original IAM policy was sufficient for every other S3 tool I've used.

It is not, if you uploaded a file in multipart form - it wouldn't work even with s3 tools.  'mc' does it automatic for all files bigger than 5MB are uploaded as multipart.

**Comment by harshavardhana** [comment]
> So back to my original question, which permissions are required? My original IAM policy was sufficient for every other S3 tool I've used.
> It is not, if you uploaded a file in multipart form - it wouldn't work even with s3 tools. 'mc' does it automatic for all files bigger than 5MB are uploaded as multipart.

As a fall back it also attempts to do single PUT operation, which i don't think it did in your case. Since the second attempt also failed.

**Comment by accaldwell** [comment]
It is possible I hadn't used these credentials to upload large files yet...

Adding s3:ListBucketMultipartUploads allows my minimal policy to work:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket"
]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*"
            ]
        }
    ]
}`

Permission found here: https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuAndPermissions.html

Much appreciated your assistance, closing this as its not a bug.

**Comment by harshavardhana** [comment]
> It is possible I hadn't used these credentials to upload large files yet...
> 
> Adding s3:ListBucketMultipartUploads allows my minimal policy to work:
> 
> { "Version": "2012-10-17", "Statement": [ { "Effect": "Allow", "Action": [ "s3:ListBucket", "s3:ListBucketMultipartUploads" ], "Resource": [ "arn:aws:s3:::mybucket" ] }, { "Effect": "Allow", "Action": [ "s3:PutObject", "s3:GetObject", "s3:DeleteObject" ], "Resource": [ "arn:aws:s3:::mybucket/*" ] } ] }
> 
> Permission found here: https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuAndPermissions.html
> 
> Much appreciated your assistance, closing this as its not a bug.

No problem @accaldwell anytime.
