### ISSUE TITLE
Binary built with tip Go version is completely unusable because of some runtime checks

### ISSUE THREAD

**Issue by artyom** [minio/mc#1709]
```
go (master) ¶ mc
mc: <ERROR> Unable to determine current go version. Malformed version: vel +61602b0 Fri May 6 17:04:11 2016 +0000
1 go (master) ¶ go version
go version devel +61602b0 Fri May 6 17:04:11 2016 +0000 darwin/amd64
```

This is the first time I've ever see such runtime checks against Go version. Can't such checks be implemented as build-time ones (version-specific build tags)?

**Comment by harshavardhana** [comment]
> This is the first time I've ever see such runtime checks against Go version. Can't such checks be implemented as build-time ones (version-specific build tags)?

Using 'go get' we cannot enforce such checks since there is no control on how one can build a project, if you used 'make' these are enforced and verified. 

There is an additional runtime check so that unsupported versions of Golang are not used.  We do not support 'tip' but we can relax this check and see a golang devel version.

**Comment by artyom** [comment]
Cannot this be enforced with build tag `+build go1.6`? This scenario is explicitly described [in documentation](https://golang.org/pkg/go/build/) under Build Constraints section:

```
- "go1.1", from Go version 1.1 onward
- "go1.2", from Go version 1.2 onward
- "go1.3", from Go version 1.3 onward
- "go1.4", from Go version 1.4 onward
- "go1.5", from Go version 1.5 onward
- "go1.6", from Go version 1.6 onward
```

Having this flag would prevent project from building if it's `go get`'ted with unsupported version.

**Comment by harshavardhana** [comment]
> Cannot this be enforced with build tag +build go1.6? This scenario is explicitly described in documentation under Build Constraints section:
> 
> - "go1.1", from Go version 1.1 onward
> - "go1.2", from Go version 1.2 onward
> - "go1.3", from Go version 1.3 onward
> - "go1.4", from Go version 1.4 onward
> - "go1.5", from Go version 1.5 onward
> - "go1.6", from Go version 1.6 onward
> Having this flag would prevent project from building if it's go get'ted with unsupported version.

Sure thanks!
