### ISSUE TITLE
mc creates a local directory on mc mb - messaging needs to be correct. 

### ISSUE THREAD

**Issue by deekoder** [minio/mc#1712]
Steps to repro : 

./mc mb abc/minio-store
Bucket created successfully ‘abc/minio-store’.

Since abc is not an alias, it creates this locally. It should atleast indicate that this was done locally and not on the remote abc server.

**Comment by harshavardhana** [comment]
Editing the text "mc creates a local directory on mc mb when the host is not reachable" - this is incorrect
 if you have an alias named 'abc' which points to a URL and it's not accessible then 'mc' does throw an error. 

This is a problem when such an alias doesn't exist in the config, 'mc' treats it as a local directory.

**Comment by GarimaKapoor** [comment]
Works as expected.
