### ISSUE TITLE
mc ls does not list properly

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/mc#1713]
```
azureuser@minio-test:/mnt$ mc ls myminio/test1/0bytefil
[2016-05-10 19:54:07 UTC]     0B 0bytefile
[2016-05-10 19:54:38 UTC]     0B 0bytefile.1
azureuser@minio-test:/mnt$ mc ls myminio/test1/0bytefile
[2016-05-10 19:54:07 UTC]     0B 0bytefile
azureuser@minio-test:/mnt$ 
```

--debug indicates that if HEAD on the prefix succeeds it does not List(), but if HEAD fails only then it List()s

**Comment by harshavardhana** [comment]
> azureuser@minio-test:/mnt$ mc ls myminio/test1/0bytefil
> [2016-05-10 19:54:07 UTC]     0B 0bytefile
> [2016-05-10 19:54:38 UTC]     0B 0bytefile.1
> azureuser@minio-test:/mnt$ mc ls myminio/test1/0bytefile
> [2016-05-10 19:54:07 UTC]     0B 0bytefile
> azureuser@minio-test:/mnt$ 
> --debug indicates that if HEAD on the prefix succeeds it does not List(), but if HEAD fails only then it List()s

Yeah we need to avoid that.. Stat() shouldn't be a requirement . It is perhaps related to url2Stat() which does HEAD and GET
