### ISSUE TITLE
mc s3 doesn't support mixed case / uppercase bucket name

### ISSUE THREAD

**Issue by raff** [minio/mc#1715]
mc ls s3/Bucket returns the error "Bucket name contains invalid characters."

the bucket was created in AWS console, contains uppercase character but can be accessed with any other client

**Comment by raff** [comment]
From: http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

The US East (N. Virginia) region currently allows more relaxed standards for bucket naming, which can result in a bucket name that is not DNS-compliant. For example,  MyAWSBucket is a valid bucket name, even though it contains uppercase letters. If you try to access this bucket by using a virtual-hosted–style request (http://MyAWSBucket.s3.amazonaws.com/yourobject), the URL resolves to the bucket myawsbucket and not the bucket  MyAWSBucket. In response, Amazon S3 will return a "bucket not found" error.

So, you are actually doing correct validation, but this may not work on some existing buckets. Maybe a configuration option to relax the check would be helpful.

**Comment by harshavardhana** [comment]
> So, you are actually doing correct validation, but this may not work on some existing buckets. Maybe a configuration option to relax the check would be helpful.

`mc` is working as intended Bucket names should be DNS compliant - capitalized names are not DNS compliant and only a feature of us-east-1. 

From: http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

```While the US East (N. Virginia) region currently allows non-compliant DNS bucket naming, we are moving to the same DNS-compliant bucket naming convention for the US East (N. Virginia) region in the coming months.
``` 

From: http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
```To avoid this problem, we recommend as a best practice that you always use DNS-compliant bucket names regardless of the region in which you create the bucket. For more information about virtual-hosted–style access to your buckets, see Virtual Hosting of Buckets.
```

**Comment by harshavardhana** [comment]
> So, you are actually doing correct validation, but this may not work on some existing buckets. Maybe a configuration option to relax the check would be helpful.

Relaxing can be done but it is tricky and involves hacks for only a matter of time before `us-east-1` also moves to the DNS naming convention.  Unsure what happens to existing buckets when `us-east-1` moves as well.
