### ISSUE TITLE
mc mirror outputs error for directory created in S3 console

### ISSUE THREAD

**Issue by willmoffat** [minio/mc#1716]
To reproduce, use Amazon S3 console to
* create a bucket
* create a directory `images` using 'Create Folder'

Setup credentials.

Test:
`mc mirror s3/s3.jooki.rocks .`
Responds with:
`mc: <ERROR> Failed to copy ‘https://s3.amazonaws.com/s3.jooki.rocks/images’. Object key is missing, object key cannot be empty`

However the files inside images/ are actually mirrored.

Tested using `mc` built from latest source. (current release fails to mirror at all)

**Comment by vadmeste** [comment]
I followed the same steps using aws-cli but I wasn't able to reproduce the bug. Anyway, progress was made to mirror cmd since this issue was opened.
@harshavardhana, could you confirm that this issue doesn't exist anymore with the actual Amazon S3 console ?

**Comment by felixbuenemann** [comment]
This issue also exists for buckets where files where uploaded using CloudBerry S3 Explorer, there's a free version available [here](http://www.cloudberrylab.com/free-amazon-s3-explorer-cloudfront-IAM.aspx). The error is shown for each "directory".

I beliebe the problem is that there are keys that end with "/", for "folder_a/folder_b/folder_c/".

Listing such a "folder" with the python aws cli looks like this:

```
aws s3api head-object --bucketmy-bucket --key folder_a/folder_b/folder_c/
{
    "AcceptRanges": "bytes",
    "ContentType": "application/octet-stream",
    "LastModified": "Fri, 02 Sep 2016 10:19:41 GMT",
    "ContentLength": 0,
    "VersionId": "CcdRFntHQz6J3PFU_mI_I2BycdynQPEj",
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "Metadata": {}
}
```

My guess is that the minio client splits the key on the "/" divider and takes the last part as the filename, which would be empty, if the key ends with a slash, which would lead the the error message: "Object key is missing, object key cannot be empty"

**Comment by felixbuenemann** [comment]
The following code looks suspicious:

https://github.com/minio/mc/blob/80b0aa3842ef02d04823a4b0f100638fa2955f19/cmd/client-s3.go#L739

```go
	// Remove trailing slashes needed for the following ListObjects call.
	// In addition, Stat() will be as smart as the client fs version and will
	// facilitate the work of the upper layers
	object = strings.TrimRight(object, string(c.targetURL.Separator))
```

If the trailing slash is removed on the key `a/b/c/`, it would list the nonexistant key `a/b/c` which would return a 404 error.

**Comment by felixbuenemann** [comment]
Btw. on current master the error is now:

```
Requested file ‘/local/path/to/a/b/c’ is not a regular file.

**Comment by felixbuenemann** [comment]
@vadmeste No idea why my comment caused you to be unassigned…

**Comment by felixbuenemann** [comment]
It would be great if this bug could be fixed. I can no longer use mc because of it.

**Comment by vadmeste** [comment]
@felixbuenemann, sorry for the delay. We are currently working on this, we'll keep you updated.

**Comment by felixbuenemann** [comment]
Thanks for the update. It is very easy to test this using the AWS S3 Console, simply choose a bucket and then click "Create Folder" to create an empty "directory".

If you inspect the key using the aws cli you get a result like this:

```shell
$ aws s3api head-object --bucket my-bucket --key 'test-aws-console/'
```
```json
{
    "AcceptRanges": "bytes",
    "ContentType": "binary/octet-stream",
    "LastModified": "Fri, 30 Sep 2016 20:27:53 GMT",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

**Comment by medBouzid** [comment]
I was playing with mc command with my dreamobjects bucket and I got plenty errors similar to the following

```
mc: <ERROR> Unexpected error during monitoring. 
mc: <ERROR> Failed to copy ‘https://objects.dreamhost.com/cara/aczema2.png’. Object key is missing, object key cannot be empty
mc: <ERROR> Failed to copy ‘https://objects.dreamhost.com/cara/error_upload.png’. Object key is missing, object key cannot be empty
......
......
```

The command I used is this :  `./mc mirror --watch backups/cara restore/` and I expected that every time I upload something in my bucket it will be mirrored to the /restore folder, however it doesn't seems looking for changes, it does only backups files the first time I run it (with errors of `Object key is missing, object key cannot be empty` for some files like above)

**Comment by vadmeste** [comment]
@medBouzid, --watch works only with Minio servers, mc should show a more meaningful error instead of `mc: <ERROR> Unexpected error during monitoring. `, we will fix that.

However, the other error is somewhat weird, what's your mc version? besides can you run your command again with --debug flag and paste its output here ?

**Comment by medBouzid** [comment]
@vadmeste Thank you about the information (watch works only with Minio servers), I thought there maybe some errors with those files so I deleted them, and now when I run the mirror command I still get `mc: <ERROR> Unexpected error during monitoring.`

```
./mc mirror --watch --debug  backups/cara /restore
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> GET /cara/?location= HTTP/1.1
Host: objects.dreamhost.com
User-Agent: Minio (linux; amd64) minio-go/2.0.3 mc/2017-02-06T20:16:19Z
Authorization: AWS4-HMAC-SHA256 Credential=e3uISRwmim-7Cey9tNVJ/20170310/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20170310T151615Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 136
Date: Fri, 10 Mar 2017 15:16:16 GMT
X-Amz-Request-Id: tx0000000000000008e29b3-0058c2c340-13a7d23b-default

mc: <DEBUG> Response Time:  432.230797ms

mc: <DEBUG> GET /cara/?location= HTTP/1.1
Host: objects.dreamhost.com
User-Agent: Minio (linux; amd64) minio-go/2.0.3 mc/2017-02-06T20:16:19Z
Authorization: AWS4-HMAC-SHA256 Credential=e3uISRwmim-7Cey9tNVJ/20170310/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20170310T151615Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 136
Date: Fri, 10 Mar 2017 15:16:16 GMT
X-Amz-Request-Id: tx0000000000000008e29a9-0058c2c340-13a8a9de-default

mc: <DEBUG> Response Time:  435.70481ms

mc: <DEBUG> GET /cara/?events=s3%3AObjectCreated%3A%2A&events=s3%3AObjectRemoved%3A%2A&prefix=&suffix= HTTP/1.1
Host: objects.dreamhost.com
User-Agent: Minio (linux; amd64) minio-go/2.0.3 mc/2017-02-06T20:16:19Z
Authorization: AWS4-HMAC-SHA256 Credential=e3uISRwmim-7Cey9tNVJ/20170310/us-west-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Expect: 100-continue
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20170310T151616Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 202
Accept-Ranges: bytes
Content-Type: application/xml
Date: Fri, 10 Mar 2017 15:16:16 GMT
X-Amz-Request-Id: tx0000000000000008e29ac-0058c2c340-13a8a9de-default

<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx0000000000000008e29ac-0058c2c340-13a8a9de-default</RequestId><HostId>13a8a9de-default-default</HostId></Error>mc: <DEBUG> Response Time:  81.12869ms

mc: <ERROR> Unexpected error during monitoring. 
 (0) client-s3.go:430 cmd.(*s3Client).Watch.func2(..)
 Release-Tag:RELEASE.2017-02-06T20-16-19Z | Commit:2c8115de4edc | Host:backup | OS:linux | Arch:amd64 | Lang:go1.7.4 | Mem:3.9MB/7.2MB | Heap:3.9MB/5.7MB
mc: <DEBUG> GET /cara/?max-keys=1000 HTTP/1.1
Host: objects.dreamhost.com
User-Agent: Minio (linux; amd64) minio-go/2.0.3 mc/2017-02-06T20:16:19Z
Authorization: AWS4-HMAC-SHA256 Credential=e3uISRwmim-7Cey9tNVJ/20170310/us-west-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Expect: 100-continue
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20170310T151616Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128674
Content-Type: application/xml
Date: Fri, 10 Mar 2017 15:16:16 GMT
X-Amz-Request-Id: tx0000000000000008e29b6-0058c2c340-13a7d23b-default

mc: <DEBUG> Response Time:  186.707361ms

```

**Comment by medBouzid** [comment]
I run `./mc mirror  backups/cara /restore` without `--watch` and now it seems working without error, it seems that `--watch` caused the `mc: <ERROR> Unexpected error during monitoring.`  the error is not verbose so hope you fix that guys :)

For non Minio servers, is it a good idea to use cron job and set it to mirror every 30 min ?

**Comment by vadmeste** [comment]
> For non Minio servers, is it a good idea to use cron job and set it to mirror every 30 min ?

Not sure about your use case but it is generally okay to do since mirror will only copy new objects.
