### ISSUE TITLE
mc: rm --incomplete at bucket level will remove the bucket itself

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1718]
```
$ mc mb myminio/bucket/
$ mc cp 128mb.bin myminio/bucket/
Ctrl-C (interrupt upload)
$ mc rm --incomplete --recursive --force myminio/bucket/
Removed ‘myminio/bucket’.
```
The fix seems to be easy, will create a PR

**Comment by harshavardhana** [comment]
> $ mc mb myminio/bucket/
> $ mc cp 128mb.bin myminio/bucket/
> Ctrl-C (interrupt upload)
> $ mc rm --incomplete --recursive --force myminio/bucket/
> Removed ‘myminio/bucket’.

This is expected.

**Comment by vadmeste** [comment]
The bucket is really removed. Personally, after reading the help, I expect --incomplete will take care of  incomplete uploads only.

**Comment by krishnasrinivas** [comment]
I think the desired behavior will be not to remove the bucket when the user is trying to remove incomplete uploads.

**Comment by harshavardhana** [comment]
> I think the desired behavior will be not to remove the bucket when the user is trying to remove incomplete uploads.

```
$ mc rm --incomplete --recursive --force play/mbtest
```

Doesn't seem to be deleting the bucket @vadmeste can you paste your output again?

I only see bucket being deleted for 

```
$ mc rm --recursive --force play/mbtest
```

**Comment by harshavardhana** [comment]
Also the behavior is different with ending '/' and without to differentiate between what the 'rm' should do. 

```
$ mc rm --recursive --force play/mbtest/
```

Doesn't delete the bucket.

**Comment by harshavardhana** [comment]
Another test with s3

```
$ mc rm -I --recursive --force s3/miniocloud/
Removed ‘s3/miniocloud/TransferXL-08nSnGFPtjbP1.zip’.
``` 

Looks like you are hitting a bug from the minio server which @krishnasrinivas fixed in master, the listing was improper. That is the reason why it would end up deleting the bucket.

**Comment by vadmeste** [comment]
@harshavardhana, you should upload a file and interrupt uploading, then try again!

**Comment by vadmeste** [comment]
@harshavardhana, yes, the patch of @krishnasrinivas that you merged few moments ago fixed the problem

**Comment by vadmeste** [comment]
however, removing incomplete upload seems to be not working now
```
~/w/gospace/src/github.com/minio/mc $ mc rm --incomplete --recursive --force myminio/bucket/
Removed ‘myminio/bucket/128mb.bin’.
~/w/gospace/src/github.com/minio/mc $ mc rm --incomplete --recursive --force myminio/bucket/
Removed ‘myminio/bucket/128mb.bin’.
```

**Comment by harshavardhana** [comment]
> however, removing incomplete upload seems to be not working now
> 
> ~/w/gospace/src/github.com/minio/mc $ mc rm --incomplete --recursive --force myminio/bucket/
> Removed ‘myminio/bucket/128mb.bin’.
> ~/w/gospace/src/github.com/minio/mc $ mc rm --incomplete --recursive --force myminio/bucket/
> Removed ‘myminio/bucket/128mb.bin’.

Can you open a bug on minio server?  - 'mc' is working as expected.

**Comment by vadmeste** [comment]
okay, btw this code in client-s3.go doesn't treat the case when incomplete == true, object == "" and bucket != ""
```
// Remove - remove object or bucket.                                             
func (c *s3Client) Remove(incomplete bool) *probe.Error {                        
    bucket, object := c.url2BucketAndObject()                                    
    // Remove only incomplete object.                                            
    if incomplete && object != "" {                                              
        e := c.api.RemoveIncompleteUpload(bucket, object)                        
        return probe.NewError(e)                                                 
    }                                                                            
    var e error                                                                  
    if object == "" {                                                            
        e = c.api.RemoveBucket(bucket)                                           
    } else {                                                                     
        e = c.api.RemoveObject(bucket, object)                                   
    }                                                                            
    return probe.NewError(e)                                                     
}
```

**Comment by harshavardhana** [comment]
> okay, btw this code in client-s3.go doesn't treat the case when incomplete == true, object == "" and bucket != ""
> 
> // Remove - remove object or bucket.                                             
> func (c *s3Client) Remove(incomplete bool) *probe.Error {                        
>     bucket, object := c.url2BucketAndObject()                                    
>     // Remove only incomplete object.                                            
>     if incomplete && object != "" {                                              
>         e := c.api.RemoveIncompleteUpload(bucket, object)                        
>         return probe.NewError(e)                                                 
>     }                                                                            
>     var e error                                                                  
>     if object == "" {                                                            
>         e = c.api.RemoveBucket(bucket)                                           
>     } else {                                                                     
>         e = c.api.RemoveObject(bucket, object)                                   
>     }                                                                            
>     return probe.NewError(e)                                                     
> }

That is correct we can handle it explicitly.  Even 'rm' is not invoking when 'object' is '==' empty.

**Comment by vadmeste** [comment]
I am not able to reproduce this issue anymore. I guess it is fixed in minio server.
