### ISSUE TITLE
mc mirror fails with too many files open error

### ISSUE THREAD

**Issue by krisis** [minio/mc#1721]
```
mc: <ERROR> Failed to copy _https://play.minio.io:9000/testbucket/minio-go/.git/objects/12/c7ac818386f36d33f18527c38a478827c473bb_. Get https://play.minio.io:9000/testbucket/minio-go/.git/objects/12/c7ac818386f36d33f18527c38a478827c473bb: dial tcp: lookup play.minio.io on 127.0.0.1:53: dial udp 127.0.0.1:53: socket: too many open files

```

**Comment by harshavardhana** [comment]
Please add more context here amount of files what operation failed, was it session resume? etc.

**Comment by krisis** [comment]
mc mirror fails with the error mentioned above in the first attempt. It fails on a session resume too.

The following command was issued. 
```
mc mirror play/testbucket kp-xl/play
```

The total no. of objects to be mirrored (found using recursive listing),
```
noone@nowhere:~/kp/tests$ mc ls -r play/testbucket/ | wc -l
5023
```

**Comment by harshavardhana** [comment]
> mc mirror fails with the error mentioned above in the first attempt. It fails on a session resume too.
> 
> The following command was issued.
> 
> mc mirror play/testbucket kp-xl/play
> The total no. of objects to be mirrored (found using recursive listing),
> 
> noone@nowhere:~/kp/tests$ mc ls -r play/testbucket/ | wc -l
> 5023

Can you also paste the 'mc version' ?
