### ISSUE TITLE
`mc session list` errors out when one or more session data files are missing - May 24

### ISSUE THREAD

**Issue by krisis** [minio/mc#1723]
```
mc: <ERROR> Unable to open session data file "/home/minio/.mc/session/JwaZuaWY.data". open /home/minio/.mc/session/JwaZuaWY.data: no such file or directory
```

**Comment by krisis** [comment]
I think the following captures the expected behaviour for `mc session`

[ ] -`mc session list` - should return the list of all sessions, skipping the 'broken' ones. e.g, sessions with missing `.data` file.

[ ] - `mc session clear <broken-session-name>` - should remove the session even in the absence of `.json` or the `.data` file.
 
[ ] - Similarly, `mc session clear all` - should remove all 'broken' sessions.

@harshavardhana Does that above make sense?

**Comment by harshavardhana** [comment]
> @harshavardhana Does the above make sense?

👍

**Comment by krisis** [comment]
I propose a change to the above behaviour specific to `mc session clear all`. I think removing partially available session data, i.e when only one of `.data` or `.json` file is present, for all such sessions would become difficult to grasp or avoid, once the command is issued. So, it makes sense to allow 'forceful' removal of session only when the session ID is provided explicitly. i.e, only in the case of `mc session clear <broken-session-id>`.

N B This doesn't alter the behaviour when the session to be cleared is pristine.
@harshavardhana Let me know if this makes sense.

**Comment by harshavardhana** [comment]
> N B This doesn't alter the behaviour when the session to be cleared is pristine.
> @harshavardhana Let me know if this makes sense.

Yeah agreed it's a more correct behavior.
