### ISSUE TITLE
`mc ls <alias>` fails

### ISSUE THREAD

**Issue by hackintoshrao** [minio/mc#1725]
`mc ls <alias>` fails on current master. It fails with the following error 

`$mc ls s3/`
`mc: <ERROR> Unable to stat target ‘s3/’. Bucket name cannot be empty.`

**Comment by hackintoshrao** [comment]
@krisis is checking this out.

**Comment by harshavardhana** [comment]
> @krisis is checking this out.

I think it's recent fix from @vadmeste

**Comment by krisis** [comment]
`clnt.Stat()` returns `BucketNameEmpty` error which is expected for `objectStorage` `clientURLType` but not so for `fileSystem`. With the introduction of #1724, `mc ls play` fails on `BucketNameEmpty`. Need to find a way by which we can ignore this error if backend is not `fileSystem`.

**Comment by vadmeste** [comment]
@krisis, yes, my bad.. Actually, I'd like to think that at certain layer in the app, all s3/fs differences should disappear, but I don't know if this is good or feasible. For the moment, I think it is sufficient to perform the old listing behavior when Stat returns an error.
