### ISSUE TITLE
feature: mc mirror myminio/ s3/ works and doesn't return an error

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1732]
I think this is a good feature to have, the user won't create manually all buckets and mirror one by one.. In mc code, it seems to be enough to make mkdir, stat, .. works at alias level to make everything works as expected

**Comment by harshavardhana** [comment]
> I think this is a good feature to have, the user won't create manually all buckets and mirror one by one.. In mc code, it seems to be enough to make mkdir, stat, .. works at alias level to make everything works as expected

👍

**Comment by harshavardhana** [comment]
Only problem with this feature is that s3 has 100 bucket limit per account, where as we do not have such limits on 'Minio server'. so it might not cleanly work all the time.

**Comment by vadmeste** [comment]
If we do this with a generic way, it will affect other commands like cp:
```mc cp ./ myminio/``` will create some buckets but will show errors because it can't copy files directly under myminio/

Otherwise, we can make mirror command smarter to create buckets on the fly.

**Comment by harshavardhana** [comment]
> If we do this with a generic way, it will affect other commands like cp:
> mc cp ./ myminio/ will create some buckets but will show errors because it can't copy files directly under myminio/
> 
> Otherwise, we can make mirror command smarter to create buckets on the fly.

After thinking about it, it is not easy to implement. Because bucket creation on s3 is not cheap would easily lead to issues.  It is easier as it is today and with no confusion.

**Comment by GarimaKapoor** [comment]
We deliberately limited that to discourage bad behavior.
