### ISSUE TITLE
mc blocks and never returns or times out

### ISSUE THREAD

**Issue by balamurugana** [minio/mc#1733]
If server holds the connection and doesn't return any response for long while, mc never returns or times out.

Is this expected behaviour?

**Comment by harshavardhana** [comment]
> Is this expected behaviour?

Yes it is expected - golang http doesn't timeout. The request should be explicitly cancelled, it is servers problem.

**Comment by balamurugana** [comment]
> Yes it is expected - golang http doesn't timeout. The request should be explicitly cancelled, it is servers problem.

We could do timeout like
```golang
timeout := time.Duration(5 * time.Second)
client := http.Client{
    Timeout: timeout,
}
client.Get(url)
```

As we expect server to close/time-out the connection, closing this as not a bug.

**Comment by harshavardhana** [comment]
> timeout := time.Duration(5 * time.Second)
> client := http.Client{
>     Timeout: timeout,
> }
> client.Get(url)
> As we expect server to close/time-out the connection, closing this as not a bug.

No this we used to do, but the http client timeout is really not the right option for us.  What really happens is for a large getObject operation which takes more than 10mins it would cancel the request. 

So it is not entirely implemented the desired behavior we want.

**Comment by balamurugana** [comment]
> No this we used to do, but the http client timeout is really not the right option for us. What really happens is for a large getObject operation which takes more than 10mins it would cancel the request.
> 

Got it.  I thought `Timeout` value in http.Client is for idle timeout or tcp socket read timeout.

By this, is it good to disable timeout in our other SDKs (eg.minio-java has default timeout)?

**Comment by harshavardhana** [comment]
> Got it. I thought Timeout value in http.Client is for idle timeout or tcp socket read/write timeout.
> 
> By this, is it good to disable timeout in our other SDKs (eg.minio-java has default timeout)?

No it depends on the implementation Golang http is odd in this manner, other libs are fine.  They perhaps might have implemented it based on idle timeout.

**Comment by balamurugana** [comment]
> No it depends on the implementation Golang http is odd in this manner, other libs are fine. They perhaps might have implemented it based on idle timeout.

Got it. Thanks.
