### ISSUE TITLE
Feature: mc policy list

### ISSUE THREAD

**Issue by mkash32** [minio/mc#1736]
I was thinking it would be nice to have a command `mc access list <alias>/<bucket-name>` which would list the policies in a certain bucket. This command would provide an easy way for an admin to know the policy status of a particular bucket. It would come in handy when trying to modify/remove policies.
example:
```
$ mc access readonly myminio/mybucket/abc/
Access permission for ‘myminio/mybucket/abc/' is set to ‘readonly’
$ mc access writeonly myminio/mybucket/def
Access permission for ‘myminio/mybucket/def’ is set to ‘writeonly’
$ mc access list myminio/mybucket
mybucket/abc/*   : 'readonly'
mybucket/def*    : 'writeonly'
```

**Comment by hackintoshrao** [comment]
@harshavardhana @abperiasamy

**Comment by abperiasamy** [comment]
It is already there. You dont need to explicitly pass list sub-command. 
$ mc access myminio/mybucket/def

If it is not obvious, it can be considered as a UI bug and we can make list an explicit sub-command.

**Comment by mkash32** [comment]
It becomes useful in cases where we want to remove a policy. If we set the policy `mc access readonly myminio/mybucket/abc` and later on we are working with an object `myminio/mybucket/abc/ex.txt`. mc access will tell us the policy which applies to ex.txt but it is not obvious how to remove/modify the policy, we would need to know the base prefix of the policy which was set. For a small case like this with only one policy it wouldn't be a problem to remember, but when we have a large number of policies it would be difficult to keep track of all the the base policy prefixes which we need to know to make any modifications.

**Comment by harshavardhana** [comment]
> It becomes useful in cases where we want to remove/modify a policy. If we set the policy mc access readonly myminio/mybucket/abc and later on we are working with an object myminio/mybucket/abc/ex.txt. mc access will tell us the policy which applies to ex.txt but it is not obvious how to remove/modify the policy, we would need to know the base prefix of the policy which was set.
> For a small case like this with only one policy it wouldn't be a problem to remember, but when we have a large number of policies it would be difficult to keep track of all the the base policy prefixes which we need to know to make any modifications.

There is no policy removal as such because of the implicit behavior of 'mc access' command - which performs `set` , `get` and `reset` so the command line currently employs implicit behavior rather than explicit command line arguments.  It is less work in terms of overall command line understanding.

What type of policies have been applied on each prefix requires a different kind of work on the client side example `mc access list myminio/mybucket`  means minio-go needs a new API which returns back a list of policies for a common prefix. Right now it is only an 'exact' match.

**Comment by mkash32** [comment]
> There is no policy removal as such because of the implicit behavior of 'mc access' command - which performs set , get and reset so the command line currently employs implicit behavior rather than explicit command line arguments.

Oh right sorry, by "remove" I meant setting access to 'none' on an already existing policy.

> What type of policies have been applied on each prefix requires a different kind of work on the client side example mc access list myminio/mybucket means minio-go needs a new API which returns back a list of policies for a common prefix. Right now it is only an 'exact' match.
Yeah I was thinking of making an api function which would achieve the 'list' functionality by using the pre-existing api. 

The below code will list all of the policies in a given bucket:
```
// List all of the policies present in a given bucket
// Collects the object prefixes from the resource of bucket policy statements, 
// and calls identifyPolicyType on each of the prefixes and finally prints

func listPolicies(bucketName string, bucketPolicy BucketAccessPolicy) {
	var objectPrefixes []string

    // collect all of the object prefixes 
	for _, statement := range bucketPolicy.Statements {
		for _, resource := range statement.Resources {
			if resource != awsResourcePrefix+bucketName {
				// collect the object prefix by splitting resource into 2 strings, 
                // second string will be the object prefix of the resource
				prefix := strings.SplitN(resource, "/", 2)[1]
				prefix = prefix[:len(prefix)-1] // remove trailing '*'
				objectPrefixes = append(objectPrefixes, prefix)
			}
		}
	}

	var policies []BucketPolicy
	for _, prefix := range objectPrefixes {
		policy := identifyPolicyType(bucketPolicy, bucketName, prefix)
		fmt.Println(bucketName+"/"+prefix+"*", ":", policy)
	}
}
```

Running this function with a bucket policy of my bucket which has 'writeonly' on abc and 'readonly' on def gave me the following output:
```
my-bucket/abc* : writeonly
my-bucket/def* : readonly
```

**Comment by GarimaKapoor** [comment]
Support recursive policy listing

`mc policy -r ALIAS/BUCKET/PREFIX`

**Comment by vadmeste** [comment]
From my understanding, the only way to do this is to make a call for each prefix which is time consuming. I suggest to add an API in minio-go which returns all policy rules in one websevice call, then mc will know how to list recursively all the rules. (GetBucketNotification returns all rules too)

**Comment by mkash32** [comment]
@vadmeste Could you take a look at code snippet I posted above (`listPolicies`)? It is an API in minio-go which collects all of the prefixes on which a policy exists and then calls `identifyPolicyType` to determine the police type.
To incorporate the recursive listing on a certain prefix, we can filter all the collected prefixes with the [matching function](https://github.com/minio/minio-go/blob/master/bucket-policy.go#L594) according to the input prefix.
What do you think about this approach?

**Comment by vadmeste** [comment]
@mkash32, I think this approach is good enough. However, I didn't find any exported functions in minio-go which helps to do that.

**Comment by harshavardhana** [comment]
> From my understanding, the only way to do this is to make a call for each prefix which is time consuming. I suggest to add an API in minio-go which returns all policy rules in one websevice call, then mc will know how to list recursively all the rules. (GetBucketNotification returns all rules too)

All policy calls underneath are single webservice on a GetBucketPolicy, the filtering happens on the client side. So it is not an expensive operation. 

Also this is not for 'BucketNotification'  this is only related to 'BucketPolicy', which will be separate command.

**Comment by harshavardhana** [comment]
Assigned to // cc @krishnasrinivas
