### ISSUE TITLE
mc mirror errors out when it's unable to get terminal width 

### ISSUE THREAD

**Issue by krisis** [minio/mc#1740]
## Steps to reproduce the issue
```
$ mc.exe mirror /c/gocode/src/github.com/minio/mc localxl/gosrc
mc.exe: <ERROR> Unable to get terminal size. Please use --quiet option. The handle is invalid.
```
## Operating System
Windows 8 (on MINGW64_NT-6.3)
N B This error is not seen in Windows cmd shell.

## mc version
```
$mc.exe version
Version: 2016-06-03T18:48:37Z
Release-tag: RELEASE.2016-06-03T18-48-37Z
Commit-id: 475670de7d9b10f4bc0d5d6f25f1a858c32c5628
```

**Comment by harshavardhana** [comment]
We don't support mingw64 and if we work for windows standard environment i.e powershell and cmd then we are good.  For 'mingw64' use `--quiet` as presented by the error message.
