### ISSUE TITLE
mirror try to sync glacier files

### ISSUE THREAD

**Issue by dcharbonnier** [minio/mc#1741]
I think it's the origin of the problem, we should be able to ignore those files that can't be mirrored anyway.

`mc: <ERROR> Failed to copy ‘http://s3.amazonaws.com/xxx/00002c2100782297d38eb8e77f7dfce9/1280x720.jpg’. The operation is not valid for the object's storage class`

**Comment by harshavardhana** [comment]
> I think it's the origin of the problem, we should be able to ignore those files that can't be mirrored anyway.
> 
> mc: <ERROR> Failed to copy ‘http://s3.amazonaws.com/xxx/00002c2100782297d38eb8e77f7dfce9/1280x720.jpg’. The operation is not valid for the object's storage class

We do not have this filtering on the minio-go library which we can do,  what is the Storage-Class of this object if i may ask?

**Comment by dcharbonnier** [comment]
yes, I confirm :
![image](https://cloud.githubusercontent.com/assets/6220422/16121178/24a8cd44-3397-11e6-8ba7-cc1590e41410.png)

**Comment by dcharbonnier** [comment]
not sure it should be on the library, there is no way to specify a filter on the api request, the only way is to filter client side and the problem is on getting the object, probably filtering the list on mc would be more appropriate. On the library the only improvement I see would be to return an appropriate error on getting the object

**Comment by harshavardhana** [comment]
> not sure it should be on the library, there is no way to specify a filter on the api request, the only way is to filter client side and the problem is on getting the object, probably filtering the list on mc would be more appropriate. On the library the only improvement I see would be to return an appropriate error on getting the object

'mc' has no context - it is minio-go which can provide this filtering, but we can't leverage anything on server side for this as you found out. So we have to do it on the client side,  would you mind opening a bug on minio-go for this?

**Comment by dcharbonnier** [comment]
dependency https://github.com/minio/minio-go/issues/420
