### ISSUE TITLE
mc copies the wrong selection in this case?

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1747]
```
$ cd /tmp/test/
$ mkdir mc
$ touch mc_test.go
$ mc cp -r mc myminio/bucket/
[0] ◐ mc_test.go
```

**Comment by vadmeste** [comment]
Probably working as expected after reviewing the code, but it is little confusing, is it possible to replace --recursive with --prefix here ?

**Comment by harshavardhana** [comment]
> Probably working as expected after reviewing the code, but it is little confusing, is it possible to replace --recursive with --prefix here ?

This is because of cli related issue.

**Comment by harshavardhana** [comment]
Because of this bug - https://github.com/minio/mc/issues/1513

**Comment by harshavardhana** [comment]
https://github.com/minio/mc/issues/1432 and here

**Comment by harshavardhana** [comment]
Closing this as duplicate of #1513
