### ISSUE TITLE
mc: please add the ability to throttle replication

### ISSUE THREAD

**Issue by esarakaitis** [minio/mc#1749]
having the ability to throttle replication both upload and download would be fantastic

a switch like -ub and -db to the mirror command would be ideal.  

-ub = upload bandwidth in Kbit/s
-db = upload bandwidth in Kbit/s

**Comment by abperiasamy** [comment]
@esarakaitis Can you give trickle tool a try?
Something like this: https://wiki.archlinux.org/index.php/Trickle

**Comment by GarimaKapoor** [comment]
Trickle works fine. We will document for community.
