### ISSUE TITLE
mc shows `Unable to load version ‘6’. Migration failed` when the system is under heavy activity

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1753]
When running this `while true; do mc rm myminio/bucket/imaginary_file; done` while my system is under stress test, I noticed that mc shows me this error: 
`mc: <ERROR> Unable to load version ‘6’. Migration failed please report this issue at https://github.com/minio/mc/issues. stat /home/vadmeste/.mc/session/nvMtBEsp.json: no such file or directory`

**Comment by harshavardhana** [comment]
> When running this while true; do mc rm myminio/bucket/imaginary_file; done while my system is under stress test, I noticed that mc shows me this error: 
> mc: <ERROR> Unable to load version ‘6’. Migration failed please report this issue at https://github.com/minio/mc/issues. stat /home/vadmeste/.mc/session/nvMtBEsp.json: no such file or directory

There is no parallel protection for migrating sessions, you can take up this and fix it.

**Comment by vadmeste** [comment]
The problem is not only with parallel migration: Sometimes, a mc instance creates a session file, executes and then removes it while another mc instance was able to detect the session file but will find it removed when trying to migrate it. Also, there are complicated cases which could happen (like running two mc versions in the same system, resuming the same session by two mc instances, ..)

For the moment, the easiest thing for me, is that we make each mc instance protects its session files with some file locking primitives (http://ikarishinjieva.github.io/tachikoma-blog/post/2014-03-20-go-file-lock/), in addition, we make migration ignores File not found error.

**Comment by harshavardhana** [comment]
> For the moment, the easiest thing for me, is that we make each mc instance protects its session files with some file locking primitives (http://ikarishinjieva.github.io/tachikoma-blog/post/2014-03-20-go-file-lock/), in addition, we make migration ignores File not found error.

Yes we can but lock is better.

**Comment by bdelagesap** [comment]
Hi
I'm having a similar issue.

I use mc RELEASE.2019-05-23T01-33-27Z

Under heavy load I get :
`
11:13:15  minio: <ERROR> Unable to load version `6`. Migration failed please report this issue at https://github.com/minio/mc/issues. Unable to parse JSON schema due to a syntax error at '    1:   <<<<'.`

**Comment by vadmeste** [comment]
Reopened for investigation

**Comment by bdelagesap** [comment]
This happens on jenkins slave containers running on k8s.
We're pushing/pulling objects from minio using mc.
Each slave has only one session.

**Comment by harshavardhana** [comment]
There are no sessions by default anymore, commands have changed. Closing this as a stale issue.
