### ISSUE TITLE
mc: Implement asynchronous replication support 

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1767]

**Comment by GarimaKapoor** [comment]
Please update the timeline for the fix.

**Comment by nl5887** [comment]
I'll add an extra option `-monitor` to cp (create, update) and mirror (create, update, delete) which will monitor the source folder for any changes. If there are any changes those will be reflected on destination as well.

**Comment by nl5887** [comment]
Wednesday 27th I'll have this all implemented.

**Comment by nl5887** [comment]
Almost there.... Working on the latest bugs and optimizations.

**Comment by nl5887** [comment]
Ok, fixed last deadlock. Everything working great now. Optimizing, cleaning up code and documenting.

**Comment by nl5887** [comment]
- the cp command will stay (at least for now) the same, the command is quite complex, and don't know what side-effects changes will have
- the mirror command will have a -watch option, which will watch for changes
- the s3 client will support watch using bucket notifications
