### ISSUE TITLE
mc flag for turning off sessions

### ISSUE THREAD

**Issue by finlay** [minio/mc#1774]
## A new flag for minio commandline tool

If you pass the `--no-session` flag to mc, like this:

    mc --no-session cp --recursive /directory/ storage/bucket/path

It won't create a session. This means that on failure there will be no retry option. However, it should make recursive copies like this much faster.

**Comment by harshavardhana** [comment]
@finlay we decided that these commands already have many options, we generally try to reduce the options so we decided to not add this option. 

Instead see if this solution works for you 

```
find . -exec mc cp {} \;
```
