### ISSUE TITLE
Check stale *.old files under ~/.mc/

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1787]

**Comment by vadmeste** [comment]
Not able to reproduce this, I even simulated a session migration but old files are still removed with mc session clear all, @koolhead17, could you reexplain the bug that you encountered upon your discussion with @harshavardhana ?

**Comment by harshavardhana** [comment]
> Not able to reproduce this, I even simulated a session migration but old files are still removed with mc session clear all, @koolhead17, could you reexplain the bug that you encountered upon your discussion with @harshavardhana ?

Most probably stale files from previous `mc` versions.

**Comment by koolhead17** [comment]
@harshavardhana I think we can close this, that .old file was created manually. I will keep an eye on this behaviour.
