### ISSUE TITLE
Session not created when doing parallel mc cp

### ISSUE THREAD

**Issue by stl-paulfriedman** [minio/mc#1809]
## Expected behaviour
transferring 1000 files from s3 to google storage by running 10 mc's in parallel.  I expect intermittent network failures every now and then and expect an mc session to be created for the cp which can be retried with mc session resume <sessionid>

## Actual behaviour
Get an error:
mc: <ERROR> Unable to load version â€˜6â€™. Migration failed please report this issue at https://github.com/minio/mc/issues. stat /home/paul/.mc/session/puQNMoxV.json: no such file or directory

Verified directory exists:
paul@deploy-server:~$ ls -al /home/paul/.mc/session
total 8
drwx------ 2 paul paul 4096 Aug 24 05:57 .
drwx------ 4 paul paul 4096 Aug 24 04:31 ..

## Steps to reproduce the behaviour
/usr/local/bin/parallel -j 10 /home/paul/mc cp --no-color -q s3-url/{} gs-url/ :::: /tmp/cuebiq_u\
s_files

## mc version
paul@deploy-server:~$ ./mc version
Version: 2016-07-13T22:00:39Z
Release-tag: RELEASE.2016-07-13T22-00-39Z
Commit-id: 589c821f9bbeb30aaf6006d56e5e1965fa806b23

## System information
Ubuntu 14.04

**Comment by vadmeste** [comment]
@stl-paulfriedman, this bug is already fixed in master (https://github.com/minio/mc/commit/acd80370e640c11b564cea027bb514a74e16313d), you can install mc manually (https://docs.minio.io/docs/minio-client-quickstart-guide, install from source section), or you wait for the next release of mc.
