### ISSUE TITLE
mc: Add '--insecure' for making insecure SSL connections

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1813]
```
type Config struct {
....
....
        // InsecureSkipVerify controls whether a client verifies the
        // server's certificate chain and host name.
        // If InsecureSkipVerify is true, TLS accepts any certificate
        // presented by the server and any host name in that certificate.
        // In this mode, TLS is susceptible to man-in-the-middle attacks.
        // This should be used only for testing.
        InsecureSkipVerify bool
....
....
}
```

**Comment by abperiasamy** [comment]
You could use a message like this:

> SSL certificate verification failed. If you are really sure about the validity of this certificate, you may override this check with '--insecure' flag.

**Comment by vadmeste** [comment]
This needs change in minio-go, I think we have four options:
- Add an API, SetInsecure()
- Add a new parameter in New()
- Add an API NewInsecure()
- The fourth option:
New() has already the secure flag, so this is my suggestion:

`New("localhost:9000", "accesskey", "secretkey", true)` => HTTPS secure
`New("localhost:9000", "accesskey", "secretkey", false)` => HTTP
`New("https://localhost:9000", "accesskey", "secretkey", false)` => HTTPS insecure
`New("http://localhost:9000", "accesskey", "secretkey", true)` => HTTP or returns an error

**Comment by harshavardhana** [comment]
> This needs change in minio-go, I think we have four options:
> 
> Add an API, SetInsecure()
> Add a new parameter in New()
> Add an API NewInsecure()
> The fourth option: New() has already the secure flag, so this is my suggestion:
> New("localhost:9000", "accesskey", "secretkey", true) => HTTPS secure
> New("localhost:9000", "accesskey", "secretkey", false) => HTTP
> New("https://localhost:9000", "accesskey", "secretkey", false) => HTTPS insecure
> New("http://localhost:9000", "accesskey", "secretkey", true) => HTTP or returns an error

This is not needed, you need to set a custom transport

```
tr := &http.Transport{
	TLSClientConfig:    &tls.Config{RootCAs: pool},
}
```

**Comment by vadmeste** [comment]
> This is not needed, you need to set a custom transport
> 
> tr := &http.Transport{
>     TLSClientConfig:    &tls.Config{RootCAs: pool},
> }

thanks, wasn't aware about SetCustomTransport in minio-go.. was looking here https://docs.minio.io/docs/golang-client-api-reference :)

**Comment by harshavardhana** [comment]
Now that you mention it we have a bug in API.md
