### ISSUE TITLE
Requirements for an attached tty?

### ISSUE THREAD

**Issue by jeremytregunna** [minio/mc#1820]
I've got a program written in Go which monitors a dir for a particular set of file events, and when they occur, executes a shell script which calls ffmpeg to transcode a file, then invokes mc to upload it to a minio server. When I run this script from my user account while ssh'd into the server, it works fine. However, if I run my Go program under supervisord, and it gets invoked from there, `mc` produces no output, and does not upload the file to minio.

Is there a requirement that mc be invoked when a tty is attached that could explain this behaviour? Or is there something special I have to do to make this work in a script that's launched from a headless program?

## mc version
Version: 2016-08-21T03:02:49Z
Release-tag: RELEASE.2016-08-21T03-02-49Z
Commit-id: 768be74f74578137951f65874cfc2e454b64aca0

## System information
x86_64 ubuntu 14.04 LTS

**Comment by jeremytregunna** [comment]
Closing this, I found the problem, sorry for the noise. Issue was a filesystem race condition, and me redirecting MC output somewhere that was different than where I was checking.

**Comment by abperiasamy** [comment]
@jeremytregunna For use cases like yours, we introduced --json flag and mc watch subcommand. You may find them interesting.
