### ISSUE TITLE
`echo "test" | mc pipe /tmp/hello.txt` doesn't work

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1830]
The pipe command doesn't seem to be working as expected with the mc master:

```
$ echo "test" | mc --debug pipe /tmp/hello.txt
mc: <ERROR> Unable to write to one or more targets. read /dev/stdin: illegal seek
 (4) pipe-main.go:109 cmd.mainPipe(..) Tags: [/tmp/test]
 (3) pipe-main.go:84 cmd.pipe(..) Tags: [/tmp/test]
 (2) common-methods.go:87 cmd.putTargetStreamFromAlias(..) Tags: [, /tmp/test]
 (1) client-fs.go:264 cmd.(*fsClient).Put(..) Tags: [/tmp/test.part.minio]
 (0) client-fs.go:1067 cmd.(*fsClient).toClientError(..)
 Commit:b404c7583bc9 | Release-Tag:DEVELOPMENT.2016-09-22T16-57-13Z | Host:xps-u | OS:linux | Arch:amd64 | Lang:go1.7.1 | Mem:12MB/19MB | Heap:12MB/15MB
```

**Comment by harshavardhana** [comment]
can we put some more details here? - we shouldn't be reporting bugs in this manner.

**Comment by vadmeste** [comment]
> can we put some more details here? - we shouldn't be reporting bugs in this manner.

:+1: , I updated the description.

**Comment by vadmeste** [comment]
os.Stdin is considered as File in go which implements (ReadAt). This could change in go2.0 according to this ticket => https://github.com/golang/go/issues/13473. I think os.Stdin can easily be treated separately in mc code.

**Comment by harshavardhana** [comment]
> os.Stdin is considered as File in go and implements (ReadAt). This could change in go2.0 according to this ticket => golang/go#13473. I think os.Stdin can easily be treated separately in mc code.

We can mask it into another struct before passing to minio-go, ie which implements io.Reader() alone.

**Comment by vadmeste** [comment]
> We can mask it into another struct before passing to minio-go, ie which implements io.Reader() alone.

This bug is reproducible only with FS, so no minio-go. client-fs anticipated this case. I added an additional check in #1834 to avoid seeking os.Stdin in Put()

**Comment by vadmeste** [comment]
Looks this bug emerged again.

**Comment by vadmeste** [comment]
> Looks like this bug emerged again.

This is a regression in minio-go, fixed it about will test further

**Comment by harshavardhana** [comment]
Is this fixed @vadmeste ?

**Comment by vadmeste** [comment]
> Is this fixed @vadmeste ?

Yes, fixed by https://github.com/minio/minio-go/pull/546
