### ISSUE TITLE
mirror: watch should provide appropirate error when used on aws-s3

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/mc#1841]
when `mc mirror -w s3/bucket1 myminio/bucket1` is done it should throw error:
`Supported only on minio storage`

right now it throws:
`Failed to start monitoring. The ARN is not well formed`

**Comment by vadmeste** [comment]
This is fixed in master. We have this instead:
```sh
$ mc mirror -w s3/vadmeste-west-2 myminio/testbucket/
mc: <ERROR> Unexpected error during monitoring. Listening bucket notification is specific only to `minio` partitions
```

**Comment by harshavardhana** [comment]
We need to fix this error message.

**Comment by harshavardhana** [comment]
@vadmeste has this been fixed?

**Comment by vadmeste** [comment]
@harshavardhana, currently in master, we have this error message:
`Unexpected error during monitoring. Listening bucket notification is specific only to minio partitions`

The error is  generic and received from minio-go, we can rename it to `This operation is supported only with Minio storage`, what do you think?

**Comment by harshavardhana** [comment]
Yes latter is better. @vadmeste
