### ISSUE TITLE
mc can't copy files, error Last-Modified time format is invalid.

### ISSUE THREAD

**Issue by ricoharisin91** [minio/mc#1848]
## Expected behaviour
mc copy the files

## Actual behaviour
mc throw an error

## Steps to reproduce the behaviour
mirror  from bucket called kilatstorage to s3 with `mc mirror` mc cannot even copy the first files, when i debug the output like this

```
mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 11402
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Content-Type: image/jpeg
Date: Mon, 03 Oct 2016 12:41:31 GMT
Etag: "ed276d4e15a7bbc7e64dbd6c2232ce40"
Last-Modified: Fri, 14 Feb 2014 08:08:15 CET
Server: CloudianS3
X-Amz-Request-Id: B5DFC770896611E6
```

## mc version
Version: DEVELOPMENT.GOGET
Release-tag: DEVELOPMENT.GOGET
Commit-id: DEVELOPMENT.GOGET

## System information
Ubuntu 14.04

**Comment by krishnasrinivas** [comment]
> mc throw an error

@ricoharisin91 can you paste what error mc throws?

Can you do simple operations like `mc cat` `mc cp` without problems?

**Comment by ricoharisin91** [comment]
hi thanks for the reply

i've tried a very simple task to `cp` one file to my local but no luck


> mc: <ERROR> Failed to copy ‘http://kilatstorage.com/jurnalotaku/wp-content/uploads/2014/02/001-17-123x300.jpg’. Last-Modified time format not recognized. Please report this issue at https://github.com/minio/minio-go/issues.
>  (4) cp-main.go:346 cmd.doCopySession.func1(..) Tags: [http://kilatstorage.com/jurnalotaku/wp-content/uploads/2014/02/001-17-123x300.jpg]
>  (3) cp-main.go:207 cmd.doCopy(..) Tags: [/home/rico/wp-content/001-17-123x300.jpg]
>  (2) common-methods.go:87 cmd.putTargetStreamFromAlias(..) Tags: [, /home/rico/wp-content/001-17-123x300.jpg]
>  (1) client-fs.go:263 cmd.(*fsClient).Put(..) Tags: [/home/rico/wp-content/001-17-123x300.jpg.part.minio]
>  (0) client-fs.go:1066 cmd.(*fsClient).toClientError(..)
>  Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:joi-apps | OS:linux | Arch:amd64 | Lang:go1.7.1 | Mem:12MB/17MB | Heap:12MB/14MB
> mc: <ERROR> Session safely terminated. To resume session ‘mc session resume ywEpqYgR’
>

**Comment by ricoharisin91** [comment]
hi thanks for the reply

i've tried a very simple `mc cp` from my bucket to local but no luck

```
mc: <ERROR> Failed to copy ‘http://kilatstorage.com/jurnalotaku/wp-content/uploads/2014/02/001-17-123x300.jpg’. Last-Modified time format not recognized. Please report this issue at https://github.com/minio/minio-go/issues.
 (4) cp-main.go:346 cmd.doCopySession.func1(..) Tags: [http://kilatstorage.com/jurnalotaku/wp-content/uploads/2014/02/001-17-123x300.jpg]
 (3) cp-main.go:207 cmd.doCopy(..) Tags: [/home/rico/wp-content/001-17-123x300.jpg]
 (2) common-methods.go:87 cmd.putTargetStreamFromAlias(..) Tags: [, /home/rico/wp-content/001-17-123x300.jpg]
 (1) client-fs.go:263 cmd.(*fsClient).Put(..) Tags: [/home/rico/wp-content/001-17-123x300.jpg.part.minio]
 (0) client-fs.go:1066 cmd.(*fsClient).toClientError(..)
 Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:joi-apps | OS:linux | Arch:amd64 | Lang:go1.7.1 | Mem:12MB/17MB | Heap:12MB/14MB
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume ywEpqYgR’
```

**Comment by vadmeste** [comment]
> Last-Modified: Fri, 14 Feb 2014 08:08:15 CET

Looks like the reason is that the server is returning time in CET and not GMT. I will investigate further.

**Comment by vadmeste** [comment]
@ricoharisin91, according to this link https://tools.ietf.org/html/rfc7232#section-2.2 which leads to this https://tools.ietf.org/html/rfc7231#section-7.1.1.1, only GMT is supported. Your S3 provider is not following  the spec exactly.

**Comment by ricoharisin91** [comment]
yeah it's really strange that my S3 provider using CET instead GMT

so no solution then?

**Comment by vadmeste** [comment]
> so no solution then?

You have to notify your S3 provider. A temporary workaround for you is to replace http.TimeFormat in your copy of minio-go code with "Mon, 02 Jan 2006 15:04:05 CET" until your provider fixes his bug. (didn't test the workaround though)

**Comment by vadmeste** [comment]
> A temporary workaround for you is to replace http.TimeFormat in your copy of minio-go code with "Mon, 02 Jan 2006 15:04:05 CET"

I meant in api-get-object.go and api-stat.go files

**Comment by harshavardhana** [comment]
```
mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 11402
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Content-Type: image/jpeg
Date: Mon, 03 Oct 2016 12:41:31 GMT
Etag: "ed276d4e15a7bbc7e64dbd6c2232ce40"
Last-Modified: Fri, 14 Feb 2014 08:08:15 CET
Server: CloudianS3
X-Amz-Request-Id: B5DFC770896611E6
```

Interestingly 'Date' header is set properly but not 'Last-Modified'  here is the output. 

S3
```
Connection: close
Content-Length: 154696
Accept-Ranges: bytes
Content-Range: bytes 0-154695/154696
Content-Type: application/octet-stream
Date: Mon, 03 Oct 2016 16:31:59 GMT
Etag: "e95fc243c0268334ec4ca33b25df0a68"
Last-Modified: Mon, 11 Jul 2016 02:45:18 GMT
Server: AmazonS3
X-Amz-Id-2: mj0+4D9OV/gyNPBTAZdVw9DWSSFLT/xg/91snFFirLBC8xUzrnfIjgDeP0yv0yAAv/onWSOU4ro=
X-Amz-Request-Id: D86F12905016C515
```

Minio
```
Content-Length: 788
Accept-Ranges: bytes
Content-Range: bytes 0-787/788
Content-Type: application/octet-stream
Date: Mon, 03 Oct 2016 16:32:53 GMT
Etag: "2a904117698c9488ce0f0c96266ac7dd"
Last-Modified: Wed, 07 Sep 2016 01:39:55 GMT
Md5sum: 2a904117698c9488ce0f0c96266ac7dd
Server: Minio/DEVELOPMENT.2016-10-02T17-05-56Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 6U6RASW4Z0A3HPR4
```

**Comment by ricoharisin91** [comment]
ok i'll try to do the workaround, hopefully it will solve for temporary

thanks for the tip anyway!

**Comment by harshavardhana** [comment]
> ok i'll try to do the workaround, hopefully it will solve for temporary
> 
> thanks for the tip anyway!

Closing as not an 'mc' issue.

**Comment by rondoe** [comment]
I had the same problem when using apache as proxy for my minio instance. Disabling mod page speed helped me to get this done.

```
<VirtualHost>
...
ModPagespeed off
...
</VirtualHost>
```
