### ISSUE TITLE
`mc mirror -w` doesn't work when we copy a file with one character name in a filesystem source directory

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1852]
If we want to watch continuously a file system directory and mirror contents to a bucket, we can notice that fs watch system doesn't consider new files whose names have only one character

If I run this in one terminal:
`$ mc mirror -w -q /path/to/mydir myminio/testbucket/`

and this in another terminal:
`$ cp f /path/to/mydir/`

`f` is not copied in the remote s3 server

**Comment by vadmeste** [comment]
By the way, `mc mirroir -w` shows some activity, but the file is not actually copied.

**Comment by harshavardhana** [comment]
Can you use `mc watch` ? See the event reported by server and what is the file size ?

**Comment by vadmeste** [comment]
> Can you use mc watch ? See the event reported by server and what is the file size ?

Nice advice :)
[2016-10-10T16:46:34Z]   581B ObjectCreated http://172.19.0.2:9000/testbucket/home/vadmeste/work/gospace/src/github.com/minio/minio/m

The file is copied. I checked. However it is copied under /home/vadmeste/work/gospace/src/github.com/minio/minio, though in the command line, I run this : `mc mirror -q -w minio/ myminio1/testbucket/`

This is confusing.

**Comment by harshavardhana** [comment]
i think the 'mc mirror' is copying full path not the relative path.
