### ISSUE TITLE
Recursive copy between buckets using mc fails

### ISSUE THREAD

**Issue by krisis** [minio/mc#1857]
## Expected behaviour

Recursive copy between buckets must succeed. 
## Actual behaviour

```
$ mc --quiet cp  --recursive localxl/test1/ localxl/test2/
‘localxl/test1/hello.txt’ -> ‘localxl/test2/hello.txt’
mc.exe: <ERROR> Failed to copy ‘http://localhost:9000/test1/hello.txt’. Object key is missing, object key cannot be empty
Total: 6 B, Transferred: 0 B, Speed: 0 B/s
```

While the same works with aws,

```
$ aws --endpoint http://localhost:9000 s3 cp --recursive s3://test1 s3://test2
copy: s3://test1/hello.txt to s3://test2/hello.txt
```
## Steps to reproduce the behaviour
- Make two buckets `test1` and `test2`
- Copy a small object to `test1`
- `mc --quiet cp  --recursive localxl/test1/ localxl/test2/` , where `localxl` is alias for local Minio server
## mc version

`17eeec6`
## System information

MS Windows

**Comment by krisis** [comment]
@harshavardhana Why have you added the question label to it?

**Comment by harshavardhana** [comment]
> @harshavardhana Why have you added the question label to it?

Ah sorry my mistake, was meant to re-evaluate this situation since we fixed a whole bunch of things on minio master.

**Comment by krisis** [comment]
@harshavardhana I shall check if this issue still exists with the current master.

**Comment by harshavardhana** [comment]
> @harshavardhana I shall check if this issue still exists with the current master.

Is this still a problem?

**Comment by krisis** [comment]
Yes, this is still a problem as of commit ``b51e6b0``.

**Comment by harshavardhana** [comment]
Only on Windows ?

**Comment by krisis** [comment]
> Only on Windows ?

yes, this is seen only on windows.
