### ISSUE TITLE
s3: [feature] Please add support for using different storage classes in S3

### ISSUE THREAD

**Issue by gcv** [minio/mc#1859]
Commands like `mc cp` and `mc mirror` should take a `--storage-class` parameter which would specify the storage class for newly-created objects. Right now, everything (reasonably) defaults to `STANDARD`.

**Comment by kannappanr** [comment]
@nitisht Is this issue still relevant? Can we close this issue?

**Comment by harshavardhana** [comment]
We can think about implementing this feature since server now supports it.

**Comment by nitisht** [comment]
> We can think about implementing this feature since server now supports it.

Yes, I think we should do it

**Comment by harshavardhana** [comment]
@nitisht is there a plan on implementing this?

**Comment by nitisht** [comment]
yes will do it @harshavardhana
