### ISSUE TITLE
Minio client fails to to provide session ID incase of incomplete mirror request.

### ISSUE THREAD

**Issue by koolhead17** [minio/mc#1860]
## Expected behaviour

`mc mirror atul/ myminio/atul`  If the connection breaks It should provide error like

```
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume jHEOxAMY’
```
## Actual behaviour

`mc` just closes the operation.
## Steps to reproduce the behaviour

On Minio1, distributed server.

`mc mirror atul/ myminio/atul` & press CTRL+C

**Comment by harshavardhana** [comment]
Is this reproducible ?

**Comment by harshavardhana** [comment]
> Is this reproducible ?

Closing this as not reproducible.
