### ISSUE TITLE
Review which characters should be accepted in access and secret keys

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1868]
minio & mc don't have the same restriction rule in terms of accepted characters in access and secret keys, we need to review this.

**Comment by koolhead17** [comment]
@vadmeste Is there a reason we are not following strict S3 guideline for access/secret keys?

**Comment by vadmeste** [comment]
> @vadmeste Is there a reason we are not following strict S3 guideline for access/secret keys?

I am not able to find any s3 guideline document @koolhead17, can you point me to one ?
