### ISSUE TITLE
[policy] mc policy upload should print help if no bucket or prefix is provided.

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1871]
> ```
ab@Gravity:~$ mc policy upload 
mc: <ERROR> Unable to set policy ‘upload’ for ‘upload’. Requested file ‘upload’ not found
```
bug.. because we interpret upload as target when no PERMISSION is passed.

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/mc/pull/1878
