### ISSUE TITLE
[policy] mc policy links s3/mybucket to list fully qualified URLs

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1873]
This was requested by @atomi to list public URLs for external processing.

**Comment by harshavardhana** [comment]
```
 mc policy links (help)
 mc policy links play/harsha - (non-recursive)
 mc policy links --recursive play/harsha - (recursive)
 mc policy links --json play/harsha - (json output)
```

**Comment by vadmeste** [comment]
Not sure what does 'links' stand for here, any explanation ?

**Comment by atomi** [comment]
> fully qualified URL

**Comment by vadmeste** [comment]
We probably need to print the full qualified URL when the user runs policy download and upload commands, just to simplify and to avoid adding a new command.

**Comment by atomi** [comment]
Yeah. 

The idea is to make it easy to list URLs for buckets that are public.

**Comment by harshavardhana** [comment]
We need to add a new command it would confuse the existing functionality. Also setting and unsetting policy shouldn't be the reason to get fully qualified URLs

**Comment by vadmeste** [comment]
> We need to add a new command it would confuse the existing functionality.

I wanted something like 'share' command which also prints the full qualified URL, policy download is somehow similar

> Also setting and unsetting policy shouldn't be the reason to get fully qualified URLs

Yeah, but also, it seems to me that someone will need a full qualified URL of an object only when this latter becomes public which means after applying policy command

**Comment by harshavardhana** [comment]
> Yeah, but also, it seems to me that someone will need a full qualified URL of an object only when this latter becomes public which means after applying policy command

That is correct but the purpose of links is to fetch URLs on existing buckets which are public adding this as part of `policy` settings makes it quite heavy and you can't extend it.  For example being able to differentiate `--recursive` v/s non-recursive has no meaning for policy settings, navigation becomes complicated but putting everything on the same command.

**Comment by vadmeste** [comment]
:+1: 

This could be done by listing prefixes associated to download policies then we should list objects which start with all found prefixes and then print the full qualified URL of the found objects.

**Comment by vadmeste** [comment]
Taking this

**Comment by vadmeste** [comment]
@harshavardhana, what would be the output of json ? {"entry:":"http://play.minio.io:9000/testbucket/public/object1"} ?

**Comment by harshavardhana** [comment]
It should have the same format. Like `mc ls` just that we don't need to show time or size.

**Comment by vadmeste** [comment]
Timeline, Jan 03.

**Comment by atomi** [comment]
Can we have the URLs escaped (QueryEscape?)

**Comment by harshavardhana** [comment]
> Can we have the URLs escaped (QueryEscape?)

@atomi that should done by the application which parses these URLs.

**Comment by vadmeste** [comment]
> @atomi that should done by the application which parses these URLs.

@harshavardhana, applications can do that, but it looks to me that no one will ever need a non encoded urls, think about spaces in object names, encoding urls will make them more ready.

**Comment by harshavardhana** [comment]
Ah that makes sense agreed.
