### ISSUE TITLE
`mc` returns inconsistent exit status on same kind of error

### ISSUE THREAD

**Issue by donatello** [minio/mc#1880]
## Expected behaviour

mc should exit with non-zero exit code for "connection refused" errors (i.e. when the server is down).

## Actual behaviour

In some cases mc exits with 0 exit status when server is down. This makes it difficult to use in scripts.

## Steps to reproduce the behaviour

```
aditya@donatello-laptop:~/Code/minio-code/data$ echo "tiny object" | mc pipe dminio1/testbucket/one
mc: <ERROR> Unable to write to one or more targets. Get http://127.0.0.1:9001/testbucket/?location=: dial tcp 127.0.0.1:9001: getsockopt: connection refused
aditya@donatello-laptop:~/Code/minio-code/data$ echo $?
1
aditya@donatello-laptop:~/Code/minio-code/data$ mc ls dminio1
mc: <ERROR> Unable to list folder. Get http://127.0.0.1:9001/: dial tcp 127.0.0.1:9001: getsockopt: connection refused
aditya@donatello-laptop:~/Code/minio-code/data$ echo $?
0

```

## mc version
```
$ mc version
Version: 2016-11-11T19:01:44Z
Release-tag: DEVELOPMENT.2016-11-11T19-01-44Z
Commit-id: 2895b0accaad4465128e4b950bf048494de36a9f
```
## System information
Linux.

**Comment by harshavardhana** [comment]
mc shouldn't exit with any status it should exit with '0' actual error is provided through '--json'

**Comment by donatello** [comment]
> mc shouldn't exit with any status it should exit with '0' actual error is provided through '--json'

Ok cool. So exit status needs to be fixed here.

**Comment by harshavardhana** [comment]
> Ok cool. So exit status needs to be fixed here.

In case of 'mc pipe' we might be doing something odd here. So will see how to fix it.

**Comment by abperiasamy** [comment]
@harshavardhana mc must exit with error code 1 for any errors independent of JSON output.

**Comment by vadmeste** [comment]
> @harshavardhana mc must exit with error code 1 for any errors independent of JSON output.

I suggest that errors of type errorIf return 1 and fatalIf return 2, that way we can differentiate between regular errors like bucket not found, network error and fatal errors like alias not found, config parsing error, etc..

**Comment by harshavardhana** [comment]
> I suggest that errors of type errorIf return 1 and fatalIf return 2, that way we can differentiate between regular errors like bucket not found, network error and fatal errors like alias not found, config parsing error, etc..

I think we don't need to make it elaborate it can be simply 1 or 0. 1 in case of error and 0 other wise. where does it help providing different kinds of error code?

**Comment by vadmeste** [comment]
> where does it help providing different kinds of error code?

I have always considered fatalIf as a dysfunctional problem (cannot read config json, invalid arguments, etc..) and errorIf for regular errors (bucket not found,  network error, ..) but it seems the intention of the existing code is not similar to my thinking. Anyway I think we should keep as it is now until someone asks for it with a clear motivation.
