### ISSUE TITLE
Add support of self signed certificates (Add ~/.mc/CAs/)

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1883]
## Expected behaviour
When a user configures a self signed certificate in his ecosystem, he shouldn't pass --insecure flag to make mc works

## Actual behaviour
User needs to pass --insecure parameter

## Steps to reproduce the behaviour
1. Generate self signed certificate and add it to a minio server
2. mc ls myminio/

## mc version
All versions

## System informationms
All systems

**Comment by vadmeste** [comment]
Working on this.

**Comment by harshavardhana** [comment]
Fixed by #1901
