### ISSUE TITLE
Mirror getting terminated if source server goes down..

### ISSUE THREAD

**Issue by rakesh-eltropy** [minio/mc#1889]
## Expected behaviour
We have configured two minio servers. Idea is to keep both the servers in sync.
So, we have run following commands:

mc mirror  -w ltropyorgnode2/rakesh ltropyorgnode1/rakesh
mc mirror  -w ltropyorgnode1/rakesh ltropyorgnode2/rakesh

If source node goes down eg. ltropyorgnode2 - syncing is not happening. mc mirror should re-establish the connection, when source node comes up.

## Actual behaviour
Getting, mc: <ERROR> Unexpected error during monitoring. Get http://ltropy.org:9002/rakesh/?events=s3%3AObjectCreated%3A%2A&events=s3%3AObjectRemoved%3A%2A&prefix=&suffix=: dial tcp 128.199.196.108:9002: getsockopt: connection refused
## Steps to reproduce the behaviour
1) Create two minio instances
2) Use mc mirror to keep both of them in sync
3) Bring down one of the minio instance
4) Synching will stop for source mc mirror command
## mc version
Version: DEVELOPMENT.GOGET
Release-tag: DEVELOPMENT.GOGET
Commit-id: DEVELOPMENT.GOGET

## System information
Ubuntu 14.04 64 bit

**Comment by harshavardhana** [comment]
It is expected and should write a session  you can do `mc session resume sessionid`

**Comment by harshavardhana** [comment]
Is the session not written ?

**Comment by rakesh-eltropy** [comment]
But, how would mc session resume will solve this problem. I want to keep two servers in sync. If one of them goes down, other takes over. In this case, even our minio server comes back, I still have to manually go and run 

> mc session resume sessionid

**Comment by vadmeste** [comment]
> Is the session not written ?

Actually yes. mc doesn't exit when the source server stops.

**Comment by harshavardhana** [comment]
mc mirror -w shouldnt fail since the internal code in minio-go is never supposed to error out.  So will fix it.  Thanks for the bug @rakesh-eltropy

**Comment by rakesh-eltropy** [comment]
Thanks @harshavardhana. Looking forward for the fix.
