### ISSUE TITLE
mc doesn't return an error when the download file is incomplete

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1896]
When we simulate disk corruption, like removing a part file in XL backend, mc doesn't show any error when it downloads the incomplete file, though it can compare the size of the downloaded file with the file size reported by the server (content-length)

**Comment by vadmeste** [comment]
I am going to do this with simply checking the size of the transferred file, any easier way before I go to implement this ?

**Comment by harshavardhana** [comment]
> I am going to do this with simply checking the size of the transferred file, any easier way before I go to implement this ?

There is already a check for this, we need to see why it is not working - in-fact for both less content v/s more content - It seems like there is something else which stops the comparison.

**Comment by harshavardhana** [comment]
It could also be `minio-go` GetObject() bug too..

**Comment by vadmeste** [comment]
:+1:

**Comment by vadmeste** [comment]
> There is already a check for this

yes, I found it.. it is working with `cp` and `mirror` but not with `cat`

**Comment by harshavardhana** [comment]
> yes, I found it.. it is working with cp and mirror but not with cat

Perhaps wrapping like a rangeReader will be nicer..

**Comment by vadmeste** [comment]
> Perhaps wrapping like a rangeReader will be nicer..

yes.. but sometimes we use ReadAt() instead of Read().. and ReadAt() is incompatible with rangeReader.. so I guess it is better to keep the code simple as it is now.

**Comment by harshavardhana** [comment]
> yes.. but sometimes we use ReadAt() instead of Read().. and ReadAt() is incompatible with rangeReader.. so I guess it is better to keep the code simple as it is now.

Ah okay cool.

**Comment by harshavardhana** [comment]
Closing fixed by #1907
