### ISSUE TITLE
mc mirror --watch remote local, syncs the ongoing upload *.part.minio

### ISSUE THREAD

**Issue by dgoo2308** [minio/mc#1902]
## Expected behaviour

sync uploaded files.

## Actual behaviour

also sync intermediate files of upload.

## Steps to reproduce the behaviour

start mirror =>`mc mirror -watch--force --remove mys3/dirwatch $HOME/dirwatch`
monitor local folder =>`mc watch dirwatch`
And => `mc cp test.txt mys3/dirwatch/test.txt`

Output mc watch local folder:
```
LOCAL  : [2016-11-30T09:17:16.410Z]     0B ObjectCreated /Users/me/dirwatch/test.txt.part.minio
LOCAL  : [2016-11-30T09:17:16.433Z] 1.2KiB ObjectCreated /Users/mr/dirwatch/test.txt
```
## mc version
- VERSION mc:
  2016-10-07T01:56:22Z
- VERSION minio:
  2016-11-26T02:23:47Z

## System information
Mac OSX, Sierra

**Comment by harshavardhana** [comment]
Thanks for opening the bug we will take a look @dgoo2308

**Comment by vadmeste** [comment]
@harshavardhana, If we'll implement ignored files feature, I think it would be better to add *.part.minio to that file by default to fix this "bug".

**Comment by harshavardhana** [comment]
Yes that is the idea.
