### ISSUE TITLE
mirror: [feature] mc mirror --exclude option to exclude unwanted system files like .Ds_Store and/or to only mirror only certain extensions

### ISSUE THREAD

**Issue by dgoo2308** [minio/mc#1903]
## Expected behaviour

1. `mc mirror --exclude .* --exclude *.temp` excludes all .* files and *.temp files
2. `mc mirror --only *.a`, mirrors only *.a files

Remark : would not mind for a `mc mirror --watch --only` if an watch event was created for non compliant files, as long as they are not mirrored.
## Actual behaviour
na
## Steps to reproduce the behaviour
na
## mc version
- (paste output of `mc version`)
na

**Comment by harshavardhana** [comment]
Any files that needs to be excluded should be defaulted into the code itself. 

```
var ( // GOOS specific ignore list.
        ignoreFiles = map[string][]string{
                "darwin": {".DS_Store"},
                // "default": []string{""},
        }
)
```
Can you help us list down the files that you wish to be ignored?.

**Comment by dgoo2308** [comment]
Sorry, but I'm not a fan to hardcore that kind of thing.
Since I only use Mac, I would not known what kind of files Windows is creating, nor what files other people on other systems want to exclude.

So for Darwin, it should be `.DS_Store` and to solve #1902, one could add `*.part.minio`, that is if wildcards are supported.

On the other hand if one does not want to add a command, perhaps a `.mc_ignore` file in the destination folder could bring a solution.

Could you indicate where that var needs to be defined?

**Comment by harshavardhana** [comment]
An ignore file is perhaps easier to implement we will discuss internally and see how it can be achieved..

**Comment by vadmeste** [comment]
--exclude as a global parameter also means we can also ignore s3 objects ?

**Comment by vadmeste** [comment]
Can we discuss this ASAP ?

**Comment by harshavardhana** [comment]
> --exclude as a global parameter also means we can also ignore s3 objects ?

Yes `--exclude` is currently being worked on by @badscooter23 - he is working on a proposal to bring in regex support as well across all commands in a more generic way.

**Comment by ebozduman** [comment]
@badscooter23:
Are you still working on `--exclude` proposal?
Please let us know if you have something ready or if you have a plan to work on it. We would like to resolve the blockage on this issue.
