### ISSUE TITLE
session: [windows] mc session resume/clear fails due to file locking

### ISSUE THREAD

**Issue by felixbuenemann** [minio/mc#1904]
When using `mc session resume <id>` or `mc session clear all` on Windows, the command fails with the error "The file is in use by another process".

## mc version
mc 2016-10-07

## System information
Windows 10 Anniversary x64

**Comment by jhedlund** [comment]
I do not have an issue with mc session resume, but I have the same error with `mc session clear <id>` or `mc session clear all`.  (interestingly, `mc session resume <id>`  cleans up the session files fine).

I tracked down the problem to the `migrateSession` function.  In particular, `migrateSessionV7ToV8`. This opens a file pointer to the data file, and never closes it. 

Just doing this:
```golang
if sessionVersion > 7 { // It is new format.
    sV7.DataFP.Close() // Fixes situation
    continue
}
```
Resolves it, though that's probably not the best place (or only?) for it.  I don't immediately see why the `mc session resume <id>`  would properly clean up, perhaps the sV7 object is garbage collected by the time it gets to the final upload and no longer has a handle to the file..?

**Comment by harshavardhana** [comment]
> Resolves it, though that's probably not the best place (or only?) for it. I don't immediately see why the mc session resume <id> would properly clean up, perhaps the sV7 object is garbage collected by the time it gets to the final upload and no longer has a handle to the file..?

Not sure @jhedlund - looks like a bug we will fix it  // cc @vadmeste

**Comment by harshavardhana** [comment]
ping @vadmeste were you able to validate this?
