### ISSUE TITLE
config: Check if older binaries can run with newer config.json

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1913]
## Expected behaviour
Fail if older binaries are used with newer config.json

## Actual behaviour
Not sure need to test.

**Comment by harshavardhana** [comment]
ping @vadmeste - can you validate this when you have time. ?

**Comment by vadmeste** [comment]
> ping @vadmeste - can you validate this when you have time. ?

The current config version is 8, the release https://github.com/minio/mc/releases/tag/RELEASE.2016-02-19T04-11-55Z is supposed to work with config v7 but it doesn't show any error when it loads a config file v8, after that release, mc starts to use config v8.

**Comment by harshavardhana** [comment]
> The current config version is 8, the release https://github.com/minio/mc/releases/tag/RELEASE.2016-02-19T04-11-55Z is supposed to work with config v7 but it doesn't show any error when it loads a config file v8, after that release, mc starts to use config v8.

Yeah we need to error out.

**Comment by harshavardhana** [comment]
Actually you have already fixed this @vadmeste with new release this will be addressed.

```
$ mc
mc: <ERROR> Config version '9' does not match mc config version '8', please update your binary.

```

**Comment by vadmeste** [comment]
yes @harshavardhana, I am checking with session files now, will open a new issue if it is not handled properly.

**Comment by harshavardhana** [comment]
#1940 should fix that too.

**Comment by harshavardhana** [comment]
Closing this since this is already handled.
