### ISSUE TITLE
mirror: Rewrite mirror command and simplify the overall behavior.

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1916]
Current code saves watch events also in the session which complicates the code, clean this up with new agreed design 

 - `mc mirror`  regular should save session and resume like `cp`
 - `mc mirror -w` should mirror and save session.  Once all the data is transferred delete the session
    and watch for events..

**Comment by vadmeste** [comment]
Taking this..

**Comment by harshavardhana** [comment]
Thanks @vadmeste

**Comment by harshavardhana** [comment]
This is available in current master.
