### ISSUE TITLE
admin: implement admin commands (service, lock, heal)

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1918]
## Expected behaviour
We need to have new admin commands which use minio admin go library to send commands to the specified minio server.

This task depends on:
#1921 
#1920 
#1919 

## Actual behaviour
We don't have these commands yet

## mc version
All versions

## System information
All systems

**Comment by harshavardhana** [comment]
Can you open issues for each.. since these will be brought in distinctively.

**Comment by GarimaKapoor** [comment]
Deleting this issue as the individual issues are already open.
