### ISSUE TITLE
Feature request: webhooks

### ISSUE THREAD

**Issue by alexellis** [minio/mc#1932]
One of the strong advantages of genuine S3 is the webhook support or events getting pushed to the SNS queue. Is this on the Road map?

**Comment by harshavardhana** [comment]
> One of the strong advantages of genuine S3 is the webhook support or events getting pushed to the SNS queue. Is this on the Road map?

We already have that with ListenBucketNotification - https://docs.minio.io/docs/golang-client-api-reference#ListenBucketNotification

There are large list of event notification endpoints we already support 

- https://blog.minio.io/part-5-5-publish-minio-events-via-postgresql-50f6cc7a7346#.xpwc689v3
- https://blog.minio.io/part-4-5-publish-minio-events-via-nats-79114ea5cd29#.ew5cuxb6y
- https://blog.minio.io/part-3-3-publish-minio-events-via-redis-8403557631cd#.5hos36pg5
- https://blog.minio.io/part-2-3-publish-minio-events-via-elasticsearch-ce7a080fa89f#.ppcxxb8em
- https://blog.minio.io/part-1-3-publish-minio-events-via-rabbitmq-8dd747632623#.c0qyt48el

We won't be doing our own SNS like product if that's what you mean.
