### ISSUE TITLE
alpine build

### ISSUE THREAD

**Issue by dcharbonnier** [minio/mc#1933]
On alpine 3.4
```
/ # curl -O https://dl.minio.io/client/mc/release/linux-amd64/mc
/ # chmod +x mc
/ # ./mc
sh: ./mc: not found
```

**Comment by vadmeste** [comment]
@dcharbonnier, what does `uname -a` return in your alpine machine ?

**Comment by dcharbonnier** [comment]
go get work on golang:1.7.4-alpine and I'm able then to copy /go/bin/mc on a alpine:3.4 image, the executable work, if you could just add the process to your CD itwould be nice.

the same thing as you 😛 
```
docker run --rm alpine uname -a
Linux dcb32b7a934f 4.4.39-moby #1 SMP Fri Dec 16 07:34:12 UTC 2016 x86_64 Linux
```

**Comment by dcharbonnier** [comment]
`apk add --no-cache ca-certificates` is required for the binary to work correctly

**Comment by vadmeste** [comment]
I build mc locally in my machine using CGO_ENABLED=0, the produced binary is no more dynamically linked and it seems that it resolved the problem.

**Comment by dcharbonnier** [comment]
can we automate this process and release like that ?
