### ISSUE TITLE
pipe not working on s3

### ISSUE THREAD

**Issue by dcharbonnier** [minio/mc#1934]
## Expected behaviour
Upload should success with `mc pipe` on s3
```
echo "test"|./mc pipe david/alpine-pipe/pipe-alpine && echo "OK"
echo "test"|./mc pipe s3test/$BUCKET/pipe-alpine && echo "OK"
```
should return 
```
OK
OK
```
## Actual behaviour
Works with minio latest but fail with s3

Return
```
OK
mc: <ERROR> Unable to write to one or more targets. Input reader closed pre-maturely. Expected ‘-1’ bytes, but only received ‘0’ bytes.
```

## Steps to reproduce the behaviour
https://gist.github.com/dcharbonnier/9df28ae546968dd1ce0944729df52429

## mc version
go get from today

## System information
alpine, this may be relevant

**Comment by dcharbonnier** [comment]
don't think about an error on the amazon credential, mc ls mc copy etc work ;-)

**Comment by harshavardhana** [comment]
```
$ echo "test" | mc pipe s3/andoria/object
$ mc ls s3/andoria/object
[2016-12-21 08:52:37 PST]     5B object
```

Seems to be working fine.

**Comment by dcharbonnier** [comment]
adding `--debug` it's a problem of authorizations, pipe require special authorizations on the bucket

**Comment by dcharbonnier** [comment]
`s3:ListBucketMultipartUploads` is required
