### ISSUE TITLE
admin: status shouldn't print XL related struct in json for FS

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1948]
## Expected behaviour
```
$ mc admin service status home --json
{"status":"success","storageInfo":{"Total":177038229504,"Free":115952594944,"Backend":{"Type":FS"}}}
```

## Actual behaviour
```
$ mc admin service status home --json
{"status":"success","storageInfo":{"Total":177038229504,"Free":115952594944,"Backend":{"Type":1,"OnlineDisks":0,"OfflineDisks":0,"ReadQuorum":0,"WriteQuorum":0}}}
```

Should just have type and should point to something meaningful not "1" to "FS or "XL" or something and Disks related info shouldn't be printed if absent.

## Steps to reproduce the behaviour

Start master minio server and use the above command

## mc version
master

**Comment by vadmeste** [comment]
@harshavardhana, shouldn't we keep online/offline disks information ?

Also, it looks like we should make change in madmin package instead, what do you think @harshavardhana ?

**Comment by harshavardhana** [comment]
> @harshavardhana, shouldn't we keep online/offline disks information ?

We should only for XL not for FS we shouldn't print something in JSON which we don't print in regular UI for example FS we don't print anything about offline, online disks.  But in JSON it exists which is not correct.

**Comment by harshavardhana** [comment]
> Also, it looks like we should make change in madmin package instead, what do you think @harshavardhana, @krisis ?

Also the TYPE should have a string conversion to a meaningful value like "FS" or "XL"  this can be done on the `mc` side since mc has a UI component to it.
