### ISSUE TITLE
admin: Should support --debug

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1949]
## Expected behaviour
--debug behaves like S3 calls for admin API as well. 

## Actual behaviour
Nothing is printed 

```
$ mc admin lock list home --debug
mc: <ERROR> Cannot get lock status. Got HTTP Status: 400 Bad Request
 (0) admin-lock-list.go:150 cmd.mainAdminLockList(..)
 Release-Tag:DEVELOPMENT.2017-01-06T09-32-09Z | Commit:7cec8f228596 | Host:prtsc | OS:linux | Arch:amd64 | Lang:go1.7.4 | Mem:3.1MB/9.2MB | Heap:3.1MB/5.8MB
```
## Steps to reproduce the behaviour
Just run master minio server and list lock command.

## mc version
master

**Comment by vadmeste** [comment]
Taking this

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/mc/pull/1951
