### ISSUE TITLE
Does mc mirror --watch support mc rm  ?

### ISSUE THREAD

**Issue by goodforever** [minio/mc#1952]
Does mc mirror --watch support mc rm files ?

mc mirror --watch minio1/mybucket minio2/mybucket 
mc cp test.txt minio1/mybucket
mc rm test.txt ,inio1/mybucket , test.txt cannot be removed on minion/mybucket.

**Comment by harshavardhana** [comment]
@goodforever you need to provide `mc mirror --watch --remove --force`

**Comment by vadmeste** [comment]
Closing as answered.
