### ISSUE TITLE
mc config host list formatting bug

### ISSUE THREAD

**Issue by poornas** [minio/mc#1954]
## Expected behaviour
Awkward formatting. Needs to be tabular
`➜  ~ mc config host list 
gcs: https://storage.googleapis.com <-  YOUR-ACCESS-KEY-HERE |  YOUR-SECRET-KEY-HERE | S3v2
local: http://localhost:9000
play: https://play.minio.io:9000        <-  Q3AM3UQ867SPQQA43P2F |zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG |  S3v4
s3: https://s3.amazonaws.com <-  YOUR-ACCESS-KEY-HERE |  YOUR-SECRET-KEY-HERE |  S3v4`
## Actual behaviour
Needs to be properly tabbed.
## mc version
- (paste output of `mc version`)

**Comment by harshavardhana** [comment]
Fixed in master.
