### ISSUE TITLE
mc cp command stalled every other run

### ISSUE THREAD

**Issue by crapougnax** [minio/mc#1961]
## Expected behaviour
Copy a file from a server with mc to a minio server
 
## Actual behaviour
Every other execution of the PUT query get stalled forever: the first 'mc cp' runs smooth, the following is blocked and needs to be stopped with Ctrl-C

## Steps to reproduce the behaviour
use mc cp over and over, every odd execution fails. (see attached file - some data anonymized)
[mc-cp-debug.txt](https://github.com/minio/mc/files/701940/mc-cp-debug.txt)

## mc version
Version: 2016-12-09T18:23:19Z
Release-tag: RELEASE.2016-12-09T18-23-19Z
Commit-id: 64166319eeaed70cdb0e1a24ea97416a9600052e

## System information
4.4.0-47-generic #68~14.04.1-Ubuntu SMP Wed Oct 26 19:42:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@crapougnax can you provide more details on is the server hung on the client is hung?  does the cp continue after server is restarted?

**Comment by harshavardhana** [comment]
Closing this insufficient data.
