### ISSUE TITLE
--json not honored properly for `mc admin` behaves inconsistently

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1962]
## Expected behaviour
`--json` is a global flag and should be honored as global value.

## Actual behaviour
```
$ mc admin --json service status play
Total: 630GiB, Free: 554GiB. Online Disks: 8, Offline Disks: 0.

$ mc admin service --json status play
{"status":"success","storageInfo":{"total":675875831808,"free":595090522112,"backend":{"backendType":"XL","onlineDisks":8,"offlineDisks":0}}}
``` 

## Steps to reproduce the behaviour
Just do `mc admin 
## mc version
Current master

## System information
System information.

**Comment by vadmeste** [comment]
I opened a new issue here https://github.com/urfave/cli/issues/585 with a minimal example, I will wait for an answer for couple of days before trying new alternatives. It seems that at least we can avoid using many levels of sub commands which seems to be the root of the problem.

**Comment by harshavardhana** [comment]
> I see that cli package is responsible for the bug. I opened a new issue here urfave/cli#585 with a minimal example, I will wait for an answer for couple of days before trying new alternatives. It seems that at least we can avoid using many levels of sub commands which seems to be the root of the problem.

I see this is an older bug.  I think then its okay will wait for upstream.
