### ISSUE TITLE
cp/mirror: [feature] More threads for multipart?

### ISSUE THREAD

**Issue by jhedlund** [minio/mc#1974]
## Expected behaviour

Faster upload of large file multipart transfers, similar to aws s3 command.

## Actual behaviour

With process explorer, mc is using 4 parallel connections to s3 compared to 10 connections for aws cli s3

## Steps to reproduce the behaviour

mc.exe cp large file

## mc version
- (paste output of `mc version`)

Version: 2016-12-09T18:23:19Z
Release-tag: RELEASE.2016-12-09T18-23-19Z
Commit-id: 64166319eeaed70cdb0e1a24ea97416a9600052e

## System information

Windows

I was looking to see if there was a flag for specifying the number of threads to use for upload, but I did not see anything.   Does the multipart upload break down the file in 5MB parts?

In practice, I am seeing ~1Mbps upload with mc.   I get 3-5Mbps with aws cli.   Using process explorer, I see there are four connections to aws when using mc.  aws cli is using 10.

I don't know if that would be the only difference in the performance.

**Comment by harshavardhana** [comment]
We do 64MB parts with 3 threads we wish to not make this configurable it is part of design @jhedlund - it is chosen as a good value for 90% of use cases.  We do not wish to increase this value to 10. 

Feel to modify this in source at https://github.com/minio/minio-go and compile.

**Comment by jhedlund** [comment]
Great, thanks for the response!

**Comment by jhedlund** [comment]
Instead of increasing the default number of threads, what about a command line flag to specify a different number of threads?  I'll look at the source regardless, and see if bumping to a higher number of threads makes a big difference.

**Comment by harshavardhana** [comment]
> Instead of increasing the default number of threads, what about a command line flag to specify a different number of threads? I'll look at the source regardless, and see if bumping to a higher number of threads makes a big difference.

We could do but potentially we always like to keep the options to the minimum, let me explore this internally with the team.

**Comment by jhedlund** [comment]
Quick update:  Adding more threads is a big help, making it 9 threads more than doubled the speed of the upload (for a large file at least).

**Comment by harshavardhana** [comment]
> Quick update: Adding more threads is a big help, making it 9 threads more than doubled the speed of the upload (for a large file at least).

Understood @jhedlund

**Comment by deekoder** [comment]
Related to https://github.com/minio/minio-go/issues/686
