### ISSUE TITLE
Tool name collides with Midnight Commander

### ISSUE THREAD

**Issue by j-vizcaino** [minio/mc#1981]
`mc` binary is typically used by the [Midnight Commander](https://en.wikipedia.org/wiki/Midnight_Commander) application.
As you can see, this popular tool has been around for more than 20 years and still actively maintained.

Maybe renaming the Minio client to `minioc` or `mioc` (shorter) would help the two programs coexist.

**Comment by harshavardhana** [comment]
We won't be doing this has been discussed and closed..  previously

- https://github.com/minio/mc/issues/873
- https://github.com/minio/mc/issues/1825
- https://github.com/minio/mc/issues/1206

`mc` is a single binary and can reside inside your application and is fully self contained. Besides, Minio Client is an object storage client. Midnight Commander (mc) is a free software clone of proprietary Norton Commander (nc). Minio and Midnight shares no code or ideas. Only their abbreviation is same.

**Comment by harshavardhana** [comment]
A possible solution https://github.com/minio/mc/issues/873#issuecomment-267583013
