### ISSUE TITLE
binary distribution of mc for arm64 (ARMv8, aarch64)?

### ISSUE THREAD

**Issue by vielmetti** [minio/mc#1983]
## Expected behaviour

https://dl.minio.io/client/mc/release/ would have downloadable arm64 (aarch64) binaries.

## Actual behaviour

Binaries not found.

## Steps to reproduce the behaviour

1. visit https://dl.minio.io/client/mc/release/
2. inspect directory

## mc version
- (paste output of `mc version`)

## System information

To be installed on Packet 2A, 96-core ARMv8 server.

**Comment by harshavardhana** [comment]
This will be taken care in the next release cycle for mc.

**Comment by harshavardhana** [comment]
> This will be taken care in the next release cycle for mc. For now source build is an option.

And also linux-arm release works fine.

**Comment by vielmetti** [comment]
When I try to build from source I get this, fyi:

```
root@docker-build-test:/mnt/src/minio/mc# make checks
Checking deps:
Check for supported arch.. Invalid arch: Linux aarch64 not supported
Makefile:6: recipe for target 'checks' failed
make: *** [checks] Error 1
```

The relevant bit of output is
```
$ arch
aarch64
```

**Comment by harshavardhana** [comment]
@vielmetti you can use 'go get' - 'make' has a list of archs which needs to be updated..
