### ISSUE TITLE
configuring servers without keys

### ISSUE THREAD

**Issue by tmbdev** [minio/mc#1989]
There doesn't seem to be any way of adding servers without keys. It seems to me that if a bucket is set to "public", I should be able to add it without any of the keys. (This also doesn't seem to work in minio-python.)

## Expected behaviour

$ mc config host add myanon http://172.10.100.34:9100
Added 'myanon' successfully
$ mc ls myanon
...
$ 

## Actual behaviour

$ mc config host add myanon http://172.10.100.34:9100
mc: <ERROR> Incorrect number of arguments for host add command. Invalid arguments provided, cannot proceed
$

**Comment by harshavardhana** [comment]
> There doesn't seem to be any way of adding servers without keys. It seems to me that if a bucket is set to "public", I should be able to add it without any of the keys. (This also doesn't seem to work in minio-python.)

You can do 

```
mc config host add myanon "" ""  http://172.10.100.34:9100
```

**Comment by harshavardhana** [comment]
Ah looks like that has stopped working.. For now as a work-around you can edit `~/.mc/config.json`
