### ISSUE TITLE
config: [feature] Request for adding aliasing paths

### ISSUE THREAD

**Issue by atomi** [minio/mc#1999]
## feature request (low priority)

Would like to be able to do operations using an alias for long paths
Instead of for example:
`mc ls minio/mybucket/deep/url/here` 
It would be nice to alias `minio/mybucket/deep/url/here` as `deepurl` 
so we could do instead:
`mc ls deepurl`

example ~/.mc/config.json
```
{
	"version": "8",
	"hosts": {
		"minio": {
			"url": "https://XXXX.com",
			"accessKey": "XXXXX",
			"secretKey": "XXXXX",
			"api": "S3v4"
		}
	},
	"aliases": {
		"deepurl": {
			"path": "minio/mybucket/deep/url/here",
		},
		"another": {
			"path": "minio/otherbucket/deep/url/here"
		}
	}		
}

```
thanks!

**Comment by CyrilPeponnet** [comment]
I could also add the capability to use a LB to server several tenants using the same entrypoint:

like `https://domain.tld/tenant(1,2)` where tenant1 resource is reverse proxying to the tenant 1 cluster and tenant2 resource is reverse proxing to the tenant2 cluster.

**Comment by kannappanr** [comment]
Will not be implementing this request currently.
