### ISSUE TITLE
Allow disabling mirror watch mode / revert default

### ISSUE THREAD

**Issue by felixbuenemann** [minio/mc#2000]
The latest mc version 2017-02-02T22:38:48Z removed the `--watch` flag of `mc mirror` and always enables watch mode.

This breaks existing scripts which depend on mirror exiting when it's done. There's also no `--no-watch` flag to disable watch mode as needed.

I would suggest reverting the default activation of watch mode and re-introduce the `-w` / `--watch` flag.

The breaking change was introduced in PR #1992.

**Comment by harshavardhana** [comment]
This was done on purpose do you need to have --watch as an option ?

**Comment by felixbuenemann** [comment]
Watch mode cannot be used when `mc mirror` is used in a script, were continuous mirroring is not wanted, it can only be used as a kind of daemon process, which fits some use cases but not all, so it should be optional like before or at least is should be possible to restore the previous behavior with a `--no-watch` switch. I'd go with reverting using watch mode by default, because it breaks existing scripts on update.

**Comment by harshavardhana** [comment]
> Watch mode cannot be used when mc mirror is used in a script, were continuous mirroring is not wanted, it can only be used as a kind of daemon process, which fits some use cases but not all, so it should be optional like before or at least is should be possible to restore the previous behavior with a --no-watch switch. I'd go with reverting using watch mode by default, because it breaks existing scripts on update.

Okay will bring the option back.

**Comment by felixbuenemann** [comment]
Thank you!

**Comment by harshavardhana** [comment]
Fixed by #2001
