### ISSUE TITLE
mc cp issue

### ISSUE THREAD

**Issue by limbo127** [minio/mc#2004]
mc from github
mc: <ERROR> Failed to copy ‘/data/upload/CM-cd4e5700-34d4-11e1-b680-eca86bf923bc-1486476921.cebox’. Your proposed upload size ‘15295971328’ exceeds the maximum allowed object size ‘5368709120’ for single PUT operation.

My file is 15G size, and limit seems to be 5G ? 
is a multipart problem ? 
is a 5G -> 5T ? problem 

Regards, 
Nicolas

**Comment by koolhead17** [comment]
Hello @limbo127 

Can you provide  output for  ``mc --debug cp [your-operation]``  and  ``mc``,  ``Minio`` server version? I will try to reproduce it.

**Comment by harshavardhana** [comment]
> mc from github
> mc: Failed to copy ‘/data/upload/CM-cd4e5700-34d4-11e1-b680-eca86bf923bc-1486476921.cebox’. Your proposed upload size ‘15295971328’ exceeds the maximum allowed object size ‘5368709120’ for single PUT operation.
> 
> My file is 15G size, and limit seems to be 5G ?
> is a multipart problem ?
> is a 5G -> 5T ? problem
> 
> Regards,
> Nicolas

where are you trying to upload @limbo127 are you uploading to Google Cloud Storage?

**Comment by limbo127** [comment]
so it's s3 upload, 
it seems a problem of access denied, with different credential, I can use multi part upload, 
but with s3cmd I do not have this problem, I think mc ask for more right that is need : 
upload, multi part action from all the bucket, not just for "directory"
Regards, 
Nicolas

mc: <DEBUG> HTTP/1.1 200 OK                                                                                                                                                        
Connection: close                                                                                                                                                                  
Transfer-Encoding: chunked                                                                                                                                                         
Content-Type: application/xml                                                                                                                                                      
Date: Wed, 08 Feb 2017 08:23:33 GMT                                                                                                                                                
Server: AmazonS3                                                                                                                                                                   
X-Amz-Bucket-Region: eu-west-1                                                                                                                                                     
X-Amz-Id-2: 7t1hZ/cHPTKUGG0hLhdnkCd+uv5Yb+PgPIyAkTViogdvL6S/P6MMOQwWOtLPUWbW52OJKKTkjkQ=                                                                                           
X-Amz-Request-Id: BCD27D5D29F6E3FB                                                                                                                                                 
                                                                                                                                                                                   
mc: <DEBUG> Response Time:  116.329405ms                                                                                                                                           
                                                                                                                                                                                   
 0 B / 14.25 GB ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃   0.00%mc: <DEBUG> GET /cebox.eu.neo/?max-uploads=1000&prefix=clients%2Fneocoretech_rd_p%2Fmedias%2FCM-cd4e5700-34d4-11e1-b680-eca86bf923bc-1486476921.cebox&uploads= HTTP/1.1            
Host: s3-eu-west-1.amazonaws.com                                                                                                                                                   
User-Agent: Minio (linux; amd64) minio-go/2.0.3 mc/DEVELOPMENT.GOGET                                                                                                               
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170208/eu-west-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**      
Expect: 100-continue                                                                                                                                                               
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD                                                                                                                                             
X-Amz-Date: 20170208T082331Z                                                                                                                                                       
Accept-Encoding: gzip                                                                                                                                                              
                                                                                                                                                                                   
mc: <DEBUG> HTTP/1.1 403 Forbidden                                                                                                                                                 
Connection: close                                                                                                                                                                  
Transfer-Encoding: chunked                                                                                                                                                         
Content-Type: application/xml                                                                                                                                                      
Date: Wed, 08 Feb 2017 08:23:31 GMT                                                                                                                                                
Server: AmazonS3                                                                                                                                                                   
X-Amz-Id-2: pLh14F5rKDxVRgshnr04ruPyQmnukQvDFHW1jAaOAZUadulATfJ04+0pwQ6x4lsbWb4Qyf2cBKI=                                                                                           
X-Amz-Request-Id: E08EDE76C4B35BCE                                                                                                                                                 
                                                                                                                                                                                   
f3                                                                                                                                                                                 
<?xml version="1.0" encoding="UTF-8"?>                                                                                                                                             
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E08EDE76C4B35BCE</RequestId><HostId>pLh14F5rKDxVRgshnr04ruPyQmnukQvDFHW1jAaOAZUadulATfJ04+0pwQ6x4lsbWb4Qyf2cBKI=</HostId></Error>                                                                                                                                                          
0                                                                                                                                                                                  
                                                                                                                                                                                   
mc: <DEBUG> Response Time:  123.571348ms                                                                                                                                           
                                                                                                                                                                                   
mc: <ERROR> Failed to copy ‘/data/upload/CM-cd4e5700-34d4-11e1-b680-eca86bf923bc-1486476921.cebox’. Your proposed upload size ‘15295971328’ exceeds the maximum allowed object size ‘5368709120’ for single PUT operation.
 (3) cp-main.go:298 cmd.doCopySession.func1(..) Tags: [/data/upload/CM-cd4e5700-34d4-11e1-b680-eca86bf923bc-1486476921.cebox]                                                      
 (2) common-methods.go:139 cmd.uploadSourceToTargetURL(..) Tags: [https://s3.amazonaws.com/cebox.eu.neo/clients/neocoretech_rd_p/medias/CM-cd4e5700-34d4-11e1-b680-eca86bf923bc-1486476921.cebox]                                                                                                                                                                     
 (1) common-methods.go:83 cmd.putTargetStreamFromAlias(..) Tags: [s3, https://s3.amazonaws.com/cebox.eu.neo/clients/neocoretech_rd_p/medias/CM-cd4e5700-34d4-11e1-b680-eca86bf923bc-1486476921.cebox]                                                                                                                                                                 
 (0) client-s3.go:593 cmd.(*s3Client).Put(..)

**Comment by limbo127** [comment]
it seems this is necessary for mc , 

   "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation",
                "s3:ListMultipartUploadParts",
                "s3:ListBucketMultipartUploads"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::*"
            ]

and with s3cmd it seems
"Resource": [
                "arn:aws:s3:::xxxxx/clients/directory_p*"

seems to be suffisient.

**Comment by harshavardhana** [comment]
Looks like you have IAM policies which have restricted usage of Multipart API, mc is falling back on using regular upload which fails because you object size exceeds the maximum allowed on S3 for a single PUT operation.

**Comment by harshavardhana** [comment]
The reason s3cmd works is because they are not using 

```
"s3:ListMultipartUploadParts",
"s3:ListBucketMultipartUploads"
```

Instead `minio-go` uses this for resuming previously uploaded incomplete multipart upload.

**Comment by harshavardhana** [comment]
With the above IAM policy it should work fine @limbo127

**Comment by limbo127** [comment]
it seems this is necessary for mc , 

   "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation",
                "s3:ListMultipartUploadParts",
                "s3:ListBucketMultipartUploads"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::*"
            ]

and with s3cmd it seems
"Resource": [
                "arn:aws:s3:::xxxxx/clients/directory_p*"

seems to be suffisient.

**Comment by limbo127** [comment]
I do not understand, 
mc cp search for part before to put an object, but in this case, why using mc session ? ( resume ) 
is mc cp automatically resuming failed upload ?

**Comment by balamurugana** [comment]
@limbo127 
`mc` (internally minio-go is used) does below when an object is trying to upload
1. When object size is > 64MiB, it uses multipart upload than normal upload.
2. When object name already exists in `ListMultipartUpload`, it tries to resume by using latest upload ID.
3. As previously mentioned by @harshavardhana, we would need respective policies need to be enabled at Amazon S3 side.

**Comment by limbo127** [comment]
thanks for explanation.
regards, 
Nicolas
