### ISSUE TITLE
Failed parsing of Go version is fatal

### ISSUE THREAD

**Issue by Gouthamve** [minio/mc#2012]
## Expected behaviour
Installed mc via source on a system using go 1.8 beta1. Should be able to use it.

## Actual behaviour
Fails with: `mc: <ERROR> Unable to determine current go version. Malformed version: 1.8beta1`

## Steps to reproduce the behaviour
Install mc via source on a system using go 1.8 beta1

**Comment by Gouthamve** [comment]
I see you are using it to check minimum go version. But, ideally, this should go away in the future and for now it should be a warning.

**Comment by harshavardhana** [comment]
Closing this as fixed and `mc` doesn't support beta/rc releases of Go.
