### ISSUE TITLE
Minio client (mc) name conflicts with Midnight Commander (mc)

### ISSUE THREAD

**Issue by romanm-odysii** [minio/mc#2016]
I suggest to change name from _mc_ to _**minio-cli**_ to prevent confusion.
'cli' means **C**ommand **L**ine **I**nterface.

**Comment by harshavardhana** [comment]
> I suggest to change name from mc to minio-cli to prevent confusion.
> 'cli' means Command Line Interface.

We will not be doing this - similar issues closed in the past - https://github.com/minio/mc/issues?q=is%3Aissue+midnight+commander+is%3Aclosed

**Comment by harshavardhana** [comment]
https://github.com/minio/mc/issues/873#issuecomment-267583013 - A possible solution.

**Comment by eugenedm** [comment]
That's lame, I used "mc" for 100 years... as midnight commander... now that we have minio... I wish it'd be like "m" or "mmc" or "mcc"... I bet there are a lot of midnight commander users that don't like this name... lol... I love Minio it's awesome, but my brain is confused by all the commands

**Comment by guettli** [comment]
@harshavardhana #873 does not contain a solution
