### ISSUE TITLE
Store configuration in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by romanm-odysii** [minio/mc#2017]
## Expected behaviour
Configuration stored in $XDG_CONFIG_HOME/PROGRAM_NAME
Follow [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) for storing configuration.

> If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/**.config** should be used.

## Actual behaviour
Configuration stored in $HOME/PROGRAM_NAME

**Comment by harshavardhana** [comment]
`mc` is a cross platform tool so what we do right now is to have a consistent behavior across platforms i.e users home directory is used for configuration. Use `--config-dir` instead to save in $HOME/.config/mc`

**Comment by romanm-odysii** [comment]
If I use `$HOME/.config/mc` next time I run will it "remember" my settings?

**Comment by harshavardhana** [comment]
> If I use $HOME/.config/mc next time I run will it "remember" my settings?

`mc` config is meant to store only your access credentials for object storage. Everything is ephemeral which should be provided through cli.

Easiest way to achieve not specifying for each command is just use bash aliases.
```
alias mc='mc -C <dir>'
```

**Comment by romanm-odysii** [comment]
Anyway, on non-POSIX systems like Windows configuration could be stored in `%APPDATA%\.config\mc`.

**Comment by harshavardhana** [comment]
> Anyway, on non-POSIX systems like Windows configuration could be stored in %APPDATA%\.config\mc.

AppData is not the right place and it is also a hidden folder on windows, we purposefully just use %USERPROFILE%/mc and $HOME/.mc on rest -  it is easy to understand, document and is portable with no forced specifications to follow.

Closing this as a non-issue.

**Comment by psnszsn** [comment]
The XDG Base Directory Specification is being widely adopted by Linux/BSD applications. If you would like to reconsider, you can follow it only on POSIX systems and use `%USERPROFILE%/mc` on Windows.

If not, it would be nice if you at least offered the option to set the config directory with an environment variable, e.g. `$MC_CONFIG_DIR`.

**Comment by harshavardhana** [comment]
Locking the conversation here, this is an old issue please reopen a new issue if you are not satisfied with the resolution here.
