### ISSUE TITLE
Implement options --newer-than and --older-than for cp, rm, mirror

### ISSUE THREAD

**Issue by limbo127** [minio/mc#2025]
Hello, 
is it possible to implement timestamp difference in mirror and diff function.
mirror only with size different is unusable for us. A timestamp sync will be very useful.
Regards, 
Nicolas

**Comment by harshavardhana** [comment]
> Hello,
> is it possible to implement timestamp difference in mirror and diff function.
> mirror only with size different is unusable for us. A timestamp sync will be very useful.
> Regards,
> Nicolas

@limbo127 timestamp cannot be synced on object storage - there is no API to update ModTime alone.

**Comment by limbo127** [comment]
ok, but it makes senses from S3 --> local filesystem for example.

**Comment by limbo127** [comment]
to be more precise, when we puts object on s3, the timestamp change, content but not size . Then we must synchronise to our local fs ( sharing data) .

**Comment by harshavardhana** [comment]
> ok, but it makes senses from S3 --> local filesystem for example.

Questions:

- How often do you re-upload the same object twice? and why would you do that? 
- Is it just to update the timestamp?

**Comment by limbo127** [comment]
- we have a lot of files with size does not change, because ot the nature of these files.
Example : 
database file, raw image file with size define at the creation of file, but content change

we are uploading each week, our first test with mc , we only mirror files with size change.

No, the content of file change, so it's a new upload. To summarize, we are uploading a lot of file with content differe but not size. I thing raw image file for virtual machine as kvm is good example of this type of file.
Regards

**Comment by limbo127** [comment]
to complete, we are using S3 but we wants to migrate de minio-server , to have Lan server.

**Comment by vadmeste** [comment]
We probably should add a parameter to specify the minimal time difference between source and target objects to decide if we need to trigger mirroring

**Comment by vadmeste** [comment]
Can we discuss this ?

**Comment by deekoder** [comment]
Implement  global options --newer-than and --older-than

**Comment by vadmeste** [comment]
ETA: 27 Apr
