### ISSUE TITLE
Suggest `mc config host remove` alias

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#2027]
Refer - https://github.com/minio/minio/issues/3770

## Expected Behavior

With most UNIX command-line tools `rm` is acceptable in the place of `remove`:

```
docker rm
git rm
git remote rm upstream
rm -rf ./test.file
mc rm play/bucket1/test_file.txt
```

It felt jarring as a UX that I could not type in `mc config host rm <host_config>` and I would like to suggest the change.

@harshavardhana if you're OK with the suggestion I don't mind looking into the code and making the change.

Alex

**Comment by alexellis** [comment]
Thanks for moving the issue.

**Comment by abperiasamy** [comment]
* add | remove | list
* add | rm | ls
* add | rm | list
It was kept as `remove` to be consistent with `add`. If you change remove->rm, then users would expect `list` also to be `ls`.

**Comment by harshavardhana** [comment]
> It was kept as remove to be consistent with add. If you change remove->rm, then users would expect list also to be ls.

We can have a sub-command short hands which would work too @abperiasamy .

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/mc/pull/2069

**Comment by alexellis** [comment]
Sounds good to me. Thanks all for this UX fix, looks good. 👍
