### ISSUE TITLE
Not possible to add new host

### ISSUE THREAD

**Issue by marekmkmk** [minio/mc#2032]
## Expected behaviour

It should be possible to add host in the following format http://IP_ADDRESS/path1/path2.

## Actual behaviour
mc.exe throws "Invalid URL" message. 
It's possible to add only URL without additional paths

## Steps to reproduce the behaviour

Add host with additional paths

## mc version
Version: 2017-02-06T20:16:19Z
Release-tag: RELEASE.2017-02-06T20-16-19Z
Commit-id: 2c8115de4edc5612525488b1b3b804689d336d01

## System information
Windows 2012 R2 x64

**Comment by harshavardhana** [comment]
A new host is only a url we don't support having subpaths in them as it can cause confusing behavior for for commands. Error generated is indeed correct it is an invalid url from `mc` point of view.

**Comment by marekmkmk** [comment]
I'm trying to connect to S3 compatible service which presents S3 as IP_ADDRESS/service/s3/

**Comment by harshavardhana** [comment]
May we know what is the S3 compatible service and show an example how it works with aws-sdk ? With an endpoint like this.!

**Comment by harshavardhana** [comment]
> May we know what is the S3 compatible service and show an example how it works with aws-sdk ? With an endpoint like this.!

Closing this as non-issue for now.

**Comment by josdotso** [comment]
I'm having this problem with minio deployed with helm .  minio is behind nginx-ingress and the path is the reverse proxy method used, because external dns won't allow us to subdomain it.   Is there any hope for using `SOME_IP/minio` as the endpoint?

**Comment by harshavardhana** [comment]
> I'm having this problem with minio deployed with helm . minio is behind nginx-ingress and path is the reverse proxy method used, because external dns won't allow us to subdomain it. Is there any hope for using SOME_IP/minio as the endpoint?

`/minio` is a reserved prefix it will not work.
