### ISSUE TITLE
mc ls , strange wildcard mode

### ISSUE THREAD

**Issue by limbo127** [minio/mc#2035]
hello, 
is it a normal behaviour that's 
mc ls s3/bucket/test

list alls keys test*  ?

If it's normal, how can ls ( to get info) on simple key ?
Regards,

**Comment by harshavardhana** [comment]
Yes it is S3 specific behavior it is a flat namespace. So every key is a prefix so the server lists which matches the prefix entirely . It is an expected normal behavior.

**Comment by limbo127** [comment]
ok, perhaps is interesting to have a mc stat key ?  with json output ( size, date .. ) ?

**Comment by harshavardhana** [comment]
> ok, perhaps is interesting to have a mc stat key ? with json output ( size, date .. ) ?

Why would you need that?  are you not planning to copy a file?

**Comment by limbo127** [comment]
we are using mc to synchronize file between difference src / dst server.
mc syncronisation is very "poor"  , and we are trying to simulating rsync
via dirrents scripts.
comparaison of file in size, in date , in md5 for example,
so info about file without copying it, it's very interesting.


2017-02-27 22:13 GMT+01:00 Harshavardhana <notifications@github.com>:

**Comment by harshavardhana** [comment]
> we are using mc to synchronize file between difference src / dst server.
> mc syncronisation is very "poor"  , and we are trying to simulating rsync
> via dirrents scripts.
> comparaison of file in size, in date , in md5 for example,
> so info about file without copying it, it's very interesting.

`mc` synchronization is kept simpler for a reason adding md5sum on top of it won't work for multi-parted objects. These type of features should be avoided from `mc` because what you want to implement is something along the lines of http://rclone.org/ and https://restic.github.io/ which do a better job already.

You don't need to write one from scratch.

**Comment by harshavardhana** [comment]
Closing this as a non issue for the moment.
