### ISSUE TITLE
mc ls , listing is different between recursive and non recursive mode

### ISSUE THREAD

**Issue by limbo127** [minio/mc#2042]
Hello,
imagine , tree as  : 
s3/xxx/test/1/file1
s3/xxx/test/2/file2 
 
mc ls s3/xxxx/test/ 
shows : 1 , 2 as directory type

mc ls -r s3/xxxx/test/
shows  1/file1 , 2/file2   as file type , 

this is a normal behaviour of flat s3 , but it 's very strange representation for ls command, 
i'im using this, to compare directory / file between s3 and local .

Regards,
Nicolas

**Comment by harshavardhana** [comment]
This is expected since filesystem is already treated like a flat namespace.  @limbo127 remember in `mc` FS looks like S3 instead of S3 looking like FS.  It is part of the design.
