### ISSUE TITLE
Migrate from `config.json` to `config.yml` / `config.yaml` 

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#2053]
## Expected behaviour

Propose a new yaml configuration based on our current JSON config.

## Actual behaviour

JSON is crippling to be used as a config file due to lack of comments / self documentation abilities. We should explore if we can migrate to yaml (benefits)

## mc version 

All versions

## System information

All operating systems

**Comment by vadmeste** [comment]
I wasn't able to find a yaml library which preserves comments, it is true that yaml ignores comments but Unmarshal then Marshal will discard initial comments. 

mc has `config host add` command which modifies the config file, hence comments will be lost. Minio server config file is generated only the first time we run the server but we can hard code the config file and put random access/secret keys without using structs (little ugly, I know)

On the other side, one developer (https://github.com/DirectXMan12/go-yaml/tree/feature/comments) added support of comments by adding a tag in struct definition, like
```
type myStruct struct {
  Field1 string `yaml:"field1" yamlComment:"my comment"`
}
```

It seems to me a reasonable solution if we really want to stick to YAML.

By the way, with YAML, even one added space at the beginning of line can lead to syntax error. On the other hand, HCL config format seems to be more comfortable with comments and more user friendly (https://github.com/hashicorp/hcl) ?

What do you think?

**Comment by vadmeste** [comment]
This task is deferred to the future.

**Comment by harshavardhana** [comment]
This was decided to be not implemented.
