### ISSUE TITLE
size difference between source and destination (feature request)

### ISSUE THREAD

**Issue by pablopla** [minio/mc#2055]
A command to show the size diff between source and destination could be:
```
mc diff --size localdir/ play/mybucket
```
result:
```
2035.42 MB
```

The old mirror command used to show the total target size but now it does streaming copy with no session files.

**Comment by harshavardhana** [comment]
This was decided to be not implemented as it doesn't provide any purpose at the moment and can be calculated using `mc diff --json` output outside of mc.
