### ISSUE TITLE
Binary name `mc` clashes with Midnight Commander

### ISSUE THREAD

**Issue by chriscowley** [minio/mc#2060]
The binary for [Midnight Commander](http://midnight-commander.org/) is also `mc` which

1. Clashes with the binary that already exists in many systems
2. Means that the docs and the installation output is at best potentially misleading, at worst plain wrong.

Given that Midnight Commander's first commit was more than 20 years ago, perhaps this project needs to review the name of its binary? Personally I have used `minioclient`.

**Comment by harshavardhana** [comment]
We will not be doing this similar issues closed in the past and provide a better explanation https://github.com/minio/mc/issues?q=is%3Aissue+midnight+commander+is%3Aclosed

A very simple solution would be here - https://github.com/minio/mc/issues/873#issuecomment-267583013

**Comment by naggie** [comment]
Another problem: bash autocompletions mean that filenames don't complete with the `mc` command -- just directories.
