### ISSUE TITLE
pipe to STDOUT not working

### ISSUE THREAD

**Issue by tsmgeek** [minio/mc#2061]
mc says it can pipe to STDOUT but when tried it just hangs doing nothing, is documentation not clear on this as there is nothing in Examples but description says it can.

## Steps to reproduce the behaviour
./mc pipe myminio/myfirstbucket/test.pdf > /tmp/test.pdf

## mc version
Version: 2017-02-06T20:16:19Z
Release-tag: RELEASE.2017-02-06T20-16-19Z
Commit-id: 2c8115de4edc5612525488b1b3b804689d336d01

**Comment by vadmeste** [comment]
@tsmgeek, mc can pipe to stdout, but you told mc to pipe to myminio/myfirstbucket/test.pdf instead. Omitting  myminio/myfirstbucket/test.pdf  will tell pipe to print to stdout. 

However, I guess in your case, you want to use `cat` command instead: 
`./mc pipe myminio/myfirstbucket/test.pdf > /tmp/test.pdf` will save myminio/myfirstbucket/test.pdf  content in /tmp/test.pdf

**Comment by tsmgeek** [comment]
I suspected that this was the case but it was not clear to me what someone would want to pipe to STDOUT unless it was retrieved from a file and pipe out ie as you said the cat command.

**Comment by harshavardhana** [comment]
this is fixed in master - closing.
