### ISSUE TITLE
cp/mirror: [feature] bring mc transparent encryption

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#2074]
## Expected behaviour

Add a new sub-field for the aliases supporting transparent encryption.
```json
"encryption": {                                                                                                                                   
   "AES": {                                                                                                                                       
      "enable": true,                                                                                                                             
      "key": ""                                                                                                                                   
   },                                                                                                                                             
   "RSA": {                                                                                                                                       
      "enable": false,                                                                                                                            
      "publicKey": "/path/to/public.key",                                                                                                         
      "privateKey": "/path/to/private.key"
   },
}
```

There are no new flags are expected for mc. But a new command should be added. 

```
mc encrypt <alias> on
mc encrypt <alias> off
```

```
mc encypt <alias> on AES <optional_key>
```

```
mc encrypt <alias> on RSA <optional_public_key> <optional_private_key>
```

Not only does the above command enables encryption it should also either take input or generate symmetric/assymetric keys automatically for the user. So for a given alias if one of the encryptions are enabled all outgoing data to remote site is encrypted and all downloaded data is automatically decrypted. 

## Actual behaviour

No encryption support available

## mc version
master 

## System information
All platforms

**Comment by vadmeste** [comment]
ETA: 23 Apr

**Comment by bollig** [comment]
What is the status of this?

**Comment by vadmeste** [comment]
ETA: 24 June

**Comment by ebozduman** [comment]
Pinging @vadmeste for status?

**Comment by vadmeste** [comment]
@ebozduman, this issue waits for this PR to be merged https://github.com/minio/minio-go/pull/830

**Comment by deekoder** [comment]
@harshavardhana  / @poornas  is this the same thing you guys are working on.

**Comment by harshavardhana** [comment]
> @harshavardhana / @poornas is this the same thing you guys are working on.

Yes its the same thing @poornas is working on.
