### ISSUE TITLE
Multi-part upload fails back to single PUT on some (non-minio) servers

### ISSUE THREAD

**Issue by viawest-davidsix** [minio/mc#2086]
## Expected behaviour
When uploading a large file, `mc` should use multi-part uploads
## Actual behaviour
`mc` attempts to use multi-part upload, gets a `HTTP 403` response, and fails back to a single `PUT`
When `--debug` is specified, this results in a large spike in memory usage, which seems to hit `[filesize]*2`
Tested combinations:
* `mc cp` -> riak-cs: single `PUT`, RSS ~8.1MB
* `mc cp --debug` -> riak-cs: single `PUT`, RSS ~1700MB
* `mc cp` -> minio: multi-part, RSS ~8.5MB
* `mc cp --debug` -> minio: multi-part, RSS ~160MB
* `aws s3 --debug cp` -> riak-cs: multi-part, RSS ~60MB
## Steps to reproduce the behaviour

1. Start a riak-cs server (docker steps here) `docker run -d --env 'RIAK_CS_BUCKETS=test' -p 80:8080 --name riakcs ianbytchek/riak-cs `
1. After a few seconds for startup, get credentials: `docker logs riakcs` 
1. Add configuration to `mc`: `mc config host add riak http://[docker_host_ip]:80 [AccessKey] [SecretKey] S3v2`
1. Copy a large file into the bucket: `mc cp ubuntu-16.04.2-server-amd64.iso riak/test/`
    * If you add `--debug` there is a memory usage spike toward the end of the transfer

## mc version
Version: 2017-02-06T20:16:19Z
Release-tag: RELEASE.2017-02-06T20-16-19Z
Commit-id: 2c8115de4edc5612525488b1b3b804689d336d01

## System information
x86_64 VM running RHEL 6

**Comment by vadmeste** [comment]
@viawest-davidsix, can you tell us what is the size of the file you are testing with ?

**Comment by viawest-davidsix** [comment]
http://releases.ubuntu.com/16.04/ubuntu-16.04.2-server-amd64.iso (829MB ISO)

**Comment by vadmeste** [comment]
> http://releases.ubuntu.com/16.04/ubuntu-16.04.2-server-amd64.iso (829MB ISO)

Thanks, will do some memory profiling and see why --debug is consuming huge memory.

**Comment by vadmeste** [comment]
Looks like Riak returns 403 Access Denied for non apparent reason, at least for me.

The following are two consecutvies web service calls, the second is actually returning 403.

1.

```
mc: <DEBUG> GET /test/?max-uploads=1000&prefix=80mb.bin&uploads= HTTP/1.1

<?xml version="1.0" encoding="UTF-8"?><ListMultipartUploadsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>test</Bucket><KeyMarker></KeyMarker><NextKeyMarker/><NextUploadIdMarker></NextUploadIdMarker><Delimiter></Delimiter><Prefix>80mb.bin</Prefix><MaxUploads>1000</MaxUploads><IsTruncated>false</IsTruncated><Upload><Key>8
0mb.bin</Key><UploadId>QsbxgdvySmWkYZ2X84hQPg==</UploadId><Initiator><ID>DHCJEOOSFIUTPKPFU6HZ</ID><DisplayName>admin</DisplayName></Initiator><Owner><ID>DHCJEOOSFIUTPKPF
U6HZ</ID><DisplayName>admin</DisplayName></Owner><StorageClass>STANDARD</StorageClass><Initiated>2017-03-31T21:25:16.000Z</Initiated></Upload></ListMultipartUploadsResult>
```


2.

```
GET /test/80mb.bin?max-parts=1000&part-number-marker=0&uploadId=QsbxgdvySmWkYZ2X84hQPg%3D%3D HTTP/1.1

<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/test/80mb.bin</Resource><RequestId></RequestId></Error>
mc: <DEBUG> Response Time:  3.005754ms
```
