### ISSUE TITLE
mc share download command without --recursive option should do an exact match

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#2088]
## Expected behaviour

```
$ mc share download play/test/passwd
URL: https://play.minio.io:9000/test/passwd
Expire: 7 days 0 hours 0 minutes 0 seconds
Share: https://play.minio.io:9000/test/passwd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20170324%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170324T005456Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a7e9f0aaa2aa746f2e8c845e075ea372fa6959e3633cefc25d508d6d825c7894
```

## Actual behaviour

```
$ mc share download play/test/passwd
URL: https://play.minio.io:9000/test/passwd
Expire: 7 days 0 hours 0 minutes 0 seconds
Share: https://play.minio.io:9000/test/passwd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20170324%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170324T005456Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a7e9f0aaa2aa746f2e8c845e075ea372fa6959e3633cefc25d508d6d825c7894

URL: https://play.minio.io:9000/test/passwd1
Expire: 7 days 0 hours 0 minutes 0 seconds
Share: https://play.minio.io:9000/test/passwd1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20170324%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170324T005456Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=88805ba91feb61a8a5c7cb89a2e7712f97c293519cf4cc95254cbbcd3a93a4ce
```

## Steps to reproduce the behaviour
Just have two files with same prefix. 

## mc version
master

## System information
All platforms.

**Comment by badscooter23** [comment]
This bug appears to be bigger than the `mc share` command to me... 

if you have three objects (logo, logo1, logo2) in a bucket test... 

`mc ls mymino/log` will show all objects.... 

Scotts-MacBook-Pro$ ./mc ls myminio/test/logo
[2017-03-27 15:14:19 PDT] 2.6KiB logo
[2017-03-27 15:14:19 PDT] 2.6KiB logo1
[2017-03-27 15:16:08 PDT]  11KiB logo2

by contrast the `ls logo` shell command will only show the file named logo

Scotts-MacBook-Pro$ pwd
/Users/scottmcclellan/Pictures/test
Scotts-MacBook-Pro$ ls logo
logo


mc appears to be doing an implicit * at the object name so 

mc ls myminio/logo                             // is equivalent to
mc ls myminio/logo*

mc share download myminio/logo      // is equivalent to          
mc share download mymino/logo*

It seems like this is a bug in and of itself and is independent of the --recursive opition... 

Thoughts?

**Comment by badscooter23** [comment]
Summary of long discussion with Harsha:

-`mc ls` and `mc share` have different intended uses, so it is ok that the behave differently
- today `mc share` will match all objects with a prefix and return multiple urls if there are multiple
  matches, this behavior is deemed to be a bug

thus if we have test/logo, test/logo1, test/logo2

- `mc ls myminio/test/logo` will show all three objects (without explicitly saying `--recursive`)
- `mc share download myninio/test/logo` will only return a single url unless you say `--recursive`
