### ISSUE TITLE
mc: Global flags do not affect initialization messages

### ISSUE THREAD

**Issue by viawest-davidsix** [minio/mc#2089]
## Expected behaviour
Global flags `--no-color`, `--quiet`, `--json`, and `--debug` should be used for all output
All output should be de-colorized/supressed/json/verbose as specified
## Actual behaviour
The initialization messages are output with color in plaintext regardless of the specified options
```
$ mc --no-color --quiet --json --config-folder=/tmp config host list
mc: Configuration written to ‘/tmp/config.json’. Please update your access credentials.
mc: Successfully created ‘/tmp/share’.
mc: Initialized share uploads ‘/tmp/share/uploads.json’ file.
mc: Initialized share downloads ‘/tmp/share/downloads.json’ file.
{"status":"success","alias":"gcs  ","URL":"https://storage.googleapis.com","accessKey":"YOUR-ACCESS-KEY-HERE","secretKey":"YOUR-SECRET-KEY-HERE","api":"S3v2"}
```
![image](https://cloud.githubusercontent.com/assets/9539060/24314423/e2df34bc-10b7-11e7-824d-06673e936bbd.png)

## Steps to reproduce the behaviour
1. Run `mc` with one of the above options with a `config-folder` that has not been previously used

## mc version
```
Version: 2017-02-06T20:16:19Z
Release-tag: RELEASE.2017-02-06T20-16-19Z
Commit-id: 2c8115de4edc5612525488b1b3b804689d336d01
```
## System information
Bash shell on Ubuntu

**Comment by vadmeste** [comment]
Shall we hide initialization messages when json flag is activated ?

**Comment by harshavardhana** [comment]
> Shall we hide initialization messages when json flag is activated ?

Actually we shouldn't we should have a JSON equivalent.
