### ISSUE TITLE
diff: ui change move from `only in first` to new format

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#2090]
## Expected behaviour

```
> /home/harsha/Photos/alice (11).jpg
> /home/harsha/Photos/alice (12).jpg
< https://play.minio.io:9000/testbucket/bin/7z
< https://play.minio.io:9000/testbucket/bin/7za
v https://play.minio.io:9000/testbucket/new-image.jpg
```

Here 

```
> - indicates file should be copied
< - indicates file should be deleted
v - indicates file differs in size. 
```

## Actual behaviour

Current output needs to be improved.

## Steps to reproduce the behaviour
Just build from master

## mc version
master

## System information
All operating systems.

**Comment by vadmeste** [comment]
![screenshot from 2017-03-29 22-53-05](https://cloud.githubusercontent.com/assets/283197/24478379/88955a3a-14d2-11e7-97e1-676ad6daa348.png)

I suggest using `!` instead of `v`

**Comment by harshavardhana** [comment]
makes sense.. @vadmeste
