### ISSUE TITLE
admin: mc admin heal --fake ambigious message

### ISSUE THREAD

**Issue by hackintoshrao** [minio/mc#2092]
## Expected behaviour
`mc admin heal --fake` to return something like `object can be healed` rather than `object is healed`. In general just define the possibility, not the verb.
## Actual behaviour
prints that the object is healed.
## Steps to reproduce the behaviour
`mc admin heal --fake alias/bucket `
## mc version
2017-03-15T06:10:26Z

**Comment by krisis** [comment]
This issue has been fixed in master. This issue can be closed.

## Test output
```
➜  mc git:(master) mc version
Version: 2017-04-07T13:18:42Z
Release-tag: DEVELOPMENT.2017-04-07T13-18-42Z
Commit-id: 5805a37d27ac99d8c91913b2c0c0e81f066d5810
➜  mc git:(master) mc admin heal --fake s1
Object: test/o2, can be healed.

```
