### ISSUE TITLE
share: `mc share download` clean up; `--recursive option` and error messages

### ISSUE THREAD

**Issue by badscooter23** [minio/mc#2099]
## Expected behaviour

Assuming: 
bucket `foo` has objects `bar1` and `bar2`

(NOTE: I updated assumption, the original text had a mistake.)

Then: 

`mc share download play/foo/bar`
should give an error (and it does), but the current error message is not good

`mc share download play/foo/bar --recursive`
should succeed and return two download URLs, one each for `bar1` and `bar2`; currently it returns no URLs and and the same error message

`mc share download play/foo/invalid`
should fail (which it does) but the current error message is not good

`mc share download play/foo/invalid --recursive`
should fail, currently it does fail but the error message is not good

## Actual behaviour

`mc share download play/foo/bar`
`mc share download play/foo/bar --recursive`
`mc share download play/foo/invalid`
`mc share download play/foo/invalid --recursive`

all generate the same error:
mc: <ERROR> Unable to stat `play/foo/bar`. Object key is missing, object key cannot be empty
or
mc: <ERROR> Unable to stat `play/foo/invalid`. Object key is missing, object key cannot be empty

The message should be more descriptive: 

mc <ERROR> Object `play/foo/invalid` does not exist.

Also the second case should NOT be an error, it should succeed.

## Steps to reproduce the behaviour

see above

## mc version
- (paste output of `mc version`)

Scotts-MacBook-Pro-2:mc scott$ mc version
Version: 2017-03-31T00:31:47Z
Release-tag: DEVELOPMENT.2017-03-31T00-31-47Z
Commit-id: 3c0094a5fe84d632b87030a46f3f2d696947cc13

## System information

can be reproduced on any system
done using mc version (above) against `play.minio.io:9000`

**Comment by vadmeste** [comment]
Hey @badscooter23,



> Assuming:
> bucket foo has objects bar1 and bar
> 
> Then:
> 
> mc share download play/foo/bar
> should give an error (and it does), but the current error message is not good

If we are assuming that bucket `foo` bucket has `bar` object, why `mc share download play/foo/bar` should return an error ?

**Comment by badscooter23** [comment]
Hey @vadmeste 

You are correct. The original text had a mistake  so it did not make sense. 
It should have said:

Assuming:
bucket foo has objects `bar1` and `bar2`

With this correction it should make sense do you. `mc share download play/foo/bar` should return an error because `play/foo/bar` does not exist and the user did not specify `--recursive`. 

NOTE: It does return an error with your fix, as it should, but the error message (which was in the original code, not something you changed) is not very descriptive (so we are going to make it better).

**Comment by badscooter23** [comment]
What's the status on this PR? I updated the commit message using `git amend` ... is there another step I need to do?

**Comment by badscooter23** [comment]
We are going to separate two aspects of this PR /Issue and address them in separate PR(s).

- Today, various `mc` commands treat the case where the user specifies a path to an object AND also specifies `--recursive` in an inconsistent manner. 

Specifically most commands (`ls`, `cp`, `mirror`, etc) treat the `mc COMMAND play/foo/invalid --recursive` case as an error and return the same error as they return if the `--recursive` option is not specified. Today `mc share download play/foo/invalid --recursive` does not return an error for this cases. There is some debate as to which behavior is correct. The behavior should be consistent. I am going to remove this aspect of the fix for now and we will address this in a separate PR>

- Today various `mc` commands all return the same missleading error.. 

mc: Unable to stat play/foo/invalid. Object key is missing, object key cannot be empty

For this PR I am going to address the second part of that message "Object key is missing, object key cannot be empty" but not change the first part. This will make the message consistent and better across multiple `mc` commands. We will address the large error cleanup (where the commands point back to `stat` failing (which is not really meaningful to end users) in a separate pr.

**Comment by deekoder** [comment]
Lowering priority to medium since its not an issue with no workaround.
