### ISSUE TITLE
mirror: mc mirror --watch --force --remove ignores changes after some days

### ISSUE THREAD

**Issue by xstillwill** [minio/mc#2105]
mc mirror --watch --force --remove ignores changes after some days

## Expected Behavior
it should mirror local content to minio server even after days without desynch of local and remote location

## Current Behavior
restarting the "mc mirror --watch --force --remove" cmd after some 10+days revealed that it missed out on a couple 150+ delete operations and also on some uploads

## Steps to Reproduce (for bugs)
1. have a directory wich is constantly updated 24/7 (we have advertisements coming in every few minutes and some vanish after they're expired)
2. have mc mirror --watch --force --remove ./local minio/remotebucket running
3. after some days restart the process and see mc delete a lot and upload some files

## Context
constantly mirror local to central distribution server.
have a near realtime updated playlist / content on the playout systems.

## Your Environment
Debian jessie
mc from 2 weeks ago i think. (version flag says 0.0.0)
caddyserver in front of minio (timeouts set to 30 minutes)

**Comment by vadmeste** [comment]
For now, I am not assuming that running `mc mirror -w` for a long time is causing the issue.

I found one issue when manually testing: when mc mirror watches a local directory, some fast changes on that directory are not detected:

Terminal 1:
`$ mc mirror -w ./local myminio/testbucket/`

Terminal 2:
`$ cd ./local ; for i in $(seq 1 1000) ; do echo "1" >> file$i ; done`

**Comment by harshavardhana** [comment]
The filesystem itself is not generating these events consistently ? @vadmeste is our dependent library?

**Comment by vadmeste** [comment]
> The filesystem itself is not generating these events consistently ? @vadmeste is our dependent library?

Increasing this https://github.com/minio/mc/blob/master/cmd/client-fs.go#L104 from 1 to 1000 fixed the problem, but that value is arbitrary.

**Comment by harshavardhana** [comment]
> Increasing this https://github.com/minio/mc/blob/master/cmd/client-fs.go#L104 from 1 to 1000 fixed the problem, but that value is arbitrary.

It is not arbitrary in-fact the events might be lost because they are not queued up, we might have increase it further if necessary to hold a particular set of events or write a new style of queue which can expand and shrink dynamically based on the rate of incoming events.

**Comment by vadmeste** [comment]
> It is not arbitrary in-fact

Yeah, I meant I chose 1000 as an arbitrary value.

> we might have increase it further if necessary to hold a particular set of events or write a new style of queue which can expand and shrink dynamically based on the rate of incoming events.

Yeah good idea, we need a code which receives and stores events as fast as possible, so the upper level can work with a lower pace.

**Comment by harshavardhana** [comment]
> Yeah good idea, we need a code which receives and stores events as fast as possible, so the upper level can work with a lower pace.

We did have that with session :-) now we need to do this in-memory.

**Comment by vadmeste** [comment]
I can get something ready tomorrow, like a separate package which has a logic queue that expands and shrinks. In addition to some benchmarks, like how many entries per second the queue can safely store before starting to drop new entries (should about millions per second)

**Comment by deekoder** [comment]
Need to test with user on whether our fix, takes care of this issue.

**Comment by deekoder** [comment]
@xstillwill  we have fixed this issue. Is it possible to tell us if you are still seeing this issue? Will close now as fixed.

**Comment by vadmeste** [comment]
Missed deletes are fixed by this PR https://github.com/minio/mc/commit/61e511cc3e4d80f7910869c37a3a200b2e438d10

**Comment by xstillwill** [comment]
I will setup Server/Client and Check / Report back :) trank you!

Von meinem iPhone gesendet

Am 11.06.2017 um 18:44 schrieb Dee Koder <notifications@github.com<mailto:notifications@github.com>>:


@xstillwill<https://github.com/xstillwill> we have fixed this issue. Is it possible to tell us if you are still seeing this issue? Will close now as fixed.

-
