### ISSUE TITLE
Please add an 'ignore existing' flag for 'mb' sub-command

### ISSUE THREAD

**Issue by stephenreay** [minio/mc#2115]
When provisioning an environment (either development, or production-ish) it's often useful to be able to say "create a new bucket in minio (or s3, etc) if it doesn't exist" - essentially the same as the `-p` flag for `mkdir`.

I'd suggest **not** using `-p`, as this has different semantics in `mkdir`. Perhaps `--ignore-existing` is a better option?

**Comment by badscooter23** [comment]
This is a good point, and to add some context the behavior is different than the default behavior for the AWS S3 CLI

Scotts-MacBook-Pro-2:mc scott$ aws s3 mb s3://scott-mcclellan-test-bucket
make_bucket: scott-mcclellan-test-bucket
Scotts-MacBook-Pro-2:mc scott$ aws s3 mb s3://scott-mcclellan-test-bucket
make_bucket: scott-mcclellan-test-bucket
Scotts-MacBook-Pro-2:mc scott$ mc mb myminio/scott-mcclellan-test-bucket
Bucket created successfully `myminio/scott-mcclellan-test-bucket`.
Scotts-MacBook-Pro-2:mc scott$ mc mb myminio/scott-mcclellan-test-bucket
mc: <ERROR> Unable to make bucket `myminio/scott-mcclellan-test-bucket`. Your previous request to create the named bucket succeeded and you already own it.

**Comment by harshavardhana** [comment]
> Scotts-MacBook-Pro-2:mc scott$ aws s3 mb s3://scott-mcclellan-test-bucket
> make_bucket: scott-mcclellan-test-bucket
> Scotts-MacBook-Pro-2:mc scott$ aws s3 mb s3://scott-mcclellan-test-bucket
> make_bucket: scott-mcclellan-test-bucket

You have to use non `us-east-1` region to see the error . `us-east-1` never returns an error on previous bucket creates.

**Comment by badscooter23** [comment]
@harshavardhana That's "odd"... I believe you, but it is "odd"...
