### ISSUE TITLE
heal: Update support for mc admin heal command.

### ISSUE THREAD

**Issue by deekoder** [minio/mc#2123]
```
 mc admin heal --force --remove --recursive --advanced --fake ALIAS[/Bucket/Prefix]
```
When only ALIAS is passed, heal the server and all the buckets.
When ALIAS/bucket is passed, heal the server and the specific bucket.
When ALIAS/bucket/prefix is passed, heal the server, the specific bucket and all objects under this prefix level  
When --recursive is passed for ALIAS , heal all buckets, all prefix, all objects.
When --advanced is a slow operation, which will read all object content and verify bitrot.
When --remove is passed with --force, will delete irreparable objects.

**Comment by krisis** [comment]
>Heal APIs

>Refer to changes to heal command specified here : minio/mc#2123
@krishnasrinivas will propose API changes here based on :

@krishnasrinivas let me know when the API proposal is ready for admin heal APIs.

**Comment by xilu0** [comment]
Why I didn't find admin command, cannot use the

**Comment by krisis** [comment]
@xilu0 `mc admin` command is being developed and some of its features are available on master branch. It is _not_ available in the latest release of Minio server.

**Comment by xilu0** [comment]
@krisis 
thanks from respond,I understand the.

**Comment by harshavardhana** [comment]
This is fixed already in master
