### ISSUE TITLE
Add --fast option to mc

### ISSUE THREAD

**Issue by deekoder** [minio/mc#2125]
--fast option : wont do md5 /sha256 computations. @harshavardhana  please add more details to this issue.

**Comment by krisis** [comment]
@harshavardhana is this issue still valid? Could you provide more details?

**Comment by harshavardhana** [comment]
> @harshavardhana is this issue still valid? Could you provide more details?

Actually this issue is not valid anymore.. we have defaulted to using streaming signature for all operations.

**Comment by krisis** [comment]
@harshavardhana Can we close this issue then?

**Comment by harshavardhana** [comment]
Yes we can @krisis
