### ISSUE TITLE
Can access using AWS CLI but MC gives me Access Key ID Does Not Exist

### ISSUE THREAD

**Issue by vfulco** [minio/mc#2144]
## Expected behaviour

AWS config
[default]
aws_access_key_id = Fake Key ID
aws_secret_access_key = Fake Access Key
region = cn-north-1
s3 =
---
MC Config

"s3": {
                        "url": "https://s3.cn-north-1.amazonaws.com.cn",
                        "accessKey": "Same Fake Key ID",
                        "secretKey": "Same Fake Secret Key",
                        "api": "S3v4"

Access Beijing AWS S3 using aws ls s3-foo

"2015-12-31 15:06:39 wss-test"

## Actual behaviour

Error Message

## mc version
 ./mc version
Version: 2017-04-03T18:35:01Z
Release-tag: RELEASE.2017-04-03T18-35-01Z
Commit-id: 81d17d28ec28987ba3c57349fc57b4c064bb5b37

## System information

Ubuntu 16.04// tried with sudo and as regular user

**Comment by vadmeste** [comment]
@vfulco, I tried with your mc config (url and API)  and with the same mc version and it just works for me. Can you check again if you put the correct access & secret keys ?

**Comment by vfulco** [comment]
Thanks for the prompt response.  I tried again, even ran aws ls, got the expected result and copied the access ID and secret key id direct from the aws config file.  Next steps are to 1) check if permission issue and 2) create a new access/key setup and 3) uninstall and reinstall mc.  Would prefer to use it for mirroring local folders.

**Comment by vfulco** [comment]
New ID & Key doesn't work.  Oddly debugging comes across a reference back to s3.amazonaws.com.  Because of governmental restrictions, the AWS S3 in China is an island unto itself.  Any reference back to AWS mothership is probably where the issue lies.   

./mc --debug ls s3
mc: <ERROR> Unable to list folder. Get https://s3.amazonaws.com/: dial tcp 52.216.66.11:443: i/o timeout
 (1) ls.go:134 cmd.doList(..) Tags: [https://s3.cn-north-1.amazonaws.com.cn/]

**Comment by harshavardhana** [comment]
> mc: Unable to list folder. Get https://s3.amazonaws.com/: dial tcp 52.216.66.11:443: i/o timeout

Looks like a bug on our end @vfulco

**Comment by vfulco** [comment]
Thanks much for the reply.  AWS in the PRC throws a lot of curve balls
at programmers so don't feel so bad.  Now I can learn how to file a
bug report.  Be well, V.

On 5/2/17, Harshavardhana <notifications@github.com> wrote:
>> mc: Unable to list folder. Get https://s3.amazonaws.com/: dial tcp
>> 52.216.66.11:443: i/o timeout
>
> Looks like a bug on our end @vfulco
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/minio/mc/issues/2144#issuecomment-298510689


-- 
Vince Fulco, CFA, CAIA
612.424.5477 (universal)
186.1694.0908 (mobile in China)
vfulco1@gmail.com
wechat: vfulco
fastmail: vfulco1@fastmail.fm
corporate: vfulco@weisisheng.cn
https://about.me/vincefulco

--
"Always be yourself, express yourself, have faith in yourself, do not
go out and look for a successful personality and duplicate it." Bruce
Lee

**Comment by vfulco** [comment]
See item #7 here for same issue.
https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions

On 5/2/17, Vince Fulco <vfulco1@gmail.com> wrote:
> Thanks much for the reply.  AWS in the PRC throws a lot of curve balls
> at programmers so don't feel so bad.  Now I can learn how to file a
> bug report.  Be well, V.
>
> On 5/2/17, Harshavardhana <notifications@github.com> wrote:
>>> mc: Unable to list folder. Get https://s3.amazonaws.com/: dial tcp
>>> 52.216.66.11:443: i/o timeout
>>
>> Looks like a bug on our end @vfulco
>>
>> --
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/minio/mc/issues/2144#issuecomment-298510689
>
>
> --
> Vince Fulco, CFA, CAIA
> 612.424.5477 (universal)
> 186.1694.0908 (mobile in China)
> vfulco1@gmail.com
> wechat: vfulco
> fastmail: vfulco1@fastmail.fm
> corporate: vfulco@weisisheng.cn
> https://about.me/vincefulco
>
> --
> "Always be yourself, express yourself, have faith in yourself, do not
> go out and look for a successful personality and duplicate it." Bruce
> Lee
>


-- 
Vince Fulco, CFA, CAIA
612.424.5477 (universal)
186.1694.0908 (mobile in China)
vfulco1@gmail.com
wechat: vfulco
fastmail: vfulco1@fastmail.fm
corporate: vfulco@weisisheng.cn
https://about.me/vincefulco

--
"Always be yourself, express yourself, have faith in yourself, do not
go out and look for a successful personality and duplicate it." Bruce
Lee

**Comment by vadmeste** [comment]
@vfulco, I believe I understood the origin of the problem. Since I can't test, can I send to you a binary or a diff to test on your side ?

**Comment by vfulco** [comment]
Yes please do.  My email is vfulco [@] gmail.com.  Remove the spaces
and brackets.

On 5/3/17, Anis Elleuch <notifications@github.com> wrote:
> @vfulco, I believe I understood the origin of the problem. Since I can't
> test, can I send to you a binary or a diff to test on your side ?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/minio/mc/issues/2144#issuecomment-298943587


-- 
Vince Fulco, CFA, CAIA
612.424.5477 (universal)
186.1694.0908 (mobile in China)
vfulco1@gmail.com
wechat: vfulco
fastmail: vfulco1@fastmail.fm
corporate: vfulco@weisisheng.cn
https://about.me/vincefulco

--
"Always be yourself, express yourself, have faith in yourself, do not
go out and look for a successful personality and duplicate it." Bruce
Lee

**Comment by vadmeste** [comment]
@vfulco, any update on this ?

**Comment by vfulco** [comment]
Mea culpa for the delay.  Excellent work.  I am in Shanghai and server
is in Beijing.  Response was immediate; sub-second even.  Thanks for
your time Anis!  Now onto setting up a Minio server elsewhere and
using this as backup/mirror.



On 5/11/17, Anis Elleuch <notifications@github.com> wrote:
> @vfulco, any update on this ?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/minio/mc/issues/2144#issuecomment-300554232


-- 
Vince Fulco, CFA, CAIA
612.424.5477 (universal)
186.1694.0908 (mobile in China)
vfulco1@gmail.com
wechat: vfulco
fastmail: vfulco1@fastmail.fm
corporate: vfulco@weisisheng.cn
https://about.me/vincefulco

--
"Always be yourself, express yourself, have faith in yourself, do not
go out and look for a successful personality and duplicate it." Bruce
Lee

**Comment by haio** [comment]
@vadmeste @vfulco can you send me a workable binary file for linux, my email is mockingror@gmail.com. I have the same problem with aws china s3. Btw, `mc(version: 2016-06-03T18:48:37Z)` works on my mac.
Thanks!

**Comment by harshavardhana** [comment]
> @vadmeste @vfulco can you send me a workable binary file for linux, my email is mockingror@gmail.com. I have the same problem with aws china s3. Btw, mc(version: 2016-06-03T18:48:37Z) works on my mac.
> Thanks!

@haio we will fix and make a release soon.

**Comment by haio** [comment]
@harshavardhana Great! 👍
