### ISSUE TITLE
corrupted file between loca source and S3 destination.

### ISSUE THREAD

**Issue by limbo127** [minio/mc#2148]
Hello, 
we are synchronizing file between local and s3 account. 
We are using mc cp command. (last stable)
Some our files ( bigfile ~ 5G ) are corrupted in s3 account : 
- file is present but this md5sum differe from local one, size of s3 file is more ( +100Mo) .

Is it possible ? what happened for example if 2 mc cp command ( with same file ) are running in // ?

Regards, 
Nicolas

**Comment by harshavardhana** [comment]
@limbo127 how do you know they are corrupted? were you trying to verify md5sum? 

Can you provide us following details? 

- paste the file size `ls -l <local_file>` 
- paste the md5sum of `_local_file` 
- calculate md5sum of s3 using `mc cat`

**Comment by limbo127** [comment]
sorry, it seems that's is another component ( not mc ) that is the bad thing .
