### ISSUE TITLE
usage of mc with an url and no .minio config

### ISSUE THREAD

**Issue by dcharbonnier** [minio/mc#2152]
for scripting, working with dynamic environments it would be nice to do :
`mc ls https://KEY:SECRET@server.com:9000/`

instead of creating a config file

**Comment by kannappanr** [comment]
This feature is supported via environment variable. Closing this issue as fixed.

**Comment by mjpowersjr** [comment]
@kannappanr - is there documentation on what env variables are supported?

**Comment by harshavardhana** [comment]
@mjpowersjr we haven't documented it yet. But you can use mc with just envs like this..

```
export MC_HOSTS_myminio=https://access:secret@endpoint:port/ 
mc ls myminio
```

**Comment by mjpowersjr** [comment]
Awesome. Thanks for the help!!!

**Comment by mjpowersjr** [comment]
Hmm ... I'm not sure if I'm doing something wrong, or discovered a bug. Setting up my environment as you described lets me list buckets using `mc ls <alias>` - but it doesn't look like I can specify a bucket path via the command line. Examples that do not seem to work:

```
# lists buckets under myalias, instead of the files inside some_bucket
mc ls myalias/some_bucket

# mc: <ERROR> Unable to write to one ore more targets. Bucket name cannot be empty.
date | mc pipe myalias/some_bucket/now.txt
```

**Comment by vadmeste** [comment]
@mjpowersjr this is a bug! Can you open a new issue ?
