### ISSUE TITLE
mc admin heal display "mc: <ERROR> Cannot heal object ``. Failed to parse server response. mc: <ERROR> Cannot heal object ``. Failed to parse server response."

### ISSUE THREAD

**Issue by bearmoo-repo** [minio/mc#2154]
## Expected behaviour
mc amdin heal example.com
<no output>
## Actual behaviour
mc: <ERROR> Cannot heal object ``. Failed to parse server response.
mc: <ERROR> Cannot heal object ``. Failed to parse server response.

## Steps to reproduce the behaviour
mc amdin heal example.com

## mc version
- (paste output of `mc version`)
[root@mgmt-node ~]# mc version
Version: 2017-04-24T20:21:22Z
Release-tag: DEVELOPMENT.2017-04-24T20-21-22Z
Commit-id: 61e511cc3e4d80f7910869c37a3a200b2e438d10

## System information
Centos 7.2 6bit Core.

/go/src/github.com/minio # minio version
Version: 2017-05-12T00:37:05Z
Release-Tag: DEVELOPMENT.2017-05-12T00-37-05Z
Commit-ID: 3bc9e6101cbd5ffddf363f5051cf560ada854e12

**Comment by harshavardhana** [comment]
mc admin is in alpha we are not recommending its usage. It is not fully released yet and is in the process of being rewritten

**Comment by ebozduman** [comment]
This is dup of https://github.com/minio/mc/issues/2123
Closing it.
