### ISSUE TITLE
more acceptance of misnamed buckets

### ISSUE THREAD

**Issue by gtallan** [minio/mc#2157]
This has been brought up before in #1715 and I guess maybe #2134, but I would find it a great help if mc were more accepting of non-compliant bucket names.

As an issue this does go beyond AWS and their us-east-1 region; for example the ceph radosgw implements an s3 interface but (unfortunately) only does very loose validation of bucket names. As a result we have many users who have created non-compliant buckets, and who are thus unable to use mc despite it being the nicest and most user-friendly client I've encountered.

What would be ideal from my perspective is if mc enforced DNS bucket naming conventions during bucket creation, but accepted non-compliant names for other operations. I can't help suspecting this must affect other people using non-AWS S3 backends.

It's not helpful that radosgw (and arguably us-east-1) permit non-compliant names, but it's also unfortunate that mc prevents access to such already-existing buckets.

**Comment by harshavardhana** [comment]
> As an issue this does go beyond AWS and their us-east-1 region; for example the ceph radosgw implements an s3 interface but (unfortunately) only does very loose validation of bucket names. As a result we have many users who have created non-compliant buckets, and who are thus unable to use mc despite it being the nicest and most user-friendly client I've encountered.
> 
> What would be ideal from my perspective is if mc enforced DNS bucket naming conventions during bucket creation, but accepted non-compliant names for other operations. I can't help suspecting this must affect other people using non-AWS S3 backends.
> 

This is a possibility can be done for newly created buckets but allow reading from older buckets. We can even throw a warning sign that your bucket is using a legacy name. 

And is a simple enough change we can do.

**Comment by gtallan** [comment]
Thank you, that would be a great change if possible. Well, ideally it would allow both read and write to the non-compliant buckets (just not creation of such names). Sadly our users are saddled with their bad bucket names, sometimes containing large amount of data. Most buckets were probably created using s3cmd, which I guess must leave name validation to the server side.

There was some discussion a while back (~2015) in ceph-devel about better S3 bucket name validation but it appears never to have been committed.

**Comment by cypa** [comment]
Trying to migrate old ceph-radosgw photo storage to minio and I've got trouble with bucket names like 'Photos' with upper case letters ...

**Comment by harshavardhana** [comment]
> Trying to migrate old ceph-radosgw photo storage to minio and I've got trouble with bucket names like 'Photos' with upper case letters ... what is the hack to migrate bucket named 'Photos' to minio?

On minio we don't allow such bucket names to be created, please create a bucket name with lower case characters @cypa - create a new bucket say `photos` and then just to `mc mirror alias/Photos alias/photos` 

Currently `mc` is not honoring uppercase bucket names but we can do that by avoiding implicit validation and letting the user copy existing buckets.

**Comment by harshavardhana** [comment]
Going to keep this blocked for now.. on @abperiasamy - since we need to decide on the behavior here as it would affect our libraries as well such as `minio-go` which is where the bucket name restrictions are coming from.

**Comment by harshavardhana** [comment]
Reopening until minio-go is vendorized.
