### ISSUE TITLE
When will the next version release

### ISSUE THREAD

**Issue by tru2dagame** [minio/mc#2158]
## Expected behaviour
The latest release version doesn't support s3.cn-north-1 region.

## Actual behaviour
I just searched and got this PR. It does support s3 cn now.
https://github.com/minio/mc/pull/2153

So that the Homebrew / Docker version doesn't work. And I tried to install from the source code, it works with s3 cn well.

## mc version
Version: 2017-04-03T18:35:01Z
Release-tag: RELEASE.2017-04-03T18-35-01Z
Commit-id: c22c076eac03dc291323f49e07c4a25722ad5bb0

## Hoping
Will minio/mc release a new update with s3 cn soon? It will be great to stick with docker / brew install. Don't need to worry about the updating things.

**Comment by harshavardhana** [comment]
You can use the latest from `go get github.com/minio/mc` , we will be making a new release soon.

**Comment by tru2dagame** [comment]
Hi @harshavardhana 
Thanks. I'm using the `DEVELOPMENT` version right now.
I spend a couple hours with this issue then realized it hasn't been released...
