### ISSUE TITLE
mc mirror shows misleading status message

### ISSUE THREAD

**Issue by poornas** [minio/mc#2161]
## Expected behaviour
Did a mc mirror operation to mirror 2 buckets. The operation completes fine, but the status message, completion status bar and filename does not reflect total size transmitted correctly. recursive cp on same bucket however gives correct status.
## Actual behaviour
mc mirror status msg indicates the operation did not fully complete.
## Steps to reproduce the behaviour
$ mc cp --recursive gcs2/newbucket33 gcs2/newbucket444
...00/newbucket33/opencv:  83.91 MB / 83.91 MB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 30.86 MB/s 2s

$ mc mirror gcs2/newbucket33 gcs2/aquaregia   
...00/newbucket33/opencv:  5.68 MB / 83.91 MB  ▓▓▓▓▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  1.72 MB/s
## mc version
- (paste output of `mc version`)
Version: 2017-05-13T05:43:51Z
Release-tag: DEVELOPMENT.2017-05-13T05-43-51Z
Commit-id: 971487250ec2159ff226a3477a92922e11a8cd1c

## System information
osx

**Comment by NitishT** [comment]
Sent a fix https://github.com/minio/mc/pull/2165
