### ISSUE TITLE
mc ls mygcs returns unactionable error

### ISSUE THREAD

**Issue by deekoder** [minio/mc#2162]
```
mc ls mygcs
mc: <ERROR> Unable to list folder. The specified bucket is not valid.
```

## Expected behaviour
list of buckets on gcs

## Actual behaviour
above error

## Steps to reproduce the behaviour
1. Start minio gateway gcs with acess key and secret key with project id.
2. minio gateway starts successfully.
3. add mc config host as shown by the CLI on start
4. mc ls mygcs returns above error

## mc version
- (paste output of `mc version`)
```
Version: 2017-04-03T18:35:01Z
Release-tag: RELEASE.2017-04-03T18-35-01Z
Commit-id: c22c076eac03dc291323f49e07c4a25722ad5bb0
````

## System information
macOS

Server has this error : 
```
 source=[bucket-handlers.go:213:objectAPIHandlers.ListBucketsHandler()] stack=~/go/src/github.com/minio/minio/cmd/gateway-gcs.go:264:(*gcsGateway).ListBuckets ~/go/src/github.com/minio/minio/cmd/bucket-handlers.go:211:objectAPIHandlers.ListBucketsHandler 
~/go/src/github.com/minio/minio/cmd/api-router.go:100:(objectAPIHandlers).ListBucketsHandler-fm
```

**Comment by harshavardhana** [comment]
This is not a client problem per se. What does regular server return ?

**Comment by hackintoshrao** [comment]
Validated with **mc version**

```
Version: 2017-03-15T06:10:26Z
Release-tag: DEVELOPMENT.2017-03-15T06-10-26Z
Commit-id: 43693592867420ad43f767ab26d8fb45dbb81051

```
and minio server built from `feature-gcs` branch at commit 8c30dcddee6bae7b83519cee8983dfe881317c6b . 

And it works.

**Comment by krishnasrinivas** [comment]
@deekoder it's working as expected on latest code on feature-gcs, can you check again?

**Comment by deekoder** [comment]
@hackintoshrao  need an update on this.

**Comment by donatello** [comment]
This errors happens when the gateway starts up after being given an invalid project id. Filed bug here - https://github.com/minio/minio/issues/4449

**Comment by deekoder** [comment]
Closing this as its a server side bug. Should go away once the above is fixed.
