### ISSUE TITLE
mc ls -r s3/ shows `Bucket name contains invalid characters.` error

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#2168]
## Expected behaviour
Normal listing without any error.

## Actual behaviour

mc error when listing: 
`mc: <ERROR> Unable to list folder. Bucket name contains invalid characters.`

## Steps to reproduce the behaviour
```
$ mc ls -r s3/
mc: <ERROR> Unable to list folder. Bucket name contains invalid characters.
mc: <ERROR> Unable to list folder. Bucket name contains invalid characters.
[2017-06-02 15:21:36 CET]    26B harshavardhana/pref
[2017-05-25 07:46:19 CET]    26B harshavardhana/prefix/object1
[2017-05-25 07:46:25 CET]    26B harshavardhana/prefix/object2
....
```

## mc version
master

## System information
All

**Comment by vadmeste** [comment]
This is high priority.

**Comment by harshavardhana** [comment]
There is a similar bug opened in minio-go is it same ?

**Comment by vadmeste** [comment]
> There is a similar bug opened in minio-go is it same ?

I can't find any similar issue in minio-go

**Comment by harshavardhana** [comment]
Oops my bad cross posted..

**Comment by harshavardhana** [comment]
This should be fixed in the master.. @vadmeste can you validate and close?

**Comment by vadmeste** [comment]
The error is not there anymore, closing..
