### ISSUE TITLE
mc progress bar does not show real time update

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#2169]
## Expected behaviour
mc progress bar should show real time progress with a not so excellent internet connection

## Actual behaviour
mc progress bar updates itself each 10 seconds with a download speed of around 800 kbytes/sec

## Steps to reproduce the behaviour
mc cp s3/vadmeste/128mb.file /tmp

## mc version
master

## System information
All

**Comment by vadmeste** [comment]
Low priority

**Comment by harshavardhana** [comment]
There is no definitive value here. The reader is updated as it's read into a give buffer rather than using ReadAt we can use just Read. This would allow to less buffering and more progress showing
