### ISSUE TITLE
Proposal for new `mc find` command

### ISSUE THREAD

**Issue by donatello** [minio/mc#2175]
The following gist contains a proposal for the `mc find` subcommand:
https://gist.github.com/donatello/116b8d8849c343f696794e0d96606e87

This command would be useful in finding files, performing pattern matches, creating customized output and executing actions on matched files. It is inspired by the UNIX find command but is only loosely based on it with the aim of making a simple command with a set of powerful features.

**Comment by CarterMcClellan** [comment]
Wrote an updated gist (now implemented which proposes a couple of changes and extensions on the mc command)

Gist: https://gist.github.com/CarterMcClellan/3744f1ad74ec757bf83163a1c5d25183
