### ISSUE TITLE
mirror: question about behavior 

### ISSUE THREAD

**Issue by dennisbappert** [minio/mc#2184]
Sorry for posting the question as an issue: how is the behavior of mc mirror when set it up as a cronjob with --watch. In case of a machine failure on the mirroring machine: is the mirroring resumed at the state the machine died? Do I get any inconsistencies? 

Thanks in advance

**Comment by vadmeste** [comment]
> Sorry for posting the question as an issue

No problem.

> how is the behavior of mc mirror when set it up as a cronjob with --watch.

When you specify `--watch` flag, mc will run forever. I am not sure if it is a good idea to use this flag in a cronjob.

> In case of a machine failure on the mirroring machine: is the mirroring resumed at the state the machine died? Do I get any inconsistencies?

Killing mc mirror in a middle of any operation is not a problem at all. You won't get any inconsistencies. Next time your run mc mirror, it will first check if it missed anything and resume normally.

**Comment by dennisbappert** [comment]
Not as a repeating cronjob, just to start with the machine. I'm born in the windows world so it was my naive translation for the task scheduler. 

Thanks for the answer -> can be closed I think.

**Comment by harshavardhana** [comment]
> Not as a repeating cronjob, just to start with the machine. I'm born in the windows world so it was my naive translation for the task scheduler.

You could perhaps use https://nssm.cc/ to configure this like a service which is run every time the server reboots. @dennisbappert - feel free to close this issue.

**Comment by deekoder** [comment]
Closing this issue @dennisbappert Please reopen if you want to discuss this further with us.
