### ISSUE TITLE
Usage protocol not enforced inside of mc

### ISSUE THREAD

**Issue by CarterMcClellan** [minio/mc#2191]
One issue inside of mc is that Usage listed inside of the help message is not enforced. 
For example, the command "make bucket" [mb], has the following Usage/ Syntax Protocol listed inside of the help text : mc mb [FLAGS] TARGET [TARGET...], but when provided with flags in what should be an invalid location the bucket will still actually be made acting as if the flag was placed correctly.

## Expected behavior
Should prompt error message "Operation not supported. Usage: mc mb [Flags] Target [Target]"

## Actual behavior
1) "Bucket created successfully 'myminio/test17' "

## Steps to reproduce the behavior
Connect to minio server, add host, make a bucket with incorrect syntax
1) mc mb myminio/test17 --region us-east-1

## mc version
Version: 2017-06-22T00:50:17Z
Release-tag: DEVELOPMENT.2017-06-22T00-50-17Z
Commit-id: c32b1ea48b651125e33015ea0d1596cb377685a4

## System information
 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,2
  Processor Name:	Intel Core i5
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	8 GB

**Comment by harshavardhana** [comment]
> Connect to minio server, add host, make a bucket with incorrect syntax
> 
> mc mb myminio/test17 --region us-east-1

How is this an incorrect syntax?

**Comment by CarterMcClellan** [comment]
When prompted with the help text for mb (by typing mb), usage indicates that flags can only be used optionally after mb, not after this.

**Comment by harshavardhana** [comment]
> When prompted with the help text for mb (by typing mb), usage indicates that flags can only be used optionally after mb, not after this.

Yes it is to indicate the default location of such flags -  the fact that it works in other places is a feature of the CLi package we use.  What we generally need is to state the fact that the command honors flags and it is provided as `[FLAGS]` in the help template. 

So i don't think so we need to do anything here.
