### ISSUE TITLE
Permit override of amazonaws.com url verification

### ISSUE THREAD

**Issue by StephanX** [minio/mc#2198]
Am new to minio, and successfully set it up on kubernetes using your helm chart.  An amazon elb is set up to front the service and works like a charm, but only if I use (one of) the IP addresses for the elb gateway.  If I configure the gateway directly in my configuration i.e. 
`	"hosts": {
		"my-minio": {
			"url": "http://xxxxx-xxxx.us-east-1.elb.amazonaws.com:9000",`
I receive: 

> tyr:> mc mb my-minio/myfancybucket
> mc: <ERROR> Invalid target my minio/myfancybucket. Amazon S3 endpoint should be 's3.amazonaws.com'.

ELB's are expected to occasionally change IPs, and I generally wouldn't need to assign a static dns name to an internal load balancer.  Validation of urls makes sense to a point, but shouldn't inhibit usage.  A --ignore-aws-url-checking type of flag would help.  Thanks!

## mc version
tyr:> mc version
Version: 2017-06-15T03:38:43Z
Release-tag: RELEASE.2017-06-15T03-38-43Z
Commit-id: 631f7fc194fe0ad8d26cb16ca264ca6665fcd151

**Comment by vadmeste** [comment]
I think we should not do the check at all because `xxxxx-xxxx.us-east-1.elb.amazonaws.com` already doesn't contain `s3.amazonaws.com`
