### ISSUE TITLE
Handling filesystem stat errors 

### ISSUE THREAD

**Issue by tareks** [minio/mc#2199]
Is there a way to not fail an entire mirror operation or simply skip errors, such as stat related ones? I'm attempting to mirror a relatively large directory structure with some potentially invalid symlinks. These seem to throw a stat error (i presume when trying to follow them) and the entire mirror operation fails. 

I'd like to skip any error'd files and mirror the rest if at all possible.

## Expected behaviour
Skip (or allow by option) errors with specific files during a mirror operation.

## Actual behaviour
Mirror operation fails with an error as follows:
mc: <ERROR> Unable to mirror objects. stat /mnt/test/file: bad message
 (1) difference.go:95 cmd.difference.func1(..) 
 (0) client-fs.go:929 cmd.(*fsClient).listRecursiveInRoutine(..)

## Steps to reproduce the behaviour
Attempt to mirror a directory structure with an invalid symbolic link or potentially a file without read access.

## mc version
Version: 2017-06-15T03:38:43Z
Release-tag: RELEASE.2017-06-15T03-38-43Z
Commit-id: c32b1ea48b651125e33015ea0d1596cb377685a4

## System information
CentOS Linux release 7.3.1611 (Core) 
3.10.0-514.26.1.el7.x86_64

**Comment by harshavardhana** [comment]
I just tested we do skip broken symlinks and permission denied. Are you sure this was the error ? Can you paste the entire error message ?

**Comment by tareks** [comment]
I encountered this when trying to mirror from a filesystem to a S3 bucket, but looks like it's more basic than that. I've just been able to reproduce on 2 local directories on the same filesystem. Perhaps i'm missing something?

Steps below:

>$ mkdir dir1 dir2
>$ cd dir1
>$ ln -s abc 123
>$ ./mc ls dir2
>mc: <ERROR> Unable to list broken link. Requested file `123` has broken symlink
>$ ./mc mirror dir1 dir2
> 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <ERROR> Unable to mirror objects. Requested file `dir1/123` has broken symlink
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃ 0s

With --debug:
>$ ./mc mirror dir1 dir2 --debug
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <ERROR> Unable to mirror objects. Requested file `dir1/123` has broken symlink
 (1) difference.go:95 cmd.difference.func1(..) Tags: [dir1/, dir2/]
 (0) client-fs.go:884 cmd.(*fsClient).listRecursiveInRoutine.func1(..)
 Release-Tag:RELEASE.2017-06-15T03-38-43Z | Commit:c32b1ea48b65 | Host:test | OS:linux | Arch:amd64 | Lang:go1.7.5 | Mem:1.3MB/3.9MB | Heap:1.3MB/2.7MB
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃ 0s

**Comment by harshavardhana** [comment]
I see the problem @tareks looks like the listing stops at broken link error. Looks like the issue is in streaming diff compare. 

Here are the steps to see if mirror happens following your steps. 

```
 ls
[2017-07-01 18:20:52 PDT]     0B 1
mc: <ERROR> Unable to list broken link. Requested file `123` has broken symlink
[2017-07-01 18:20:12 PDT]    26B issue
```

```
mc mirror dir1 dir2
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <ERROR> Unable to mirror objects. Requested file `dir1/123` has broken symlink
dir1/1:                    0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃ 0s
```

If you see 1 is mirrored where as `issue` is not mirrored. All lexically earlier are mirrored properly rather which come at the tail end. 

Let me check what is causing the issue we should be ignoring this error and proceeding to the next one.
