### ISSUE TITLE
Misleading help text & short description for mc config host 

### ISSUE THREAD

**Issue by badscooter23** [minio/mc#2202]
## Expected behavior
The mc config host -help command description is 

"mc config host - List, modify and remove hosts in configuration file."

This is misleading in the sense that "list" and "remove" are valid sub-commands for mc config host, but modify is not. The text does not mention "add" which is valid and the behavior of the "add" sub-command will modify an existing entry if it already exists. 

In additon, the mc confg host add command does not currently explain the requirement (or behavior) when the user specifies

mc config host add gcs https://storage.googleapis.com  <access key> <secret key>  S3v2 

This command has been changed to default the API signature to "S3v2" if the URL is "https://storage.googleapis.com" and to give an error if the user specifies S3v2. This should be explained in the help text - particularly given the API Signature should be verified when the config file is validated at mc startup time (and the wrong signature would generate an error once this is fixed). 

## Actual behavior
Current help text: 

NAME:
  mc config host - List, modify and remove hosts in configuration file.

USAGE:
  mc config host COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  add, a      Add a new host to configuration file.
  remove, rm  Remove a host from configuration file.
  list, ls    Lists hosts in configuration file.
  

## Steps to reproduce the behaviour

mc config host -help

## mc version
- (paste output of `mc version`)

Version: 2017-07-04T00:18:43Z
Release-tag: DEVELOPMENT.2017-07-04T00-18-43Z
Commit-id: 05f588fd195fe3e235a4951e0beee55e27eac189

## System information

any

**Comment by badscooter23** [comment]
Also need to improve the help text for mc config host add -help and improve the documentation in ddocs/minio-client-complete-guide.md. 

mc config host add should have an example for GCS (and mention the requirement for the API signature to be S3v2). 

There are a few places in the document where details can be clarified.

**Comment by harshavardhana** [comment]
> mc config host add should have an example for GCS (and mention the requirement for the API signature to be S3v2).

@badscooter23 GCS is only provided in a limited sense.. that is why it was never a priority to document it. With minio gateway gcs - direct access to GCS would not be necessary as well. 

In-fact i think we should even consider removing support for GCS from minio-go as well, it has added lot of legacy code which we don't need.

**Comment by badscooter23** [comment]
Obviously no need to fix the documentation issues related to GCS if it is going to be removed. 

The other "issue" is quite subtle and somewhat minor (and independent of the items related to GCS). The current text suggests that

mc config host modify ... 

would be valid when in fact the way a user 'modifies' a host configuration is to use

mc config host add ...

**Comment by harshavardhana** [comment]
> mc config host - List, modify and remove hosts in configuration file.

This text is more English than a direct representation of the sub-commands themselves.  

- Just like how `mc rm` says `Remove files and objects` it doesn't say `mc remove` 
- Just like how `mc share` says 'Generate URL for sharing` it doesn't say `mc generate-url`

**Comment by badscooter23** [comment]
It is possible to have a short description written in clear English that isn't misleading.

For example

mc config host add --help 

NAME:
  mc config host add - Add a new host to configuration file (or modify and existing entry).
...

mc config host --help 
NAME:
  mc config host - List, add or remove hosts in configuration file.

USAGE:
  mc config host COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  add, a      Add a new host to configuration file (or modify and existing entry).
  remove, rm  Remove a host from configuration file.
  list, ls    Lists hosts in configuration file.

Those are all in clear English and not misleading in anyway.

**Comment by deekoder** [comment]
needs to be discussed with @abperiasamy

**Comment by harshavardhana** [comment]
we will get to this at a future date, closing for now.
