### ISSUE TITLE
Need persistent versioned URL for current release that will not change over time

### ISSUE THREAD

**Issue by Yurmusp** [minio/mc#2205]
Need persistent versioned URL for current release that will not change over time.

Currently most recent version release is in one folder and it will be moved to another folder with next release.

Need versioned URL to current release which would not change with further releases.

I'm on linux-amd64

**Comment by Yurmusp** [comment]
Any progress here? Do we know when we expect it done?

**Comment by harshavardhana** [comment]
> Any progress here? Do we know when we expect it done?

This will be done soon. Will update it here @Yurmusp . For the time being use the work-around as mentioned earlier.

**Comment by ebozduman** [comment]
This will be taken care of when we release new `mc` version.
Closing it as "wontfix/invalid".
