### ISSUE TITLE
access key validation is too short for swift S3 emulation

### ISSUE THREAD

**Issue by jtratner** [minio/mc#2210]
The access key max length here ( https://github.com/minio/mc/blob/53cb92038aa33f117bd7f59e7b1d28bb8af6e5c4/cmd/config-utils.go#L25 )  doesn't work for Swift(Stack) clusters that use the access key to specify tenants.  Might make sense to expand it to a longer value.

## Expected behaviour
mc config host add AUTH_my_long_tenant_name https://some-swift-cluster.example.com "swft_user:AUTH_my_long_tenant_name" $API_KEY S3v2

should work
## Actual behaviour

errors about invalid config

## Steps to reproduce the behaviour

run the command

## mc version
- (paste output of `mc version`)
Version: DEVELOPMENT.GOGET
Release-tag: DEVELOPMENT.GOGET
Commit-id: DEVELOPMENT.GOGET

I manually edited the local to accept a longer access key and it successfully worked with a swiftstack cluster.

**Comment by harshavardhana** [comment]
> The access key max length here ( https://github.com/minio/mc/blob/53cb92038aa33f117bd7f59e7b1d28bb8af6e5c4/cmd/config-utils.go#L25 ) doesn't work for Swift(Stack) clusters that use the access key to specify tenants. Might make sense to expand it to a longer value.

what is the final length of the key expected @jtratner ?

**Comment by jtratner** [comment]
It looks like the default account name max length is 256, which means max length is ~518 characters. (`<name>:<4 char prefix>_<othername>`)

**Comment by deekoder** [comment]
yea I believe max length is 256 for s3 compatibility. I will check on this and get back to you.

**Comment by ebozduman** [comment]
This issue will be fixed when [PR4730](https://github.com/minio/minio/pull/4730) pushed in for [Issue#4717](https://github.com/minio/minio/issues/4717) is merged into master.
We can close this issue as fixed then.
