### ISSUE TITLE
mc "rm" command does not remove multipart uploads on Swift cluster via S3 API

### ISSUE THREAD

**Issue by whiteman999** [minio/mc#2214]
## Expected behaviour

When attempting to remove objects larger than a certain size (>70m) the objects are not being removed and no errors received.

A command similar to the below should remove the listed file:
`mc rm s3test/test1/testfile1`

When attempting this same procedure using s3cmd as the client, the object is removed successfully.

## Actual behaviour
When the object removal is attempted, it reports as successful but the object still shows in the list.

Remove Command:
`mc rm s3test/test1/testfile1`

Returns:
`Removing `s3test/test1/testfile1`.`

List bucket/ container contents shows the object has not been removed:
`mc ls s3test/test1`

[2017-07-13 14:21:38 BST]  67MiB testfile1

## Steps to reproduce the behaviour

As above - this is consistent for objects above 60MB in size.

Testing:

Objects testfile1 and testfile2 (~70MB in size) uploaded using mc client

mc ls s3test/test1
[2017-07-13 14:21:38 BST]  67MiB testfile1
[2017-07-13 14:23:15 BST]  67MiB testfile2

1. testfile1 attempted removal using minio mc client on Windows

```
mc rm s3test/test1/testfile1
Removing `s3test/test1/testfile1`.
```

- Object listing shows testfile1 not removed.
```
mc ls s3test/test1
[2017-07-13 14:21:38 BST]  67MiB testfile1
[2017-07-13 14:23:15 BST]  67MiB testfile2

```
2. testfile2 removal using s3cmd client:

```
# s3cmd del s3://test1/testfile2
delete: 's3://test1/testfile2'
```

- Object listing using minio mc client shows testfile2 has now been removed:

mc ls s3test/test1
[2017-07-13 14:21:38 BST]  67MiB testfile1

The corresponding logs from Swift storage server for both deletes may indicate the potential issue:

- mc client delete for testfile1

Jul 13 14:21:38 host1.test.com container-server[19136]: 192.168.1.181 - - [13/Jul/2017:13:21:38 +0000] "DELETE /d0/23404/AUTH_testuser1/test1%2Bsegments/testfile1/ZGRlODFhNjItYjgwYi00NDQxLTgyNjEtMzRjMWNiMDNhNGZl" 204 - "DELETE http://192.168.1.182/d5/14755/AUTH_testuser1/test1%2Bsegments/testfile1/ZGRlODFhNjItYjgwYi00NDQxLTgyNjEtMzRjMWNiMDNhNGZl" "tx2a659f949d4342ac9a019-00596773e2" "object-server 12652" 0.0009 "-" 19136 0
Jul 13 14:21:38 host1.test.com object-server[19211]: 192.168.1.179 - - [13/Jul/2017:13:21:38 +0000] "DELETE /d1/14755/AUTH_testuser1/test1%2Bsegments/testfile1/ZGRlODFhNjItYjgwYi00NDQxLTgyNjEtMzRjMWNiMDNhNGZl" 204 - "DELETE http://192.168.1.182/v1/AUTH_testuser1/test1%2Bsegments/testfile1/ZGRlODFhNjItYjgwYi00NDQxLTgyNjEtMzRjMWNiMDNhNGZl" "tx2a659f949d4342ac9a019-00596773e2" "proxy-server 15572" 0.0295 "-" 19211 0

- s3cmd delete for testfile2

JJul 13 14:28:37 host1.test.com container-server[19136]: 192.168.1.180 - - [13/Jul/2017:13:28:37 +0000] "DELETE /d0/23404/AUTH_testuser1/test1%2Bsegments/testfile2/ZDE2NmY1MTItYmFmYS00MWQxLWExZjItNDBlMTU2MDY5NzIz/2" 204 - "DELETE http://192.168.1.182/d0/60688/AUTH_testuser1/test1%2Bsegments/testfile2/ZDE2NmY1MTItYmFmYS00MWQxLWExZjItNDBlMTU2MDY5NzIz/2" "tx27a0412ecc5648ab8fe47-0059677585" "object-server 19208" 0.0008 "-" 19136 0
Jul 13 14:28:37 host1.test.com object-server[19208]: 192.168.1.178 - - [13/Jul/2017:13:28:37 +0000] "DELETE /d0/60688/AUTH_testuser1/test1%2Bsegments/testfile2/ZDE2NmY1MTItYmFmYS00MWQxLWExZjItNDBlMTU2MDY5NzIz/2" 204 - "DELETE http://192.168.1.182/v1/AUTH_testuser1/test1%2Bsegments/testfile2/ZDE2NmY1MTItYmFmYS00MWQxLWExZjItNDBlMTU2MDY5NzIz/2**?multipart-manifest=delete**" "tx27a0412ecc5648ab8fe47-0059677585" "proxy-server 18075" 0.0490 "-" 19208 0

**- The mc client delete does not seem to be passing the ?multipart-manifest=delete directive whereas the s3cmd client is.**

## mc version
Version: 2017-06-15T03:38:43Z
Release-tag: RELEASE.2017-06-15T03-38-43Z
Commit-id: c32b1ea48b651125e33015ea0d1596cb377685a4

## System information
The client is Windows 2012 R2 running the above mc client version

The Object Storage cluster is a Swift(Stack) cluster configured for S3 using S3v2 API signature.

Swift version is 2.9.0.2-4.el7

**Comment by vadmeste** [comment]
`?multipart-manifest=delete` is not defined in S3 spec.. but it looks it is no harm to add it in `mc`.

**Comment by krishnasrinivas** [comment]
@vadmeste just verified that s3cmd also does not add `multipart-manifest=delete` by itself, I grepped `multipart-manifest` in s3cmd source, could not find anything. So it is weird that Swift's S3 layer is adding `multipart-manifest=delete` for s3cmd and not minio. Something weird is going on.

**Comment by harshavardhana** [comment]
The problem is perhaps Swift S3 doesn't support abort multipart upload properly.

An abort multipart upload should have only `?delete` query parameters adding multipart-manifest means we are making odd changes to support Swift S3 API alone we should be avoiding that.

Currently mc rm -I works with AWS S3 this must be Swift server side issue.

**Comment by whiteman999** [comment]
Thank you for that analysis @harshavardhana.  We are progressing with additional testing and debugging and will feed back any further information when we can.

**Comment by whiteman999** [comment]
@harshavardhana, following our case raised with SwiftStack support, a Swift3 bug has been raised for this as below:

https://bugs.launchpad.net/swift3/+bug/1705409

It has been indicated that if mc utilised the general delete object API rather than the delete mulitple objects API then this should work.

Not sure if this option could be made available with a switch / parameter to allow this delete functionality from the mc client.

**Comment by harshavardhana** [comment]
@whiteman999  AWS S3 implements two types of API one is single object delete and multi-object when you want to delete objects in bulk. 

```
mc rm
``` 

On the other hand gravitates to use multi object delete API instead to delete objects in bulk.  Swift can implement multiple object delete API and it should work fine. 

Currently `mc rm` works with Minio and AWS S3 which both implement this API. 

> It has been indicated that if mc utilised the general delete object API rather than the delete mulitple objects API then this should work.

You meant the other way around  - `mc` uses multiple objects API as default.

**Comment by whiteman999** [comment]
@harshavardhana thanks for that response.

Yes, as per my response mc does utilise the multiple object API as default as you have indicated.

My question, was whether `mc rm`  could implement a switch or parameter that would allow the default behaviour to NOT use the multiple object API as default.

It is understood that this is to work around a bug in the Swift3 implementation so we will await for updates to address this bug and I will close this issue.

**Comment by harshavardhana** [comment]
> @harshavardhana thanks for that response.
> 
> Yes, as per my response mc does utilise the multiple object API as default as you have indicated.
> 
> My question, was whether mc rm could implement a switch or parameter that would allow the default behaviour to NOT use the multiple object API as default.
> 
> It is understood that this is to work around a bug in the Swift3 implementation so we will await for updates to address this bug and I will close this issue.

One way we could avoid this is by doing a single RemoveObject() just for one object and for multiple objects we would do `multi-object`.   Let us know if this work-around is acceptable then perhaps we can do it.??
