### ISSUE TITLE
Missing error message using 'rm' command for deleting a bucket

### ISSUE THREAD

**Issue by nesc58** [minio/mc#2223]
## Expected behaviour
Same behaviour as 'rm' on linux
`rm <not-empty-dir>`
`rm: '<not-empty-dir>' is a directory`

I think this would be fine.

## Actual behaviour
When remove a bucket/folder the following mesage will be written to the shell:
`mc rm minio/<dir>`
`Removing 'minio/<dir>'.`

Yes. I can delete it with `--recursive` (for the dangour way `--recursive --force`) but it would be fine to say 'Hey, I cannot delete a directory without the param --recursive'.
My first thought was: Yes, Deleted. (Open the minio browser) Heey. why is the bucket/folder not deleted?!

## Steps to reproduce the behaviour
Create a bucket
Add files
Try to delete with `mc rm`

## mc version
Version: 2017-06-15T03:38:43Z
Release-tag: RELEASE.2017-06-15T03-38-43Z
Commit-id: c32b1ea48b651125e33015ea0d1596cb377685a4

## System information
OS: Linux (CoreOS)

**Comment by balamurugana** [comment]
This expected behavior would lead to incompatible with Amazon S3 behavior i.e. Remove object does not return error unless there is permission error.

**Comment by nesc58** [comment]
I understand. I will solve this issue for mine in a simple script.
1. Remove,
2. Check if the object still exists
3. Remove with rm recursive force.

Or check first if this is a folder and contains objects e.g. With ls

Thanks for your help and information.
