### ISSUE TITLE
'mc ls' gives error with s3 endpoint other than s3.amazonaws.com

### ISSUE THREAD

**Issue by davidmaxwaterman** [minio/mc#2224]
## Expected behaviour
I expect it to list the buckets, and also to be able to list individual buckets

## Actual behaviour
I can list the buckets if I use s3.amazonaws.com, but not individual buckets.
If I specify the ireland endpoint in my host config, then I can't even list buckets.

Error:
```
mc: <ERROR> Unable to stat `ai`. Amazon S3 endpoint should be 's3.amazonaws.com'.
```

## Steps to reproduce the behaviour
1. `mc config host add ai https://s3-eu-west-1.amazonaws.com ...`
1. `mc ls ai`

## mc version
- (paste output of `mc version`)
```
Version: 2017-06-15T03:38:43Z
Release-tag: RELEASE.2017-06-15T03-38-43Z
Commit-id: c32b1ea48b651125e33015ea0d1596cb377685a4
```

## System information
WSL
`Linux DESKTOP-2RF28S0 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by deekoder** [comment]
will look at this @davidmaxwaterman

**Comment by poornas** [comment]
@davidmaxwaterman, we are working on a fix for this issue - will keep you posted. 
It would be helpful if you could paste the output of  mc --debug ls ai  .

**Comment by davidmaxwaterman** [comment]
```
10:31:59 ~$ mc --debug ls ai |& tee mc.out
mc: <ERROR> Unable to stat `ai`. Amazon S3 endpoint should be 's3.amazonaws.com'.
 (3) ls-main.go:102 cmd.checkListSyntax(..) Tags: [ai]
 (2) client-url.go:177 cmd.url2Stat(..) Tags: [ai]
 (1) common-methods.go:177 cmd.newClientFromAlias(..) Tags: [ai, https://s3-eu-west-1.amazonaws.com/]
 (0) client-s3.go:118 cmd.newFactory.func1(..)
 Release-Tag:RELEASE.2017-06-15T03-38-43Z | Commit:c32b1ea48b65 | Host:DESKTOP-2RF28S0 | OS:linux | Arch:amd64 | Lang:go1.7.5 | Mem:1.2MB/2.8MB | Heap:1.2MB/1.7MB
```

Somehow that seems too little info to be useful. Is that what you were after?

**Comment by poornas** [comment]
@davidmaxwaterman, thanks for the log info.

**Comment by davidmaxwaterman** [comment]
how do I get a fixed version?

**Comment by harshavardhana** [comment]
> how do I get a fixed version?

@davidmaxwaterman for now from source `go get -u github.com/minio/mc`  if not wait for the release which we will do this week.

**Comment by davidmaxwaterman** [comment]
`go` seems to require a whole new subsystem to be installed, so I'll give that a miss and wait for the release since it's not too long anyway. Thanks.
