### ISSUE TITLE
session: support for 'mc session resume all'

### ISSUE THREAD

**Issue by awwalker** [minio/mc#2226]
## Expected behaviour
For mc session commands to be consistent
## Actual behaviour
Currently mc session clear supports all as an option to remove all active sessions. In order to be consistent mc session resume should also support all as valid input to resume all active sessions.
## Steps to reproduce the behaviour
Run mc session resume all
## mc version
- (paste output of `mc version`)
All
## System information
All

**Comment by deekoder** [comment]
We discussed this and decided that resume all would be dangerous especially if sessions are very old and could result in unpredictable results (eg maybe a bucket is gone but a session 1 year did some operations on that bucket). It's acceptable to inspect them one by one and resume.

**Comment by ebozduman** [comment]
Closing...
