### ISSUE TITLE
permit more characters for relaxed bucket name validation

### ISSUE THREAD

**Issue by gtallan** [minio/mc#2229]
This is a follow-on to issue #2157.

I tried out the updated version of mc which is more accepting of non-compliant bucket names. The changes are much appreciated, but I would like to ask you to consider two more exceptions.

1) underscore (_) should be accepted in an existing bucket name - it's accepted by AWS US-East and ceph radosgw, and is sadly the most popular "non-compliant" character chosen by my user base!

2) Perhaps colon (:) could also be accepted. I'm not sure how this relates to AWS, but in ceph radosgw it can be used to refer to a bucket with an explicit tenant
see (http://docs.ceph.com/docs/master/radosgw/multitenancy/#accessing-buckets-with-explicit-tenants)

Thanks!

## Expected behaviour

mc ls gta/Test_bucket
...
list of bucket contents
...

## Actual behaviour
mc ls gta/Test_bucket
mc: <ERROR> Unable to stat 'gta/Test_bucket'. Bucket name contains invalid characters

## mc version
DEVELOPMENT.2017-07-20T18-35-28Z

**Comment by deekoder** [comment]
@gtallan will discuss this ask and get back to you.

**Comment by harshavardhana** [comment]
> underscore (_) should be accepted in an existing bucket name - it's accepted by AWS US-East and ceph radosgw, and is sadly the most popular "non-compliant" character chosen by my user base!
> 

This is perhaps expected and we can allow.  Requires changes in minio-go will send a fix. Sorry for the delay @gtallan

**Comment by harshavardhana** [comment]
A PR is sent once merged, we will bump up the release of minio-go and vendorize with `mc`.  -https://github.com/minio/minio-go/pull/778

**Comment by harshavardhana** [comment]
This is not blocked anymore @deekoder we can remove blocked label?
