### ISSUE TITLE
mc access OVH Openstack container?

### ISSUE THREAD

**Issue by ktwalrus** [minio/mc#2232]
I'm trying to access my Openstack container hosted at OVH in their Public Cloud. OVH runs Openstack Swift with Identify v2. I haven't been successful in even connecting to it with mc.

mc gives the following error:

```
mc: <ERROR> URL https://auth.cloud.ovh.net/v2.0 for host https://auth.cloud.ovh.net/v2.0 is not valid. Could not parse it.
```
The endpoints available to me are:
![ovh-endpoints](https://user-images.githubusercontent.com/1620132/28787620-eb7f1374-75ea-11e7-84a6-886b6b4640a6.png)

I haven't been able to figure out the aws_access_key or aws_secret_key either, because mc doesn't parse any of the endpoints I have.

Maybe host URL parsing has a bug?

I have submitted a support ticket with OVH to see if they really support S3 compatible API like this Openstack page suggests they should:

https://docs.openstack.org/kilo/config-reference/content/configuring-openstack-object-storage-with-s3_api.html

**Comment by ktwalrus** [comment]
OVH hasn't responded to my support ticket yet, but I did find this:

http://travaux.ovh.com/?do=details&id=17136&PHPSESSID=5dff607dc1f470aa97343a69af7d11d4

which suggests they removed S3 API support last year.

Still, mc shouldn't be giving me a URL parsing error, should it?

**Comment by harshavardhana** [comment]
It is not a wrong URL in a generic manner but with in the context of mc it is not a correct URL . mc requires user to provide endpoint with no resource component.

We will improve the error message to indicate the type of endpoints expected.

In a larger sense If OVH doesn't support S3 API then mc won't work anyways.

**Comment by harshavardhana** [comment]
I see that we report an error when adding ovh like URLs

```
$ mc config host add ovh https://auth.cloud.ovh.net/v2.0 minio minio123
mc: <ERROR> Invalid URL `https://auth.cloud.ovh.net/v2.0`. 
```

Did you edit the `config.json` directly? @ktwalrus

**Comment by ktwalrus** [comment]
@harshavardhana - yes, I edited the `config.json` directly. It was just easier to clone the gce config for OVH. 

I suppose it is a restriction that the AWS S3 API imposes on minio/mc. That is, all S3 endpoints are composed of only the scheme, host, and port (with no path part). If this is the real reason for the restriction, it would have been helpful if the parse error simply included that AWS S3 endpoints cannot contain a path (or query string) to be valid.

Of course, maybe I'm the first or only user to try to use an OpenStack API endpoint as an AWS S3 API endpoint. So, maybe this issue doesn't really need to be addressed. You could add a section or note to the documentation explaining the difference between an AWS S3 API endpoint and a full URL (like the OpenStack API endpoints). I read all the documentation before trying out Minio and if there was such a note embedded somewhere, I missed it.
