### ISSUE TITLE
mc admin credentials fails with "cannot get a configured admin connection"

### ISSUE THREAD

**Issue by krisis** [minio/mc#2237]
## Expected behaviour
Should set supplied credentials on Minio server

## Actual behaviour
`mc admin credentials TARGET ACCESS_KEY SECRET_KEY` fails with

`mc: <ERROR> Cannot get a configured admin connection. The specified alias: 123 not found`

## Steps to reproduce the behaviour
1. `mc admin credentials TARGET access_key secret_key`

## mc version
- (paste output of `mc version`)
commit id `ca96cfc`

**Comment by krisis** [comment]
This is a simple issue and needs to be fixed immediately. @deekoder @harshavardhana I could take this up in the interest of time to fix.

**Comment by vadmeste** [comment]
Looks like the help isn't updated
