### ISSUE TITLE
mc quiet flag not working

### ISSUE THREAD

**Issue by rosario-raulin** [minio/mc#2240]
## Expected behaviour

When using the global `--quiet/-q` flag, mc should not print progress to stdout.

## Actual behaviour

Progress is still written to stdout, even if `--quiet` is set.

## Steps to reproduce the behaviour

1. Run `mc -q mirror some/local/path some-dest`
2. Still see output to stdout.

## mc version

Version: 2017-06-15T03:38:43Z
Release-tag: RELEASE.2017-06-15T03-38-43Z
Commit-id: c32b1ea48b651125e33015ea0d1596cb377685a4

## System information

macOS Sierra (10.12.6)

**Comment by harshavardhana** [comment]
This is expected behavior of quiet. Quiet only turns off progress bar. If you don't want anything to be printed just redirect stdout to /dev/null instead.

**Comment by rosario-raulin** [comment]
Okay, then you should at least improve the documentation on that. The current description `suppress chatty console output.` isn't clear enough, IMHO.
