### ISSUE TITLE
mc rm not erroring out when deleting directory

### ISSUE THREAD

**Issue by donatello** [minio/mc#2242]
## Expected behaviour

`mc rm` should exit with an error message when attempting to delete a non-empty directory inside object storage (when no flags are given). 

## Actual behaviour

See steps below:

```
$ mc mb play/testbucket1
Bucket created successfully `play/testbucket1`.
$ mc cp Dockerfile appveyor.yml play/testbucket1/folder1/folder2/
appveyor.yml:                  2.54 KB / 2.54 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 5.07 KB/s 0s
$ mc ls -r play/testbucket1/
[2017-08-24 16:29:49 IST]   779B folder1/folder2/Dockerfile
[2017-08-24 16:29:49 IST] 1.8KiB folder1/folder2/appveyor.yml
$ mc rm play/testbucket1/folder1
Removing `play/testbucket1/folder1`.
$ mc ls -r play/testbucket1/
[2017-08-24 16:29:49 IST]   779B folder1/folder2/Dockerfile
[2017-08-24 16:29:49 IST] 1.8KiB folder1/folder2/appveyor.yml
```

## Steps to reproduce the behaviour
See previous sectoin.

Originally raised by a user here - https://github.com/minio/minio/issues/4852

**Comment by balamurugana** [comment]
RemoveObject REST api doesn't return error other than permission denied.  Could you tell what error message you are expecting?

**Comment by donatello** [comment]
> RemoveObject REST api doesn't return error other than permission denied.

This is unfortunate. From a usability perspective it is a bit misleading, especially if the last component is not known to be a object or a directory.

Perhaps the multi-delete API https://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html could be used - it can be set to return explicit acknowledgements for each object being deleted. This way client could get to know and the print an appropriate message.

**Comment by balamurugana** [comment]
We use (the same api)[https://github.com/minio/mc/blob/master/cmd/rm-main.go#L137] for removing single object too. :smile:

**Comment by harshavardhana** [comment]
Is this still a problem? @donatello - `mc rm` is being enhanced to do more https://github.com/minio/mc/pull/2265 - perhaps fixing this issue as well.
