### ISSUE TITLE
Wrong status message when doing `mc admin info minio --json`

### ISSUE THREAD

**Issue by davidgeorgealex** [minio/mc#2280]
## Expected behaviour
Minio in distributed mode - when running `mc admin info minio --json` and one node is down, the `status` should not be `success` for that one.

## Actual behaviour
Even if I have `error` field populated, the `status` is still success (the output is for a 3-node cluster):
{"status":"success","service":true,"address":"minio2:9000","error":"","storage":{"total":167720767488,"free":132576399360,"backend":{"backendType":"Erasure","onlineDisks":6,"offlineDisks":0}},"network":{"transferred":94864,"received":56830},"server":{"uptime":573347137993,"version":"2017-10-10T08:49:44Z","commitID":"60cc6184d253efee4a3120683517028342229e21","region":"","sqsARN":null}}
{"status":"success","service":true,"address":"minio0:9000","error":"dial-http minio0:9000/minio/admin: dial tcp: lookup minio0 on 127.0.0.11:53: server misbehaving"}
{"status":"success","service":true,"address":"minio1:9000","error":"","storage":{"total":167720767488,"free":132576399360,"backend":{"backendType":"Erasure","onlineDisks":6,"offlineDisks":0}},"network":{"transferred":783631,"received":355252},"server":{"uptime":8682093371814,"version":"2017-10-10T08:49:44Z","commitID":"60cc6184d253efee4a3120683517028342229e21","region":"","sqsARN":null}}

## Steps to reproduce the behaviour
1. Using docker-compose, declare 3 minio instances
2. Bring up the cluster (using docker-compose up)
3. Stop a docker container
4. Do a `mc admin info minio --json` and check the output.
## mc version
Version: 2017-10-10T08:50:07Z
Release-tag: DEVELOPMENT.2017-10-10T08-50-07Z
Commit-id: c10b429dcbeb7071e2758233afeda46d2ed688e5

**Comment by krisis** [comment]
@davidgeorgealex Thanks for reporting the issue. There is a bug in the json message construction code of `admin-info` and `admin-status`. I have sent a PR for this - https://github.com/minio/mc/pull/2293.

**Comment by krisis** [comment]
After some discussions around what `Service` field values should be in `mc admin service status` output, we have decided that `Service` will be one of `"on"` or `"off"`. I will be updating the PR to reflect this.
