### ISSUE TITLE
access key validation error

### ISSUE THREAD

**Issue by walterdejong** [minio/mc#2298]
## Expected behaviour
I expected a valid access key to be recognized as such.

## Actual behaviour
```
mc: <ERROR> Invalid access key `myuser@mys3server.domain.com`. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.
```

## Steps to reproduce the behaviour
```
./mc config host add myminio http://127.0.0.1:9000 myuser@mys3server.domain.com xxxxxxxxxxx
```

## mc version
- (paste output of `mc version`)
```
Version: 2017-10-27T08:29:05Z
Release-tag: DEVELOPMENT.2017-10-27T08-29-05Z
Commit-id: 79a51e9afcb71231ae2882c7ccbe1ddf3eede623
```

## System information
```
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4
```

## Detailed description
`minio/mc/cmd/config-utils.go` has this code:

```
const (
    accessKeyMinLen = 5
    accessKeyMaxLen = 20
    secretKeyMinLen = 8
    secretKeyMaxLen = 100
)

// isValidAccessKey - validate access key for right length.
func isValidAccessKey(accessKey string) bool {
    if accessKey == "" {
        return true
    }
    return len(accessKey) >= accessKeyMinLen && len(accessKey) <= accessKeyMaxLen
}
```
So based on this the key is invalid because it is too long.
However, the `minio` server has a different way of checking the access key:
```
{{{
const (
    // Minimum length for Minio access key.
    accessKeyMinLen = 5

    // Maximum length for Minio access key.
    // There is no max length enforcement for access keys
    accessKeyMaxLen = 20

    ...
)

// isAccessKeyValid - validate access key for right length.
func isAccessKeyValid(accessKey string) bool {
    return len(accessKey) >= accessKeyMinLen
}
```
According to the `minio` server, the key is valid because it is longer than 5 characters.

This does not seem to be compatible with Amazon S3 at all.
Amazon S3 documentation says:
* Length Constraints: Minimum length of 1. Maximum length of 128.
* regex pattern: `[\w+=,.@-]+`
See http://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateAccessKey.html

**Comment by harshavardhana** [comment]
> Length Constraints: Minimum length of 1. Maximum length of 128.
> regex pattern: [\w+=,.@-]+
> See http://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateAccessKey.html

Slight correction needed AccessKey is not mentioned to have `@` character instead its for Username there is no such concept on Minio server. 

Instead you should read here http://docs.aws.amazon.com/IAM/latest/APIReference/API_AccessKey.html
```
AccessKeyId
The ID for this access key.

Type: String

Length Constraints: Minimum length of 16. Maximum length of 128.

Pattern: [\w]+

Required: Yes
```

So what you are specifying as part of `accessKey` is incompatible anyways.  So you should fix it appropriately. 

> According to the minio server, the key is valid because it is longer than 5 characters.

mc keys are lenient in terms to handle minio servers requirement, i.e minio server which supports multiple different gateway modes which leverages each backend and their accountID/accessKey. The scope of `mc` is larger than restricting itself to AWS S3 restrictions alone.

**Comment by walterdejong** [comment]
I see, thanks for the link to the correct documentation.

**Comment by shoehn** [comment]
Will this be documented somewhere? It took me quite a while to find out that minio-client gives an invalid access key error, if the access key is longer than 20 bytes. Such a key perfectly works on my minio server.

**Comment by harshavardhana** [comment]
> Will this be documented somewhere? It took me quite a while to find out that minio-client gives an invalid access key error, if the access key is longer than 20 bytes. Such a key perfectly works on my minio server.

This is a bug in minio client @shoehn we don't need to do an upper bound.

**Comment by eode** [comment]
..just ran into this.  MC client won't let me log in with four-character username, but logging in directly via the server is fine.

**Comment by harshavardhana** [comment]
> ..just ran into this. MC client won't let me log in with four-character username, but logging in directly via the server is fine.

Yep looks like a bug in `mc` fixed here https://github.com/minio/mc/pull/2579
