### ISSUE TITLE
NoSuchUpload error when copying large file to S3

### ISSUE THREAD

**Issue by jwadolowski** [minio/mc#2301]
## Expected behaviour

`mc` should handle S3 errors gracefully.

This may be related to #2245 

## Actual behaviour

* exactly the same script uploads daily backups to S3 using `mc cp` command
* all was working fine until today's morning (the only notable change was increased size of `.tar.gz` file - was ~132,7 GB yesterday, but today's backup is around ~179 GB) 
* `mc cp /opt/cms/backups/author/2017-11-07-1510045201-xyz-prod-a1-cms-author.tar.gz s3/xyz-prod-daily-backups/2017/11/07/2017-11-07-1510045201-xyz-prod-a1-cms-author.tar.gz` produced the following output:

```
{
    "size": 191839031401,
    "source": "/opt/cms/backups/author/2017-11-07-1510045201-xyz-prod-a1-cms-author.tar.gz",
    "status": "success",
    "target": "s3/xyz-prod-daily-backups/2017/11/07/2017-11-07-1510045201-xyz-prod-a1-cms-author.tar.gz",
    "totalCount": 1,
    "totalSize": 191839031401
}
{
    "error": {
        "cause": {
            "error": {
                "BucketName": "",
                "Code": "NoSuchUpload",
                "HostID": "Fpn5HyNk0e5oQfVEmIUoWTFkKYZhQZkMlYYfzEKmqYdmb9NtpvjdFKhJZcB66dswBMUoWMr0+8I=",
                "Key": "",
                "Message": "The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.",
                "Region": "",
                "RequestID": "F8A23202F96336B0"
            },
            "message": "The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed."
        },
        "message": "Failed to copy `/opt/cms/backups/author/2017-11-07-1510045201-xyz-prod-a1-cms-author.tar.gz`.",
        "sysinfo": {
            "host.arch": "amd64",
            "host.cpus": "8",
            "host.lang": "go1.9.1",
            "host.name": "xyz-prod-a1.example.org",
            "host.os": "linux",
            "mem.heap.total": "9.2MB",
            "mem.heap.used": "4.6MB",
            "mem.total": "15MB",
            "mem.used": "4.6MB"
        },
        "type": "error"
    },
    "status": "error"
}
```

## Steps to reproduce the behaviour

* upload large `.tar.gz` file (~179 GB in my case) to S3 using `mc cp /opt/cms/backups/author/2017-11-07-1510045201-xyz-prod-a1-cms-author.tar.gz s3/xyz-prod-daily-backups/2017/11/07/2017-11-07-1510045201-xyz-prod-a1-cms-author.tar.gz` command

## mc version

```
$ mc version
Version: 2017-10-14T00:51:16Z
Release-tag: RELEASE.2017-10-14T00-51-16Z
Commit-id: 785e14a725357b39e22b74483cd202e7effa6195
```

## System information

* RedHat 7.4 x64

**Comment by jwadolowski** [comment]
Reupload of the same file, using exactly the same `mc` command just finished successfully.

**Comment by harshavardhana** [comment]
There is no real graceful way to handle this if server returned NoSuchUpload in middle of data transfer. It means there was sort of a bug on AWS S3, once multipart operation has started an uploadid cannot return NoSuchUpload. In-fact on AWS S3 even a completed multipart upload Id is still valid until few hrs .. 

So what happened here is highly unusual.

**Comment by jwadolowski** [comment]
Thanks for your prompt reply @harshavardhana! 

What would be the best way to handle such case then? Pick that error up in a wrapper script and simply resume a session?

**Comment by krishnasrinivas** [comment]
> What would be the best way to handle such case then? Pick that error up in a wrapper script and simply resume a session?

Yes.

**Comment by krishnasrinivas** [comment]
@jwadolowski can you close this issue then? you can re-open it if you are getting NoSuchUpload too frequently which warrants us to see if we should handle this inside `mc` itself.

**Comment by jwadolowski** [comment]
Sure thing. Will let you know if that becomes a major issue for us.

Thanks!
