### ISSUE TITLE
Use mc from another project

### ISSUE THREAD

**Issue by karabill** [minio/mc#2307]
## Expected behaviour

Be able to call functions of minio/mc from other projects or packages. 

This is not a bug report, but rather than a request for a feature.
We would like to reuse some parts of minio/mc source code in another go project. However, most of the functions and structs are private, so they can not be used.
So, what I would like to ask is if some parts of the code could made public. We are willing to provide the corresponding PR, if there is a possibility to be accepted.

## Actual behaviour

Most functions are private, so other projects can not use them.

## Steps to reproduce the behaviour

```
go get -d github.com/minio/mc

mkdir $GOPATH/src/tmp

cd $GOPATH/src/tmp

govendor init

govendor add github.com/minio/mc/^

cat > main.go << EOF
package main

import (
  "github.com/minio/mc/cmd"
)

func main() {
  // This does not compile
  cmd.fsNew("/")
}
EOF

go run main.go
```

The above does not compile. If I rename `fsNew` to `FsNew` or add another file in minio/mc folder, which defines another function `FsNew` which calls `fsNew`, it compiles.

## mc version
Not applicable

## System information
Not applicable

**Comment by harshavardhana** [comment]
This is out of scope for mc, mc is a client tool and it is not meant to be used like a library.   Feel free to fork and make changes yourself.

**Comment by karabill** [comment]
Thanks for the reply. Then, I assume you can close this issue.
