### ISSUE TITLE
feature request : Sending to aws s3 with metadata

### ISSUE THREAD

**Issue by frallain** [minio/mc#2308]
I'd like to send metadata like `aws s3 cp --metadata profile_id=3765   filename   s3://bucket/`, is it possible with `mc` currently ? If not, do you plan to integrate this feature? 
Cheers and thanks for `mc`

**Comment by kannappanr** [comment]
@frallain We currently do not support this feature.

**Comment by kannappanr** [comment]
@frallain We discussed adding this feature. The problem is that `cp` command can be used on a single file and also a directory. Setting same metadata for all the files in a directory is not a desired feature. Do you have any suggestion for handling this issue?

**Comment by kannappanr** [comment]
@frallain are you still interested in this feature. If yes, can you suggest a way to handle this issue.

**Comment by kannappanr** [comment]
Closing this issue now. Please open a new issue if you have any further questions.
