### ISSUE TITLE
Mirror Metadata for Existing Objects

### ISSUE THREAD

**Issue by JustinPullen** [minio/mc#2311]
## Expected behaviour
Because of #2196 (slow mirroring/copy) I am forced to look for a work around to speed up my mirroring of my remote s3 buckets.

I have used the AWS cli to sync all my files down to the minio data/bucketname directory. I then attempted to resolve my meta data mapping by running mirror to go and collect all the data for the objects that exist on the local file system. 

I assumed it would do 3 things.  
1. Check if the files stored locally were up to date with s3.
2. Check to see if there was a proper mapping for the object under .minio.sys/buckets/bucketname/.... when comparing the objects against s3
3. If no/incorrect mapping was found generate/update it.

## Actual behaviour
The cli appears to check if the file is present and if it is the cli just moves on without checking/creating or repairing the metadata mapping.

This leaves the mirroring process in an a middle of the road situation where it is not actually truly mirroring s3 just copying files and only when it is done by the minio cli will any metadata be mirrored.

## Steps to reproduce the behaviour

aws sync s3://bucket /Path/to/minio/data/bucket
mc mirror s3/bucket local/bucket

Check if metadata was created or updated.

## mc version
- (paste output of `mc version`)
Version: 2017-10-14T00:51:16Z
Release-tag: RELEASE.2017-10-14T00-51-16Z
Commit-id: 785e14a725357b39e22b74483cd202e7effa6195

## System information
Mac OSX Sierra
MacBook Pro (Retina, Mid 2012)
2.6 GHz Intel Core i7
8 GB 1600 MHz DDR3

**Comment by poornas** [comment]
@JustinPullen,  your approach will not work for  a couple of reasons – mc mirror just does a listing compare between source and target and not a metadata compare. Metadata is not returned by the list operation, and will need an additional 2x overhead to do a HEAD operation for each object in the bucket against source and target for metadata mirroring. The ideal solution would be to make mc cp/mirror performant –  we already have  PR # https://github.com/minio/mc/pull/2289 that aims to bring in parallelism on cp/mirror operations and should result in performance improvements.

**Comment by poornas** [comment]
@JustinPullen, you might want to download the latest mc binary and see if it mitigates your issues with mirror/copy performance.The PR mentioned above is part of this [release](https://github.com/minio/mc/releases).
