### ISSUE TITLE
mc timeout  

### ISSUE THREAD

**Issue by limbo127** [minio/mc#2312]
Hello, 
We are trying to use mc to cp data to s3.
We are using a lot of connection site in our country, and with some of them, it is impossible to put file, 
timeout error .

 mc: <ERROR> Failed to copy `/data/test_wisper`. Put http://xxxx-eu-west-1.amazonaws.com/medias/testt..4?partNumber=2&uploadId=vdO4XKbuT6Rg7.bQphbfRiSOzH5LUu.OjcqF616gknCJ1OfpSeCj9nBucM4uY4nxgyB52yNg8rILQZwRZV7prrrsno7sUSn_oGPofRohW1dfIspPhKfCNrQdAK49XNoI: net/http: HTTP/1.x transport connection broken: write tcp [fd00::baae:edff:feea:2f3c]:45212->[fd00::841:c2ff:fe4f:85f]:8888: write: connection reset by peer

Version: 2017-10-14T00:51:16Z
Release-tag: RELEASE.2017-10-14T00-51-16Z
Commit-id: 785e14a725357b39e22b74483cd202e7effa6195

With s3cmd, we have also the same issue, correct by : 
socket_timeout  in s3cmd configuration, 
how can we do that with minio mc ?

Regards, 
Nicolas

**Comment by vadmeste** [comment]
@limbo127, the error log that you pasted doesn't indicate this is a timeout.. `Connection reset by peer` looks like to be another problem.

Anyway, I will use Linux traffic shaper (tc) to simulate a really slow upload to AWS S3 and test low bandwidth condition with mc. I will update you.

Sorry for the delay by the way.

**Comment by limbo127** [comment]
hello,
it's seems to be a go library transport problem.
with software as https://github.com/kahing/goofys , the same issues as
minio/mc.
No problem with s3cmd ( python )
Regards,
nicolas

2017-12-11 12:30 GMT+01:00 A. Elleuch <notifications@github.com>:

**Comment by vadmeste** [comment]
@limbo127, I tested mc with a low bandwidtch config (5 kbytes/sec) it didn't generate any error after two hours.

@limbo127, what value did you set to your socket_timeout option ?

Currently, mc is configured with connect and keepalive timeout, both set to 30 seconds. We will probably increase it to higher value to reduce timeout problem.

**Comment by limbo127** [comment]
modify timeout does not resolv this issue, for me.
as I said, it seems a go problem.
regards
nicolas

**Comment by vadmeste** [comment]
> With s3cmd, we have also the same issue, correct by :
> socket_timeout in s3cmd configuration,

@limbo127 you said s3cmd works only by setting socket_timeout, are you still confirming this ? if yes, can you tell what is the value that you are using right now ?

**Comment by limbo127** [comment]
in s3cfg
socket_timeout=1800
when i'm trying to change timeout in minio package, 

is it possible to be a similar issue describe here : 
https://github.com/kahing/goofys/commit/6b55674433a801daef71168405f1625455aa361b

**Comment by harshavardhana** [comment]
> is it possible to be a similar issue describe here :
> kahing/goofys@6b55674

We already have these configured correctly @limbo127 

```go
    var transport http.RoundTripper = &http.Transport{
                                Proxy: http.ProxyFromEnvironment,
                                DialContext: (&net.Dialer{
                                        Timeout:   30 * time.Second,
                                        KeepAlive: 30 * time.Second,
                                }).DialContext,
                                MaxIdleConns:          100,
                                IdleConnTimeout:       90 * time.Second,
                                TLSHandshakeTimeout:   10 * time.Second,
                                ExpectContinueTimeout: 1 * time.Second,
                                TLSClientConfig:       tlsConfig,
                                // Set this value so that the underlying transport round-tripper
                                // doesn't try to auto decode the body of objects with
                                // content-encoding set to `gzip`.
                                //
                                // Refer:
                                //    https://golang.org/src/net/http/transport.go?h=roundTrip#L1843
                                DisableCompression: true,
                        }
```

**Comment by vadmeste** [comment]
@limbo127 I am not sure if I understood correctly, did you try to modify mc code and set timeout and keep-alive to 1800 seconds ?

**Comment by limbo127** [comment]
Yes without success

Le ven. 16 févr. 2018 à 11:56, A. Elleuch <notifications@github.com> a
écrit :

**Comment by deekoder** [comment]
Unable to reproduce this issue.  Please reactivate if you are still seeing this with the latest mc.
