### ISSUE TITLE
mc no http header, no forwarding by domain name,

### ISSUE THREAD

**Issue by xilu0** [minio/mc#2316]
## Steps to reproduce the behaviour
hi,  Minio is a very good software, mc no http header, no forwarding by domain name, Is there a way?

## mc version
- (Version: 2017-10-14T00:51:16Z
Release-tag: RELEASE.2017-10-14T00-51-16Z
Commit-id: 785e14a725357b39e22b74483cd202e7effa6195`)

**Comment by harshavardhana** [comment]
Can you describe more what is the requirement here ?

**Comment by deekoder** [comment]
@xilu0  please let us know more.

**Comment by harshavardhana** [comment]
Closing as we do not have enough information to proceed. @xilu0 - feel free to re-open.
