### ISSUE TITLE
Mirror command with --watch doesn't honor --exclude option

### ISSUE THREAD

**Issue by Vesnica** [minio/mc#2319]
## Expected behaviour
mirror command with --watch should honor --exclude option

## Actual behaviour
mirror command with --watch doesn't honor --exclude option

## Steps to reproduce the behaviour
1. Create 2 minio instance on different node, and make a test bucket on both instance
2. Config the mc host, let's say local and target
3. ./mc mirror --force --remove --watch --exclude ".*" --exclude "\*.temp" local/test target/test
4. Create another shell, execute: ./mc cp test.temp local/test
5. You can see mirror command sync the test.temp to target incorrectly
6. ./mc ls target/test/ can see the test.temp file

## mc version
Version: 2017-10-14T00:51:16Z
Release-tag: RELEASE.2017-10-14T00-51-16Z
Commit-id: 785e14a725357b39e22b74483cd202e7effa6195

## System information
Ubuntu 16.04

**Comment by harshavardhana** [comment]
Thanks @Vesnica looks like its reproducible on our end as well. We will take a look.

**Comment by harshavardhana** [comment]
> is --exclude option works for folder? cause when we upload an docker image, there will be a lot of temp files, MC tool always crash when mirror these temp files.
> 
> panic info as following:
> **panic: runtime error: comparing uncomparable type minio.ErrorResponse
> 
> goroutine 28 [running]:
> net/http.(*Request).write(0xc420634700, 0xb68940, 0xc4203ee3c0, 0x0, 0x0, 0x0, 0xb6a9c0, 0xc42076a960)
> /home/builder/.gimme/versions/go1.9.1.linux.amd64/src/net/http/request.go:620 +0x757
> net/http.(persistConn).writeLoop(0xc4204ab200)
> /home/builder/.gimme/versions/go1.9.1.linux.amd64/src/net/http/transport.go:1762 +0x201
> created by net/http.(Transport).dialConn

This looks like a bug in our code @zlypwonderful
