### ISSUE TITLE
Question, how do I copy in place?

### ISSUE THREAD

**Issue by andrewsav-datacom** [minio/mc#2321]
When I run

```
mc cp server/bucket/file server/bucket/file-old
```

I expect the file to be copied. But in fact I'm getting:

```
mc.EXE: <ERROR> Failed to copy `https://server/bucket/file`. Insufficient permissions to access this file `https://server/bucket/file-old`
```

What am I doing wrong?

**Comment by harshavardhana** [comment]
You might have a prefix which already exists on destination as directory.

**Comment by harshavardhana** [comment]
For example this works fine

```
$ mc cp play/testbucket/issue play/testbucket/issue-old
...o.io:9000/testbucket/issue:  20 B / 20 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 386 B/s 0s
```

There are 3 situations where the error might happen

- The destination already exists as `issue-old` and is a directory, if the PutObject is issued on this prefix server would reject such an operation with `Access Denied` 
- The source is a directory i.e `issue`, if a GetObject is issued on this prefix then server would return "Access Denied"
- Unless you have a backend problem i.e you cannot write to the destination you do not have ample permissions to write.

PS: It would be beneficial if we follow issue template describing the problem, i.e steps to reproduce with `mc` 

- with `--debug` output. 
- with `mc version` output. 
- operating system details

Helps narrow down the issue quickly.

**Comment by AndrewSav** [comment]
Sorry, my bad. Again mysteriously I had ancient version of mc.exe, although I could swear I updated recently.  No issues with the latest version of mc.exe.
