### ISSUE TITLE
"mc config host add" does not accept access key longer than 20 chars

### ISSUE THREAD

**Issue by Sovetnikov** [minio/mc#2328]
I see that this issue was fixed on 26 Nov https://github.com/minio/mc/issues/2298 but mc binary for linux-amd64 at download page is still not updated.

Binary at https://dl.minio.io/client/mc/release/linux-amd64/mc is Version: 2017-10-14T00:51:16Z

When it will be updated?

**Comment by harshavardhana** [comment]
We will be making a release soon.
