### ISSUE TITLE
add convenience flag '-i' for case-insensitive matching

### ISSUE THREAD

**Issue by peterquirk** [minio/mc#2332]
## Expected behaviour
mc find local/bucket1 -i --name "*.jpg"     finds all files with .jpg or .JPG suffix
## Actual behaviour
you have to issue mc find local/bucket1 --regex "(?i)\.(jpg|JPG)"
## mc version
- (paste output of `mc version`)

**Comment by deekoder** [comment]
We will have a discussion about adding this and let you know.

**Comment by deekoder** [comment]
We currently dont have the cycles to take this on. If someone is interested in the community, this is a great item for them to take on. Would love to support them get this for the community if they really want this feature. Closing this for now and will reopen if someone is able to work on it.
