### ISSUE TITLE
Support for Virtual Host Addressing with S3 compatible storage services

### ISSUE THREAD

**Issue by Sovetnikov** [minio/mc#2335]
## mc version
- (paste output of `mc version`)
Version: 2017-12-12T01:08:02Z
Release-tag: RELEASE.2017-12-12T01-08-02Z
Commit-id: 4cb6e3534286819d3e11db7c3659164655020bd3

I need to transfer files between minio server and some commercial S3 compatible storage service that supports only virtual host addressing, but i can't find how to force mc into virtual host addressing mode for my target service hostname.
Just see that virtual host addressing is turned on based on hard coded hostnames.

Can i turn it on with some command args switch?

**Comment by harshavardhana** [comment]
> I need to transfer files between minio server and some commercial S3 compatible storage service that supports only virtual host addressing, but i can't find how to force mc into virtual host addressing mode for my target service hostname.
> Just see that virtual host addressing is turned on based on hard coded hostnames.
> 
Virtual hosting is enabled based on AWS S3, Google Cloud Storage which are known to support virtual host addressing.  Can you let us know which is the commercial S3 compatible storage service? we can simply add this as part of minio-go client configuration which optionally by `mc` can choose.

**Comment by Sovetnikov** [comment]
hb.bizmrg.com and ib.bizmrg.com
It is hard to make a command line option or config option for VH addressing mode?
Waiting next release on every new local hosting provider is tedious.
And seems that bucket path addressing has less priority on AWS S3 and so may not be supported for 3rd party providers.

**Comment by harshavardhana** [comment]
It is possible to modify minio-go for virtual style which would remove the requirement to enable only for AWS S3

**Comment by krishnasrinivas** [comment]
@harshavardhana how about having `VirtualHostRequest` global bool in minio-go package?
and for mc:
```
mc config host add myminio http://192.168.1.123:9000 SXO8VW2OFKKP2OG7AC85 CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 virtual
```

**Comment by harshavardhana** [comment]
> mc config host add myminio http://192.168.1.123:9000 SXO8VW2OFKKP2OG7AC85 CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 virtual

We don't need to do this

- first we should explore if we can auto probe virtual host style support and deprecate s3utils.IsVirtualHostSupported() function in minio-go/pkg/s3utils. 
- bring changes to minio-go constructor to make it future extensible,  we need to perhaps now take a config struct minio.NewWithConfig(*Config)  which encompasses all the scenarios that are needed.  Once verified by @abperiasamy  we can proceed to implement something like this. 

Then it can be used here the UI part of how `mc config host add` changes can be decided later.

**Comment by deekoder** [comment]
@abperiasamy  confirmed that we should take this change.
