### ISSUE TITLE
mc -q is not quiet

### ISSUE THREAD

**Issue by nkirsch** [minio/mc#2337]
## Expected behaviour
No output
## Actual behaviour

Output indicating source -> dest as well as copy performance.

## Steps to reproduce the behaviour
```
home % /usr/local/bin/mc -q cp /tmp/.imagesnap lab/home/home.local.jpg 
`/tmp/.imagesnap` -> `lab/home/home.local.jpg`
Total: 171.97 KB, Transferred: 171.97 KB, Speed: 5.42 MB/s
```
## mc version
Version: 2017-12-12T01:08:02Z
Release-tag: RELEASE.2017-12-12T01-08-02Z
Commit-id: 4cb6e3534286819d3e11db7c3659164655020bd3

## System information
`Darwin home.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`

**Comment by harshavardhana** [comment]
mc -q is expected to only suppress progress bar @nkirsch

**Comment by deekoder** [comment]
@nkirsch  -q is a flag which suppresses chattiness such as in the case of progressbar ux showing up. For the limited output, as a workaround you could simply redirect it to /dev/null. We have had lot of discussions while building this feature and we ended up picking q for the quiet flag (akin to other unix commands). Let us know if you have any suggestions on other flags we could consider for this purpose.

**Comment by nkirsch** [comment]
I think -q is great, I’d just have it actually quiet the display. If someone wants to NOT see the progress bar, but still see transfer output, it’s logical for me to see -q and -j (or —json) used together, because I presume the primary use case for this is scriptability.

That said, if you don’t like that logic, I’ll work around it by redirecting to /dev/null.

Thanks!

Nick

**Comment by ebozduman** [comment]
Obviously, redirecting to /dev/null will be the quickest solution for the time-being. I'll also bring the subject up into the team's attention in our next meeting.

**Comment by harshavardhana** [comment]
> If nothing else, the option text should be more explicit; it currently reads: "Suppress chatty console output."; "Disables progress bar." would be more accurate in its current form.

FWIW the `-q` description was changed a while back not sure if you are using latest version @nkirsch 
```
  --quiet, -q                      Disable progress bar display.
```

**Comment by nkirsch** [comment]
Cool, thanks!

**Comment by kannappanr** [comment]
Nothing to implement. Closing this issue.
