### ISSUE TITLE
mc mirror: [feature] Request for excluding dirs

### ISSUE THREAD

**Issue by peters77** [minio/mc#2343]
## Expected behaviour
Add an option to mc mirror to exclude one or more directories/folders while mirroring a local folder to a bucket. 

Example: 

/test 

contains ----> etc/ 
               ----> usr/
               ----> usr2/

While mirroring test/ add an option to prevent mc to mirror for example subdir usr2/ to the target bucket.

example:

mc mirror _**--exclude usr2/**_ test/ play/mybucket

**Comment by vadmeste** [comment]
Hey @peters77,

mc mirror already has an exclude option, you can use `--exclude "usr2/*"` to avoid usr2 from being mirrored.

@peters77 I am closing this issue but feel free to comment/reopen if you have any issue.
