### ISSUE TITLE
Event notification filters, multiple suffixes

### ISSUE THREAD

**Issue by daniel-007** [minio/mc#2346]
## Expected behaviour
mc events add play/andoria arn:minio:sqs:us-east-1:1:your-queue --prefix photos/ --suffix .jpg,.png,.tiff
## Actual behaviour
it does't work
## mc version
Version: DEVELOPMENT.GOGET
Release-tag: DEVELOPMENT.GOGET
Commit-id: DEVELOPMENT.GOGET

## System information
windows 10 64bit

**Comment by harshavardhana** [comment]
AWS S3 doesn't allow multiple suffixes for the same prefix @daniel-007 so we comply with the spec.

**Comment by nitisht** [comment]
@daniel-007 closing this as answered. For further questions please join us on [Slack](https://slack.minio.io)
