### ISSUE TITLE
mc mb fails for Minio server regions other than us-east-1

### ISSUE THREAD

**Issue by nitisht** [minio/mc#2352]
## Expected behaviour
`$ mc mb myminio/test` should pass

## Actual behaviour
`$ mc mb myminio/test` fails with

```
$ mc mb myminio/test
mc: <ERROR> Unable to make bucket `myminio/test`. Region does not match, expecting region 'us-west-2'.
```

## Steps to reproduce the behaviour
- Start Minio server with a region other than `us-east-1`. 
- add alias in mc like ` mc config host add myminio http://192.168.0.104:9000 minio minio123`
- try creating a bucket using `mc mb myminio/test`

## mc version
- Latest master

**Comment by harshavardhana** [comment]
The fix is simply removing the default https://github.com/minio/mc/blob/master/cmd/mb-main.go value for region.

**Comment by harshavardhana** [comment]
We don't need a fix in minio-go. It is behaving correctly ...

**Comment by nitisht** [comment]
as discussed this can be done using the `--region` flag. If the Minio server is not running in `us-east-1`. So this is not an issue with mc/minio-go. Closing as working as intended
