### ISSUE TITLE
Failed to copy - Object does not exist issues with cp and mirror.

### ISSUE THREAD

**Issue by tnoonan-salesforce** [minio/mc#2358]
## Expected behavior

I can use the mirror command to mirror objects on a minio s3 server to AWS S3.

## Actual behaviour

I get a weird error about the source object not being found when doing a cp or a mirror to AWS. I've checked and re-checked that the source objects do exist. In my example below the S3 alias is targeted to a bucket on AWS.

The source bucket name on the minio instance and target aws bucket names are different. Could that be the issue? Do the parent key names have to match? As an example if I wanted to mirror folder bar/baz under bucket foo does the target endpoint also have to have folder bar under a bucket named foo? 

## Steps to reproduce the behaviour

mc cp foo2/<redacted>/media/<redacted>/<redacted>/channels/release/version s3/<redacted>/media/<redacted>/<redacted>/channels/release/version

Output:

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 63
Accept-Ranges: bytes
Cache-Control: max-age=0
Content-Type: application/json
Date: Wed, 17 Jan 2018 14:57:57 GMT
Etag: "4264747af3ac2c9790b08fe76c1c6b02"
Last-Modified: Wed, 17 Jan 2018 14:39:40 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: minioRegion_9000
X-Amz-Request-Id: 150AA0D8BFAF9433

mc: <DEBUG> Response Time:  76.665281ms

mc: <ERROR> Failed to copy `http://<redacted>/<redacted>/media/<redacted>/<redacted>/channels/release/version`. Object does not exist
 (3) cp-main.go:344 cmd.doCopySession(..) Tags: [http://<redacted>/<redacted>/media/<redacted>/<redacted>/channels/release/version]
 (2) common-methods.go:169 cmd.uploadSourceToTargetURL(..) Tags: [https://s3.amazonaws.com/<redacted>/media/<redacted>/<redacted>/channels/release/version/version]
 (1) common-methods.go:113 cmd.putTargetStream(..) Tags: [s3, https://s3.amazonaws.com/<redacted>/media/<redacted>/<redacted>/channels/release/version/version]
 (0) client-s3.go:621 cmd.(*s3Client).Put(..)
 Release-Tag:DEVELOPMENT.2018-01-17T14-51-21Z | Commit:d9663e5d96d5 | Host:<redacted> | OS:darwin | Arch:amd64 | Lang:go1.9.2 | Mem:2.4MB/11MB | Heap:2.4MB/6.5MB

I get a similar series of errors when using mirror:

mc mirror --overwrite --debug source/<redacted>/media/<redacted>/<redacted>/channels/release s3/<redacted>/media/<redacted>/<redacted>/channels/release

mc: <ERROR> Failed to copy `http://<redacted>/<redacted>/media/<redacted>/<redacted>/channels/release/windows-x86`. Object does not exist
 (3) mirror-main.go:249 cmd.(*mirrorJob).startStatus.func1(..) Tags: [http://<redacted>/<redacted>/media/<redacted>/<redacted>/channels/release/windows-x86]
 (2) common-methods.go:169 cmd.uploadSourceToTargetURL(..) Tags: [https://s3.amazonaws.com/<redacted>/media/<redacted>/<redacted>/channels/release/windows-x86]
 (1) common-methods.go:113 cmd.putTargetStream(..) Tags: [s3, https://s3.amazonaws.com/<redacted>/media/<redacted>/<redacted>/channels/release/windows-x86]
 (0) client-s3.go:621 cmd.(*s3Client).Put(..)
 Release-Tag:DEVELOPMENT.2018-01-17T14-51-21Z | Commit:d9663e5d96d5 | Host:<redacted> | OS:darwin | Arch:amd64 | Lang:go1.9.2 | Mem:2.5MB/14MB | Heap:2.5MB/6.9MB
...nnels/release/windows-x86:  0 B / 2.74 GB  

In the case of cp above, I noticed the odd path - version/version. I expected just .../version

## mc version
 Version: 2018-01-17T14:51:21Z
 Release-tag: DEVELOPMENT.2018-01-17T14-51-21Z
 Commit-id: d9663e5d96d5f32725867167de2a0403704ae537

Also have the same behavior with
Version: 2018-01-17T14:51:21Z
Release-tag: DEVELOPMENT.2018-01-17T14-51-21Z
Commit-id: d9663e5d96d5f32725867167de2a0403704ae537

## System information
Using minio server

Version: 2017-11-22T19:55:46Z
Release-Tag: RELEASE.2017-11-22T19-55-46Z
Commit-ID: d1a6c32d800f1d5b703baad1f8aeede6cf2cdf48

I

**Comment by harshavardhana** [comment]
> mc cp foo2//media///channels/release/version s3//media///channels/release/version

why do you have multiple '/' in the path?

**Comment by tnoonan-salesforce** [comment]
Oh sorry. That must have been a copy paste error.

mc cp --recursive source/<redacted>/media/<redacted>/<redacted>/ s3/<redacted>/media/<redacted>/<redacted>channels/release/

The redacted elements after the source and s3 alias' are bucket names.

**Comment by kannappanr** [comment]
Can you add `--debug` to your mc command and paste the output here? Also, can you do `mc ls` on relevant buckets and prefixes on both the source and destination with the debug flag turned on?

**Comment by tnoonan-salesforce** [comment]
So if I run -
mc ls s3/<bucket>/ 

I get -
mc: <ERROR> Unable to stat `s3/<bucket>/`. Access Denied.

If I run the following I also get access denied 
mc ls s3/<bucket>/folder1/folder2/ 

However for folder 3
mc ls s3/<bucket>/folder1/folder2/folder3/

The listing works just fine.

I wonder if the problem is related to that. The fact that the permission for the 
creds are at the nested folder?

--- Begin debug for the failed ls

mc: <DEBUG> GET /<redacted>/?location= HTTP/1.1
Host: s3.amazonaws.com
User-Agent: Minio (darwin; amd64) minio-go/4.0.0 mc/2017-12-12T01:08:02Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180118/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180118T235046Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Thu, 18 Jan 2018 23:50:46 GMT
Server: AmazonS3
X-Amz-Id-2: h17RqRt+IC24X2UL1G28iDo2VJdQyGjiv4ZRmwZZGKK0LR1B4OGSKfQk0ChhfoC1egIVC0iFBwE=
X-Amz-Request-Id: 61AF84B8D460FE60

f3
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>61AF84B8D460FE60</RequestId><HostId>h17RqRt+IC24X2UL1G28iDo2VJdQyGjiv4ZRmwZZGKK0LR1B4OGSKfQk0ChhfoC1egIVC0iFBwE=</HostId></Error>
0

mc: <DEBUG> Response Time:  628.790465ms

mc: <DEBUG> GET /?delimiter=%2F&fetch-owner=true&list-type=2&max-keys=1000&prefix=media%2F<redacted> HTTP/1.1
Host: <redacted>.s3.amazonaws.com
User-Agent: Minio (darwin; amd64) minio-go/4.0.0 mc/2017-12-12T01:08:02Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180118/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180118T235047Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Thu, 18 Jan 2018 23:50:46 GMT
Server: AmazonS3
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: OU0QIJbsQRiphgILobqFyCYlXT3M9Ky1Busg4Hiu3+E6S468eQds8ST5gz6OP/tqxAWdUHRXuN0=
X-Amz-Request-Id: 23597DB49F176516

f3
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>23597DB49F176516</RequestId><HostId>OU0QIJbsQRiphgILobqFyCYlXT3M9Ky1Busg4Hiu3+E6S468eQds8ST5gz6OP/tqxAWdUHRXuN0=</HostId></Error>
0

mc: <DEBUG> Response Time:  521.694225ms

mc: <DEBUG> GET /?delimiter=%2F&fetch-owner=true&list-type=2&max-keys=1000&prefix=media%<redacted>%2F HTTP/1.1
Host: <redacted>.s3.amazonaws.com
User-Agent: Minio (darwin; amd64) minio-go/4.0.0 mc/2017-12-12T01:08:02Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180118/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180118T235047Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Thu, 18 Jan 2018 23:50:48 GMT
Server: AmazonS3
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: LvmAM14g34/RmwWTaQqlOBPl6wdz7tCiBdyk0EhFhmfg7VJ8aljP9l7sZyDQUSmMFfEZNok61Oo=
X-Amz-Request-Id: 3135524805DECABE

mc: <DEBUG> Response Time:  154.739055ms

mc: <DEBUG> GET /?delimiter=%2F&fetch-owner=true&list-type=2&max-keys=1000&prefix=media%2F<redacted> HTTP/1.1
Host: <redacted>.s3.amazonaws.com
User-Agent: Minio (darwin; amd64) minio-go/4.0.0 mc/2017-12-12T01:08:02Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180118/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180118T235047Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Thu, 18 Jan 2018 23:50:47 GMT
Server: AmazonS3
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: uGHRLp/ype0G0BcdMPNgfu65KltaAoe7M/tTYbIe/2/D7KUn5YYq66h20J5I7Ioz1bSi0oP/+CE=
X-Amz-Request-Id: DFA97A0B60382385

f3
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>DFA97A0B60382385</RequestId><HostId>uGHRLp/ype0G0BcdMPNgfu65KltaAoe7M/tTYbIe/2/D7KUn5YYq66h20J5I7Ioz1bSi0oP/+CE=</HostId></Error>
0

mc: <DEBUG> Response Time:  112.012518ms

mc: <ERROR> Unable to initialize target `s3/<redacted>/media/<redacted>/`. Access Denied
 (1) ls-main.go:141 cmd.mainList(..) Tags: [s3/<redacted>/media/<redacted>/]
 (0) client-s3.go:877 cmd.(*s3Client).Stat(..)
 Release-Tag:RELEASE.2017-12-12T01-08-02Z | Commit:4cb6e3534286 | Host:<redacted> | OS:darwin | Arch:amd64 | Lang:go1.9.1 | Mem:3.0MB/11MB | Heap:3.0MB/6.6MB

**Comment by harshavardhana** [comment]
Looks like you have I AM policies rejecting access..

**Comment by tnoonan-salesforce** [comment]
Yes, but I can use 'aws s3 sp' to copy anything under the IAM access folder.

**Comment by kannappanr** [comment]
@tnoonan-salesforce Can you please post your relevant IAM policy here, so that we can reproduce the issue here.

**Comment by MikeVL** [comment]
I have same error. Only one file `img008.jpg` i can`t mirror.

```
./mc ls local/magazine/clients
[2018-02-16 14:34:54 MSK] 2.9KiB avkenergo.gif
[2018-02-16 17:29:40 MSK] 501KiB img008.jpg
[2018-02-16 14:34:54 MSK] 3.2KiB mpz.gif
```
```
./mc mirror local/magazine/clients local/media/clients
mc: <ERROR> Failed to copy `http://10.78.1.54:9000/magazine/clients/img008.jpg`. Object does not exist
..magazine/clients/img008.jpg:  0 B / 501.10 KB
```
```
http -h http://10.78.1.54:9000/magazine/clients/img008.jpg
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public,max-age=2592000
Content-Length: 513122
Content-Type: image/jpeg
Date: Fri, 16 Feb 2018 21:47:45 GMT
Etag: "213212a71d0a51e4bcb834b987a5125e"
Last-Modified: Fri, 16 Feb 2018 14:29:40 GMT
Server: Minio/RELEASE.2018-02-09T22-40-05Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 1513EC9EBB6D4228
```

**Comment by kannappanr** [comment]
@MikeVL I tried to reproduce the issue and was unable to do so. I issued ` mc policy download local/magazine/clients`, though it is not required for mirroring. I did it because you seem to have that policy set. Then I issued `./mc mirror local/magazine/clients local/media/clients` I did not see any error.

If `local` is your local minio server, you can also enable http tracing by setting environment variable MINIO_HTTP_TRACE=<log_file.log>

Can you please enable `--debug` in your mc mirror and command and paste the relevant debug logs here?

**Comment by MikeVL** [comment]
minio server logs:
```
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [151882039.160282] [2018-02-16 22:33:11 +0000]
HEAD /magazine/clients/img008.jpg
Host: 10.78.1.54:9000
User-Agent: Minio (linux; amd64) minio-go/4.0.7 mc/2018-02-09T23:07:36Z
Authorization: AWS4-HMAC-SHA256 Credential=77C721B81152521A/20180216/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=3e3bd5341bda1300042a174e1503c7d793342a3f3eb7c7091e4f92b1f31dea4a
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180216T223311Z


[RESPONSE] [151882039.160282] [2018-02-16 22:33:11 +0000]
200 OK
Vary: Origin
Accept-Ranges: bytes
Last-Modified: Fri, 16 Feb 2018 14:29:40 GMT
Etag: "213212a71d0a51e4bcb834b987a5125e"
Content-Type: image/jpeg
X-Amz-Request-Id: 1513EF195F225D94
Server: Minio/RELEASE.2018-02-09T22-40-05Z (linux; amd64)
Content-Length: 513122
Cache-Control: public,max-age=2592000
```

mc client debug log:
```
mc: <DEBUG> HEAD /magazine/clients/img008.jpg HTTP/1.1
Host: 10.78.1.54:9000
User-Agent: Minio (linux; amd64) minio-go/4.0.7 mc/2018-02-09T23:07:36Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180216/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180216T223311Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 513122
Accept-Ranges: bytes
Cache-Control: public,max-age=2592000
Content-Type: image/jpeg
Date: Fri, 16 Feb 2018 22:33:11 GMT
Etag: "213212a71d0a51e4bcb834b987a5125e"
Last-Modified: Fri, 16 Feb 2018 14:29:40 GMT
Server: Minio/RELEASE.2018-02-09T22-40-05Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 1513EF195F225D94

mc: <DEBUG> Response Time:  2.714254ms

mc: <ERROR> Failed to copy `http://10.78.1.54:9000/magazine/clients/img008.jpg`. Object does not exist
 (3) mirror-main.go:267 cmd.(*mirrorJob).startStatus.func1(..) Tags: [http://10.78.1.54:9000/magazine/clients/img008.jpg]
 (2) common-methods.go:169 cmd.uploadSourceToTargetURL(..) Tags: [https://***/media/clients/img008.jpg]
 (1) common-methods.go:113 cmd.putTargetStream(..) Tags: [local, https://***/media/clients/img008.jpg]
 (0) client-s3.go:621 cmd.(*s3Client).Put(..)
 Release-Tag:RELEASE.2018-02-09T23-07-36Z | Commit:3987f1405aa7 | Host:magazine-docker | OS:linux | Arch:amd64 | Lang:go1.9.4 | Mem:2.9MB/11MB | Heap:2.9MB/7.9MB
```

**Comment by kannappanr** [comment]
@MikeVL Thanks for the logs. what version of Minio server are you running this on? What is the mode that you are running it?

Also, are the other two files `avkenergo.gif` and `mpz.gif` copied over to the target? You can do a `mc ls local/media/clients` and verify it

**Comment by MikeVL** [comment]
@kannappanr I use lates docker image.

```
# minio --version
VERSION:
  2018-02-09T22:40:05Z
```

Early i copy all files from digitaloceanspaces s3 to `elec/magazine/clients` via `rclone copy ...`

But file `img008.jpg` created by `django-s3-stprage` backend.

Other two files are success copied
```
./mc ls local/media/clients
[2018-02-16 23:03:15 MSK] 2.9KiB avkenergo.gif
[2018-02-16 23:03:16 MSK] 3.2KiB mpz.gif
```

**Comment by MikeVL** [comment]
I try to copy files from digital ocean to new test bucket:

```
./mc mirror spaces/elec-magazine/clients local/test/clients
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <ERROR> Failed to copy `https://ams3.digitaloceanspaces.com/***/clients/avkenergo.gif`. Object does not exist
mc: <ERROR> Failed to copy `https://ams3.digitaloceanspaces.com/***/clients/mpz.gif`. Object does not exist
```

I remove `Cache-Control` header from meta

```
s3cmd modify -v --remove-header=Cache-Control --recursive s3://magazine/clients

INFO: Retrieving list of remote files for s3://magazine/clients ...
INFO: Summary: 5 remote files to modify
modify: 's3://magazine/clients/avkenergo.gif'
modify: 's3://magazine/clients/mpz.gif'
```

And all files copied success.

**Comment by kannappanr** [comment]
@MikeVL Can we please have debug output for the failed mirror command

```./mc mirror spaces/elec-magazine/clients local/test/clients
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <ERROR> Failed to copy `https://ams3.digitaloceanspaces.com/***/clients/avkenergo.gif`. Object does not exist
mc: <ERROR> Failed to copy `https://ams3.digitaloceanspaces.com/***/clients/mpz.gif`. Object does not exist
...``` Can you please recreate the scenario where none of the files are in the destination? Then you would  issue the `mirror` command. We would expect one of the files in this case `mpz.gif` to fail mirroring.
