### ISSUE TITLE
Improvement request: make mc able to consume 10Gb/s throughput while uploading large files

### ISSUE THREAD

**Issue by sl0n** [minio/mc#2366]
## Expected behaviour
I have two 10Gb/s connected servers: one is Minio server, the other one is Minio client. Both servers are equipped with SSD local storage.
I want to upload more than 1GiB in size backup file with "mc".
I expect "mc" to consume all available bandwidth, ie 10Gb/s (given that server is not busy and can handle such a workload)
## Actual behaviour
I tried both "mc copy" and "mc mirror", but couldn't see throughput of more than ~120MiB/s per file.
## Steps to reproduce the behavior
1. Install Minio server and client on physical servers
2. Connect both servers to 10Gb network.
3. Generate more than 1GiB test file, eg with dd.
4. Run "mc copy" or "mc mirror" to test throughput.
## mc version

```
$ ./mc version
Version: 2018-01-18T21:18:56Z
Release-tag: RELEASE.2018-01-18T21-18-56Z
Commit-id: d9663e5d96d5f32725867167de2a0403704ae537

$ ./minio version
Version: 2018-01-02T23:07:00Z
Release-Tag: RELEASE.2018-01-02T23-07-00Z
Commit-ID: a6318dbdaf0a33d80e52bb762e153e4d7ca396f7

```
## System information
iperf throughput test, where minio100-04 is Minio server, minio100-02 - Minio client:

```
@minio100-02 ~]$ iperf -c minio100-04
------------------------------------------------------------
Client connecting to minio100-04, TCP port 5001
TCP window size:  502 KByte (default)
------------------------------------------------------------
[  3] local 10.198.232.23 port 38470 connected with 10.198.221.42 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  11.0 GBytes  9.41 Gbits/sec

```

**Comment by harshavardhana** [comment]
Thanks @sl0n for opening an issue.

**Comment by vadmeste** [comment]
@sl0n currently mc (using minio-go) spawns three threads to upload all parts in parallel. If there are other files, then copy/mirror should be even more boosted. 

If we are going to do this, then we must add an API in minio-go to control the number of threads responsible of uploading parts.

I'll refer to the team first.

**Comment by deekoder** [comment]
@sl0n  we will consider this for the future, it will be a great nice feature. But we will get to this after we wrap up some of our other open issues first. We usually move the ask to future milestone and close it. We will reactivate it again and bring it back to current milestone when we work on it.

**Comment by harshavardhana** [comment]
> @sl0n we will consider this for the future, it will be a great nice feature. But we will get to this after we wrap up some of our other open issues first. We usually move the ask to future milestone and close it. We will reactivate it again and bring it back to current milestone when we work on it.

This issue is going to be fixed by https://github.com/minio/mc/pull/2521
