### ISSUE TITLE
mc mirror --remove --watch delete all target instance's file when it can't monitor source instance

### ISSUE THREAD

**Issue by Vesnica** [minio/mc#2373]
## Expected behaviour
mc mirror --remove --watch should do nothing when it can't monitor source instance

## Actual behaviour
mc mirror --remove --watch delete all target instance's file when it can't monitor source instance

## Steps to reproduce the behaviour

1. create 2 standalone minio instance(source and target), and create test bucket
2. on source node, execute: `mc mirror --remove --watch source/test target/test`
3. cp some files to source, mirror working properly
4. do something(I don't know how) and restart mc(with the same config), mc pop the following error(3 times):
```
{"status":"error","error":{"message":"Failed to start monitoring.","cause":{"message":"Get http://127.0.0.1:9000/: dial tcp 127.0.0.1:9000: connect: cannot assign requested address","error":{"Op":"Get","URL":"http://127.0.0.1:9000/","Err":{"Op":"dial","Net":"tcp","Source":null,"Addr":{"IP":"127.0.0.1","Port":9000,"Zone":""},"Err":{"Syscall":"connect","Err":99}}}},"type":"fatal","sysinfo":{"host.arch":"amd64","host.cpus":"8","host.lang":"go1.9.2","host.name":"172-168-0-16","host.os":"linux","mem.heap.total":"2.4MB","mem.heap.used":"1.4MB","mem.total":"4.4MB","mem.used":"1.4MB"}}}
```
5. mc starts to delete all the target files
## mc version
- (Version: 2017-12-12T01:08:02Z
Release-tag: RELEASE.2017-12-12T01-08-02Z
Commit-id: 4cb6e3534286819d3e11db7c3659164655020bd3)

**Comment by harshavardhana** [comment]
Thanks for the report we will fix it soon.

**Comment by ebozduman** [comment]
@Vesnica:

I could not reproduce the problem with the provided information.
Here are the steps I followed:
1. Started 2 standalone minio servers on 9000 and 9001 ports and on 2 different directories; `/var/tmp/source` and `/var/tmp/target` respectively,
2. Configured mc command-line access points for both servers;
     ```
     $ mc config host add source http://192.168.1.22:9000 minio minio123
       Added `source` successfully.
     $ mc config host add target http://192.168.1.22:9001 minio minio123
       Added `target` successfully.
     ```
3. Created `test` bucket on both servers;
     ```
    $ mc mb source/test target/test
       Bucket created successfully `source/test`.
       Bucket created successfully `target/test`.
     ```
4. Ran the watch command
     ```
     $ ./mc mirror --remove --watch source/test target/test
     ```
5. Copied bunch of files into `source/test` bucket. I watched and verified that these files are also automatically created at `target/test` bucket.
6. I `CTRL-C`'ed `mc mirror --remove --watch` command and restarted it. The content of the `target/test` bucket stayed intact.
7. I repeated the same steps upto 6, and then `CTRL-C`'ed the minio server (source) this time to interrupt the server and in return the mirror command. minio server stopped and then `mc mirror --remove --watch` command stopped with `"Unable to mirror"` error message as expected. However, the content of the `target/test` bucket stayed intact at this point and after the minio server and mc command are restarted. So, nothing was missing in the `target/test` bucket.
8. I also tried `CTRL-C`'ing the minio server (target) and the result was the same. Nothing was missing.

Please clarify what you did in your reproduction step:
> 4. do something(I don't know how) and restart mc(with the same config)

or what we should change in our reproduction steps.

**Comment by ebozduman** [comment]
@Vesnica 
I finally reproduced the issue. I'll be looking into it.
Thanks for filing it.
