### ISSUE TITLE
Information / feature request add stable/delay option on mirror

### ISSUE THREAD

**Issue by john-bakker** [minio/mc#2380]
## Expected behaviour
I'd like to know if there is already a feature in the mirror mode to check for a stable period or a delay. 

## Actual behaviour
The folder I'm currently mirroring contains a lot of files. Every time the feature team does a deploy, it removes the entire folder and populates it again. (some of the content changes, some doesn't). I was wondering if there is already a feature to set a stable / delay period. So in case mc sees the deletes, it doesn't start deleting all the files first and then recreating them again. 

The reason I'm asking this is my mc mirror watch job dies during the moments the feature team does a new deploy to my mirrored folder

## mc version
- (paste output of `mc version`)

2017-10-14

**Comment by harshavardhana** [comment]
we will get to this at a future date, closing for now.
