### ISSUE TITLE
Installing minio-client via homebrew

### ISSUE THREAD

**Issue by knyttl** [minio/mc#2394]
## Expected behaviour
`brew install minio/stable/mc` should install minio-client even when midnight commander has been already installed via homebrew before

## Actual behaviour
```
Error: Cannot install minio/stable/mc because conflicting formulae are installed.
  midnight-commander: because Both install a `mc` binary

Please `brew unlink midnight-commander` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```
## Steps to reproduce the behaviour
- `brew install mc`
- `brew install minio/stable/mc`

I am aware of many similar issues, but there is no straightforward information how to install the client via homebrew.

**Comment by harshavardhana** [comment]
This is not possible @knyttl https://github.com/minio/mc/blob/master/CONFLICT.md please look at the explanation here. You can simply download the binary instead and rename them appropriately.

**Comment by kannappanr** [comment]
closing this issue according to the previous comments. Please feel free to open a new issue if you have any other questions.
