### ISSUE TITLE
Digital Ocean Spaces: intermittent re-uploads when using mirror command

### ISSUE THREAD

**Issue by leshik** [minio/mc#2396]
Hi there,

As DO recently introduced its Spaces object storage, I decided to give it a try. My use case here is backing up the website data, primarily images, about 38,000 files (30 GB). Each next backup starts `1h` after the last one. After the initial backup, at every launch `minio` uploads only new files. This worked pretty well for about one day, but today I noticed that most files were re-uploaded for an unknown reason.

## Expected behavior

Only new files are uploaded to the Digital Ocean object storage.

## Actual behavior

Sometimes most files get re-uploaded with no reason. Here are some log excerpts (from docker JSON logs with timestamps):

```
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-21T17:40:59.222591037Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-21T18:41:06.507027909Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-21T19:41:13.740290203Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-21T20:41:20.9104424Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-21T21:41:31.995025599Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-21T22:41:39.268870448Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-21T23:41:46.587143816Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T00:41:53.948865889Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T01:42:01.435601936Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T02:42:08.787520684Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T03:42:16.263452855Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T04:42:28.062911943Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T05:42:35.872384131Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T06:42:44.37316538Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T07:42:52.176567121Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T08:42:59.877767291Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T09:43:07.279969106Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T10:43:14.602819485Z"}
{"log":"Total: 19.10 GB, Transferred: 18.78 GB, Speed: 17.81 MB/s\n","stream":"stdout","time":"2018-02-22T12:01:14.639613701Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T13:01:23.324847165Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T13:39:32.426011259Z"}
{"log":"Total: 0 B, Transferred: 0 B, Speed: 0 B/s\n","stream":"stdout","time":"2018-02-22T14:39:39.854067865Z"}
{"log":"Total: 29.10 GB, Transferred: 28.24 GB, Speed: 25.95 MB/s\n","stream":"stdout","time":"2018-02-22T15:58:14.362950398Z"}
```

I can confirm that no one file has been added since yesterday, and if I check file listing with `mc ls -r` I see that timestamps for many files in Spaces were updated. At the same time, originals on the filesystem haven't changed and are dated back in 2016.

I've no idea if it's the minio client or DO Spaces platform problem. Any clue that could help to troubleshoot this intermittent issue is greatly appreciated.

## Steps to reproduce the behavior
`mc --quiet mirror /data do/bucket/path`

## mc version
- 2018-02-09T23:07:36Z

## System information
- Ubuntu 16.04.3 LTS
- Docker 17.12.0-CE

**Comment by harshavardhana** [comment]
> I can confirm that no one file has been added since yesterday, and if I check file listing with mc ls -r I see that timestamps for many files in Spaces were updated. At the same time, originals on the filesystem haven't changed and are dated back in 2016.

The only way this can happen is if the Listing is incomplete on "/data" and new content was added.  Since you didn't provide `--overwrite` `--remove` i don't see you would be overwriting existing data.

**Comment by leshik** [comment]
@harshavardhana do you mean that DO somehow breaks while `mc` gets the list of files for checksumming?

**Comment by harshavardhana** [comment]
> @harshavardhana do you mean that DO somehow breaks while mc gets the list of files for checksumming?

Not sure if DO is returning partial list then yes it might think that it needs to upload the files @leshik

**Comment by leshik** [comment]
What if some sort of timeout happens during the operation? I see “connection reset by peer” in logs sometimes...

**Comment by harshavardhana** [comment]
> What if some sort of timeout happens during the operation? I see “connection reset by peer” in logs sometimes...

For connection errors we simply error out, it must be that list itself is partial.

**Comment by leshik** [comment]
Ok, thanks. I also opened the ticket at DO, will keep you posted about results.

**Comment by leshik** [comment]
Got the reply from them, here it is:

> It is quite possible that the listing is incomplete, especially if Minio is not waiting long enough for the entire list to be returned. What is the timeout setting for that list action?

**Comment by harshavardhana** [comment]
> It is quite possible that the listing is incomplete, especially if Minio is not waiting long enough for the entire list to be returned. What is the timeout setting for that list action?

```go
   var transport http.RoundTripper = &http.Transport{
                                Proxy: http.ProxyFromEnvironment,
                                DialContext: (&net.Dialer{
                                        Timeout:   30 * time.Second,
                                        KeepAlive: 30 * time.Second,
                                }).DialContext,
                                MaxIdleConns:          100,
                                IdleConnTimeout:       90 * time.Second,
                                TLSHandshakeTimeout:   10 * time.Second,
                                ExpectContinueTimeout: 1 * time.Second,
                                TLSClientConfig:       tlsConfig,
                                // Set this value so that the underlying transport round-tripper
                                // doesn't try to auto decode the body of objects with
                                // content-encoding set to `gzip`.
                                //
                                // Refer:
                                //    https://golang.org/src/net/http/transport.go?h=roundTrip#L1843
                                DisableCompression: true,
                        }
```

this is the default config, we don't have any other timeouts. on an active connection we do not prematurely timeout @leshik

**Comment by deekoder** [comment]
@leshik  let us know if altering any of these timeout helped you.

**Comment by leshik** [comment]
After few more tries, I switched to GCS, and the problem disappeared. Unfortunately, DO Spaces aren't production-ready yet, had too many issues.

**Comment by harshavardhana** [comment]
> After few more tries, I switched to GCS, and the problem disappeared. Unfortunately, DO Spaces aren't production-ready yet, had too many issues.

Thanks for letting us know @leshik - do you want to keep this open still?

**Comment by leshik** [comment]
I believe this isn't `mc` problem as I had issues with other services backed by DO Spaces too. So I'll close it for now.
