### ISSUE TITLE
traffic control

### ISSUE THREAD

**Issue by fbarbeira** [minio/mc#2397]
We want to use minio client but right now we don't find any method of traffic control like s3cmd has:

```
--limit-rate=LIMITRATE
                        Limit the upload or download speed to amount bytes per
                        second.  Amount may be expressed in bytes, kilobytes
                        with the k suffix, or megabytes with the m suffix
```
For example we want to use only 400mb/s in a gigabit interface to not saturate IO client disk. Do you have in your roadmap the implementation of something like this?

**Comment by harshavardhana** [comment]
You can use external tools outside of `mc` to do this.

We do not yet have anything like this in our roadmap.

**Comment by kannappanr** [comment]
closing this as won't fix, as this is not in our roadmap now. Please feel free to file a new issue if you have further questions.
