### ISSUE TITLE
parallel workers 

### ISSUE THREAD

**Issue by limbo127** [minio/mc#2404]
Hello, 
- minio mc from latest git.
parallel workers is set to 32 on code. 
I do mc mirror with a lot of small files and 
- bandwitch seems to limit to ~ 10mbits/s  on 100mbits/s line
- mc thread is never > 13 
- http connection is never > 7 

so need to specify a parameter or global var to maximize // upload ?
regards, 
Nicolas

**Comment by kannappanr** [comment]
@limbo127 There is no parameter to maximize upload. mc will spawn go-routines based on overall bandwidth usage.  10mbps is not good enough to exhaust the number of parallel operations it can do. Do you have more information that you can share about your server etc? Also, do you see a performance issue or can you describe more about what your expectations are?

**Comment by limbo127** [comment]
hello,
if i'm using mc to download or upload a simple big file ( 100G) ,
upload/download is near 80mbits/s
if 'im using mc to upload or download a lot of small files, < 32K  ,
upload/download is near 10mbits/s with paraller never exceed 10
regards
nicolas

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-03 3:12 GMT+01:00 kannappanr <notifications@github.com>:

**Comment by kannappanr** [comment]
@limbo127 Will try to reproduce this locally and get back to you. Thanks for reporting this issue.

**Comment by kannappanr** [comment]
@limbo127 I tried a basic test to mirror a folder with a single file of size 400 MB to `play` server and it took about 3 minutes and 19 seconds. I also mirrored a folder with 12800 files each of size 32KB and it took about 3 minutes and 28 seconds.

**Comment by limbo127** [comment]
our tests is about aws s3. I don't know why paralele http connection is
less than 10 , the code limit is 32 .
regards
nicolas

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-05 22:35 GMT+01:00 kannappanr <notifications@github.com>:

**Comment by harshavardhana** [comment]
Quite simply because you have saturated your link we only create new threads as needed and stop when we see a saturation.

**Comment by limbo127** [comment]
I redo the tests : 

/data  is a lot of small files ( < 32 K ) 
mc mirror /data/  s3/xxx    : 500KB/s
netstat -pan |grep mc   => 1 connection
htop shows 10 mc thread

mc cp /data2/test  s3/xxxx  : 11MB/s 
test is one file of 10G
netstat -pan |grep mc -> 4 connections
htop show 10 mc thread

Regards
Nicolas

**Comment by limbo127** [comment]
I redo the tests :

/data is a lot of small files ( < 32 K )
mc mirror /data/ s3/xxx : 2MB/s
netstat -pan |grep mc => ~ 7 connections only 4 max active in same time
htop shows 10 mc thread

mc cp /data2/test s3/xxxx : 11MB/s
test is one file of 10G
netstat -pan |grep mc -> 4 connections
htop show 10 mc thread

netstat shows that with mc cp on single file, 4 http connections  is open during the copy 
with mc mirror, it seems that connection is created and deleted during process, mirror // does not keep the same connection during the mirror, perhaps the time to establishing new http connection explains this bandwitch difference.

Regards
Nicolas

**Comment by limbo127** [comment]
For your attention, i do some test with https://github.com/folbricht/desync  which is using minio as librairy for s3 endpoint, and manage a lot of small files ... and bandwitch is 11MB/s all , so it seems to be relative to http connection of minio mc 
regards, 
Nicolas

**Comment by systemlevel** [comment]
Is there a proposed resolution to this issue? As I have pointed out I am experiencing very slow performance when there are many small files in minio.  We have close to 1M in our minio instance.

**Comment by harshavardhana** [comment]
> Is there a proposed resolution to this issue? As I have pointed out I am experiencing very slow performance when there are many small files in minio. We have close to 1M in our minio instance.

@systemlevel this issue is not related to your problem - you have sufficient bandwidth and `mc` shouldn't be slow.
