### ISSUE TITLE
mc admin info does not work when a non default region is set in Minio server

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#2411]
Reported by brauliobo in #general Slack channel.

## Expected behaviour
`mc admin info myminio/` should always work for whatever region.

## Actual behaviour
`mc admin info myminio/` doesn't work when Minio server is set with a non default region, like `us-west-2`

```
mc admin info myminio/
mc: <ERROR> Cannot get service status. The authorization header is malformed; the region is wrong; expecting 'us-east-1'.
```

## Steps to reproduce the behaviour
- Set `us-west-2` in ~/.minio/config.json
- Run minio server
- mc admin info myminio/

## mc version
master (fe82b0381c5ccf004515be3bfd9b6fa733890005)

## System information
All

**Comment by foxdalas** [comment]
Thx. Waiting

**Comment by harshavardhana** [comment]
This is already fixed and released.
