### ISSUE TITLE
Breaking change in RELEASE.2018-03-14T23-16-27Z

### ISSUE THREAD

**Issue by leshik** [minio/mc#2414]
Something has happened between `RELEASE.2018-02-09T23-07-36Z` and `RELEASE.2018-03-14T23-16-27Z` that broke my setup. I use `mc` to backup website assets at regular intervals to GCS. Previously, if some files were removed at the source, `mc` complained about it but still continued the mirror operation (and it was ok because I don't want to delete anything from backup). With the new version, it just stops after the first encountered error of such type.

## Expected behavior

`mc: <ERROR> Unable to prepare URL for copying. Delete not allowed for 'https://storage.googleapis.com/example/assets/originals/image/7/4/7473/8b2367af-5a29-496d-87de-2b9c5a2e4173.jpg'. Use '--remove' to override this behavior.`

Then `mc` continues the operation until all files are mirrored successfully.

## Actual behavior

`mc: <ERROR> Unable to mirror Delete not allowed for 'https://storage.googleapis.com/example/assets/originals/image/7/4/7473/8b2367af-5a29-496d-87de-2b9c5a2e4173.jpg'. Use '--remove' to override this behavior.`

Then `mc` exits with code `1` after the first error, canceling the whole mirroring operation.

## Steps to reproduce the behavior

`mc --quiet mirror /example gcs/example/assets`

Then remove some files at source, add some other files, and repeat.

## mc version

Version: 2018-03-14T23:16:27Z
Release-tag: RELEASE.2018-03-14T23-16-27Z
Commit-id: fe82b0381c5ccf004515be3bfd9b6fa733890005

## System information

Linux AMD64

**Comment by harshavardhana** [comment]
This is not intended thanks for the report we will fix the behavior.

**Comment by harshavardhana** [comment]
We will be making a release shortly. @leshik
