### ISSUE TITLE
enhancement : does not interrupt mirror process when error occur

### ISSUE THREAD

**Issue by limbo127** [minio/mc#2415]
hello, 
when we mirror a local dir to a s3 bucket, if for example s3 bucket destination contains the same file, 
mc mirror stop with errror , for example Unable to mirror Overwrite not allowed , or Unable to mirror Delete not allowed  . We do not want using --overwrite or --remove , ( s3 policies requirement) , so is it possible to add an option, that mc mirror does not stop, but continue with all the other file of dir ?

Regards, 
Nicolas

**Comment by harshavardhana** [comment]
This is a regression we will fix it @limbo127

**Comment by deekoder** [comment]
same as #2414 @limbo127  please follow #2414 for this fix which is being worked on by @vadmeste
