### ISSUE TITLE
[Feature Request] Allow mirroring public buckets/objects

### ISSUE THREAD

**Issue by ejb1123** [minio/mc#2417]
It would be nice to allow the mc client to mirror public buckets/objects without the need for any authentication.
## Example
```
mc mirror https://play.minio.io:9000/test123/ ~/teest123
```

**Comment by kannappanr** [comment]
This is already possible

Here is the command 
`mc config host add s3-public https://s3.amazonaws.com "" ""`

**Comment by kannappanr** [comment]
@ejb1123 Closing this issue, as we already have the support to do the function you requested. Please feel free to reopen if you feel otherwise.
