### ISSUE TITLE
`mc config host add` can have an option to skip the credentials verify.

### ISSUE THREAD

**Issue by tru2dagame** [minio/mc#2422]
## Expected behaviour
`mc config host add` can have an option to skip the credentials verify.

## Actual behaviour
```
mc config host add s3-somebucket https://s3.cn-north-1.amazonaws.com.cn XXXXX XXXXXXXXXX S3v4
mc: <ERROR> Unable to initialize new config from the provided credentials. The specified bucket does not exist.
```

## Steps to reproduce the behaviour
Here is my s3 iam Policies:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1506154426000",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws-cn:s3:::somebucket/*"
            ]
        },
        {
            "Sid": "Stmt1506154452000",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws-cn:s3:::somebucket"
            ]
        }
    ]
}
```

In the old version of mc, it won't verify when I added the credentials.
And I give a very strict permission to my s3 access key. So it does like this:

**The access key can't list the bucket name. But it does have the access when you know the specific bucket name.** 

![2018-03-27 at 11 48 am](https://user-images.githubusercontent.com/1673006/37945877-fd243f60-31b4-11e8-8a0e-39e6d94a7233.png)

## mc version
- Version: 2018-03-25T01:22:22Z
Release-tag: RELEASE.2018-03-25T01-22-22Z
Commit-id: da5c19848d1e82a24eddb453b01e83d4a0660de4

## System information
Tested on macOS, Ubuntu 16.04

**Comment by harshavardhana** [comment]
You can by providing the `--api s3v4` directly and it shouldn't call the validation call path.

**Comment by kannappanr** [comment]
@tru2dagame Closing this issue as answered. Please feel free to re-open the issue if you feel otherwise.

**Comment by kannappanr** [comment]
@rbetts if option `--api` is provided, credential verification is skipped. If you do not specify the option, it will do the verification which is failing in your case. Will look into adding the option in the documentation

**Comment by aisensiy** [comment]
What exact authorization does `mc` need to work without `--api s3v4` parameter?

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws-cn:s3:::<my-bucket>"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws-cn:s3:::<my-bucket>/*"
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": "s3:GetBucketLocation",
            "Resource": "arn:aws-cn:s3:::<my-bucket>"
        },
        {
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "*"
        }
    ]
}
```

Try the command like this:

```
$ mc config host add s3 <endpoint> <key> <secret>; mc ls s3/<my-bucket>

mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
mc: <ERROR> Unable to initialize new config from the provided credentials. The specified bucket does not exist.
mc: <ERROR> Unable to stat `<my-bucket>`. Requested file `<my-bucket>` not found
```

Try with docker image `minio/mc:RELEASE.2018-05-25T20-20-15Z`.

**Comment by furkanmustafa** [comment]
> You can by providing the --api s3v4 directly and it shouldn't call the validation call path.

This worked for me. But it is extremely confusing and impossible to understand without trial or without visiting this issue.

`mc config host add` can have an explanation near `--api` argument, saying it would prevent active probing.

Also adding `--debug` outputs \****nothing***\*, the command just looks at me with empty eyes, for more than a minute.. :/
