### ISSUE TITLE
Documentation update: create sample bucket

### ISSUE THREAD

**Issue by sethgrid** [minio/mc#2430]
## Summary
Could you add a sample usage right after the `Add a Cloud Storage Service` section? Something like `mc mb <ALIAS>/<BUCKET>` and `mc ls <ALIAS>/<BUCKET>`? It was unclear to me that I needed <ALIAS>. 

I filled out the rest of your template even though it felt unrelated to this issue/request. Thanks for this client! 

## Expected behaviour
An example of using mc in readme

## Actual behaviour
No example of using mc in reame

## Steps to reproduce the behaviour
 - be unfamiliar with mc
 - install locally
 - configure to talk to remote by using `mc config host add $hostName $host $accessKey 
 - $accessSecret`
 - wonder how to make a bucket and file
 - read the very top of the readme's quick start guide, see the `mb` and `cp` commands.
 - run: `mc mb $bucket` and `mc ls` and see $bucket and think you are good to go. You are not.
 - later learn that it needs to be `mc mb $hostName/$bucket`. 

## mc version
Version: 2018-03-25T01:22:22Z
Release-tag: RELEASE.2018-03-25T01-22-22Z
Commit-id: da5c19848d1e82a24eddb453b01e83d4a0660de4

## System information
MacOSX

**Comment by deekoder** [comment]
ok let's add examples for making a bucket and putting an object in that bucket right after mc ls section which shows how to list a bucket
