### ISSUE TITLE
mc mirror +watch +overwrite is not reliable

### ISSUE THREAD

**Issue by 8666** [minio/mc#2433]
## Expected behavior

When any file changes are made on the local folder, the same changes to be reflected on the server

## Actual behavior

When renaming a file, mc.exe detects generation of a new file and upload it again with new name. On the server, you have now duplicate with the old name and the new name.

It also locks the renamed file for maybe too long so it can not be updated in meantime (let's say it is a text document that can not be saved twice in a minute)

Sometimes, rarely, it does work as expected

If I rerun the same command without --watch that it will be all synced properly. Probably 'watch' is not doing its job as expected. 

PS it will be smart if it detects renaming without reuploading the file just renaming it on the server too.
## Steps to reproduce the behavior

mc.exe mirror --watch --overwrite --remove  c:\tools buckets/folder1

rename a file in c:\tools

refresh the minio server web page. File with old filename is still there

mc.exe mirror --overwrite --remove  c:\tools buckets/folder1

will fix it

## mc version
- (paste output of `mc version`)

Version: 2018-03-25T01:22:22Z
Release-tag: RELEASE.2018-03-25T01-22-22Z
Commit-id: da5c19848d1e82a24eddb453b01e83d4a0660de4

## System information

Windows 7 SP1 64bit

**Comment by deekoder** [comment]
We will investigate @8666

**Comment by deekoder** [comment]
Can reproduce. Lowering to medium since root cause is identified. We will send a fix for this. Please use the workaround until then.

**Comment by scher200** [comment]
just wondering reading this.. does the minio "mc mirror --watch --overwrite --remove" command copy full files on changes or does it update the new parts of files (like rsync for example)? @deekoder

**Comment by vadmeste** [comment]
> just wondering reading this.. does the minio "mc mirror --watch --overwrite --remove" command copy full files on changes or does it update the new parts of files (like rsync for example)? @deekoder

There is no way to update a part of an object in the S3 specification, therefore all updates are full copy.

**Comment by scher200** [comment]
I see what you mean, thank you @vadmeste

**Comment by curantes** [comment]
I have similar issue but for me this is the "--remove" part in "mc mirror --watch --overwrite --remove" which removes files from destination even if the files in source are there.

**Comment by harshavardhana** [comment]
> I have similar issue but for me this is the "--remove" part in "mc mirror --watch --overwrite --remove" which removes files from destination even if the files in source are there.

Is this still happening @curantes ?

**Comment by curantes** [comment]
@harshavardhana yes we still have this issue. But from what I can see we don't see this with the 2017-12-12T01:08:02Z version of mc. So must be something introduced in a later release of mc.

**Comment by deekoder** [comment]
@vadmeste  will pr for this soon.

**Comment by harshavardhana** [comment]
You need to update to latest mc to get this fix.

**Comment by gauravsharma071982** [comment]
@harsh , I am really sorry for confusion 

Actually, I am already using latest MC and Minio, downloaded today only

Look like mc with watch remove exclude option has problem 

I am trying to map zeppelin notebook folder 
And zeppelin creates .note temp files while modification of notebook 

Somehow in between notebook folder get deleted in minio and if I add few more code to notebook, it get created again

Tried to exclude “.*” but seems not working with mc watch

If I use mc without watch and setup crontab, seems to be working fine 

Hope this helps
