### ISSUE TITLE
`mc stat` shows security related information in Metadata

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#2436]
## Expected behaviour
mc stat shows only Content-Type metadata

## Actual behaviour
mc stat shows unrelated information to metadata

```
15:52 $ mc stat myminio/id-platform/1mb.file
Name      : 1mb.file
Date      : 2018-04-17 15:52:16 PDT
Size      : 0B
ETag      : d41d8cd98f00b204e9800998ecf8427e
Type      : file
Metadata  :
  Content-Type           : application/octet-stream
  Content-Security-Policy: block-all-mixed-content
  X-Frame-Options        : SAMEORIGIN
  X-Xss-Protection       : "1; mode=block"
```

## Steps to reproduce the behaviour
1. `mc cp 1mb.file myminio/testbucket/`
2. `mc stat myminio/testbucket/1mb.file`

## mc version
`master`

## System information
All

**Comment by harshavardhana** [comment]
@vadmeste can you vendorize the new changes?
