### ISSUE TITLE
MC_HOSTS_* environment variables are not documented

### ISSUE THREAD

**Issue by adamc00** [minio/mc#2442]
## Expected behaviour

Look for documentation relating to `MC_HOSTS_*` environment variable which allows passing configuration to `mc` via the environment rather then its configuration files.

Find documentation.

## Actual behaviour

It's not there.

I've looked everywhere. I found reference to it in the code and I have it working using the current stable release. I'd be happy to assist but would need someone who understands it properly to review my submission.

**Comment by harshavardhana** [comment]
> I've looked everywhere. I found reference to it in the code and I have it working using the current stable release. I'd be happy to assist but would need someone who understands it properly to review my submission.

Feel free to send a PR @adamc00 more than happy to review it.

**Comment by deekoder** [comment]
ping @adamc00  we'd really appreciate a PR for this if you are able to send it.

**Comment by kairichard** [comment]
Just in case anyone is wondering how the ENV variable needs to look like ->
`MC_HOSTS_<alias>='http://<accesskey>:<secret>@<url>' mc ls <alias>`

**Comment by nitisht** [comment]
PR in progress here https://github.com/minio/mc/pull/2450

**Comment by Colhodm** [comment]
This should be closed now

**Comment by nitisht** [comment]
fixed by https://github.com/minio/mc/pull/2458
