### ISSUE TITLE
mc cp s3 bucket "Object name cannot be empty"

### ISSUE THREAD

**Issue by tru2dagame** [minio/mc#2461]
## Expected behaviour
`mc cp somefile alias/s3bucketname/`
Show error
`mc: <ERROR> Failed to copy 'somefile'. Object name cannot be empty`

It seems I have to name the target filename. It should use the same name if I leave it empty.

## Actual behaviour
![2018-06-08 at 2 27 pm](https://user-images.githubusercontent.com/1673006/41142397-25770b9e-6b28-11e8-89e7-4c586880a342.png)

## Steps to reproduce the behaviour
```shell
~/Downloads/test
➜ touch test1.md

~/Downloads/test
➜ touch test2.md

~/Downloads/test
➜ echo test1 > test1.md

~/Downloads/test
➜ echo test2.md > test2.md

~/Downloads/test
➜ mc cp test1.md s3-gitlab-backup/ubnt-gitlab-backup/
mc: <ERROR> Failed to copy `test1.md`. Object name cannot be empty
mc: <ERROR> Session safely terminated. To resume session `mc session resume MNdjnqMv`

~/Downloads/test took 2s
➜ mc cp test2.md s3-gitlab-backup/ubnt-gitlab-backup/
mc: <ERROR> Failed to copy `test2.md`. Object name cannot be empty
mc: <ERROR> Session safely terminated. To resume session `mc session resume QAljlJDl`

~/Downloads/test
➜ mc cp test1.md s3-gitlab-backup/ubnt-gitlab-backup/test1.md
test1.md:              6 B / 6 B  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 129 B/s 0s
~/Downloads/test
➜ mc cp test2.md s3-gitlab-backup/ubnt-gitlab-backup/test2.md
test2.md:              9 B / 9 B  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 177 B/s 0s
```

## mc version

```
Version: 2018-05-25T20:20:15Z
Release-tag: RELEASE.2018-05-25T20-20-15Z
Commit-id: 961c4b5daebe0f5f8ac2930f087a14a597e95f5b
```

## System information

macOS 10.13.5

**Comment by harshavardhana** [comment]
can you try with the latest release @tru2dagame ?

**Comment by harshavardhana** [comment]
```

**Comment by deekoder** [comment]
closing hence.

**Comment by scottsb** [comment]
@deekoder @harshavardhana It seems this may have reverted again? Seeing the same behavior:

```
[sbuchanan@myserver ~]$ sudo -u deployer mc cp /home/deployer/database.sql sync-export/sanitized-databases
mc: <ERROR> Failed to copy `/home/deployer/database.sql`. Object name cannot be empty
mc: <ERROR> Session safely terminated. To resume session `mc session resume HXotdVmQ`

[sbuchanan@myserver ~]$ mc --version
mc version RELEASE.2019-02-06T20-26-56Z
```

**Comment by harshavardhana** [comment]
Re-opening to re-test this situation..

**Comment by ebozduman** [comment]
@scottsb, @Paic,
I've tried to reproduce this issue, but with our latest code base, version shown below, and `mc cp` worked just fine.
Version: 2019-05-02T18:46:11Z
Release-Tag: DEVELOPMENT.2019-05-02T18-46-11Z
Commit-ID: 4b858b562a0887e10bfd0414dc87e68f1af31c3a

Please let us know more information about your setup and how to reproduce the issue, so that we can have a chance to fix the problem.

**Comment by Paic** [comment]
Our problem came from a tool using mc client for S3 upload. I've checked which version the docker image `stefanprodan/mgob:0.10` use :
```
Version: 2018-07-31T02:28:53Z
Release-tag: RELEASE.2018-07-31T02-28-53Z
Commit-id: a8c97b467dad6b29caad00fa5ff7712877ffb033
```

This version has the bug.

In a more recent docker image (1.0), the version installed is
```
Version: 2019-02-20T22:21:50Z
Release-tag: RELEASE.2019-02-20T22-21-50Z
Commit-id: e538599e2ffa4ee8d8040d5cd14475b380da531a
```

The bug is still present.

**Comment by harshavardhana** [comment]
Looks the version used on your end is old @Paic

**Comment by kannappanr** [comment]
ping @tru2dagame Can you please try with the latest version?

**Comment by tru2dagame** [comment]
@kannappanr I can confirm the latest version doesn't have this issue.

```
Version: 2019-05-01T23:27:44Z
Release-tag: RELEASE.2019-05-01T23-27-44Z
Commit-id: b1aa2232ef3babc5f06bacb1b0044022185457ca
```

**Comment by kannappanr** [comment]
@tru2dagame Thanks for confirming. closing this issue now.

**Comment by neofreko** [comment]
This issue returned in the release from https://github.com/minio/minio/tree/RELEASE.2020-04-02T21-34-49Z

Downgrading to older releases fix the issue.

**Comment by harshavardhana** [comment]
> This issue returned in the release from https://github.com/minio/minio/tree/RELEASE.2020-04-02T21-34-49Z
> 
> Downgrading to older releases fix the issue.

are you talking about server or `mc` @neofreko ? also please open a new issue.
