### ISSUE TITLE
'mc rm --incomplete <object>' removes incomplete files one by one.

### ISSUE THREAD

**Issue by ebozduman** [minio/mc#2465]
## Expected behaviour
All generated incomplete files are removed when the `mc rm --incomplete <object>` command runs the first time.
## Actual behaviour
Incomplete files are removed one by one. I.e. if there are 3 incomplete files, user has to run the command 3 times.
```
$ mc ls -I myminio/mybucket/1g
[2018-06-15 18:35:21 PDT] 256MiB 1g
[2018-06-15 18:36:28 PDT] 256MiB 1g
[2018-06-15 18:36:52 PDT] 768MiB 1g
$ mc rm --incomplete myminio/mybucket/1g
Removing `myminio/mybucket/1g`.
$ mc ls -I myminio/mybucket/1g
[2018-06-15 18:35:21 PDT] 256MiB 1g
[2018-06-15 18:36:28 PDT] 256MiB 1g
$ mc rm --incomplete myminio/mybucket/1g
Removing `myminio/mybucket/1g`.
$ mc ls -I myminio/mybucket/1g
[2018-06-15 18:35:21 PDT] 256MiB 1g
$ mc rm --incomplete myminio/mybucket/1g
Removing `myminio/mybucket/1g`.
$ mc ls -I myminio/mybucket/1g
mc: <ERROR> Unable to stat `myminio/mybucket/1g`. Object does not exist
```
## Steps to reproduce the behaviour
- Create a large file
- Start copying the file over to Minio server. 
- During copying, CTRL-C/interrupt the copy process
- Repeat copy/CTRL-C several times
- List and remove the generated incomplete files. You have to run the command as many number as the generated incomplete files.
## mc version
Version: 2018-06-14T00:34:59Z
Release-tag: DEVELOPMENT.2018-06-14T00-34-59Z
Commit-id: c0b89a7aecb89174f3fda68f726eea2e3342b0aa

**Comment by kannappanr** [comment]
PR https://github.com/minio/minio-go/pull/994 adds the fix in minio-go. Once it is merged, the minio-go code needs to be vendorized in mc.

**Comment by kannappanr** [comment]
Closing this issue as PR https://github.com/minio/mc/pull/2473 fixes this issue.
