### ISSUE TITLE
Add support for ppc64le

### ISSUE THREAD

**Issue by rpsene** [minio/mc#2467]
When trying to use mc on Linux/ppc64le I noticed that this platform is not supported. I tried to build it from source code and it worked perfectly.

root@rpsene-development1:~/go/src/github.com/minio/mc# uname -m
ppc64le

root@rpsene-development1:~/go/src/github.com/minio/mc# make test
Installing golint
Installing gocyclo
Installing deadcode
Installing misspell
Installing ineffassign
Running vet
Running fmt
Running lint
Running cyclo
Running deadcode
Checking dependencies
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Checking for project in GOPATH
Building minio binary to './mc'
Running unit tests
?   	github.com/minio/mc	[no test files]
ok  	github.com/minio/mc/cmd	(cached)
ok  	github.com/minio/mc/pkg/console	(cached)
ok  	github.com/minio/mc/pkg/hookreader	(cached)
ok  	github.com/minio/mc/pkg/httptracer	(cached)
ok  	github.com/minio/mc/pkg/ioutils	(cached)
ok  	github.com/minio/mc/pkg/probe	(cached)
Running functional tests
Running test_make_bucket()
Running test_make_bucket_error()
Running test_put_object()
Running test_put_object_error()
Running test_put_object_with_storage_class()
Running test_put_object_with_storage_class_error()
Running test_put_object_multipart()
Running test_get_object()
Running test_get_object_multipart()
Running test_presigned_post_policy_error()
Running test_presigned_put_object()
Running test_presigned_get_object()
Running test_cat_object()
Running test_mirror_list_objects()
Running test_mirror_list_objects_storage_class()
Running test_find()
Running test_find_empty()
Running test_watch_object()
Running test_put_object_with_sse()
Running test_put_object_with_sse_error()
Running test_put_object_multipart_sse()
Running test_get_object_with_sse()
Running test_cat_object_with_sse()
Running test_cat_object_with_sse_error()
Running test_copy_object_with_sse()
Running test_copy_object_with_sse2()
Running test_sse_key_rotation()
Running test_mirror_with_sse()
Running test_rm_object_with_sse()
Running test_config_host_add()
Running test_config_host_add_error()

root@rpsene-development1:~/go/src/github.com/minio/mc# make coverage
Checking dependencies
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Checking for project in GOPATH
Building minio binary to './mc'
Running all coverage for minio
?   	github.com/minio/mc	[no test files]
ok  	github.com/minio/mc/cmd	0.092s	coverage: 12.4% of statements
ok  	github.com/minio/mc/pkg/console	0.005s	coverage: 6.1% of statements
ok  	github.com/minio/mc/pkg/hookreader	0.005s	coverage: 35.3% of statements
ok  	github.com/minio/mc/pkg/httptracer	0.007s	coverage: 0.0% of statements
ok  	github.com/minio/mc/pkg/ioutils	0.006s	coverage: 14.3% of statements
ok  	github.com/minio/mc/pkg/probe	0.006s	coverage: 42.9% of statements

root@rpsene-development1:~/go/src/github.com/minio/mc# ./mc --help
NAME:
  mc - Minio Client for cloud storage and filesystems.

USAGE:
  mc [FLAGS] COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  ls       List files and folders.
  mb       Make a bucket or a folder.
  cat      Display file and object contents.
  pipe     Redirect STDIN to an object or file or STDOUT.
  share    Generate URL for sharing.
  cp       Copy files and objects.
  mirror   Mirror buckets and folders.
  find     Search for files and objects.
  stat     Stat contents of objects and folders.
  diff     List differences in object name, size, and date between folders.
  rm       Remove files and objects.
  events   Manage object notifications.
  watch    Watch for file and object events.
  policy   Manage anonymous access to objects.
  admin    Manage Minio servers
  session  Manage saved sessions for cp command.
  config   Manage mc configuration file.
  update   Check for a new software update.
  version  Print version info.

GLOBAL FLAGS:
  --config-folder value, -C value  Path to configuration folder. (default: "/root/.mc")
  --quiet, -q                      Disable progress bar display.
  --no-color                       Disable color theme.
  --json                           Enable JSON formatted output.
  --debug                          Enable debug output.
  --insecure                       Disable SSL certificate verification.
  --help, -h                       Show help.

VERSION:
  2018-06-18T19:10:56Z

root@rpsene-development1:~/go/src/github.com/minio/mc# ./mc config host add myminio http://9.30.210.228:9000 <KEY> <KEY>
Added `myminio` successfully.

root@rpsene-development1:~/go/src/github.com/minio/mc# ./mc ls myminio
[2018-06-18 11:15:30 PDT]     0B icp-workloads/
[2018-06-18 11:19:27 PDT]     0B travis-power/

**Comment by deekoder** [comment]
@rpsene  we don't build officially for that particular platform. But as you see, we like to make sure the source compiles on most platforms. So you will have to build it from source like you have! Glad it worked. Let us know if any other issues.

**Comment by harshavardhana** [comment]
Fixed by #2468
