### ISSUE TITLE
Mirror doesn't watch bucket creation, but when running again with same command it can copy new created bucket

### ISSUE THREAD

**Issue by rufushuang** [minio/mc#2475]
## Expected behaviour
Mirror should watch bucket creation in `mainnode`, watch the create action and create the local folder.
## Actual behaviour
Mirror does not fired by bucket creation.
## Steps to reproduce the behaviour

1. With a `mainnode` by minio server, use `mc -mirror` to backup it constantly on local disk `/miniodata`
2. `./mc mirror --overwrite --remove --watch --quiet mainnode /miniodata`
3. Create a bucket on `mainnode`. But nothings happens on local `/miniodata`. Nothing on log.

## mc version
- (paste output of `mc version`)
Version: 2018-06-22T23:32:12Z
Release-tag: RELEASE.2018.06-22T23-32-12Z
Commit-id: 4070902cdaa...
## System information
SuSE Linux 11sp2

**Comment by rufushuang** [comment]
See https://github.com/minio/minio/issues/3418

But there's still no `--region` in mc?

Also, turn the local backup to a minio-ized S3 node, tried with `-a`, result as the same issue.

**Comment by deekoder** [comment]
@rufushuang since this is how its supposed to work (aka as @harshavardhana pointed out) on already created buckets, I marked it working as intended.

**Comment by rufushuang** [comment]
Thanks for quick reply.

Got the design for the mirror action.
Some how it's confusing that run twice mirror with same command it can copy new created bucket.
Maybe some design clarification in document or somewhere?

**Comment by harshavardhana** [comment]
> Some how it's confusing that run twice mirror with same command it can copy new created bucket.
> Maybe some design clarification in document or somewhere?

It can because since the bucket creation is not notified in any manner the reason being notifications are not only for Objects not buckets in AWS S3, we could extend this by adding new meaning but at that point, it would be a new standard which can lead to confusion.

**Comment by deekoder** [comment]
@rufushuang since minio will be 100% S3 compatible, we keep in lock step with how AWS specs it out.
