### ISSUE TITLE
mc does request wrong path (# instead of /)

### ISSUE THREAD

**Issue by verymilan** [minio/mc#2477]
## Expected behaviour
Succeeding of `mc cp ~/backups/db.dump server/bucket/subfolder/`

## Actual behaviour

Object name contains unsupported characters

```
UserAgent: Minio (linux; amd64) minio-go/v603 mc/2018-06-22T23:32:12Z
Error: Object name invalid: bucket#subfolder/
       1: cmd/object-api-input-checksgo:171:cmdcheckObjectArgs()
       2: cmd/object-api-input-checksgo:136:cmdcheckNewMultipartArgs()
       3: cmd/fs-v1-multipartgo:213:cmd(*FSObjects)NewMultipartUpload()
       4: cmd/object-handlersgo:839:cmd(ObjectLayer)NewMultipartUpload-fm()
       5: cmd/object-handlersgo:843:cmdobjectAPIHandlersNewMultipartUploadHandler()
       6: cmd/api-routergo:69:cmd(objectAPIHandlers)NewMultipartUploadHandler-fm()
       7: net/http/servergo:1947:httpHandlerFuncServeHTTP()
```

Minio version: `2018-04-19T22:54:58Z`
mc version: `2018-06-22T23:32:12Z`

...working mc version: `2018-03-25T01:22:22Z`

or is this a mc <-> minio version conflict?

**Comment by vadmeste** [comment]
Thanks for reporting this, this is an important bug and I was able to reproduce it, it seems a regression in mc when the target object exists, we'll take a look quickly on this.
