### ISSUE TITLE
No Proxy Support in Windows Binary Version

### ISSUE THREAD

**Issue by D1rect10ns** [minio/mc#2479]
## Expected behaviour
MC for Windows would have the ability to be used behind a proxy, using the Internet Explorer configured proxy settings and the logged in users credentials.

## Actual behaviour
MC can not connect to the specified endpoint as the Proxy requests authentication.

## Steps to reproduce the behaviour
Run MC when behind a proxy.

## mc version
Version - 2018-06-09T02:18:09Z

## System information
Windows 10 / 2012 R2 / 2016

**Comment by harshavardhana** [comment]
You can https://golang.org/pkg/net/http/#ProxyFromEnvironment just set one of the environment variables. Binaries for Windows and Linux are no different in this functionality.

**Comment by D1rect10ns** [comment]
Hi, apologies, but I don’t see how you would make mc use a proxy from your response. Installing golang in this environment is not an option. If I’m missing something then please let me know.

**Comment by harshavardhana** [comment]
> Hi, apologies, but I don’t see how you would make mc use a proxy from your response. Installing golang in this environment is not an option. If I’m missing something then please let me know.

Not installing Golang just set HTTP_PROXY environment variable @D1rect10ns

**Comment by D1rect10ns** [comment]
Thanks @harshavardhana I can confirm that worked. It would be good to have the HTTP_PROXY and HTTPS_PROXY information added to the documentation.
