### ISSUE TITLE
x/net/lex/httplex has moved to x/net/http/httpguts

### ISSUE THREAD

**Issue by y0ssar1an** [minio/mc#2493]
You're importing both and that's causing `dep` to fail when I try to vendor `mc`. 

Please update your code to remove the legacy path to `httplex`.

New path: https://github.com/golang/net/blob/master/http/httpguts/httplex.go

**Comment by harshavardhana** [comment]
> You're importing both and that's causing dep to fail when I try to vendor mc.
> 
> Please update your code to remove the legacy path to httplex.
> https://github.com/golang/net/blob/master/http/httpguts/httplex.go

Why are you vendoring `mc` - its a tool not a library.

**Comment by y0ssar1an** [comment]
I'm vendoring `mc` to remove the need to fetch it during CI. This is possible using the [`required`](https://golang.github.io/dep/docs/Gopkg.toml.html#required) keyword in `Gopkg.toml`.
