### ISSUE TITLE
Does not resume loading the file mc session resume XXX

### ISSUE THREAD

**Issue by rurala** [minio/mc#2495]
## Expected behavior
With the following command you should resume the climb from where you would have cut
mc session resume XXX
## Real behavior
the  command mc session resume XXX, does not recover the interrupted upload
## Steps to reproduce the behavior
Once launched from the client the upload of a file with the command:

mc cp file.zip / mialias / bucket1

When an error occurs it tells us that to continue the upload we can do it with the mc session resume XXX command,
but this does not continue the rise but it ends

Thanks
## mc version
![version_mc](https://user-images.githubusercontent.com/41945596/43454658-0b03fba4-94be-11e8-95b6-a63d3aa87b89.JPG)

![image](https://user-images.githubusercontent.com/41945596/43454830-73e9efa2-94be-11e8-9c71-4958139c70b3.png)

**Comment by deekoder** [comment]
Looks like this is fixed? Please confirm.

**Comment by Praveenrajmani** [comment]
Hey @rurala ,

So im trying the same with `mc` linux build , 

![image](https://user-images.githubusercontent.com/5410427/43832261-7fba029c-9b24-11e8-8529-6befa13aa6f6.png)

Which works fine for me here . Am is missing something ?
And can you check again with the latest `mc` build.

Meanwhile let me try bringing that up on a windows build.

**Comment by Praveenrajmani** [comment]
I tried in windows also 
![minio](https://user-images.githubusercontent.com/5410427/43858953-02c39368-9b6d-11e8-963c-6213b55f636a.png)
It seems to work fine !

**Comment by kalleyne** [comment]
I'm seeing a similar problem with mc on Linux - Version: 2018-08-18T02:13:04Z.

partaa failed during copy yet partab gets copied during resume. This seems a little odd.

![mc](https://user-images.githubusercontent.com/8624598/44961930-e69fb880-aede-11e8-8167-82f1268a60ea.png)

**Comment by Praveenrajmani** [comment]
Yes i can see this happening . Will discuss this further with the team and then decide! Thanks for reporting!

**Comment by kalleyne** [comment]
@Praveenrajmani Thanks. :-)

**Comment by Praveenrajmani** [comment]
@kalleyne @deekoder We do a parrallel upload for each object ( It does not sequentially stream the objects in order ). The progress bar will work in common for all the uploads. As in parallel uploading, the last file/object will always be set as the title for the progress bar. So, it is expected to work like this. And it is infeasible for such feature in the current implementation (since the upload does not happen sequentially).

**Comment by harshavardhana** [comment]
session doesn't exist anymore - closing as stale issue
