### ISSUE TITLE
Unable to initialize new host

### ISSUE THREAD

**Issue by lyoko17220** [minio/mc#2496]
Hi, I'm working with the latest Docker Image. Since this morning my command `mc config host add` not working. It's a Docker client problem because the browser GUI working with same credentials.

```
mc config host add minio_caas https://myurl.fr minio4corp *********** S3v4
mc: <ERROR> Unable to initialize new config from the provided credentials. The specified bucket is not valid.
```

**Comment by nitisht** [comment]
Thanks for reporting @lyoko17220 we will fix it soon

**Comment by lyoko17220** [comment]
When a new "latest" image will be on Docker Hub ?
