### ISSUE TITLE
mc mirror --watch should exit with non-zero code upon failure

### ISSUE THREAD

**Issue by KhaledSharif** [minio/mc#2505]
## Expected behaviour

When an error occurs, `mc mirror` with the `--watch` option should exit with a non-zero code.

## Actual behaviour

`mc mirror` does not exit and continues watching. Moreover, when the error is solved, `mc mirror --watch` does not automatically mirror the file(s) that failed the first time.

## Steps to reproduce the behaviour

```
while true; do
    mc mirror --watch minio/mybucket minio_offsite/mybucket
    echo "exited"
done
```

```
minio_client_1   | `minio/mybucket/h.html` -> `minio_offsite/mybucket/h.html`
minio_client_1   | mc: <ERROR> Failed to copy `http://minio:9000/mybucket/h.html`. Put http://minio_offsite:9000/mybucket/h.html: dial tcp: lookup minio_offsite on 127.0.0.11:53: no such host
```

## mc version

```
Version: 2018-08-02T17:39:44Z
Release-tag: RELEASE.2018-08-02T17-39-44Z
Commit-id: 9998e077dfd70a0c1189f1a9b5d7ab25a6e01b79
```

**Comment by kannappanr** [comment]
@KhaledSharif Thanks for filing this issue. Since this is a watch command, and while the mirror is still running, if there is any error and you resolve it, I will not expect the file to be mirrored. I can check internally and get back to you on how we should handle this scenario. 

Can you also let us know in which scenarios do you see this issue? A way to reproduce this issue might be helpful.

**Comment by KhaledSharif** [comment]
Imagine you have two instances of Minio on two separate servers, minio and minio_offsite. You upload file A to minio, it is detected by the mirror --watch command and is copied to minio_offsite. Before you upload file B to minio, minio_offsite becomes offline. mirror --watch fails to copy file B over to minio_offsite, but the command stays running. When minio_offsite comes back online, I upload file C and in turn it is copied to minio_offsite. File B is never mirrored while the mirror watch command is running.

My workaround to this issue is to not use the watch command and instead put mirror in a Bash infinite loop, as so:

```
while true
do

mc mirror minio/bucket minio_offsite/bucket
sleep 1

done
```
