### ISSUE TITLE
Mc mirror --watch should exit if source bucket doesn't exist.

### ISSUE THREAD

**Issue by aarushiarya** [minio/mc#2522]
## Expected behaviour
mc mirror does not exit and continues watching, even if source bucket doesn't exist.
## Actual behaviour
mc mirror gives an error if source bucket doesn't exist and continues watch.

## Steps to reproduce the behaviour
1. Add host to mc.
2. Run mc mirror watch, enter bucketname that doesn't exist in the source.
mc mirror --watch minio/mybucket myminio/mybucket
3. mc gives out an error
4. mc: <ERROR> Unable to perform a mirror action. The specified bucket does not exist
Continues watch.

## mc version
`Version: 2018-08-02T23:11:36Z 
Release-Tag: RELEASE.2018-08-02T23-11-36Z 
Commit-ID: a091b1a3eefbaea07499bef9a5462280ec9d2a7a`

**Comment by deekoder** [comment]
We will fix this in the future. Closing for now and will reactivate once we are done with current priorities.
