### ISSUE TITLE
Provide `--stdin` flag usable for other operations, like `mb` or `stat`

### ISSUE THREAD

**Issue by cstamas** [minio/mc#2528]
## Expected behaviour
IMO, would simplify automation with mc, to have `--stdin` flag for other operations, not just `rm`.

## Actual behaviour
To create several buckets at once, several mc invocation needed.

## Steps to reproduce the behaviour
This is new feature request.

## mc version
Release-tag: RELEASE.2018-08-18T02-13-04Z
Commit-id: 073ed250fea2beec9b2c5534f9c71b5ebaae79df

## System information
Linux/OSX

**Comment by harshavardhana** [comment]
you can create buckets by specifying multiple buckets as arguments

```
mc mb play/testbucket.{1..100}
```

I don't see a good reason to have --stdin flags

**Comment by cstamas** [comment]
Oh, cool, did not know that. Still, this is ok for "range", but in case of some hashes not quite working.

Anyway, the "range" thing "works for me", so you can close this issue then.

**Comment by kannappanr** [comment]
closing this issue based on the previous comments
