### ISSUE TITLE
Update rjeczalik/notify to fix MacOS builds

### ISSUE THREAD

**Issue by eborisch** [minio/mc#2535]
## Expected behaviour
Successfully build mc on macOS. (Go 1.11)

## Actual behaviour
Can't build mc on macOS, fails with:
```
# github.com/minio/mc/vendor/github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51:216: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:162:47: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCStringNoCopy
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:163:225: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
```
This issue was appears to have been identified and fixed upstream: https://github.com/rjeczalik/notify/pull/162

## Steps to reproduce the behaviour
Build on macOS with Go 1.11

## mc version
Attempting to build 2018-09-10T23-39-12Z

## System information
macOS High Sierra 10.13.6; Go 1.11

**Comment by kannappanr** [comment]
@eborisch Thanks for filing this issue. We will update the library soon.

**Comment by harshavardhana** [comment]
@eborisch just compile with `go build -tags kqueue`
