### ISSUE TITLE
mc mirror --watch --remove crash after  a few hours

### ISSUE THREAD

**Issue by curantes** [minio/mc#2537]
## Expected behaviour

Should be able to run sync with `mc mirror --watch` without mc client crashing

## Actual behaviour
After mirroring for a few hours the mc client crash with log:
```
Failed to copy `http://minio:9093/197/247197/2018/0912/a39d3625-811f-4aa4-8240-a2dcca8ecfc2.pdf`. Object does not exist
```

## Steps to reproduce the behaviour
run `mc mirror --watch --remove cluster /local/disk`
cluster have 1000 buckets, files are pdf and images avrage file size 1-3 mb

## mc version
- RELEASE.2018-09-06T23-26-56Z

## System information
mc client runs on FreeBSD, mc client is compiled with golang 1.10.3
mc is running from a FreeBSD server to mirror a minio cluster to local zfs disk where we take periodic zfs snapshot of filesystem

**Comment by vadmeste** [comment]
@curantes Object Not Found error by itself could be a normal thing if the object itself is deleted by a separate process.

You said it crashed, do you have any stacktrace ?

**Comment by curantes** [comment]
@vadmeste where can I find the stack trace, ot do I need to start it with som paramter?

**Comment by curantes** [comment]
@harshavardhana we are using RELEASE.2018-09-06T23-26-56Z as discribed in issue. nothing gets printed its just silently dies.

**Comment by vadmeste** [comment]
> @harshavardhana we are using RELEASE.2018-09-06T23-26-56Z as discribed in issue. nothing gets printed its just silently dies.

@curantes can we agree first that "Object Not Found" error is normal if some clients removes that object during mirroring ?

**Comment by vadmeste** [comment]
@curantes why do you think mc did silently die? there is a probability that mc just finished its job with one error (Object not found), what do you think ?

I tried the scenario and I noticed that mc continues mirroring even if it encounters Object Not Found error in the middle of mirror operation.

**Comment by vadmeste** [comment]
I was wrongly testing the scenario, I confirm that mc die after Object Not Found error without continuing mirroring the remaining files.

This has been introduced with a recent commit, but I will talk with the team to check if this is the right behavior.

**Comment by curantes** [comment]
@vadmeste in mean time can I rollback mc version to a version not having this commit? which version can I rollback to so I don't have issue with my sync's being interupted.

Thanks

**Comment by harshavardhana** [comment]
> This has been introduced with a recent commit, but I will talk with the team to check if this is the right behavior.

This is not a right behavior @vadmeste

**Comment by vadmeste** [comment]
@curantes RELEASE.2018-08-18T02-13-04Z doesn't have that behavior you can try with it again.



> This is not a right behavior @vadmeste

@harshavardhana, Yes I agree, especially for "Object Not Found" error. mc mirror also stops when there is a broken symlink, which seems to be also wrong for me. We might need to ignore some errors but emphasizes other errors.

**Comment by curantes** [comment]
@vadmeste I have now rolled back to version RELEASE.2018-08-18T02-13-04Z as recommended. I will check if it works better now.

**Comment by kressh** [comment]
Have same issue. `mc mirror -w --overwrite --remove source/ target/` fails with:

```
mc: <ERROR> Failed to copy `http://minio-cdn01:9000/1158/static/1158_ru-238ebc9f5e8c339db369a689f1dbb7e3b1c7f8efe9df361561d1c9df8061518e.pdf`. Object does not exist
```

In my case object totally exists, I can reach it with curl:

```
# curl -I http://minio-cdn01:9000/1158/static/1158_ru-238ebc9f5e8c339db369a689f1dbb7e3b1c7f8efe9df361561d1c9df8061518e.pdf
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=31557600
Content-Length: 13248088
Content-Security-Policy: block-all-mixed-content
Content-Type: application/pdf
Etag: "c160600234ee3e6110bc8ba31947e578"
Expires: Sun, 29 Sep 2019 05:35:21 GMT
Last-Modified: Fri, 28 Sep 2018 23:35:23 GMT
Server: Minio/RELEASE.2018-09-25T21-34-43Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 1558F00D13E23FB8
X-Xss-Protection: 1; mode=block
Date: Sat, 29 Sep 2018 17:46:51 GMT
```

I use minio/mc:latest image (38108e8d15a88bfe3f98585b8a6de1e1791046afd062ece3aad89760b99bba9b)
and minio server: Minio/RELEASE.2018-09-25T21-34-43Z
