### ISSUE TITLE
Minio Client Find UNIT hours & minutes

### ISSUE THREAD

**Issue by mitchellmaler** [minio/mc#2539]
I am using the mc docker image to find snapshot files newer than 3 hours and send it to a minio server. Right now mc can only do days and nothing lower. Could I request an enhancement to add these units as well? 

The workaround I have is to overwrite the entrypoint of the docker image so I can use the built-in find command which supports mmin.

For Example
```
docker run --rm -v /etcd-snapshots:/backups -it --entrypoint /usr/bin/find minio/mc /backups -type f -mmin -180 -exec mc ls {} +
```

**Comment by harshavardhana** [comment]
> I am using the mc docker image to find snapshot files newer than 3 hours and send it to a minio server. Right now mc can only do days and nothing lower. Could I request an enhancement to add these units as well?

We can add hours @mitchellmaler

**Comment by kannappanr** [comment]
Closing this issue as #2614 has been merged.
