### ISSUE TITLE
mc client seems to be waiting when proxy setting is set, but not available

### ISSUE THREAD

**Issue by limbo127** [minio/mc#2541]
Version: 2018-09-06T23:26:56Z
Release-tag: RELEASE.2018-09-06T23-26-56Z
Commit-id: 0d0638b398e69887b5d7c0abcfb32882fd37b1fd

echo $https_proxy
http://[fd00:000d:0000:0000:08e2:97ff:fe2e:f1ea]:8081

curl https://www.google.fr
curl: (7) Failed to connect to fd00:000d:0000:0000:08e2:97ff:fe2e:f1ea port 8081: No route to host

mc --debug  ls s3/cebox.eu.neo/clients/neocoretech_rd_p/routing/
mc does not release

Regards, 
Nicolas Prochazka

**Comment by limbo127** [comment]
without proxy but firewall rules to block s3 endpoint, is same issue
mc never release

**Comment by kannappanr** [comment]
@limbo127 Thanks for reaching out to us. We will try repro the issue and fix it.

**Comment by harshavardhana** [comment]
> without proxy but firewall rules to block s3 endpoint, is same issue
> mc never release

This is internal to Go implementation @limbo127 we do not have control over it, do not set proxy ENV if not needed. Why would you set it to a value which is non-existent and expect a failure?

**Comment by kannappanr** [comment]
@limbo127 Closing this issue as answered. Please feel free to reopen the issue if you feel otherwise.
