### ISSUE TITLE
mc admin service status/info return "Failed to parse server response"

### ISSUE THREAD

**Issue by xie-qianyue** [minio/mc#2556]
## Expected behaviour
run 2 admin commands:
- mc admin service status myService
- mc admin info myService

reuturn no error
## Actual behaviour
the both comamnds return "Failed to parse server response"

## Steps to reproduce the behaviour
I deploy minio in docker swarm. I don't konw whether it's related to it.

## mc version
- (paste output of `mc version`)
Version: 2018-09-10T23:39:12Z
Release-tag: RELEASE.2018-09-10T23-39-12Z
Commit-id: c352cadd4be2c6bed64884c78d1e8a8ac6efaf3f

## System information
docker swarm running on CentOS 7.5

**Comment by vadmeste** [comment]
@xie-qianyue  can you paste your Minio version ?

**Comment by xie-qianyue** [comment]
@vadmeste How can I get the Minio version? We build Minio on the codes 6 months ago.

**Comment by xie-qianyue** [comment]
@vadmeste I got the Minio version, it's RELEASE.2017-12-28T01-21-00Z, should I update the Minio version?

**Comment by vadmeste** [comment]
> @vadmeste I got the Minio version, it's RELEASE.2017-12-28T01-21-00Z, should I update the Minio version?

Sure, many issues were fixed since then

**Comment by xie-qianyue** [comment]
@vadmeste I use the version RELEASE.2018-09-12T18-49-56Z, also deployed on swarm mode. When I try to run `mc config host add` comamnd, the following err occurs:
```
mc: <ERROR> Unable to initialize new config from the provided credentials. The request signature we calculated does not match the signature you provided. Check your key and signing method.
```
But I can access minio on browser, and I can upload file on browser.

**Comment by xie-qianyue** [comment]
Maybe I found the reason, we have a Nginx in the docker swarm, which proxy all the request to the serivce behind it, including Minio. And we use self signed certificate. I find this issus: https://github.com/minio/mc/issues/1220. But what is the official way to solve the problem?

**Comment by vadmeste** [comment]
> ```
> mc: <ERROR> Unable to initialize new config from the provided credentials. The request signature we calculated does not match the signature you provided. Check your key and signing method.
> ```

If you are using nginx, then most likely the error means that nginx is modifying S3 requests.

You need to follow the documentation here: https://docs.minio.io/docs/setup-nginx-proxy-with-minio

**Comment by xie-qianyue** [comment]
Thanks! it work on following the document.
