### ISSUE TITLE
mc mirror tls error

### ISSUE THREAD

**Issue by limbo127** [minio/mc#2558]
mirroring a lot of small files, i obtain sometimes : 

mc: <ERROR> Failed to copy `/xxxx/d32e/d32e0054b93531a52add5bcb0c2ae64a52e0930ecdff2bc237b116fddc339f54.1`. Put https://s3-eu-west-3.amazonaws.com/xxxxx//d32e/d32e0054b93531a52add5bcb0c2ae64a52e0930ecdff2bc237b116fddc339f54.1: tls: received record with version 6865 when expecting version 303

mc version
Version: 2018-09-26T00:42:43Z
Release-tag: RELEASE.2018-09-26T00-42-43Z
Commit-id: 87f7e65c4c837c8886bf2dd8800c445983b36187

**Comment by harshavardhana** [comment]
@limbo127 this is due to network issue - have you verified your network?

**Comment by harshavardhana** [comment]
what is really happening is that the TLS packets are being mangled and are received corrupted from S3 perhaps it's your local network issue like a driver bug etc. 

```go
	if c.haveVers && vers != c.vers {
		c.sendAlert(alertProtocolVersion)
		msg := fmt.Sprintf("received record with version %x when expecting version %x", vers, c.vers)
		return c.in.setErrorLocked(c.newRecordHeaderError(msg))
	}
```

**Comment by limbo127** [comment]
I cannot be sure that it's a network issue but it seems possible, due to that our infrastructure are using some udp vpn.
Regards
