### ISSUE TITLE
Installing mc from source, make fails silently

### ISSUE THREAD

**Issue by eco-minio** [minio/mc#2561]
## Expected behaviour
mc should install to $GOPATH/bin/ when running make
## Actual behaviour
mc does not build and does not get installed to $GOPATH/bin

## Steps to reproduce the behaviour
1) `go get -d github.com/minio/mc`
2) `cd ${GOPATH}/src/github.com/minio/mc`
3) `make`
```
Checking dependencies
Checking for project in GOPATH
Building minio binary to './mc'
```
$GOPATH is set
```
echo $GOPATH
/home/e/go/
ls $GOPATH/bin/mc
ls: cannot access '/home/e/go//bin/mc': No such file or directory
```
Note: `go build` allowed the binary to be built but we should rely on `make` to enforce Go version and install, and `make` needs to provide output if it fails

## mc version
N/A

## System information
cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

**Comment by eco-minio** [comment]
@kannappanr the issue is that the binary doesn't actually build or get put into the path

**Comment by eco-minio** [comment]
Per discussion with @kannappanr issue was only running `make` vs. `make install`, closing.

**Comment by harshavardhana** [comment]
> Per discussion with @kannappanr issue was only running `make` vs. `make install`, closing.

`make` builds binary locally in your `pwd`, `make install` installs it to your GOPATH. Similar to all other build systems.
