### ISSUE TITLE
mc on arm64 tries IPv6 to resolve the hostname and fails

### ISSUE THREAD

**Issue by arno01** [minio/mc#2564]
Trying to use mc on my Samsung S8+ in Termux, which apparently I can't as it fails to resolve the hostname.

## Expected Behavior
mc should not struggle resolving the hostname.

## Current Behavior
mc tries IPv6 to resolve the hostname and fails.

## Possible Solution
I think the issue lies down to how DNS resolution is implemented in the Golang as I came across the same exact issue with the terraform arm32 build:

```
* provider.vsphere: error setting up new vSphere SOAP client: Post https://mysite.com/sdk: dial tcp: lookup mysite.com on [::1]:53: read udp [::1]:39892->[::1]:53: read: connection refused
```

## Steps to Reproduce
1. Make sure to have ARM-based android cellphone.
2. ``mc config host add play https://play.minio.io:9000 Q3AM3UQ867SPQQA43P2F  zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG``
2. ``mc ls play/``

## Your Environment
* Version used (`minio version`):

```
Version: 2017-06-15T03:38:43Z
Release-tag: RELEASE.2017-06-15T03-38-43Z
Commit-id: c32b1ea48b651125e33015ea0d1596cb377685a4
```

Samsung Galaxy S8+ with the latest Termux that is available from the Google Play store

```
@localhost:~$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 4.4.111-14315050-QB19732162 #1 SMP PREEMPT Tue Sep 11 11:13:13 KST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-G955F
```

**Comment by arno01** [comment]
Interesting. The above issue is gone when I am building ``RELEASE.2018-09-26T00-42-43Z`` mc directly in my Android.

### go env

```
$ go env
GOARCH="arm64"
GOBIN=""
GOCACHE="/data/data/com.termux/files/home/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="android"
GOOS="android"
GOPATH="/data/data/com.termux/files/home/go"
GOPROXY=""
GORACE=""
GOROOT="/data/data/com.termux/files/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64"
GCCGO="gccgo"
CC="aarch64-linux-android-clang"
CXX="aarch64-linux-android-clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="/home/builder/.termux-build/_cache/18-aarch64-21-v1/bin/aarch64-linux-android-pkg-config"
GOGCCFLAGS="-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/data/data/com.termux/files/usr/tmp/go-build226764631=/tmp/go-build -gno-record-gcc-switches"
```

Maybe this has something to do that I am having ``CGO_ENABLED=1`` flag?
https://golang.org/pkg/net/#hdr-Name_Resolution

**Comment by harshavardhana** [comment]
> dial tcp: lookup mysite.com on [::1]:53: read udp [::1]:39892->[::1]:53: read: connection refused

This issue is related to your DNS configuration @arno01 your mysite.com is resolving to "::1" you can fix this by either editing your /etc/hosts

**Comment by arno01** [comment]
> your mysite.com is resolving to "::1"

Fortunately, this is not my case. ``mysite.com`` (redacted of course) does not have ``AAAA`` record.
The issue is that ``<anything>.com`` would throw exact same error. The issue is that ``mc`` tries to resolve the IP over IPv6 protocol and it fails. The question is - why does it go IPv6 at all? I am not using IPv6. My device does support IPv6, but my ISP isn't. Neither the latter should cause the issue described.

> you can fix this by either editing your /etc/hosts

Not sure why you are assuming that as it is working right after I recompiled the minio client... I wish this would be that simple.
Unfortunately (or fortunately), my Android device is not ``root``'ed, so there is no way to modify my ``/etc/hosts`` and even if it was, I would never accept this as a solution since the issue is not about the ``AAAA`` DNS record nor the IPv6 in general.

**Comment by harshavardhana** [comment]
> Fortunately, this is not my case. `mysite.com` (redacted of course) does not have `AAAA` record.
> The issue is that `<anything>.com` would throw exact same error, because for some reason `mc` tries to resolve the IP over IPv6 protocol and it fails. The question is - why does it go IPv6 at all? I am not using IPv6. My device does support IPv6, but my ISP isn't. Neither the latter should cause the issue described.

It is not `mc` - `mc` doesn't do anything special in resolving your hosts. It is your /etc/resolv.conf or your /etc/nsswitch.conf configuration - which is resolving for non-existent hosts. 

you can do this perhaps with `dig mysite.com` 

> Not sure why you are assuming that as it is working right after I recompiled the minio client... I wish this would be that simple.
> Unfortunately (or fortunately), my Android device is not `root`'ed, so there is no way to modify my `/etc/hosts` and even if it was, I would never accept this as a solution since the issue is not about the `AAAA` DNS record nor the IPv6 in general.

We don't officially build for arm platform and never test it. So source compile is the recommended option here so CGO enabled if it works then its fine. 

So this is not an `mc` issue.

**Comment by arno01** [comment]
If dig, nslookup, ping .. any other glibc program resolve a host without an error, but golang app does not, particularly when it is compiled without CGO (e.g. mc, terraform), then it must be the language problem?

I think this has something to do with https://github.com/golang/go/issues/25321 but haven't checked it further.

It is sad that you do not officially build for arm, but since I found the binary https://dl.minio.io/server/minio/release/linux-arm would you consider building for ARM with CGO enabled then as it clearly works and does not when without CGO?

**Comment by harshavardhana** [comment]
We only build official binaries for the platforms we test and validate, cgo enabled requires us to do native platform compilation which is not possible from release automation point of view. 

Source compile is the way to go here.

**Comment by arno01** [comment]
Ok, fair enough.
