### ISSUE TITLE
How to mirror -w  multi-bucket in one process

### ISSUE THREAD

**Issue by xdreamman** [minio/mc#2565]
As the title says

**Comment by harshavardhana** [comment]
you can do `mc mirror -w alias1 alias2` this would mirror all buckets from alias1 to alias2 and start watching all buckets.

**Comment by xdreamman** [comment]
> you can do `mc mirror -w alias1 alias2` this would mirror all buckets from alias1 to alias2 and start watching all buckets.

I have used 'mc mirror -w minio/bucket1 ./' but this only watch one folder,I want watch multi folder

**Comment by harshavardhana** [comment]
> I have used 'mc mirror -w minio/bucket1 ./' but this only watch one folder,I want watch multi folder

do `mc mirror -w minio` watches all buckets

**Comment by kannappanr** [comment]
@xdreamman Closing this issue as answered. Please feel free to re-open if you feel otherwise.
