### ISSUE TITLE
mc goes endless loop when tries to access an unencrypted remote object while SSE-C key provided

### ISSUE THREAD

**Issue by arno01** [minio/mc#2567]
mc goes endless loop when tries to access an unencrypted remote object while SSE-C key provided.

## Expected behaviour

mc should cat/cp/mirror an unencrypted remote object despite the SSE-C key provided.

## Actual behaviour

mc goes endless loop when tries to cat/cp/mirror an unencrypted remote object with SSE-C key provided.

## Context

There could accidentally be unencrypted file in a remote directroy, so one would not want his minio client go endless loop because of that. The client should rather see a warning that the file is unencrypted.

## Possible solution

Probably the client or a server should make the difference between encrypted and unencrypted remote objects.

## Steps to reproduce the behaviour

1. mc mb server/dir
2. mc cp file1.txt server/dir/ --encrypt-key "server/dir=$(echo pwd111 | openssl dgst -sha256 -binary | xxd -p -c 32 -l 16)"
3. mc cp file2.txt server/dir/
4. mc mirror server/dir/ localdir --encrypt-key "server/dir=$(echo pwd111 | openssl dgst -sha256 -binary | xxd -p -c 32 -l 16)"

mc will go endless loop:

```
...server/dir/file1.txt:  6 B / 12 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░┃ 47 B/s
```

 ``--debug`` option will show:

```
mc: <DEBUG> HEAD /dir/file2.txt HTTP/1.1
Host: server
User-Agent: Minio (linux; amd64) minio-go/v6.0.6 mc/2018-09-26T00:42:43Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20181012/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-server-side-encryption-customer-algorithm;x-amz-server-side-encryption-customer-key;x-amz-server-side-encryption-customer-key-md5, Signature=**REDACTED**
X-Amz-Content-Sha256: **REDACTED**
X-Amz-Date: 20181012T074107Z
X-Amz-Server-Side-Encryption-Customer-Algorithm: AES256
X-Amz-Server-Side-Encryption-Customer-Key: **REDACTED**
X-Amz-Server-Side-Encryption-Customer-Key-Md5: **REDACTED**

mc: <DEBUG> HTTP/1.1 500 Internal Server Error
Connection: close
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Fri, 12 Oct 2018 07:41:06 GMT
Server: Minio/DEVELOPMENT.2018-10-11T20-22-03Z (linux; arm)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 155CCC8A12AE83C0
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  4.285215ms
```

## mc version

client ``RELEASE.2018-09-26T00-42-43Z``
server ``2018-10-11T20:22:03Z``

**Comment by kannappanr** [comment]
@arno01 Thanks for filing this issue with the steps to reproduce. This is an `minio` issue. It should return an output similar like

```
mc: <DEBUG> HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 12 Oct 2018 14:26:20 GMT
Server: AmazonS3
X-Amz-Id-2: HfFiA0/OS29Hhx5w1CNajjnqEC6x1LZLHaKbi0d8hZgzWx4cJyy0BjYvJWOs6VV1/wM62hvodJk=
X-Amz-Request-Id: 28B8E75C3DB7B7D3

124
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The encryption parameters are not applicable to this object.</Message><RequestId>28B8E75C3DB7B7D3</RequestId><HostId>HfFiA0/OS29Hhx5w1CNajjnqEC6x1LZLHaKbi0d8hZgzWx4cJyy0BjYvJWOs6VV1/wM62hvodJk=</HostId></Error>
```

**Comment by arno01** [comment]
@kannappanr should I move it to the minio github then?

**Comment by kannappanr** [comment]
as far as `mirror` command is concerned, upon receiving this failure, `mc` should retry without the ecrption headers.

**Comment by kannappanr** [comment]
@arno01 this issue can remain here.  Can you please also open an issue on minio repo.

**Comment by arno01** [comment]
@kannappanr https://github.com/minio/minio/issues/6623

**Comment by harshavardhana** [comment]
Closing as duplicate of minio/minio#6623
