### ISSUE TITLE
heal command fails with nginx

### ISSUE THREAD

**Issue by xie-qianyue** [minio/mc#2568]
## Expected behaviour
Command `heal` works.

## Actual behaviour
Command `heail` fails.

## Steps to reproduce the behaviour
First, I execute `mc admin heal -r store`:
`mc: <ERROR> Unable to display follow heal status. No such heal process is running on the server`

Then I try to execute it with force flag, `mc admin heal -f store`:
`mc: <ERROR> Unable to display follow heal status. Client token mismatch`

With --debug flag, `mc admin heal -f --debug store`:
```
mc: <DEBUG> POST /minio/admin/v1/heal/?forceStart=true HTTP/1.1
Host: localhost:9090
User-Agent: Minio (linux; amd64) madmin-go/0.0.1 mc/2018-09-10T23:39:12Z
Content-Length: 34
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20181012//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: 3d43ee8090c9fdedf76e4fe4a5075abb310649f3907c40104170e4870f83903f
X-Amz-Date: 20181012T072532Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Fri, 12 Oct 2018 07:25:32 GMT
Server: nginx/1.13.10
Vary: Origin
X-Amz-Request-Id: 155CCBB0D089EFDA
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  11.206148ms

mc: <DEBUG> POST /minio/admin/v1/heal/?clientToken=781c86a3-c23a-46e5-95f2-a52c4304d7d4&forceStart=true HTTP/1.1
Host: localhost:9090
User-Agent: Minio (linux; amd64) madmin-go/0.0.1 mc/2018-09-10T23:39:12Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20181012//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20181012T072532Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Fri, 12 Oct 2018 07:25:32 GMT
Server: nginx/1.13.10
Vary: Origin
X-Amz-Request-Id: 155CCBB0D1249160
X-Xss-Protection: 1; mode=block

9d
{"Code":"XMinioHealInvalidClientToken","Message":"Client token mismatch","Resource":"/minio/admin/v1/heal/","RequestId":"155CCBB0D1249160","HostId":"3L137"}

0

mc: <DEBUG> Response Time:  11.931351ms

mc: <ERROR> Unable to display follow heal status. Client token mismatch
 (0) admin-heal.go:130 cmd.mainAdminHeal(..)
 Release-Tag:RELEASE.2018-09-10T23-39-12Z | Commit:c352cadd4be2 | Host:hzadg-youdata-test-swarm-2.server.163.org | OS:linux | Arch:amd64 | Lang:go1.10.2 | Mem:2.1MB/8.0MB | Heap:2.1MB/4.7MB
```

## mc version
Version: 2018-09-10T23:39:12Z
Release-tag: RELEASE.2018-09-10T23-39-12Z
Commit-id: c352cadd4be2c6bed64884c78d1e8a8ac6efaf3f

## System information
Our minio is running in Docker Swarm, with other services. In front of these services, an nginx serves as reverse proxy. I found that if nginx dispatches the request to multiple minio services, the above error occurs:
```
  upstream store {
    server store1:9000;
    server store2:9000;
  }
```

If I modify the nginx conf, proxy all the request to one service, no error occurs:
```
  upstream store {
    server store1:9000;
    server store2:9000 backup;
  }
```

**Comment by kannappanr** [comment]
@xie-qianyue Thanks for filing this issue. We will try to reproduce this issue and get back to you.

**Comment by philipkozeny** [comment]
Can confirm the issue. Using latest minio binary on 3 servers in distributed mode `(2018-10-06T00:15:16Z)`. Heal does not work over nginx if there is more than one active server in upstream. Same error messages.

MC Version: 
> Version: 2018-09-26T00:42:43Z
Release-tag: RELEASE.2018-09-26T00-42-43Z
Commit-id: 87f7e65c4c837c8886bf2dd8800c445983b36187

**Comment by kannappanr** [comment]
Are other commands working and is it just an issue with heal commands?

**Comment by xie-qianyue** [comment]
@kannappanr I didn't test all the commands. The basic commands like `ls`, `mb` and also the `config`, `info` comamnds work.

**Comment by donatello** [comment]
The reason this happens is that the heal status fetching API request went to a different server in the cluster than the one that received the original heal request. This will be fixed in an enhancement on the heal API - however we do not have an ETA at this time.

CC: @deekoder

**Comment by deekoder** [comment]
I will put this in the future milestone until we fix this.

**Comment by deekoder** [comment]
I will close this and put it in the future milestone.

**Comment by deekoder** [comment]
Will reactivate and bring it to current when we work on this.
