### ISSUE TITLE
Timer expired exceptions

### ISSUE THREAD

**Issue by David-Development** [minio/mc#2577]
## Expected behavior

When copying files (`mc cp --recursive`) into a bucket which contains quite a few files (~4000), I get a `timer expired` exception ~90% of the time. This is also somewhat related to https://github.com/minio/mc/issues/2046.

Are there any steps I can do to investigate this problem a little more? I can access minio during the whole time via the web-interface. Network issues are impossible as this happens on the same host. (I'm trying to copy some files from the minio storage into a docker container on the same host). 

## Actual behavior

```bash
mc: <ERROR> Failed to copy `XXX.json`. open XXX.json: timer expired
mc: <ERROR> Session safely terminated. To resume session `mc session resume DlOGtIis`
```

Server log shows the following exception:

```bash
API: CompleteMultipartUpload(bucket=lmt, object=XXX.json)
Time: 07:15:27 UTC 10/23/2018
RequestID: 15602B817AF0CDB3
RemoteHost: xxx.xxx.xxx.xxx
UserAgent: Minio (linux; amd64) minio-go/v6.0.6 mc/2018-08-18T02:13:04Z
Error: open /storage/.minio.sys/multipart/6014934eb42c871882718ff8ab16b03deeed3908f66496d02d8cae342a9c95e2/83a0093b-893c-452a-8735-32c5403a0cb6/00001.a3cc6756fd6c344937dcec0d7e9f1c7d.67108864: timer expired
       uploadID=83a0093b-893c-452a-8735-32c5403a0cb6, partPath=/storage/.minio.sys/multipart/6014934eb42c871882718ff8ab16b03deeed3908f66496d02d8cae342a9c95e2/83a0093b-893c-452a-8735-32c5403a0cb6/00001.a3cc6756fd6c344937dcec0d7e9f1c7d.67108864, filepath=/storage/.minio.sys/tmp/3555d2cb-9041-48ef-be0a-1d6eeb9d9a5f/83a0093b-893c-452a-8735-32c5403a0cb6.d3c87fb4-e3fd-4a07-9bd3-97e1cd5de9e8
       1: cmd/logger/logger.go:295:logger.LogIf()
       2: cmd/fs-v1-multipart.go:122:cmd.(*FSObjects).backgroundAppend()
       3: cmd/fs-v1-multipart.go:596:cmd.(*FSObjects).CompleteMultipartUpload()
       4: cmd/object-handlers.go:1977:cmd.(ObjectLayer).CompleteMultipartUpload-fm()
       5: cmd/object-handlers.go:1981:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
       6: cmd/api-router.go:58:cmd.(objectAPIHandlers).CompleteMultipartUploadHandler-fm()
       7: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
```

## mc version
```
Version: 2018-09-26T00:42:43Z
Release-tag: RELEASE.2018-09-26T00-42-43Z
Commit-id: 87f7e65c4c837c8886bf2dd8800c445983b36187
```

## System Information

- Minio is deployed (standalone) on a Kubernetes Cluster (using a `hostPort` as we use an on-premise bare-metal cluster).
- Docker Container running on the same node as minio is accessing the Minio Storage using the nodes IP address. Copying small amounts of files works but as soon as we copy larger amounts of files, this operation fails quite often.
- We use HDD's in the Cluster

**Comment by kannappanr** [comment]
@David-Development The error is being returned by the `os.OpenFile` call. Are you seeing this issue if you are using minio as a standalone binary instead of say on kubernetes. Also, what is the PV filesystem being used here?

**Comment by David-Development** [comment]
@kannappanr Your pointers helped us to investigate the problem more in depth. While our investigation is still ongoing, this problem might occur due to a hardware defect on our master node (disk failure). After turning on the debug flag we can see that the minio api is returning 200 status codes and as you said, the IO operation is failing. We ran some more tests and while copying files with `scp` we got a similar exception `scp timer expired`. We're analyzing our storage right now. I'll let you know when we have more information. Thank you!

> Also, what is the PV filesystem being used here?

Plain local disk. Here's our pv-definition:

```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: research-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/dluhmer/Desktop/persistent-storage/research"
```

**Comment by David-Development** [comment]
We're still investigating this issue further. Sometimes we are even able to reproduce this issue with tools such as `nano / tail / ..` - therefore this issue is not related to minio. The hardware looks fine as we couldn't find any defects. Using `dmesg` we were able to find some kernel messages that were complaining about `talpa-deny: Timeout occurred while opening`. It looks like this is related to our anti-virus system (sophos).

@kannappanr Thank you for your help. I'll close this for now.
