### ISSUE TITLE
mc cp * does not work with a remote server 

### ISSUE THREAD

**Issue by sanguinius69** [minio/mc#2589]
## Expected behavior
Hey ! I want to copy an entire folder from one gcs folder to a remote minio server by using
`mc cp --recursive gcs/hello/world/example/* k8s/welcome/`
## Actual behavior
it's giving out an error
`mc: <ERROR> Unable to validate source gcs/hello/world/example/*`
## Steps to reproduce the behavior

connect to 2 remote minio and try to transfer the content of a folder name A to a folder named B - it seems impossible ?! I tried also mirror which is working with `mc mirror --remove --overwrite gcs/hello/world/example k8s/welcome/` but is spitting an error at the beginning
`mc: <ERROR> Failed to copy https://storage.googleapis.com/hello/world/example/ . Object name cannot be empty`

## mc version
- (paste output of `mc version`)
Version: 2018-07-13T00:53:22Z
Release-tag: RELEASE.2018-07-13T00-53-22Z
Commit-id: 70dcf20d747d305f73a117b4787acf46e6809d99

## System information
server version: Version : 2018-07-10T01:42:11Z

Thanks a lot, if you need any extra info I am available ( might be my way of doing it is not optimal as well)

**Comment by harshavardhana** [comment]
'*' is escaped by bash before we receive it, also '*' is meaningless when you provide `--recursive`. In Object storage, there can be an object which has a '*' in-it since its a flat namespace. 

I don't think it's useful to add this and there is no new functionality this would bring to Minio

**Comment by sanguinius69** [comment]
Ok so * could be an object, still there is no way to be able to copy an entire folder from one remote to another remote with changing the name of the folder ? Shouldn't this be a feature/possible ?

**Comment by kannappanr** [comment]
@sanguinius69 
Something like `mc cp --recursive gcs/hello/world/example/ k8s/welcome/` should work. I have verified this with my own setup. 
Closing this issue now. Feel free to re-open this issue, if you feel otherwise, or we have misunderstood your question.

**Comment by mp-pinheiro** [comment]
Hey, sorry for reopening this, but is there a way of using wild cards? Like copying all _.so_ files in a folder, say `cp bucket/*.so path`.

Thankss!

**Comment by kannappanr** [comment]
@mp-pinheiro You can do something like this
```
mc find s3/bucket --name "*.so" --exec "mc cp {} play/test"

```
