### ISSUE TITLE
Feature request: tab path completion

### ISSUE THREAD

**Issue by matthdsm** [minio/mc#2590]
## Expected behavior
Auto-complete bucket path on `tab`
## Actual behavior
None
## Steps to reproduce the behavior
Just hit `tab` when entering a bucket path
## mc version
```
Version: 2018-10-31T22:15:44Z
Release-tag: RELEASE.2018-10-31T22-15-44Z
Commit-id: fd340638bbd009ea4b098084f5de6ef8a7a6abaa
```
## System information
Linux Ubuntu 14.04; but useful on any system

**Comment by matthdsm** [comment]
I don't know if this is viable, but it'd be neat to have some kind of tab completion available, altough I suppose this would create a bunch of extra requests to the server.

Cheers
M

**Comment by vadmeste** [comment]
@matthdsm I am currently implementing this, it should be ready soon.

This is the issue to follow https://github.com/minio/mc/issues/2572

**Comment by matthdsm** [comment]
Great to hear! Thanks!
M
