### ISSUE TITLE
Add support for `--self-signed` flag in `config host add` command

### ISSUE THREAD

**Issue by kannappanr** [minio/mc#2596]
*** Not using standard template ***
Instead of using `--insecure` flag, we will use a `--self-signed` flag. When used, this will get the certificate of the server and calculate the hash of the public key and store it in `config.json`

When a connection is being made in mc, if this entry does not exist or does not match the one stored in `config.json`, the connection to s3 fails.

**Comment by harshavardhana** [comment]
We already have `--insecure` flag, this feature has passed its time. Closing as stale.
