### ISSUE TITLE
mc mirror aborts on a broken symlink

### ISSUE THREAD

**Issue by arno01** [minio/mc#2604]
Hello,

mc mirror aborts on a broken symlink:

```
$ mc mirror \
  --overwrite \
  --remove \
  --encrypt-key "mycloud/host1=<REDACTED>" \
  --exclude ".cache/*" \
  /home mycloud/host1/

.../Default/Web Data-journal:  2.07 MB / 2.33 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░┃ 75.30 KB/s
mc: <ERROR> Unable to perform a mirror action. Requested file `/home/user1/.config/google-chrome/SingletonCookie` has broken symlink
```

Is this expected?

## Expected behavior

I am expecting minio to mirror everything except the broken symlinks instead of just aborting the entire mirror process at the first broken symlink it encounters.

## minio client version

```
$ mc version
Version: 2018-10-18T00:40:05Z
Release-tag: RELEASE.2018-10-18T00-40-05Z
Commit-id: 0dd32c1b26f05e7f94f76f2ceb62b5229836b009
```

## minio server version

```
  Version : 2018-10-11T20:22:03Z
```

**Comment by kannappanr** [comment]
@arno01 Thanks for filing this issue. Will try to send a fix soon.

**Comment by Praveenrajmani** [comment]
Hi @arno01 , 

`mc` does not abort when a broken link is caught. It indeed continues it leaving behind the infected files.

![image](https://user-images.githubusercontent.com/5410427/48755133-475ab800-ecba-11e8-820d-83c150d76b70.png)

Can you also try updating the version ?

**Comment by arno01** [comment]
@Praveenrajmani the symlink ``/tmp/one/three`` that you have created comes last in the list since minio client processes the data alphabetically. That is why you were able to see the first two files got mirrored as expected ``DelayedFlights.csv`` & ``four/``.

Here is a better way how you can reproduce the issue:

## Minio client

```
mkdir temp1
cd temp1
touch 1{01..10}
ln -svf nonexisting 105
mc mb play/i2604
mc mirror . play/i2604
```

Result:

```
user@host:~/temp1$ mc mb play/i2604/
Bucket created successfully `play/i2604/`.
user@host:~/temp1$ mc mirror . play/i2604/
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <ERROR> Unable to perform a mirror action. Requested file `105` has broken symlink
103:                                0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃ 0s

user@host:~/temp1$ mc ls -r play/i2604/
[2018-11-20 14:04:46 CET]     0B 101
[2018-11-20 14:04:46 CET]     0B 102
[2018-11-20 14:04:45 CET]     0B 103
[2018-11-20 14:04:46 CET]     0B 104
```

I have tried the latest version of Minio client.

I have also tried bringing my own Minio server (latest version) in a docker: ``docker run --rm -ti -p 9000:9000 minio/minio:RELEASE.2018-11-17T01-23-48Z server /data``

The issue is valid.

**Comment by Praveenrajmani** [comment]
@arno01 yes i can see this happening .. will fix this :+1:
