### ISSUE TITLE
Cannot List Buckets due to Forbidden Error

### ISSUE THREAD

**Issue by filfla** [minio/mc#2609]
## Expected behavior
A list of all S3 buckets is shown

## Actual behavior
mc returns a Forbidden error. The full debug output is as shown below:

mc: <ERROR> Unable to list folder. Get https://myhostname:9000/: Forbidden
 (1) ls.go:135 cmd.doList(..) Tags: [https://myhostname:9000/]
 (0) client-s3.go:1668 cmd.(*s3Client).listInRoutine(..)
 Release-Tag:RELEASE.2018-11-06T01-12-20Z | Commit:b827fac6356f | Host:myhostname | OS:linux | Arch:amd64 | Lang:go1.10.2 | Mem:1.8MB/5.2MB | Heap:1.8MB/3.6MB

## Steps to reproduce the behavior
Using the Binary download of MC tool, install and then add the storage as per below example:

mc config host add mys3 http://192.168.1.51 BKIKJAA5BMMU2RHO6IBB V7f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12

Afterwards execute:

./mc ls mys3

## mc version
Version: 2018-11-06T01:12:20Z
Release-tag: RELEASE.2018-11-06T01-12-20Z
Commit-id: b827fac6356f80354a1cf61f43cf5e5b60bbb511

## System information
Ubuntu 16.04.3 LTS

I have confirmed that the access and secret keys are correct, since I manage to login successfully via the browser at https://myhostname:9000/

**Comment by filfla** [comment]
Unfortunately this does not work. Below you can find the commands that I have directly inputted in the server for your reference:

root@mt-ub-devoplb7:/opt/minio-client# ./mc config host add mys3 https://mt-ub-devoplb7:9000 BKIKJAA5BMMU2RHO6IBB V7f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12 --api s3v4
Added `mys3` successfully.
root@mt-ub-devoplb7:/opt/minio-client# ./mc ls mys3
mc: <ERROR> Unable to list folder. Get https://mt-ub-devoplb7:9000/: Forbidden

**Comment by Praveenrajmani** [comment]
> root@mt-ub-devoplb7:/opt/minio-client# ./mc config host add mys3 https://mt-ub-devoplb7:9000 BKIKJAA5BMMU2RHO6IBB V7f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12 --api s3v4

Can you share me the server logs ?

**Comment by filfla** [comment]
The only error that I have managed to retrieve so far is the one I quoted earlier - as soon as I execute "./mc ls mys3", the following is shown in standard output:

mc: Unable to list folder. Get https://mt-ub-devoplb7:9000/: Forbidden

Other than I have not found any log files that are generated by the Minio instance. For what its' worth I am running Minio as a standalone instance on Ubuntu, rather than on a Docker container. The config.json in the .minio.sys/config directory is configured as follows in terms of logging:

        "logger": {
                "console": {
                        "enabled": true
                },
                "http": {
                        "target1": {
                                "enabled": false,
                                "endpoint": "https://username:password@example.com/api"
                        }
                }
        },

**Comment by Praveenrajmani** [comment]
Hi @filfla ..I need the specific log prints from `./mc --debug config host add mys3 https://mt-ub-devoplb7:9000 BKIKJAA5BMMU2RHO6IBB V7f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12 --api s3v4` to understand better. Can u provide me that ?

**Comment by filfla** [comment]
I have inputted the command as per your instructions:

root@mt-ub-devoplb7:/opt/minio-client# ./mc --debug config host add mys3 https://mt-ub-devoplb7:9000 BKIKJAA5BMMU2RHO6IBB V7f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12 --api s3v4
Added `mys3` successfully.

The only line that is printed to stdout is 'Added `mys3` successfully.

I can also confirm that the entry is also inserted in /root/.mc/config.json file upon executing the command.

**Comment by Praveenrajmani** [comment]
@filfla Sorry.. my bad.. I need the logs for `./mc --debug ls mys3`

**Comment by filfla** [comment]
No worries. The logs are as per below:

root@mt-ub-devoplb7:/opt/minio-client# ./mc --debug ls mys3
mc: <ERROR> Unable to list folder. Get https://mt-ub-devoplb7:9000/: Forbidden
 (1) ls.go:135 cmd.doList(..) Tags: [https://mt-ub-devoplb7:9000/]
 (0) client-s3.go:1668 cmd.(*s3Client).listInRoutine(..)
 Release-Tag:RELEASE.2018-11-06T01-12-20Z | Commit:b827fac6356f | Host:mt-ub-devoplb7 | OS:linux | Arch:amd64 | Lang:go1.10.2 | Mem:1.8MB/6.7MB | Heap:1.8MB/3.7MB

**Comment by Praveenrajmani** [comment]
@filfla Is the server configured with any bucket policies ? need the server version as well. 

It would be better if you can connect to us on slack .. [https://join.slack.com/t/minio/shared_invite/enQtNDAzMjM0Njc4OTMzLWVhYTYyZjRlZWQ2YjhkNjAxNmM5MTEyZTZkZTI2NWJlZGUzMDI5ZjkzMDBmNGNkNDZhNGU2MmRjZmEwNGQwNTE](url)

This requires more info.

**Comment by kannappanr** [comment]
Closing this issue as stale. Please feel free to reach out to us, if you still face this issue with your Ubuntu setup
