### ISSUE TITLE
mc should respect "Set-Cookie" headers and provide the Cookie in requests

### ISSUE THREAD

**Issue by eripa** [minio/mc#2610]
## Expected behavior

`mc` should respect `Set-Cookie` headers in responses. When using a reverse proxy that uses sticky sessions based on Cookies, `mc` should provide this cookie back to the proxy for ensure the proxy/load balancer can properly persist the session.

## Actual behavior

`mc --debug` shows that the proxy/loadbalancer sends the `Set-Cookie` header in the response, but doesn't attach the cookie on the next request.

## Steps to reproduce the behavior

1. Setup a HAProxy (or similar) reverse proxy in front of minio
2. Enable the proxy to use Sticky sessions by cookie
3. Make requests with `mc --debug` to see that the `Set-Cookie` header is ignored

## mc version

```shell
 Release-Tag:RELEASE.2018-11-06T01-12-20Z | Commit:b827fac6356f | Host:e1e0a95ab4a1 | 
```

## System information

N/A

**Comment by eripa** [comment]
It might not be part of the S3 standard -- I don't know. But honestly, with that reasoning there's no need to have the `mc` client at all if it's just intended to 100% mimic the S3 client.

It's common functionality in HTTP servers/clients (https://tools.ietf.org/html/rfc2965) and since S3 wouldn't send any `Set-Cookie` it wont affect the S3 compatibility.

Feel free to close if you don't think it's a valid feature. Thanks for considering it.

**Comment by harshavardhana** [comment]
> It might not be part of the S3 standard -- I don't know. But honestly, with that reasoning there's no need to have the `mc` client at all if it's just intended to 100% mimic the S3 client.

yes, `mc` only works with S3 servers I don't think it can be used with any other object storage servers. So `mc` works within the boundaries of S3. Set-Cookie like features are meant for your custom applications, not `mc`.

**Comment by eripa** [comment]
The reason why I suggested is that it's a normal thing for load balancers to do to route traffic to the same instance. E.g. you have HAProxy in front of your minio cluster and then HAProxy injects the cookie to keep clients pinned to one server.

**Comment by harshavardhana** [comment]
This required a change in minio-go PR already sent https://github.com/minio/minio-go/pull/1054

**Comment by eripa** [comment]
Thanks a lot, @harshavardhana! Much appreciated. :)
