### ISSUE TITLE
Bucket renaming

### ISSUE THREAD

**Issue by LahariGuntha** [minio/mc#2619]
Hi,

Do we have any option of renaming the Existing bucket in Minio?
I was not able to find any documentation for this.

Thanks and Regards,
Lahari G

**Comment by harshavardhana** [comment]
There is no S3 API to do it. You will have to script this out with multiple operations.

**Comment by LahariGuntha** [comment]
Hi Harsha,

Could you please elaborate on this?

Thanks and Regards,
Lahari G

**Comment by LahariGuntha** [comment]
Hi Harsha,

Could you please elaborate the steps to rename the bucket.

Thanks and Regards,
Lahari G.

**Comment by harshavardhana** [comment]
```
mc mb myminio/newbucket
mc mirror myminio/oldbucket myminio/newbucket
mc rm -r --force myminio/oldbucket
```

This is how you would do.
