### ISSUE TITLE
`mirror` stops after an error in just one object

### ISSUE THREAD

**Issue by leshik** [minio/mc#2623]
## Expected behavior

Mirror operation shouldn't stop completely in case of errors in individual objects, though should return non-zero code in the end.

## Actual behavior

I upgraded to the last version from `RELEASE.2018-06-22T23-32-12Z` and noticed that mirroring is now stops completely if some of the objects has an error, which in my case is:

```
mc: <ERROR> Failed to copy `https://storage.googleapis.com/mybucket/very_long_path_is_here`. mkdir very_long_path_is_here: file name too long
```

This might be related to #2474 and the corresponding fix.

## mc version

`RELEASE.2018-12-05T22-59-07Z`

## System information

Linux/amd64

**Comment by nitisht** [comment]
Thanks for reporting @leshik we'll take a look .

**Comment by leshik** [comment]
@nitisht I believe it's similar to #2604, which have its fix on the way, just the condition is different.
