### ISSUE TITLE
Feature request: support client certificates

### ISSUE THREAD

**Issue by Ricordel** [minio/mc#2625]
## Goal

Be able to specify a TLS client certificate for a given host, that will then be sent with every https request. The use case is Minio running behind a reverse proxy filtering access based on client certificates.

## Suggested interface

Add two new options to `minio config host add`: `--client-cert` and `--client-cert-key` (or other relevant names), translating to two fields in the json config file.

**Comment by phillipp** [comment]
@kannappanr Hey, any updates on this? How can I help?

**Comment by aead** [comment]
That feature is something we can add. However, this is something we won't (and can't) show during server startup. Therefore I suggest a general clean way to do this:
Introduce `mc config host set <endpoint> <key> <value>` (Better names for the command `set` are welcome)
The `<key>` is the JSON object key (or an alias), <value> is the JSON value. So for example:
 - `mc config host set play mTLSKey <path-to-pem-key>`
 - `mc config host set play mTLSCert <path-to-pem-certificate>`

#### Rationale

Adding command line arguments for every possible feature becomes leads to a very confusing / complex CLI. Alternatively this FR could be implemented using env. variables. However, that approach has similar issues. It becomes difficult for users to find the right env. variable (if it exists) for their need and we have to maintain the env. as well as the config file setting anyway -> maintenance overhead.

**Comment by harshavardhana** [comment]
Let's not forget this feature is S3 incompatible, meaning S3 doesn't mandate any such client requirement. We wouldn't want to add Minio only features.

**Comment by aead** [comment]
@harshavardhana Don't agree here. Yes, AWS does not provide mTLS based authentication. (AFAIK) But following that argument our `--insecure` flag is also not "S3 compatible" - because S3 has either HTTP or HTTP + TLS with CA signed cert endpoint. Also it would be perfectly fine to run a TLS reverse proxy in-front of AWS S3.
From my perspective that is transparent to S3.

**Comment by deekoder** [comment]
@Ricordel we don't have cycles right now to take this on. I am keeping it in future milestone and will reactivate after we are done with our current priorities.
