### ISSUE TITLE
Feature request: store SSE-C keys locally

### ISSUE THREAD

**Issue by arno01** [minio/mc#2632]
## Use case

The user would benefit from having his SSE-C keys stored under ``~/.mc/`` directory when he is encrypting multiple buckets with different keys.

## Benefit how?

The user would not be needing to provide the SSE-C keys on the command line each time he accesses his data. Complicated part is when the user has multiple buckets/objects with different keys.
This also protects against [shoulder surfing](https://en.wikipedia.org/wiki/Shoulder_surfing_(computer_security)).

I would suggest to store user's SSE-C credentials under ``~/.mc/credentials/<host>.json`` files.
The layout would be something like (likely be a JSON):

- ``~/.mc/credentials/<host>.json``:
```
<bucketName1>/<objectXYZ>=<32byte-long-keys1>
<bucketName2>/<objectXYZ>=<32byte-long-keys2>
```

----

Since I am suggesting adding the ``~/.mc/credentials`` for the SSE-C keys, it might be a good idea to move the bucket's ``secretKey`` there as well. Then the layout would look like a usual JSON.

**Edit**: added ``/<objectXYZ>`` to reflect https://github.com/minio/mc/issues/2632#issuecomment-450166909
**Edit**: changed ``passwords`` to ``keys`` to reflect https://github.com/minio/mc/issues/2632#issuecomment-450198677

**Comment by kannappanr** [comment]
@arno01 There is no requirement for one bucket to have one SSE-C (password). Each object within a bucket can have a separate `SSE-C` key.

There are issues like how to maintain keys if they change etc. Will talk internally about this and get back to you.

**Comment by arno01** [comment]
@kannappanr I've edited my FR to reflect  the objects as well. The credential maintenance is solely the user problem, IMHO :-)

**Comment by aead** [comment]
@arno01 I see what you try to achieve with this feature request.
However, I think there is some kind of misunderstanding. First, a SSE-C key is not a password. A password and a cryptographic key are two separate things. Therefore from my point of view there a two separate requirements:
 1.  `mc` should be able to access/create SSE-C objects created/accessed by other S3 tools - e.g. AWS CLI. That's the reason for the current SSE-C support in mc.
 2.  `mc` should provide a nice interface to the user such that the user can simply use one/multiple passwords for one/multiple objects. Therefore I propose something like a `--encrypt` flag which expects either a password argument or (if no argument is provided) look for a certain env. var (e.g. `MINIO_MC_SSE_PASSWORD`). The password is used to derive an unique SSE-C key deterministically using a PBKDF (Argon2id). That allows a smooth interaction from the `mc` user's point of view.

Would this (2) cover your requirements @arno01

**Comment by arno01** [comment]
> 2. ``mc`` should provide a nice interface to the user such that the user can simply use one/multiple passwords for one/multiple objects. Therefore I propose something like a ``--encrypt`` flag which expects either a password argument or (if no argument is provided) look for a certain env. var (e.g. ``MINIO_MC_SSE_PASSWORD``). The password is used to derive an unique SSE-C key deterministically using a PBKDF (Argon2id). That allows a smooth interaction from the ``mc`` user's point of view.

@aead I actually meant the ``keys``, not the ``passwords`` in the FR. I have updated the FR to reflect this.

Thinking of ``(2)`` could seem to be a nice idea at the first sight, except if it isn't. People will start confusing the password with the key as this would add more entropy (which is only good in CSPRNG ;) ). Especially that confusion will happen once the users will want to use other than Minio Client software, such as AWS client. (i.e. hoping they won't remove their ``~/.mc/credentials`` or at least can derive their password deterministically using a PBKDF). And what I mean by "more entropy" is that you might want to add other than ``Argon2id`` PBKDF (or users might want to add more PBKDF's) which would increase the complexity and confusion.

I think that the way how the users are managing (e.g. generating their keys either by doing ``openssl rand 1024 | tr -dc 'a-zA-Z0-9' | head -c32`` or anything else [e.g. PBKDF] they find is good for their use-case) and maintaining (e.g. rotating them) their keys is solely the user problem.

I am not sure becoming a Swiss Army knife is the way Minio Client should go.

What I would like the Minio Client do with the scope of this FR is only to help the user store his SSE-C keys in a config file.

**Comment by aead** [comment]
I agree that users may get confused by different options for encrypting their objects. However, users may also not use SSE-C just because of all the key management overhead - which is currently their responsibility. 

> What I would like the Minio Client to do with the scope of this FR is only to help the user store his SSE-C keys in a config file.

Honestly, I don't think it is a good idea to store the SSE-C keys in a file (in plaintext). It may indeed prevent shoulder surfing but on the other side compromising / exposing this file compromises **all** SSE-C encrypted objects.

Additionally there are management problems. For instance if a user uses multiple tools to manage S3 objects - e.g. mc and AWS CLI. If the users changes the SSE-C key for an object using AWS CLI there is no way mc can detect that. So the entries in `.mc/credentials/` may become stale.

However, it is already possible to do exactly what you're describing using some shell magic:
Let's assume you have a file of SSE-C keys `ssec.keys` of the following format:
```
s3/my-bucket-1=32byteslongsecretkeymustbegiven1
s3/my-bucket-2=32byteslongsecretkeymustbegiven2
...
```
Now you can:
- Create an object using:
 `mc cp --encrypt-key "$(cat ssec.keys | grep s3/my-bucket-1)" some-file s3/my-bucket-1/object`
- Download an object using:
  `mc cat --encrypt-key "$(cat ssec.keys | grep s3/my-bucket-1)" s3/my-bucket-1/object`
...

Of course you can also use awk/sed to do more advanced filtering/matching...

**Comment by harshavardhana** [comment]
I think it is not a good idea to add SSE-C creds in a file which can be read and copied. We shouldn't need to bring any special semantics here. `mc` is good the way it is - there is another SSE PR pending https://github.com/minio/mc/pull/2626 which would not even require SSE-C

**Comment by arno01** [comment]
@aead thanks for the shell magic, I am already using that in combination with the GNU [pass](https://www.passwordstore.org/), e.g. ``--encrypt-key "$(pass show backups/tablet)"``

With your example ``cat ssec.keys | grep s3/my-bucket-1``, it is no different from storing keys in a file (in a plaintext).

This is usually why people use LUKS to encrypt their data at REST.
Be there an intruder, he will snoop the keys from the clipboard, the tty, over a shoulder..
Of course, in the perfect world the ``~/.mc/credentials/<host>.json`` could be encrypted with the user provided key to ensure a higher level of security such as encryption of SSH/GPG keys.

My idea was that instead of using shell magic, users could just ``mc cp -r ~/photos minio/photos`` without the need of thinking on where their keys are and whether they are using the correct keys as they might end up with their objects encrypted with different keys. (you have mentioned pretty much same about stale keys).

That was just an idea, if the majority do not like it, I am fine to have this issue closed ;)
