### ISSUE TITLE
Update readme file with ppc64le binary

### ISSUE THREAD

**Issue by mkumatag** [minio/mc#2644]
Currently, I see minio client binary is already published for ppc64le but readme is not updated with the relevant link, this task is for updating the readme file with a proper link.

Reference: https://github.com/minio/minio/issues/7062#issuecomment-452970812

Readme link - https://github.com/minio/mc#gnulinux

Readme has been already fixed for [minio/minio project](https://github.com/minio/minio/issues/7063).

**Comment by kannappanr** [comment]
@mkumatag We will add a link to the ppc binary.
