### ISSUE TITLE
Consider password prompt or env variable when using mc admin user add

### ISSUE THREAD

**Issue by zefie** [minio/mc#2651]
## Info
When adding a user using MC, we have to provide the access secret on the CLI. Minio sometimes (depending on setup, usually on distributed) can take upwards to 20 seconds to respond. During this time, the password is shown in ```ps aux``` for any user with access to the machine to see.

## Expected behavior
Ability to securely add users

## Actual behavior
Password can be exposed in running process list if task takes longer than expected

## Possible solution
Environment variable for automation, user password prompt for interactive setup.

## Steps to reproduce the behavior
1. Set up a Minio, the slower the system the better but doesn't matter for this test case
2. add a user and ps aux | grep mc (eg ```mc admin user add zefie test testpassword readonly & ps aux | grep mc```)
[1] Password is exposed in process list (eg ```root     24913  0.0  0.0 445900 14460 pts/2    Rl   14:00   0:00 mc admin user add zefie test testpassword readonly```

## mc version
- DEVELOPMENT.GOGET ;) ... realistically 0854af6e6d3e9f79e8d9c98db5e0d133a527923b

## System information
* Server type and version: Debian Linux 9 x86_64
* Operating System and version (`uname -a`): Linux s3 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@zefie Will check internally on this request. Meanwhile you can also use

`mc config host add mys3 http://localhost:9000 access secret --api "s3v4"`

**Comment by harshavardhana** [comment]
We have something similar for `mc config host add` we can do something similar for `mc admin user add`

**Comment by deekoder** [comment]
We will put this in the futures milestone for now till we discuss this internally.

**Comment by kannappanr** [comment]
> @zefie Will check internally on this request. Meanwhile you can also use
> 
> `mc config host add mys3 http://localhost:9000 access secret --api "s3v4"`

Sorry, missed that you had specifically asked about `mc admin user add`

**Comment by sinhaashish** [comment]
@harshavardhana running the `config host add ` command do show the access and secret key 
```
ashish@minio:~/code/go/src/github.com/minio/mc$ ./mc config host add myminio http://192.168.86.149:9000 minio minio123 & ps aux | grep mc
[1] 3993
Added `myminio` successfully.
ashish    3995  0.0  0.0  21536  1028 pts/0    S+   13:11   0:00 grep --color=auto mc
[1]+  Done                    ./mc config host add myminio http://192.168.86.149:9000 minio minio123
```

IMO its not wise to have a prompt for access key and secret key as in that case it will get tough to use `mc` programmatically.

**Comment by harshavardhana** [comment]
this has been fixed already and released.
