### ISSUE TITLE
Quiet should print only in the case of errors

### ISSUE THREAD

**Issue by kannappanr** [minio/mc#2666]
## Expected behavior
Quiet should not only disable progress bar display as explained in mc help, but also not display any of the success messages. Should only display messages in case of failure. We should also check with @abperiasamy 

## Actual behavior
Currently `quiet` flag only disables progress bar messages.

**Comment by harshavardhana** [comment]
blocked on discussion..

**Comment by kannappanr** [comment]
Closing the issue based on the explanation given above.
