### ISSUE TITLE
Need better error message for failing to add user when access key is equal to user name

### ISSUE THREAD

**Issue by eco-minio** [minio/mc#2670]
## Expected behavior
Non critical issue, just filing for better inline help.  When adding a new user, the username cannot be the same as the access key (expected behavior).  
```
mc admin user add min minio minio123 readonly
mc: <ERROR> Cannot add new user. Invalid Request.
```
We should be a bit more exact as to the reason, something like "Cannot add new user, username may not be the same as access key"

## Steps to reproduce the behavior
1. `export MINIO_ACCESS_KEY=minio; export MINIO_SECRET_KEY=b1gsecret; minio server /data;`
2. `mc admin user add myminio minio userpass readonly`

## mc version
- (paste output of `mc version`)
mc version
Version: 2019-01-30T19:57:22Z
Release-tag: RELEASE.2019-01-30T19-57-22Z
Commit-id: 75a36b4831c35ebf7cb15ca9e617f057c7729b6f

## System information
N/A

**Comment by Praveenrajmani** [comment]
@kannappanr , I see that this has to be fixed in server code. Shall we move this to `minio/minio`?

**Comment by harshavardhana** [comment]
What is the `--debug` output here? @Praveenrajmani

**Comment by Praveenrajmani** [comment]
@harshavardhana , i see `400 Bad Request` with `{"Code":"InvalidRequest","Message":"Invalid Request","Resource":"/minio/admin/v1/add-user","RequestId":"158010C3D4C181F8","HostId":"3L137"}
`

![image](https://user-images.githubusercontent.com/5410427/52191079-d6627f80-2868-11e9-83c0-75eba49e95b8.png)

**Comment by Praveenrajmani** [comment]
@nitisht  Shall we close this issue ?

**Comment by nitisht** [comment]
Fixed by https://github.com/minio/minio/pull/7190
