### ISSUE TITLE
mc mirror (and diff) confused when srcpath/<name>.xyz and srcpath/<name>/ exist

### ISSUE THREAD

**Issue by eborisch** [minio/mc#2686]
## Expected behavior
`mc mirror local_dir/ s3dest/bucket/path/to/remote_dir`
...let finish...
`mc mirror local_dir/ s3dest/bucket/path/to/remote_dir`
Expect no changes / resends

## Actual behavior
`mc: <ERROR> Failed to copy 'local_dir/LLS.png\'. Object already exists.`

The `LLS.png` object _does_ exist (shows up in `mc ls ...`; has proper size & hash; can be retrieved) in the remote destination after the initial mirror, as does `remote_dir/LLS/` (directory). `mc diff ...` also lists `LLS.png` as (erroneously) missing from the remote.

Generically, any time (that I've tested) `<name>.<foo>` and `<name>/` exist side-by-side, while mirror successfully copies them both, on updates, it acts like `remote/.../<name>.<foo>` isn't there, and then tries (and errors, because it _is_ there) to send again.

## Steps to reproduce the behavior
```sh
mkdir -p testdir/foo
touch testdir/foo.bar testdir/foo/item
mc mirror testdir/ remote/bucket/testing
mc mirror testdir/ remote/bucket/testing
```

Will return:
`mc: <ERROR> Failed to copy 'testdir/foo.bar'. Object already exists.`

## mc version
mc version RELEASE.2019-02-06T20-26-56Z

## System information

Darwin _hostname_ 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64

[Edit: typos]

**Comment by harshavardhana** [comment]
// cc @vadmeste

**Comment by eborisch** [comment]
This may to be due (in part) to the HCP backend I'm testing against; it is returning directory names in the listings, which I'm guessing is tripping things up:

(the first is against a minio server, the second against HCP)

```
$ mc ls --json --recursive miniotest/test/testdir/
{"status":"success","type":"file","lastModified":"2019-02-13T14:51:40.037-06:00","size":8,"key":"foo.bar","etag":"9d20b255a723d8e5c8389068961d780a"}
{"status":"success","type":"file","lastModified":"2019-02-13T14:51:40.037-06:00","size":12,"key":"foo/item","etag":"1fac5a0078b77aa765f968910e114f30"}
$ mc ls --json --recursive hcptest/test/testdir/
{"status":"success","type":"file","lastModified":"2019-02-13T13:16:43.058-06:00","size":0,"key":"","etag":"d41d8cd98f00b204e9800998ecf8427e"}
{"status":"success","type":"file","lastModified":"2019-02-13T13:18:13.821-06:00","size":0,"key":"foo/","etag":"d41d8cd98f00b204e9800998ecf8427e"}
{"status":"success","type":"file","lastModified":"2019-02-13T14:52:25.678-06:00","size":12,"key":"foo/item","etag":"1fac5a0078b77aa765f968910e114f30"}
{"status":"success","type":"file","lastModified":"2019-02-13T14:52:25.654-06:00","size":8,"key":"foo.bar","etag":"9d20b255a723d8e5c8389068961d780a"}
```

Time to go see if there is a config bit to fiddle with....

I would still say this shouldn't result in the behavior above with mirror and diff.

**Comment by harshavardhana** [comment]
An S3 incompatible output @eborisch will result in different behavior, we only test with S3 and Minio - other S3 compatible backends may have issues if they diverge from expected behavior.

**Comment by eborisch** [comment]
No problem. Sorry for the noise.

**Comment by harshavardhana** [comment]
> {"status":"success","type":"file","lastModified":"2019-02-13T13:16:43.058-06:00","size":0,"key":"","etag":"d41d8cd98f00b204e9800998ecf8427e"}

This is clearly a bug @eborisch in a list operation key can never be empty.

**Comment by eborisch** [comment]
Related: is there a way to have mc dump the actual response as part of --debug? It has the header, but not the contents.

**Comment by eborisch** [comment]
With `awscli`, I can see that the list operation is returning keys that have values, but when the prefix  (and /) is pruned, it will become empty:

```
eborisch@R5038979 ~/d/minio> aws s3api list-objects-v2 --bucket=test --prefix=testdir
{
    "Contents": [
        {
            "LastModified": "2019-02-13T19:16:43.058Z",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "StorageClass": "STANDARD",
            "Key": "testdir/",
            "Size": 0
        },
        {
            "LastModified": "2019-02-13T19:18:13.821Z",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "StorageClass": "STANDARD",
            "Key": "testdir/foo/",
            "Size": 0
        },
        {
            "LastModified": "2019-02-13T20:52:25.678Z",
            "ETag": "\"1fac5a0078b77aa765f968910e114f30\"",
            "StorageClass": "STANDARD",
            "Key": "testdir/foo/item",
            "Size": 12
        },
        {
            "LastModified": "2019-02-13T20:52:25.654Z",
            "ETag": "\"9d20b255a723d8e5c8389068961d780a\"",
            "StorageClass": "STANDARD",
            "Key": "testdir/foo.bar",
            "Size": 8
        }
    ]
}
```

Not your problem, but for reference. ;)
