### ISSUE TITLE
Can't install as name clashes

### ISSUE THREAD

**Issue by luckydonald** [minio/mc#2688]
## Expected behavior
Can install it as a long name like `minio-client`, and only link it as `mc` if not present.

## Actual behavior
```
Error: Cannot install minio/stable/mc because conflicting formulae are installed.
  midnight-commander: because Both install a `mc` binary
```
## Steps to reproduce the behavior
```bash
brew install minio/stable/mc
```

## mc version
None

## System information
Mac OS 10.9.5

**Comment by harshavardhana** [comment]
This is expected, you can download the binary here 

https://dl.minio.io/client/mc/release/darwin-amd64/mc

And then rename 

```
mv ./mc ./mcli
```

Our stand on why we can't change the project name is listed here https://github.com/minio/mc/blob/master/CONFLICT.md

**Comment by kannappanr** [comment]
@luckydonald Closing this issue based on the feedback from @harshavardhana . Please feel free to reach out to us if you have other questions.
