### ISSUE TITLE
Error when attempting to transfer from GCP to S3

### ISSUE THREAD

**Issue by p-doyle** [minio/mc#2690]
I am attempting to transfer a GCP storage bucket to S3 using the following command with the Windows CLI exe:
`mc.exe cp -r gcs/takeout-export-123/ s3/my-bucket/`

It seems to start transferring but then throws this error:

`mc.exe: <ERROR> Failed to copy https://storage.googleapis.com/takeout-export-123/20190215T172254Z/Resource-456/takeout-20190215T172258Z-001.zip. Expires unsupported user defined metadata name`

## Your Environment
Version: 2019-02-13T19:48:27Z
Release-tag: RELEASE.2019-02-13T19-48-27Z
Commit-id: bc1a108e5c8f3c2a9e25ed34ff221985987b3fed
Windows 10 Pro 64-bit

**Comment by poornas** [comment]
Can you run this with --debug flag and post the trace?
`mc.exe cp -r gcs/takeout-export-123/ s3/my-bucket/ --debug`

**Comment by p-doyle** [comment]
So I actually had to move --debug to before -r as when I append it to the command I get:
`mc.exe: <ERROR> Unable to guess the type of copy operation. Invalid arguments provided, please refer mc <command> -h for relevant documentation.`

Anyway here is the trace:

```
ERROR> Failed to copy `https://storage.googleapis.com/takeout-export-123/20190215T172254Z/Resource-456/takeout-20190215T172257Z-001.zip`. Expires unsupported user defined metadata name
 (3) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/cp-main.go:415 cmd.doCopySession(..) Tags: [https://storage.googleapis.com/takeout-export-123/20190215T172254Z/Resource-456/takeout-20190215T172257Z-001.zip]
 (2) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/common-methods.go:252 cmd.uploadSourceToTargetURL(..) Tags: [https://s3.amazonaws.com/my-bucket/20190215T172254Z/Resource-456/takeout-20190215T172257Z-001.zip]
 (1) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/common-methods.go:178 cmd.putTargetStream(..) Tags: [s3, https://s3.amazonaws.com/my-bucket/20190215T172254Z/Resource-456/takeout-20190215T172257Z-001.zip]
 (0) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/client-s3.go:758 cmd.(*s3Client).Put(..)
 Release-Tag:RELEASE.2019-02-13T19-48-27Z | Commit:bc1a108e5c8f | Host:ITWORKED | OS:windows | Arch:amd64 | Lang:go1.11.4 | Mem:3.0MB/12MB | Heap:3.0MB/7.1MB
```
