### ISSUE TITLE
mc mb autocomplete adds additional whitespace

### ISSUE THREAD

**Issue by eco-minio** [minio/mc#2693]
## Expected behavior
No whitespace should be added after the autocomplete so that you can instantly type the bucket name.
## Actual behavior
When using new autocomplete feature, `mc mb pl<tab complete>` will fill as `mc mb play/ `.  The extra whitespace has to be deleted to add the bucket name.
## Steps to reproduce the behavior
Press tab after autocompleting `mc mb`.
## mc version
```
Version: 2019-02-20T22:21:50Z
Release-tag: RELEASE.2019-02-20T22-21-50Z
Commit-id: e538599e2ffa4ee8d8040d5cd14475b380da531a
```
## System information
N/A

**Comment by vadmeste** [comment]
This will be fixed after we redo the autocomplete without posener/complete.
