### ISSUE TITLE
mc cp autocomplete does not expand ~/

### ISSUE THREAD

**Issue by eco-minio** [minio/mc#2694]
## Expected behavior
When using autocomplete for mc commands, ~/ should expand to users home directory
## Actual behavior
Tab autocomplete does not expand ~/
## Steps to reproduce the behavior
`mc cp ~/Down<tab>` to try and expand to /home/user/Downloads
## mc version
```
mc version
Version: 2019-02-20T22:21:50Z
Release-tag: RELEASE.2019-02-20T22-21-50Z
Commit-id: e538599e2ffa4ee8d8040d5cd14475b380da531a
```
## System information
N/A

**Comment by moonsn** [comment]
not work too

mc --autocompletion                                                                                        
mc: autocompletion is already enabled in your '$SHELLRC'

Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e
