### ISSUE TITLE
mc admin monitor does not autocomplete targets

### ISSUE THREAD

**Issue by eco-minio** [minio/mc#2695]
## Expected behavior
`mc admin monitor<tab>` should automatically list all target clusters, play/, s3/, etc...
## Actual behavior
Does not automatically expand targets
## Steps to reproduce the behavior
`mc admin monitor<tab>`
## mc version
```
mc version
Version: 2019-02-20T22:21:50Z
Release-tag: RELEASE.2019-02-20T22-21-50Z
Commit-id: e538599e2ffa4ee8d8040d5cd14475b380da531a
```
## System information
N/A

**Comment by harshavardhana** [comment]
This command is GA ready yet I think and going through some changes // cc @wlan0 can fill in

**Comment by kannappanr** [comment]
Closing this issue as `admin monitor` command is going to be merged into `admin info` command.
