### ISSUE TITLE
mc shows incorrect number of files transferred until all uploads have completed

### ISSUE THREAD

**Issue by eco-minio** [minio/mc#2696]
## Expected behavior
mc should show the current file it is transferring
## Actual behavior
mc displays files that have no been transferred yet
## Steps to reproduce the behavior
Create a directory with 100k empty files, e.g., file-000001 - file-100000
`mc cp -r local_foo/ myminio/bucket`.  Within a few seconds it will show it has transferred 99,999 of the files, then hangs.  If you do the same operation with the `--quiet` flag you can see that it is actually transferring files in the background, so just a cosmetic bug
## mc version
```
Version: 2019-02-20T22:21:50Z
Release-tag: RELEASE.2019-02-20T22-21-50Z
Commit-id: e538599e2ffa4ee8d8040d5cd14475b380da531a
```
## System information
Ubuntu 18.04-2

**Comment by deekoder** [comment]
@eco-minio  we will work on this in the future after we are done with our current priorities. I will put it in future and reactivate it when we have more bandwidth to take this on.
