### ISSUE TITLE
Include whether a heal is purposefully paused in the base heal output

### ISSUE THREAD

**Issue by ryjose1** [minio/mc#2698]
## Expected behavior
Running `mc admin heal -r <target>` will have output that will help determine whether minio is hung or is paused on purpose
## Actual behavior
Running `mc admin heal -r <target>` only displays the bucket/object that is up for healing , the objects healed/total, the bytes parsed, the time elapsed, and the ratios of the object's status levels
## Steps to reproduce the behavior
1. Start minio
2. Bombard it with requests enough to trigger the "pause healing" condition
3. Heal the cluster 
## mc version
Version: 2018-09-10T23:39:12Z
Release-tag: RELEASE.2018-09-10T23-39-12Z
Commit-id: c352cadd4be2c6bed64884c78d1e8a8ac6efaf3f
## System information
*Environment name and version: Docker 17.09.0-ce
*Server type and version: CentOS 7
*Operating System and Version: Linux 4.18.12-1.el7.elrepo.x86_64 #1 SMP Thu Oct 4 09:36:51 EDT 2018 x86_64 GNU/Linux
## Context
I was asked to put up an issue after asking in [this thread](https://minio.slack.com/archives/C3NDUB8UA/p1551207150315600)
When attempting a heal on my cluster, it spent ~four hours healing on the bucket before moving onto the objects in the bucket. It would be helpful to have more info in the base heal output for how the progress is going/info that could help determine if the heal is hung.
As a specific example, a thread from earlier today mentioned that [healing pauses itself when the server is busy](https://minio.slack.com/archives/C3NDUB8UA/p1551195314287400?thread_ts=1551194958.286600&cid=C3NDUB8UA) .
In cases where it is paused, a status on the output saying that the hang up is on purpose would be helpful, diagnostics-wise
Thanks

**Comment by kannappanr** [comment]
@rajose Thanks for filing this issue. We will discuss internally and try to add a status message in case of these sorts of pause.

**Comment by kannappanr** [comment]
@rajose Sorry for getting back late. We do not have a pause as such in heal. It is just that when I/O activity happens, like putobject and getobject calls, I/O activity gets precedence. Let us say we send a status message saying that it is paused, by that time it would have resumed healing, so you will end up seeing a lot of these messages.

**Comment by kannappanr** [comment]
Closing this issue as answered. Please feel free to reach out to us if you have further questions.
