### ISSUE TITLE
Error trying to autocomplete via mc when prefaced with time command

### ISSUE THREAD

**Issue by eco-minio** [minio/mc#2704]
## Expected behavior
mc should gracefully autocomplete or not autocomplete when `time` command is used before mc
## Actual behavior
When you use `time mc cp<tab>`, you see the following error:
```
time mc cpbash: compgen: warning: -C option may not work as you expect
```
## Steps to reproduce the behavior
Use time before mc then try to autocomplete

## mc version
```
Version: 2019-02-27T18:44:28Z
Release-tag: RELEASE.2019-02-27T18-44-28Z
Commit-id: bd5372f165a5f5fb59aab1b68c6d4c693e9de282
```
## System information
Ubuntu 18.04

**Comment by harshavardhana** [comment]
> ```
> time mc cpbash: compgen: warning: -C option may not work as you expect
> ```

This is a limitation of bash `compgen`  and our autocomplete library - there is nothing we can here @eco-minio
