### ISSUE TITLE
Socket timeout when copying large files

### ISSUE THREAD

**Issue by p-doyle** [minio/mc#2707]
## mc version
Version: 2019-03-06T18:41:35Z
Release-tag: RELEASE.2019-03-06T18-41-35Z
Commit-id: b3229507a94c27ce51cfc7cde6710f26ebb41657

## System information
Win 10 Pro 
Version	10.0.17134 Build 17134

I am attempting to transfer 1.63 TB worth of files from GCP to S3 using the following command:
mc.exe cp -r gcs/takeout-export-123/ s3/my-bucket/

After a few minutes I receive a timeout error.  I can resume the session but it seems to assume that it finished transferring the last file, which it did not.  The file it timed out on was 3.61 GB.  Here is the debug output:

```
mc.exe: <ERROR> Failed to copy `https://storage.googleapis.com/takeout-export-123/largefile.zip`. Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
 (3) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/cp-main.go:416 cmd.doCopySession(..) Tags: [https://storage.googleapis.com/takeout-export-123/largefile.zip]
 (2) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/common-methods.go:252 cmd.uploadSourceToTargetURL(..) Tags: [https://s3.amazonaws.com/my-bucket/largefile.zip]
 (1) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/common-methods.go:178 cmd.putTargetStream(..) Tags: [s3, https://s3.amazonaws.com/my-bucket/largefile.zip]
 (0) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/client-s3.go:758 cmd.(*s3Client).Put(..)
 Commit:b3229507a94c | Release-Tag:RELEASE.2019-03-06T18-41-35Z | Host:ITWORKED | OS:windows | Arch:amd64 | Lang:go1.11.4 | Mem:121MB/407MB | Heap:121MB/388MB
```

Any ideas?

Thank you!

**Comment by kannappanr** [comment]
@p-doyle We will reproduce this issue and get back to you for more info. but in general it looks like we do not retry on error in this case.

**Comment by Kenvelo90** [comment]
I'm experiencing the same issue for large files (~10g)
can we configure the timeout? @kannappanr

**Comment by harshavardhana** [comment]
What is the server here ?

**Comment by Kenvelo90** [comment]
@harshavardhana 
google storage to S3

**Comment by ebozduman** [comment]
@p-doyle & @Kenvelo90 ,

With the provided information, we cannot reproduce the issue.

Could you please give us more information on how MinIO is/was involved in your setup?
Do you reach `gcs` and `s3` buckets and objects directly or through MinIO?

**Comment by kannappanr** [comment]
Closing the issue as stale. Please feel free to reach out to us when you have the information requested
