### ISSUE TITLE
mc rm <alias/bucket_name> gives user the wrong success impression

### ISSUE THREAD

**Issue by ebozduman** [minio/mc#2710]
## Expected behavior
`mc rm <alias/bucket_name>` errors out with a meaningful message, like `rm expects an object name or ---recursive option to clean up the whole bucket content`.

## Actual behavior
`mc rm <alias/bucket_name>` does not error out but the following message in green is shown to the user giving the user a wrong impression as if the removal process is successful. 
`Removing '<alias/bucket_name>'.`
If the bucket and its content are checked with `mc ls <alias/bucket_name>`, the bucket and its content are still there untouched.

## Steps to reproduce the behavior
`mc rm <alias/bucket_name>`

## mc version
$ mc version
Version: 2019-03-08T09:32:30Z
Release-tag: DEVELOPMENT.2019-03-08T09-32-30Z
Commit-id: 2d07e36a593c193de443b761788167a001d56000

**Comment by sinhaashish** [comment]
We can close this issue as [PR](https://github.com/minio/mc/pull/2700) caters this issue.
The new error message `Target <<server_alias/bucketname>> not found`  is much apt than the earlier message which was `Removing '<alias/bucket_name>`.

**Comment by nitisht** [comment]
fixed by https://github.com/minio/mc/pull/2700
