### ISSUE TITLE
'mc ls <alias> --recursive' does not list empty buckets

### ISSUE THREAD

**Issue by ebozduman** [minio/mc#2711]
## Expected behavior
`mc ls <alias> --recursive`mc version should list buckets and their contents recursively as well as the buckets that are empty

## Actual behavior
`mc ls <alias> --recursive` lists only the buckets that have objects

## Steps to reproduce the behavior
Create an empty bucket and some buckets with couple of objects in them and run the following command:
`mc ls <alias> --recursive`
The output does not list the empty bucket

## mc version
$ mc version
Version: 2019-03-08T09:32:30Z
Release-tag: DEVELOPMENT.2019-03-08T09-32-30Z
Commit-id: 2d07e36a593c193de443b761788167a001d56000

**Comment by kannappanr** [comment]
@ebozduman Let's discuss internally.

**Comment by harshavardhana** [comment]
This is on purpose recursive listing only lists objects

**Comment by ebozduman** [comment]
I checked `aws s3 ls --recursive` command output, but its design/behavior is completely different than our design and regular ls (Linux/Unix) command design.

Although, our design is also not the same with the common (Linux/Unix) ls command design (listing everything including empty buckets), it is deliberately implemented this way to avoid having 2 versions of ls command, one for regular listing function, the other one for mirror functionality which requires full address of the objects. 

The strongest argument about keeping it this way is the fact that no customer has ever complained about it until this point. 
So, we'll keep it as is for the time-being and then we'll revisit this subject if any complaints comes in the future.
