### ISSUE TITLE
Deleted objects not syncing across servers after mc heal with --remove flag

### ISSUE THREAD

**Issue by adiospeds** [minio/mc#2713]
## Steps to reproduce the behavior
It seems heal doesn't sync deleted objects on federated cluster.
I stopped minio server on one of my 16 instances (lets call this faulty instance)
then deleted some existing objects from GUI
then turned on the minio server on the faulty instance 
then ran the command `mc admin heal -r --remove m2` on the faulty instance 
Objects that were deleted throughout the cluster were not deleted from the faulty instance even after heal command was completed.

## mc version
Version: 2019-03-06T18:41:35Z
Release-tag: RELEASE.2019-03-06T18-41-35Z
Commit-id: b3229507a94c27ce51cfc7cde6710f26ebb41657

## System information
Linux myserver 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adiospeds** [comment]
@nitisht confirmed this, by checking locally on his machine.

**Comment by harshavardhana** [comment]
Yes this is expected, --remove is only for situations when an object looses quorum or becomes dangling while the heal list is being built.

You don't need --remove dangling entries all you have to do is `mc rm -r --force` it will remove the dangling files.

**Comment by adiospeds** [comment]
So, if I have objects on the faulty server which are deleted throughout the cluster - do I have to manually delete them one by one?
`mc rm -r --force list-of-objects-to-be-deleted`

**Comment by kannappanr** [comment]
As of now, `mc -r --force` will only work on a `directory` level within a `bucket`, and if you do not have a directory and if it is just an object under a bucket, this will not work.

**Comment by kannappanr** [comment]
@adiospeds Closing this issue now. Please let us know if you need further clarification.
