### ISSUE TITLE
JSON output broken

### ISSUE THREAD

**Issue by bclermont** [minio/mc#2715]
command I run is: `mc ls target/ --json --no-color`

output of version `RELEASE.2019-02-27T18-44-28Z`

```
{"status":"success","type":"folder","lastModified":"2018-08-31T14:08:36Z","size":0,"key":"backup/","etag":""}
{"status":"success","type":"folder","lastModified":"2018-08-23T07:09:09.39Z","size":0,"key":"assets/","etag":""}
```

since `RELEASE.2019-03-06T18-41-35Z` output is:

```
{
 "status": "success",
 "type": "folder",
 "lastModified": "2018-08-31T14:08:36Z",
 "size": 0,
 "key": "backup/",
 "etag": ""
}
{
 "status": "success",
 "type": "folder",
 "lastModified": "2018-08-23T07:09:09.39Z",
 "size": 0,
 "key": "assets/",
 "etag": ""
}
```

making it impossible to parse lines, breaking the whole purpose of json output

**Comment by vadmeste** [comment]
@bclermont if you redirect the output, such as to a pipe, then you will still have one JSON document per line.

Can you check that and update us if you still face a problem with your use case ?

**Comment by bclermont** [comment]
ah you're right... it's annoying because I wanted to parse the output using python.
like that:

```python
import subprocess

import json

def run_mc(*args):
    """
    run minio client with the specified arguments and return the json output
    """
    cmd = ["mc"] + list(args) + ["--json", "--no-color"]
    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE)
    proc.wait()
    stdout, err = proc.communicate()
    output = []
    for line in stdout.decode("utf-8").splitlines():
        try:
            output.append(json.loads(line))
        except Exception as err:
            print("Can't parse line: %s\n" % err)
            print(line)
    return output
```

and when I pipe it a buffer and read it, it's broken.

so, I guess I must redirect to a file and read that file...

IMHO,  if the combination of `--json --no-color` it should behave like if there is no tty to write to

**Comment by vadmeste** [comment]
@bclermont I am not sure I understand, the python script works as expected, right ?

**Comment by bclermont** [comment]
weird, it works now... sorry, close the task

BTW, I use python and json because the admin functions are not available through the golang API :(

**Comment by harshavardhana** [comment]
@bclermont you mean this ? https://github.com/minio/minio/tree/master/pkg/madmin

**Comment by bclermont** [comment]
@harshavardhana I was looking into `minio/minio-go` :(
thank you!
