### ISSUE TITLE
Please provide way to configure log output for scripts

### ISSUE THREAD

**Issue by cbluth** [minio/mc#2719]
## Context
I use the minio client in scripts, and some of my tasks are very long-running (lots of data to transfer). So, naturally, I want to log the output to a file, something like this `mc <command such as mirror> |& tee -a /path/to/log`. Then, throughout the day, I will periodically check on the log to see how its doing.
Using the `--json` or `-q` arguments makes the output too silent to check on progress of the transfer.
Using the default output makes the logs unreadable in a log file, not to mention that it also cuts off important information like filenames and such.

## Expected behavior
I would like to use `mc` in long running scripts and be able to check the logs periodically.

## Actual behavior
I can use `mc` in long running scripts, but the output is unpalatable.

## Steps to reproduce the behavior
 `mc <command such as mirror> |& tee -a /path/to/log`
or
 `mc --json <command such as mirror> |& tee -a /path/to/log`

## mc version
```
# mc version
Version: 2019-03-13T21:05:06Z
Release-tag: RELEASE.2019-03-13T21-05-06Z
Commit-id: ecfd4526a3b6071330a0093c80815b59d451afd0
```
## System information
Ubuntu 16.04

**Comment by vadmeste** [comment]
@cbluth what mc command are you running ?

**Comment by cbluth** [comment]
I am now running this:
> for i in `ls` ; do time mc --json mirror ./${i} new-minio/ |& tee -a /root/minio-sync-log ; done

I was running this:
> for i in `ls` ; do time mc mirror ./${i} new-minio/ |& tee -a /root/minio-sync-log ; done

And this:
> for i in `ls` ; do time mc -q mirror ./${i} new-minio/ |& tee -a /root/minio-sync-log ; done


^ all of these produce logs that are unreadable.

**Comment by vadmeste** [comment]
> for i in `ls` ; do time mc --json mirror ./${i} new-minio/ |& tee -a /root/minio-sync-log ; done

This works for me, are you saying that you fixed the issue?

**Comment by cbluth** [comment]
> > for i in `ls` ; do time mc --json mirror ./${i} new-minio/ |& tee -a /root/minio-sync-log ; done
> 
> This works for me, are you saying that you fixed the issue?

The issue still persists. Please see the context section of the issue.
The logs are awful.

**Comment by kannappanr** [comment]
@cbluth Can you please try with the `-q` flag? 

Here is a sample output
```
`/tmp/vscode-gov3kR8e/go-code-check` -> `x1minio/kannappan102/vscode-gov3kR8e/go-code-check`
`/tmp/vscode-typescript/tscancellation-40b84582de9612d0e5d6.tmp16` -> `x1minio/kannappan102/vscode-typescript/tscancellation-40b84582de9612d0e5d6.tmp16`
`/tmp/vscode-typescript/tscancellation-40b84582de9612d0e5d6.tmp17` -> `x1minio/kannappan102/vscode-typescript/tscancellation-40b84582de9612d0e5d6.tmp17`
`/tmp/vscode-typescript/tscancellation-40b84582de9612d0e5d6.tmp21` -> `x1minio/kannappan102/vscode-typescript/tscancellation-40b84582de9612d0e5d6.tmp21`
`/tmp/winstone984190527159250419.jar` -> `x1minio/kannappan102/winstone984190527159250419.jar`
`/tmp/vscode-typescript/tscancellation-40b84582de9612d0e5d6.tmp6` -> `x1minio/kannappan102/vscode-typescript/tscancellation-40b84582de9612d0e5d6.tmp6`
`/tmp/x1minio/kannappan102/.X1024-lock` -> `x1minio/kannappan102/x1minio/kannappan102/.X1024-lock`
`/tmp/x1minio/kannappan102/1/.minio.sys/config/config.json/part.1` -> `x1minio/kannappan102/x1minio/kannappan102/1/.minio.sys/config/config.json/part.1`
`/tmp/x1minio/kannappan102/.com.google.Chrome.AeFOih` -> `x1minio/kannappan102/x1minio/kannappan102/.com.google.Chrome.AeFOih`
`/tmp/x1minio/kannappan102/1/.minio.sys/config/config.json/xl.json` -> `x1minio/kannappan102/x1minio/kannappan102/1/.minio.sys/config/config.json/xl.json`
`/tmp/x1minio/kannappan102/1/.minio.sys/format.json` -> `x1minio/kannappan102/x1minio/kannappan102/1/.minio.sys/format.json`
`/tmp/x1minio/kannappan102/1/.minio.sys/multipart/090a5b745cdf3eb78650377f4d789bb5d8d337319d55cea93003df9986a8305b/52c7a1b7-ff1e-4e48-bb59-c40d3b5d7ca2/xl.json` -> `x1minio/kannappan102/x1minio/kannappan102/1/.minio.sys/multipart/090a5b745cdf3eb78650377f4d789bb5d8d337319d55cea93003df9986a8305b/52c7a1b7-ff1e-4e48-bb59-c40d3b5d7ca2/xl.json`
Total: 83.12 MB, Transferred: 83.12 MB, Speed: 754.42 MB/s
```

If not can you let us know how you would expect the output to be, I can go over it internally and get back to you.

**Comment by cbluth** [comment]
I ended up changing it a bit and i am now using `s3fs` and `rsync`, it provides logs good enough for me to use.
