### ISSUE TITLE
how to mirror or copy files based on checksum

### ISSUE THREAD

**Issue by hosnas** [minio/mc#2721]
Sorry If I'm asking this question in the wrong place. 

I want to transfer files based on checksum (not based on modification time or size) . What should I do to achieve this? I checked the normal behavior and it didn't compare checksum while transferring files.

**Comment by harshavardhana** [comment]
It's not possible our behavior is similar to `aws sync`  - modtime and size are used to compare and copy.

**Comment by hosnas** [comment]
@harshavardhana  not possible at all? or its not implemented yet? cause s3cmd and rclone can simply do it. 
I was very disappointed by this behavior. I transferred a folder to my bucket. them copied that folder to another place in my local then tried to transfer the copy to same bucket. All files were transferred again just because modification times were altered.

**Comment by harshavardhana** [comment]
Checksum involves downloading data on both ends, mc is not just about copying from local folder  to object storage. But copying PetaByte worth of contents from one object storage to another so technically it's not feasible.

S3cmd and rclone are good alternatives here.
