### ISSUE TITLE
ignore timestamp checking

### ISSUE THREAD

**Issue by hosnas** [minio/mc#2724]
Is there a way to ignore timestamp checking in cp or mirror? I didn't find anything in logs.

**Comment by kannappanr** [comment]
@hosnas Can you explain your issue in more detail and give some example.  Let's say if you are talking about `cp`, can you give examples, so that it is easier to understand for us.

**Comment by hosnas** [comment]
@kannappanr I'm using jekyll for my website. And I use minio to host the assets. Everytime I'm building my jekyll website, all of the files would be populated in the build folder. So all modification time of the files are changed. In this case I can rely on the file size to not upload everything again to minio. So I need an option to ignore modification time and only upload files to my minio bucket using file size.

**Comment by harshavardhana** [comment]
> @kannappanr I'm using jekyll for my website. And I use minio to host the assets. Everytime I'm building my jekyll website, all of the files would be populated in the build folder. So all modification time of the files are changed. In this case I can rely on the file size to not upload everything again to minio. So I need an option to ignore modification time and only upload files to my minio bucket using file size.

@hosnas Jekyll shouldn't be modifying modTime on all files only which it did modify. Now if it did modify why shouldn't it be copied?

**Comment by hosnas** [comment]
@harshavardhana but I think it does according to this blog post:
https://nathangrigg.com/2012/04/rsyncing-jekyll
Even if it doesn't, modification time is something that could be changed easily. For example lets say I clone my repository to another system and want to build my website, etc.

**Comment by harshavardhana** [comment]
> Even if it doesn't, modification time is something that could be changed easily. For example lets say I clone my repository to another system and want to build my website, etc.

It's not something that can be changed easily, even `size` change changed easily for a file appending a single byte at the end.  That is not a correct example @hosnas `git clone` preserves times.

**Comment by hosnas** [comment]
Are you sure? As far as I can see It changes mtimes and also I found [this question](https://stackoverflow.com/questions/21735435/git-clone-changes-file-modification-time) that confirms it. What I'm missing here? :thinking:

**Comment by kannappanr** [comment]
@hosnas What is the maximum object size? If you are using `mc` and the object sizes are guaranteed to be less than `64MB` and assuming that you are not doing `SSE-C` encryption, then you can do `md5sum` of the objects locally and then get the `ETag` of the corresponding objects from the server and compare them.

**Comment by hosnas** [comment]
@kannappanr my objects are mostly less than 64MB. But not all of them. I'm curious to know how that could be done? 

As far as I searched, mc was first based on filesize only. later modificationtime was added to it. If we were able to choose it optionally, that would have been great.

**Comment by kannappanr** [comment]
I don't think `mc` would handle this, as this is a very specific use case. You will have to write a small program/shell script to do this. 

There are some assumptions being made here, which is you uploaded your objects only via `mc`.

**Comment by kannappanr** [comment]
@hosnas Closing this issue. Please feel free to reach out to us if you still have further questions.

**Comment by hosnas** [comment]
@kannappanr I still believe this should be possible and regard it as a feature request. many other programs have it. for example rclone have it with this flag:

      --size-only                                    Skip based on size only, not mod-time or checksum

in rclone if we add this flag to sync command, it will skipp based on only size.

**Comment by kannappanr** [comment]
@hosnas I can check once more with the team and get back to you.

**Comment by hosnas** [comment]
@kannappanr  any news?

**Comment by hosnas** [comment]
@kannappanr any news?

**Comment by hosnas** [comment]
@kannappanr  Can you please open this issue? I really think its a valid feature request.
