### ISSUE TITLE
Not working behind http_proxy or HTTP_PROXY settings

### ISSUE THREAD

**Issue by perrywang** [minio/mc#2728]
## Expected behavior
working with http_proxy HTTP_PROXY settings
## Actual behavior
with http_proxy execute
mc ls play 
mc: <ERROR> Unable to list folder. Get https://play.minio.io:9000/: Forbidden
if no environment variables all things work well
## Steps to reproduce the behavior
1. set http_proxy or HTTP_PROXY
2. execute ms ls play
## mc version
- (paste output of `mc version`)
Release-tag: RELEASE.2019-03-20T21-29-03Z
Commit-id: 3ea090fe18dd675cd65bd9a5ffb4942d0d9c7a99
## System information
Ubuntu 18.04.2 LTS

**Comment by harshavardhana** [comment]
Can you provide --debug output?

**Comment by perrywang** [comment]
> Can you provide --debug output?
mc: <ERROR> Unable to list folder. Get https://play.minio.io:9000/: Forbidden
 (1) ls.go:135 cmd.doList(..) Tags: [https://play.minio.io:9000/]
 (0) client-s3.go:1793 cmd.(*s3Client).listInRoutine(..)
 Commit:3ea090fe18dd | Release-Tag:RELEASE.2019-03-20T21-29-03Z | Host:aio-test-1 | OS:linux | Arch:amd64 | Lang:go1.11.4 | Mem:3.9MB/72MB | Heap:3.9MB/67MB

**Comment by harshavardhana** [comment]
> mc: Unable to list folder. Get https://play.minio.io:9000/: Forbidden
> (1) ls.go:135 cmd.doList(..) Tags: [https://play.minio.io:9000/]
> (0) client-s3.go:1793 cmd.(*s3Client).listInRoutine(..)
> Commit:3ea090fe18dd | Release-Tag:RELEASE.2019-03-20T21-29-03Z | Host:aio-test-1 | OS:linux | Arch:amd64 | Lang:go1.11.4 | Mem:3.9MB/72MB | Heap:3.9MB/67MB

This looks like your proxy is rejecting the request @perrywang - does your proxy support TLS?

**Comment by kannappanr** [comment]
Ping @perrywang

**Comment by perrywang** [comment]
> > mc: Unable to list folder. Get https://play.minio.io:9000/: Forbidden
> > (1) ls.go:135 cmd.doList(..) Tags: [https://play.minio.io:9000/]
> > (0) client-s3.go:1793 cmd.(*s3Client).listInRoutine(..)
> > Commit:3ea090fe18dd | Release-Tag:RELEASE.2019-03-20T21-29-03Z | Host:aio-test-1 | OS:linux | Arch:amd64 | Lang:go1.11.4 | Mem:3.9MB/72MB | Heap:3.9MB/67MB
> 
> This looks like your proxy is rejecting the request @perrywang - does your proxy support TLS?

sure to support TLS. Actually it is my daily generic proxy I am using it on browser and any other tool npm, curl, yum

**Comment by harshavardhana** [comment]
Looks like it's rejecting the calls, does your proxy support HTTP 2.0 ? If not mc will not work for you.

**Comment by perrywang** [comment]
> Looks like it's rejecting the calls, does your proxy support HTTP 2.0 ? If not mc will not work for you.

Is proxy supporting http 2.0 mandatory？ Can I bypass this with any workaround? Currently I temporally unset these environments before using client. If no this can be closed.

**Comment by harshavardhana** [comment]
It's not possible, because of https requirement.

**Comment by perrywang** [comment]
> It's not possible, because of https requirement.

thanks for patience and closing.
