### ISSUE TITLE
`mc mirror --watch` does not copy files of size 0 bytes

### ISSUE THREAD

**Issue by kfergiani** [minio/mc#2737]
## Expected behavior
All new files are copied from one minio instance to the other
## Actual behavior
Files of size 0 bytes are not copied
## Steps to reproduce the behavior
Run `mc mirror --watch cluster1 cluster2` and upload a 0 byte file to cluster1. Observe that the new file is not present on cluster2
## mc version
- (paste output of `mc version`)
Version: 2019-03-28T20:43:56Z
Release-tag: RELEASE.2019-03-28T20-43-56Z
Commit-id: 7f2770e68f1fa398c2964b3b2655b85823f12868
## System information
centos7 virtual machine

**Comment by poornas** [comment]
@kfergiani , wasn't able to repro this with the mc version above. Can you rerun ```mc mirror --watch --debug cluster1 cluster2``` with --debug flag and then retry the mc cp of zero byte file?  It would be useful to see the trace and double check that the 0-byte file is listed on cluster1 as well.

**Comment by kfergiani** [comment]
![Screenshot 2019-04-02 at 10 44 50](https://user-images.githubusercontent.com/23742930/55393185-acf66500-5534-11e9-8284-45b3f0802038.png)
In the rightmost window I have the UI for cluster1, in the middle window I have the UI for cluster2 and in the iterm window I have the `mc mirror` command that I'm going to run

![Screenshot 2019-04-02 at 10 45 11](https://user-images.githubusercontent.com/23742930/55393274-de6f3080-5534-11e9-9833-e04844f22873.png)
I press enter in the iterm window

![Screenshot 2019-04-02 at 10 45 32](https://user-images.githubusercontent.com/23742930/55393303-eb8c1f80-5534-11e9-8cb8-20c69e82af33.png)
I upload a 0 byte file to cluster1

![Screenshot 2019-04-02 at 10 45 43](https://user-images.githubusercontent.com/23742930/55393323-f6df4b00-5534-11e9-9ede-a67f7d377186.png)
I refresh the UI for cluster2. Observe that there are no files in cluster2
