### ISSUE TITLE
"mc mirror" "mc cp -r" do not copy from bucket with a large number of files. Minio Distributed Mode

### ISSUE THREAD

**Issue by chernykhse** [minio/mc#2751]
## Expected behavior
Files start to copy to destination.
## Actual behavior
the program looks hung, left for a day, copied 200 files, out of more than half a million
## Steps to reproduce the behavior
1. Make a minio cluster of 14 disks and 7 servers.
2. Upload more than half a million files of 300Kb to baket
3. launch MC MIRROR to a folder or in another cluster
## mc version
- (paste output of `mc version`)
Version: 2019-03-20T21:29:03Z
Release-tag: RELEASE.2019-03-20T21-29-03Z
Commit-id: 3ea090fe18dd675cd65bd9a5ffb4942d0d9c7a99

## System information

 uname -a
Linux urudc2f001 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@chernykhse We think it might have something to do with your MinIO setup. Is this on the same setup where you are facing this issue https://github.com/minio/minio/issues/7510

**Comment by chernykhse** [comment]
> @chernykhse We think it might have something to do with your MinIO setup. Is this on the same setup where you are facing this issue [minio/minio#7510](https://github.com/minio/minio/issues/7510)

yes, it is the same setup.

But the problem with the mirror and copying is only on 1 bucket, in others, where there are many folders with files, mirroring takes place at a normal speed.
In addition, downloading a specific file in this bucket is fast.
The problem appears when trying to mirror or copy the entire folder with a huge number of files.

**Comment by chernykhse** [comment]
tnx
