### ISSUE TITLE
"mc cp" and "mc mirror" report "Insufficient permissions to access this file ..." 

### ISSUE THREAD

**Issue by crcjs** [minio/mc#2753]
## Expected behavior
Pointing the "mc cp" or "mc mirror" command to a local directory that doesn't exist.
The "mc cp" command should report that the target doesn't exist. 

## Actual behavior
$ mc cp /Users/Administrator/Documents/source/newark.jpg /myminio/target
mc: <ERROR> Failed to copy `/Users/Administrator/Documents/source/newark.jpg`. Insufficient permissions to access this file `/myminio/target`

## Steps to reproduce the behavior
Point the "mc cp" or "mc mirror" to a local directory that doesn't exist.

## mc version
Version: 2019-04-10T22:11:28Z
Release-tag: RELEASE.2019-04-10T22-11-28Z
Commit-id: ea469140d50b0240501963666e1de19c6d37f812

## System information
MacBook Pro
Darwin Chris-MBP 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

**Comment by poornas** [comment]
@crjcs, target in this case is the filesystem - so returning target doesn't exist wouldn't be accurate. 

Insufficient permissions is being returned only because you are attempting to copy to a destination under root dir "/" which is restricted
