### ISSUE TITLE
mc config help output does include "host" or "add"

### ISSUE THREAD

**Issue by crcjs** [minio/mc#2754]
## Expected behavior
Two issues:
1) the USAGE line should include "host" as part of the example
2) the COMMANDs line should include "add" as part of the list of commands

USAGE:
  mc config host COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  list, add, modify, and remove in the configuration file.

## Actual behavior
$ mc config
NAME:
  mc config - configure minio client

USAGE:
  mc config COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  host  list, modify and remove hosts in configuration file

## Steps to reproduce the behavior
Run the command "mc config"

## mc version
Version: 2019-04-10T22:11:28Z
Release-tag: RELEASE.2019-04-10T22-11-28Z
Commit-id: ea469140d50b0240501963666e1de19c6d37f812

**Comment by harshavardhana** [comment]
```
mc config host add -h
```

add, delete are sub-commands provide their own docs. So we don't repeat them at top level.

**Comment by crcjs** [comment]
I was trying to add a new host and I couldn't find the syntax for the
command. How am I supposed to know that these commands exist if they aren't
in the help file?


Cheers,
Christopher Slater
m: 408-599-9103

**Comment by harshavardhana** [comment]
> I was trying to add a new host and I couldn't find the syntax for the command. How am I supposed to know that these commands exist if they aren't in the help file?

They are `mc config` says `host` is the subcommand

```
mc config 
...
COMMANDS:
  host  list, modify and remove hosts in configuration file
...

And `mc config host` says
```
mc config host
...
COMMANDS:
  add, a      add a new host to configuration file
  remove, rm  remove a host from configuration file
  list, ls    list hosts in configuration file
```

And we document it everywhere https://docs.min.io/docs/minio-client-quickstart-guide.html

**Comment by crcjs** [comment]
Yes, the documentation shows the add command. Why can't the online help use the same text?

USAGE:
  mc config host COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  add, a      add a new host to configuration file
  remove, rm  remove a host from configuration file
  list, ls    lists hosts in configuration file

**Comment by harshavardhana** [comment]
I am unable to understand what is the problem here.

**Comment by kannappanr** [comment]
Closing the issue as answered.
