### ISSUE TITLE
Deletion of non-existing object shows an error

### ISSUE THREAD

**Issue by marvin0815** [minio/mc#2761]
## Expected behavior
Exit with notice and exit code 0
## Actual behavior
mc: <ERROR> Failed to remove `host/bucket/object` recursively. Object does not exist

## mc version
- (paste output of `mc version`)
Version: 2019-04-24T00:09:41Z
Release-tag: RELEASE.2019-04-24T00-09-41Z
Commit-id: ecdeb3934d8297170c508140d08a9730f16d8440
## System information
N/A

The intention of `rm` is the deletion of objects; if they do not exist mc should show an information or warning instead of an error and exit code 1.

**Comment by vadmeste** [comment]
@marvin0815 I think some people would say they still want to be alerted when that object is not there. I think it is better to follow the behavior to the standard linux 'rm' command here

**Comment by marvin0815** [comment]
> @marvin0815 I think some people would say they still want to be alerted when that object is not there. I think it is better to follow the behavior to the standard linux 'rm' command here

Agreed, and like you said, mc should not complain about missing objects when using --force as `rm` does.

**Comment by kannappanr** [comment]
@marvin0815 Thanks for filing this issue, will see if we can return `no error` in the case of `--force` flag.
