### ISSUE TITLE
mc mirror --watch ignores files owned by other user

### ISSUE THREAD

**Issue by radlwadl** [minio/mc#2763]
## Expected behavior
"mc mirror --watch" should sync all files, even owned by other users than the one which runs the mc command

## Actual behavior
After starting "mc mirror --watch" all files in source directory are synced to target, no matter by which user the source files are owned. File permissions are 644 for all files.
When creating a new file by a user which is not the user that runs the "mc mirror --watch", while the "mc mirror --watch" is running, the new file doesn't get synced

## Steps to reproduce the behavior
1. Source-directory owned by UserA:GroupA, Permissions 776
2. Create file "test1" in Source-directory by UserA, group GroupA, permissions 644
3. start "mc mirror --watch" with UserB, syncing Source-directory
4. -> "test1" is synced to target
5. Create file "test2" with user UserA, group GroupA, permissions 644, in Source-directory while "mc mirror --watch" is still running.
6. File "test2" is not synced
7. Create file "test3" with user UserB (running the mc), group GroupA, permissions 644, in Source-directory while "mc mirror --watch" is still running.
8. -> "test3" is synced to target

## mc version
- (paste output of `mc version`)
Version: 2018-11-06T01:12:20Z
Release-tag: RELEASE.2018-11-06T01-12-20Z
Commit-id: b827fac6356f80354a1cf61f43cf5e5b60bbb511

## System information
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4

**Comment by vadmeste** [comment]
@radlwadl, userB doesn't have full access to source directory

Try this `sudo -u testuser md5sum /path/to/source-directory/file`, you should have permission denied. 

So mc mirror, ran as userB, won't be really able to mirror.

Are you saying the mc is not showing any permission error message ?

**Comment by radlwadl** [comment]
@vadmeste 
Due to a lot of restrictions here in the I'm currently not able to use "sudo" as I want to.
A `md5sum /path/to/source-directory/file` executed under the user which runs the mc gives no error and calculates the md5sum as it should.

UserB, which runs the mc is also member of GroupA. So UserB has full access (rwx) to source directory by its group policy - kindly excuse, I didn't mention that.

mc mirror --watch starts without any permission error.
It even copies all files (including those which don't belong to UserB, running the mc) right after starting.
A file, created by an user != UserB and created while mc mirror --watch is running is not copied.

**Comment by vadmeste** [comment]
@radlwadl I tested locally and it seems to work.

`mc mirror -w` from local directory to play/vadmeste/ ran by userB who has access to the local direcotry

I executed `touch local_directory/newfile` with userA

By the way, mc mirror -w won't overwrite existing files unless --overwrite flag is passed, are you sure you are not overwriting an existing file during your test ?

**Comment by radlwadl** [comment]
@vadmeste I'll leave now, and will proceed on Thursday.
I can say, that I don't try to overwrite files.
Ah, another detail: source-directory is a NFS mounted NAS filesystem. But this shouldn't make any difference as both the users have full access to the source-dir...

**Comment by harshavardhana** [comment]
fsnotify might not be supported on NFSv3

**Comment by vadmeste** [comment]
@radlwadl could you please try your experiment with a normal folder and update us ? that would be a lead for us to investigate further.

**Comment by radlwadl** [comment]
@vadmeste @harshavardhana 
It's very likely that it's really connected to the NFS exported filesystem. Tried the same with the same users and directory/file permissions and the file created with a user != the mc running user was copied right after creating it.
I'm currently asking for the exact NFS version that's used at our fileservers.

**Comment by radlwadl** [comment]
Update2:
The problem still concerns only those files which are not created by the user which runs the mc process.
Files created by the user that runs the mc process (using --watch) are copied to the target even they're stored on a NFS mounted filesystem.
Kindly excuse this little bit confusing issue report...
