### ISSUE TITLE
Add --ignore-existing to bucket notification event creation

### ISSUE THREAD

**Issue by poksiala** [minio/mc#2771]
## Expected behavior
It would be great benefit to minio deployment automation if we could ignore `event add` errors that are caused by the rule already existing like we can ignore bucket already existing
```
mc event add myminio/mybucket arn:minio:sqs::1:webhook --event put
mc: <INFO> Identical rule already exists.
```
## Actual behavior
```
mc event add myminio/mybucket arn:minio:sqs::1:webhook --event put
mc: <ERROR> Cannot enable notification on the specified bucket. An object key name filtering rule defined with overlapping prefixes, overlapping suffixes, or overlapping combinations of prefixes and suffixes for the same event types.
```

## Steps to reproduce the behavior
Add same event rule twice to single bucket

## mc version
Version: 2019-05-01T23:27:44Z
Release-tag: RELEASE.2019-05-01T23-27-44Z
Commit-id: b1aa2232ef3babc5f06bacb1b0044022185457ca

## System information
Mac

**Comment by kannappanr** [comment]
@poksiala Will talk about this internally and get back to you.
