### ISSUE TITLE
mc.exe rm  can't find the object

### ISSUE THREAD

**Issue by pkleanthous** [minio/mc#2772]
When I'm using mc on a Unix system it can delete an object. On a Windows host, it can't find the same object

## Expected behavior
It should delete the object.

### On a Windows host
```
mc.exe rm minio/maroulla/kokos.tar
mc.exe : mc.exe: <ERROR> Failed to remove `minio/maroulla/kokos.tar`. Target `minio/maroulla/kokos.tar` not found.
At line:1 char:1
+ mc.exe rm minio/maroulla/kokos.tar
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (mc.exe: <ERROR>...tar` not found.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
### On a Unix host
```
mc rm --fake  minio/maroulla/kokos.tar
Removing `minio/maroulla/kokos.tar`.
```

## Steps to reproduce the behavior
Run mc.exe rm in a windows system

## mc version
mc.exe version RELEASE.2019-05-01T23-27-44Z

## System information
Windows 10

**Comment by nitisht** [comment]
Thanks for reporting @pkleanthous we'll take a look

**Comment by pkleanthous** [comment]
I have a workaround for this issue.

Use Backslash instead of Forward Slash

```
mc.exe rm minio\maroulla\kokos.tar
```
