### ISSUE TITLE
Service help description wrong for windows users

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#2776]
## Expected behavior
Borrowing from https://github.com/minio/minio/issues/7598 we should make this appropriate behavior just like a server.

## Actual behavior
No platform-specific help

## Steps to reproduce the behavior
Just type `mc cp -h` on Windows

## mc version
master

## System information
All supported systems

**Comment by ebozduman** [comment]
Tested and verified the fix on both Windows (8.1) and Linux (Ubuntu 18.04) OSs.

**Note**: You may need to `"go get github.com/minio/cli"` at `mc` repo, if one wants to test the fix.
