### ISSUE TITLE
Set --content-type option

### ISSUE THREAD

**Issue by alebeta90** [minio/mc#2786]
## Expected behavior
Be able to set content-type to file being upload
## Actual behavior
No option available
## mc version
Version: 2019-03-13T21:05:06Z
Release-tag: RELEASE.2019-03-13T21-05-06Z
Commit-id: ecfd4526a3b6071330a0093c80815b59d451afd0

## System information
5.0.16-100.fc28.x86_64

**Comment by kannappanr** [comment]
It already exists, please look at `mc cp` for examples

An example here is 
` mc cp --attr Content-Type=txt /etc/issue play/test`

**Comment by alebeta90** [comment]
@kannappanr thanks!
