### ISSUE TITLE
Support for Homebrew on Linux

### ISSUE THREAD

**Issue by mitchellmaler** [minio/mc#2789]
Right now the formula only installs the Darwin binary of k9s. I have some users that are using Linux and Windows Subsystem for Linux and then using homebrew for Linux. This allows us to keep our on-boarding and setup very similar. If the formula could be modified to install the Linux version when on Linux then both can be supported.

**Comment by harshavardhana** [comment]
Feel free to send a PR @mitchellmaler - also please make sure to use our issue template for feature requests. It is in our interest to have our issues well documented for historical purposes.

**Comment by harshavardhana** [comment]
Fixed and merged.. `brew install  minio/stable/mc`
