### ISSUE TITLE
Very slow Get/Read Performance 1000's Small Files (250KB<)

### ISSUE THREAD

**Issue by ghost** [minio/mc#2796]
## Expected behavior
I'm running this in a lab setup to test before buying additional hardware. I wasn't expecting blazing performance but did at minimum expect slightly better download performance than upload.

I'm wondering if there is a more optimal command I should use to get maybe more concurrency?

The key goal of the end setup is fast as possible access/read time of small image files.

Thanks

Hass

## Actual behavior
In a testing with 1000's of small JPG files (most less than 240KB in size) I found the following:

Upload Entire DataSet
mc cp --recursive c:\temp\all_images minio/temp/data1
...mp\all_images\00001929.jpg:  18.75 GiB / 18.75 GiB [=========================] 100.00% **8.88 MiB/s** 36m2s

Download first go, I gave up due to speed
mc cp --recursive minio/temp/data1 c:\temp\all_images_down
...a1/all_images/00000456.jpg:  682.71 MiB / 18.75 GiB 
[===>   3.56% **95.32 KiB/s** 2d7h13m28s

Download second go, still running.
mc cp --recursive minio/temp/data4 c:\temp\all_images_down
...00/temp/data4/00003956.jpg:  444.80 MiB / 720.40 MiB 
[=======>                                         ]  61.74% **393.56 KiB/s** 11m56s

## Steps to reproduce the behavior

Outside of my basic setup you just need lots of small JPG files within a single folder.

## mc version
- (paste output of `mc version`)
Version: 2019-05-01T23:27:44Z
Release-tag: RELEASE.2019-05-01T23-27-44Z
Commit-id: b1aa2232ef3babc5f06bacb1b0044022185457ca

## System information

Laptop is a fairly new Dell i7/16GB RAM 1Gbps wired connection between it and minio server(s)

I have three Minio Servers running on a VM ESXi host with two disks each, they are all sharing a 1TB EVO SSD. No other VM's are leveraging this SSD.

Minio Server: 2019-06-11T00:44:33Z

CPU/RAM and Disk all look good on the backend

**Comment by kannappanr** [comment]
@hassbabaie Can you please let us the command you used to start `minio` server?

**Comment by hassbabaie** [comment]
Thanks for the quick reply @kannappanr 

I'm using the systemd startup with the minio.service (downloaded yesterday)

Below is the command minio.service is running:

`ExecStart=/usr/local/bin/minio server $MINIO_VOLUMES`



Below is an extract of /etc/default/minio   


```
# Volume to be used for MinIO server.
MINIO_VOLUMES="http://svr-minio-00{1...3}.XXXXX.com/mnt/minio_data_{1...2}"
# Use if you want to run MinIO on a custom port.
# MINIO_OPTS="--address :9000"
# Access Key of the server.
MINIO_ACCESS_KEY="XXXXXXX
# Secret key of the server.
MINIO_SECRET_KEY="XXXXXXXX"
# test service account
User="minio-user"
```

**Comment by hassbabaie** [comment]
Hi @kannappanr any thoughts on this, looking at it it 'looks" like it's doing a single file at a time versus a high level of parallelism which is what you would want when dealing with small files?

I tried to use --worker-count but it seems this switch only works for doing a mirror

Thanks in advance

Hass

**Comment by vadmeste** [comment]
@hassbabaie --worker-count is not supported since some time, are you sure you are running the latest mc version ?

**Comment by hassbabaie** [comment]
@vadmeste thanks and I think so:

This is the version I'm running:

(paste output of mc version)
Version: 2019-05-01T23:27:44Z
Release-tag: RELEASE.2019-05-01T23-27-44Z
Commit-id: b1aa223

DO you know what I should expected to see? If there is logging I can turn this on. Again thank you for your help

**Comment by krishnasrinivas** [comment]
Can you use iperf to check the bandwidth between your laptop and minio server?

**Comment by hassbabaie** [comment]
Hi @krishnasrinivas I don't have iperf running on the laptop I'm testing the client from however see below. If I pull a large file from the MINIO Server I max the 1Gbps wired ethernet connection:

```
mc cp --recursive minio/temp/data2 c:\temp\all_images_down
...00/temp/data2/lots_of_pics.zip:  4.60 GiB / 4.60 GiB 
[=====================] 100.00% 106.42 MiB/s 44s
```

Then from a latency perspective they are plugged into the same 1Gbps switch and so sub 1m/s

```
Pinging svr-minio-001.corp.domain.com [10.10.2.126] with 32 bytes of data:
Reply from 10.10.2.126: bytes=32 time<1ms TTL=64
Reply from 10.10.2.126: bytes=32 time=1ms TTL=64
Reply from 10.10.2.126: bytes=32 time<1ms TTL=64
Reply from 10.10.2.126: bytes=32 time<1ms TTL=64
```

**Comment by hassbabaie** [comment]
FYI, I just tested with rclone instead of mc and got a 11x speed improvement on the same small files:

```
C:\>rclone copy Minio:temp/data4 c:/temp/test-rclone -P
Transferred:      720.395M / 720.395 MBytes, 100%, 4.421 MBytes/s, ETA 0sss7s
Errors:                 0
Checks:                 0 / 0, -
Transferred:        10779 / 10779, 100%
Elapsed time:     2m42.9s
```

Hope this helps

Hass

**Comment by harshavardhana** [comment]
So it is `mc` concurrency which is slower @hassbabaie

**Comment by hassbabaie** [comment]
@harshavardhana on download it looks like MC is doing zero concurrency? Again uploading seemed fine, large fines are find in both directions but small files downloaded are getting at best 400KB per second (versus rclone with no real tweaking on the same laptop is getting for small files 4.4MBps)

**Comment by vadmeste** [comment]
@hassbabaie downloading should also be done in parallel, I can test this locally and update you

**Comment by vadmeste** [comment]
@hassbabaie tested that version with my local machine, it is just working fine as expected,

Can you try to test with one single big file ? and see what's the download speed ?

**Comment by hassbabaie** [comment]
@vadmeste I think I mentioned above when access larger file it works very fast and maxes my 1Gbps link. it's only when accessing/copying down 1000's of small files.

Can you confirm if it is supposed to be concurrent and what it defaults to? 

I did some more testing over the weekend with rclone and the concurrency setting

**Concurrency = 4
ByPass Cache go direct to Remote Minio Server:**
testuser@minio-b:/$ sudo rclone copy minio:temp/data4 /mnt/sdc/ -P
Transferred:   	  720.395M / 720.395 MBytes, 100%, 4.677 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:        10779 / 10779, 100%
Elapsed time:       2m34s

**Concurrency = 10**
testuser@minio-b:/mnt/sdc$ sudo rm -rf /mnt/sdc/*
testuser@minio-b:/mnt/sdc$ sudo rclone copy minio:temp/data4 /mnt/sdc/ -P --transfers=10
Transferred:   	  720.395M / 720.395 MBytes, 100%, 5.894 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:        10779 / 10779, 100%
Elapsed time:      2m2.2s

**Concurrency = 20**
ByPass Cache go direct to Remote Minio Server:
testuser@minio-b:/mnt/sdc$ sudo rclone copy minio:temp/data4 /mnt/sdc/ -P --transfers=20
Transferred:   	  720.395M / 720.395 MBytes, 100%, 7.039 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:        10779 / 10779, 100%
Elapsed time:     1m42.3s


I can do some more testing today if you would like. Also as a heads up I'm also on the slack channel if that helps

Hass

**Comment by hassbabaie** [comment]
@vadmeste please let me know if you would like me to do any more testing. I'm happy to do that it's odd if I'm the only person not seeing concurrent connections 

Thanks

Hass

**Comment by vadmeste** [comment]
Hey @hassbabaie, 

Sure, can we discuss in private ? can you ping me in Minio Slack channel,  https://slack.min.io ?

**Comment by hassbabaie** [comment]
FYI, @vadmeste @krishnasrinivas  sorry for the delay, I've now tested this with the latest dev build from @vadmeste and I don't really see much concurrency improvement when tweaking the export _MC_PARALLEL_WORKERS=5 setting (tried 5,10,50,100)

I can seem to get the speed to double to about 130KBps however still far slower than other S3 clients. Again this is related to Copying small files.

Hass

**Comment by i0x71** [comment]
I am also seeing slow copy with lots of small files. Any news on this ?

**Comment by harshavardhana** [comment]
> I am also seeing slow copy with lots of small files. Any news on this ?

This is not to do with `mc` @i0x71 small files cannot be made any faster than the overall HTTP overhead that they incur. The higher bandwidth can be utilized only with larger streams smaller streams can never really peak due to the overall chattiness.

**Comment by i0x71** [comment]
Thanks, that what i figured.

**Comment by ntavares** [comment]
I was just having an avg 5 Ki/s copy (mirror) speed right now, which led me to google and end up here.

> small files cannot be made any faster than the overall HTTP overhead that they incur

@harshavardhana that would not explain the better performance with rclone (above), right?
Just wondering, is this _MC_PARALLEL_WORKERS setting and env var? Is it something we can use, to see if it helps?

**Comment by kilia** [comment]
> > I am also seeing slow copy with lots of small files. Any news on this ?
> 
> This is not to do with `mc` @i0x71 small files cannot be made any faster than the overall HTTP overhead that they incur. The higher bandwidth can be utilized only with larger streams smaller streams can never really peak due to the overall chattiness.

so any suggestions for large number of smalll size files?

**Comment by kilia** [comment]
> > I am also seeing slow copy with lots of small files. Any news on this ?
> 
> This is not to do with `mc` @i0x71 small files cannot be made any faster than the overall HTTP overhead that they incur. The higher bandwidth can be utilized only with larger streams smaller streams can never really peak due to the overall chattiness.

can we do anything like open more threads/process to improve?
BTW: multithreading using python api does not seem to improve anything :-(

**Comment by phanipvarma** [comment]
Hi All,

minio version: RELEASE.2020-09-21T22-31-59Z
mc version: RELEASE.2020-09-18T00-13-21Z

Is there a guidance or recommendation when Minio has many smaller size files ? (In our case, we have smaller size files in Millions)

In our Application stack, we are using Minio as object storage (3 node cluster) to store configuration and application generated data files.

When we deploy our Application stack in Production environment, we need to take backup of Application configuration and data on periodic basis. For the Application data that is stored on Minio, we are using 'mc mirror' to copy the data to backup folder on regular basis (ex: once in 24 hours for Full backup).

Over the time, the number of application data files (small in size, few KBs) grow into Millions and 'mc mirror' takes pretty long time, 18hours+ to copy 8GB of data overall because of many number of smaller files i guess. It is a 10Gbps network, if i have a same 8GB amount of data in the form of larger files, 'mc mirror' finishes in less than a minute, just to prove that it is not a network issue. 

Is there any plan to improve 'mc mirror' performance when dealing with many smaller size files ?

Thanks,
Phani

**Comment by harshavardhana** [comment]
@phanipvarma for performance recommendations and architecture help we recommend you to approach us at https://subnet.min.io/subscribe

**Comment by phanipvarma** [comment]
Thanks @harshavardhana, i subscribed to community, do i need to post my question to 'general' group in Slack ?

**Comment by klauspost** [comment]
@phanipvarma There may be some community members that can help you on Slack, but as Harsha points out we cannot help with architecture design and setup outside our subscription services. See the provided links.

**Comment by mirajgodha** [comment]
So, the conclusion is minio is not a good choice for small files?

**Comment by klauspost** [comment]
@mirajgodha Several improvements and new features has been made since then.

**Comment by Rush** [comment]
Today I am trying to mirror a 4 HDD disk cluster to an 8 HDD disk cluster with hundreds of GBs of small files (100-300KB). The speed is fairly slow - around 2MB/s after tweaking readahead. 

Unfortunately I cannot use rclone as it doesn't support directories with large amount of files.

I use latest version of minio, latest version of mc and the recommended XFS filesystem.

**Comment by Rush** [comment]
Also `_MC_PARALLEL_WORKERS` sort of helps - now I am getting 6MB/s. Thanks @ntavares !!

To anybody reading this, you can just run:
```
_MC_PARALLEL_WORKERS=10 mc mirror --watch <SOURCE><DESTINATION>
```

**Comment by ginkel** [comment]
> Unfortunately I cannot use rclone as it doesn't support directories with large amount of files.

rclone worked quite well for me when cloning minio with ~ 100k files per bucket. What issues have you been struggling with specifically?

**Comment by Rush** [comment]
> rclone worked quite well for me when cloning minio with ~ 100k files per bucket. What issues have you been struggling with specifically?

I had it running for 15m without it making any progress. I assumed it got stuck on loading the directory tree. https://forum.rclone.org/t/recommendations-for-using-rclone-with-a-minio-10m-files/14472/2 - here they say rclone may not be ideal for lots of small files.

I have 1.6mln small files in the bucket.

**Comment by Rush** [comment]
Also maybe I should have picked Ext4 rather than the recommended XFS. https://unix.stackexchange.com/questions/28756/what-is-the-most-high-performance-linux-filesystem-for-storing-a-lot-of-small-fi/28792#28792

Anybody has experience with a different filesystem choice based on the small files use case?

**Comment by vijayanandnandam** [comment]
@Rush i have around ~40 mil files on (10x16tb array).. struggling to recover after disk replacement.. The data is still available through thanks to minio. But healing single disk is taking enormous time. I am using ext4 and its not any better btw
