### ISSUE TITLE
Update Help File and Document for "mb" command

### ISSUE THREAD

**Issue by hassbabaie** [minio/mc#2797]
## Expected behavior

I think it should (used to say):

mb       make a bucket and/or folders

This helps remove the need to go hunting for how to create folders

## Actual behavior

It now says:

mb       make a bucket

## Steps to reproduce the behavior
N/A

## mc version
- (paste output of `mc version`)
Version: 2019-05-01T23:27:44Z
Release-tag: RELEASE.2019-05-01T23-27-44Z
Commit-id: b1aa2232ef3babc5f06bacb1b0044022185457ca

## System information
N/A

**Comment by kannappanr** [comment]
@hassbabaie Can you please go ahead and send a PR?

**Comment by hassbabaie** [comment]
thanks and yes i'll get one in tomorrow, thanks @kannappanr

**Comment by kannappanr** [comment]
@hassbabaie Closing this issue as stale. please feel free to send a PR to update the doc.
