### ISSUE TITLE
Don't show "Removing" if nothing gets removed

### ISSUE THREAD

**Issue by WolfspiritM** [minio/mc#2800]
When using mc rm together with e.g. `--older-than 10d and --recursive`

## Expected behavior
Only removed keys are listed.

## Actual behavior
 mc shows "Removing" for all directories even so nothing is actually removed.
This is very confusing as I thought it's ignoring --older-than and removing all the directories but instead it's only "Scanning" them and ignoring the files.

```
Removing `production/in/customer/2019/06/15/CID1/`.
Removing `production/in/customer/2019/06/15/CID1/MID/`.
Removing `production/in/customer/2019/06/15/CID2/`.
Removing `production/in/customer/2019/06/15/CID2/MID/`.
Removing `production/in/customer/2019/06/15/CID3/`.
Removing `production/in/customer/2019/06/15/CID3/MID/`.
Removing `production/in/customer/2019/06/15/CID4/`.
Removing `production/in/customer/2019/06/15/CID4/MID/`.
Removing `production/in/customer/2019/06/15/CID5/`.
Removing `production/in/customer/2019/06/15/CID5/MID/`.
Removing `production/in/customer/2019/06/15/CID6/`.
Removing `production/in/customer/2019/06/15/CID6/MID/`.
Removing `production/in/customer/2019/06/15/CID7/`.
Removing `production/in/customer/2019/06/15/CID7/MID/`.
```

## mc version
- RELEASE.2019-06-12T20-35-20Z

## System information
Docker

**Comment by kannappanr** [comment]
@WolfspiritM Thanks for reporting this issue. Will take a  look and see how we can handle this.
