### ISSUE TITLE
`mc policy` does not error when executed on an object that does not exist

### ISSUE THREAD

**Issue by kfergiani** [minio/mc#2801]
## Expected behavior
`mc policy` should error/feedback to the user if the target object does not exist
## Actual behavior
`mc policy` outputs a policy for an object that does not exist
## Steps to reproduce the behavior
create a bucket, execute `mc policy [bucket]/foobar`, observe output
## mc version
- (paste output of `mc version`)
```
Version: 2019-05-29T21:21:34Z
Release-tag: RELEASE.2019-05-29T21-21-34Z
Commit-id: f4bb0b8850cb5a9c2901961572066e48ad972e8c
```
## System information
macOS Mojave

**Comment by kannappanr** [comment]
@kfergiani Thanks for reporting. Will take a look.

**Comment by kannappanr** [comment]
@kfergiani Can you explain in more detail, what you are seeing? The exact steps. I don't see any error. Remember that these are bucket policies, so the object here is more of a prefix and it need not exist.

**Comment by harshavardhana** [comment]
Closing this issue as working as per AWS S3 behavior requirement.

**Comment by kfergiani** [comment]
Yeah in that case I guess I just misunderstood the documentation. My bad
