### ISSUE TITLE
Support for IAM auth?

### ISSUE THREAD

**Issue by mausch** [minio/mc#2821]
## Expected behavior
I'd like to be able to say `mc config host add s3 https://s3.amazonaws.com` and have mc use IAM auth instead of access keys.
I'd like to see documentation for IAM auth if it's supported, or otherwise an item on some FAQ saying that it's not supported. I can't seem to find any of this :-(

## Actual behavior
When running the command above I get `<ERROR> Incorrect number of arguments for host add command.`

## mc version
RELEASE.2019-07-09T23-57-06Z

**Comment by harshavardhana** [comment]
We don't support IAM auth yet @mausch there is a plan in future we will though.

**Comment by mausch** [comment]
Thanks for the quick reply! it seems that support in the SDK has been implemented quite some time ago: https://github.com/minio/minio-go/issues/643

**Comment by harshavardhana** [comment]
> Thanks for the quick reply! it seems that support in the SDK has been implemented quite some time ago: [minio/minio-go#643](https://github.com/minio/minio-go/issues/643)

SDKs have implemented a long time ago. `mc` requires some CLI changes to make it user-friendly

**Comment by kgrimes2** [comment]
Can we reopen this? Are there any suitable workarounds? Our team really needs it

**Comment by harshavardhana** [comment]
> Can we reopen this? Are there any suitable workarounds? Our team really needs it

@kgrimes2 you should get the keys from the IAM endpoints and then pass them to `mc` as 

```
MC_HOST_iam=http://<access_key>:<secret_key>:<session_token>@s3-server:port/ mc ls iam/mybucket
```

**Comment by ztaylor54** [comment]
@harshavardhana Is this documented anywhere in MinIO docs? I have yet to stumble upon it.

**Comment by harshavardhana** [comment]
> @harshavardhana Is this documented anywhere in MinIO docs? I have yet to stumble upon it. 

https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#specify-temporary-host-configuration-through-environment-variable 

Something like this
