### ISSUE TITLE
mirror command does not remove empty directories from local machine

### ISSUE THREAD

**Issue by agabrys** [minio/mc#2826]
I'm synchronizing a local machine with minio server. Everything what has been deleted from the server should be also removed from the local machine.

I'm executing the following command:
```minio mirror --config-dir /data/config --overwrite --remove s3/prod/ /data/files/```

## Expected behavior
Content of the local machine `/data/files/` directory is exactly the same as `s3` server `prod` bucket:
* all new files should be created on the local machine
* all removed files should be removed from the local machine
* all removed directories should be removed from the local machine

## Actual behavior
Everything except deleting removed directories works properly:
* all new files should be created on the local machine 🆗 
* all removed files should be removed from the local machine 🆗 
* all removed directories should be removed from the local machine 🐛

It causes that after some time I have dozen of empty directories on the local machine.

## Steps to reproduce the behavior

1. create a directory with deep nested structure (in all leaves directories must be located at least one file)
2. upload to minio server
3. execute mirror remote → local machine (the file structure is not the same)
4. remove some 1-st level directories from minio
5. execute mirror remote → local machine (removed files are deleted, but empty directories stay)

In our case we have the following structure (all directories have the same structure):
```
dir1
    \- artifacts (← directory, stores 3 files)
    |- pipeline-scripts
    |                  \- directory (←directory, stores 3 file)
    |                  |- jobs (← directory, stores 6 files)
    |                  |- utils (← directory, stores 9 files)
    |                  |- .editorconfig
    |                  |- .gitignore
    |                  | ... (additional 4 files)
    |- product (← git repository without .git folder, contain nested directories with 5-6 levels)
    |- resources (← directory, stores 4 files)
    |- pipeline.prooperties
    |- product-fat.zip
```

After removal whole `dir1` from the server, and mirror to local I see that all files have been removed, but directories still exist.

## mc version
```minio version RELEASE.2019-05-23T01-33-27Z```

## System information
```
> uname -a
Linux host-p-15760 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
```

## Additional comments
I found #2612 about missing empty directories after mirroring. I understand that this behavior is a design decision to not create any empty directories (they store no files, so there is no sense to keep them). It would be really great to make it consistent and remove directories which don't store any files :)

**Comment by kannappanr** [comment]
@agabrys Thanks for the detailed description of the issue. We will take a look at this.
