### ISSUE TITLE
mc ignores extra root certificate on Ubuntu 18.04

### ISSUE THREAD

**Issue by kiwy42** [minio/mc#2831]
## Expected behavior
I add internal root certificate to my Ubuntu 18.04 in:  
 `/usr/share/ca-certificates/extra/`  
then doing :  
`sudo dpkg-reconfigure ca-certificates`  
When adding my internal server with command:  
`mc config host add Internals3 https://internalS3:8080  key password --api "s3v4"`  
It should work flawlessly and accept the certificate as it's trusted at the OS level. 
I should also be able to use : 
`mc ls Internals3`

## Actual behavior
I'm forced to use `--insecure` flag for all command regarding this server.
If I force example run a simple:  
`wget -O- https://internalS3:8080`  
I got absolutly no error because it uses OS root CA authorities.  

## Steps to reproduce the behavior
I think I explain it correctly in the actual behaviour.
Use an internal CA authority is ignored if set at OS level.
## mc version
Version: 2019-04-17T17:41:56Z
Release-tag: RELEASE.2019-04-17T17-41-56Z
Commit-id: 83a9d8b91d0b4c61883442a50c2e990cb0bdc3be
## System information
Ubuntu 18.04
 4.15.0-54-generic

**Comment by vadmeste** [comment]
Checking this..

**Comment by vadmeste** [comment]
mc seems to be working fine for me, I tested with the same version as yours. 

What's the exact error message shown by mc ?

**Comment by kiwy42** [comment]
OK, 
For reasons unknown after a reboot, and a weekend off, it seems to work properly.
I'm sorry, I must have done something wrong during my testing.
You can close it.
