### ISSUE TITLE
mc binary name collides with another Ubuntu utility.

### ISSUE THREAD

**Issue by adiospeds** [minio/mc#2842]
While packaging the minio-client as deb package (`mc.deb`) I came across some issues. Figured that there was already a package providing the `mc` binary. But this `mc` wasn't the minio client. There exists an Ubuntu File System browser called Midnight Commander which also provides the `mc` binary. Having both the utils installed may start creating a problem for users. Minio should consider renaming the mc binary to something like may be minio-cli or find other ways to tackle this problem as it may create issues in future if mc is released as a deb/rpm package.

For now, we have named the mc.deb for minio client as minio-client.deb and that has solved the problem for us.

Links: 
https://github.com/MidnightCommander/mc     (has  14,462 commits)
http://midnight-commander.org

**Comment by nitisht** [comment]
This is known and as you mentioned simple rename is enough. 

There are no plans to change the `mc` name, pls refer previous conversations here  https://github.com/minio/mc/issues?utf8=%E2%9C%93&q=is%3Aissue+Midnight+commander
