### ISSUE TITLE
minio-2019.07.24.02.02.23: cmd/admin-heal.go:148:11: undefined: madmin.BgHealState

### ISSUE THREAD

**Issue by Zlogene** [minio/mc#2844]
$title

it is referenced as:
https://github.com/minio/mc/blob/master/cmd/admin-heal.go#L30

go version 1.12.5

System:
Linux unrandom 4.19.57-gentoo #2 SMP Tue Jul 30 14:42:34 MSK 2019 x86_64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz GenuineIntel GNU/Linux

**Comment by harshavardhana** [comment]
you need to use GO111MODULE=on to start building `mc` @Zlogene

**Comment by Zlogene** [comment]
oh, that sound reasonable, thank you very much @harshavardhana !
