### ISSUE TITLE
mc should not enforce any length restriction on access_key or secret_key

### ISSUE THREAD

**Issue by mattbenjamin** [minio/mc#2845]
## Expected behavior
mc will allow (e.g.) string valujes of any length as access_key or secret_key

## Actual behavior
mc config host add will not add a host with secret_key less than 8 characters

## Steps to reproduce the behavior
ahem

## mc version
- (paste output of `mc version`)
VERSION:
  DEVELOPMENT.2019-07-31T20-30-21Z

## System information
linux

**Comment by harshavardhana** [comment]
why not @mattbenjamin

**Comment by harshavardhana** [comment]
Default AWS Keys are even longer by default, we kept 8 character to be user-friendly.  Secret keys up to 8 characters provide best practices for the actual password length. 

We are not planning to relax this, as there are no practical reasons why this restriction should be removed.

**Comment by mattbenjamin** [comment]
@harshavardhana you're missing the obvious point: key length policy is already enforced by S3 server/gateway implementations;  it is not appropriate for the client to be weighing in

**Comment by harshavardhana** [comment]
> @harshavardhana you're missing the obvious point: key length policy is already enforced by S3 server/gateway implementations; it is not appropriate for the client to be weighing in; conversely, I would never opine on policy preferences of a server implementation (e.g., minio)

I don't think I agree the validation is here to stay and is done with good reasons. If its a show stopper for you feel free to send a PR.

**Comment by ogadaki** [comment]
Just to let you know a concrete example on this subject.

I use a local and internal server that is compatible with S3, but the access and secret credentials are both less than 8 characters (6 in my case). I don't operate the server so I can't change the credentials. I wanted to use mc but with the 8 characters limitation on secret I can't.

However, if you plan to keep this limitation, here is a suggestion: at least the error message could be more explicit on the problem? Something like "Invalid secret key `sikret`, which must be at least 8 characters".
