### ISSUE TITLE
Minio mc image build is getting stalled.

### ISSUE THREAD

**Issue by chakravarthy392** [minio/mc#2858]
## Expected behavior
docker image should get built from the Dockerfile.
## Actual behavior
Getting stalled at "go install" step [6/10]
## Steps to reproduce the behavior
```
go get -d github.com/minio/mc
cd $GOPATH/src/github.com/minio/mc
git checkout RELEASE.2019-05-01T23-27-44Z
docker build --no-cache -f Dockerfile -t minio/mc:RELEASE.2019-05-01T23-27-44Z .
```
## System information
Ubuntu 16.04
Linux in-ibmibm3400 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
are you sure your networking has no issues? @chakravarthy392

**Comment by chakravarthy392** [comment]
Hi @harshavardhana , 

I have tried after disabling the firewall, same behavior is observed.

**Comment by kannappanr** [comment]
@chakravarthy392 I was unable to reproduce the issue, though I tried `git clone` instead of `go get`
My go version is `go version go1.12.1 linux/amd64`, not sure if that makes any difference. That particular version requires `go 1.12`

**Comment by kannappanr** [comment]
Closing this as stale. Please feel free to reach out to us if you still have issues
