### ISSUE TITLE
Documentation is misleading

### ISSUE THREAD

**Issue by seqizz** [minio/mc#2865]
- Run minio (version: 2019-08-07T01:59:21Z)
- Add policy via: `mc admin policy add myminio mytestpolicy policy.json`
- Add user via: `mc admin user add myminio seqizz 12345678`
- Try to set user's policy via: `mc admin policy set myminio mytestpolicy user=seqizz`
- Get error:
> mc: <ERROR> Cannot set the policy. The specified method is not allowed against this resource.
Trace gives: `[405 Method Not Allowed] notFoundHandlerJSON`

Latest version mc seems to not support declaring policy while creating the user. What am I doing wrong?

Thanks 

## System information
mc version:
Version: 2019-08-14T20:49:49Z
Release-tag: RELEASE.2019-08-14T20-49-49Z
Commit-id: 418c8e718252263d1edef2b34879a81c6ce9b415
OS: Debian stretch 9.9

**Comment by harshavardhana** [comment]
You need to use the latest release on MinIO @seqizz and also latest release of `mc` - also these commands will work in server mode, in gateway mode you need to setup etcd.

**Comment by seqizz** [comment]
Well, turns out I am using a week old version :man_facepalming: After updating minio, everything seems ok. Thanks, especially for the fastest reply I got on GitHub :octocat:
