### ISSUE TITLE
mc admin info display 0/0 Drives

### ISSUE THREAD

**Issue by ebal** [minio/mc#2867]
I am starting my minio server with 10 directories like this:

```
$ minio server --address 127.0.0.1:9000 .minio_data{1...10}

Waiting for all other servers to be online to format the disks.
Status:         10 Online, 0 Offline
```

and when I am using mc client I do not see Drives

```
$ mc admin info myminio
●  127.0.0.1:9000
   Uptime: 25 minutes 
  Version: 2019-08-14T20:37:41Z
  Storage: Used 0 B
   Drives: 0/0 OK
```

## Expected Behavior

I would expect to see Drives: 10/10 OK

## Current Behavior

but I see `Drives: 0/0 OK`

## Context

Also, when I am removing a directory/drive I would except to see 

`Drives: 9/10 OK`

or perhaps not OK ?

## Your Environment

* Version used (`minio version`):

```
minio version
Version: 2019-08-14T20:37:41Z
Release-Tag: RELEASE.2019-08-14T20-37-41Z
Commit-ID: bbb56739bd331e7bbca86d08510fe97682ed0a38
```

* Server type and version: **Archlinux**
* Operating System and version (`uname -a`):

```
$ uname -a
Linux myhomepc 4.19.66-1-lts minio/minio#1 SMP Sat Aug 10 13:13:28 CEST 2019 x86_64 GNU/Linux
```

Thanks in advance

**Comment by nitisht** [comment]
Thanks for reporting @ebal we'll take a look

**Comment by Praveenrajmani** [comment]
@ebal It works fine for me. What is your mc version? Can you update the mc version and try?

**Comment by ebal** [comment]
I am sorry, forgot to mention mc version

```
$ mc version
Version: 2019-07-31T19:17:35Z
Release-tag: RELEASE.2019-07-31T19-17-35Z
Commit-id: 81eb54d14670729a7309b9fffd24a97a083819a9
```

**Comment by K-free-N** [comment]
HI, I have the same problem
`●  minio1:9000
   Uptime: 3 minutes 
   Version: 2020-09-21T22:31:59Z
   Network: 2/2 OK 
   Drives: 0/0 OK 
   Pool: 

●  minio2:9000
   Uptime: 3 minutes 
   Version: 2020-09-21T22:31:59Z
   Network: 2/2 OK 
   Drives: 0/0 OK 
   Pool: 

Pools:

30 MiB Used, 14 Buckets, 17,865 Objects
0 drives online, 0 drives offline`
I have 4 directories that use Minio, but the MC client doesn't see it
My mc version "RELEASE.2022-08-28T20-08-11Z"

**Comment by harshavardhana** [comment]
You can't use latest `mc` with such old deployment of MinIO please upgrade your server @K-free-N
