### ISSUE TITLE
mc rb should simply fail when presented with more input other than the bucket name

### ISSUE THREAD

**Issue by kalleyne** [minio/mc#2869]
Good day.

It's been suggested that I publish this bug report about the overly open nature and the end result of using "mc rb".

MinIO Version: 2019-08-14T20:37:41Z
mc Version: 2019-08-14T20:49:49Z

Here is an example:

```
user1@ThinkPad-T440s:~$ mc ls ub18svr-minio-bugtest/twa
[2019-08-19 10:41:38 CDT]      0B data/
[2019-08-19 10:41:38 CDT]      0B data1/
[2019-08-19 10:41:38 CDT]      0B data2/
[2019-08-19 10:41:38 CDT]      0B data3/
[2019-08-19 10:41:38 CDT]      0B prefix/
[2019-08-19 10:41:38 CDT]      0B prefix1/
[2019-08-19 10:41:38 CDT]      0B prefix2/
[2019-08-19 10:41:38 CDT]      0B prefix3/
user1@ThinkPad-T440s:~$ mc rb --force ub18svr-minio-bugtest/twa/data
mc: <ERROR> Failed to remove `ub18svr-minio-bugtest/twa/data`. The bucket you tried to delete is not empty.
user1@ThinkPad-T440s:~$ mc ls ub18svr-minio-bugtest/twa
[2019-08-19 10:42:37 CDT]      0B prefix/
[2019-08-19 10:42:37 CDT]      0B prefix1/
[2019-08-19 10:42:37 CDT]      0B prefix2/
[2019-08-19 10:42:37 CDT]      0B prefix3/
user1@ThinkPad-T440s:~$
```

I recognize that this is not the proper way to remove prefixes. However, if the "mc rb" command is designed to remove buckets then using the "mc rb --force" command in the above example to remove specific prefixes could be dangerous to other prefixes.

I've been told that "mc rb" should just simply fail when presented with more input other than the bucket name. This would close off any ambiguity about the use of the command. Newcomers would use "mc mb" to create buckets and prefixes and the temptation would be to use "mc rb" to remove both buckets and prefixes when in fact "mc rm" is the correct way to remove prefixes. Perhaps the documentation could also clear up this issue?

Thanks.

**Comment by poornas** [comment]
The real issue is that `mc rb --force ub18svr-minio-bugtest/twa/data/` needed a terminating `/` whereas you did `user1@ThinkPad-T440s:~$ mc rb --force ub18svr-minio-bugtest/twa/data` . It would have had the intended behavior of deleting data/ prefix but not data1/, data2/ and data3/.  

`mc rm` or `mc rb` without slash terminating the `data` prefix will have deleted all matching prefixes starting with `data`. This command is working as intended here @kalleyne , we can perhaps add an example to the cli documentation

**Comment by harshavardhana** [comment]
I think for `rb` we shouldn't honor prefixes @poornas

**Comment by poornas** [comment]
since rb also works on fs, it would essentially mean we can only delete top level dir, isn't it?

**Comment by harshavardhana** [comment]
Correct for that we have `mc rm` ..
