### ISSUE TITLE
du displays redundant information

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#2871]
## Expected behavior
```
~ mc du play/adv/recovery
355KiB
```

## Actual behavior
```
~  mc du play/adv/recovery
355KiB	adv/recovery/201908/root/900000000/10008/1000001448/1000001453
355KiB	adv/recovery/201908/root/900000000/10008/1000001448
355KiB	adv/recovery/201908/root/900000000/10008
355KiB	adv/recovery/201908/root/900000000
355KiB	adv/recovery/201908/root
355KiB	adv/recovery/201908
355KiB	adv/recovery
```

Recursively displaying per tree level size is not useful IMO when a user is simply asking for `du` of a given prefix or bucket. It seems like we are displaying the tree information along with `du` as well. 

## Steps to reproduce the behavior
Quite easy, create a deep directory hierarchy.
 
## mc version
master and released

## System information
Ubuntu

**Comment by harshavardhana** [comment]
I think we have implemented `du --all` as default instead it should be following as default. 

```
~ mc du --depth 1 play/adv/recovery
355KiB	adv/recovery
```

Meaning `--depth 0` should trim everything up-to the input, `--depth 1` should print the top level prefix only.

**Comment by balamurugana** [comment]
This how system `du` command works.
```sh
$ mkdir -pv adv/recovery/201908/root/900000000/10008/1000001448/1000001453
mkdir: created directory 'adv'
mkdir: created directory 'adv/recovery'
mkdir: created directory 'adv/recovery/201908'
mkdir: created directory 'adv/recovery/201908/root'
mkdir: created directory 'adv/recovery/201908/root/900000000'
mkdir: created directory 'adv/recovery/201908/root/900000000/10008'
mkdir: created directory 'adv/recovery/201908/root/900000000/10008/1000001448'
mkdir: created directory 'adv/recovery/201908/root/900000000/10008/1000001448/1000001453'

$ du adv
0	adv/recovery/201908/root/900000000/10008/1000001448/1000001453
0	adv/recovery/201908/root/900000000/10008/1000001448
0	adv/recovery/201908/root/900000000/10008
0	adv/recovery/201908/root/900000000
0	adv/recovery/201908/root
0	adv/recovery/201908
0	adv/recovery
0	adv

$ du adv/recovery
0	adv/recovery/201908/root/900000000/10008/1000001448/1000001453
0	adv/recovery/201908/root/900000000/10008/1000001448
0	adv/recovery/201908/root/900000000/10008
0	adv/recovery/201908/root/900000000
0	adv/recovery/201908/root
0	adv/recovery/201908
0	adv/recovery
```

`mc du` should work exactly like system `du` command. You would need to discuss with @abperiasamy to confirm this requirement.

**Comment by balamurugana** [comment]
As per slack discussion

1. `mc du` without args should print help like other `mc` commands
2. `mc du` should behave like `du -h --max-depth=1` as default
3. one can always give --recursive if they want capacity for each folder. recursive should be optional

**Comment by kannappanr** [comment]
@balamurugana What are the next steps in this issue?

**Comment by balamurugana** [comment]
> @balamurugana What are the next steps in this issue?

Implementation if not implemented

**Comment by kannappanr** [comment]
@balamurugana Can you please implement whatever was discussed on slack?
