### ISSUE TITLE
no trace logs :(

### ISSUE THREAD

**Issue by jayunit100** [minio/mc#2875]
## Expected behavior
using `mc admin trace` i was hoping to see why I keep getting 403 forbidden errors on my minio service (accessing it through apache hive, but i think thats irrelevant).

## Actual behavior

when running failed (403 forbidden) hadoop jobs to minio, I see no output from `mc admin trace` unless i do `--debug` in which case i get debug logs.

## mc version
- (paste output of `mc version`)

## System information

kuberentes, but probably thats irrelevant.

Ideally, is there a way i can just tail logs on the server itself ?

**Comment by jayunit100** [comment]
FYI, looks like from conversations w/ sid ^ , that the 403 error above is not logged on the server side.  I think it should be - i.e. every webserver should generally have an access log w/ response codes, if for no other reason, for batch forensics in outages or just general log collection  standards.   So, I think this issue is actionable, probably i should re file it on upstream mino.  Ultimately what i think we should have are...

1) localhost:9000/metrics should have all HTTP errors that occur in prometheus format and/or
2) there should be a minio.log file that has every server response, timestamped and ideally explained if possible .

**Comment by harshavardhana** [comment]
@jayunit100 403 errors are logged - are you trying to do anonymous requests ?

**Comment by jayunit100** [comment]
ah... wait, ` mc admin trace prestos3 --insecure -a    ` seemed to get me the answer, i guess this is a continous 1 second poll for getting logging events.   

Maybe the issue is that i wasn't using the `-a` option.  

Thanks !!!!!!!!!!!!

**Comment by harshavardhana** [comment]
It was because you are trying to access https without trusting the server certificate, it is not -a it is --insecure which helped avoid the issue.
