### ISSUE TITLE
Add healing tests in functional tests

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#2878]
To make sure that healing with normal & and deep scan is successful, heal status should also be tested.

**Comment by harshavardhana** [comment]
Healing tests already added on the server side, not sure about `mc` @vadmeste please update here if there is any work in progress on this.

**Comment by vadmeste** [comment]
> Healing tests already added on the server side, not sure about `mc` @vadmeste please update here if there is any work in progress on this.

No, there is no work in progress. I guess we can close this. However we need to discuss how to test background ops like lifecycle/data-usage/quota, etc..
