### ISSUE TITLE
Implement mc ILM cmd

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#2879]
Suggest and implementing `mc ilm` command with expiry feature

**Comment by vadmeste** [comment]
This is my proposal for the ILM command https://gist.github.com/vadmeste/2871f5e53996cc67576b62193e8dc9c8

**Comment by harshavardhana** [comment]
Copying the entire draft here

### Draft for ILM command in MC

#### Showing expiry rules

```
$ mc ilm expiry show myminio/bucket
Expiry rules:
   ID       Prefixes               Enabled    Days/Date
   fgh      ""                        ✓       10 May 2019
   gop      "temporary_uploads/"      ✓       7 days
   vez      "2019-uploads/"           ✓       2021-01-01
```

ID is a GUID in fact, but mc shows only the shortest possible length, mc will automatically
understand it from full GUID really stored in bucket lifecycle configuration.


Notice: show command will also set random GUID for rules which have empty IDs (when lifecycle configuration is stored using other means other than mc, such as aws cli, etc..


#### Deleting/enabling/disabling a policy rule
```
$ mc ilm expiry enable myminio/bucket --id fgh
$ mc ilm expiry disable myminio/bucket --id gop
$ mc ilm expiry remove myminio/bucket --id vez
```

#### Set an expiry duration in days
```
$ mc ilm expiry set --days 7 --prefix "" myminio/bucket
Objects uploaded under `myminio/bucket/` will be automatically deleted after 7 days!
```

#### Set an expiry on specific date
```
$ mc ilm expiry set --date "oct 7, 2020" --prefix "uploads/" myminio/bucket
All objects under `myminio/bucket/uploads/` will be automatically deleted on 2020-10-07 00:00:00 +0000 MST
```

#### Used libraries
Parsing a date, very generic https://github.com/araddon/dateparse

**Comment by gwperry** [comment]
This would be awesome for those of us not using aws.  Are you looking to implement this soon?

**Comment by vadmeste** [comment]
> This would be awesome for those of us not using aws. Are you looking to implement this soon?

This is the PR related to the feature, https://github.com/minio/mc/pull/3097
