### ISSUE TITLE
Add options to preserve object create date in mirror and cp 

### ISSUE THREAD

**Issue by henrythefool** [minio/mc#2881]
## Expected behavior
There can be an option like `cp -p` in Linux to keep files' create date when moving them, such as `mc mirror -p` or `mc cp -p`.

## Actual behavior
There's no this kind of options in `mc mirror` or `mc cp`.

Sometimes I need to `mc mirror` between servers or buckets. 
But once mirrored from A to B,  B's objects are all newer than A. Then if I mirrored back from B to A, I have to overwrite the entire bucket.

## mc version
Version: 2019-08-29T00:40:57Z
Release-tag: RELEASE.2019-08-29T00-40-57Z
Commit-id: bd7564a2d4524335a594f0f4e10b06c033eb299c

**Comment by henrythefool** [comment]
If I mirror from A to B, then mirror back from B to A without `--overwrite`.
The mirror will automatically break and prompt me to use the `--overwrite` option.

**Comment by harshavardhana** [comment]
Additional metadata is not a good idea to store this information. mc mirror is not meant for that @henrythefool

**Comment by harshavardhana** [comment]
We have decided to introduce this as `-a` option for both `mirror` and `cp`  - option `-a` will preserve the entire stat() calls something similar to s3cmd style. 

```
content-length:227
content-type:text/plain
host:localhost:9000
x-amz-content-sha256:d5f9719f90a663345b853c299745b9c14f30f69f491ece1df6b1942f19915fa3
x-amz-date:20191015T051153Z
x-amz-meta-s3cmd-attrs:atime:1571087177/ctime:1570305453/gid:0/gname:root/md5:934e5a3bf854df990bb9b9e40802e413/mode:33188/mtime:1570305453/uid:0/uname:root
x-amz-storage-class:STANDARD
```

We are planning to add `x-amz-meta-mc-attrs` and also even fallback if `s3cmd-attrs` are present to preserve it both sides on filesystem as well as on object storage.
