### ISSUE TITLE
Make minio fails on FreeBsd12 

### ISSUE THREAD

**Issue by fiero05** [minio/mc#2883]
## Expected behavior
Make minio should work once import it via ports on Freebsd

## Actual behavior

Make fails with below message 

===>  Patching for minio-2019.06.15.23.07.18
===>  Applying FreeBSD patches for minio-2019.06.15.23.07.18
===>   minio-2019.06.15.23.07.18 depends on package: go>=1.9.4 - found
===>  Configuring for minio-2019.06.15.23.07.18
===>  Building for minio-2019.06.15.23.07.18
cd /usr/ports/www/minio/work/minio-RELEASE.2019-06-15T23-07-18Z/src/github.com/minio/minio ;  /usr/bin/env XDG_DATA_HOME=/usr/ports/www/minio/work  XDG_CONFIG_HOME=/usr/ports/www/minio/work  HOME=/usr/ports/www/minio/work PATH=/usr/ports/www/minio/work/.bin:/rescue:/usr/build/buildroot/tools/x86_FBSD1X_gcc4.2.4/usr/bin:/rescue:/usr/build/buildroot/tools/x86_FBSD1X_gcc4.2.4/usr/bin:/rescue:/usr/build/buildroot/tools/x86_FBSD1X_gcc4.2.4/usr/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/ykulkarni/bin:/usr/build/pzb/home/bin:/usr/build/buildroot/tools/x86_FBSD1X_gcc4.2.4/usr/bin:/usr/build/buildroot/tools/x86_FBSD1X_gcc4.2.4/usr/bin:/usr/build/buildroot/tools/x86_FBSD1X_gcc4.2.4/usr/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  LIBDIR="/usr/lib"  CC="cc" CFLAGS="-O2 -pipe -DPANZURA_DEV -DPZ_LONGNAMES  -fstack-protector -fno-strict-aliasing"  CPP="cpp" CPPFLAGS=""  LDFLAGS=" -fstack-protector" LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -DPANZURA_DEV -DPZ_LONGNAMES -fstack-protector -fno-strict-aliasing "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" GOPATH=/usr/ports/www/minio/work/minio-RELEASE.2019-06-15T23-07-18Z CGO_ENABLED=0 go build  --ldflags '-X github.com/minio/minio/cmd.Version=2019-06-15T23:07:18Z -X github.com/minio/minio/cmd.ReleaseTag=RELEASE.2019-06-15T23-07-18Z -X github.com/minio/minio/cmd.CommitID=99bf4d0c429f04dbd013ba98840d07b759ae1702 -X github.com/minio/minio/cmd.GOPATH=/usr/ports/www/minio/work/minio-RELEASE.2019-06-15T23-07-18Z -s -w' -o /usr/ports/www/minio/work/minio-RELEASE.2019-06-15T23-07-18Z/bin/minio
vendor/github.com/minio/parquet-go/column.go:24:2: cannot find package "github.com/minio/minio-go/pkg/set" in any of:
	/usr/ports/www/minio/work/minio-RELEASE.2019-06-15T23-07-18Z/src/github.com/minio/minio/vendor/github.com/minio/minio-go/pkg/set (vendor tree)
	/usr/local/go/src/github.com/minio/minio-go/pkg/set (from $GOROOT)
	/usr/ports/www/minio/work/minio-RELEASE.2019-06-15T23-07-18Z/src/github.com/minio/minio-go/pkg/set (from $GOPATH)
*** Error code 1

Stop.
make: stopped in /usr/ports/www/minio
gmake[2]: *** [package/minio/minio.mk:13: _minio-real-build] Error 1
gmake[2]: Leaving directory '/usr/build/buildroot'
gmake[1]: *** [package/minio/minio.mk:9: /usr/build/pkg/All/minio-2019.06.15.23.07.18.txz] Error 2
gmake[1]: Leaving directory '/usr/build/buildroot'
gmake: *** [package/minio/minio.mk:9: minio-target-install] Error 2

## Steps to reproduce the behavior
make package

## mc version
- (paste output of `mc version`)

## System information

12.0-CURRENT FreeBSD 12.0-CURRENT #2 r332472: Fri Apr 13 09:11:25 PDT 2018     root@bob.pixel8networks.com:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

**Comment by harshavardhana** [comment]
We do not maintain FreeBSD port @fiero05 - you should ask the FreeBSD port maintainers.

**Comment by kannappanr** [comment]
Closing this based on the previous comment. Please feel free to reach out to us if you have further questions.
