### ISSUE TITLE
Deprecate mc session command

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#2893]
## Expected behavior
Deprecate `mc session` command and modify `cp` command to handle this scenario.

The new command will look like this
`mc cp -r -s /tmp/bin play/test`

In this case, you will create a session in `/tmp/mc/uniquename`

The file will have `read only` access for the account user who ran `mc`. Other users should not have any access.

On error, the session file is created under `/tmp/mc/uniquename`. Then a command is printed

mc: <ERROR> copy operation safely terminated. To resume operation `mc cp -r --resume /tmp/mc/uniquename`

When you are starting up `mc` if there are existing `session files` in the existing folder, we need to move it to `/tmp/mc`

Resuming the same `mc cp` operation would be via `mc cp --resume /tmp/mc/uniquename`

If attr `-s` is not passed, then session file is not created.

## Actual behavior
mc session resume - resumes previously saved sessions.

## Steps to reproduce the behavior
This is a breaking change. `cp` is quite slow for large datasets due to session building stage, most users gravitate towards using `mirror` instead without session.

## mc version
All versions

## System information
All OS

**Comment by kannappanr** [comment]
The changes are

```
1. The location of the session file and not the format of it

2. The command names will change. Will use the ones that I have in the issue for now. Once we finalize the options, we can use that.
3. If -s option is not passed, we do not generate a session file
```
