### ISSUE TITLE
mc gives error when copy huge bucket

### ISSUE THREAD

**Issue by WahyuMW** [minio/mc#2899]
I'm trying to copy bucket with 31 million object ( more than 20TB object) from ceph cluster to another ceph cluster  and it gives error : 

```
 mc: <ERROR> Unable to prepare URL for copying. XML syntax error on line 1: illegal character code U+0017
```
and the copy process is only copy for 2 TB object.

## mc version
- mc version RELEASE.2019-08-29T00-40-57Z

## System information
debian 10.0 
Linux debian 4.19.0-5-cloud-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux

**Comment by vadmeste** [comment]
It looks like minio-go needs to set encodingType to url by default in all operations so we can avoid illegal characters in xml documents.

**Comment by kannappanr** [comment]
@WahyuMW minio-go has been fixed and released. mc has that version in the go.mod file. Next release should have the fix.

**Comment by kannappanr** [comment]
@WahyuMW closing this issue. As `mc` has been released. Please try with `mc` version `RELEASE.2019-09-20T00-09-55Z`
