### ISSUE TITLE
Commands returning URL query-escaped filenames

### ISSUE THREAD

**Issue by coffee-squirrel** [minio/mc#2903]
## Expected behavior
`mc ls` and `mc find` display true filenames without encoding (e.g. `backup-20190912.2002.10+UTC.zip`)

## Actual behavior
`mc ls` and `mc find` (at minimum) are returning URL query-escaped filenames (e.g. `backup-20190912.2002.10%2BUTC.zip`)

Potentially introduced with minio/minio-go#1161?

## Steps to reproduce the behavior
1. Have a bucket with files whose names contain characters that should be escaped in a URL query string ([list of characters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#Description); e.g. `backup-20190912.2002.10+UTC.zip`, `hello(world).txt`)
2. Use `mc` @ `RELEASE.2019-09-20T00-09-55Z` to either `mc ls bucket/path/to/files` or `mc find bucket/path/to/files` (also tested with `--json`)
3. Observe the returned filenames are URL query-encoded (e.g. `+` is `%2B`, `(` is `%28`, `)` is `%29`), and do not reflect the true filename.

## mc version
```
Version: 2019-09-20T00:09:55Z
Release-tag: RELEASE.2019-09-20T00-09-55Z
Commit-id: 57a9c6fab2064c30a036c1ff7f044f0be483cd8d
```

## System information
* Server (`minio`): `RELEASE.2019-05-23T00-29-34Z`
* Server OS:  Windows Server 2016
* Client (`mc`): `RELEASE.2019-09-20T00-09-55Z`
* Client OS:  Ubuntu 18.04.2

**Comment by coffee-squirrel** [comment]
I've verified `mc.RELEASE.2019-09-11T20-17-47Z` returns the expected (unencoded) filenames.

**Comment by harshavardhana** [comment]
Yes this is the new change @coffee-squirrel - we will convert it back for humanized view appropriately..

**Comment by coffee-squirrel** [comment]
Just confirming `mc.RELEASE.2019-09-24T01-36-20Z` fixed the issue reported.  Thanks!

**Comment by harshavardhana** [comment]
:cake:
