### ISSUE TITLE
Add a flag to allow throttling of operations

### ISSUE THREAD

**Issue by khumps** [minio/mc#2907]
It would be nice if, when running operations, I could tell the client to put a strict cap on requests per second sent. For processes such as `mc mirror --watch` this will allow traffic to still be handled properly by a cluster if a large influx of operations happens from the `mirror` that causes it to consume all of the bandwidth, I/O, etc

**Comment by kannappanr** [comment]
@khumps Thanks for filing this issue. Will talk internally and see if we can handle it easily within `mc` if not try to provide a way to handle it outside of `mc`.

**Comment by khumps** [comment]
Any status on if/when this might get implemented. This would really be helpful, especially when running lots of concurrent mirrors to prevent a cluster from getting pegged for resources

**Comment by harshavardhana** [comment]
Not right now, we don't have enough cycles to work on this yet @khumps - feel free to send a PR if you have ideas on implementing it.

**Comment by khumps** [comment]
@harshavardhana Uber has a implementation of golang rate limiting [here](https://github.com/uber-go/ratelimit) I don't think network specific limiting is really the issue as making sure you aren't overloading on OPS. Potentially you could put one of those in front of every operation that mc provides and have it default to their struct that has no limit. I could take a peruse of where this would need to be inserted but any suggestions on where to start to apply it to would be greatly appreciated
