### ISSUE TITLE
mc rm has encoding issues

### ISSUE THREAD

**Issue by tuempeltaucher** [minio/mc#2922]
## Expected behavior
mc ls backup/xxx/Tabelle\ Navi.xlsx
[2019-08-20 09:26:09 UTC]   10KiB Tabelle+Navi.xlsx

mc rm backup/xxx/Tabelle\ Navi.xlsx

## Actual behavior
mc rm backup/xxx/Tabelle\ Navi.xlsx 
mc: <ERROR> Failed to remove `backup/xxx/Tabelle Navi.xlsx`. Target `backup/xxx/Tabelle Navi.xlsx` not found.

## mc version
/ # mc version
Version: 2019-10-02T19:41:02Z
Release-tag: RELEASE.2019-10-02T19-41-02Z
Commit-id: 26b9044a8676a8c5ff79a6054343e5be74c35135

## System information
Minio Server: 2019-10-02T21:19:38Z

**Comment by vadmeste** [comment]
@tuempeltaucher Thanks for reporting this, I am able to reproduce this, some unit tests are missing in minio-go that's why this wasn't detected, I am going to write a new unit test also for this

**Comment by vadmeste** [comment]
This should be fixed in the last release with this commit https://github.com/minio/minio-go/commit/bb93a2c4f0cb3f2357e0dbfcf9d196bbf20c7fcb

Closing this..
