### ISSUE TITLE
Autocompletion of 2019-10-09T22:54:57Z doesn't properly escape the spaces

### ISSUE THREAD

**Issue by titansmc** [minio/mc#2928]
## Expected behavior
Autocompletion would escape the special characters
## Actual behavior
it doesn't escape them
```
[moscardo@login ~]$ mc cp lfs/git-lfs/V de Vendetta HDRip www.DivxTotaL.com.avi .
mc: <ERROR> Unable to validate source lfs/git-lfs/V
```
## Steps to reproduce the behavior
- Upload a file with spaces
- Copy the file back using autocompletion
## mc version
```
Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e
```

## System information
Client Ubuntu 18.04 with latest
Server CentOS 7 with latest

**Comment by vadmeste** [comment]
Thanks for opening this issue @titansmc 

I sent an proposal to posener/complete library to fix this, https://github.com/posener/complete/issues/101.

If the proposal is accepted, I will implement it in the library itself and incorporate it here

**Comment by vadmeste** [comment]
I will do this after I finish with versioning, I expect this will take one day to replace poserner/complete with another simple solution

**Comment by invidian** [comment]
Would be nice to get this done. It makes autocompletion useless in certain cases.
