### ISSUE TITLE
mc client does not update Minio (remote server) when new folder is created on a local pc

### ISSUE THREAD

**Issue by Racklogic** [minio/mc#2929]
## Expected behavior
When using the mirror function, mc client should always mirror the new local folder on the minio server.

## Actual behavior
mc client does not update Minio (remote server) when a new folder is created on a local pc. 

## Steps to reproduce the behavior
example syntax
./mc mirror -w --overwrite --remove temp/ minio/backups/
On a local (linux) pc create the /home/username/temp folder
In the temp folder, create a folder named "test"
On the Minio server, observe through the web gui that this new "test" folder is not present - nor is it present through a browser refresh.
Stop/start mc client and observe on the minio server (with a browser refresh) that the new "test" folder is now present.

## mc version
- (paste output of `mc version`)
Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e
## System information

**Comment by harshavardhana** [comment]
This not possible on filesystems - it is lack of inotify support for directory creates. Inotify probes do not capture this event so have no way of knowing we need to mirror the content.

**Comment by harshavardhana** [comment]
Although this is possible if both ends are MinIO server.

**Comment by Racklogic** [comment]
@harshavardhana 
Thanks for the explanation. I'll do a workaround with some scripting.
