### ISSUE TITLE
'mc rm -r --force <alias>/<bucket>' cannot remove filesystem multilevel subdirectories (=prefixes)

### ISSUE THREAD

**Issue by ebozduman** [minio/mc#2930]
## Expected behavior
`mc rm -r --force <alias>/<bucket>` is supposed to clean up all the objects, prefixes, files, or any item in the target location, regardless of how they are created: by the filesystem or by the object storage.

On the other hand, this could be considered as an expected behavior. The obvious reason is; in object storage world, we don't expect prefixes to be left behind lingering around as the object name is actually includes the prefixes and both is removed together when the object is removed, provided that there is no other object is using the same prefix. Prefixes are considered to be the directories in filesystem world. So, an empty directory is not expected and hence prefix without an object is not not touched as they are assumed to be already cleaned up.
If we choose not to change this behavior, then we might want to explain it in an appropriate section in our documentation.

## Actual behavior
```
$ mc ls -r myminio/nested
[2019-10-15 18:06:36 PDT]      0B a
[2019-10-15 18:07:27 PDT]      0B xxx/a/b/c/zzz
[2019-10-15 17:57:56 PDT]      0B xxx/level1/
$ mc rm -r --force myminio/nested/
Removing `myminio/nested/a`.
Removing `myminio/nested/xxx/a/b/c/zzz`.
$ mc ls -r myminio/nested
[2019-10-15 17:57:56 PDT]      0B xxx/level1/
```
## Steps to reproduce the behavior
Just create an empty subdirectory in your data location and then try to remove it:
```
$ mkdir -p <data-location>mybucket/a/b/c`
$ mc rm -r --force <alias>/mybucket
```
## mc version
Any version

**Comment by Praveenrajmani** [comment]
@ebozduman looks like we are purposefully skipping the prefix levels in while removing recursively. https://github.com/minio/mc/blob/master/cmd/rm-main.go#L283
