### ISSUE TITLE
Non-leading slashes in object name prevent deletion of this object on MinIO gateway instance

### ISSUE THREAD

**Issue by Shappenny** [minio/mc#2935]
## Expected behavior
An object containing multiple, non-leading slashes in its name, e.g., `minio/testbucket/test///new_.json`, should be removable with `mc rm minio/testbucket/test///new_.json`.

## Actual behavior
An object containing multiple, non-leading slashes in its name, e.g., `minio/testbucket/test///new_.json`, is not removable with `mc rm minio/testbucket/test///new_.json`.  However, it can be copied with `mc cp minio/testbucket/test///new_.json`.

## Steps to reproduce the behavior
With `minio` configured with credentials with proper access permissions, as a gateway to a locally hosted MinIO cluster.

Exact commands and output:
```bash
test@test-ubuntu:~$ mc cp new_.json minio/testbucket/test/new_.json
new_.json:                        18.90 MiB / 18.90 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 76.42 MiB/s 0s
test@test-ubuntu:~$ mc cp new_.json minio/testbucket/test///new_.json
new_.json:                        18.90 MiB / 18.90 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 75.89 MiB/s 0s
test@test-ubuntu:~$ mc stat minio/testbucket/test/
Name      : new_.json
Date      : 2019-10-22 10:43:10 PDT 
Size      : 19 MiB 
ETag      : 20000f00cb67ba552b3b8986afcc49ad-1 
Type      : file 
Metadata  :
  Content-Type: application/json 
Encrypted :
  X-Amz-Server-Side-Encryption: AES256 

Name      : new_.json
Date      : 2019-10-22 10:43:10 PDT 
Size      : 19 MiB 
ETag      : 20000f00cb67ba552b3b8986afcc49ad-1 
Type      : file 
Metadata  :
  Content-Type: application/json 
Encrypted :
  X-Amz-Server-Side-Encryption: AES256 

test@test-ubuntu:~$ mc rm new_.json minio/testbucket/test///new_.json
Removing new_.json.
mc: <ERROR> Failed to remove minio/testbucket/test///new_.json. Target minio/testbucket/test///new_.json not found.
test@test-ubuntu:~$ mc rm new_.json minio/testbucket/test//new_.json
mc: <ERROR> Failed to remove new_.json. Target object is not found 
mc: <ERROR> Failed to remove minio/testbucket/test//new_.json. Target minio/testbucket/test//new_.json not found.
test@test-ubuntu:~$ mc stat minio/testbucket/test/
Name      : new_.json
Date      : 2019-10-22 10:43:10 PDT 
Size      : 19 MiB 
ETag      : 20000f00cb67ba552b3b8986afcc49ad-1 
Type      : file 
Metadata  :
  Content-Type: application/json 
Encrypted :
  X-Amz-Server-Side-Encryption: AES256 

Name      : new_.json
Date      : 2019-10-22 10:43:10 PDT 
Size      : 19 MiB 
ETag      : 20000f00cb67ba552b3b8986afcc49ad-1 
Type      : file 
Metadata  :
  Content-Type: application/json 
Encrypted :
  X-Amz-Server-Side-Encryption: AES256 

test@test-ubuntu:~$ mc rm new_.json minio/testbucket/test/new_.json
mc: <ERROR> Failed to remove new_.json. Target object is not found 
Removing minio/testbucket/test/new_.json.
test@test-ubuntu:~$ mc stat minio/testbucket/test/
Name      : new_.json
Date      : 2019-10-22 10:43:10 PDT 
Size      : 19 MiB 
ETag      : 20000f00cb67ba552b3b8986afcc49ad-1 
Type      : file 

test@test-ubuntu:~$ mc cp minio/testbucket/test/new_.json .
mc: <ERROR> Failed to copy https://storagegw.corp.xnor.ai/testbucket/test/new_.json. Object does not exist
test@test-ubuntu:~$ mc cp minio/testbucket/test///new_.json .
...testbucket/test///new_.json:  18.90 MiB / 18.90 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 72.14 MiB/s 0s
test@test-ubuntu:~$ mc rm minio/testbucket/test///new_.json
mc: <ERROR> Failed to remove minio/testbucket/test///new_.json. Target minio/testbucket/test///new_.json not found.
```

## mc version
Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e

## MinIO version
Gateway: 2019-10-02T21:19:38Z
Backend: 2019-10-02T21:19:38Z

## System information
4.15.0-66-generic #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@Shappenny Can you let us know what the backend is here and how you started `MinIO` instance?

**Comment by kannappanr** [comment]
@Shappenny I was unable to reproduce the issue in `S3 Gateway` with `AWS S3` as backend. I see that you have `minIO` itself as the backend. In the case of `minio` both `minio/testbucket/test/new_.json` and `minio/testbucket/test///new_.json` will be the same.

**Comment by Shappenny** [comment]
Sorry for the delay @kannappanr. The MinIO version running on both our gateway node and the backend cluster were both `2019-10-02T21:19:38Z`.

**Comment by Shappenny** [comment]
> @Shappenny I was unable to reproduce the issue in `S3 Gateway` with `AWS S3` as backend. I see that you have `minIO` itself as the backend. In the case of `minio` both `minio/testbucket/test/new_.json` and `minio/testbucket/test///new_.json` will be the same.
Hmm, interesting. This isn't the behavior I saw using `mc` to talk to `minio`, though.

Interestingly, I tried this again using the `play` host configured by default in `mc`, and *did not* find this behavior. That is, both `play/testbucket/test/new_.json` and `play/testbucket/test///new_.json` are the same. I wonder if this is specific to having a MinIO gateway in the middle?

**Comment by kannappanr** [comment]
I tested on Gateway with `Play` as my backend and was unable to reproduce it.

**Comment by Shappenny** [comment]
Bizarre. I updated my previous comment, but for clarity:

I also tried using minio-py (version 4.0.20) talking directly to our MinIO backend cluster (no gateway), uploading the object https://server.test/minio/testbucket/testdata///new_file1.txt. Calling stat_object on this object returned the expected object info struct, <Object: bucket_name: testbucket object_name: b'testdata///new_file1.txt' last_modified: time.struct_time(tm_year=2019, tm_mon=10, tm_mday=25, tm_hour=0, tm_min=6, tm_sec=24, tm_wday=4, tm_yday=298, tm_isdst=0) etag: 6cd3556deb0da54bca060b4c39479839 size: 13 content_type: application/octet-stream, is_dir: False, metadata: {'Content-Type': 'application/octet-stream', 'X-Amz-Server-Side-Encryption': 'AES256'}>.
Calling stat_object on https://server.test/minio/testbucket/testdata/new_file1.txt returns a minio.error.NoSuchKey error.
