### ISSUE TITLE
Fail to preserve bucket policy upon -a option used in mirror

### ISSUE THREAD

**Issue by sinhaashish** [minio/mc#2936]
## Expected behavior
Policy should be preserved in destination when `-a` is used in mirror

## Actual behavior
Policy not copied to destination bucket .
## Steps to reproduce the behavior

Configue `myminio` and `myminio1` to two different minio servers
Steps to replicate:
Issue 1: Policy not reflecting in source bucket.
```
1. mc mb myminio/source
2. mc policy set download myminio/source
3. mc policy list myminio/source
4. mc cp ~/Downlods/test.png myminio/source
4. mc mirror -a myminio myminio1
5. mc policy list myminio1/source
```

Issue 2: Not able to create bucket. 
```
1. mc mb myminio/source
2. mc policy set download myminio/source
3. mc policy list myminio/source
4. mc cp ~/Downlods/test.png myminio/source
5. mc mirror -a myminio/source  myminio1
```
The console shows 
```
mc: <ERROR> Cannot created bucket in `myminio1`. Bucket name cannot be empty.
```

## mc version
- (paste output of `mc version`)

**Comment by nitisht** [comment]
Fixed by #2938
