### ISSUE TITLE
Can't change server config: Cannot get server configuration file. sio: unsupported version.

### ISSUE THREAD

**Issue by Meshkati** [minio/mc#2948]
## Expected behavior
Get and set configs using minio client.
## Actual behavior
It gives me `mc: <ERROR> Cannot get server configuration file. sio: unsupported version.`. Other commands like ls, cp, etc. are working.
## Steps to reproduce the behavior
1. `mc admin config get minio-opr`
## mc version
- (paste output of `mc version`)
MC: 
RELEASE.2019-09-24T01-36-20Z
Minio:
2019-10-22T07:47:32Z
Note that I build minio binary by myself using `make build`, but without any changes.

**Comment by vadmeste** [comment]
@Meshkati this means you need to upgrade to the latest mc version, it is also good to upgrade to the latest Minio server also

**Comment by kannappanr** [comment]
@Meshkati Please upgrade mc to the latest version and let us know if you still see this issue

**Comment by Meshkati** [comment]
@vadmeste I have the same error with `DEVELOPMENT.2019-11-03T07-22-20Z` version of mc :(

**Comment by harshavardhana** [comment]
> @vadmeste I have the same error with `DEVELOPMENT.2019-11-03T07-22-20Z` version of mc :(

@Meshkati do not use the development version - it is not released yet and has breaking changes. If you are building binaries by yourself then it won't work at the moment - you have to use released binaries to make MinIO and `mc` talk to each other.

**Comment by harshavardhana** [comment]
Server and mc has been released - please upgrade. Closing this issue.
