### ISSUE TITLE
X-Amz-Website-Redirect-Location unsupported user defined metadata name

### ISSUE THREAD

**Issue by JakeDEvans** [minio/mc#2949]
## Expected behavior
copy data between s3 servers/buckets

## Actual behavior
copy fails
```
mc: <ERROR> Failed to copy `http://scality:8000/bucket/file.zip`. X-Amz-Website-Redirect-Location unsupported user defined metadata name

```

## Steps to reproduce the behavior
 mc cp --recursive scality/test minio/test --debug
copy data from /scality/s3server to minio

## mc version
```
mc version
Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e
```

**Comment by JakeDEvans** [comment]
Can I ignore/drop this header somehow?

**Comment by harshavardhana** [comment]
`mc` doesn't add this @JakeDEvans this is a server issue we are simply preserving what is present on the server - user-defined metadata is of form `x-amz-meta` so I am not sure why your server is complaining about a different header.

**Comment by JakeDEvans** [comment]
@harshavardhana figured that, was hoping for a way to strip the header, turns I can dump the data to disk first and that'll work.

```
mc cp -r scality/test /tmp/test
mc cp -r /tmp/test minio/test
```

**Comment by JakeDEvans** [comment]
Workaround no longer working on `RELEASE.2020-04-04T05-28-55Z`

**Comment by harshavardhana** [comment]
@JakeDEvans `X-Amz-Website-Redirect-Location` is not properly preserved  - can you provide the `--debug` output of error that you see?

**Comment by JakeDEvans** [comment]
I need an --ignore-invalid-headers option.

**Comment by harshavardhana** [comment]
> I need an --ignore-invalid-headers option.

Please post the --debug, we are not there yet.
