### ISSUE TITLE
rewatching an in-progress heal shows the correct total time but not correct total items/data healed

### ISSUE THREAD

**Issue by khumps** [minio/mc#2954]
## Expected behavior
if I start a heal then close the heal command, it will continue to run in the background and keep track of the total items/amount of data checked/healed as well as the time it has been running
## Actual behavior
It only keeps track of the total time the heal has been running
## Steps to reproduce the behavior
run an `mc admin heal`, close the heal and re-open it
## mc version
Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e

**Comment by vadmeste** [comment]
@khumps healing is run in background, however if you have too many files, healing will pause itself until you run mc again, so mc can get the complete status of healing without missing any important status.

But that's true, mc is confusing users here. I think this issue needs to be discussed internally.

**Comment by khumps** [comment]
@vadmeste my understanding was that issuing a heal command simply triggered the process on the cluster? does the cluster not internally keep track of how many objects its healed, how much data it's traversed and/or healed, etc?

**Comment by vadmeste** [comment]
> @vadmeste my understanding was that issuing a heal command simply triggered the process on the cluster? does the cluster not internally keep track of how many objects its healed, how much data it's traversed and/or healed, etc?

Currently it stores 10k healing objects information, after that it pauses itself until mc consumes some of these information.

**Comment by khumps** [comment]
@vadmeste so this background heal really isn't background then 😞 it doesn't really appear to stop either from testing except for very brief periods that don't appear to be affected by me running the command to check on it

**Comment by vadmeste** [comment]
> @vadmeste so this background heal really isn't background then  it doesn't really appear to stop either from testing except for very brief periods that don't appear to be affected by me running the command to check on it

It will suspend after checking 10k objects which can take a while depending of the size of your objects.

**Comment by khumps** [comment]
@vadmeste objects are small (between 256k and 5MB)
