### ISSUE TITLE
mc mirror will re-upload files with '+' character in filename on Windows hosts

### ISSUE THREAD

**Issue by juv** [minio/mc#2970]
## Expected behavior
Minio Client with mirror command uploads all updated files

## Actual behavior
Minio Client re-uploads files with a '+' character in the file name on Windows hosts.
Every time you run the mc mirror command, these files are tried (?) to be uploaded the Minio. Looks like some encoding problems occur because of the special character '+'.

Adding the --json flag makes this pretty obvious.
In my case, all files are uploaded as expected but the ones with a '+' in the file name are handled in a unexpected way.

## Steps to reproduce the behavior
Put a file with '+' character in a directory that is being mirrored by mc.

## mc version
RELEASE.2019-10-09T22-54-57Z

## System information
Windows Server 10, Version 1709, Build 16299.125

**Comment by kannappanr** [comment]
@juv Thanks for reporting the issue. We will try this out and get back to you

**Comment by BigUstad** [comment]
@juv  I tried this scenario with variations. This is no longer happening. We can reopen this bug if we see it again.
