### ISSUE TITLE
mc mirror with --watch flag stops mirroring on Windows after a certain amount of time

### ISSUE THREAD

**Issue by juv** [minio/mc#2971]
## Expected behavior
mc mirror with --watch flag continuously uploads all files that are added/changed in a directory to Minio

## Actual behavior
The mirroring stops after a certain amount of time on a Windows Network File Share. The error is reproducible, however the amount of time when mc stops mirroring appears to be somewhat random. Sometimes its a few hours, sometime its 2 days. 

The biggest problem of this is that there are no error logs and mc looks like it is still up and running but the changes to the directory are not being mirrored to Minio anymore. So the mc instance will sit and do nothing until it is restarted.

When restarting mc instance with the exact same command and flags, the file changes are noticed by mc and then uploaded to Minio. 

## Steps to reproduce the behavior
Connect a mc with mirror command and --watch flag to a Windows Network File Share on a Windows Server. Make sure to continuously change files or upload new files to the directory. After some time the retrieval of updates on this directory are not fetched anymore. Only a restart of the mc instance helps then. 

## mc version
RELEASE.2019-10-09T22-54-57Z

## System information
Windows Server 10, Version 1709, Build 16299.125

**Comment by bigorn0** [comment]
Hello,

I'm facing the same but on Linux (Centos) after upgrading to the same RELEASE while the same command was perfectly reliable in previous version `RELEASE.2019-10-02T19-41-02Z`

**Comment by harshavardhana** [comment]
Thanks for reporting we shall take a look @bigorn0 @juv

**Comment by bigorn0** [comment]
@harshavardhana I wasn't seeing anything useful as troubleshooting starting point in the logs but if you need some inputs happy to help/test, just tell me how to proceed.

**Comment by harshavardhana** [comment]
@bigorn0 @juv can you update to latest mc and server and see if it's reproducible still?

**Comment by harshavardhana** [comment]
Closing this as not reproducible at the moment, please re-open if seen again @bigorn0

**Comment by juv** [comment]
Sorry, for some reason, I missed the email notification before christmas when you asked us to update and retest it. I will let you know if this is still reproducible on the newest version.

**Comment by harshavardhana** [comment]
> Sorry, for some reason, I missed the email notification before christmas when you asked us to update and retest it. I will let you know if this is still reproducible on the newest version.

Thanks @juv

**Comment by juv** [comment]
I can confirm that it works. Thanks for the fix 👍

Harshavardhana <notifications@github.com> schrieb am Do. 6. Feb. 2020 um
03:07:
