### ISSUE TITLE
unable to get and set minio server setting with mc compiled from master

### ISSUE THREAD

**Issue by kirannittur** [minio/mc#2972]
## Expected behavior
should be able to get/set server admin config from minio client.
I am using minio server from master branch so i built minio client also from master branch and when i try to get the config to enable compression i am getting below error. Is there any workaround
mc: <ERROR> Cannot get help for the sub-system: json: unknown field "audit_webhook".
## Actual behavior
mc admin config get myminio/
mc: <ERROR> Cannot get help for the sub-system: json: unknown field "audit_webhook".
## mc version
Version: DEVELOPMENT.GOGET
Release-tag: DEVELOPMENT.GOGET
Commit-id: DEVELOPMENT.GOGET
- (paste output of `mc version`)

## System information
windows server 2008 r2

**Comment by harshavardhana** [comment]
mc is not released yet, once server and client are released it will work fine..

Please use released version for now, with latest released version of server.
