### ISSUE TITLE
[Feature Request] Download Directory Contents as ZIP

### ISSUE THREAD

**Issue by toni-moreno** [minio/mc#2985]
## Expected behavior

I would like download a complete Directory as ZIP file from the minio client

something like

```
mc zip s3/backups/2005/December/
```

## Actual behavior

Only `mc cat` for single files, and not zipped.

## mc version
```
$ mc version
Version: 2019-12-05T13:57:34Z
Release-tag: DEVELOPMENT.2019-12-05T13-57-34Z
Commit-id: f3b2d5471fc7769dfc764f200d8ed5831303090a
```

**Comment by harshavardhana** [comment]
Feel free send a PR

**Comment by juniorschen** [comment]
@harshavardhana 
This has already been implemented :?

**Comment by harshavardhana** [comment]
> @harshavardhana
> This has already been implemented :?

Nope feel free to send a PR

**Comment by i0x71** [comment]
While sounds like a great idea, this is rather difficult to implement if your bucket is n terrabytes in size.
