### ISSUE TITLE
Feature Request: ability to redact information from output(especially debug output)

### ISSUE THREAD

**Issue by khumps** [minio/mc#3001]
If I am asked to send in logs to you, especially the debug/verbose ones, they contain a lot of sensitive information.

It would make it a lot easier if it could do some sort of scrubbing on the information, even on a basic level such as redacting IPs/hostnames, credentials(including the usernames) as well as bucket and/or file names

**Comment by harshavardhana** [comment]
Just use --anonymous @khumps

**Comment by khumps** [comment]
@harshavardhana I am talking about the client, is that something that is in master branch? I don't see `--anonymous` and it doesnt seem to allow me to pass that flag for rm, ls, or any other commands

**Comment by kannappanr** [comment]
@khumps Will check internally and get back to you on anonymizing `mc` debug output
