### ISSUE TITLE
mc event add should provide more verbose output when there is an error

### ISSUE THREAD

**Issue by khumps** [minio/mc#3006]
## Expected behavior
Be more specific on the error that occurs when an event add fails (ex. invalid ARN, invalid bucket name, etc)
## Actual behavior
Generic, cannot enable notifications
## mc version
Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e

**Comment by kannappanr** [comment]
@khumps 

In the following example, I have neither the ARN nor the bucket

```
$ mc event add myminio/mybucket arn:aws:sqs:us-west-2:444455556666:your-queue
mc: <ERROR> Cannot enable notification on the specified bucket. The specified bucket does not exist.
```
So, if the bucket does not exist, `MinIO` is printing the correct error.

Now, when I do create the bucket and try it again

```
$ mc mb myminio/mybucket
Bucket created successfully `myminio/mybucket`.
$ mc event add myminio/mybucket arn:aws:sqs:us-west-2:444455556666:your-queue
mc: <ERROR> Cannot enable notification on the specified bucket. A specified destination ARN does not exist or is not well-formed. Verify the destination ARN.
```
I believe these are already covered and closing this as working. Please feel free to reach out to us if you feel otherwise. Also, an example for us to repro would be good.

**Comment by harshavardhana** [comment]
Actually, there is a bug in server in-fact 

```
mc event add play/testbucket arn:minio:sqs::us-west-2:1
Successfully added arn:minio:sqs::us-west-2:1

mc event add play/testbucket arn:minio:sqs::us-west-2:2
Successfully added arn:minio:sqs::us-west-2:2

mc event add play/testbucket arn:minio:sqs::us-west-2:3
Successfully added arn:minio:sqs::us-west-2:3
```

```
mc event list play/testbucket/
arn:minio:sqs:us-east-1:us-west-2:1   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter: 
arn:minio:sqs:us-east-1:us-west-2:2   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter: 
arn:minio:sqs:us-east-1:us-west-2:3   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter: 
```

**Comment by harshavardhana** [comment]
@kannappanr what @khumps is saying is this

```
~ mc event add --debug myminio/testbucket arn:minio:sqs:us-east-1:1231
mc: <ERROR> Cannot enable notification on the specified bucket. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.
```

We should error out like `A specified destination ARN does not exist or is not well-formed. Verify the destination ARN.` so it is unexpected and users are unsure of what is the issue with their ARN
