### ISSUE TITLE
mc.exe fails with EvalSymlinks: too many links when using NTFS mounted folders

### ISSUE THREAD

**Issue by DerFireWal** [minio/mc#3011]
## Expected behavior

```
mc --config-dir $mc_cfg_dir stat D:\folder_x\folder_y\MNT_FOLDER\folder\subfolder1\subfolder2\image.jpg $mc_cfg_alias/$target_bucket/
Name      : image.jpg
Date      : 2018-01-15 08:35:35 CET 
Size      : 68 KiB 
Type      : file 
Metadata  :
  Content-Type: image/jpeg 
```

Would be the same for mc mirror, mc cp, mc ls etc.

## Actual behavior

```
mc_bin --config-dir $mc_cfg_dir stat D:\folder_x\folder_y\MNT_FOLDER\folder\subfolder1\subfolder2\image.jpg $mc_cfg_alias/$target_bucket/
mc.exe : mc.exe: <ERROR> Unable to stat `D:\folder_x\folder_y\MNT_FOLDER\folder\subfolder1\subfolder2\image.jpg`. EvalSymlinks: too many links.
```

```
mc --config-dir $mc_cfg_dir stat e:\folder\subfolder1\subfolder2\image.jpg $mc_cfg_alias/$target_bucket/
Name      : image.jpg
Date      : 2018-01-15 08:35:35 CET 
Size      : 68 KiB 
Type      : file 
Metadata  :
  Content-Type: image/jpeg 
```

## Steps to reproduce the behavior
Mount an NTFS formated drive into a NTFS sub-folder (MNT_FOLDER)
Assign a drive letter to the same drive (D:)

## mc version
RELEASE.2019-10-09T22-54-57Z

## System information
Windows Server 2016 Version 1607

**Comment by harshavardhana** [comment]
Looks like you do have recursive symlinks? @DerFireWal

**Comment by DerFireWal** [comment]
@harshavardhana Not quite sure what exactly would make it a recursive symlink. All "Windows" based command inside cmd or powershell work fine the same way as using the Windows Explorer. Any additional info I could provide?
