### ISSUE TITLE
mc cp --encrypt failed with error

### ISSUE THREAD

**Issue by AlexZept** [minio/mc#3013]
## Expected behavior
As I know the flag --encrypted should encrypt files on MinIO when the SSe_S3 is configured.

## Actual behavior
But the following command is failed with error:
`mc cp  --encrypt "minio/test"   etc/termcap minio/test   
mc: <ERROR> Failed to copy etc/termcap. We encountered an internal error, please try again.
`
## mc version
mc version RELEASE.2019-12-17T23-26-28Z

## System information
MinIO with KMS with Hashicorp Vault

`MINIO_SSE_AUTO_ENCRYPTION=off
MINIO_SSE_VAULT_AUTH_TYPE=approle
MINIO_BROWSER=off
MINIO_SSE_VAULT_APPROLE_ID=6e2a6d08-5479-77fe-4119-727ff11039e8
MINIO_SSE_VAULT_APPROLE_SECRET=22f036c8-cb29-1106-ef58-dddc1cdc32d3
MINIO_SECRET_KEY=fTv5P8LgbXKVfmMOve2i02IGz4G1kENnwDaLcl1y
MINIO_ACCESS_KEY=Wfrq1ZrAMGPDaXryXQPK
MINIO_SSE_VAULT_ENDPOINT=https://sec-key-management.default.svc.cluster.local:8200
MINIO_SSE_VAULT_KEY_NAME=my-minio-key
MINIO_PROMETHEUS_AUTH_TYPE=public`

**Comment by nitisht** [comment]
Thanks for reporting @AlexZept we'll take a look

**Comment by aead** [comment]
@AlexZept Does the server log - MinIO server output - show something when you encounter this error?

**Comment by kannappanr** [comment]
@AlexZept I tried this exact set of env variables, with the appropriate values for `MINIO_SSE_VAULT_APPROLE_ID`, `MINIO_SSE_VAULT_APPROLE_SECRET` and `MINIO_SSE_VAULT_KEY_NAME` and it seems to work. Like @aead mentioned if you can paste the server log, we might have some clue on what might be wrong

**Comment by AlexZept** [comment]
Sorry for long response,  I was tried to reproduce problem for collect the minio logs.
But it isn't reproduced. It looks like environment problem on my side.
Thank you for support. I think the ticket can be closed.
