### ISSUE TITLE
mc mirror --exclude behaves differently in a container versus the bare client

### ISSUE THREAD

**Issue by khumps** [minio/mc#3014]
## Expected behavior
I am running the processes `mc mirror --exclude "*clusterA_clusterC*" clusterA/bucket clusterB/bucket` and `mc mirror --exclude "*clusterA_clusterB*" clusterA/bucket clusterC/bucket` both in their own containers
if I create the file  clusterA/bucket/test-file-containerID-clusterA_clusterC using the command
`echo "" | mc pipe clusterA/bucket/test-file-containerID-clusterA_clusterC` I expect the file to be created in clusterA/bucket and then mirrored to clusterC/bucket but not clusterB because the rule `--exclude "*clusterA_clusterB*"` should cover that.
## Actual behavior
the file is mirrored to both clusterB and clusterC when it should only go to clusterC
if I run the identical commands from outside of containers, the behavior is expected
## mc version
Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e

**Comment by kannappanr** [comment]
@khumps Thanks for reporting this issue, we will reproduce this issue and get back to you

**Comment by vadmeste** [comment]
@khumps could you show you are running the mc mirror command inside the container ?

**Comment by khumps** [comment]
I don't have it up currently but what I would run to show you it is I would run `docker exec -it CONTAINER_ID /bin/sh` and then once inside the container run `ps aux` and the process list would show the mirror command running as such `mc mirror --exclude "*clusterA_clusterB*" clusterA/bucket clusterC/bucket`

**Comment by khumps** [comment]
It seems that those exterior quotes around the exclude statement were causing the issue, apparently they were being handled differently than expected. The issue has been resolved
