### ISSUE TITLE
mirror always fails with "`ListBucketPolicies` is not supported for `filesystem`"

### ISSUE THREAD

**Issue by coffee-squirrel** [minio/mc#3015]
## Expected behavior
`mc mirror` does not attempt to copy bucket policies unless `--preserve` or `-a` is specified, allowing the command to complete successfully when MinIO Server is of the `filesystem` type.

## Actual behavior
The `mc mirror` command (e.g. `mc mirror --overwrite --remove files/ "blobstore/my-bucket/some/path/"`) fails with an error like:
```
mc: <ERROR> Unable to copy bucket policies to `https://mydomain:8443/my-bucket/some/path/`. `ListBucketPolicies` is not supported for `filesystem`.
```

It looks like #2965 (specifically: https://github.com/minio/mc/pull/2965/files#diff-037c805435914444292ac1b753a92529R743) changed the behavior of `mc mirror`, making it so that copying bucket policies is always attempted rather than being conditional upon `--preserve` / `-a`.  The `filesystem` client [doesn't support `GetAccessRules`](https://github.com/minio/mc/blob/d92d2f0d4f1c21236cecf5a305bd6679b9527f66/cmd/client-fs.go#L1026-L1032), however.

## Steps to reproduce the behavior
1. Have a standalone/`filesystem` MinIO Server instance
2. Attempt to `mc mirror` some content to the MinIO Server instance
3. Note the aforementioned error

## mc version
```
Version: 2019-12-17T23:26:28Z
Release-tag: RELEASE.2019-12-17T23-26-28Z
Commit-id: d92d2f0d4f1c21236cecf5a305bd6679b9527f66
```

## System information
* Standalone Minio Server instance
* Server OS:  Windows Server 2016
* MinIO Server version:
```
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812
```

**Comment by harshavardhana** [comment]
It doesn't fail it is just a warning and it continues @coffee-squirrel

**Comment by coffee-squirrel** [comment]
@harshavardhana Sorry, you're completely right.  The content I was looking at was already in sync, so I misunderstood what was happening.  It is a bit odd to see an error, though.  I'll go ahead and close this out.

**Comment by harshavardhana** [comment]
Warning to be removed in PR #3018
