### ISSUE TITLE
mc mirror --watch: --quiet flag stopped working in latest release (2019-12-17T23-26-28Z)

### ISSUE THREAD

**Issue by gcmsch** [minio/mc#3017]
## Expected behavior
Specifying the `--quiet` flag for `mc mirror --watch` should disable the progress bar.

## Actual behavior
Progress bar appears whether `--quiet` is specified or not.

## Steps to reproduce the behavior
Call `mc mirror --watch` with `--quiet` flag.

## mc version
```
$ mc version
Version: 2019-12-17T23:26:28Z
Release-tag: RELEASE.2019-12-17T23-26-28Z
Commit-id: d92d2f0d4f1c21236cecf5a305bd6679b9527f66
```

## System information
CentOS Linux release 7.7.1908 (Core)

**Comment by harshavardhana** [comment]
Have you tried --json mode ?

**Comment by gcmsch** [comment]
Tried `--json` today, but does not make any difference, the progress bar is still visible.
My final try was `mc mirror --watch --quiet --json --no-color`, still got the progress bar.

**Comment by harshavardhana** [comment]
You are right it prints both progress and JSON which is odd will check @gcmsch
