### ISSUE TITLE
mirror failed randomly

### ISSUE THREAD

**Issue by RayRay10460** [minio/mc#3019]
## Expected behavior
mirror video slice by nginx rtmp failed randomly.

## Actual behavior
mirror will fail randomly.

## Steps to reproduce the behavior
1. mirror /etc/data/hls myminio/bucket.
2. mirror will fail randomly.

## mc version
- RELEASE.2019-10-09T22-54-57Z

## System information
linux

**Comment by harshavardhana** [comment]
I have no idea what your issue seems to be about, there isn't much information to help you out.

Will close this for now please reopen the issue with proper reproducers.
