### ISSUE TITLE
mc cp not working on wasabi copying between buckets

### ISSUE THREAD

**Issue by kallisti5** [minio/mc#3022]
I attempted to copy ~50 GiB between two buckets at wasabi.  I started the copy and let it run.

18 hours later...

```
[root@limerick r1beta1]# mc cp --recursive wasabi/haiku-repositories-test/ wasabi/haiku-repositories-us
...x86_64/r1~beta1_hrev52300/repo.sha256:  2.93 TiB / 2.98 TiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░┃ 46.34 MiB/s
...x86_64/r1~beta1_hrev53000/repo.sha256:  2.93 TiB / 2.98 TiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░┃ 46.34 MiB/s...evel-r1~beta1_hrev53050-1-x86_64.hpkg:  2.93 TiB / 2.98 TiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░┃ 46.34 MiB/s 18h26m56s
```

2.98TiB?!?

mc version RELEASE.2019-12-17T23-26-28Z

![deleted](https://user-images.githubusercontent.com/100110/71416925-4a944600-2628-11ea-906a-9172b4715c4e.png)

Wasabi shows 1.3TiB deleted, 650 GiB total stored.   MC just *blew* us by our billing for the next 3 months and tripled our costs. What the hell was it doing?

**Comment by harshavardhana** [comment]
No idea let's answer a few questions

- does wasabi support server side copy operation?
- did you have 2.93TiB to transfer?

mc calculates this by Listing object storage - you can compute this by doing `mc du` if that results in 2.98TiB and you don't have that much data then Wasabi is doing something here.

So please verify these things first and let us know.

**Comment by kallisti5** [comment]
Hi!

mc du --depth 1 wasabi/haiku-repository-test

Shows ~50GiB

**Comment by harshavardhana** [comment]
@kallisti5 2.98TiB is perhaps what `mc cp` calculated based on some timeouts that it might have seen, you are better off using `mc mirror` instead of `mc cp` which tries to build session locally.

**Comment by kallisti5** [comment]
Mc mirror had the same issue oddly. It got 600GiB in before I cancelled it.   What's odd is the deleted count that wasabi is calculating is there any reason mirror or cp will delete from the target bucket?

**Comment by harshavardhana** [comment]
mc never deletes unless you asked for in `mc mirror` with --remove @kallisti5

**Comment by harshavardhana** [comment]
The issue here is at Wasabi end its returning incorrect amount of content for us to copy.

**Comment by kallisti5** [comment]
What's weird is mc has been working fine with wasabi until I updated to the December 2019 version.  Older versions continue to upload to it as expected (different scenario though)

**Comment by harshavardhana** [comment]
> What's weird is mc has been working fine with wasabi until I updated to the December 2019 version. Older versions continue to upload to it as expected (different scenario though)

the only change we did was `c.api.ListObjectsV2WithMetadata` which basically adds an extra query param which works fine with AWS S3 - I am suspecting Wasabi is misbehaving here? are you using `-`-a` to preserve metadata?

Also, can you try using `mc` older release and see if you see the same problem? if not we can check on our end what might be causing this. 

Since we don't have access to Wasabi we can't test it ourselves.

**Comment by kallisti5** [comment]
$5/month up to 1TiB storage with no bandwidth caps. :-D.  I'll test and report back with the older version number.

**Comment by harshavardhana** [comment]
> $5/month up to 1TiB storage with no bandwidth caps. :-D. I'll test and report back with the older version number

Well, we use MinIO we don't need Wasabi :-)

**Comment by kannappanr** [comment]
@kallisti5 Please let us know if you had a chance do the tests that were requested.

**Comment by kannappanr** [comment]
@kallisti5 Closing this issue as stale. Please feel free to reach out to us with the requested information.
