### ISSUE TITLE
mc: <ERROR> Unable to update the server. Failed to parse server response.

### ISSUE THREAD

**Issue by mentalinc** [minio/mc#3023]
## Expected behavior
mc updates the minio server instances

## Actual behavior
The below error message is provided when running /opt/minio/mc admin update TARGET
mc: <ERROR> Unable to update the server. Failed to parse server response.

## Steps to reproduce the behavior
run either 
 sudo /opt/minio/mc admin update TARGET
/opt/minio/mc admin update TARGET

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2019-12-24T23-41-36Z

## System information
Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64)
minio server is currently 2019-10-09T23:01:31Z

I was able to update the servers previously using mc admin update TARGET from a version released in August where breaking change was introduced per the below, but have not been able to update again.
https://github.com/minio/minio/pull/8070

**Comment by harshavardhana** [comment]
You can't use latest mc with old servers unfortunately. There has been breaking changes which are written in release notes. 

Closing this issue as working as expected.

**Comment by mentalinc** [comment]
I missed the ramification of the breaking change in the release log
Not sure how to upgrade the old servers, are there any ways other than with mc?

per https://github.com/minio/minio/issues/8479
I've tried setting the environment....

echo $MINIO_UPDATE                         
on
/opt/minio/mc -version
mc version RELEASE.2019-10-09T22-54-57Z
/opt/minio/mc admin update TARGET
mc: <ERROR> Unable to update the server. The specified method is not allowed against this resource.

but using the old commands work, so suggests I can communicate to the servers...
/opt/minio/mc admin info server TARGET
 Uptime: 7 hours 
  Version: 2019-10-12T01:39:57Z

Any direction would be great

**Comment by harshavardhana** [comment]
Unfortunately no there is no way to upgrade old servers with new binary

**Comment by mentalinc** [comment]
I've gone back to the October version
mc -version
mc version RELEASE.2019-10-09T22-54-57Z

but now I get the issue per the above post.

Has running the new version broken something more?
I've also removed and readded the server, still have issues.

**Comment by harshavardhana** [comment]
Yes there was also a bug In that version which disabled upgrade

**Comment by mentalinc** [comment]
opt/minio/mc -v                                
mc version RELEASE.2019-10-02T19-41-02Z

Also has this issue
mc: <ERROR> Unable to update the server. The specified method is not allowed against this resource.
It seems the latest has a breaking change and the one before that doesn;t work...
Can you please let me know a known working version that can update servers?

thanks

**Comment by mentalinc** [comment]
mc -v 
mc version RELEASE.2019-09-24T01-36-20Z                               
also doesn't work
mc: Unable to update the server. The specified method is not allowed against this resource.

It seems I'm now stuck with an old version of minio server?
Any other ideas to maybe reset mc to enable upgrading minio servers on the below version
Version: 2019-10-12T01:39:57

**Comment by harshavardhana** [comment]
Just upgrade the old school approach, download the binary and replace the binaries..

And restart all servers

**Comment by mentalinc** [comment]
Of course so obvious!

wget https://dl.min.io/server/minio/release/linux-amd64/minio
sudo mv ./minio /opt/minio/
sudo chmod +x /opt/minio/minio

All fixed, and all updated

**Comment by harshavardhana** [comment]
:+1:
