### ISSUE TITLE
Cannot set 'notify_mysql ... ... ' , Error 1071: Specified key was too long;

### ISSUE THREAD

**Issue by fromsvn** [minio/mc#3037]
## Expected behavior
Setting new key has been successful.
Please restart your server with `mc admin service restart minio_oa/`.

## Actual behavior
mc: <ERROR> Cannot set 'notify_mysql enable=true format=namespace host=10.1.1.1 port=3306 username=minio_event password=1234 database=miniodb_event_oa dsn_string= table=notification_events queue_dir=/data/minio_event_queue/oa queue_limit=0' to server. Error 1071: Specified key was too long; max key length is 3072 bytes.

## Steps to reproduce the behavior
mysql --version
mysql  Ver 14.14 Distrib 5.7.17, for macos10.12 (x86_64) using  EditLine wrapper

# minio --version
minio version RELEASE.2020-01-03T19-12-21Z

#mc admin config get minio_oa/ notify_mysql
notify_mysql enable=off format=namespace host= port= username= password= database= dsn_string= table= queue_dir= queue_limit=0 

# mc admin config set minio_oa/ notify_mysql enable=true format=namespace host=10.1.1.1 port=3306 username=minio_event password=123456 database=miniodb_event_oa dsn_string= table=notification_events queue_dir="/data/minio_event_queue/oa" queue_limit=0

## mc --version
mc version RELEASE.2020-01-03T20-33-14Z

## System information
# uname -a
Linux vm10-130.cloud 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nitisht** [comment]
Thanks for reporting @fromsvn we'll take a look

**Comment by ebozduman** [comment]
@fromsvn ,

What were the lengths of your table, `notification_events`, fields?
i.e. You must have used the table creation MySQL command, like below, to define field names and their lengths:
`CREATE TABLE notification_events (key_name VARCHAR(N), value VARCHAR(M));`

What were your N and M?

**Comment by kannappanr** [comment]
closing this issue as stale. Please feel free to reach out to us with the requested information
