### ISSUE TITLE
MC mirror doesn't see uppercase bucket name in source (NAS gateway mode)

### ISSUE THREAD

**Issue by grdekhayser** [minio/mc#3038]
## Expected behavior
$> mc mirror minio/WindowsUpdatelogs minio/grd2
Should find objects in WindowsUpdatelogs and mirror them to grd2 bucket. 
Note that mc ls minio/WindowsUpdatelogs works fine and DOES list the objects.

## Actual behavior
Output:
mc: <ERROR> Unable to stat source `minio/WindowsUpdatelogs`. Bucket `WindowsUpdatelogs` does not exist.
 0 B / ?  mc: <ERROR> Unable to copy bucket policies to `http://10.102.24.54:9000/grd2`. The specified bucket does not exist
 0 B / ?  mc: <ERROR> Unable to list comparison retrying.. The specified bucket does not exist

## Steps to reproduce the behavior
1) Create a Nas Gateway instance, attach export that has existing data that has mixed case directory names. 
2) create a second bucket to mirror data to
3) do "mc mirror minio/ExistingBucket minio/newbucket"

## mc --version
mc version RELEASE.2020-01-03T20-33-14Z

## System information
Minio NAS gateway running docker latest, container's host has NFS export mounted on /mnt. Container uses /mnt as /container/vol.

**Comment by vadmeste** [comment]
@grdekhayser a quick workaround is to rename WindowsUpdatelogs to windowsUpdatelogs if possible (replace W with w)

Capital letters in bucket names is not allowed in S3 specification. This is somehow a gray area, maybe we should make the gateway stricter and not show buckets with capital letters.

**Comment by harshavardhana** [comment]
This is because `mc mirror` has couple of bugs related to MakeBucket which we need to address.

**Comment by grdekhayser** [comment]
Please close this.  Realized issue was unrelated to minio. 

Successful mirror:
IICMBP00178:~ glenndekhayser$ mc mirror -a minio/Windowsupdatelogs minio/grd2
...t.log_220_2019928201944.log:  2.76 KiB / 2.76 KiB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  1.93 KiB/s 1s

**Comment by harshavardhana** [comment]
thanks @grdekhayser - will open separate issues with `mc mirror` which I have found.
