### ISSUE TITLE
Auto-completion ignores `--insecure` flag

### ISSUE THREAD

**Issue by donatello** [minio/mc#3056]
## Expected behavior
mc autocompletion works. See below.

## Actual behavior
mc auto-completion does not work when accessing a https minio server with a self-signed https certificate.

## Steps to reproduce the behavior
```
mc --insecure ls m1/testb<TAB><TAB>
```

The above will show bad certificate error on minio server console.

**Comment by harshavardhana** [comment]
@donatello flags are not enabled until they are parsed by the CLI - we don't get this control yet.
