### ISSUE TITLE
Secure mechanism for adding new host

### ISSUE THREAD

**Issue by bbockelm** [minio/mc#3058]
## Expected behavior

I would like to use `mc` locally on a user login host for interaction with an S3 endpoint.

Unfortunately, the way that new configurations are added to user setup is insecure.  From the `--help` output, this is how a new host is added:

```
mc config host add mys3 https://s3.amazonaws.com \
                 BKIKJAA5BMMU2RHO6IBB V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12
```

On a Linux system, the contents of the argument array is considered public - hence the access key ID and secret key ID are available for everyone who is logged in to see!

Instead, is it possible to have a secure mechanism to specify the access key and secret key ID?  Is it possible to use the CLI but provide the secrets via a file or an environment variable?

## mc --version

```
mc version RELEASE.2020-01-03T20-33-14Z
```

**Comment by kannappanr** [comment]
There is already an option 

```
export MC_HOST_<alias>=https://<Access Key>:<Secret Key>@<YOUR-S3-ENDPOINT>
```
Please look at the documentation 
https://docs.minio.io/docs/minio-client-complete-guide.html

Closing this as answered.

Please feel free to reach out to us at https://slack.min.io for such questions in the future.

**Comment by bbockelm** [comment]
@kannappanr - thanks  for following up.  I was aware of the `MC_HOST_<myalias>` environment variable, but it doesn't really help my situation as I really would like to have a way to setup a permanent configuration using the config file.  The configuration file is useful as it works in a much wider set of situations, even when the user clobbers parts of their environment - or sets up their shell session in some funky way.

**Comment by harshavardhana** [comment]
> @kannappanr - thanks for following up. I was aware of the `MC_HOST_<myalias>` environment variable, but it doesn't really help my situation as I really would like to have a way to setup a permanent configuration using the config file. The configuration file is useful as it works in a much wider set of situations, even when the user clobbers parts of their environment - or sets up their shell session in some funky way.

I think its an overkill there is no security issue as such in specifying `mc config host add` it's not as if it's a running service which gets exposed, it runs and finishes right away. You can turn off `history in all shells if you wish to avoid the history.  

If not you can use the ENV @bbockelm - too many ways to do the same thing is confusing and not a design we would want to keep.
