### ISSUE TITLE
feature request: mirror retry behaviour setting

### ISSUE THREAD

**Issue by matti** [minio/mc#3069]
Continuing from #3068

currently `mc mirror` with invalid bucket retries forever and I need something like
```
timeout 1 mc mirror ...
```

**Comment by harshavardhana** [comment]
What are you trying to mirror if the bucket doesn't exist ?

**Comment by matti** [comment]
It is created eventually, but clients try to use it before it is created. And if it's not created the clients should continue doing other things.

**Comment by harshavardhana** [comment]
There is nothing `mc` can do without the bucket @matti so it is waiting.

**Comment by harshavardhana** [comment]
This is an unexpected request, closing this as a non-issue and out of scope.
