### ISSUE TITLE
When copying objects from aws s3 to local minio, an error is raised that is "Please reduce your request rate"

### ISSUE THREAD

**Issue by ocworld** [minio/mc#3074]
## Expected behavior
When copying objects from aws s3 to local minio, they are imported to local without any exception.

The number of them are large.

## Actual behavior
An error is raised that is "Please reduce your request rate"

## Steps to reproduce the behavior
Please see Expected behavior

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2020-01-25T03-02-19Z

## System information
CentOS 7

**Comment by vadmeste** [comment]
@ocworld do you know which is complaining, your local deployment or AWS S3 ?

(Better if you paste the mc output next time here)

**Comment by ocworld** [comment]
mc: <ERROR> Failed to copy `FILEPATH`. Please reduce your request

**Comment by ocworld** [comment]
It is happened in minio on your local deployment

**Comment by vadmeste** [comment]
We need to be sure who is complaining. For that, you need to run mc again with --debug flag and save the debug output in a file, then we can analyze that.
