### ISSUE TITLE
When copying objects, sometimes, an error is raised "HTTP/1.x transport connection broken"

### ISSUE THREAD

**Issue by ocworld** [minio/mc#3075]
## Expected behavior
When copying objects, everything is success without any exception.

## Actual behavior
When copying objects, sometimes, an error is raised like that,

```bash
[root@localhost ~]# mc cp --recursive $local_minio_path $s3_minio_path
mc: <ERROR> Failed to copy `$local_minio_file_path`. Put $aws_s3_file_path?partNumber=1&uploadId=$id--: net/http: HTTP/1.x transport connection broken: http: ContentLength=134217728 with Body length 25165824
mc: <ERROR> Session safely terminated. To resume session `mc session resume zoMhOlVu`
```

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2020-01-25T03-02-19Z

## System information
CentOS 7

**Comment by harshavardhana** [comment]
This means your network is flaky @ocworld

**Comment by ocworld** [comment]
@harshavardhana Yeah, I think that your comment is possible. However, I have wonder about it because when using aws-cli to download objects to my local disk, it is success. After downloading, copying them to minio with mc is also available. It is only occurred, when using only  mc without aws-cli.

**Comment by harshavardhana** [comment]
It looks like a network issue, closing this issue.

**Comment by mostafa8026** [comment]
@ocworld 
Did you find any solution?

**Comment by mostafa8026** [comment]
@harshavardhana 
Does mc client retry the copy operation for failed objects?

**Comment by harshavardhana** [comment]
> @harshavardhana
> Does mc client retry the copy operation for failed objects?

yes @mostafa8026
