### ISSUE TITLE
[Question] `mc cp -r` display folder size is diffience to real folder size

### ISSUE THREAD

**Issue by invent-lwj** [minio/mc#3082]
distributed mode
1. Why `mc cp -r` display the node_modules0 folder is 159.3MB, but node_modules0 is 222MB by `du` command, node_modules0 contain many files and child folders.
```
/ # mc cp -r node_modules0 ecocloud/ecocloud
...es0/yargs/yargs.js:  159.30 MiB / 159.30 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 665.27 KiB/s 4m5s/ # ls
```
```
thinkpad:~ lwj$ du -sh node_modules0
222M	node_modules0
```
2. How to calculate space consumed if i cp a file or folder.
3. Cloud you talk about principle of minio.
Thanks!

**Comment by kannappanr** [comment]
@invent-lwj is there any pattern on files that you see is missing in `cp -r`?

**Comment by harshavardhana** [comment]
note: du -sh would get sparse value, where as mc cp -r would get actual value

**Comment by invent-lwj** [comment]
@kannappanr  no pattern, thanks for your replay.

**Comment by klauspost** [comment]
I think harsha answered the question.
