### ISSUE TITLE
Strange behavior mc mirror

### ISSUE THREAD

**Issue by nurieff** [minio/mc#3088]
I updated mc and now I can't upload files with mirror

`mc --version`
**mc version RELEASE.2020-02-14T19-35-50Z**

Run:
`mc mirror --remove /backups/ s3/backup/dev`

Getting an error
**mc: <ERROR> Unable to create bucket at `s3/backup/dev`. Buckets or prefixes can only be created with `/` suffix.**

OK, I am adding `/` suffix (on the old version it worked without the suffix)
Run:
`mc mirror --remove /backups/ s3/backup/dev/`

Again getting an infinite error
**mc: <ERROR> Unable to list comparison retrying.. A header you provided implies functionality that is not implemented.**

### Everything works fine on the old version
**mc version RELEASE.2019-06-27T21-31-45Z**

**Comment by nitisht** [comment]
can you paste the `--debug` output for `mc mirror --remove /backups/ s3/backup/dev/`

**Comment by nurieff** [comment]
@nitisht yes

mc: <DEBUG> GET /backup/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=dev%2F HTTP/1.1
Host: storage.yandexcloud.net
User-Agent: MinIO (linux; amd64) minio-go/v6.0.48 mc/2020-02-14T19:35:50Z
Authorization: AWS4-HMAC-SHA256 Credential=q69MZittT8v0kf**/20200219/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4**
X-Amz-Date: 20200219T**
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 501 Not Implemented
Content-Length: 269
Connection: keep-alive
Content-Type: application/xml; charset=UTF-8
Date: Wed, 19 Feb 2020 13:04:36 GMT
Keep-Alive: timeout=60
Server: nginx
X-Amz-Request-Id: 37dfd97ab**
X-Yc-S3-Cloud-Id: b1g757so7r**
X-Yc-S3-Folder-Id: b1gqqc8b9n**

<?xml version='1.0' encoding='UTF-8'?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented.</Message><Resource>/backup/</Resource><RequestId>37dfd97ab**</RequestId><FetchOwner>true</FetchOwner></Error>mc: <DEBUG> Response Time:  40.44031ms

mc: <ERROR> Unable to list comparison retrying.. A header you provided implies functionality that is not implemented.
 (1) difference.go:134 cmd.differenceInternal(..) Tags: [/backup/, https://storage.yandexcloud.net/backup/dev/]
 (0) client-s3.go:1978 cmd.(*s3Client).listRecursiveInRoutine(..)
 Release-Tag:RELEASE.2020-02-14T19-35-50Z | Commit:2f2aecb09dd1 | Host:dev.kvmvps | OS:linux | Arch:amd64 | Lang:go1.13.7 | Mem:4.2 MB/72 MB | Heap:4.2 MB/66 MB

**Comment by nurieff** [comment]
"mc cp /backups/example.gz s3/backup/dev/" — work fine

**Comment by harshavardhana** [comment]
This is because your cloud provider doesn't support encoding-type=url, they are returning 501 not implemented. You need to ask them to implement it.

**Comment by nurieff** [comment]
@harshavardhana, maybe there is a parameter in command `mirror` that makes the request the old version? Without encoding-type=url
`GET /backup/?delimiter=&max-keys=1000&prefix=dev%2F HTTP/1.1`

I wrote to the provider, but it will be slow.
I will use the old version

Thanks

**Comment by harshavardhana** [comment]
Unfortunately no, encoding-type URL support is present to handle characters which cannot be handled by XML parsing. It ensures more stable implementation to support all kinds of files.

If you use AWS CLI this is the default encoding--type as well.
