### ISSUE TITLE
limit the transfer speed

### ISSUE THREAD

**Issue by Bhanukiran117** [minio/mc#3096]
## Expected behavior
want to know if there option for cp command to limit the transfer rate
## Actual behavior
looks like no such option now
## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2019-10-09T22-54-57Z

## System information

Because existing data transfer rate with cp command, I am encountering high I/O, load avg and affecting the database on the server while copying the files to cloud. So looking for option to limit the data transfer rate.

**Comment by harshavardhana** [comment]
Use wondershaper tool, out of scope for `mc`
