### ISSUE TITLE
mc autocomplete does not work with self signed cert

### ISSUE THREAD

**Issue by eco-minio** [minio/mc#3102]
## Expected behavior
Low priority issue, autocompletion should work when even with self signed cert
## Actual behavior
Autocompletion works on the alias itself, not any prefixes or objects
## Steps to reproduce the behavior
Set up a cluster with self-signed cert, add public cert to ~/.mc/certs/CAs
## mc --version
- (paste output of `mc --version`)
RELEASE.2020-02-25T18-10-03Z
## System information
Ubuntu 18.04

**Comment by klauspost** [comment]
@vadmeste I know you've been tinkering with autocomplete.
