### ISSUE TITLE
Bucket space usage

### ISSUE THREAD

**Issue by s3rj1k** [minio/mc#3109]
I am not confident that https://github.com/minio/minio/issues/6577 answers original question fully, `mc admin info play` does not show per bucket usage, only combined bucket usage of whole cluster.

Other solutions that were provided by `minio` team feel hacky, listening to bucket notifications.

Also bucket notifications as per documentation do not work for usage case when `minio` is used as gateway for `s3`, with or without cache.

**Comment by kannappanr** [comment]
@s3rj1k We will be adding this command to mc soon. Until then you can use the following command

```
 $ mc du play/test
52B	test
```
This will list real time and display the value, but might take a very long time if you have millions of objects.

**Comment by seqizz** [comment]
Sorry for another +1'ish comment, but `du` is taking incredibly long on big buckets.
If I understand correctly there is already some accounting done per-bucket, waiting for the feature :tada:

**Comment by s3rj1k** [comment]
Any news?

**Comment by s3rj1k** [comment]
Still relevant

**Comment by sstubbs** [comment]
This would be really useful.

**Comment by mrdsam** [comment]
> Sorry for another +1'ish comment, but `du` is taking incredibly long on big buckets.
> If I understand correctly there is already some accounting done per-bucket, waiting for the feature

You can get the usage per bucket from the prometheus metrics https://docs.minio.io/docs/how-to-monitor-minio-using-prometheus.html

The data is not always up to date, in my setup it lags up to 24h. Nevertheless, it is a very fast way to retrieve the 'du' data.

**Comment by s3rj1k** [comment]
Still relevant

**Comment by s3rj1k** [comment]
Why this is closed?

**Comment by melsom** [comment]
Can we reopen this? Still relevant and much needed.

**Comment by geraldo-netto** [comment]
Dear Friends,

I`m also interested in this feature, in my case, I would need to use it through java
How can I contribute to implement this feature?

Kind Regards,
Geraldo Netto

**Comment by klauspost** [comment]
We do not provide admin API through other means than [madmin-go](https://github.com/minio/madmin-go) and [mc](https://github.com/minio/mc).

The API is fully public in madmin, but backwards compatibility is not guaranteed for future releases. Feel free to implement it in your own language.

**Comment by mirekphd** [comment]
One workaround until this problem is fixed - if your maintain a local copy of the remote bucket (e.g. using backup software such as `restic` in parallel for remote and local copies), you can monitor disk usage with e.g. `du -sch` and `df -haT` on these local copies (which is reasonably performant even when `local` really means network storage such as NFS or Ceph).

**Comment by simplecoka** [comment]
I think we can solve the issue with this script

package main

import (
    "log"


    "context"

    "github.com/minio/madmin-go/v2"
)

func main() {
	// API requests are secure (HTTPS) if secure=true and insecure (HTTPS) otherwise.
	// NewAnonymousClient returns an anonymous MinIO Admin client object.
	// Anonymous client doesn't require any credentials
	madmClnt, err := madmin.New($URL,$ACK ,$ASK, false)
	if err != nil {
		log.Fatalln(err)
	}
	// Get Bucket Size
	dataUsageInfo, err := madmClnt.DataUsageInfo(context.Background())
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(dataUsageInfo.BucketsUsage["$bucket"].Size)

	// Get Quote Size
	ctx := context.Background()
	quotaCfg, err := madmClnt.GetBucketQuota(ctx, "$bucket")
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(quotaCfg)
}

**Comment by s3rj1k** [comment]
3 years have passed, no official solution to very basic OPS request is provided...

**Comment by dminca** [comment]
How about `minio_bucket_usage_total_bytes` ? This should give you a historical view on bucket size perhaps

**Comment by seqizz** [comment]
Yes, although getting updated a bit slower/incrementally, seems like `minio_bucket_usage_total_bytes` from `mc admin prometheus metrics` seems to be the easiest way of doing it currently. I got rid of the IO-heavy `du` solution at last.
