### ISSUE TITLE
mc: <ERROR> dial tcp [::1]:9000: connect: connection refused.

### ISSUE THREAD

**Issue by sbryans** [minio/mc#3123]
## Expected behavior
Added **HOST** successfully.

## Actual behavior
mc: <ERROR> Unable to initialize new config from the provided credentials. Get http://localhost:9000/probe-bucket-sign-o2kvz9es6crq/?location=: dial tcp [::1]:9000: connect: connection refused.

## Steps to reproduce the behavior
./mc config host add **HOST** http://localhost:9000 **AccessKey** **SecretKey**

## mc --version
RELEASE.2020-03-14T01-23-37Z

## System information
Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
is there a server running locally? @sbryans

**Comment by kannappanr** [comment]
@sbryans I am assuming that is the case and closing this issue. Please feel free to reach out to us if not, with more information.

**Comment by sbryans** [comment]
There must have been an instance of something running on :9000. I couldn't figure it out. I installed MinIO on another instance, this time on Debian 10. No issues.

**Comment by chandrakalagowda** [comment]
Do we have to install minIO on the local computer for. backup?
My docker shows the following volumes running
Will. the backup use the minio from the docker or should minio be installed seperately.
Please give me some pointers.
<img width="959" alt="image" src="https://github.com/minio/mc/assets/24473622/1bfe184e-f146-4d99-956c-5899bb15c4d7">
