### ISSUE TITLE
'mc diff' not working for hosts

### ISSUE THREAD

**Issue by szemlyanoy** [minio/mc#3124]
## Expected behavior
`mc diff host1/ host2/`

list of diffs between buckets and bucket objects

## Actual behavior
```
mc diff host1/ host2/
mc: <ERROR> Unable to stat 'minio_qa4/'. Bucket name cannot be empty.

```
## Steps to reproduce the behavior
create 2 hosts then
`mc diff host1/ host2/`

## mc --version
- (paste output of `mc --version`)
`mc version RELEASE.2020-03-14T01-23-37Z
`

## System information
Red Hat Enterprise Linux Server release 6.9 (Santiago)

Thanks,
Sergii

**Comment by harshavardhana** [comment]
@szemlyanoy `mc diff` needs bucket names as indicated by the error message.

**Comment by szemlyanoy** [comment]
so basically there is no way to diff hosts? only script looping through buckets?

**Comment by harshavardhana** [comment]
Yes @szemlyanoy

**Comment by kannappanr** [comment]
```
$ mc diff
NAME:
  mc diff - list differences in object name, size, and date between two buckets

USAGE:
  mc diff [FLAGS] FIRST SECOND
```
Closing this issue, please feel free to reach out to us at https://slack.min.io for further questions
