### ISSUE TITLE
mc fails with digital ocean ams3 region

### ISSUE THREAD

**Issue by mvrhov** [minio/mc#3140]
## Expected behavior
mc doesn't report an error

## Actual behavior
mc: <ERROR> Unable to stat `done`. Bucket name cannot be shorter than 3 characters.

## Steps to reproduce the behavior
Configure a bucket in digitalocean spaces ams3 region
```json
                "done": {
                        "url": "https://ams3.digitaloceanspaces.com",
                        "accessKey": "",
                        "secretKey": "",
                        "api": "S3v4",
                        "lookup": "dns"
                },
```

run `mc ls done`

## mc --version
- latest + master

## PROBLEM
I don't know why you are splitting host but the bug is in this line 
https://github.com/minio/mc/blob/master/cmd/client-s3.go#L1404
and another one a few lines lower
https://github.com/minio/mc/blob/master/cmd/client-s3.go#L1426

**Comment by harshavardhana** [comment]
> Configure a bucket in digitalocena spaces ams3 region

This is because perhaps ams3 has s3 in it

> I don't know why you are splitting host but the bug is in this line https://github.com/minio/mc/blob/master/cmd/client-s3.go#L1404

There are lot of historical reasons @mvrhov - it is worth a fix.
