### ISSUE TITLE
mc mirror -w exits after 9 hours

### ISSUE THREAD

**Issue by korzq** [minio/mc#3143]
## Expected behavior
`mc mirror -w`  to work over a long period of time

## Actual behavior
Exits with status code 1 after 9 hours and error "Failed to perform mirroring. bufio.Scanner: token too long"
```
λ mc mirror -w s1/test s2/test
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <ERROR> Failed to perform mirroring. bufio.Scanner: token too long
```

## Steps to reproduce the behavior
1. get two minio servers, i named them s1 and s2
2. run  `mc mirror -w s1/test s2/test`

## mc --version
- mc version RELEASE.2020-03-14T01-23-37Z

## System information
```
λ uname -mprsv
Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64
```

Nginx Config (I followed https://docs.min.io/docs/setup-nginx-proxy-with-minio)

```
server {
        server_name [REDACTED];
        listen [::]:443 ssl;

 ignore_invalid_headers off;
 client_max_body_size 0;
 proxy_buffering off;

large_client_header_buffers 8 32k;
 location / {

   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_set_header Host $http_host;

   proxy_connect_timeout 300;
   proxy_http_version 1.1;
   proxy_set_header Connection "";
   chunked_transfer_encoding off;

   proxy_pass http://172.20.1.20:9000;
 }
}
```

Minio server startup command
`docker run -d --restart unless-stopped --name minio --network=general --ip=172.20.1.20 -v /home/eric/dockerdata/minio:/data --user $(id -u):$(id -g) -e MINIO_ACCESS_KEY="[REDACTED, contains a-zA-Z0-9]" -e MINIO_SECRET_KEY="[REDACTED contains a-zA-Z0-9]" minio/minio server /data`

**Comment by kannappanr** [comment]
@korzq Thanks for reporting this issue. We will take a look and get back to you.

**Comment by eco-minio** [comment]
@korzq Are any objects being created in the source while this is running?

**Comment by harshavardhana** [comment]
this is related to an incorrect nginx config

> large_client_header_buffers 8 32k;

Remove this - you shall never cache/buffer anything at nginx. 

Related issue https://github.com/minio/minio-go/issues/1236#issuecomment-596424554

**Comment by korzq** [comment]
MC now exits with `mc: <ERROR> Failed to perform mirroring. bufio.Scanner: token too long` after 9 hours. Here is the nginx config

```
server {
        server_name [redacted];
        listen [::]:443 ssl;

# To allow special characters in headers
 ignore_invalid_headers off;
 # Allow any size file to be uploaded.
 # Set to a value such as 1000m; to restrict file size to a specific value
 client_max_body_size 0;
 # To disable buffering
 proxy_buffering off;

 location / {

   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_set_header Host $http_host;

   proxy_connect_timeout 300;
   # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
   proxy_http_version 1.1;
   proxy_set_header Connection "";
   chunked_transfer_encoding off;

   proxy_pass http://172.20.1.20:9000; # If you are using docker-compose this would be the hostname i.e. minio
   # Health Check endpoint might go here. See https://www.nginx.com/resources/wiki/modules/healthcheck/
   # /minio/health/live;
 }
}
```

Shall I open a new issue?

**Comment by harshavardhana** [comment]
> MC now exits with `mc: <ERROR> Failed to perform mirroring. bufio.Scanner: token too long` after 9 hours. Here is the nginx config
> 
> ```
> server {
>         server_name [redacted];
>         listen [::]:443 ssl;
> 
> # To allow special characters in headers
>  ignore_invalid_headers off;
>  # Allow any size file to be uploaded.
>  # Set to a value such as 1000m; to restrict file size to a specific value
>  client_max_body_size 0;
>  # To disable buffering
>  proxy_buffering off;
> 
>  location / {
> 
>    proxy_set_header X-Real-IP $remote_addr;
>    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>    proxy_set_header X-Forwarded-Proto $scheme;
>    proxy_set_header Host $http_host;
> 
>    proxy_connect_timeout 300;
>    # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
>    proxy_http_version 1.1;
>    proxy_set_header Connection "";
>    chunked_transfer_encoding off;
> 
>    proxy_pass http://172.20.1.20:9000; # If you are using docker-compose this would be the hostname i.e. minio
>    # Health Check endpoint might go here. See https://www.nginx.com/resources/wiki/modules/healthcheck/
>    # /minio/health/live;
>  }
> }
> ```
> 
> Shall I open a new issue?

Are you sure you only have single proxy here? This looks like someone is messing with the response headers or either you applied the nginx config.. it is still using some other config locally..

Note: this is not our issue, the incoming response from server is being mangled in some form.

**Comment by harshavardhana** [comment]
> > MC now exits with `mc: <ERROR> Failed to perform mirroring. bufio.Scanner: token too long` after 9 hours. Here is the nginx config
> > ```
> > server {
> >         server_name [redacted];
> >         listen [::]:443 ssl;
> > 
> > # To allow special characters in headers
> >  ignore_invalid_headers off;
> >  # Allow any size file to be uploaded.
> >  # Set to a value such as 1000m; to restrict file size to a specific value
> >  client_max_body_size 0;
> >  # To disable buffering
> >  proxy_buffering off;
> > 
> >  location / {
> > 
> >    proxy_set_header X-Real-IP $remote_addr;
> >    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >    proxy_set_header X-Forwarded-Proto $scheme;
> >    proxy_set_header Host $http_host;
> > 
> >    proxy_connect_timeout 300;
> >    # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
> >    proxy_http_version 1.1;
> >    proxy_set_header Connection "";
> >    chunked_transfer_encoding off;
> > 
> >    proxy_pass http://172.20.1.20:9000; # If you are using docker-compose this would be the hostname i.e. minio
> >    # Health Check endpoint might go here. See https://www.nginx.com/resources/wiki/modules/healthcheck/
> >    # /minio/health/live;
> >  }
> > }
> > ```
> > 
> > 
> > Shall I open a new issue?
> 
> Are you sure you only have single proxy here? This looks like someone is messing with the response headers or either you applied the nginx config.. it is still using some other config locally..
> 
> Note: this is not our issue, the incoming response from server is being mangled in some form.

But of course we can do patch the client side, to allow nginx bugs to be fixed later. We need to fix minio-go here.

**Comment by korzq** [comment]
Error exist with the minio play instance too.

```
λ mc mirror -w play/eric1 play/eric2
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <ERROR> Failed to perform mirroring. unexpected end of JSON input
```
