### ISSUE TITLE
Minio mc docker compose file not create bucket

### ISSUE THREAD

**Issue by tapos007** [minio/mc#3144]
I add my docker-compose.yml file why bucket not creating using this command . plz help me 

minio:
        image: "minio/minio"
        container_name: myminio
        ports:
            - "9000:9000"
        environment:
            - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
            - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        restart: always
        command: server /data
    mc:
        image: minio/mc
        container_name: mc
        depends_on:
            - minio
        entrypoint: >
          /bin/sh -c "
          /mc host rm local
          /mc config host add local http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
          /mc mb local/somebucketname1;
          /mc policy set public local/somebucketname1;
          "

**Comment by kannappanr** [comment]
please use something like this
```

version: '2'

services:
 minio:
  image: minio/minio:latest
  container_name: myminio
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server /data
 mc:
  image: minio/mc:latest
  depends_on:
   - minio
  entrypoint: >
    /bin/sh -c "
    /usr/bin/mc config host rm local;
    /usr/bin/mc config host add --quiet --api s3v4 local http://myminio:9000 minio minio123;
    /usr/bin/mc rb --force local/somebucketname1/;
    /usr/bin/mc mb --quiet local/somebucketname1/;
    /usr/bin/mc policy set public local/somebucketname1;
    "
```

Please reach us out at https://slack.min.io for further such questions

**Comment by bigmachini** [comment]
Am having some issues, am running docker-compose v3 the above syntax doesn't work, went ahead and modified it by passing in a script

./entrypoint.sh
`#!/bin/bash
/bin/sh -c "
    /usr/bin/mc config host rm local;
    /usr/bin/mc config host add --quiet --api s3v4 local http://localhost:9000 minio minio123;
    /usr/bin/mc rb --force local/somebucketname1/;
    /usr/bin/mc mb --quiet local/somebucketname1/;
    /usr/bin/mc policy set public local/somebucketname1;
    "`
minio mc on docker compose part
`  mc:
    image: minio/mc:latest
    depends_on:
      - nginx
    volumes:
      - ./entrypoint.sh:/etc/bin/entrypoint.sh
    entrypoint: ./etc/bin/entrypoint.sh`

Attached is a screenshot of what the logs are saying
![Screenshot from 2021-09-30 07-58-50](https://user-images.githubusercontent.com/5182869/135390062-57b8da4a-3135-4342-a30e-1f0f8747719c.png)
![Screenshot from 2021-09-30 07-58-43](https://user-images.githubusercontent.com/5182869/135390066-0c2921fc-83be-4e7f-b854-1daeac4a9ea7.png)

**Comment by janpekar** [comment]
@bigmachini 
You have http://localhost:9000 in you URL, you should have http://servicename:9000 so in this case http://myminio:9000 how it is specified in example above.
