### ISSUE TITLE
Can't mirror or copy files with national characters from GCS anymore

### ISSUE THREAD

**Issue by leshik** [minio/mc#3147]
## Expected behavior

Operations with national characters work fine.

## Actual behavior

For example, with the current version, file listing with Thai symbols looks like this:

```
th-phrase-how-often-do-you-skate-4-%E0%B9%80%E0%B8%A5%E0%B9%88%E0%B8%99%E0%B8%AA%E0%B9%80%E0%B8%81%E0%B8%95.67b639cdb4eda78c2578ca16a835afd8.mp3
```

It's not possible to copy this file to the local filesystem from GCS:

```
mc: <ERROR> Unable to validate source th-phrase-how-often-do-you-skate-0-%E0%B9%81%E0%B8%84%E0%B9%88%E0%B9%84%E0%B8%AB%E0%B8%99.c21c4f9e6fafef241df70ecf07ba8b70.mp3
```

While with `RELEASE.2019-10-09T22-54-57Z` everything looks (and works) as expected:

```
th-phrase-how-often-do-you-skate-0-แค่ไหน.c21c4f9e6fafef241df70ecf07ba8b70.mp3
```

## Steps to reproduce the behavior

Copy/mirror files with national characters from GCS to the local filesystem.

## mc --version

```
mc version RELEASE.2020-03-14T01-23-37Z
```

## System information

MacOS, Linux – doesn't matter.

**Comment by ebozduman** [comment]
Hi @leshik,

I've tried to reproduce the issue with a build generated with the latest mc master code and I did not see it. I created a file with the problematic name you've provided and copied it back and forth between my local filesystem and GCS (MinIO as a gateway). However, everytime it worked without any issue. I've also tried RELEASE.2020-03-14T01-23-37Z and still did not see the issue.

Could you please try again with the latest mc release and if you could reproduce it, add more detail about how you reproduced, like how you started MinIO, best would be to copy and paste the exact command, and ... 
- the command to create a file with a name with local/special characters (touch, rename, etc.). I assume you create it in your local file system first.
 - the command to copy it over to a GCS bucket, like `mc cp`, `mc mirror`
 - just confirm you get the same error message

**Comment by leshik** [comment]
@ebozduman the key here is that I don't use minio gateway for gcs as I don't need to delete any files from GCS. Why introduce additional moving parts that I don't need? It worked fine up to RELEASE.2019-10-09T22-54-57Z, now it doesn't. The commands are:
```bash
mc config host add gcs https://storage.googleapis.com secret key --api "S3v2"
mc --quiet mirror gcs/object/key local/file
```
It breaks with Thai symbols in the file name in my case, you can try an example from my original message.

**Comment by harshavardhana** [comment]
@leshik the problem here is that GCS doesn't implement correct URL encoding for those characters.  We moved to use encoding-type=url which is why perhaps it stopped working with GCS.

**Comment by leshik** [comment]
@harshavardhana but there were never any issues with encodings in GCS <-> mc before. Is it possible to implement the previous encoding-type for GCS? Some options in CLI maybe?

**Comment by harshavardhana** [comment]
> @harshavardhana but there were never any issues with encodings in GCS <-> mc before. Is it possible to implement the previous encoding-type for GCS? Some options in CLI maybe?

The point I am trying to make is that we moved to a better mechanism to support some unexpected characters for XML marshaling protection, this is facilitated by URL encoding. It looks like GCS is broken here @leshik so give us some time to figure this out and fix it for. 

If it's urgent then you should send a PR and fix it yourself.

**Comment by leshik** [comment]
No, that's not urgent. Thanks!

**Comment by leshik** [comment]
@harshavardhana what's funny is that just today I've stumbled upon [the same bug](https://github.com/minio/mc/issues/3067) on a different project, but now on DigitalOcean. That issue was closed without a fix.

**Comment by harshavardhana** [comment]
> @harshavardhana what's funny is that just today I've stumbled upon [the same bug](https://github.com/minio/mc/issues/3067) on a different project, but now on DigitalOcean. That issue was closed without a fix.

Yes because the issue was because DigitalOcean server is buggy, not implementinh the right requirements for S3 API.

If its the same issue then it would be unfortunate..
