### ISSUE TITLE
mc cat is doing listing before retrieving a file

### ISSUE THREAD

**Issue by Baresse** [minio/mc#3148]
## Expected behavior

Whatever the number of files in a directory when the command `mc cat  .../file` is used no listing should be done by `mc`. 

## Actual behavior
I’ve a minio cluster serving files stored on an XFS backed filesystem. When I try to retrieve a small CSV file (2 lines) in a directory which contains around 200k files, it takes around 10 seconds to come.

Here is the command I use : 
`mc cat minio/draft/xxxx/yyyy/FR2313202810` 

If I do the same command in a directory with less files inside, the file is returned without delay. 

If I create a shared Download URL using this command : 
 `mc share download -expire 4h minio/draft/xxxx/yyyy/FR2313202810` 

I get an URL and if use the following command : 
  `wget <provided_download_url> -O FR2313202810` 
the file is returned without delay.

Note: We have the same behavior with filename with extension for instance `FR2313202810.csv`

## mc --version
- `mc version RELEASE.2020-04-04T05-28-55Z`

**Comment by klauspost** [comment]
`mc cat local2/somebucket/aprefix/data.csv` results in 

```
s3.ListObjectsV2 localhost:9001/somebucket/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=aprefix%2Fdata.csv
s3.GetObject localhost:9001/somebucket/aprefix/data.csv
```
