### ISSUE TITLE
mc cp extra calls

### ISSUE THREAD

**Issue by klauspost** [minio/mc#3149]
## Expected behavior

`mc cp local2/somebucket/Chrom/data.csv .` should be efficient at retrieving files.

## Actual behavior

```
λ mc admin trace local2
13:28:37.191 [200 OK] s3.HeadObject localhost:9001/somebucket/Chrom/data.csv                   5.001ms      ↑ 77 B ↓ 380 B
13:28:37.210 [200 OK] s3.ListObjectsV2 localhost:9001/somebucket/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=Chrom%2Fdata.csv                    19.005ms     ↑ 77 B ↓ 874 B
13:28:37.215 [200 OK] s3.HeadObject localhost:9001/somebucket/Chrom/data.csv                   4.001ms      ↑ 77 B ↓ 380 B
13:28:37.219 [200 OK] s3.HeadObject localhost:9001/somebucket/Chrom/data.csv                   3.001ms      ↑ 77 B ↓ 380 B
13:28:37.223 [200 OK] s3.GetObject localhost:9001/somebucket/Chrom/data.csv                   4.001ms      ↑ 86 B ↓ 401 B
```

There are 3 `HeadObject` calls, 1 directory listing and finally a GetObject call.

## Reproducing:

Copy a file to MinIO, use `λ mc admin trace myminio` to monitor calls. Copy the file back.

## mc --version

- latest master

**Comment by vadmeste** [comment]
I noticed that `mc cp -r alias/bucket/prefix/ /tmp/` will issue a HEAD for every object inside alias/bucket/prefix/. It looks like it is unnecessary and a good room of improvement.

(I am mostly searching optimization of big operations)

**Comment by vadmeste** [comment]
It is in minio-go and not in mc.

mc calls minio.Object.Stat() function to get metadata during copy. That's how the HEAD call is issued before each file copy operation.

But probably we can enhance minio-go so it sends only one GET request, since metadata will be returned in header. The GET request content can be on hold until the caller starts to read data

**Comment by harshavardhana** [comment]
> It is in minio-go and not in mc.
> 
> mc calls minio.Object.Stat() function to get metadata during copy. That's how the HEAD call is issued before each file copy operation.
> 
> But probably we can enhance minio-go so it sends only one GET request, since metadata will be returned in header. The GET request content can be on hold until the caller starts to read data

You should see why minio-go does extra calls, it is to ensure Seeker compatibility @vadmeste you cannot just avoid it if you want to avoid seeker behavior, it is present to resume partially copied operations on local FS. 

It is rather historical ..

**Comment by vadmeste** [comment]
> You should see why minio-go does extra calls,

@harshavardhana, 

mc explicity calls object.Stat(), the reason is that it wants to copy the retention configuration of each object.

**Comment by harshavardhana** [comment]
> > You should see why minio-go does extra calls,
> 
> @harshavardhana,
> 
> mc explicity calls object.Stat(), the reason is that it wants to copy the retention configuration of each object.

@vadmeste that part is already fixed the double Stat() exists because of `cp` trying to figure out the mode of operation.

**Comment by vadmeste** [comment]
> @vadmeste that part is already fixed

Not really, I am testing with master.

```
 mc --debug cp -r s3/vadmeste/colorjson/ /tmp/
```

You will notice that there is a HEAD request for each object inside colorjson directory.

**Comment by harshavardhana** [comment]
> You will notice that there is a HEAD request for each object inside colorjson directory.

yes that is needed because of minio-go Seeker behavior @vadmeste

**Comment by ebozduman** [comment]
@vadmeste ,

The last comment shows you wrote:
> notice that there is a HEAD request for each object inside colorjson directory.

@harshavardhana said:
> yes that is needed because of minio-go Seeker behavior @vadmeste

Do you have any extra information related to the issue/fix after your and Harsha's comments?

**Comment by vadmeste** [comment]
> Do you have any extra information related to the issue/fix after your and Harsha's comments?

We need to reevaluate the current status of this again, since many things have been changed. Currently it seems that `mc cp s3/bucket/object localdir/` issues one GET call but several HEAD calls (still better than List calls), I just don't know yet why we have multiple HEAD calls.

**Comment by ebozduman** [comment]
@vadmeste ,

Isn't Harsha's last answer for that ?

> yes that is needed because of minio-go Seeker behavior

**Comment by vadmeste** [comment]
> Isn't Harsha's last answer for that ?
> 
> > yes that is needed because of minio-go Seeker behavior

yeah, maybe also there are other calls in mc itself

**Comment by ebozduman** [comment]
We'll keep it open as there is no consensus on if there is something we can do about this issue.

**Comment by vadmeste** [comment]
yes agree, I just tested, copying a simple file from a S3 server sends six HEAD requests for the same file.

**Comment by klauspost** [comment]
@vadmeste Thanks for testing! Yeah, that should be possible to reduce.

**Comment by harshavardhana** [comment]
The way to fix would be to pass around the information captured

- `--recursive` can inherit the information from ListObjects() 

- Cache Head calls locally for repeated successive operations,  it locally 
   in the `cmd/client-s3.go` - we do not expect objects to change every 
   millisecond during downloads

OR 

- We have to pass around a successful Head() call to minio-go as well.
