### ISSUE TITLE
mc: <ERROR> Failed to get the status of the background heal. Unexpected client 'admin' API version found 'v2', expected 'v3'

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3152]
## Expected behavior
Heal process should start

## Actual behavior
Receeve error
mc: <ERROR> Failed to get the status of the background heal. Unexpected client 'admin' API version found 'v2', expected 'v3', please downgrade the client to older releases.

## Steps to reproduce the behavior
Got latest versions of server and client
wget https://dl.minio.io/server/minio/release/linux-amd64/minio
wget https://dl.minio.io/client/mc/release/linux-amd64/mc

Started server with
./minio --compat server stor0
Started client
./mc admin heal server

Could this be due to server not being in a distributed mode ?

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2020-04-04T05-28-55Z

**Comment by harshavardhana** [comment]
> ./minio --compat server stor0

Healing is only supported with erasure coding @i0x71 not FS mode.
