### ISSUE TITLE
Configuration for Requester Pays Buckets setting a Project.

### ISSUE THREAD

**Issue by jsindy** [minio/mc#3158]
Currently we are using mc client in production and need the ability to define a project for buckets set to Requester Pays.

Specifically in GCP mc will fail on a bucket set to Requester Pays because it doesn't know what project to bill it to. The work around is to setup a non-service account and set a project as default for that account. Unfortunately this doesn't scale very well as we would need many GCP accounts. We would like to use service accounts and be able to specify a project via the client.

If there is already a way to do this please let me know. Any help would be much appreciated. Thank you.

**Comment by vadmeste** [comment]
@jsindy sorry but this is clearly out of scope of mc. I don't think the team will approve it.

**Comment by jsindy** [comment]
Understood, thank you for the fast response.
