### ISSUE TITLE
[future] escape ';' in mc cp --attr

### ISSUE THREAD

**Issue by bjg2** [minio/mc#3165]
I cannot set content-disposition correctly while uploading a file to S3.

Tried with following command:
```
mc cp SOURCE DEST --attr Content-Disposition=attachment;filename*=UTF-8''%D8%AF%D9%88%D8%A8%D8%A7%D8%B1%D8%A9%2C%20%D9%88%D9%8E%D8%AA%D9%8E%D8%B1.txt
```

## Expected behavior
Value of Content-Disposition meta is `attachment;filename*=UTF-8''%D8%AF%D9%88%D8%A8%D8%A7%D8%B1%D8%A9%2C%20%D9%88%D9%8E%D8%AA%D9%8E%D8%B1.txt`

## Actual behavior
Value of Content-Disposition meta is `attachment`, and value of x-amz-meta-filename* meta is `UTF-8''%D8%AF%D9%88%D8%A8%D8%A7%D8%B1%D8%A9%2C%20%D9%88%D9%8E%D8%AA%D9%8E%D8%B1.txt`

## Steps to reproduce the behavior

Run the command in the description against AWS S3.

## mc --version
mc version RELEASE.2020-04-04T05-28-55Z

## System information
Windows Server 2019 Standard (MSYS_NT-10.0-17763 WIN-2K6P17UCF1D 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys)

**Comment by vadmeste** [comment]
@bjg2 you need to quote the attr option:

```
mc cp SOURCE DEST --attr "Content-Disposition=attachment;filename*=UTF-8''%D8%AF%D9%88%D8%A8%D8%A7%D8%B1%D8%A9%2C%20%D9%88%D9%8E%D8%AA%D9%8E%D8%B1.txt"
```

**Comment by bjg2** [comment]
Tried that already, doesn't help. Problem is that key-value pairs in --attr are split by ; (official documentation states `add custom metadata for the object (format: KeyName1=string;KeyName2=string)`), while I need a value that has ; inside...

**Comment by vadmeste** [comment]
Does it help if you replace ';' with %3B ?

**Comment by bjg2** [comment]
Well, it does not, as now the content-disposition value stored in AWS is `attachment%3Bfilename*=UTF-8''%D8%AF%D9%88%D8%A8%D8%A7%D8%B1%D8%A9%2C%20%D9%88%D9%8E%D8%AA%D9%8E%D8%B1.txt` (instead of `attachment;filename*=UTF-8''%D8%AF%D9%88%D8%A8%D8%A7%D8%B1%D8%A9%2C%20%D9%88%D9%8E%D8%AA%D9%8E%D8%B1.txt`)...

**Comment by harshavardhana** [comment]
For now it's not possible, for any other complex variations use the SDK directly and set them using code.

**Comment by bjg2** [comment]
In my usecase, I have to have a process in the server that manages more than just download / upload, it has to be node, it has to be able to have multiple fast uploads / downloads in parallel, and it has to be highly responsive while doing that. Especially since node has 1 thread, solution is new processes.

Don't want to push you into giving this task higher priority, just wanted to decribe that there is a usecase where separate process is needed. it is much easier to have that separate process as a CLI than to create another process that imports the SDK and just uploads the file (the same thing that CLI does).

**Comment by harshavardhana** [comment]
> In my usecase, I have to have a process in the server that manages more than just download / upload, it has to be node, it has to be able to have multiple fast uploads / downloads in parallel, and it has to be highly responsive while doing that. Especially since node has 1 thread, solution is new processes.
> 
> Don't want to push you into giving this task higher priority, just wanted to decribe that there is a usecase where separate process is needed. it is much easier to have that separate process as a CLI than to create another process that imports the SDK and just uploads the file (the same thing that CLI does).

Every use-case is valid for everyone @bjg2 some possible with limited constraints, some not, in this case, it's not easy to handle this as a CLI without complicating the CLI. 

The point is in such scenarios use SDKs, write code which does this for you and it will always work. complicating our CLI to handle a myriad of scenarios would simply make CLI a swiss army knife.

**Comment by bjg2** [comment]
I totally agree in general (CLI and swiss army knife analogy), but in this case it's not about adding a new feature... When a string is separated by a given character there should be a way to escape that character...

**Comment by harshavardhana** [comment]
This functionality is already implemented and released.
