### ISSUE TITLE
mc stuck on remove bucket

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3176]
When trying to use mc rb to remove a bucket but host name is omitted command hangs.

~$ mkdir crap && touch crap/test
~$ mc rb --force crap
Removed `crap` successfully.
^C^C

mc rb is supposed to remove a bucket, however is the host name is passed, it does something else, it remove a local folder rather than a bucket and hangs after that.
To me that is misleading behavior, i would expect it to fail stating that either no host or no bucket name specified rather than deleting files/folders from local fs.

## Strace output
epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=947871192, u64=140678306684376}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 5, 0xc00010ea74) = -1 EPERM (Operation not permitted)
getdents64(5, /* 3 entries */, 8192)    = 72
getdents64(5, /* 0 entries */, 8192)    = 0
newfstatat(AT_FDCWD, "crap/test", {st_mode=S_IFREG|0644, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
close(5)                                = 0
futex(0xc000070bc8, FUTEX_WAKE_PRIVATE, 1) = 1
uname({sysname="Linux", nodename="debian", ...}) = 0
epoll_pwait(4, [], 128, 0, NULL, 21707160) = 0
futex(0xc000070bc8, FUTEX_WAKE_PRIVATE, 1) = 1
uname({sysname="Linux", nodename="debian", ...}) = 0
epoll_pwait(4, [], 128, 0, NULL, 21707160) = 0
futex(0xc000070bc8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc000070bc8, FUTEX_WAKE_PRIVATE, 1) = 1
openat(AT_FDCWD, "crap", O_RDONLY|O_CLOEXEC) = 5
epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=947871192, u64=140678306684376}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 5, 0xc00010eb04) = -1 EPERM (Operation not permitted)
getdents64(5, /* 3 entries */, 8192)    = 72
getdents64(5, /* 0 entries */, 8192)    = 0
newfstatat(AT_FDCWD, "crap/test", {st_mode=S_IFREG|0644, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
close(5)                                = 0
futex(0xc000070bc8, FUTEX_WAKE_PRIVATE, 1) = 1
unlinkat(AT_FDCWD, "crap/test", 0)      = 0
unlinkat(AT_FDCWD, "crap", 0)           = -1 EISDIR (Is a directory)
unlinkat(AT_FDCWD, "crap", AT_REMOVEDIR) = 0
futex(0xc000070bc8, FUTEX_WAKE_PRIVATE, 1) = 1
Removed `crap` successfully.
unlinkat(AT_FDCWD, "crap", 0)           = -1 ENOENT (No such file or directory)
unlinkat(AT_FDCWD, "crap", AT_REMOVEDIR) = -1 ENOENT (No such file or directory)

## mc --version
mc version RELEASE.2020-04-15T20-18-00Z

**Comment by kannappanr** [comment]
most of the `mc` commands will work on file systems too.

**Comment by harshavardhana** [comment]
You are right I am able to reproduce this issue @i0x71

**Comment by i0x71** [comment]
@kannappanr that makes sense, however I would expectc RM to remove local files rather than remove bucket specific RB

**Comment by i0x71** [comment]
Thanks for the fix! 👍
