### ISSUE TITLE
mc rm does nothing

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3177]
When running mc rm in the following fashion it goes over all of the files and returns after a while achieving nothing
~$ mc ls dot9/apitest | wc -l
3000

~$ time mc rm --force dot9/apitest/
Removing `dot9/apitest/`.

real	2m12.176s
user	0m7.040s
sys	0m2.119s
~$ mc ls dot9/apitest | wc -l
3000

--debug shows that its going over every single file in that bucket
What is the purpose of this behavior ?

If i run with -r it deletes the files properly

mc version RELEASE.2020-04-15T20-18-00Z

**Comment by harshavardhana** [comment]
@i0x71 empty folders are not removed in `mc rm` on purpose

**Comment by harshavardhana** [comment]
> --debug shows that its going over every single file in that bucket
> What is the purpose of this behavior ?

this looks incorrect

**Comment by harshavardhana** [comment]
> mc version RELEASE.2020-04-15T20-18-00Z

@i0x71 this should be fixed in latest release `mc version RELEASE.2020-04-15T20-18-00Z`

**Comment by i0x71** [comment]
What is the purpose of it going over all the files in the bucket and not deleting anything ?
Expected behavior would be that it empties the folder at that path

**Comment by i0x71** [comment]
Thanks, will test

**Comment by harshavardhana** [comment]
> Thanks, will test

Fixed in #3178

**Comment by i0x71** [comment]
Confirmed that it no longer goes over all the files, however isn't it misleading that it says Removing /folder yet it doesn't actually remove anything ?
I would expect it to empty that bucket

**Comment by harshavardhana** [comment]
> Confirmed that it no longer goes over all the files, however isn't it misleading that it says Removing /folder yet it doesn't actually remove anything ?

:+1: 

> I would expect it to empty that bucket

No, it shouldn't - it's too easy to accidentally delete, it is expected that bucket deletes should be recursive and should have necessary flags sent a fix in #3178

**Comment by i0x71** [comment]
Ok, thank you

**Comment by i0x71** [comment]
Would it at least make sense to not show that message "Removing /xxxxxxx" and just return nothing.
I believe standard Linux rm -f folder returns an error, hence you run rm -rf
