### ISSUE TITLE
mc: <ERROR> Unable to save new mc config. open /root/.mc/config.json: permission denied.

### ISSUE THREAD

**Issue by Bhanukiran117** [minio/mc#3184]
## Steps to reproduce the behavior

I am trying to execute the mc config from chef receipe as non root user.
I am getting following error.

mc: <ERROR> Unable to save new mc config. open /root/.mc/config.json: permission denied.

Where as same command is working fine from the user command prompt and config file creating under user home directory and in .mc 

## mc --version
- (paste output of `mc --version`)

mc --version
mc version RELEASE.2020-04-19T19-17-53Z

## System information
RHEL 7

**Comment by harshavardhana** [comment]
@Bhanukiran117 `mc` requires shell access without that it will fallback to default /home DIR set a specific $HOME if needed. 

It was never designed in non HOMEDIR environments.

**Comment by Bhanukiran117** [comment]
ok. Thank you.  I got the work around, i.e --config-dir and su - <user> -c "mc ------------- --config-dir(user home directory)"
