### ISSUE TITLE
mc not preserving ownership

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3186]
## Expected behavior
mc should preserve ownership

## Actual behavior
mc doesnt

## Steps to reproduce the behavior
~ ls -l cont/box0/ | grep scripts
drwxr-xr-x 2 **sshd daemon** 4096 Apr 22 15:10 scripts
~ mc mirror -a --remove --overwrite cont/box0/ dot9/cont/box0/
 0 B / ? 
~ rm -rf cont/box0 
~ mc mirror -a dot9/cont/box0/ cont/box0/
...000/cont/box0/testFile:  149 B / 149 B 7.03 KiB/s 0s
~ ls -l cont/box0/ | grep scripts
drwxr-xr-x 2 **root root** 4096 Apr 22 15:13 scripts

## mc --version
mc version RELEASE.2020-04-19T19-17-53Z

**Comment by klauspost** [comment]
Use the `--preserve` parameter to "preserve file(s)/object(s) attributes and bucket policy rules on target bucket(s)".

**Comment by i0x71** [comment]
I am using it "-a" is same as --preserve, according to help menu.
Either way just tried with --preserve instead of -a, same result

root@sandbox:~# ls -l cont/box0/| grep script
drwx------ 2 sshd daemon 4096 Apr 22 15:38 scripts
root@sandbox:~# mc mirror --preserve --remove --overwrite cont/box0/ dot9/cont/box0/
 0 B / ? _______________________________________________________________________________________________________________________________________________ 0s
root@sandbox:~# rm -rf cont/box0
root@sandbox:~# mc mirror --preserve dot9/cont/box0/ cont/box0/
...000/cont/box0/testFile:  149 B / 149 B ___________________________________________________________________________________________________ 7.09 KiB/s 0s
root@sandbox:~# ls -l cont/box0/| grep script
drwxr-xr-x 2 root root 4096 Apr 22 15:40 scripts

Neither ownership nor permission are preserved
