### ISSUE TITLE
mc not preserving ownership

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3187]
## Expected behavior
mc should preserve ownership

## Actual behavior
mc doesnt

## Steps to reproduce the behavior
~ ls -l cont/box0/ | grep scripts
drwxr-xr-x 2 sshd daemon 4096 Apr 22 15:10 scripts
~ mc mirror -a --remove --overwrite cont/box0/ dot9/cont/box0/
0 B / ?
~ rm -rf cont/box0
~ mc mirror -a dot9/cont/box0/ cont/box0/
...000/cont/box0/testFile: 149 B / 149 B 7.03 KiB/s 0s
~ ls -l cont/box0/ | grep scripts
drwxr-xr-x 2 root root 4096 Apr 22 15:13 scripts

@klauspost i am using -a flag which is same as --preserve as per ticket #3186 
Also tested with --preserve instead of -a, same result

## mc --version
mc version RELEASE.2020-04-19T19-17-53Z

**Comment by harshavardhana** [comment]
@i0x71 do you have permissions to apply permissions locally? Like chown? chmod?

**Comment by i0x71** [comment]
Yes, im running all of the commands as root.

**Comment by harshavardhana** [comment]
> Yes, im running all of the commands as root.

@i0x71 because I am able to preserve.

**Comment by i0x71** [comment]
Here is debug output if that helps

root@sandbox:~# chown sshd:daemon cont/box0/scripts                                                                                                        
root@sandbox:~# ls -l cont/box0/                                                                                                                           
total 4                                                                  
drwxr-xr-x 2 sshd daemon 4096 Apr 22 16:38 scripts                                                                                                         
root@sandbox:~# mc mirror -a --remove --overwrite cont/box0/ dot9/cont/box0/                                                                               
 0 B / ? _______________________________________________________________________________________________________________________________________________ 0s
root@sandbox:~# rm -rf cont/box0/                                                     
root@sandbox:~# mc mirror --debug -a dot9/cont/box0/ cont/box0/                                                                                            mc: <DEBUG> GET /cont/?location= HTTP/1.1                                                                                                                  
Host: 10.0.0.9:9000                                                                                                      
Accept-Encoding: gzip                                                                                                                                      
                                                                                       
mc: <DEBUG> HTTP/1.1 200 OK                                                           
Content-Length: 128                                                      
Accept-Ranges: bytes                                                                                                                                       
Content-Security-Policy: block-all-mixed-content                                                                        
Content-Type: application/xml                                                         
Date: Wed, 22 Apr 2020 16:39:21 GMT       
Server: MinIO/RELEASE.2020-04-15T19-42-18Z      
Vary: Origin                                                                                                                                              
X-Amz-Request-Id: 160831BE2352DB6D    
X-Xss-Protection: 1; mode=block                                     
mc: <DEBUG> Response Time:  1.572243ms          
                                                                                                                                                           
mc: <DEBUG> GET /cont/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=box0 HTTP/1.1              
Host: 10.0.0.9:9000                                                                                                                                       
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 351
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 22 Apr 2020 16:39:21 GMT
Server: MinIO/RELEASE.2020-04-15T19-42-18Z
Vary: Origin
X-Amz-Request-Id: 160831BE2368EA56
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  4.411311ms

 0 B / ? ____________________________________________
mc: <DEBUG> GET /cont/?object-lock= HTTP/1.1
Host: 10.0.0.9:9000
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Content-Length: 326
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 22 Apr 2020 16:39:21 GMT
Server: MinIO/RELEASE.2020-04-15T19-42-18Z
Vary: Origin
X-Amz-Request-Id: 160831BE23B24A3D
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ObjectLockConfigurationNotFoundError</Code><Message>Object Lock configuration does not exist for this bucket</Message><BucketName>cont</Bucket
Name><Resource>/cont/</Resource><RequestId>160831BE23B24A3D</RequestId><HostId>0e8ac155-b558-4751-8e56-3d3bbc9cdde4</HostId></Error>mc: <DEBUG> Response Ti
me:  6.690798ms

mc: <DEBUG> GET /cont/?policy= HTTP/1.1
Host: 10.0.0.9:9000
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Content-Length: 284
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 22 Apr 2020 16:39:21 GMT
Server: MinIO/RELEASE.2020-04-15T19-42-18Z
Vary: Origin
X-Amz-Request-Id: 160831BE241D7E32
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucketPolicy</Code><Message>The bucket policy does not exist</Message><BucketName>cont</BucketName><Resource>/cont/</Resource><RequestId
>160831BE241D7E32</RequestId><HostId>0e8ac155-b558-4751-8e56-3d3bbc9cdde4</HostId></Error>mc: <DEBUG> Response Time:  6.104099ms


mc: <DEBUG> GET /cont/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&metadata=true&prefix=box0%2F HTTP/1.1
Host: 10.0.0.9:9000
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 904
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 22 Apr 2020 16:39:21 GMT
Server: MinIO/RELEASE.2020-04-15T19-42-18Z
Vary: Origin
X-Amz-Request-Id: 160831BE2484B731
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  26.033439ms

mc: <DEBUG> HEAD /cont/box0/scripts/qqinit HTTP/1.1
Host: 10.0.0.9:9000
mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 129
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Wed, 22 Apr 2020 16:39:21 GMT
Etag: "6c4179266654d65b9a32f482ad4bd796"
Last-Modified: Wed, 22 Apr 2020 15:10:39 GMT
Server: MinIO/RELEASE.2020-04-15T19-42-18Z
Vary: Origin
X-Amz-Meta-Mc-Attrs: atime:1587567585/ctime:1587568233/gid:1/gname:daemon/mode:33216/mtime:1587567571/uid:105/uname:sshd
X-Amz-Meta-Mtime: 1587568418.265195772
X-Amz-Request-Id: 160831BE261715BC
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  7.33778ms

mc: <DEBUG> GET /cont/box0/scripts/qqinit HTTP/1.1
Host: 10.0.0.9:9000
Accept-Encoding: gzip


mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 129
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Wed, 22 Apr 2020 16:39:21 GMT
Etag: "6c4179266654d65b9a32f482ad4bd796"
Last-Modified: Wed, 22 Apr 2020 15:10:39 GMT
Server: MinIO/RELEASE.2020-04-15T19-42-18Z
Vary: Origin
X-Amz-Meta-Mc-Attrs: atime:1587567585/ctime:1587568233/gid:1/gname:daemon/mode:33216/mtime:1587567571/uid:105/uname:sshd
X-Amz-Meta-Mtime: 1587568418.265195772
X-Amz-Request-Id: 160831BE268AF264
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  7.826332ms

...nt/box0/scripts/qqinit:  129 B / 129 B ___________________________________________________________________________________________________ 2.96 KiB/s 0s
root@sandbox:~# ls -l cont/box0/
total 4
drwxr-xr-x 2 root root 4096 Apr 22 16:39 scripts

**Comment by i0x71** [comment]
Running this on a freshly installed debian buster

**Comment by i0x71** [comment]
Is there any other debug info i can provide ?

**Comment by harshavardhana** [comment]
> X-Amz-Meta-Mc-Attrs: atime:1587567585/ctime:1587568233/gid:1/gname:daemon/mode:33216/mtime:1587567571/uid:105/uname:sshd

Yep the attributes are correct @i0x71 so it is preserved, but it's not persisting.

**Comment by ebozduman** [comment]
I reproduced the issue with `mc mirror` and `mc cp` commands.
Both ownership and group info are not preserved at the destination object.
Looking into it now.
