### ISSUE TITLE
[future] [Feature] add parameter to mc to avoid creating local files/folders

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3190]
Hello,
I would like to propose a suggestion to at least add a flag to mc to prevent it from creating local files and folders when user does not intend to, like in the following scenario:

echo test | mc pipe minioServ1/some/path/file.txt
In this case mc will exit with 0 and will create a local folder minioServ1 (if minioServ1) does not exist in the configuration.
This is completely misleading, i have personally ran into this many times already where on one of the machines "minioServ1" config does not exist and mc creates a local folder instead. If i wanted to create a local folder i would have used cp or other standard unix tools instead.
When i use mc client it is to **specifically interact with a minio server** rather than local file system and frankly mixing the 2 fields is a recipe for disaster, like in cases where mc will delete local files and folders rather than on the minio server.

As i don't foresee the devs changing this behavior, i kindly request to at least add a flag which can be passed to mc which will prevent it from interacting (creating/removing) with local filesystem and throw an error instead if the relevant config is not found.

Thanks

**Comment by juv** [comment]
I have also ran into this problem a few times. When using `mc ls {path}` it is not obvious is that is coming from the local storage or a remote (minio/s3/whatever) server

**Comment by i0x71** [comment]
Bump

**Comment by rotten** [comment]
:+1: 

I'm new to minio and I'm finding this really confusing.
