### ISSUE TITLE
mc mv slow response because of minio error

### ISSUE THREAD

**Issue by BigUstad** [minio/mc#3192]
## Expected behavior
I executed the following commands. It executes eventually just fine with the correct end result of moving one file. Minio server is running/listening on port 9000. It is a gateway to S3.
NOTE: I've removed some IP information below.
$ mc config host list s3gateway
s3gateway
  URL       : https://<Local_IP_Address>:9000
  AccessKey : <S3_Gateway_AccessKey>
  SecretKey : <S3_Gateway_SecretKey>
  API       : s3v4
  Lookup    : auto

$ mc mb s3gateway/pribkt3/samplecsvdata/
$ mc cp ~/Downloads/TotalPopulationByGender.csv.gz s3gateway/pribkt3/samplecsvdata/
$ mc mb s3gateway/pribkt3/samplecsvdata/archive/
$ mc mv s3gateway/pribkt3/samplecsvdata/TotalPopulationByGender.csv.gz s3gateway/pribkt3/samplecsvdata/archive/
$ mc ls s3gateway/pribkt3/samplecsvdata/archive/
[2020-04-26 23:20:50 PDT]  5.7MiB TotalPopulationByGender.csv.gz

Complete moving 
## Actual behavior
This error is seen on minio server(gateway) side. Because of this error the response is delayed.
API: GetBucketObjectLockConfig(bucket=pribkt3)
Time: 23:17:16 PDT 04/26/2020
DeploymentID: 0eae6977-449b-4001-98c7-093b3da906da
RequestID: 160998B28D5E4668
RemoteHost: <Local_IP_Address>
Host: <Local_IP_Address>:9000
UserAgent: MinIO (darwin; amd64) minio-go/v6.0.54 mc/DEVELOPMENT.GOGET
Error: Bucket name contains invalid characters
       configFile=buckets/pribkt3/object-lock-enabled.json
       4: github.com/minio-bucket-tagging/cmd/api-errors.go:1831:cmd.toAPIErrorCode()
       3: github.com/minio-bucket-tagging/cmd/api-errors.go:1856:cmd.toAPIError()
       2: github.com/minio-bucket-tagging/cmd/bucket-handlers.go:1110:cmd.objectAPIHandlers.GetBucketObjectLockConfigHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

## Steps to reproduce the behavior
Run all the commands shown in the Expected behavior section.

## mc --version
- (paste output of `mc --version`)
mc version DEVELOPMENT.GOGET

## System information
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G3020

**Comment by harshavardhana** [comment]
are you using gateway on server @BigUstad ?

**Comment by BigUstad** [comment]
gateway on S3.

**Comment by harshavardhana** [comment]
> minio gateway s3 https://s3.amazonaws.com --address :9000

@BigUstad gateway code doesn't support object locking.

**Comment by BigUstad** [comment]
mc mv execution is delayed. Attaching the debug information for your review.
[2020Apr26_BucketName_InvalidCharacters.txt](https://github.com/minio/mc/files/4537952/2020Apr26_BucketName_InvalidCharacters.txt)

**Comment by harshavardhana** [comment]
> mc mv execution is delayed. Attaching the debug information for your review.

It is delayed because `minio-go` retrying the operation and server is failing with internal server error.

**Comment by harshavardhana** [comment]
This is not an issue just lack of feature on server @BigUstad

**Comment by BigUstad** [comment]
OK. Thank you.
