### ISSUE TITLE
Error message with "WORM" reference although "WORM" is deprecated

### ISSUE THREAD

**Issue by ebozduman** [minio/mc#3194]
## Expected behavior
No references to removed/deprecated `"WORM"` feature (PR#9436: deprecate/remove global WORM mode) is expected to be seen in error messages.

## Actual behavior
Error message comes with a reference to deprecated/removed feature, `"WORM"`.
`mc: <ERROR> Failed to copy `/etc/issue`. Object is WORM protected and cannot be overwritten`

## Steps to reproduce the behavior
Example:
- Retention error message after `mc cp` command to copy the same file on top of itself 
`mc: <ERROR> Failed to copy `/etc/issue`. Object is WORM protected and cannot be overwritten`
- Try to delete an object protected by lock/retention mechanism.

I  am not sure one or more error messages are out there.

## Version
$ mc --version
mc version DEVELOPMENT.2020-04-27T23-48-39Z

## System information
MinIO FS

**Comment by harshavardhana** [comment]
WORM still exists a a feature on MinIO i.e object locking / retention @ebozduman 

What is removed is global WORM

**Comment by kannappanr** [comment]
Closing this issue now. We can look at this when we have versioning and make sure that it is behaving exactly like AWS S3.

**Comment by Rocking80** [comment]
Seems new version of minio can clone WORM objects now.

```shell
# mc retention info minio/bucket-123/Activate.ps1-cloned-2
Name    : minio/bucket-123/Activate.ps1-cloned-2
Mode    : COMPLIANCE, expiring in 7 hours 42 minutes

# mc cp minio/bucket-123/Activate.ps1-cloned-2 minio/bucket-123/Activate.ps11
...t-123/Activate.ps1-cloned-2:  18.88 KiB / 18.88 KiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 308.00 KiB/s 0s

# mc retention info -r minio/bucket-123/
[     COMPLIANCE     ]  minio/bucket-123/Activate.ps1-cloned-2
[    NO RETENTION    ]  minio/bucket-123/Activate.ps11
```
