### ISSUE TITLE
"mc mv"  fails on a locked object, but creates the target object

### ISSUE THREAD

**Issue by ebozduman** [minio/mc#3198]
## Expected behavior
`mc mv` command to move/rename an object protected with retention `compliance` mode ends up with a meaningful error message, like:
`issue` is the protected object.
```
$ mc mv myminio/bucketlock/issue myminio/bucketlock/issue1 
`mc: <ERROR> Failed to move source to target. Source object is WORM protected and cannot be moved (removed).` 
```
and no left overs like a newly created object, `issue1` at the destination.

## Actual behavior
It looks like we copy the source to target and create a new object at the destination first, and then check if the source object is protected or not before removing it. Since the source object is protected, we give up removing it and end up with 2 objects. 
So, basically move works as copy command for retention protected objects.

```
$ mc mv myminio/bucketlock/issue myminio/bucketlock/issue1 
...bucketlock/issue:  26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 638 B/s 0s
```
and the destination, the same location with the source in this case, has a newly created file.
```
$ mc stat myminio/bucketlock/
Name      : issue
Date      : 2020-05-02 22:29:04 PDT 
Size      : 26 B   
ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f 
Type      : file 
Metadata  :
  X-Amz-Object-Lock-Retain-Until-Date: 2020-05-05T05:30:05Z 
  Content-Type                       : application/octet-stream 
  X-Amz-Object-Lock-Mode             : COMPLIANCE 

Name      : issue1
Date      : 2020-05-02 22:41:23 PDT 
Size      : 26 B   
ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f 
Type      : file 
Metadata  :
  Content-Type                       : application/octet-stream 
  X-Amz-Object-Lock-Retain-Until-Date: 2020-05-04T05:41:23Z 
  X-Amz-Object-Lock-Mode             : GOVERNANCE 
```

## Steps to reproduce the behavior
1. $ mc mb myminio/bucketlock -l
Bucket created successfully `myminio/bucketlock`.
2. $ mc lock myminio/bucketlock/ governance 1d
GOVERNANCE mode is enabled for 1d
3. $ mc cp --retention-mode compliance --retention-duration 1d /etc/issue myminio/bucketlock/
/etc/issue:               26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 2.00 KiB/s 0s
4.  $ mc stat myminio/bucketlock/
Name      : issue
Date      : 2020-05-03 00:26:49 PDT 
Size      : 26 B   
ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f 
Type      : file 
Metadata  :
  Content-Type                       : application/octet-stream 
  X-Amz-Object-Lock-Retain-Until-Date: 2020-05-04T07:26:49Z 
  X-Amz-Object-Lock-Mode             : COMPLIANCE 
5. $ mc mv myminio/bucketlock/issue myminio/bucketlock/issue1
...000/bucketlock/issue:  26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 2.74 KiB/s 0s
6. $ mc stat myminio/bucketlock/
Name      : issue
Date      : 2020-05-03 00:26:49 PDT 
Size      : 26 B   
ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f 
Type      : file 
Metadata  :
  Content-Type                       : application/octet-stream 
  X-Amz-Object-Lock-Retain-Until-Date: 2020-05-04T07:26:49Z 
  X-Amz-Object-Lock-Mode             : COMPLIANCE 

Name      : issue1
Date      : 2020-05-03 00:27:57 PDT 
Size      : 26 B   
ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f 
Type      : file 
Metadata  :
  Content-Type                       : application/octet-stream 
  X-Amz-Object-Lock-Retain-Until-Date: 2020-05-04T07:27:57Z 
  X-Amz-Object-Lock-Mode             : GOVERNANCE 

## mc --version
mc version DEVELOPMENT.2020-05-02T07-40-50Z

## System information
$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 MINIO_REGION="us-east-1" minio server /data

**Comment by balamurugana** [comment]
https://github.com/minio/mc/blob/master/cmd/mv-main.go#L298 check shouldn't pass, is the bucket lock-enabled?

**Comment by ebozduman** [comment]
Hi @balamurugana, 
Yes. Bucket lock was enabled and its default retention was set on the bucket as "governance 1d".
You can see the same information in the reproduction steps...

I agree. The first thing we should be doing is the check to see if the source is protected or not, as the source object will be removed after the target object is created. 
If protected, we should give up right away, unless user has a policy with retention bypass permission and the object retention is set to "governance" mode.

**Comment by ebozduman** [comment]
@balamurugana 
Another problem is sometimes, not sure when, `mc mv` command ends up with a complete progress bar and an error/failure message. 
```
$ mc mv mm3/bucket/issue mm3/bucket/issue1
....8:9000/bucket/issue:  26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 1.52 KiB/s 0s
mc: <ERROR> Failed to remove in `http://192.168.1.8:9000/bucket/issue`. Object is WORM protected and cannot be overwritten
```
This also needs to be cleaned up and the progress bar should not be displayed.

Some settings:
```
$  mc lock mm3/bucket/
GOVERNANCE mode is enabled for 3d
$ mc ls mm3/bucket/
[2020-05-01 20:23:03 PDT]     26B file
[2020-05-01 20:23:03 PDT]     26B issue
[2020-05-03 01:35:07 PDT]     26B issue1
$ mc stat mm3/bucket/
Name      : file
Date      : 2020-05-01 20:23:03 PDT 
Size      : 26 B   
ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f 
Type      : file 
Metadata  :
  Content-Type                       : application/octet-stream 
  X-Amz-Object-Lock-Mode             : GOVERNANCE 
  X-Amz-Meta-Mc-Attrs                : atime:1588389645/ctime:1588389541/gid:1001/gname:ab/mode:33188/mtime:1588389472/uid:1001/uname:ab 
  X-Amz-Object-Lock-Retain-Until-Date: 2020-05-05T03:23:03Z 

Name      : issue
Date      : 2020-05-01 20:23:03 PDT 
Size      : 26 B   
ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f 
Type      : file 
Metadata  :
  X-Amz-Object-Lock-Retain-Until-Date: 2020-05-05T03:23:03Z 
  Content-Type                       : application/octet-stream 
  X-Amz-Meta-Mc-Attrs                : atime:1588389706/ctime:1588389541/gid:1001/gname:ab/mode:33188/mtime:1588389484/uid:1001/uname:ab 
  X-Amz-Object-Lock-Mode             : GOVERNANCE 

Name      : issue1
Date      : 2020-05-03 01:35:07 PDT 
Size      : 26 B   
ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f 
Type      : file 
Metadata  :
  Content-Type                       : application/octet-stream 
  X-Amz-Meta-Mc-Attrs                : atime:1588389706/ctime:1588389541/gid:1001/gname:ab/mode:33188/mtime:1588389484/uid:1001/uname:ab 
  X-Amz-Object-Lock-Mode             : GOVERNANCE 
  X-Amz-Object-Lock-Retain-Until-Date: 2020-05-06T08:35:07Z

**Comment by balamurugana** [comment]
Try with this PR https://github.com/minio/mc/pull/3199, it makes `mc mv` to fail immediately if source/destination buckets have object lock enabled.

**Comment by ebozduman** [comment]
Sounds good. Thank you
