### ISSUE TITLE
mc update returns 1 on success

### ISSUE THREAD

**Issue by markkutikkanen** [minio/mc#3207]
## Expected behavior
standard return value is 0 when no error
## Actual behavior
```
markkut:~ $ sudo mc update
[sudo] password for markkut: 

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of mc released 1 week ago ┃
┃ Update: https://dl.min.io/client/mc/release/linux-amd64/mc ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

mc updated to version RELEASE.2020-05-05T06-03-47Z successfully.
markkut:~ $ echo $?
1
```
## Steps to reproduce the behavior
Update the mc client successfully
## mc --version
- (paste output of `mc --version`)
RELEASE.2020-04-25T00-43-23Z
## System information
Linux amd64

**Comment by harshavardhana** [comment]
Its mentioned here 

```
EXIT STATUS:
  0 - you are already running the most recent version
  1 - new update was applied successfully
 -1 - error in getting update information
```

**Comment by markkutikkanen** [comment]
I'd like to know why `mc` deviates from industry standard. https://www.tldp.org/LDP/abs/html/exit-status.html

**Comment by markkutikkanen** [comment]
@harshavardhana would you be so kind to enlighten me. It's pretty awkward when scripts and tools like Ansible see successful updates as failed.
