### ISSUE TITLE
mc copy not copying the soft link correctly

### ISSUE THREAD

**Issue by Bhanukiran117** [minio/mc#3208]
## Actual behavior

Actually I am trying copy with --recursive directory which has a softlink

lrwxrwxrwx. 1 root root    1 May  6 11:47 b -> a
-rw-------. 1 root root 3893 May  6 11:54 a

In Cloud bucket I can see both a and b two different files of same size.

I am planning to take filesystems backups to cloud, How do I get the files same as in filesystem while copy back from cloud to filesystem. 

## mc --version

mc version RELEASE.2020-04-19T19-17-53Z
## System information
CentOS Linux release 7.8.2003 (Core)

**Comment by harshavardhana** [comment]
symlinks are ignored on `mc` because object storage doesn't support them. @Bhanukiran117 - this is by design and nothing can be fixed for this.
