### ISSUE TITLE
mc head crashes

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3210]
## Actual behavior
mc crashes when given a nonexistant file
mc head -n 1 dot9/dump/dsfsdfsdf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb67cdb]

goroutine 1 [running]:
github.com/minio/mc/cmd.headURL(0x7ffd2b810f07, 0x13, 0xc000309ad0, 0x1, 0x0)
        github.com/minio/mc@/cmd/head-main.go:102 +0x4cb
github.com/minio/mc/cmd.mainHead(0xc00030ad00, 0x0, 0x30ad00)
        github.com/minio/mc@/cmd/head-main.go:172 +0xfd
github.com/minio/cli.HandleAction(0xc6a9c0, 0xdf0a30, 0xc00030ad00, 0xc00032e000, 0x0)
        github.com/minio/cli@v1.22.0/app.go:498 +0xc8
github.com/minio/cli.Command.Run(0xd97365, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdba0b5, 0x24, 0x0, ...)
        github.com/minio/cli@v1.22.0/command.go:225 +0x991
github.com/minio/cli.(*App).Run(0xc00009f6c0, 0xc000030050, 0x5, 0x5, 0x0, 0x0)
        github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
github.com/minio/mc/cmd.Main(0xc000030050, 0x5, 0x5)
        github.com/minio/mc@/cmd/main.go:118 +0x341
main.main()
        github.com/minio/mc@/main.go:34 +0x45

## mc --version
mc version RELEASE.2020-04-25T00-43-23Z

**Comment by harshavardhana** [comment]
> mc head -n 1 dot9/dump/dsfsdfsdf

Thanks looks like a silly bug, we shall fix.

**Comment by harshavardhana** [comment]
Ah this is fixed by #3206 we shall be making a new release.
