### ISSUE TITLE
mc display similar files instead of a single file

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3211]
## Expected behavior
mc stat displays multiple similar files rather than the only the one requested.

## Actual behavior
mc stat dot9/dump/test

Name      : test
Date      : 2020-04-23 13:12:14 UTC 
Size      : 347 KiB 
ETag      : 2f5c7c95ea0b08a9538f5d9bbf7c169f-1 
Type      : file 
Metadata  :
  Content-Type: application/octet-stream 

Name      : test1
Date      : 2020-05-05 20:09:56 UTC 
Size      : 100 MiB 
ETag      : b3578a3ae4d4d13d4e3130f966d29d94 
Type      : file 
Metadata  :
  Content-Type: application/octet-stream 

Name      : test2
Date      : 2020-05-06 17:47:20 UTC 
Size      : 0 B    
ETag      : d41d8cd98f00b204e9800998ecf8427e 
Type      : file 
Metadata  :
  Content-Type: application/octet-stream 

## mc --version
RELEASE.2020-04-25T00-43-23Z

It doesn't make sense to display all the similar objects when only a single object is being requested, if anything its misleading.
In my scenario im trying to check if object exists before accessing it, with the current behavior this functionality is impossible to achieve.
It would only make sense to display similar files if the command is being ran with an asterisk on the end
mc stat dot9/dump/test*****

**Comment by harshavardhana** [comment]
> mc stat dot9/dump/test

This is on purpose it does prefix match by default @i0x71

**Comment by harshavardhana** [comment]
> In my scenario im trying to check if object exists before accessing it, with the current behavior this functionality is impossible to achieve.

You shouldn't be using `mc` for that, you should be writing code using an SDK

**Comment by harshavardhana** [comment]
> In my scenario im trying to check if object exists before accessing it, with the current behavior this functionality is impossible to achieve.

Also, there is no point in doing that there is no guarantee that HEAD if succeeds GET would definitely succeed, as both are disconnected HTTP calls.  if HEAD succeeds before you send a GET there is room for someone to set DELETE so your GET would fail. 

If you have a controlled environment where you say you never send DELETE then you can happily do just GET instead of HEAD because you have a controlled environment, in an un-controlled environment there is no point doing HEAD at all. 

So I think what you are doing is incorrect in terms of its expectations.

**Comment by harshavardhana** [comment]
> There could be situations where mc could be used to assist with sysadmin duties, such as backing up files. Since snapshots are not part of the s3 spec these things could be implement by simply wrapping mc in bash script and achieving what is needed.
> 
> Basically im just trying wrap backing up a file before overwriting it
> mc cp box/second_latest box/third_latest
> mc cp box/latest box/second_latest
> 
> In the scenario above it would good to check if the file exists before trying to copy it, as the first time you run the command it for sure will not exist.
> 
> Rather writing a dedicated tool for this simple task, to me it makes sense to use mc for this.

That is very easy to do rely on `mc stat --json | jq ` to look for correct entries as they are presented it shall solve your conundrum.

We cannot change the prefix behavior as it is a design requirement for us.

**Comment by i0x71** [comment]
Ok, thanks
