### ISSUE TITLE
Received excess data on input reader on mc cp from bucket to local fs

### ISSUE THREAD

**Issue by michagruner** [minio/mc#3215]
## Expected behavior
File is copied from a minio S3 bucket to the local filesystem
## Actual behavior
Copy job exits and throws the error message "Received excess data on input reader. Expected only `4504670` bytes, but received `18009689` bytes."
## Steps to reproduce the behavior
`user@server-management:~$ ./mc mb play/xinurg`
Bucket created successfully `play/xinurg`.
`user@server-management:~$ ./mc cp /tmp/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082 play/xinurg/`
...f12b207b082:  4.30 MiB / 4.30 MiB ┃┃ 46.61 KiB/s 1m34s
`user@server-management:~$ ./mc cp play/xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082 /tmp/`
mc: <ERROR> Failed to copy `https://play.min.io/xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082`. Received excess data on input reader. Expected only `4504670` bytes, but received `18009689` bytes.
...f12b207b082:  4.30 MiB / 4.30 MiB ┃┃ 341.77 KiB/s 12s
user@server-management:~$ ./mc cp --debug play/xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082 /tmp/
mc: <DEBUG> GET /xinurg/?location= HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v6.0.54 mc/2020-04-17T08:55:48Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200508/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200508T073331Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 08 May 2020 07:37:02 GMT
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin
X-Amz-Request-Id: 160CFD6F2D55E9F9
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  763.811239ms

mc: <DEBUG> HEAD /xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082 HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v6.0.54 mc/2020-04-17T08:55:48Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200508/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200508T073332Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 4504670
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Fri, 08 May 2020 07:37:02 GMT
Etag: "460932be64e8cefb4c9e9dcb8fbc1f9a"
Last-Modified: Fri, 08 May 2020 07:35:09 GMT
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin
X-Amz-Request-Id: 160CFD6F37E41F1C
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  173.685421ms

mc: <DEBUG> HEAD /xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082 HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v6.0.54 mc/2020-04-17T08:55:48Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200508/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200508T073332Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 4504670
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Fri, 08 May 2020 07:37:02 GMT
Etag: "460932be64e8cefb4c9e9dcb8fbc1f9a"
Last-Modified: Fri, 08 May 2020 07:35:09 GMT
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin
X-Amz-Request-Id: 160CFD6F422D9CF0
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  169.018277ms

mc: <DEBUG> HEAD /xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082 HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v6.0.54 mc/2020-04-17T08:55:48Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200508/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200508T073332Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 4504670
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Fri, 08 May 2020 07:37:03 GMT
Etag: "460932be64e8cefb4c9e9dcb8fbc1f9a"
Last-Modified: Fri, 08 May 2020 07:35:09 GMT
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin
X-Amz-Request-Id: 160CFD6F4C5A4C73
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  171.461776ms

 0 B / ? ┃┃mc: <DEBUG> HEAD /xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082 HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v6.0.54 mc/2020-04-17T08:55:48Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200508/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200508T073332Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 4504670
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Fri, 08 May 2020 07:37:03 GMT
Etag: "460932be64e8cefb4c9e9dcb8fbc1f9a"
Last-Modified: Fri, 08 May 2020 07:35:09 GMT
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin
X-Amz-Request-Id: 160CFD6F56AE33E4
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  167.220353ms

 0 B / ? ┃┃mc: <DEBUG> HEAD /xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082 HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v6.0.54 mc/2020-04-17T08:55:48Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200508/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200508T073332Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 4504670
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Fri, 08 May 2020 07:37:03 GMT
Etag: "460932be64e8cefb4c9e9dcb8fbc1f9a"
Last-Modified: Fri, 08 May 2020 07:35:09 GMT
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin
X-Amz-Request-Id: 160CFD6F60C6316B
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  168.721784ms

...f12b207b082:  0 B / 4.30 MiB ┃┃mc: <DEBUG> HEAD /xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082 HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v6.0.54 mc/2020-04-17T08:55:48Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200508/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200508T073332Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 4504670
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Fri, 08 May 2020 07:37:03 GMT
Etag: "460932be64e8cefb4c9e9dcb8fbc1f9a"
Last-Modified: Fri, 08 May 2020 07:35:09 GMT
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin
X-Amz-Request-Id: 160CFD6F6AE9F665
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  171.468805ms

...f12b207b082:  4.30 MiB / 4.30 MiB ┃┃ 6.82 MiB/smc: <DEBUG> GET /xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082 HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v6.0.54 mc/2020-04-17T08:55:48Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200508/us-east-1/s3/aws4_request, SignedHeaders=host;if-match;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
If-Match: "460932be64e8cefb4c9e9dcb8fbc1f9a"
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200508T073333Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 4504670
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Fri, 08 May 2020 07:37:03 GMT
Etag: "460932be64e8cefb4c9e9dcb8fbc1f9a"
Last-Modified: Fri, 08 May 2020 07:35:09 GMT
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin
X-Amz-Request-Id: 160CFD6F7879AB6F
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  234.916812ms

mc: <ERROR> Failed to copy `https://play.min.io/xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082`. Received excess data on input reader. Expected only `4504670` bytes, but received `22514359` bytes.
 (3) cp-main.go:545 cmd.doCopySession(..) Tags: [https://play.min.io/xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082]
 (2) common-methods.go:493 cmd.uploadSourceToTargetURL(..) Tags: [https://play.min.io/xinurg/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082]
 (1) common-methods.go:317 cmd.putTargetStream(..) Tags: [, /tmp/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082]
 (0) client-fs.go:377 cmd.(*fsClient).put(..)
 Release-Tag:RELEASE.2020-04-17T08-55-48Z | Commit:2d6a960f9486 | Host:server-management | OS:linux | Arch:amd64 | Lang:go1.13.10 | Mem:3.2 MB/72 MB | Heap:3.2 MB/66 MB
...f12b207b082:  4.30 MiB / 4.30 MiB ┃┃ 474.63 KiB/s 
user@server-management:~$ file /tmp/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082
/tmp/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082: data

## mc --version
mc version RELEASE.2020-04-17T08-55-48Z

## System information
Linux server-management 4.19.107-1.pvops.qubes.x86_64 #1 SMP Sat Feb 29 16:04:42 UTC 2020 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@michagruner thanks for reporting this.

This is an intermittent issue and I was able to reproduce after several retries.

I suspect this is caused by a retry mechanism inside minio-go

@michagruner I wanted to make sure, do you have a decent internet connection ?

**Comment by michagruner** [comment]
@vadmeste thanks for answering to the issue. I think my internet connection is quite decent. I faced the same issue when trying to download from my selfhosted homelab minio-server. What I also noticed: on the first try the client mentioned to have received a file smaller than expected, while on the retries the received file size was larger than expected.

Is the issue placed correct in the client or is this a server issue?

I tried the same procedure with aws cli and that worked out well.

**Comment by vadmeste** [comment]
@michagruner I was able to reproduce it locally, it seems it is a regression somewhere when you stop prematurely the cp command and start it over again.

You should be able to find the following file in your machine: /tmp/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082.minio.part

If you remove it and execute your copy command again, it should succeed.

**Comment by michagruner** [comment]
@vadmeste thanks. You're right. Using the play-environment I can download after deleting the .part-file. Using my home-server doesn't work. It creates the `.part` file and exits with:

mc: <ERROR> Failed to copy `https://s3.myserver/mybucket/data/00/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082`. Input reader closed pre-maturely. Expected `4504670` bytes, but only received `4501673` bytes.
 (3) cp-main.go:545 cmd.doCopySession(..) Tags: [https://s3.myserver/mybucket/data/00/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082]
 (2) common-methods.go:493 cmd.uploadSourceToTargetURL(..) Tags: [https://s3.myserver/mybucket/data/00/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082]
 (1) common-methods.go:317 cmd.putTargetStream(..) Tags: [, /tmp/000f8e5d889bb88eb7499132e6acbcdc0ff746f9a278d561e5282f12b207b082]
 (0) client-fs.go:370 cmd.(*fsClient).put(..)
 Release-Tag:RELEASE.2020-04-17T08-55-48Z | Commit:2d6a960f9486 | Host:server-management | OS:linux | Arch:amd64 | Lang:go1.13.10 | Mem:3.0 MB/72 MB | Heap:3.0 MB/66 MB

Any idea where to look next in my setup?

**Comment by vadmeste** [comment]
@michagruner I sent a draft PR to fix the first issue

@michagruner for the second issue, is it consistent ? do you see any logs in server's side ?

**Comment by michagruner** [comment]
@vadmeste thanks for filing the PR.

I must admit, my setup might not be the easiest out there; it looks like this:

OpenBSD relayd (ssl termination) -> traefik@docker -> minio@docker

From my perspective the issue is how the relayd reverse proxy is handling the mc client connection compared to the aws cli connection on the same cp task (that works in every case with the aws cli).

Lets see:
## mc cp
relay_tls_transaction: session 1: scheduling on EV_READ
relay httpstohttp, tls session 1 established (1 active)
relay_tls_transaction: session 1: scheduling on EV_WRITE
relay httpstohttp, tls session 1 connected (1 active)
relay httpstohttp, session 1 (1 active), 0, 127.0.0.1 -> :9443, Invalid argument (500 Internal Server Error), GET -> 192.168.1.139:9443; HEAD; HEAD HEAD HEAD HEAD HEAD GET: Invalid argument
## aws cp s3
relay_tls_transaction: session 1: scheduling on EV_READ
relay httpstohttp, tls session 1 established (1 active)
relay_tls_transaction: session 1: scheduling on EV_WRITE
relay httpstohttp, tls session 1 connected (1 active)
relay_tls_transaction: session 2: scheduling on EV_READ
relay httpstohttp, tls session 2 established (1 active)
relay_tls_transaction: session 2: scheduling on EV_WRITE
relay httpstohttp, tls session 2 connected (1 active)
relay httpstohttp, session 2 (1 active), 0, 127.0.0.1 -> 192.168.1.139:9443, done, GET -> 192.168.1.139:9443;
relay httpstohttp, session 1 (1 active), 0, 127.0.0.1 -> 192.168.1.139:9443, done, HEAD -> 192.168.1.139:9443;

Seems like the communication the mc client is initiating gives my relayd some headache because of malformed requests (or respones?). Are you interested in digging deeper in to this. I'm willing to help if there is a need to solve this and dig deeper into whats happening here. Otherwise I'm happy to try to solve my mirroring-problem with the aws cli for the time being.

**Comment by philipkozeny** [comment]
@vadmeste FYI, seeing the same issue / error when using mc mirror command, always happens on the same object. 

- source is running with a single disk
- file is in the source and can be downloaded / content shown with cat
- I can verify that the content is the same (I save a sha256 hash of the file in my database before uploading and downloaded the file and verified that the hash is still the same)

I am running an Nginx reverse proxy in front of the source and get the error always on the same files with the mirror command.

**Comment by vadmeste** [comment]
@philipkozeny please check if you have any incomplete download in your machine, something like your-object-name.part.minio, delete it and try again. There is an open PR (https://github.com/minio/mc/pull/3216) which should fix it.

**Comment by philipkozeny** [comment]
@vadmeste thanks, confirmed works after deleting the *.part.minio files
