### ISSUE TITLE
mc mirror does not run without --region although bucket exists

### ISSUE THREAD

**Issue by philipkozeny** [minio/mc#3222]
## Expected behavior
I am running a mc mirror command with --overwrite and --remove from a local minio server to a remote minio server. I expect the mirror command to work without adding a --region command. The remote minio server has a custom region setting (eu-central).

The bucket exists in remote and the command works as expected with the --region argument, mirroring works when adding the command, e.g.

`mc mirror --region=eu-central --overwrite --remove local/test-demo remote/test-demo-backup
`
## Actual behavior

`mc: <ERROR> Unable to create bucket at `remote/test-demo-backup/`. The authorization header is malformed; the region is wrong; expecting 'us-east-1'.`

## Steps to reproduce the behavior

- create two minio instances
- set custom region
- create bucket on remote with --region
- mirror without region command

## mc --version
- RELEASE.2020-05-16T01-44-37Z

## System information
-

**Comment by harshavardhana** [comment]
This is because you have GetBucketLocation permission missing for the account, we expect you to either provide this permission for us to auto fetch the region or specify the region manually..

**Comment by harshavardhana** [comment]
Alternatively use the right region URL so we can assume region in the URL

**Comment by philipkozeny** [comment]
Thanks @harshavardhana, makes sense and I am using the parameter. 

Just from my point of view: Maybe the error message „unable to create bucket“ is a bit misleading since a permission (GetBucketLocation) is missing or a parameter is needed. Thanks for the heads up, guess we can close the issue!
