### ISSUE TITLE
`mc update` does not use http_proxy

### ISSUE THREAD

**Issue by BLuFeNiX** [minio/mc#3225]
## Expected behavior
All networking is done via proxy, if configured.

## Actual behavior
`mc update` does not use the proxy

```
root@b76efd39aa1b:/# ./mc update
mc: <ERROR> Unable to update ‘mc’. Get https://dl.min.io/client/mc/release/linux-amd64/mc.shasum: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

## Steps to reproduce the behavior
configure proxy like:
```
export http_proxy="http://myproxy.local:3128"
export https_proxy="http://myproxy.local:3128"
export HTTPS_PROXY="http://myproxy.local:3128"
export HTTP_PROXY="http://myproxy.local:3128"
```
and then run `mc update`

## mc --version
mc version RELEASE.2020-05-16T01-44-37Z

## System information
Ubuntu 20.04 docker container

**Comment by krishnasrinivas** [comment]
@BLuFeNiX to update mc docker image, you have to just pull the latest image.

doing `mc update` inside docker container is not useful, `mc update` is designed not to be run inside the container.

**Comment by harshavardhana** [comment]
> @BLuFeNiX to update mc docker image, you have to just pull the latest image.
> 
> doing `mc update` inside docker container is not useful, `mc update` is designed not to be run inside the container.

As @krishnasrinivas mentioned containers are meant to be immutable and shouldn't be modified. Any such modified is not saved. So doing docker pull is the way to update the container which supports proxy.

**Comment by BLuFeNiX** [comment]
@krishnasrinivas @harshavardhana 
It is irrelevant whether I am using a docker container or not. `mc update` will also not use the proxy in a non-docker environment.

**Comment by harshavardhana** [comment]
> @krishnasrinivas @harshavardhana 
> It is irrelevant whether I am using a docker container or not. `mc update` will also not use the proxy in a non-docker environment.

Not irrelevant, the reproducer you showed made it relevant.

We will see if we can address the proxy support in future.

**Comment by BLuFeNiX** [comment]
@harshavardhana And what if I had reproduced this issue using an Ubuntu virtual machine? Would you say that I must configure my hypervisor to direct all VM traffic through the proxy? The particulars of environment do not change the existence of the bug.

It is fully your decision to support or not support the feature, but it has nothing to do with docker because the issue also reproduces in the absence of docker.

Thanks for your time.

**Comment by ebozduman** [comment]
@BLuFeNiX 

I setup nginx reverse proxy on my Ubuntu system and ran `mc update` without any problem. So, I cannot reproduce the issue.

Please let me know if you have specific reproduction steps for us to be able to reproduce the issue and probably your proxy configuration file for me to compare yours with my setup.

Thank you very much for your help.
