### ISSUE TITLE
mc mirror does not take automatically take into account the region

### ISSUE THREAD

**Issue by gbe** [minio/mc#3228]
## Expected behavior
I expect mc to take into account the region set-up when creating the bucket without ever trying to authenticate against another region.

## Actual behavior
For every commands, I have noticed that mc submits the following Authorization header:
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED*

As a result, my provider (Scaleway, region fr-par) returns an error that this region is not the good one and mc does not recover from this in mirror mode.

For other commands like cp, somehow the workflow continues and the region us-east-1 gets correctly replaces by fr-par in subsequent http requests... but not for mirror where it must be manually forced.

## Steps to reproduce the behavior
Creation of the bucket while setting the region (provider is Scaleway):
```
mc config host add scfr https://s3.fr-par.scw.cloud
[...]
mc mb scfr/gbe --region fr-par
Bucket created successfully `scfr/gbe`.
```

Normal upload works without needing to force the region:
```
mc cp test-minio.txt scfr/gbe
test-minio.txt:      12 B / 12 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 50 B/s 0s
```

Above, an example (without debug for readability) that the upload goes through. The initial Authorization value is however wrong but gets correctly changed by fr-par, allowing the upload to be completed.

With mirror, the initial Authorization is incorrect but the workflow is stopped unless I manually force it.

```
mc --debug mirror ./ scfr/gbe
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> PUT /gbe/ HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200523T133010Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Sat, 23 May 2020 13:30:10 GMT
X-Amz-Id-2: tx6478b307d7644c7597336-005ec92562
X-Amz-Request-Id: tx6478b307d7644c7597336-005ec92562

11c
<?xml version='1.0' encoding='UTF-8'?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'</Message><Region>fr-par</Region><RequestId>tx6478b307d7644c7597336-005ec92562</RequestId></Error>
0

mc: <DEBUG> Response Time:  276.928608ms

mc: <ERROR> Unable to create bucket at `scfr/gbe`. The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'
 (0) client-s3.go:1221 cmd.(*S3Client).MakeBucket(..)
 Release-Tag:RELEASE.2020-05-16T01-44-37Z | Commit:3b479cf92ed6 | Host:sonatal | OS:linux | Arch:amd64 | Lang:go1.13.10 | Mem:2.4 MB/72 MB | Heap:2.4 MB/66 MB.
```

By forcing the region, the uploads are completed:
```
mc --debug mirror --region fr-par ./ scfr/gbe 
mc: <DEBUG> PUT /gbe/ HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Content-Length: 150
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: wJ63Q/OLhskc79HGR87UVw==
X-Amz-Content-Sha256: 2cb57fad7b7168921a4c94426cfcb9ee2953f126430595df844e22d50f029060
X-Amz-Date: 20200523T133028Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 409 Conflict
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Sat, 23 May 2020 13:30:29 GMT
X-Amz-Id-2: tx7d7dbd21cd9e49f5a452e-005ec92575
X-Amz-Request-Id: tx7d7dbd21cd9e49f5a452e-005ec92575

114
<?xml version='1.0' encoding='UTF-8'?>
<Error><Code>BucketAlreadyOwnedByYou</Code><Message>Your previous request to create the named bucket succeeded and you already own it.</Message><RequestId>tx7d7dbd21cd9e49f5a452e-005ec92575</RequestId><BucketName>gbe</BucketName></Error>
0

mc: <DEBUG> Response Time:  223.013066ms

 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> GET /gbe/?location= HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200523T133029Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Sat, 23 May 2020 13:30:29 GMT
X-Amz-Id-2: txb71d8abca0e84617bd2d0-005ec92575
X-Amz-Request-Id: txb71d8abca0e84617bd2d0-005ec92575

11c
<?xml version='1.0' encoding='UTF-8'?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'</Message><Region>fr-par</Region><RequestId>txb71d8abca0e84617bd2d0-005ec92575</RequestId></Error>
0

mc: <DEBUG> Response Time:  137.073196ms

 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> GET /gbe/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix= HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T133029Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 661
Content-Type: application/xml
Date: Sat, 23 May 2020 13:30:29 GMT
X-Amz-Id-2: txe8dbb518e1874006aed7d-005ec92575
X-Amz-Request-Id: txe8dbb518e1874006aed7d-005ec92575

mc: <DEBUG> Response Time:  121.490914ms

...cw/glacier1.txt:  119 B / 119 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 316 B/smc: <DEBUG> PUT /gbe/glacier1.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Content-Length: 14
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Type: text/plain
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200523T133029Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Sat, 23 May 2020 13:30:29 GMT
Etag: "9e7d870bb30f48ee4ff97ddb7fa183c4"
Last-Modified: Sat, 23 May 2020 13:30:29 GMT
X-Amz-Id-2: tx9f681aef42084abaaa70d-005ec92575
X-Amz-Request-Id: tx9f681aef42084abaaa70d-005ec92575
X-Amz-Version-Id: 1590240629461199

mc: <DEBUG> Response Time:  138.289494ms
[...]
```

## mc --version
```
mc --version
mc version RELEASE.2020-05-16T01-44-37Z
```

## System information
Linux Mint 18, 64 bits

**Comment by harshavardhana** [comment]
You lack GetBucketLocation permissions otherwise fetching region is always automatic..

**Comment by gbe** [comment]
Is this something I misconfigured or is it an incomplete response from server side that mc expects?

**Comment by harshavardhana** [comment]
> Is this something I misconfigured or is it an incomplete response from server side that mc expects?

We expect GetBucketLocation AWS S3 API to return the right region for the bucket, if it is not returned we assume its us-east-1 @gbe

**Comment by gbe** [comment]
Ok... but my understanding is that the location is not checked by mc when doing a mirror.
As shown above, the very first http request done by mc when doing a mirror is a PUT.
Whereas when doing a cp, the first request is a GET /gbe/?location=, followed by PUT.

And the server replies to the PUT anyway when mirroring. It says what the correct region is but it's not taken into account by mc which stops the execution.

Could this lack of GET ?location= as first request when mirroring be key to this issue ?

Thank you

**Comment by harshavardhana** [comment]
> Ok... but my understanding is that the location is not checked by mc when doing a mirror.
> As shown above, the very first http request done by mc when doing a mirror is a PUT.
> Whereas when doing a cp, the first request is a GET /gbe/?location=, followed by PUT.
> 
> And the server replies to the PUT anyway when mirroring. It says what the correct region is but it's not taken into account by mc which stops the execution.
> 
> Could this lack of GET ?location= as first request when mirroring be key to this issue ?
> 
> Thank you

@gbe we do check that automatically in `mc` if you specify the --region then we don't

**Comment by gbe** [comment]
I'm not sure I follow you because this it not what I experience.

If I do not specify --region, it is NOT checked automatically by mc when mirroring:
```
mc --debug mirror ./ scfr/gbe
mc: <DEBUG> PUT /gbe/ HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200523T191437Z
Accept-Encoding: gzip
```
No --region, no location check.

**Comment by harshavardhana** [comment]
@gbe it doesn't do location lookup for destination because the destination is where it writes for writes you need specify the --region of what you want. 

If the source is object storage as well then region is looked up automatically,  the destination cannot be looked up without having first the bucket there in the first place we do that automatically if you pick a sub-directory which indicates that bucket already exists if it doesn't we attempt to create it if you didn't specify the region we auto choose us-east-1 as per AWS S3 spec. 

So you need to specify the region during create phase on the destination as expected. There is no way to lookup region without having a bucket already in place at the destination.

**Comment by gbe** [comment]
Except mc should already know what the region is as it was set up when creating the bucket. It's in my first comment above but let me summarize for clarity my full scenario:

```
$ mc mb scfr/debug --region fr-par
Bucket created successfully `scfr/debug`.
$ mc --debug mirror ./ scfr/debug
mc: <DEBUG> PUT /debug/ HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200523T194132Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Sat, 23 May 2020 19:41:32 GMT
X-Amz-Id-2: tx1d236cfc47754d95842ed-005ec97c6c
X-Amz-Request-Id: tx1d236cfc47754d95842ed-005ec97c6c

11c
<?xml version='1.0' encoding='UTF-8'?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'</Message><Region>fr-par</Region><RequestId>tx1d236cfc47754d95842ed-005ec97c6c</RequestId></Error>
0

mc: <DEBUG> Response Time:  198.074655ms

mc: <ERROR> Unable to create bucket at `scfr/debug`. The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'
 (0) client-s3.go:1221 cmd.(*S3Client).MakeBucket(..)
 Release-Tag:RELEASE.2020-05-16T01-44-37Z | Commit:3b479cf92ed6 | Host:sonatal | OS:linux | Arch:amd64 | Lang:go1.13.10 | Mem:2.0 MB/72 MB | Heap:2.0 MB/66 MB.
```

In my opinion, mc should not go in fatal error mode because of malformed authorization header because of the region as mc could already know it from handling the bucket creation.
Moreover, I don't understand why "mirror" would crash and not "cp" for example. But maybe there are some concepts with mirroring that I'm missing.

I attempted what you suggested, to mirror and add a subfolder as target. And indeed, no need to specify the region in that case. First request is this time a GET ?location= but region still is by default us-east-1. But mc recovers and mirrors.
```
mc --debug mirror ./ scfr/debug/test/
mc: <DEBUG> GET /debug/?location= HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200523T194421Z
Accept-Encoding: gzip
```

Honestly, for me it's still a blur:
1/ why mc cannot make the assumption that fr-par is the right region from http request number 1 as the bucket was setup with that setting.
Because of this lack of info, there are some unnecessary http requests in my opinion.

2/ and if it's not enough, why in mirror mode it cannot recover while the bucket actually exists and the server replies with the correct region (same way that mc recovers with cp and mv).
I understand that there is a need for assumptions when the bucket does not exist but this is not what I am reporting. mc can know the region as the bucket was created by it (should be added as region assumption number 1) and, if for some reason this assumption would no longer be correct, the server also replies with what the correct region is. With these 2 combined, there would be potentially less http requests and more importantly a continued execution rather than a fatal error.

All in all, you are right to set this issue as priority low.

I hope I made myself understandable and I thank you for your time.

**Comment by harshavardhana** [comment]
We don't remember those states we cannot remember your buckets on mc and what they map to. That is not the intention of mc.

**Comment by harshavardhana** [comment]
I don't think there is anything actionable here on our end. 

- GetBucketLocation should work properly if you wish to not provide a region and it should match the region you are mirroring to. If it cannot be matched it will fail.

- If the bucket is new and it needs to be created you need to specify the right region. If that is not provided also it would fail.

mc also retries the request if we see Authorization malformed error the error response should have the region XML field set but not during the PUT call which we can indeed fix.

But AFAICS the lack of GetBucketLocation not working is the original issue for you, that either is for your credentials or somehow the implementation is wrong on scaleway.

**Comment by harshavardhana** [comment]
> $ mc mb scfr/debug --region fr-par
> Bucket created successfully `scfr/debug`.
> $ mc --debug mirror ./ scfr/debug
> mc: <DEBUG> PUT /debug/ HTTP/1.1
> Host: s3.fr-par.scw.cloud
> User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
> Content-Length: 0
> Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> X-Amz-Date: 20200523T194132Z
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 400 Bad Request
> Transfer-Encoding: chunked
> Content-Type: application/xml
> Date: Sat, 23 May 2020 19:41:32 GMT
> X-Amz-Id-2: tx1d236cfc47754d95842ed-005ec97c6c
> X-Amz-Request-Id: tx1d236cfc47754d95842ed-005ec97c6c
> 
> 11c
> <?xml version='1.0' encoding='UTF-8'?>
> <Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'</Message><Region>fr-par</Region><RequestId>tx1d236cfc47754d95842ed-005ec97c6c</RequestId></Error>
> 0

Now closing looking at this - this request should have been retried automatically there is something missing in `scaleway` which failed this request, I will check and get back.
