### ISSUE TITLE
Add host in doesn't work correctly with `$` character

### ISSUE THREAD

**Issue by nimamahmoudi** [minio/mc#3231]
## Expected behavior
After entering the below command:
```
mc config host add myserver ACCESS_KEY SECRET_KEY(containing $)
---> Added myserver successfully.
```
I would expect to see the same ACCESS_KEY and SECRET_KEY in config.json

## Actual behavior
The characters `$CwQ4747@` become `@` in config.json (only on linux, windows works fine).

## Steps to reproduce the behavior
```
mc config host add test test test$CwQ4747@
```

## mc --version
- mc version RELEASE.2020-05-16T01-44-37Z

## System information
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by harshavardhana** [comment]
Just add quotes around the string, it is your shell which evaluates this value. This is common in bash to quote such characters.

**Comment by nimamahmoudi** [comment]
@harshavardhana that works but the issue is that `mc` successfully adds the server, but then no commands work afterwards (I don't know why it is different from other commands). The password was automatically generated, so I didn't check the characters and ended up searching and upgrading/downgrading the client for half an hour until I checked the config.json and found out the issue.

**Comment by harshavardhana** [comment]
> @harshavardhana that works but the issue is that `mc` successfully adds the server, but then no commands work afterwards (I don't know why it is different from other commands). The password was automatically generated, so I didn't check the characters and ended up searching and upgrading/downgrading the client for half an hour until I checked the config.json and found out the issue.

There is nothing we can do about it @nimamahmoudi bash escapes before `mc` can know what was passed rather than passing you can type your password 

```
~ mc config host add test http://localhost:9000
Enter Access Key: 
```

**Comment by nimamahmoudi** [comment]
@harshavardhana I totally understand, what I meant was that `mc config host add` should have also failed as a way to convey the issue with the secret key. Thanks for your reply.
