### ISSUE TITLE
mc mirror unable to copy bucket policies when copying all buckets

### ISSUE THREAD

**Issue by dmayle** [minio/mc#3235]
## Expected behavior
mc mirror should copy policies from each bucket

## Actual behavior
Whenver the source is all buckets in S3, the mirror command bails out while getting bucket policies, rather than handling policies per-bucket.  Call stack:
https://github.com/minio/mc/blob/master/cmd/mirror-main.go#L838
https://github.com/minio/mc/blob/master/cmd/mirror-main.go#L691
https://github.com/minio/mc/blob/master/cmd/client-s3.go#L1232

## Steps to reproduce the behavior
mc mirror --preserve <S3_SOURCE> <FILE_TARGET>

## mc --version
mc version RELEASE.2020-05-05T06-03-47Z

## System information
Kubernetes 1.16.4 using official minio/mc images.

**Comment by harshavardhana** [comment]
We need permission to make certain calls to ensure that we can get the policies from your source to copy to the destination. 

Without those permissions we cannot copy them, please share all the debugging details rather than pointing source files. Such as `mc --debug` output which will help us articulate the issue better.

**Comment by dmayle** [comment]
Certainly, here is the debug logs.  It's a brand new, empty installation:
```
/ # mc mirror --remove -a --overwrite --debug source /backup
mc: <DEBUG> GET / HTTP/1.1
Host: airflow-logs.cluster.ecedge.net
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-05T06:03:47Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20200526/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200526T195421Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 442
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 26 May 2020 19:54:21 GMT
Server: MinIO/RELEASE.2020-05-01T22-19-14Z
Vary: Origin
X-Amz-Bucket-Region: eu-west-3
X-Amz-Request-Id: 1612AC1D9908AB29
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  358.977839ms

 0 B / ? mc: <ERROR> Unable to copy bucket policies to `/backup`. Bucket name cannot be empty.
 (0) client-s3.go:1218 cmd.(*S3Client).GetAccessRules(..)
 Release-Tag:RELEASE.2020-05-05T06-03-47Z | Commit:b99c31336633 | Host:airflow-logs-mirror-7c5495df86-zt986 | OS:linux | Arch:amd64 | Lang:go1.13.10 | Mem:3.9 MB/72 MB | Heap:3.9 MB/66 MB
 0 B / ? mc: <DEBUG> GET / HTTP/1.1
Host: airflow-logs.cluster.ecedge.net
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-05T06:03:47Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20200526/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200526T195421Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 442
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 26 May 2020 19:54:21 GMT
Server: MinIO/RELEASE.2020-05-01T22-19-14Z
Vary: Origin
X-Amz-Bucket-Region: eu-west-3
X-Amz-Request-Id: 1612AC1D9D1E0198
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  30.458402ms

mc: <DEBUG> GET /bar/?location= HTTP/1.1
Host: airflow-logs.cluster.ecedge.net
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-05T06:03:47Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20200526/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200526T195421Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 137
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 26 May 2020 19:54:21 GMT
Server: MinIO/RELEASE.2020-05-01T22-19-14Z
Vary: Origin
X-Amz-Bucket-Region: eu-west-3
X-Amz-Request-Id: 1612AC1D9EFBC79C
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  4.521455ms

mc: <DEBUG> GET /bar/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&metadata=true&prefix= HTTP/1.1
Host: airflow-logs.cluster.ecedge.net
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-05T06:03:47Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20200526/eu-west-3/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200526T195421Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 675
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 26 May 2020 19:54:21 GMT
Server: MinIO/RELEASE.2020-05-01T22-19-14Z
Vary: Origin
X-Amz-Bucket-Region: eu-west-3
X-Amz-Request-Id: 1612AC1D9F4C5BAD
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  17.745657ms

mc: <DEBUG> GET /foo/?location= HTTP/1.1
Host: airflow-logs.cluster.ecedge.net
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-05T06:03:47Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20200526/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200526T195421Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 137
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 26 May 2020 19:54:21 GMT
Server: MinIO/RELEASE.2020-05-01T22-19-14Z
Vary: Origin
X-Amz-Bucket-Region: eu-west-3
X-Amz-Request-Id: 1612AC1DA074A987
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  5.668927ms

mc: <DEBUG> GET /foo/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&metadata=true&prefix= HTTP/1.1
Host: airflow-logs.cluster.ecedge.net
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-05T06:03:47Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20200526/eu-west-3/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200526T195421Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 681
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 26 May 2020 19:54:21 GMT
Server: MinIO/RELEASE.2020-05-01T22-19-14Z
Vary: Origin
X-Amz-Bucket-Region: eu-west-3
X-Amz-Request-Id: 1612AC1DA0D2F0EB
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  17.483825ms

 0 B / ?  0s/ # 
```

**Comment by ebozduman** [comment]
Hi @dmayle,

Could you tell me what was your `source` in your example?
```
mc mirror --remove -a --overwrite --debug source /backup
```
When I tried to reproduce the issue, I used my minio server. Created bunch of buckets, and used server <alias> as my source file. However, I did not see the error message `"Unable to copy bucket policies to '/backup'. Bucket name cannot be empty."`.
So, I need those missing information in the reproduction steps. Please let me know if there is any missing information that might be helpful during reproduction efforts.

**Comment by ebozduman** [comment]
Here is the issue:

Before mirroring bucket policies, `GetAccessRules()` function is called to check if a bucket name is provided or not. If a bucket name is specified, we error out, but keep going with mirroring. So, in your example, your source location is the server alias name, `source` with no bucket name specified. Hence the error message:

`"<ERROR> Unable to copy bucket policies to '<destination>'. Bucket name cannot be empty.`

Result: While the buckets and objects are mirrored correctly, bucket policies are not.

**Comment by dmayle** [comment]
@ebozduman I am using an environemt variable:
```
penguin:~/mirror$ env | grep MC_
MC_HOST_source=https://<ID>:<KEY>@airflow-logs.cluster.ecedge.net
```

> Result: While the buckets and objects are mirrored correctly, bucket policies are not.

I think that's an accurate description of the bug.  If I were instead to use `mc ls` to get the list of buckets, and then mirror each bucket in a separate command, the bucket policies would be copied.  When copying all buckets, however, mc mirror is unable to copy the bucket policies.

**Comment by ebozduman** [comment]
@dmayle,

In `"Steps to reproduce the behavior"` section, you entered:

`mc mirror --preserve <S3_SOURCE> <FILE_TARGET>`

and in your debug example, in coincide with the above information, the command is:

`/ # mc mirror --remove -a --overwrite --debug source /backup`

So, it is in between s3 source/alias, `"source"`, and file target, `"/backup"`, in the local file system.

To have bucket policies copied over, the mirroring should be happening between s3 buckets, i.e s3 to s3. We don't even call `copyBucketPolicies` function in s3 to file system mirroring.

So, I believe there is a discrepancy in the issue report somehow.You may want to look into it.
I guess this is the reason I could not reproduce it.
Please re-run the `mc mirror` command without using any variables, and without relying on environment variables, if possible. That is going to help us more easily diagnose the problem, if any.

Assuming your destination is a single s3 bucket, then you still won't see bucket policies copied over. S3 multi-bucket to to s3 single bucket, it doesn't make sense. 

Final point: 
We don't believe there is any unexpected behavior in mirroring as far as bucket policies. That's why I marked the issue as `"working as intended"`

Please let us know if you still see the issue. If you cannot reproduce the issue, then please close it.

**Comment by ebozduman** [comment]
Closing the issue.

**Comment by ebozduman** [comment]
Closing this issue since there is no answer for 12 days.
Please reopen it with your clear reproduction steps, if you think this is still a reproducible problem.
