### ISSUE TITLE
Invalid query parameters when using `mc mirror` with Google Cloud

### ISSUE THREAD

**Issue by novakg** [minio/mc#3237]
## Expected behavior

`mc mirror` reports no error when using it to sync files from a Google Cloud bucket to a local directory.

## Actual behavior

The following errors occur when I try to sync from a GCP bucket:

```
mc: <DEBUG> GET /?object-lock= HTTP/1.1
Host: <removed>.storage.googleapis.com
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200528/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200528T033928Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 177
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private, max-age=0
Content-Type: application/xml; charset=UTF-8
Date: Thu, 28 May 2020 03:39:28 GMT
Expires: Thu, 28 May 2020 03:39:28 GMT
Server: UploadServer
X-Guploader-Uploadid: AAANsUl0cuhxe3jjh0raKQusX8FZ7H8FSVtY6qpQcG0Rw3LUFfXMUbBRA3zcF1dEhJcykJEfyIubqmvmyLvGYWxx5A

<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message><Details>Invalid query parameter(s): [object-lock]</Details></Error>mc: <DEBUG> Response Time:  111.443263ms

mc: <DEBUG> GET /?policy= HTTP/1.1
Host: <removed>.storage.googleapis.com
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200528/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200528T033928Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 172
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private, max-age=0
Content-Type: application/xml; charset=UTF-8
Date: Thu, 28 May 2020 03:39:28 GMT
Expires: Thu, 28 May 2020 03:39:28 GMT
Server: UploadServer
X-Guploader-Uploadid: AAANsUkn3jIkhUB_TiGLsD5-jD_hOqbuYIRm3aDDseOzO_qQ2Ldq2TH-RZ-bl9TkYeZ-fzj9UhS-v0RP4htkJ_w4pw

<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message><Details>Invalid query parameter(s): [policy]</Details></Error>mc: <DEBUG> Response Time:  89.870126ms```
```

Please note that these errors don't block the sync process: files are being downloaded correctly from the bucket.

## Steps to reproduce the behavior

 1. Create an S3 bucket in Google Cloud using "fine-grained access control" (I did not test it with bucket level access control.)
 2. Mirror that bucket to a local directory like:
```console
mc mirror gcs/<my_bucket>/some/path /my/local/path --json --debug --overwrite
```

## mc --version

```
mc version RELEASE.2020-05-16T01-44-37Z
```

**Comment by harshavardhana** [comment]
@novakg not all features are available on GCS which `mc` - you may use `mc cp` as alternative.

**Comment by harshavardhana** [comment]
Alternatively you should ask GCS for more compliance with AWS S3 APIs

**Comment by novakg** [comment]
:) I agree. 

Or maybe the code could be updated to not try to use functions that are not supported by Google when the url starts with "gcs/" ;)

**Comment by ebozduman** [comment]
@novakg,

With the merge of another PR#3274, `mc mirror` command's behavior changed and the offending error messages in the `--debug`  output cleared up.

"Stop calling unsupported apis in GCS" is a possible solution as you suggest. However, it makes us vulnerable to possible GCS changes in the future, like adding/removing support for some apis. 
We don't want to revisit our code from time to time to adapt possible compatibility changes of GCS in the future. We assume all is in and decide if supported/implemented or not depending on the returned value.

Please try your `mc mirror` command again in your setup with the mc executable either built from the top of the mc master branch or downloaded from MinIO download page.
If you are satisfied with what you see, please Close the issue. Otherwise, let us know what problem(s) you see.

**Comment by harshavardhana** [comment]
> :) I agree.
> 

Thanks 

> Or maybe the code could be updated to not try to use functions that are not supported by Google when the url starts with "gcs/" ;) (in case you'd like to develop a robust code...)

That's not called robust, its called hacks and we do have them for GCS for a while and we break them once a while because we don't really test with GCS and it's not a priority.

**Comment by novakg** [comment]
> @novakg,
> 
> With the merge of another PR#3274, `mc mirror` command's behavior changed and the offending error messages in the `--debug` output cleared up.
> 
> "Stop calling unsupported apis in GCS" is a possible solution as you suggest. However, it makes us vulnerable to possible GCS changes in the future, like adding/removing support for some apis.
> We don't want to revisit our code from time to time to adapt possible compatibility changes of GCS in the future. We assume all is in and decide if supported/implemented or not depending on the returned value.
> 
> Please try your `mc mirror` command again in your setup with the mc executable either built from the top of the mc master branch or downloaded from MinIO download page.
> If you are satisfied with what you see, please Close the issue. Otherwise, let us know what problem(s) you see.

Hi @ebozduman ,
Thanks for your comment. I've tested GCS access with different versions of mc and I experienced the followings:

- RELEASE.2020-05-16T01-44-37Z pulls files fine from GCS bucket, but shows the errors I've opened this ticket for
- RELEASE.2020-06-20T00-18-43Z (the current "release" version) seems to get into an infinite loop when trying to read from GCS bucket. I can see the following GCS response in the logs:
```<?xml version='1.0' encoding='UTF-8'?><Error><Code>NotImplemented</Code><Message>A header or query you provided requested a function that is not implemented.</Message><Details>GET ?list-type is not implemented for buckets</Details></Error>mc: <DEBUG> Response Time:  94.02724ms```
- The latest version built from git head (like `GO111MODULE=on go get github.com/minio/mc`) works fine with GCS, I can not see the above-mentioned GCS specific errors with this version.

**Comment by ebozduman** [comment]
Thank you @novakg for testing and verifying the issue is not reproducible anymore.
So, the fix will be available in the next official mc release.
Could you close the issue now?
