### ISSUE TITLE
Unable to connect to minio gateway s3 etcd backend after upgrade

### ISSUE THREAD

**Issue by jdheyburn** [minio/mc#3242]
## Expected behavior
mc commands should work, i.e.:

```
mc admin policy list myminio
mc admin user list myminio
```

## Actual behavior
The error below is produced

```
$ ./mc admin user list nonprodcs --debug
mc: <DEBUG> GET /minio/admin/v3/list-users HTTP/1.1
Host: MINIO_ENDPOINT:443
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-05-28T23:43:36Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200603//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200603T164529Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 278
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Wed, 03 Jun 2020 16:45:29 GMT
Server: MinIO/RELEASE.2020-06-01T17-28-03Z
Vary: Origin
X-Amz-Request-Id: 16151673BC18C2F5
X-Xss-Protection: 1; mode=block

{"Code":"SignatureDoesNotMatch","Message":"The request signature we calculated does not match the signature you provided. Check your key and signing method.","Resource":"/minio/admin/v3/list-users","RequestId":"16151673BC18C2F5","HostId":"c49b8f1a-90eb-4c80-98e8-bee205e8036b"}
mc: <DEBUG> Response Time:  65.523358ms

mc: <ERROR> Cannot list user. The request signature we calculated does not match the signature you provided. Check your key and signing method.
 (1) admin-user-list.go:73 cmd.mainAdminUserList(..) Tags: [nonprodcs]
 (0) admin-user-list.go:73 cmd.mainAdminUserList(..)
 Release-Tag:RELEASE.2020-05-28T23-43-36Z | Commit:2403e7a7441b | Host:ip-10-193-15-230.eu-west-1.compute.internal | OS:linux | Arch:amd64 | Lang:go1.13.10 | Mem:3.4 MB/72 MB | Heap:3.4 MB/66 MB.
```

This was experienced on both of the following minio versions:
RELEASE.2020-06-01T17-28-03Z
RELEASE.2020-05-29T14-08-49Z

## Steps to reproduce the behavior
1. Spin up minio version with one of the above
2. Add gateway s3 minio config
3. Try one of the commands above

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2020-05-28T23-43-36Z

## System information

I appreciate the version of mc here is older than the minio version released, however we perform several tests to ensure that functionality is the same when upgrading minio (mc is our means of interfacing minio) - so we are blocked on upgrading minio if we don't have a compatible mc released alongside. What is the scheduled release pattern for mc?

**Comment by jdheyburn** [comment]
Thanks. I cleared the `~/.mc` directory and added back the configs for 2 instances. One worked fine but the other complains of incorrect keys. 

We use etcd for backend, and as I understand it minio uses access and secret keys for encryption in etcd. Here is when I add the instance using the correct access and secret keys.

```
./mc config host add nonprodcs https://MINIO_ENDPOINT:443 ACCESS_KEY SECRET_KEY
mc: Configuration written to `/home/centos/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/home/centos/.mc/share`.
mc: Initialized share uploads `/home/centos/.mc/share/uploads.json` file.
mc: Initialized share downloads `/home/centos/.mc/share/downloads.json` file.
Added `nonprodcs` successfully.
```

This indicates that the access and secret keys match what is on the etcd backend. I am even able to log into minio using the access key and secret, so the issue is not there. However when I try to list out the users or policies, that is where I get the same issue as above.

For reference, I am not able to add the instance in mc if the secret key is wrong.

```
mc: <ERROR> Unable to initialize new config from the provided credentials. The request signature we calculated does not match the signature you provided. Check your key and signing method.
 (5) config-host-add.go:289 cmd.mainConfigHostAdd(..) Tags: [nonprodcs, https://MINIO_ENDPOINT:443, ACCESS_KEY, INCORRECT_SECRET_KEY]
 (4) config-host-add.go:230 cmd.BuildS3Config(..) Tags: [https://MINIO_ENDPOINT:443, ACCESS_KEY, INCORRECT_SECRET_KEY, , auto]
 (3) config-host-add.go:203 cmd.probeS3Signature(..) Tags: [s3v4, s3v2]
 (2) config-host-add.go:195 cmd.probeS3Signature.func1(..) Tags: [s3v2]
 (1) client-s3.go:1375 cmd.(*S3Client).Stat(..) Tags: [probe-bucket-sign-nswgtlh2bpgy]
 (0) client-s3.go:1871 cmd.(*S3Client).bucketStat(..)
 Release-Tag:RELEASE.2020-05-28T23-43-36Z | Commit:2403e7a7441b | Host:REDACTED | OS:linux | Arch:amd64 | Lang:go1.13.10 | Mem:3.5 MB/72 MB | Heap:3.5 MB/66 MB.
```

**Comment by jdheyburn** [comment]
I've updated the title to something more appropriate. The stack I am running is:

- minio gateway s3: upgrading from `RELEASE.2020-04-15T19-42-18Z` to `RELEASE.2020-06-01T17-28-03Z`
- etcd backend v3.3.9
- minio mc client: upgrading from `RELEASE.2020-04-19T19-17-53Z` to `RELEASE.2020-05-28T23-43-36Z`

The only resolution we have found is to wipe the etcd backend and add back users and policies. Having to do this on each upgrade is not ideal. The access and secrets keys are correct, since we can log into the minio server with them - it is the `mc` client that is having issues.

I'm happy to provide further assistance if you need it @harshavardhana. Thanks for your time.

**Comment by kannappanr** [comment]
@jdheyburn I have tried the exact versions that you just described, though the etcd version is `3.2.17` and was unable to reproduce the issue.

**Comment by harshavardhana** [comment]
@kannappanr may be @jdheyburn didn't consistently use the same credentials with different versions and didn't follow the credential migration process.

https://github.com/minio/minio/tree/master/docs/config#rotating-encryption-with-new-credentials

**Comment by jdheyburn** [comment]
- It's my understanding that when we use `mc config host add`, that if the credentials are incorrect, we are notified by the error message:

```
mc: <ERROR> Unable to initialize new config from the provided credentials. The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

- I do not see this when I add the minio instance to the config 
- instead I get `Added 'NAME' successfully.`. 
- Based on this we can determine that the credentials *are* correct. 
- The same credentials can even be used to log into the web browser of minio successfully.

It is then when I try to interface with minio via a command such as `./mc admin policy add NAME fixbug fixbug.json` that I get the error described above.

Our credentials are fixed in AWS SSM Parameter store - they would not, and have not changed.

I'm getting the same issue even with latest minio version `RELEASE.2020-06-12T00-06-19Z`.

**Comment by jdheyburn** [comment]
I just created a new set of access and secret keys for the AWS user minio is using, and migrated using the credential migration process @harshavardhana described. 

The exact same issue occcurs:

- I was able to add to `mc config` using the new credentials fine after boot.
- I got the same error when trying to `mc admin` minio.

```
mc: <ERROR> Cannot add new user. The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Comment by jdheyburn** [comment]
Hi team,

I got the same error again with these versions:

- `minio:RELEASE.2020-07-02T00-15-09Z`
- `mc:RELEASE.2020-06-26T19-56-55Z`

I'm happy to take a look and debug the code for this. Can you advise on which components of both minio and mc I should be looking at? Notably as well I wish to recreate the API queries that mc is producing. If there is some guidance on that it would be helpful.

**Comment by jdheyburn** [comment]
Hi folks - we found the issue to be with the AWS ALB that fronted the service. We fixed by converting to NLB. Thanks for the help on this one. 👍
