### ISSUE TITLE
Failed to parse server response: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by wyx666518** [minio/mc#3245]
## Expected behavior
MinIO Bucket Notification For Elasticsearch
One step by step in https://docs.min.io/docs/minio-bucket-notification-guide.html#Elasticsearch

## Actual behavior
Failed to parse server response: invalid character '<' looking for beginning of value

## Steps to reproduce the behavior
1、docker pull minio/mc
2、docker run -it --entrypoint=/bin/sh minio/mc
3、mc config host add minio http://192.168.3.208:9000 root password
4、step 3 is return Added `minio` successfully.
5、mc admin config set minio notify_elasticsearch:1 queue_limit="0"  url="http://192.168.3.208:9200" format="namespace" index="minio_events" queue_dir=""
6、mc: <ERROR> Cannot set 'notify_elasticsearch:1 queue_limit=0 url=http://192.168.3.208:9200 format=namespace index=minio_events queue_dir=' to server. Failed to parse server response: invalid character '<' looking for beginning of value.

Thank you!

## mc --version
RELEASE.2020-05-28T23-43-36Z

## System information
ubuntu 18.04LTS x64

**Comment by harshavardhana** [comment]
@wyx666518 your server is too old here and mc is rather new.

Can you paste your server version?

**Comment by wyx666518** [comment]
> @wyx666518 your server is too old here and mc is rather new.
> 
> Can you paste your server version?

OK!
My server verison is RELEASE.2020-06-03T22-13-49Z.

**Comment by wyx666518** [comment]
> > > @wyx666518 your server is too old here and mc is rather new.
> > > Can you paste your server version?
> > 
> > 
> > OK!
> > My server verison is RELEASE.2020-06-03T22-13-49Z.
> 
> can you do `--debug` along with `mc admin config set` ?

mc: <DEBUG> PUT /minio/admin/v3/set-config-kv HTTP/1.1
Host: 192.168.3.208:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-05-28T23:43:36Z
Content-Length: 170
Authorization: AWS4-HMAC-SHA256 Credential=root/20200604//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e7ee8730d8ba8dbc1184f402bf91b96c70f0d005c46aa597cebf53d7d774cbb8
X-Amz-Date: 20200604T150408Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 405 
Content-Length: 685
Allow: OPTIONS, GET, HEAD, POST
Content-Language: en
Content-Type: text/html;charset=utf-8
Date: Thu, 04 Jun 2020 15:04:08 GMT

<!doctype html><html lang="en"><head><title>HTTP Status 405 – Method Not Allowed</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 405 – Method Not Allowed</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource.</p><hr class="line" /><h3>Apache Tomcat/8.5.51</h3></body></html>mc: <DEBUG> Response Time:  3.342611ms

mc: <ERROR> Cannot set 'notify_elasticsearch:1 queue_limit=0 url=http://192.168.3.208:9200 format=namespace index=minio_events queue_dir=' to server. Failed to parse server response: invalid character '<' looking for beginning of value.
 (0) admin-config-set.go:122 cmd.mainAdminConfigSet(..)
 Release-Tag:RELEASE.2020-05-28T23-43-36Z | Commit:2403e7a7441b | Host:d130299c97db | OS:linux | Arch:amd64 | Lang:go1.13.10 | Mem:68 MB/141 MB | Heap:68 MB/134 MB.

**Comment by harshavardhana** [comment]
> <!doctype html><title>HTTP Status 405 – Method Not Allowed</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style>
> 
> # HTTP Status 405 – Method N

This looks like you have some random proxy in between @wyx666518

**Comment by wyx666518** [comment]
> This looks like you have some random proxy in between @wyx666518

But I did not set up a random proxy.
Have any other ways to try again?

**Comment by klauspost** [comment]
MinIO will not return 405 and HTML, so it looks like you are hitting something between `mc` and the MinIO server.

**Comment by klauspost** [comment]
Looks like an Apache Tomcat server maybe?

**Comment by wyx666518** [comment]
> MinIO will not return 405 and HTML, so it looks like you are hitting something between `mc` and the MinIO server.

I'm reinstall Virtual machine system, es , minio and mc.
Now, it return 400.
mc: <DEBUG> PUT /minio/admin/v3/set-config-kv HTTP/1.1
Host: 192.168.5.110:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-05-28T23:43:36Z
Content-Length: 170
Authorization: AWS4-HMAC-SHA256 Credential=root/20200605//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: 1ea76c443aa24262a72993f3daad68fbe93ff821f90f4679ee48aae2d70406d1
X-Amz-Date: 20200605T115823Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 209
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Fri, 05 Jun 2020 11:58:29 GMT
Server: MinIO/RELEASE.2020-06-01T17-28-03Z
Vary: Origin
X-Amz-Request-Id: 1615A3F22E4D7ED0
X-Xss-Protection: 1; mode=block

{"Code":"XMinioAdminConfigBadJSON","Message":"not connected to target server/service","Resource":"/minio/admin/v3/set-config-kv","RequestId":"1615A3F22E4D7ED0","HostId":"0ab406e4-da62-4793-934b-2828abbe7863"}
mc: <DEBUG> Response Time:  5.204569331s

**Comment by wyx666518** [comment]
> MinIO will not return 405 and HTML, so it looks like you are hitting something between `mc` and the MinIO server.

Now I'm resinstall system, es, minio and mc.
mc admin config set myminio notify_elasticsearch:1 queue_limit="0" url="http://192.168.5.108:9200" format="namespace" index="minio_events" queue_dir=""
It return 400.

mc: <DEBUG> PUT /minio/admin/v3/set-config-kv HTTP/1.1
Host: 192.168.5.110:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-05-28T23:43:36Z
Content-Length: 170
Authorization: AWS4-HMAC-SHA256 Credential=root/20200605//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: d26e89d8c01a3a7bd1798d4271f8812bd5feb910dbb936ec40cb21d9fbd005e5
X-Amz-Date: 20200605T122002Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 209
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Fri, 05 Jun 2020 12:20:07 GMT
Server: MinIO/RELEASE.2020-06-01T17-28-03Z
Vary: Origin
X-Amz-Request-Id: 1615A520754BE5C1
X-Xss-Protection: 1; mode=block

{"Code":"XMinioAdminConfigBadJSON","Message":"not connected to target server/service","Resource":"/minio/admin/v3/set-config-kv","RequestId":"1615A520754BE5C1","HostId":"0ab406e4-da62-4793-934b-2828abbe7863"}
mc: <DEBUG> Response Time:  5.293167208s

mc: <ERROR> Cannot set 'notify_elasticsearch:1 queue_limit=0 url=http://192.168.5.108:9200 format=namespace index=minio_events queue_dir=' to server: not connected to target server/service
 (0) admin-config-set.go:122 cmd.mainAdminConfigSet(..)
 Release-Tag:RELEASE.2020-05-28T23-43-36Z | Commit:2403e7a7441b | Host:0453a152502d | OS:linux | Arch:amd64 | Lang:go1.13.10 | Mem:68 MB/141 MB | Heap:68 MB/134 MB.
~/.mc # ping 192.168.5.108
PING 192.168.5.108 (192.168.5.108): 56 data bytes
64 bytes from 192.168.5.108: seq=0 ttl=63 time=1.326 ms
64 bytes from 192.168.5.108: seq=1 ttl=63 time=1.060 ms
64 bytes from 192.168.5.108: seq=2 ttl=63 time=0.407 ms
64 bytes from 192.168.5.108: seq=3 ttl=63 time=0.400 ms
64 bytes from 192.168.5.108: seq=4 ttl=63 time=0.625 ms

**Comment by ebozduman** [comment]
@wyx666518,

I could not reproduce the issue with the mc built from the top of the branch and with `mc.RELEASE.2020-05-28T23-43-36Z` you've seen the issue with.

Here is what I've seen when I tried the same command you've used:
```
$ mc admin config set myminio notify_elasticsearch:1 queue_limit="0" url="http://localhost:9200"
format="namespace" index="minio_events" queue_dir=""
Setting new key has been successful.
Please restart your server with `mc admin service restart myminio`.
```

```
$ ~/Downloads/mc.RELEASE.2020-05-28T23-43-36Z admin config set myminio notify_elasticsearch:1
queue_limit="0" url="http://localhost:9200" format="namespace" index="minio_events" queue_dir="" 
Setting new key has been successful.
Please restart your server with `mc admin service restart myminio`.

```

Could you please try it, if you can, on a new system or VM ?
I don't think it is going to help no matter how many times minio and mc are re-installed on the same Linux, MacOS or Windows system.

**Comment by ebozduman** [comment]
Marking this issue as "working as intended".

**Comment by Shw2333** [comment]
mc: <ERROR> Cannot get service status: invalid character '<' looking for beginning of value
