### ISSUE TITLE
The MC client successfully created the user, but it did not take effect immediately

### ISSUE THREAD

**Issue by sanmusen404** [minio/mc#3248]
## Expected behavior
The MC client successfully created the user, and the newly created user can be used immediately
## Actual behavior
My minio log shows'Added user `xxxxx` successfully.'. In fact, no user was created. After some time, the user was actually created. This happens only to some users.
## Steps to reproduce the behavior
PHP executes a shell script remotely
The following is the main content of the script
1. mc admin user add minio/ ${access_key} ${secret_key} >> /root/minio/minio.log  
2. mc mb minio/${bucket} >> /root/minio/minio.log  
3. policy_content=`cat /root/minio/policy.json`  
4. printf "${policy_content}" ${bucket} > /root/minio/user_policy/${bucket}.json  
5. mc admin policy add minio ${bucket} /root/minio/user_policy/${bucket}.json >> /root/minio/minio.log  
6. mc admin policy set minio ${bucket} user=${access_key} >> /root/minio/minio.log  
7. mc event add minio/${bucket} arn:minio:sqs::1:redis >> /root/minio/minio.log  

The bucket can be created every time
## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2020-04-04T05-28-55Z
## System information
CentOS Linux release 7.6.1810

**Comment by harshavardhana** [comment]
Please upgrade both mc and server to latest and let us know.

**Comment by sanmusen404** [comment]
I upgraded minio server to the latest version and solved the problem
