### ISSUE TITLE
'MinIO Client Complete Guide' title incorrect

### ISSUE THREAD

**Issue by Mattacks** [minio/mc#3253]
## Expected behavior
Title should describe the contents

## Actual behavior
Title says it is the 'complete guide', but it is far from complete

**Comment by bensodenkamp** [comment]
@Mattacks, could you propose a spec which when met would indicate completeness? Is there some specific aspect of the function of the mc command which is not covered in the guide?

**Comment by i0x71** [comment]
mc mirror --active-active would be one of the commands not covered in the guide but exists on the binary.
