### ISSUE TITLE
Feature request, cashed pipes from storage to host

### ISSUE THREAD

**Issue by itzsimpl** [minio/mc#3254]
I see this an entirely client side featrure, useful for any s3 client. 

My use case is to use minio as a data storage. I would use parts of this data (not entire buckets, or subfolders, only some files from those and not always the same ones). The software that I use is limited to POSIX io. The `mc` client supports piping data from host to minio storage, but not in the other direction.

My feature request would be to provide piping from storage as well, that is in the opposite direction as `mc pipe`. If you add to that a possibility to provide a caching drive, where data would be stored locally and retrieved in case of reuse pending it has not changed in minio storage, that would be a killer feature for my use case. I have looked at ways of mounting minio as a posix drive, but all solutions seem to be either overkill or have unsatisfactory performance. Another option would be to have `mc mirror`, perform two ways selective synching in background, but that's for another feature request.

**Comment by vadmeste** [comment]
@itzsimpl maybe you need to explore MinIO S3 gateway with caching enabled, it looks close to what you want.

**Comment by klauspost** [comment]
@itzsimpl `mc cat` is the opposite direction of `mc pipe`.
