### ISSUE TITLE
aws behavior cp --metadata-directive

### ISSUE THREAD

**Issue by OscarHanzely** [minio/mc#3260]
## Expected behavior
It seems that there is missing functionality in minio client cp command. It is expected that we can copy a file from bucket to bucket, and remove the user metadata. In aws-cli it is done via `--metadata-directive` which can specify if the base metadata should be copied over or replaced.

## Actual behavior
Seems that the mc client can only add metadata and always copies the existing ones, which prevents it from removing unwanted metadata.

## Steps to reproduce the behavior
copy without attr flag or with attr flag and single attribute still carries everything that a file has in source location.

## mc --version
- mc version RELEASE.2020-06-16T19-24-41Z

## System information
minio/mc docker image

**Comment by ebozduman** [comment]
This issue is on hold waiting for the requirements to be clarified and specified by  the development team.
