### ISSUE TITLE
mc diff lists files that aren't actually different

### ISSUE THREAD

**Issue by BLuFeNiX** [minio/mc#3261]
## Expected behavior

`mc diff` reports no changes when directories/buckets are identical

## Actual behavior

`mc diff` shows incorrect results, and those results change depending on which level of the directory structure is being compared. 

## Steps to reproduce the behavior
1. `mc mirror -a --overwrite --remove /data/local/ mys3/remote/`
2. `mc diff /data/local/ mys3/remote/`

Here are some more specific examples:

One of my top level directories, when compared right after `mirror`ing
```
# ./mc diff "/data/Foo/" "wasabi/my.redacted.domain/Foo/"
< /data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Some Place 2018/IMG_20180418_221741.jpg
< /data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Some Place 2018/IMG_20180418_221829.jpg
< /data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Some Place 2018/IMG_20180418_221845.jpg
```
The `--json` output looks like this, for all entries:
```
{
 "status": "success",
 "first": "/data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Some Place 2018/IMG_20180418_221741.jpg",
 "second": "",
 "diff": 4
}
```
swapping the remote and local paths, ie: `./mc diff "wasabi/my.redacted.domain/Foo/" "/data/Foo/"` produces similar output (diff code swapped)
```
{
 "status": "success",
 "first": "",
 "second": "/data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Some Place 2018/IMG_20180418_221741.jpg",
 "diff": 5
}
```
Furthermore, if I compare just the directory that appears different in the command above...
```
# ./mc diff --json "/data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Some Place 2018/" "wasabi/my.redacted.domain/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Some Place 2018/"
```
I get no output, meaning no differences are detected.

And if I walk back up the hierarchy, folder by folder, I eventually get an entirely different result:
```
# ./mc diff "/data/Foo/Bar/" "wasabi/my.redacted.domain/Foo/Bar/"
< /data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20171221_165344.jpg
< /data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20171221_165354.jpg
< /data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20171221_165756.jpg
< /data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20171221_165811.jpg
< /data/Foo/Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20171221_165932.jpg
```

I have edited the paths for privacy, but left the format of the names the same, to illustrate any naming patterns that may affect this issue. Every file that I have manually checked does indeed exist in both locations, so it does not appear to be a bug with the mirror operation itself.

## mc --version
```
mc version RELEASE.2020-06-16T19-24-41Z
```

## System information
Ubuntu 20.04 in a docker container

**Comment by BLuFeNiX** [comment]
Additionally, running `mc mirror` against these directories causes the same, unchanged data to be uploaded every time, even though it is identical. I assume this is due to `mirror` using the same logic that `diff` uses.

**Comment by harshavardhana** [comment]
@BLuFeNiX can you do this? 

```
~ mc ls -r --json /data/Foo | jq -r .key > local_files
~ mc ls -r --json "wasabi/my.redacted.domain/Foo/" | jq -r .key > remote_files
~ diff -pruN local_files remote_files
```

**Comment by BLuFeNiX** [comment]
@harshavardhana 
```
# diff -pruN local_files remote_files
--- local_files 2020-06-18 06:21:33.949409192 +0000
+++ remote_files        2020-06-18 06:22:21.557900178 +0000
@@ -1998,15 +1998,6 @@ Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/S
 Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221634.jpg
 Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221648.jpg
 Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221731.jpg
-Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221741.jpg
-Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221829.jpg
-Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221845.jpg
-Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221904.jpg
-Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221932.jpg
-Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221956.jpg
-Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_222007.jpg
-Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_222019.jpg
-Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/something-2018-04-16-002249.jpg
 Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Elsewhere 2017/IMG_20180105_235801.jpg
 Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Elsewhere 2017/IMG_20180105_235804.jpg
 Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Elsewhere 2017/IMG_20180105_235807.jpg
```
The results appear to match.

**Comment by harshavardhana** [comment]
> # diff -pruN local_files remote_files
> --- local_files 2020-06-18 06:21:33.949409192 +0000
> +++ remote_files        2020-06-18 06:22:21.557900178 +0000
> @@ -1998,15 +1998,6 @@ Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/S
>  Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221634.jpg
>  Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221648.jpg
>  Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221731.jpg
> -Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221741.jpg
> -Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221829.jpg
> -Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221845.jpg
> -Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221904.jpg
> -Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221932.jpg
> -Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_221956.jpg
> -Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_222007.jpg
> -Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/IMG_20180418_222019.jpg
> -Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/PLACE 2017/something-2018-04-16-002249.jpg
>  Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Elsewhere 2017/IMG_20180105_235801.jpg
>  Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Elsewhere 2017/IMG_20180105_235804.jpg
>  Bar/UPPERCASE_NAME_WITH_UNDERSCORES/SORTED/Elsewhere 2017/IMG_20180105_235807.jpg

They don't that's the point @BLuFeNiX `diff` shouldn't match. the problem here is that wasabi is sending in the wrong lexical order.

**Comment by harshavardhana** [comment]
Similar test on my end 

```
~ mc ls -r --json /usr/sbin | jq -r .key > local_files
~ mc mirror /usr/sbin play/testbucket/sbin/
~ mc ls -r --json play/testbucket/sbin | jq -r .key > remote_files
~ diff -pruN local_files remote_files | wc -l
0
```

Either you have new content that got added to /data/Foo or `mc mirror` didn't upload all content or wasabi is incorrectly returning incomplete entries.

**Comment by BLuFeNiX** [comment]
Sorry, I mean "match" as the incorrect behavior is still observed. So you think this is a bug to report to wasabi? Is there a way to work around this by sorting the results that are being received from wasabi? I wonder if the lexical order is a requirement in the S3 specification.

**Comment by harshavardhana** [comment]
> Sorry, I mean "match" as the incorrect behavior is still observed. So you think this is a bug to report to wasabi? Is there a way to work around this by sorting the results that are being received from wasabi? I wonder if the lexical order is a requirement in the S3 specification.

lexical order is a requirement for S3 spec we cannot sort it partially locally, the entire index on the namespace is sorted. To verify that mc mirror is working correctly try running `minio` locally 

```
~ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio server /tmp/data
~ mc mirror /data/Foo myminio/testbucket/Foo
```

**Comment by BLuFeNiX** [comment]
@harshavardhana thanks for the quick action on this. I will have to try the server component later, as I do not have it installed at this time.

In the mean time I will report this to Wasabi.

**Comment by klauspost** [comment]
Closing...

**Comment by BLuFeNiX** [comment]
Quick update, in case anyone else experiences similar problems. After much effort, I was able to prove that the original problem that I reported here was due to a bug in the Wasabi S3 service. I reported the bug with a reproducible test case, so the ball is in their court now.
