### ISSUE TITLE
 Unexpected client 'admin' API version found 'v3', expected 'v2', please downgrade the client to older releases.

### ISSUE THREAD

**Issue by pandyamarut** [minio/mc#3262]
## Expected behavior
One should be able to manage the server.

## Actual behavior
mc: <ERROR> Cannot get service status. Unexpected client 'admin' API version found 'v3', expected 'v2', please downgrade the client to older releases.

## Steps to reproduce the behavior
./mc admin info <aliasName>

## mc --version
mc version RELEASE.2020-05-28T23-43-36Z

## System information
Ubuntu 18.04 LTS, 12GB Ram.

**Comment by harshavardhana** [comment]
> mc: Cannot get service status. Unexpected client 'admin' API version found 'v3', expected 'v2', please downgrade the client to older releases.

As shown in the error message @pandyamarut you need to either use an older `mc` or upgrade your server.

**Comment by gitbizzi** [comment]
How can I get an older mc?

**Comment by klauspost** [comment]
https://dl.min.io/client/mc/release/linux-amd64/archive/
