### ISSUE TITLE
Failed to copy object to filesystem if the remote object has attributes

### ISSUE THREAD

**Issue by eddienko** [minio/mc#3263]
## Expected behavior
 
```
mc cp myminio/CHECKSUM .
```

should work and should not try to preserve attributes since the `-a` flag is not used.

## Actual behavior

If the remote file has attributes, `mc` still tries to preserve them in the local disk causing an error unless you are root.

## Steps to reproduce the behavior

Copy a file with attributes to local disk:

```
$ mc stat  myminio/CHECKSUM
Name      : CHECKSUM
Date      : 2020-06-10 16:07:36 BST
Size      : 51 KiB
ETag      : 17eecfcd0739538d2812da06cd435b40
Type      : file
Metadata  :
  X-Amz-Meta-Mc-Attrs: atime:1591801490/ctime:1591801617/gid:3000311/mode:33261/mtime:1591801617/uid:2018633400
  Content-Type       : application/octet-stream
```

and

```
$ mc cp --debug  myminio/CHECKSUM .
mc: <ERROR> Failed to copy `https://xxx/CHECKSUM`. chown CHECKSUM.part.minio: operation not permitted
 (4) cp-main.go:562 cmd.doCopySession(..) Tags: [https://xxx/CHECKSUM]
 (3) common-methods.go:525 cmd.uploadSourceToTargetURL(..) Tags: [https://xxx/CHECKSUM]
 (2) common-methods.go:317 cmd.putTargetStream(..) Tags: [, CHECKSUM]
 (1) client-fs.go:300 cmd.(*fsClient).put(..) Tags: [CHECKSUM]
 (0) client-fs.go:248 cmd.preserveAttributes(..)
 Commit:975423abe2e1 | Release-Tag:DEVELOPMENT.2020-06-19T07-21-40Z | Host:io.local | OS:darwin | Arch:amd64 | Lang:go1.14.3 | Mem:3.3 MB/74 MB | Heap:3.3 MB/66 MB
```

## mc --version
- mc version DEVELOPMENT.2020-06-19T07-21-40Z

## System information
- OS:darwin | Arch:amd64 | Lang:go1.14.3

**Comment by ebozduman** [comment]
@eddienko,

I see some discrepancies in your report:

It looks like your alias is `myminio`. This means you defined it to point to your minio server URL and also the credentials (AccessKey & SecretKey)

Your `mc stat myminio/CHECKSUM` command output shows CHECKSUM as a file. 

But then where is your bucket?
```
$ mc mb myminio/mybucket
Bucket created successfully `myminio/mybucket`.
$ mc stat myminio/mybucket
Name      : mybucket/
Date      : 1969-12-31 16:00:00 PST 
Size      : 0 B    
Type      : folder 
```

You cannot have an object/file stored without having a minio bucket defined.
If `CHECKSUM` is a bucket, then the type field would show `folder`.

So, I need you to answer the following questions:
1. What is `myminio`?
2. What is `CHECKSUM`?
3. Where is your bucket?

**Comment by eddienko** [comment]
Hi,

Sorry I edited out the information that I thought it was not relevant. This is the actual real command:

```
$ mc stat myminio/incoming/stpt/20190520_4t1_T_tc_day20_Lungs_100x15um_set2/CHECKSUM
Name      : CHECKSUM
Date      : 2020-06-11 16:03:45 BST
Size      : 3.4 MiB
ETag      : 7f04a452fb0e99c1e7c04d4776df3d5f
Type      : file
Metadata  :
  Content-Type       : application/octet-stream
  X-Amz-Meta-Mc-Attrs: atime:1591873281/ctime:1591886786/gid:0/gname:root/mode:33261/mtime:1591886786/uid:2018633400
```

So in this  bucket is incoming:

```
$ mc ls myminio
[2020-06-20 06:50:38 BST]      0B incoming/
[2020-06-20 06:50:38 BST]      0B shared/
```

**Comment by ebozduman** [comment]
@eddienko 

Thank you for the info.

Please also add information about how you created the CHECKSUM file in your bucket `incoming`.
Maybe like:
```
mc cp -a /stpt/20190520_4t1_T_tc_day20_Lungs_100x15um_set2/CHECKSUM myminio/incoming/stpt/20190520_4t1_T_tc_day20_Lungs_100x15um_set2/
```

**Comment by ebozduman** [comment]
I also need to know who owns the file and who is trying to copy the file. `operation not permitted` means you don't have the right privileges.

Please also notice your first ` mc stat` output shows the owner id as `3000311` (where are the uname and gname info? They are missing in the output), but the one you sent lately shows user as `root`. 

But without any other input, I am pretty sure, what your issue is;
Your user who wants to copy the file doesn't have the permission to change the ownership (right to run chown) because the file belongs to someone else. You need to either adjust the permissions on your original file, CHECKSUM, in your local file system before it was copied over to your object store, or you need to switch your identity and become the owner before running the command:

```
`mc cp myminio/incoming/stpt/20190520_4t1_T_tc_day20_Lungs_100x15um_set2/CHECKSUM .
```

Your issue will be resolved.

**Comment by eddienko** [comment]
Hi,

Thanks for looking into this. I am going to try to describe the use case as best as I can. I just run through this again, so the file names and uid and gid may change. 

The `incoming` bucket is a users shared folder where for instance one user can copy data to it from their local storage and another user can copy that data from it to their local storage in another computer.

Now the first user, the user that copies the data into the bucket, is copying the data that is originally stored in windows shared disk mounted in Linux. So the first user has the following files:

```
# ls -la /data/some_dir
total 64
drwxr-xr-x 2 2018633400 3000311 49152 Jul  1 15:25 .
drwxr-xr-x 2 2018633400 3000311 16384 Jul  1 15:36 ..
-rwxr-xr-x 1 2018633400 3000311     0 Jul  1 14:36 OK_TO_COPY
-rwxr-xr-x 1 2018633400 3000311     0 Jul  1 14:36 PROCESSING
-rwxr-xr-x 1 2018633400 3000311     0 Jul  1 15:25 SUCCESSFULLY_COPIED
```

This user as uid=2018633400, gid=3000311

and does

```
mc -c -r -a -q /data/some_dir  myminio/incoming/some_dir
```

So now:

```
mc stat myminio/incoming/some_dir/OK_TO_COPY
Name      : OK_TO_COPY
Date      : 2020-07-01 16:22:42 BST
Size      : 0 B
ETag      : d41d8cd98f00b204e9800998ecf8427e
Type      : file
Metadata  :
  X-Amz-Meta-Mc-Attrs: atime:1593614176/ctime:1593614176/gid:3000311/mode:33261/mtime:1593614176/uid:2018633400
  Content-Type       : application/octet-stream
```

All good as expected here.

Now the problem is when a second user wants to download that data to their own different local filesystem. This second user is working on his desktop and he has uid=501, gid=501. There is no user with the  uid and gid of the first user on this second user computer. Now I would still expect that using

```
mc cp myminio/incoming/some_dir/OK_TO_COPY .
```

would work as I am not using the `-a` flag. However it does not work because as you say the uid and gid of the remote file do not match the ones from the second user in their own local computer. But how can this second user copy the file otherwise? He cannot ask the admin of his desktop computer to create another account for him with the uid and gid of that particular file -- in particular because many other users can upload data to the incoming bucket and they will all have different uid and gid.

I guess the workaround is for the first user to not use `-a` when copying from local storage to remote, but still, I would think that this use case should work without this workaround so the system can keep the stats of who uploaded the data (maybe I do not understand how buckets work!).

Thanks!

**Comment by ebozduman** [comment]
@eddienko 

We discussed your proposed fix and agreed to implement it. 
PR minio/mc#3285 is already merged.

**Comment by eddienko** [comment]
Tested with the version in master and working as intended so closing.

Thanks!
