### ISSUE TITLE
Don't copy subfolders itself when recursive

### ISSUE THREAD

**Issue by ekbfh** [minio/mc#3267]
Hello!
Recently i notice that my data was copy some wrong way: 

## Steps to reproduce

I have test folders and a file at the end:
`test-q-old/1/2/3/4/5/file1`

I took some old release:
`./mc.RELEASE.2019-10-02T19-41-02Z -q cp -r test-q-old/* cdn/$S3_BUCKET/  `
and it was copied normal: 
``test-q-old/1/2/3/4/5/file1` -> `cdn/test-ek/1/2/3/4/5/file1``

But latest release was: 
```
/bin/mc --version 
mc version RELEASE.2020-06-20T00-18-43Z

/bin/mc -q cp -r test-q-old/* cdn/$S3_BUCKET/                                                      
`test-q-old/1/2/3/4/5/file1` -> `cdn/test-ek/2/3/4/5/file1`

we miss the `1` folder itself
```

Maybe it helps: s3 server is minio too, version `2019-10-12T01:39:57Z`

**Comment by harshavardhana** [comment]
Moved this to relevant repo

**Comment by harshavardhana** [comment]
> `./mc.RELEASE.2019-10-02T19-41-02Z -q cp -r test-q-old/* cdn/$S3_BUCKET/ `

Passing args in disparate positions do not work - this is a limit of Go flag parser. You should either use all flags together in the beginning of the CLI or at the end - following variants will correctly work as expected all the time

> `./mc.RELEASE.2019-10-02T19-41-02Z cp -r -q test-q-old/* cdn/$S3_BUCKET/ `

or 

 > `./mc.RELEASE.2019-10-02T19-41-02Z cp test-q-old/* cdn/$S3_BUCKET/ ` -r -q

**Comment by ekbfh** [comment]
Thanks for a quick answer!

I retry with your version, but still the same result:
```
new:
/bin/mc  cp  test-q-old/* cdn/$S3_BUCKET/ -r -q
`test-q-old/1/2/3/4/5/file1` -> `cdn/test-ek/2/3/4/5/file1`

old:
./mc.RELEASE.2019-10-02T19-41-02Z cp test-q-old/* cdn/$S3_BUCKET/ -r -q 
`test-q-old/1/2/3/4/5/file1` -> `cdn/test-ek/1/2/3/4/5/file1`
```

**Comment by harshavardhana** [comment]
> new:
> /bin/mc  cp  test-q-old/* cdn/$S3_BUCKET/ -r -q
> `test-q-old/1/2/3/4/5/file1` -> `cdn/test-ek/2/3/4/5/file1`

This is wrong @ekbfh needs to be fixed.

**Comment by poornas** [comment]
@ekbfh, I was not able to find any bug with the mc implementation - interestingly, this is linux behavior which is why you do not see the 1/ parent folder as part of the prefix on the destination.
I recreated a local dir hierarchy like you described - the ls with a wildcard * after the directory name omits the first level folder 1/ - you should be omitting the wildcard to get the entire prefix copied to destination.
```
➜  tree -a test-q-old
test-q-old
└── 1
    └── 2
        └── 3
            └── 4
                └── 5
                    └── file1
                        └── test.json

6 directories, 1 file
➜ ls test-q-old/
1
➜ ls test-q-old/*
2
```

**Comment by ekbfh** [comment]
@poornas why it worked another way in old releases?

**Comment by poornas** [comment]
> @poornas why it worked another way in old releases?

Looked closer, it is a regression. I will send a PR after finalizing a fix.

**Comment by ekbfh** [comment]
Also i notised a strange thing:
I can't rewrite an existing folder with the same command: `/tmp/mc cp $SOURCE $DEST -q -r` on certain releases.

`mc.RELEASE.2019-10-02T19-41-02Z` -- works well, but i get an error on all releases after this, for example `mc.RELEASE.2020-02-20T23-49-54Z` and all later.

 `mc: <ERROR> Target `cdn/docs/master/` is not a folder. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.`

But If i delete the `master` folder, it copy as normal on all releases.

I found that it calls in `typeC` function, but don't find why it is a error, cause `mc ls --type json ` tells that `/master` has type `folder`

I think it is kind similar and it may be connected to issue.
Thanks!
