### ISSUE TITLE
Feature request: Read AWS config files for credentials

### ISSUE THREAD

**Issue by dariosusman** [minio/mc#3275]
Feature request:

Would it be possible to have the client read the config and credentials files in ~/.aws when an AWS S3 bucket is used instead of having to configure them in?

Thank you!

Cheers,
Dario Susman

**Comment by kannappanr** [comment]
@dariosusman We use an alias to talk to an S3 Object store. So, you will have to enter all the information except for access and secret key. So, I don't think it will be useful to add something like this. Also, if someone wants to access a public AWS bucket, they will be forced to remove the credentials set in `~/.aws` folder

**Comment by harshavardhana** [comment]
> Feature request:
> 
> Would it be possible to have the client read the config and credentials files in ~/.aws when an AWS S3 bucket is used instead of having to configure them in?
> 
> Thank you!
> 
> Cheers,
> Dario Susman

mc has its own config, we cannot use AWS credentials file.
