### ISSUE TITLE
mc mirror watch doesnt detect folders moved

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3292]
It doesnt looks like mc mirror -a -w --remove picks up folders being moved into a watch folder
Eg:

mc -q -a -w --remove watched dest
mv someFolder watched

Copying and creating new files works properly.
removal of the newly added folder is detected.

Is this a limitation of watching for changes ?

Thanks
Running mc version RELEASE.2020-06-26T19-56-55Z

**Comment by harshavardhana** [comment]
watch relies on filesystem notify events, it is a limitation of FS notify which cannot detect directory changes or renames @i0x71

**Comment by i0x71** [comment]
Thanks, is there a periodic full rescan or would i have to manually restart mc to rescan for changes periodically ?

**Comment by harshavardhana** [comment]
> Thanks, is there a periodic full rescan or would i have to manually restart mc to rescan for changes periodically ?

We cannot do that @i0x71 that makes it very complicated design. we have to start re-watching them etc. You have to live with this limitation for now. 

Rescanning, again and again, is not a scalable solution.

**Comment by i0x71** [comment]
Ok, perhaps we should mention this rather important shortcoming somewhere, in the help menu or docs.

**Comment by harshavardhana** [comment]
> Ok, perhaps we should mention this rather important shortcoming somewhere, in the help menu or docs.

This is listed as a shortcoming in FSNotify we say that --watch is dependent on FSNotify the behavior is different for example on windows FSNotify supports directory renames.
