### ISSUE TITLE
mc active-active docs

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3297]
Hi,
mc version RELEASE.2020-07-11T05-18-52Z
mentions  --active-active                    enable active-active multi-site setup
Where could i find more information on what this does, i dont see any mention of this command in the official mc guide and couldnt find anything on google.

Thanks

**Comment by joshmoore** [comment]
I find myself also looking for this information.

**Comment by Sug2077** [comment]
https://blog.min.io/active-active-replication/
https://docs.min.io/docs/minio-bucket-replication-guide.html
