### ISSUE TITLE
mc admin heal fails with panic: runtime error: integer divide by zero after removing permissions from one of the server's disk

### ISSUE THREAD

**Issue by uucico** [minio/mc#3300]
## Expected behavior
Show "UI" and color codes for objects when trying to real.

## Actual behavior
When running "mc admin heal -r xxxxx/" output is:

panic: runtime error: integer divide by zero
 
goroutine 1 [running]:
github.com/minio/mc/cmd.hri.getReplicatedFileHCCChange.func1(0x0, 0x0, 0x0, 0x4118ea, 0x90)
        github.com/minio/mc@/cmd/admin-heal-result-item.go:58 +0xc1
github.com/minio/mc/cmd.hri.getReplicatedFileHCCChange(0xc0004fdc88, 0xc0004301e0, 0x0, 0xc00031e0d8, 0xed6a17ee1, 0x0, 0x3c040c78)
        github.com/minio/mc@/cmd/admin-heal-result-item.go:66 +0x67
github.com/minio/mc/cmd.(*uiData).updateStats(0xc0004fe450, 0x1, 0xc0002f85c8, 0x8, 0x0, 0x0, 0x0, 0x0, 0xc0002f85d0, 0xb, ...)
        github.com/minio/mc@/cmd/admin-heal-ui.go:130 +0x123
github.com/minio/mc/cmd.(*uiData).UpdateDisplay(0xc0004fe450, 0xc0004fdff8, 0xc0002f64c0, 0x7ffc64676815)
       github.com/minio/mc@/cmd/admin-heal-ui.go:378 +0x109
github.com/minio/mc/cmd.(*uiData).DisplayAndFollowHealStatus(0xc0004fe450, 0x7ffc64676815, 0x7, 0xc0002f85c0, 0x7, 0x0, 0x0, 0x37e84ee3, 0xed6a17ee1, 0x0, ...)
        github.com/minio/mc@/cmd/admin-heal-ui.go:425 +0x1fa
github.com/minio/mc/cmd.mainAdminHeal(0xc00034cd00, 0xc0002f4390, 0x9)
        github.com/minio/mc@/cmd/admin-heal.go:271 +0x10ce
github.com/minio/cli.HandleAction(0xcfc8e0, 0xe9d210, 0xc00034cd00, 0xc00025ac00, 0x0)
        github.com/minio/cli@v1.22.0/app.go:498 +0xc8
github.com/minio/cli.Command.Run(0xe40799, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe6ece2, 0x2f, 0x0, ...)
        github.com/minio/cli@v1.22.0/command.go:225 +0x991
github.com/minio/cli.(*App).RunAsSubcommand(0xc00034c680, 0xc00034c4e0, 0x0, 0x0)
        github.com/minio/cli@v1.22.0/app.go:387 +0x7fa
github.com/minio/cli.Command.startApp(0xe413b1, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe50e88, 0x14, 0x0, ...)
        github.com/minio/cli@v1.22.0/command.go:313 +0x809
github.com/minio/cli.Command.Run(0xe413b1, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe50e88, 0x14, 0x0, ...)
        github.com/minio/cli@v1.22.0/command.go:111 +0x127b
github.com/minio/cli.(*App).Run(0xc00034c1a0, 0xc0000f6000, 0x5, 0x5, 0x0, 0x0)
        github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
github.com/minio/mc/cmd.Main(0xc0000f6000, 0x5, 0x5)
        github.com/minio/mc@/cmd/main.go:119 +0x341
main.main()
        github.com/minio/mc@/main.go:34 +0x45

## Steps to reproduce the behavior
1. Running 4 node, 12 disk each (48 disks) objects with EC:5, "minio server http://minioc1n{1...4}:9000/data{1...12}/data", minio 2020-07-12T19:14:17Z
2. In one of the nodes, remote all permissions from one of the disks. i.e. "chmod a-rwx /data3/data"
3. See disk offline in the "mc admin info" command such as: 47 drives online, 1 drive offline
4. Try to run an mc admin heal, it will fail.

## mc --version
- mc version RELEASE.2020-07-11T05-18-52Z

## System information
As in step 1 above.

**Comment by uucico** [comment]
Error happens in mc after the following HTTP exchange:

```
POST /minio/admin/v3/heal/?clientToken=235692ae-d3b2-47e5-a39e-c7bc37b73566%400 HTTP/1.1
Host: minio-c1n1:9001
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-07-11T05:18:52Z
Transfer-Encoding: chunked
Authorization: AWS4-HMAC-SHA256 Credential=z2Zaw05lErvIwFJwsv1IEwRO4kQVzUFD/20200715//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=379a450f7db2303b303bbc8f37875c5d682084f2c83851393482cb32084a78a2
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200715T225345Z

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 77391
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Server: MinIO/RELEASE.2020-07-12T19-14-17Z
Vary: Origin
X-Amz-Request-Id: 16220EEC349392E0
X-Xss-Protection: 1; mode=block
Date: Wed, 15 Jul 2020 22:53:45 GMT
```

- Attaching the response body. Please note that the setSize is zero, and this is causing the division by zero in line 58 (first item in stack).

- Not sure it his is a bug mc in or if the server is misbehaving. Also having other issues with disk healing.

[minio-heal-body.txt](https://github.com/minio/mc/files/4928808/minio-heal-body.txt)

**Comment by ebozduman** [comment]
@uucico,

I could not reproduce the problem. 

I created a setup similar to yours; 4 MinIO servers/nodes and 12 disks (directories in my local file system). Then removed the permissions on one of the disks/directories as you explained, confirmed the lost disk in the output of `mc admin heal <alias>`. However, I did not see any panic. Instead, mc displayed the following error message:
```
$ mc admin heal minio01/disk01 
mc: <ERROR> Unable to heal bucket `disk01`. We encountered an internal error, please try again.
```
while minio console was showing error message:
```
Error: corrupted backend format, please join https://slack.min.io for assistance
       4: cmd/api-errors.go:1926:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:1951:cmd.toAPIError()
       2: cmd/bucket-handlers.go:177:cmd.objectAPIHandlers.GetBucketLocationHandler()
       1: net/http/server.go:2012:http.HandlerFunc.ServeHTTP()
```

Please provide more details for us to be able to reproduce the issue.

**Comment by kannappanr** [comment]
@uucico Closing this issue. We will re-open the issue once you have information to reproduce the issue
