### ISSUE TITLE
mc with a custom config-dir does not seem to work

### ISSUE THREAD

**Issue by ricardogsilva** [minio/mc#3307]
I am trying to write some integration tests and for those I'm spinning up an ephemeral docker container with minio server running on port 9200. The plan is to run all my tests against this server. I don't want to mess up my main `mc` config file so I've created `/tmp/mytest` dir and put a `config.json` file inside with the following contents:

```json
# cat /tmp/mytest/config.json 
{
    "version": "9",
    "hosts": {
        "pytest": {
            "url": "http://localhost:9200",
            "accessKey": "myuser",
            "secretKey": "mypassword",
            "api": "S3v4",
            "lookup": "auto"
        }
    }
}
```

The problem is that whenever I try to use this custom config with `mc` I get an error:

```
$ mc admin info pytest --config-dir /tmp/mytest --debug

mc: <ERROR> Unable to initialize admin connection. No valid configuration found for 'pytest' host alias
 (0) client-admin.go:145 cmd.newAdminClient(..)
 Release-Tag:RELEASE.2020-07-11T05-18-52Z | Commit:1513d76ca9d3 | Host:panthro | OS:linux | Arch:amd64 | Lang:go1.13.12 | Mem:1.7 MB/72 MB | Heap:1.7 MB/67 MB.
```

## Expected behavior

I expected `mc` to be able to connect to the minio server using my custom config dir

## Actual behavior

`mc` complains that it cannot find a configuration for my alias, even though I am supplying the correct one and the configuration file seems to be correct

## Steps to reproduce the behavior

-  Create some custom directory, for example `/tmp/mytest`
-  Recreate the same `config.json` as shown above and put it inside the custom directory
-  Launch `mc admin info --config-dir /tmp/mytest`

## mc --version
- (paste output of `mc --version`)
```
$ mc --version
mc version RELEASE.2020-07-11T05-18-52Z
```

## System information

My local machine is running a pretty vanilla ubuntu 20.04

**Comment by harshavardhana** [comment]
> ```
> mc version RELEASE.2020-07-11T05-18-52Z
> ```

@ricardogsilva this is fixed in the recent release RELEASE.2020-07-17T02-52-20Z fixed by #3302

**Comment by ricardogsilva** [comment]
wow, that was fast!

I'll test it out to see if it works then

Thanks a lot for the lightning respnse :smile_cat:

**Comment by ricardogsilva** [comment]
@harshavardhana please reopen this

Unfortunately even with the latest `mc` release I am getting the same error

```bash
$ mc --version
mc version RELEASE.2020-07-17T02-52-20Z
```

Created my custom `/tmp/mytest/config.json` with contents as shown in the issue description

Then, when running some `mc` command I get the error

```bash
$ mc admin info pytest --config-dir /tmp/mytest --debug
mc: <ERROR> Unable to initialize admin connection. No valid configuration found for 'pytest' host alias
 (0) client-admin.go:145 cmd.newAdminClient(..)
 Release-Tag:RELEASE.2020-07-17T02-52-20Z | Commit:f19a10dce2ab | Host:panthro | OS:linux | Arch:amd64 | Lang:go1.13.13 | Mem:2.3 MB/70 MB | Heap:2.3 MB/67 MB.
```

**Comment by harshavardhana** [comment]
> @harshavardhana please reopen this
> 
> Unfortunately even with the latest `mc` release I am getting the same error
> 
> ```bash
> $ mc --version
> mc version RELEASE.2020-07-17T02-52-20Z
> ```
> 
> Created my custom `/tmp/mytest/config.json` with contents as shown in the issue description
> 
> Then, when running some `mc` command I get the error
> 
> ```bash
> $ mc admin info pytest --config-dir /tmp/mytest --debug
> mc: <ERROR> Unable to initialize admin connection. No valid configuration found for 'pytest' host alias
>  (0) client-admin.go:145 cmd.newAdminClient(..)
>  Release-Tag:RELEASE.2020-07-17T02-52-20Z | Commit:f19a10dce2ab | Host:panthro | OS:linux | Arch:amd64 | Lang:go1.13.13 | Mem:2.3 MB/70 MB | Heap:2.3 MB/67 MB.
> ```

Pass config-dir in the beginning at mc --config-dir ?

**Comment by ricardogsilva** [comment]
> Pass config-dir in the beginning at mc --config-dir ?

yes, that works!

I was surprised with this behavior, since the `--debug` and `--json` global flags (which I've been using) can be passed at the end and they work. Perhaps this is a bug?

After reading the help I realize that indeed the recommended usage is to put global flags in the beginning, so yeah, I guess I should've RTFM a bit better :sweat_smile: 

Anyway, thanks for your help!

**Comment by harshavardhana** [comment]
> > Pass config-dir in the beginning at mc --config-dir ?
> 
> yes, that works!
> 
> I was surprised with this behavior, since the `--debug` and `--json` global flags (which I've been using) can be passed at the end and they work. Perhaps this is a bug?
> 
> After reading the help I realize that indeed the recommended usage is to put global flags in the beginning, so yeah, I guess I should've RTFM a bit better 😅
> 
> Anyway, thanks for your help!

Its a limitation of our CLI package not your understanding @ricardogsilva we will try to address the positional behavior in the future.
