### ISSUE TITLE
mc ilm files not being deleted

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3316]
Not sure if i have something setup incorrectly or not, but having added an expiry rule with 15 days, none of the files in the bucket after being deleted after the 15 days expiry set in my policy.

mc ilm list xx/xxxxxx
       ID       |     Prefix     |  Enabled   | Expiry |  Date/Days   |  Transition  |    Date/Days     |  Storage-Class   |       Tags       
----------------|----------------|------------|--------|--------------|--------------|------------------|------------------|------------------
 expire15       |                |    ✓       |  ✓     |              |     ✗        |                  |                  |                  
----------------|----------------|------------|--------|--------------|--------------|------------------|------------------|------------------

Is there a way to debug this from my end ?

Thanks

**Comment by vadmeste** [comment]
@i0x71, what's your MinIO server version ?

**Comment by i0x71** [comment]
Its running latest as of today, im about a week behind on the latest releases
   Version: 2020-07-22T00:26:33Z

**Comment by i0x71** [comment]
Not sure if its the latest version that fixed it, or me listing the contents, now an hour later when i list the contents the files are gone.
Was there a fix in the latest version ?

**Comment by vadmeste** [comment]
> Was there a fix in the latest version ?

Yes, there is a fix for lifecycle in FS mode (https://github.com/minio/minio/commit/44c8af66ad1dae2bdcd27771209cc83c3fce5065), we released it recently. Besides you sometimes need to wait some time until the lifecycle routine is triggered again.

**Comment by i0x71** [comment]
Got it, thanks!
