### ISSUE TITLE
Problems encountered configuring minio user policies

### ISSUE THREAD

**Issue by wwz801226** [minio/mc#3317]
My goal is to give a user configurable permissions to read, write, and list buckets and objects.
However, actions in S3 doesn't seem to be supported?

`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:ListObjects",
        "s3:ListBuckets"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::test/*"
      ],
      "Sid": ""
    }
  ]
}`

and then

`[root@cns-vs-d149 policy]# mc admin policy add zjm  test-readwrite test.json 
mc: <ERROR> Cannot add new policy: unsupported action 's3:ListObjects'.
[root@cns-vs-d149 policy]# vim test.json 
`

**Comment by harshavardhana** [comment]
> `{ "Version": "2012-10-17", "Statement": [ { "Action": [ "s3:PutObject", "s3:GetObject", "s3:ListObjects", "s3:ListBuckets" ], "Effect": "Allow", "Resource": [ "arn:aws:s3:::test/*" ], "Sid": "" } ] }`

s3:ListObjects --> s3:ListBucket

**Comment by wwz801226** [comment]
> > `{ "Version": "2012-10-17", "Statement": [ { "Action": [ "s3:PutObject", "s3:GetObject", "s3:ListObjects", "s3:ListBuckets" ], "Effect": "Allow", "Resource": [ "arn:aws:s3:::test/*" ], "Sid": "" } ] }`
> 
> s3:ListObjects --> s3:ListBucket
 
Wow!  You are great! It work

And then, where can I find this permission statement?

**Comment by harshavardhana** [comment]
> > > `{ "Version": "2012-10-17", "Statement": [ { "Action": [ "s3:PutObject", "s3:GetObject", "s3:ListObjects", "s3:ListBuckets" ], "Effect": "Allow", "Resource": [ "arn:aws:s3:::test/*" ], "Sid": "" } ] }`
> > 
> > 
> > s3:ListObjects --> s3:ListBucket
> 
> Wow! You are great! It work
> 
> And then, where can I find this permission statement?

https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html

> To use this operation in an AWS Identity and Access Management (IAM) policy, you must have permissions to perform the s3:ListBucket action. The bucket owner has this permission by default and can grant this permission to others. For more

**Comment by wwz801226** [comment]
Permissions work on the Web side, but errors are reported through the Java JDK

`io.minio.errors.ErrorResponseException: Access Denied.
	at io.minio.MinioClient.execute(MinioClient.java:1201) ~[minio-3.0.10.jar!/:3.0.10]
	at io.minio.MinioClient.updateRegionCache(MinioClient.java:1216) ~[minio-3.0.10.jar!/:3.0.10]
	at io.minio.MinioClient.getRegion(MinioClient.java:1262) ~[minio-3.0.10.jar!/:3.0.10]
	at io.minio.MinioClient.executePut(MinioClient.java:1390) ~[minio-3.0.10.jar!/:3.0.10]
	at io.minio.MinioClient.putObject(MinioClient.java:3688) ~[minio-3.0.10.jar!/:3.0.10]
	at io.minio.MinioClient.putObject(MinioClient.java:3728) ~[minio-3.0.10.jar!/:3.0.10]`

**Comment by harshavardhana** [comment]
> Permissions work on the Web side, but errors are reported through the Java JDK
> 
> `io.minio.errors.ErrorResponseException: Access Denied. at io.minio.MinioClient.execute(MinioClient.java:1201) ~[minio-3.0.10.jar!/:3.0.10] at io.minio.MinioClient.updateRegionCache(MinioClient.java:1216) ~[minio-3.0.10.jar!/:3.0.10] at io.minio.MinioClient.getRegion(MinioClient.java:1262) ~[minio-3.0.10.jar!/:3.0.10] at io.minio.MinioClient.executePut(MinioClient.java:1390) ~[minio-3.0.10.jar!/:3.0.10] at io.minio.MinioClient.putObject(MinioClient.java:3688) ~[minio-3.0.10.jar!/:3.0.10] at io.minio.MinioClient.putObject(MinioClient.java:3728) ~[minio-3.0.10.jar!/:3.0.10]`

minio-java needs more permissions @wwz801226 such as GetBucketLocation etc.

**Comment by wwz801226** [comment]
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:GetBucketLocation"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::mcp-bm/*",
        "arn:aws:s3:::mcp-cc/*",
        "arn:aws:s3:::mcp-ncb/*",
        "arn:aws:s3:::mcp-tcb/*"
      ],
      "Sid": ""
    }
  ]
}
`

add the  "GetBucketLocation" is ok

**Comment by harshavardhana** [comment]
Please join https://slack.min.io for more questions @wwz801226
