### ISSUE TITLE
Admin Info not showing correct stats and Remove Bucket questionably if it works

### ISSUE THREAD

**Issue by petersedivec** [minio/mc#3323]
## Expected behavior
When I use the `mc rb` command I expect the storage usage and bucket count to decrease by a corresponding amount.  

## Actual behavior
Nothing appears to have changed, see below output
```bash
[root@localhost tmp]# ./mc admin info minio
●  127.0.0.1:9000
   Uptime: 29 minutes 
   Version: 2020-06-22T03:12:50Z
   Network: 1/1 OK 

20 GiB Used, 7 Buckets, 45,698 Objects
[root@localhost tmp]# ./mc ls -r --json minio/202007 | awk '{ FS=","; print $4 }' | awk '{ FS=":"; n+=$2 } END{ print n }'
21358589283
```
Next, delete the bucket
```bash
[root@localhost tmp]# ./mc rb --force minio/rms-processed
Removed `minio/rms-processed` successfully.
[root@localhost tmp]# ./mc admin info minio
●  127.0.0.1:9000
   Uptime: 36 minutes 
   Version: 2020-06-22T03:12:50Z
   Network: 1/1 OK 

20 GiB Used, 7 Buckets, 45,737 Objects
[root@localhost tmp]# ./mc ls -r --json minio/202007 | awk '{ FS=","; print $4 }' | awk '{ FS=":"; n+=$2 } END{ print n }'
21359514231
```
When looking at the UI the bucket rms-processed has disappeared but the bucket count, objects, storage used doesn't appear to have dropped.  I don't know the exact counts but there were at least 100+ objects in the bucket I deleted and non trivial size.  Another discrepancy is that `mc admin info` shows 7 buckets but the UI only shows 2
![image](https://user-images.githubusercontent.com/6617012/88576447-53a02800-cffa-11ea-830d-78a45885aec0.png)

## Steps to reproduce the behavior
Try running `mc rb` command against a bucket and before/after running that command look at the UI and run `mc admin info` command

## mc --version
```
[root@localhost tmp]# ./mc --version
mc version RELEASE.2020-05-16T01-44-37Z
```

## System information
Centos7
minio/minio:RELEASE.2020-06-22T03-12-50Z

**Comment by harshavardhana** [comment]
> ```shell
>    Version: 2020-06-22T03:12:50Z
> ```

Please upgrade to latest @petersedivec

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/releases/tag/RELEASE.2020-07-24T22-43-05Z 

> Fixes a regression in bucket usage metrics to remove double counting, see #10126

**Comment by petersedivec** [comment]
Thanks for the quick response, we will be upgrading to the latest.  we've also been seeing stability issues and we haven't figured out why minio keeps failing with `non zero exit (137)` which we hadn't encountered prior to upgrading to the 2020-06-11 release.  Hopefully the stability issue we're seeing is resolved.

![image](https://user-images.githubusercontent.com/6617012/88615588-1a41d980-d047-11ea-9c36-bb665b18aae6.png)

**Comment by harshavardhana** [comment]
> Thanks for the quick response, we will be upgrading to the latest. we've also been seeing stability issues and we haven't figured out why minio keeps failing with `non zero exit (137)` which we hadn't encountered prior to upgrading to the 2020-06-11 release. Hopefully the stability issue we're seeing is resolved.
> 
> ![image](https://user-images.githubusercontent.com/6617012/88615588-1a41d980-d047-11ea-9c36-bb665b18aae6.png)

just exit code is not that useful, would be better to share any console logs that you see..

**Comment by petersedivec** [comment]
feel free to close this issue @harshavardhana

**Comment by petersedivec** [comment]
```
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error: github.com/minio/minio/cmd/http.(*Server).Start.func1(0x1fa72a0, 0xc00058e460, 0xc0001d7700)
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error:    github.com/minio/minio@/cmd/http/server.go:104 +0x2ab
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error: net/http.HandlerFunc.ServeHTTP(0xc0001da080, 0x1fa72a0, 0xc00058e460, 0xc0001d7700)
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error:    net/http/server.go:2007 +0x44
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error: net/http.serverHandler.ServeHTTP(0xc0000ad560, 0x1fa72a0, 0xc00058e460, 0xc0001d7700)
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error:    net/http/server.go:2802 +0xa4
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error: net/http.(*conn).serve(0xc0007c2b40, 0x1faede0, 0xc003eb0bc0)
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error:    net/http/server.go:1890 +0x875
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error: created by net/http.(*Server).Serve
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error:    net/http/server.go:2928 +0x384
KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
```

**Comment by harshavardhana** [comment]
> ```
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error: github.com/minio/minio/cmd/http.(*Server).Start.func1(0x1fa72a0, 0xc00058e460, 0xc0001d7700)
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error:    github.com/minio/minio@/cmd/http/server.go:104 +0x2ab
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error: net/http.HandlerFunc.ServeHTTP(0xc0001da080, 0x1fa72a0, 0xc00058e460, 0xc0001d7700)
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error:    net/http/server.go:2007 +0x44
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error: net/http.serverHandler.ServeHTTP(0xc0000ad560, 0x1fa72a0, 0xc00058e460, 0xc0001d7700)
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error:    net/http/server.go:2802 +0xa4
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error: net/http.(*conn).serve(0xc0007c2b40, 0x1faede0, 0xc003eb0bc0)
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error:    net/http/server.go:1890 +0x875
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error: created by net/http.(*Server).Serve
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | API: SYSTEM()
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Time: 13:18:59 UTC 07/06/2020
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | DeploymentID: 8dd287dd-54ee-4dad-b3dc-8e35492d827f
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    | Error:    net/http/server.go:2928 +0x384
> KMS_minio.1.wdi9vzmdwdkp@apgrw6jraaa0cma    |        1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> ```

You need to share entire trace this looks like half of what was printed.

**Comment by klauspost** [comment]
Closing as requested. Feel free to open another issue or visit slack if you persistently have issues.
