### ISSUE TITLE
mc command is taking a long time to copy the objects to bucket

### ISSUE THREAD

**Issue by shettypriy** [minio/mc#3325]
Till now we were able to copy the objects without any slowness issue using mc command. But today copying a empty file is taking long time and it gets stuck as below

time mc cp /mnt/sdf/test.txt myminio/pctestbucket/test.txt                                                                             /mnt/sdf/test.txt:             0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓                                                                                                                        ex51ssd71  07/28  6:13a

not sure what is making mc to be slow

WE have setup minio cluster on 4 machines with debian 10. We have one machine of 1TB and remaining 3 of 500GB.  One machine with debian 9 and remaining machines with debian 10. This setup worked fine in the beginning and after a gap of one month it is causing the issue

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2020-05-28T23-43-36Z
## System information

Everytime one or the other node in the minicluster gives the following error in the error log

Error: http: Server closed                                                                                                                                                         disk=http://minio1.promptcloud.com:9000/mnt/sdf/installs/minio_cluster_setup/data1                                                                                          3: github.com/minio/minio@/cmd/xl-v1-utils.go:132:cmd.readXLMeta()                                                                                                          2: github.com/minio/minio@/cmd/xl-v1-utils.go:155:cmd.readAllXLMetadata.func1()                                                                                             1: github.com/minio/minio@/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1() 

Error: disk not found                                                                                                                                                              endpoint=http://minio4.promptcloud.com:9000/mnt/sdf/installs/minio_cluster_setup/data4                                                                                      2: github.com/minio/minio@/cmd/prepare-storage.go:51:cmd.glob..func5.1()                                                                                                    1: github.com/minio/minio@/cmd/xl-sets.go:205:cmd.(*xlSets).connectDisks.func1()       

API: SYSTEM()                                                                                                                                                               Time: 11:35:50 UTC 07/28/2020                                                                                                                                               DeploymentID: 4d42f340-15e7-4985-9419-c16fd30a32e6                                                                                                                          Error: Operation timed out                                                                                                                                                         1: github.com/minio/minio@/cmd/data-usage.go:59:cmd.storeDataUsageInBackend()

**Comment by klauspost** [comment]
This looks more like a server setup problem than an `mc` issue. If it persists feel free to open an issue on the [server project](https://github.com/minio/minio) with more information on your setup.

> 3 of 500GB

This could be the cause of the problems.  Before filing the issue either clear some space or add more, since MinIO will refuse to receive more files once disks are closed to being filled.
