### ISSUE TITLE
Documentation should reflect the latest released version

### ISSUE THREAD

**Issue by rhurling** [minio/mc#3332]
## My Problem
I tried to use the `mc alias set` command but it wouldn't work and also was not listed when i ran `mc --help`. Only after searching for ~30mins I found that it was only added 2 days ago and the last release was almost 2 weeks ago.

## Expected behavior
The [Documentation](https://docs.min.io/docs/minio-client-complete-guide.html) should reflect the latest released version

## Actual behavior
The Documentation reflects (as far as i can tell) the master branch

## Solution
Maybe there could be a dropdown or something like in similar documentations which allows selecting which release (or master branch) one wants to look at.

**Comment by kannappanr** [comment]
@rhurling Thanks for reporting. We are aware of the issue, we will make a release in the next couple of days.

**Comment by harshavardhana** [comment]
mc released with the latest document.
