### ISSUE TITLE
This looks more like a server setup problem than an `mc` issue. If it persists feel free to open an issue on the [server project](https://github.com/minio/minio) with more information on your setup.

### ISSUE THREAD

**Issue by shettypriy** [minio/mc#3357]
This looks more like a server setup problem than an `mc` issue. If it persists feel free to open an issue on the [server project](https://github.com/minio/minio) with more information on your setup.

> 3 of 500GB

This could be the cause of the problems.  Before filing the issue either clear some space or add more, since MinIO will refuse to receive more files once disks are closed to being filled.

_Originally posted by @klauspost in https://github.com/minio/mc/issues/3325#issuecomment-671849340_

**Comment by shettypriy** [comment]
Can minio cluster be setup on the machines with RAID 1 configuration? Currently the machines that we use for minio cluster have RAID configuration with 2 drives each and we have 4 machines and total of 8 drives. Can the machines with RAID1 configuration be used for setting up minio cluster

**Comment by klauspost** [comment]
See https://docs.min.io/docs/minio-erasure-code-quickstart-guide.html

With the default erasure coded setup you can loose any 4 drives compared to RAID 1 where you can lose data already at 2 dead drives. In both cases you lose the same amount of available space, so erasure coded setups are always preferable.

This is unrelated to mc. Closing. Feel free to join the community slack for these type of questions. https://slack.min.io/
