### ISSUE TITLE
`mc ilm list` prints wrongly colored text

### ISSUE THREAD

**Issue by AndiDog** [minio/mc#3363]
## Expected behavior

Text printed in default color instead of fancy colors. Please don't assume that people use dark mode.

## Actual behavior

Lines are printed white on – in my case – white background.

<img width="424" alt="Screenshot 2020-08-15 at 20 15 41" src="https://user-images.githubusercontent.com/1376043/90318953-4eb50100-df34-11ea-832d-963731b8a262.png">

## Steps to reproduce the behavior

```
mkdir /tmp/m
cd /tmp/m
minio server . # run in background
mc mb json-list-issue
mc alias set local http://localhost:9000 minioadmin minioadmin
echo '{"Rules":[{"Expiration":{"Days":42},"ID":"xyz","Filter":{"Prefix":"abc/"},"Status":"Enabled"}]}' | mc ilm import local/json-list-issue
mc ilm list local/json-list-issue
mc ilm list --json local/json-list-issue # works (uses other colors)
```

## mc --version

```
mc version RELEASE.2020-07-31T23-34-13Z
```

## System information

macOS, iTerm terminal with profile that uses black text on white background ("light mode")

**Comment by kannappanr** [comment]
@AndiDog Can you try 
```
mc ilm list --json --no-color local/json-list-issue
```

**Comment by AndiDog** [comment]
Both of those work as expected. But that's not a solution.

**Comment by vadmeste** [comment]
> Both of those work as expected. But that's not a solution.

I agree, we can avoid specifying black and white, the terminal will use the default color in that case.

**Comment by klauspost** [comment]
The same can be said for *any* color. Unless somebody submits a "theme" functionality I don't see that as a solution. Banning individual random colors isn't a solution either.

@AndiDog I suggest you use `--no-color` as proposed, switch background color or wait for/submit a patch that allows selecting "themes".
