### ISSUE TITLE
A header you provided implies functionality that is not implemented

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3370]
Hi,
Any idea how to fix this ?

$ mc version info ny/vtest
server/vtest versioning status is enabled
$ mc cp rr server/vtest
mc: <ERROR> Failed to copy `rr`. A header you provided implies functionality that is not implemented

minio    Version: 2020-08-18T19:41:00Z
mc version RELEASE.2020-08-08T02-33-58Z

**Comment by harshavardhana** [comment]
FS mode doesn't implement versioning @i0x71

**Comment by harshavardhana** [comment]
> $ mc version info ny/vtest
> server/vtest versioning status is enabled
> $ mc cp rr server/vtest
> mc: Failed to copy `rr`. A header you provided implies functionality that is not implemented

Provide `--debug` output

**Comment by i0x71** [comment]
Here you go

mc: <DEBUG> GET /vtest/?location= HTTP/1.1
Host: xx.xx.xx.130:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-08T02:33:58Z
Authorization: AWS4-HMAC-SHA256 /20200820/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200820T133001Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 20 Aug 2020 13:30:01 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Vary: Origin
X-Amz-Request-Id: 162CFD0D431225B3
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  45.444439ms

mc: <DEBUG> HEAD /vtest/ HTTP/1.1
Host: xx.xx.xx.130:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-08T02:33:58Z
Authorization: AWS4-HMAC-SHA256 /20200820/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200820T133001Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Thu, 20 Aug 2020 13:30:01 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Vary: Origin
X-Amz-Request-Id: 162CFD0D4477F224
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  23.254013ms

mc: <DEBUG> HEAD /vtest/ HTTP/1.1
Host: xx.xx.xx.130:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-08T02:33:58Z
Authorization: AWS4-HMAC-SHA256 /20200820/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200820T133001Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Thu, 20 Aug 2020 13:30:01 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Vary: Origin
X-Amz-Request-Id: 162CFD0D45E12849
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  23.047351ms


 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> HEAD /vtest/ HTTP/1.1
Host: xx.xx.xx.130:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-08T02:33:58Z
Authorization: AWS4-HMAC-SHA256 20200820/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200820T133001Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Thu, 20 Aug 2020 13:30:01 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Vary: Origin
X-Amz-Request-Id: 162CFD0D474C0441
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  22.689918ms

mc: <DEBUG> GET /vtest/?object-lock= HTTP/1.1
Host: xx.xx.xx.130:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-08T02:33:58Z
Authorization: AWS4-HMAC-SHA256 /20200820/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200820T133001Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Content-Length: 328
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 20 Aug 2020 13:30:01 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Vary: Origin
X-Amz-Request-Id: 162CFD0D48B3A953
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ObjectLockConfigurationNotFoundError</Code><Message>Object Lock configuration does not exist for this bucket</Message><BucketName>vtest</BucketName><Resource>/vtest/</Resource><RequestId>162CFD0D48B3A953</RequestId><HostId>fea42684-f118-4f24-b75d-82cc80bb1c26</HostId></Error>mc: <DEBUG> Response Time:  23.311445ms

mc: <DEBUG> PUT /vtest/rr HTTP/1.1
Host: xx.xx.xx.130:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-08T02:33:58Z
Content-Length: 10500246
Authorization: AWS4-HMAC-SHA256 xxxxxxxxxxxxxx/20200820/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=**REDACTED**
Content-Type: application/octet-stream
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20200820T133001Z
X-Amz-Decoded-Content-Length: 10485760
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 501 Not Implemented
Connection: close
Content-Length: 332
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 20 Aug 2020 13:30:01 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Vary: Origin
X-Amz-Request-Id: 162CFD0D4A1CB7D7
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Key>rr</Key><BucketName>vtest</BucketName><Resource>/vtest/rr</Resource><RequestId>162CFD0D4A1CB7D7</RequestId><HostId>fea42684-f118-4f24-b75d-82cc80bb1c26</HostId></Error>mc: <DEBUG> Response Time:  37.970685ms

mc: <ERROR> Failed to copy `rr`. A header you provided implies functionality that is not implemented
 (3) cp-main.go:570 cmd.doCopySession(..) Tags: [rr]
 (2) common-methods.go:552 cmd.uploadSourceToTargetURL(..) Tags: [rr]
 (1) common-methods.go:317 cmd.putTargetStream(..) Tags: [ny, http://xx.xx.xx.130:9000/vtest/rr]
 (0) client-s3.go:1048 cmd.(*S3Client).Put(..)
 Release-Tag:RELEASE.2020-08-08T02-33-58Z | Commit:7e52c104bee1 | Host:debian | OS:linux | Arch:amd64 | Lang:go1.13.15 | Mem:28 MB/72 MB | Heap:28 MB/66 MB

**Comment by harshavardhana** [comment]
Are you running in FS mode?

**Comment by i0x71** [comment]
What do you mean ?

**Comment by harshavardhana** [comment]
> minio server /MINIO
> Where /MINIO is a folder on nfs

yes we don't support versioning in FS mode @i0x71 - it is bug `mc version` command should fail. Let me fix that.

**Comment by harshavardhana** [comment]
So what you see is correct - will be fixed to disallow setting `mc version` in the first place. You need to use erasure coding or distributed erasure coding to avail versioning.

Read the docs here https://docs.minio.io/docs/minio-bucket-versioning-guide.html
> Versioning feature is only available in erasure coded and distributed erasure coded setups.
