### ISSUE TITLE
mc: <ERROR> Unable to validate source `test.*`.

### ISSUE THREAD

**Issue by fdefilippo** [minio/mc#3374]
## Expected behavior
c:\tmp>dir test*exe
...
Directory of C:\tmp

21/08/2020  14:58        776 test1.bin
21/08/2020  14:58        776 test2.bin

mc cp test* play\test\

copy all matching file

## Actual behavior
mc: <ERROR> Unable to validate source `test*`.

## Steps to reproduce the behavior
mc cp test* play\test\

## mc --version
mc version RELEASE.2020-08-20T00-23-01Z

## System information
windows 10, windows 2012, windows 2016

**Comment by fdefilippo** [comment]
nobody else ?

**Comment by fdefilippo** [comment]
the same executable used in the cygwin environment has no problems::

```
$ ./mc.exe --json cp uno* play/test/
{
 "status": "success",
 "source": "uno.txt",
 "target": "play/test/uno.txt",
 "size": 0,
 "totalCount": 1,
 "totalSize": 0
}
{
 "status": "success",
 "source": "uno1.txt",
 "target": "play/test/uno1.txt",
 "size": 0,
 "totalCount": 2,
 "totalSize": 0
}
{
 "status": "success",
 "source": "uno2.txt",
 "target": "play/test/uno2.txt",
 "size": 0,
 "totalCount": 3,
 "totalSize": 0
}
{
 "status": "success",
 "total": 0,
 "transferred": 0,
 "speed": 0
}

```

**Comment by ebozduman** [comment]
I see this also works in Linux, but not on Windows.
So, it is legit.
