### ISSUE TITLE
mc does not resolve mDNS zero-conf hostnames.

### ISSUE THREAD

**Issue by dapperfu** [minio/mc#3377]
## Expected behavior

Using a ```.local``` hostname works.

## Actual behavior

```mc``` seems to bypass name resolution on the host and goes directly to the specified DNS servers?

```
$ mc ls nas
mc: <ERROR> Unable to list folder. Get http://nas.local:9000/: dial tcp: lookup nas.local on 127.0.0.53:53: no such host

$ ping nas.local
PING nas.local (192.168.0.2) 56(84) bytes of data.
64 bytes from 192.168.0.2 (192.168.0.2): icmp_seq=1 ttl=64 time=4.54 ms
```
## Steps to reproduce the behavior

1. Add a machine using the mDNS
2. Attempt to use ```mc``` with the host.

## mc --version

```
mc --version
mc version RELEASE.2020-08-08T02-33-58Z
```

## System information

```
PopOS! 20.04
Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
Can you share your `/etc/nssswitch.conf`? @dapperfu

**Comment by dapperfu** [comment]
```# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files systemd
group:          files systemd
shadow:         files
gshadow:        files

hosts:          files mdns4_minimal [NOTFOUND=return] dns myhostname
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

**Comment by ebozduman** [comment]
I'll get back to this issue as soon as I am done with my other higher priority tasks.

**Comment by harshavardhana** [comment]
> hosts:          files mdns4_minimal [NOTFOUND=return] dns myhostname

It would be better to test with the following changes

> hosts:          files dns myhostname

**Comment by cageyz** [comment]
> I'll get back to this issue as soon as I am done with my other higher priority tasks.

mc version RELEASE.2021-09-02T09-21-27Z

still has this issue

**Comment by anderbubble** [comment]
This behavior also still present on macOS.

```
mc version RELEASE.2021-10-07T04-19-58Z
```
