### ISSUE TITLE
minio-client (windows) mv command seems to remove entire source directory when there's no files left after move

### ISSUE THREAD

**Issue by arizvisa** [minio/mc#3379]
Not sure if I'm crazy or what, but it seems if there's a single file in a target directory and it's moved into a target bucket using `mc mv`, the source directory is also being removed by the minio-client. It seems to only happen for me on Windows, and works as one would expect in a posix environment (`RELEASE.2020-07-31T23-34-13Z`). I haven't setup a proper testing environment to reproduce, but it's only happening to me on Windows. Really doesn't make sense...

## Actual behavior
![image](https://user-images.githubusercontent.com/2035497/91266754-804d7980-e737-11ea-8383-b742dd75b6b0.png)

## Expected behavior
I would expect the source directory to remain.

## Steps to reproduce the behavior
C> mkdir test1
C> mkdir test2
C> dir /ad test?
C> echo > test1\file
C> mc.exe mv test1\file test2\file
C> dir /ad test?

## mc --version
mc version DEVELOPMENT.GOGET

However, this binary is being cross-compiled with golang 1.14.4 from the release tag (as of 8/26) of the github.com/minio/mc repo.

## System information
This is on a win81x86-enterprise evaluation box. (I can get you a packer template if y'all don't have one handy).

**Comment by arizvisa** [comment]
Not stale. There has been no triaging performed on this issue since it has been created.

**Comment by ebozduman** [comment]
@arizvisa ,

Sorry for the delay looking into this issue.
This is a known behavior in any local filesystem and it is consistent with `mc`s design done for block storage. That is, `mc rm ...` and `mc mv ...` commands will automatically remove/mv any empty prefixes together with the intended object.

Example:
```
$ mc mb mm1/test1 mm1/test2
Bucket created successfully `mm1/test1`.
Bucket created successfully `mm1/test2`.
$ mc tree -f mm1
mm1
├─ test1
└─ test2
$ mc cp /etc/issue mm1/test1/pre/fix/file
/etc/issue:            26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 174 B/s 0s
$ mc tree -f mm1
mm1
├─ test1
│  └─ pre
│     └─ fix
│        └─ file
└─ test2
$ mc mv mm1/test1/pre/fix/file mm1/test2/
...est1/pre/fix/file:  26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 412 B/s 0s
$ mc tree -f mm1
mm1
├─ test1
└─ test2
   └─ file
```
As you can see, the prefixes are removed as in the case of the local filesystem. If you had any other objects/files in your directories, which are treated as prefixes by `mc`, then those local filesystem directories, up to the point where the object/file resides, won't be touched.
As in;
```
$ mkdir -p test1/pre/fix/
$ mkdir test2
$ tree test*
test1
└── pre
    └── fix
test2

2 directories, 0 files
$ mc cp /etc/issue test1/pre/fix/file1
/etc/issue:            26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 4.26 KiB/s 0s
$ mc cp /etc/issue test1/pre/file2
/etc/issue:            26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 3.55 KiB/s 0s
$ tree test*
test1
└── pre
    ├── file2
    └── fix
        └── file1
test2

2 directories, 2 files
$ mc rm test1/pre/fix/file1
Removing `test1/pre/fix/file1`.
$ tree test*
test1
└── pre
    └── file2
test2

1 directory, 1 file
$ mc rm test1/pre/file2
Removing `test1/pre/file2`.
$ tree test*
test2

0 directories, 0 files
```

**Comment by arizvisa** [comment]
Is this a WONTFIX in that case, as it's working as intended?

**Comment by ebozduman** [comment]
@arizvisa 
Yes, it is.
But we still would like to hear your opinion to make sure there is no compelling reason for us to rethink about our design before marking it as `won't fix`.

**Comment by arizvisa** [comment]
Well I personally don't care too much just as long as the differences between the device types are documented properly for their respective commands, because I imagine I won't be the first to assume that in a single-depth directory structure, there's a sort-of parallel between both mb/mkdir and rb/rmdir. It's because of the similarities in naming that I assumed both `mc rm` and `mc mv` would retain similar semantics as `/bin/rm` and `/bin/mv`.

But again, these semantics only seem to be true for me on windows. On a linux, for example, the following `mc mv` shows that it's actually `cp`ing instead of `mv`ing to avoid removing the directory.
```
# the following is equiv as the first 4 commands in my windows example
$ mc mb dir1; mc mb dir2; touch dir1/file; mc ls dir1/
Bucket created successfully `dir1`.
Bucket created successfully `dir2`.
[2021-01-04 19:06:09 CST]      0B file

# this is the 5th command in my example
$ mc mv dir1/file dir2/file
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃

# this is the 6th command in my example
$ ls -ald dir1 dir2
drwxr-xr-x. 2 user users 4096 Jan  4 19:06 dir1
drwxr-xr-x. 2 user users 4096 Jan  4 19:06 dir2

$ find .
.
./dir2
./dir2/file
./dir1
./dir1/file
```

Anyways, the reason why I walked right into this issue was because I was prototyping some windows scripts I wrote using the `mc` client prior to them acting directly on a bucket (hosted by the daemon), and I couldn't figure out why my provisioned and acl'd directory kept disappearing. Hence I was in a loop testing something else (re-creating and re-acl'ing the removed directory) whilst running my scripts thinking that my config-mgmt tool was somehow removing the entire directory. I eventually figured out that it was the `mc` client that was removing it (and nothing that I was actually doing). So my issue was really that I was treating the base directory as a "bucket" (in a sense), prior to the deployment of the actual daemon.

Like to me, it would make sense to do these removals for any subdirectories underneath a particular directory/bucket, but removing the parent directory/bucket that an object is contained in is just non-obvious logic and definitely should be documented in the minio-complete-guide or somewhere. Still, though, I'm okay with this being closed as a WONTFIX. Not all software can be perfect, and as MinIO is already so awesome at everything else, this little quirk in the client gives it character.

**Comment by ebozduman** [comment]
Thanks @arizvisa 
Closing this issue as `won't fix` at this point. 
The reported problem is local file system specific and user has a chance to use native OS commands to manipulate local filesystem entities.

**Comment by arizvisa** [comment]
Ftr, this issue that was tagged as "WONTFIX" seems to be related to #3621 and has a PR related to it in #3678.
