### ISSUE TITLE
mc rm does not delete bucket if empty, but deletes bucket if it has files

### ISSUE THREAD

**Issue by kcboyle** [minio/mc#3387]
After some of the recent "bug fix" releases, some of the behavior we were expecting changed. In short, if we create a bucket with `mc`, and try to delete it, minio says the bucket does not exist. `mc ls` shows the bucket present. if we add anything to that bucket, and run the same `mc rm`, then the object is somehow found, and deletes appropriately. This was strange behavior, and unexpected. (We have changed our code to use `mc rb` instead of `mc rm`, but we felt it appropriate to file this issue anyway)

## Expected Behavior
I expect `mc rm` to remove my bucket, even if it is empty OR I expect `mc rm` to never remove my bucket at all

## Current Behavior
`mc rm` will only remove the bucket if there are files inside, and errors "it cannot find the object" otherwise

## Possible Solution
Unsure. Prior to Aug 17th (whatever version of minio was released then) we did not encounter this issue.

## Steps to Reproduce (for bugs)
```
○ →  mc mb my-bucket
Bucket created successfully `my-bucket`.

○ → mc rm my-bucket --recursive --force
mc: <ERROR> Failed to remove `my-bucket`. Object does not exist

○ → mc ls
[2020-06-24 13:44:08 MDT]    319B main.go
[2020-08-28 11:01:07 MDT]     64B my-bucket/

○ → touch my-bucket/file.txt

○ → mc rm my-bucket --recursive --force
Removing `my-bucket/file.txt`.
```

## Context
We were testing error cases in our codebase using minio.
We wanted to show the user a helpful error message if the bucket was empty (meaning that it did not have any matching products in it for us to use). In the test, we run
`mc mb my-bucket`
[run-test]
`mc rm my-bucket --force --recursive` 
We remove the bucket after every test to ensure a clean test environment for the next test, so contamination does not occur.

## Regression
 Yes. This was not an issue before Aug 17
 Not sure which commit caused the regression

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-08-27T05-16-20Z
* Server setup and configuration: N/A
* Operating System and version (`uname -a`): OSX 10.15.6 AND ubuntu bionic

**Comment by harshavardhana** [comment]
Moved the issue to relevant repository.

**Comment by kcboyle** [comment]
I'm okay with this issue being marked by the team as a non-issue, but please do not close because the team has not had any further activity on it. Thanks. Happy to provide additional context/answer questions

**Comment by ebozduman** [comment]
@kcboyle, @kannappanr , @vadmeste 

Please chime in and give me your thoughts about the 3 issues that need to be fixed here.

_Note:_
_mc version DEVELOPMENT.2021-02-03T01-24-46Z_

This is the current and expected behavior for `mc rb <empty-dir>` on the local filesystem and the object storage.
```
$ mc mb test
Bucket created successfully `test`.
$ ll test
total 8
drwxr-xr-x  2 ersan ersan 4096 Feb  2 17:25 ./
drwxr-xr-x 10 ersan ersan 4096 Feb  2 17:25 ../
$ mc rb test
Removed `test` successfully.
$ ll test
ls: cannot access 'test': No such file or directory
```

This is the current and expected behavior for `mc rm -r --force <empty-dir>` on the local filesystem and the object storage... almost!
```
$ mc mb test
Bucket created successfully `test`.
$ ll test
total 8
drwxr-xr-x  2 ersan ersan 4096 Feb  2 17:25 ./
drwxr-xr-x 10 ersan ersan 4096 Feb  2 17:25 ../
$ mc rm test
mc: <ERROR> Removal requires --recursive flag. This operation is *IRREVERSIBLE*. Please
review carefully before performing this *DANGEROUS* operation. 
$ mc rm -r test
mc: <ERROR> Removal requires --force flag. This operation is *IRREVERSIBLE*. Please review
carefully before performing this *DANGEROUS* operation. 
#
# Ooops! Failure, nothing is removed, but no error message. This is an issue.
$ mc rm -r --force test/
$ ll test
total 8
drwxr-xr-x  2 ersan ersan 4096 Feb  2 17:25 ./
drwxr-xr-x 10 ersan ersan 4096 Feb  2 17:25 ../
```

#### Issue#1
Match the object storage error message on the fs side (see the last `mc rm` command above)
```
# correct object storage behavior
$ mc rm -r --force mm1/ersan/ 
mc: <ERROR> Failed to remove `mm1/ersan/`. Object does not exist
```

#### Issue#2
 - The error message in local filesystem is misleading. It needs to be removed.
 - (?) Leave the base/root directory behind, treating it as the bucket or maybe NOT, as there is no concept of 'bucket' in local filesystem. We need to decide on this. @kannappanr , @vadmeste ??
```
# On object storage
$ mc mb mm1/ersan ; mc cp /etc/issue mm1/ersan/pre/fix/ ; mc tree -f mm1
mm1
└─ ersan
   └─ pre
      └─ fix
         └─ issue
$ mc rm -r --force mm1/ersan/
Removing `mm1/ersan/pre/fix/issue`.
$ mc tree -f mm1
mm1
└─ ersan

# On local filesystem
$ mc mb test ; mc cp /etc/issue test/pre/fix/ ; mc tree -f test
test
└─ pre
   └─ fix
      └─ issue
$ mc rm -r --force test/
Removing `test/pre/fix/issue`.
Removing `test/pre/fix`.
Removing `test/pre`.
mc: <ERROR> Failed to remove `test/pre`. remove test/pre/fix: no such file or directory
$ ll test
ls: cannot access 'test': No such file or directory
```

#### Issue#3
 - Directories are all removed. Wrong error message needs to be removed.
 - The error message in object storage is correct. Successful removal message needs to be suppressed.
 - (?) I think object storage behavior is the one, we want to go with. Or we can keep it as is, as there is no concept of 'bucket' in local filesystem. @kannappanr , @vadmeste ??
```
# On object storage
$ mc mb mm1/ersan ; mc cp /etc/issue mm1/ersan/pre/fix/ ; mc tree -f mm1
mm1
└─ ersan
   └─ pre
      └─ fix
         └─ issue

$ mc rb --force mm1/ersan/pre/fix/issue
mc: <ERROR> Failed to remove `mm1/ersan/pre/fix/issue`, continuing.. cannot delete prefixes
with `mc rb` command - Use `mc rm` instead
Removed `mm1/ersan/pre/fix/issue` successfully.
$ mc tree -f mm1
mm1
└─ ersan
   └─ pre
      └─ fix
         └─ issue

# On local filesystem
$ mc mb test ; mc cp /etc/issue test/pre/fix/ ; mc tree -f test
test
└─ pre
   └─ fix
      └─ issue
$ mc rb --force test/pre/fix/issue
mc: <ERROR> Failed to remove `test/pre/fix/issue`, continuing.. readdirent: not a directory
Removed `test/pre/fix/issue` successfully.
$ ll test
ls: cannot access 'test': No such file or directory
```
