### ISSUE TITLE
mc admin trace for TLS enabled server fails.

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [minio/mc#3396]
## Expected behavior
mc config host add  miniotls http://IP:PORT minioadmin minioadmin should configure new alias
## Actual behavior
But the same gives <ERROR> Unable to initialize new alias from the provided credentials. Get https://IP:PORT/probe-bucket-sign-d0kzpdf09xzv/?location=: x509: certificate signed by unknown authority.

However if I run, mc --insecure config host add  miniotls http://IP:PORT minioadmin minioadmin alias gets added, but subsequent activities mc admin trace --all miniotls does not log any request.
MinIO console keeps on logging,
2020/09/03 14:54:04 http: TLS handshake error from 192.168.1.144:57378: remote error: tls: bad certificate
## Steps to reproduce the behavior
Start MinIO server with TLS enabled,
Run mc config host add  miniotls http://IP:PORT minioadmin minioadmin should configure new alias

## mc --version
- (paste output of `mc --version`)
Latest

**Comment by vadmeste** [comment]
What happens if you pass --insecure flag to your admin trace command ? `mc --insecure admin trace --all miniotls`

**Comment by PSHREYASHOLLA** [comment]
@vadmeste  With --insecure it works. But why is MC throwing error when MinIO is hosted on self signed certificate?

**Comment by vadmeste** [comment]
@PSHREYASHOLLA because mc is unable to trust the self signed certificate that you generated. You need a trusted authority to generate a real certificate for you.

Nothing to fix here, closing this ticket.

**Comment by harshavardhana** [comment]
> @vadmeste With --insecure it works. But why is MC throwing error when MinIO is hosted on self signed certificate?

Put the server public certificate at `.mc/certs/CAs`  to trust it.
