### ISSUE TITLE
> Let me know if I'm missing any thing. is there a way to configure mc to access certs

### ISSUE THREAD

**Issue by xi1149-ashurana** [minio/mc#3403]
> Let me know if I'm missing any thing. is there a way to configure mc to access certs

mc currently doesn't support self signed certificates, it used to support early in its days. But we removed it to keep things simpler. 

You can use 'mc' with standard SSL without using 'insecure' option for example - if you have a domain certificate signed by known SSL authorities. 

```@harshavardhana I am using domain self-signed certificate but still cannot connect to minio without --insecure
mc ls https://play.minio.io:9000
```

```
mc ls https://s3.amazonaws.com 
```

_Originally posted by @harshavardhana in https://github.com/minio/mc/issues/1220#issuecomment-151628794_

**Comment by harshavardhana** [comment]
> > Let me know if I'm missing any thing. is there a way to configure mc to access certs
> 
> mc currently doesn't support self signed certificates, it used to support early in its days. But we removed it to keep things simpler.
> 
> You can use 'mc' with standard SSL without using 'insecure' option for example - if you have a domain certificate signed by known SSL authorities.
> 
> ```
> mc ls https://play.minio.io:9000
> ```
> 
> ```
> mc ls https://s3.amazonaws.com 
> ```
> 
> _Originally posted by @harshavardhana in [#1220 (comment)](https://github.com/minio/mc/issues/1220#issuecomment-151628794)_

Drop your public.crt at `.mc/certs/CAs/`  and follow docs on how to create an alias for your target using

`mc alias set`
