### ISSUE TITLE
mc mirror mirrors other buckets than requested

### ISSUE THREAD

**Issue by taisph** [minio/mc#3409]
## Expected behavior

I'm using `mc --json --quiet mirror --watch --overwrite --remove myhost/mybucket/ /data/`to continuously synchronize all files in that bucket into a local folder.

## Actual behavior

Files from other buckets are mirrored into subfolders under `/data` when they are updated/added on the server.

## Steps to reproduce the behavior

- Run `mc --json --quiet mirror --watch --overwrite --remove myhost/mybucket/ /data/`.
- Add files in another bucket on the same host.

## mc --version
mc version RELEASE.2020-09-03T00-08-28Z

## System information
Kubernetes, container images minio/mc:RELEASE.2020-09-03T00-08-28Z (and minio/minio:RELEASE.2020-09-02T18-19-50Z).

mc mirror log:
```
{"status":"success","source":"myhost/mybucket/some.pdf","target":"/data/some.pdf","size":194385,"totalCount":18,"totalSize":964100}
{"status":"success","source":"myhost/mybucket/other.pdf","target":"/data/other.pdf","size":404828,"totalCount":19,"totalSize":1368928}
{"status":"success","source":"myhost/mybucket/some.xsl","target":"/data/some.xsl","size":8339,"totalCount":20,"totalSize":1412993}
{"status":"success","source":"myhost/otherbucket/folder/current/1.pdf","target":"/data/otherbucket/folder/current/1.pdf","size":117828,"totalCount":21,"totalSize":2814610}
{"status":"success","source":"myhost/otherbucket/folder/current/2.pdf","target":"/data/otherbucket/folder/current/2.pdf","size":117358,"totalCount":22,"totalSize":3049796}
{"status":"success","source":"myhost/otherbucket/folder/current/3.pdf","target":"/data/otherbucket/folder/current/3.pdf","size":118215,"totalCount":23,"totalSize":3285369}
```

**Comment by harshavardhana** [comment]
> I'm using `mc --json --quiet mirror --watch --overwrite --remove myhost/mybucket/ /data/`to continuously synchronize all files in that bucket into a local folder.

All flags need to come together @taisph i.e specify all them at the end or in the beginning - flags can change the order of args and this is a limitation of our current CLI library.

**Comment by taisph** [comment]
> > I'm using `mc --json --quiet mirror --watch --overwrite --remove myhost/mybucket/ /data/`to continuously synchronize all files in that bucket into a local folder.
> 
> All flags need to come together @taisph i.e specify all them at the end or in the beginning - flags can change the order of args and this is a limitation of our current CLI library.

`mc mirror --json --quiet --watch --overwrite --remove myhost/mybucket/ /data/` made no difference.
