### ISSUE TITLE
mc mirror --watch implies --remove

### ISSUE THREAD

**Issue by rafaelsierra** [minio/mc#3413]
## Expected behavior

`mc mirror --watch . s3/my-bucket` should not remove files that were removed

## Actual behavior

`mc mirror --watch` behaves like `mc mirror --watch --remove`

## Steps to reproduce the behavior
```
mc mirror --watch . s3/my-bucket
touch a
touch b
rm a
```

File `a` should not be removed from `s3/my-bucket`

## mc --version
mc version DEVELOPMENT.GOGET (from around 2020-09-18)

## System information
go version go1.15.2 linux/arm64
Running on raspberry pi 3 model b

**Comment by rafaelsierra** [comment]
I suppose this is the intended behavior, if that is the case, than I would suggest a new feature to add `--keep` to `--watch` so that it will never attempt to remove files.

My goal running this `mc mirror --watch` is to create a backup on the bucket from files that have to be removed locally due to lack of disk space (i.e. I have way more space on my bucket than on my raspberry)

**Comment by harshavardhana** [comment]
This is by design @rafaelsierra we have gone few iterations over this and it is worthless for us to keep going back and forth on this. 

Some want it `--remove` with `--watch` and some do not, we cannot satisfy everyone.

**Comment by rafaelsierra** [comment]
What about my suggestion to add `--keep` that would negate this behavior? Have this been discussed as well?

**Comment by rafaelsierra** [comment]
I have been running this PR version for some hours now and it is working as intended (with the `--keep` flag set).

@harshavardhana is this an interesting idea or should I scrap the PR?

**Comment by tannerjfco** [comment]
@harshavardhana if this is by design, it is completely terrible design. The existence of the remove flag implies that if the remove flag isn't set, then things should not be removed. That is also the original behavior of mirror, and introducing a behavior change with no documentation, and no change to the flags design for the command, is a really poor show. Anything that can cause unexpected deletions is a terrible design, and deletions and overwrites should be well safeguarded. The current flag design for the mirror command implies that they are, but that simply isn't true if mirror can remove objects without --remove being set. What is the point of --remove if mirror will remove without the flag set? The point becomes even less clear if a --keep flag as proposed in #3414 is required to provide the opposite effect

**Comment by rafaelsierra** [comment]
I would rather have someone from the project to close this as "won't do" or "working as expected" than letting it close due to staleness.

I am still using my PR version to work around this and looks like more people have the same issue/concern. It would be better to have an official answer about this issue and update the documentation to explain this weird behavior

**Comment by DasSkelett** [comment]
Weirdly enough the behaviour seems to be different for me, `--watch --overwrite --preserve` never removes objects deleted from the source bucket, and `--watch --overwrite --preserve --remove` only removes them on start-up but ignores all files removed from source afterwards...

**Comment by ravindk89** [comment]
For anyone coming to this PR later, there are a few things to consider:

- Our docs here could use improvement - see https://github.com/minio/docs/issues/377
- The behavior of `mc mirror --watch` and `mc mirror --watch --remove` are nuanced in *what* they delete. A bit more information [here](https://github.com/minio/mc/pull/3787#issuecomment-915399657)
- Adding more flags is not something we are looking to do. More flags = more complexity around interactivity between flags, which gets confusing from a user perspective and is more difficult to support from an engineering perspective.

To the point of the OP, its worth marking this correctly - that is, the intended design of `mc mirror --watch` is to synchronize PUT and DELETE operations on the source to the destination. 

Other issues around interactions between flags should be standalone issues for us to look into.

**Comment by henxing** [comment]
>  More flags = more complexity around interactivity between flags, which gets confusing from a user perspective and is more difficult to support from an engineering perspective.
