### ISSUE TITLE
`mc cp/mv` get wrong source/target path because of cli reorder args

### ISSUE THREAD

**Issue by icefed** [minio/mc#3419]
## Expected behavior
`mc cp local/dir1 -r awss3/bucket1/`
should copy `local/dir1` to `awss3/bucket1/`.

## Actual behavior
mc copy `awss3/bucket1/`  to  `local/dir1`.

## mc --version
- (paste output of `mc --version`)

## System information

There is a parse flags bug in cli: 
https://github.com/urfave/cli/issues/355

Set `SkipArgReorder` can prevent reorder args. Also other commands which want order need this. 
https://github.com/minio/cli/blob/735b30120ed7535d13933b0246f8a75cf80b0f74/command.go#L49

**Comment by harshavardhana** [comment]
This is a limitation of our CLI, SkipArgReorder doesn't fix the issue completely. @icefed there are other areas where this actually doesn't work.

**Comment by icefed** [comment]
Yes, we could not fix this completely now, that need complex flags parser.
https://github.com/urfave/cli/issues/355#issuecomment-217648046

Also `mc alias set` now work, sorry, I know not much mc commands.
```
mc alias set s3 http://test.com --api "api" access secret
mc: <ERROR> Invalid URL. URL `secret` for MinIO Client should be of the form scheme://host[:port]/ without resource component.
```

**Comment by harshavardhana** [comment]
> Yes, we could not fix this completely now, that need complex flags parser.
> [urfave/cli#355 (comment)](https://github.com/urfave/cli/issues/355#issuecomment-217648046)
> 
> Also `mc alias set` now work, sorry, I know not much mc commands.
> 
> ```
> mc alias set s3 http://test.com --api "api" access secret
> mc: <ERROR> Invalid URL. URL `secret` for MinIO Client should be of the form scheme://host[:port]/ without resource component.
> ```

Just use either all flags in the beginning or at the end together.

There is nothing we can do to fix this for now.

**Comment by icefed** [comment]
```
Just use either all flags in the beginning or at the end together.
```
This didn't help, bug still in there and you can not ignore it.

we can fix this.
solution 1:
Set `SkipArgReorder=true`, but will not parse flags between args.

Thsolution 2:
Cli use `stdlib flag` for parsing flags, we can replace it with `github.com/spf13/pflag`.

**Comment by kannappanr** [comment]
@icefed Are you saying that something like

```
mc cp local/dir1 awss3/bucket1/ -r
```
or 
```
mc cp -r local/dir1 awss3/bucket1/
```
is not working ?

**Comment by icefed** [comment]
> @icefed Are you saying that something like
> 
> ```
> mc cp local/dir1 awss3/bucket1/ -r
> ```
> 
> or
> 
> ```
> mc cp -r local/dir1 awss3/bucket1/
> ```
> 
> is not working ?

those works.

`mc cp local/dir1 -r awss3/bucket1/` not.

**Comment by harshavardhana** [comment]
> `mc cp local/dir1 -r awss3/bucket1/` not.

This is exactly not fixable at the moment. this is a known limitation perhaps we may have time to fix it in future.
