### ISSUE TITLE
mc rb --force fails/broken after minio upgrade

### ISSUE THREAD

**Issue by rajeshamdev** [minio/mc#3423]
## Expected behavior

Force bucket removal should succeed. We are noticing this issue after migrating to Sept 23 releases. We did not notice this issue in early Sept/2020 release.

## Actual behavior
```
mc rb --force devt/64fa67db-a024-4752-b169-d41be403a16d
mc: <ERROR> Failed to remove `devt/64fa67db-a024-4752-b169-d41be403a16d`, continuing.. The bucket you tried to delete is not empty
Removed `devt/64fa67db-a024-4752-b169-d41be403a16d` successfully.
```
## mc --version
```
minio: 2020-09-23T19:18:30Z
mc : RELEASE.2020-09-23T20-02-13Z
```
## System information
RHEL-7.5

Here are the trace error logs:
```
devt [REQUEST s3.ListObjectVersions] 20:50:13.825
devt GET /64fa67db-a024-4752-b169-d41be403a16d/?delimiter=&encoding-type=url&prefix=&versions=
devt Proto: HTTP/1.1
devt Host: devt:9000
devt Content-Length: 0
devt User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-23T20:02:13Z
devt X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
devt X-Amz-Date: 20200928T205055Z
devt Authorization: AWS4-HMAC-SHA256 Credential=1GpxTt0VlAqfPz2dasFULOQjJLcnno6ysLeRtMaa/20200928/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=be228addfa010c141d2b7e327930689345476af7e289e0706b6321488104c6a8
devt 
devt [RESPONSE] [20:50:13.825] [ Duration 378µs  ↑ 77 B  ↓ 1.3 KiB ]
devt 200 OK
devt Content-Type: application/xml
devt Server: MinIO/RELEASE.2020-09-23T19-18-30Z
devt Vary: Origin
devt X-Amz-Request-Id: 16390DB510977693
devt X-Xss-Protection: 1; mode=block
devt Accept-Ranges: bytes
devt Content-Length: 1050
devt Content-Security-Policy: block-all-mixed-content
devt <?xml version="1.0" encoding="UTF-8"?>
<ListVersionsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>64fa67db-a024-4752-b169-d41be403a16d</Name><Prefix></Prefix><KeyMarker></KeyMarker><NextVersionIdMarker></NextVersionIdMarker><VersionIdMarker></VersionIdMarker><MaxKeys>1000</MaxKeys><Delimiter></Delimiter><IsTruncated>false</IsTruncated><Version><Key>backup/</Key><LastModified>0001-01-01T00:00:00.000Z</LastModified><ETag></ETag><Size>0</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName></DisplayName></Owner><StorageClass>STANDARD</StorageClass><IsLatest>false</IsLatest><VersionId>null</VersionId></Version><Version><Key>license/</Key><LastModified>0001-01-01T00:00:00.000Z</LastModified><ETag></ETag><Size>0</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName></DisplayName></Owner><StorageClass>STANDARD</StorageClass><IsLatest>false</IsLatest><VersionId>null</VersionId></Version><EncodingType>url</EncodingType></ListVersionsResult>
devt 
devt [REQUEST s3.DeleteMultipleObjects] 20:50:13.826
devt POST /64fa67db-a024-4752-b169-d41be403a16d/?delete=
devt Proto: HTTP/1.1
devt Host: devt:9000
devt X-Amz-Content-Sha256: 7514584b2c88bf892f2f920aea83ee1263b3a924568d9f69fb22109b33772993
devt X-Amz-Date: 20200928T205055Z
devt Authorization: AWS4-HMAC-SHA256 Credential=1GpxTt0VlAqfPz2dasFULOQjJLcnno6ysLeRtMaa/20200928/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=1bd9f1dad3e5564c5bb94cd344368ff6681d22c799506df8411623a406b74afc
devt Content-Length: 161
devt Content-Md5: FQSaJ/WGRJsyD+Dzd2fU9w==
devt User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-23T20:02:13Z
devt <Delete><Quiet>true</Quiet><Object><Key>backup/</Key><VersionId>null</VersionId></Object><Object><Key>license/</Key><VersionId>null</VersionId></Object></Delete>
devt [RESPONSE] [20:50:13.827] [ Duration 500µs  ↑ 250 B  ↓ 366 B ]
devt 200 OK
devt Server: MinIO/RELEASE.2020-09-23T19-18-30Z
devt Vary: Origin
devt X-Amz-Request-Id: 16390DB510A74226
devt X-Xss-Protection: 1; mode=block
devt Accept-Ranges: bytes
devt Content-Length: 116
devt Content-Security-Policy: block-all-mixed-content
devt Content-Type: application/xml
devt <?xml version="1.0" encoding="UTF-8"?>
<DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></DeleteResult>
devt 
devt [REQUEST s3.DeleteBucket] 20:50:13.827
devt DELETE /64fa67db-a024-4752-b169-d41be403a16d/
devt Proto: HTTP/1.1
devt Host: devt:9000
devt X-Amz-Date: 20200928T205055Z
devt Authorization: AWS4-HMAC-SHA256 Credential=1GpxTt0VlAqfPz2dasFULOQjJLcnno6ysLeRtMaa/20200928/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=7378ebf351f5283ed2d6db09ee16ead3abf29a20c61f7cc359ae27970ef0598b
devt Content-Length: 0
devt User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-23T20:02:13Z
devt X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
devt 
devt [RESPONSE] [20:50:13.827] [ Duration 218µs  ↑ 77 B  ↓ 611 B ]
devt 409 Conflict
devt Content-Length: 355
devt Content-Security-Policy: block-all-mixed-content
devt Content-Type: application/xml
devt Server: MinIO/RELEASE.2020-09-23T19-18-30Z
devt Vary: Origin
devt X-Amz-Request-Id: 16390DB510B5939E
devt X-Xss-Protection: 1; mode=block
devt Accept-Ranges: bytes
devt <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BucketNotEmpty</Code><Message>The bucket you tried to delete is not empty</Message><BucketName>64fa67db-a024-4752-b169-d41be403a16d</BucketName><Resource>/64fa67db-a024-4752-b169-d41be403a16d/</Resource><RequestId>16390DB510B5939E</RequestId><HostId>27af346d-3b84-41e4-b584-5da03a360099</HostId></Error>
devt 
```

**Comment by vadmeste** [comment]
@rajeshamdev could you paste the output of this command ?
```
mc ls --versions devt/64fa67db-a024-4752-b169-d41be403a16d
```

**Comment by harshavardhana** [comment]
> mc: Failed to remove `devt/64fa67db-a024-4752-b169-d41be403a16d`, continuing.. The bucket you tried to delete is not empty

This error message indicates that Versioning is not enabled @vadmeste

**Comment by rajeshamdev** [comment]
@harshavardhana. Thanks for looking at the issue.

[~]# mc ls --versions devt/64fa67db-a024-4752-b169-d41be403a16d
[2020-09-28 16:32:09 CDT]     0B backup/
[2020-09-28 16:32:09 CDT]     0B license/
[~]#

**Comment by harshavardhana** [comment]
This looks like have you some stale directories with some content @rajeshamdev can you check the backend?

**Comment by rajeshamdev** [comment]
> This looks like have you some stale directories with some content @rajeshamdev can you check the backend?

minio server started as: minio server --address devt:9000 /minio/data{1...4}

The backend datastore:
/dev/sdb1            7.3T   99G  7.2T   2% /minio/data2
/dev/sdc1            7.3T   99G  7.2T   2% /minio/data3
/dev/sda1            7.3T   99G  7.2T   2% /minio/data1
/dev/sdd1            7.3T   99G  7.2T   2% /minio/data4

I see empty dirs in /minio/data{1..4}/64fa67db-a024-4752-b169-d41be403a16d.

ls -lR /minio/data{1..4}/64fa67db-a024-4752-b169-d41be403a16d

/minio/data1/64fa67db-a024-4752-b169-d41be403a16d/backup:
total 0
/minio/data1/64fa67db-a024-4752-b169-d41be403a16d/license:
total 0

/minio/data2/64fa67db-a024-4752-b169-d41be403a16d/backup:
total 0

/minio/data2/64fa67db-a024-4752-b169-d41be403a16d/license:
total 0

/minio/data3/64fa67db-a024-4752-b169-d41be403a16d/backup:
total 0

/minio/data3/64fa67db-a024-4752-b169-d41be403a16d/license:
total 0

/minio/data4/64fa67db-a024-4752-b169-d41be403a16d/backup:
total 0

/minio/data4/64fa67db-a024-4752-b169-d41be403a16d/license:
total 0

When bucket is force removed, why these empty dirs not removed?

**Comment by harshavardhana** [comment]
Because these prefixes don't get listed with `mc rm --force` - it skips the empty directories as valid content.

**Comment by rajeshamdev** [comment]
> Because these prefixes don't get listed with `mc rm --force` - it skips the empty directories as valid content. You can remove them directly from backend.

We are using minio unlimited bucket support :-), there are so many buckets - so removing at the backend is hard.
Do you know why we ended up there?

**Comment by harshavardhana** [comment]
> > Because these prefixes don't get listed with `mc rm --force` - it skips the empty directories as valid content. You can remove them directly from backend.
> 
> We are using minio unlimited bucket support :-), there are so many buckets - so removing at the backend is hard.
> Do you know why we ended up there?

`mc` doesn't list prefixes anymore so that's the change.

**Comment by rajeshamdev** [comment]
We noticed an interesting pattern. Force delete SUCCESSFUL on buckets created after minio Sept/23 release.
It fails on buckets existed before upgrade. This behaviors seems consistent. This means minio upgrade might
have broken.

**Comment by harshavardhana** [comment]
> We noticed an interesting pattern. Force delete SUCCESSFUL on buckets created after minio Sept/23 release.
> It fails on buckets existed before upgrade. This behaviors seems consistent. This means minio upgrade might
> have broken.

Nothing is broken, `mc` simply ignores empty prefixes - which is a change in behavior.

**Comment by rajeshamdev** [comment]
We think upgrade compatibility BROKEN:
i)  Create bucket with prefix and then force delete the bucket while at a mc/minio versions succeeds.
ii) force delete of bucket, existed before mc/minio upgrade, fails after upgrades.
iii) Similar tests successful after upgrade.

Please see the below details.

1) minio at RELEASE.2020-09-02T18-19-50Z and mc at RELEASE.2020-09-03T00-08-28Z - bucket create with prefix and force delete  succeeds.

[root@raj-440 ~]# mc admin info m2
●  172.22.12.166:9003
   Uptime: 58 minutes 
   Version: 2020-09-02T18:19:50Z
   Network: 1/1 OK 
   Drives: 4/4 OK 

0 B Used, 1 Bucket, 0 Objects
4 drives online, 0 drives offline
[root@raj-440 ~]# mc mb m2/science/molecules/h2o
mc: <ERROR> Unable to make prefix, please use `mc mb m2/science/molecules/h2o/`. Buckets or prefixes can only be created with `/` suffix.
[root@raj-440 ~]#
[root@raj-440 ~]# mc mb m2/science/molecules/h2o/
Bucket created successfully `m2/science/molecules/h2o/`.
[root@raj-440 ~]# mc mb m2/science/molecules/n2/
Bucket created successfully `m2/science/molecules/n2/`.
[root@raj-440 ~]# mc mb m2/science/molecules/o3/
Bucket created successfully `m2/science/molecules/o3/`.
[root@raj-440 ~]# mc mb m2/science/molecules/nacl/
Bucket created successfully `m2/science/molecules/nacl/`.
[root@raj-440 ~]# mc mb m2/science/pets/pappy/
Bucket created successfully `m2/science/pets/pappy/`.
[root@raj-440 ~]# mc mb m2/science/pets/gappy/
Bucket created successfully `m2/science/pets/gappy/`.
[root@raj-440 ~]# mc mb m2/science/pets/happy/
Bucket created successfully `m2/science/pets/happy/`.
[root@raj-440 ~]# mc tree -f m2/science
m2/science
├─ molecules
│  ├─ h2o
│  ├─ n2
│  ├─ nacl
│  └─ o3
└─ pets
   ├─ gappy
   └─ pappy
[root@raj-440 ~]#
[root@raj-440 ~]# mc rb --force m2/science
Removed `m2/science` successfully.
[root@raj-440 ~]# mc ls m2
[root@raj-440 ~]#

2) create bucket with prefixes. upgrade minio and mc. minio at 2020-09-26T03:44:56Z and mc at 2020-09-23T20-02-13Z.
   force delete bucket fails.

[root@raj-440 ~]# mc tree -f m2/science
m2/science
├─ molecules
│  ├─ h2o
│  ├─ n2
│  ├─ nacl
│  └─ o3
└─ pets
   ├─ gappy
   └─ pappy
[root@raj-440 ~]# mc admin update m2
Server `m2` updated successfully from 2020-09-02T18:19:50Z to 2020-09-26T03-44-56Z
[root@raj-440 ~]# 
[root@raj-440 ~]# 
[root@raj-440 ~]# mc admin info m2
●  172.22.12.166:9003
   Uptime: 14 seconds 
   Version: 2020-09-26T03:44:56Z
   Network: 1/1 OK 
   Drives: 0/0 OK 

0 B Used, 1 Bucket, 0 Objects
0 drives online, 0 drives offline
[root@raj-440 ~]# 
[root@raj-440 ~]# mc rb --force m2/science
mc: <ERROR> Failed to remove `m2/science`, continuing.. The bucket you tried to delete is not empty
Removed `m2/science` successfully.
[root@raj-440 ~]#
[root@raj-440 ~]# mc tree -f m2/science
m2/science
├─ molecules
│  ├─ h2o
│  ├─ n2
│  ├─ nacl
│  └─ o3
└─ pets
   ├─ gappy
   └─ pappy
[root@raj-440 ~]# 

3) Create another bucket with prefixes and force delete on new bucket succeeds.

[root@raj-440 ~]# mc mb m2/socialscience/metros/hyd/
Bucket created successfully `m2/socialscience/metros/hyd/`.
[root@raj-440 ~]# mc mb m2/socialscience/metros/blr/
Bucket created successfully `m2/socialscience/metros/blr/`.
[root@raj-440 ~]# mc mb m2/socialscience/metros/mysore/
Bucket created successfully `m2/socialscience/metros/mysore/`.
[root@raj-440 ~]# mc mb m2/socialscience/metros/msp/
Bucket created successfully `m2/socialscience/metros/msp/`.
[root@raj-440 ~]#
[root@raj-440 ~]# mc tree -f m2/socialscience
m2/socialscience
└─ metros
   ├─ blr
   ├─ hyd
   ├─ msp
   └─ mysore
[root@raj-440 ~]# mc rb --force m2/socialscience
Removed `m2/socialscience` successfully.
[root@raj-440 ~]#

**Comment by ebozduman** [comment]
@rajeshamdev 

I don't see any of these issues with `mc rb --force` command with the latest `mc` release, `RELEASE.2021-01-30T00-50-42Z`.

Could you please try it?

**Comment by ebozduman** [comment]
@rajeshamdev 

Please re-open the issue and let us know if you can reproduce the issue.
Closed as `working as intended`.
