### ISSUE TITLE
mc admin info wrong drives after pulling disk 

### ISSUE THREAD

**Issue by numas** [minio/mc#3425]
Testing MinIO on 4 drives with this server cmd:
`minio server --certs-dir /etc/pki/minio --address :9001 /disk/i/atst /disk/j/atst /disk/k/atst /disk/l/atst`

`mc admin info atst` shows
Drives: 4/4 OK
4 drives online, 0 drives offline

Pulling one of the disks out of the running server to see how MinIO reacts.

## Expected behavior

`mc admin info atst` should show
Drives 3/4 Degraded(?)
3 drives online, 1 drives offline

## Actual behavior

`mc admin info atst` shows
Drives: 3/3 OK
3 drives online, 0 drives offline

## Steps to reproduce the behavior

Check `mc admin info tenant` before and after pulling a disk from a running system

## mc --version
- RELEASE.2020-09-23T20-02-13Z

## System information

- CentOS Linux release 7.8.2003
- ServeRAID M1015 SAS/SATA Controller (JBOD)

**Comment by harshavardhana** [comment]
> Pulling one of the disks out of the running server to see how MinIO reacts.

Pulling a drive doesn't mean that drive is not available, `mc admin info --json` provides if there is a fresh drive detected and it needs to be healed. 

A fresh drive is also not an offline drive according to MinIO - this is working as expected. Please upgrade your server as well which has fixed these behaviors appropriately.
