### ISSUE TITLE
`mc rm` requires `s3:GetObject`

### ISSUE THREAD

**Issue by znz** [minio/mc#3426]
## Expected behavior

The user with `"s3:DeleteObject"` permission can not remove object.

## Actual behavior

The user without  `"s3:GetObject"` permission can not remove object.

## Steps to reproduce the behavior

```
$ mc admin policy add my-minio expire-backup /tmp/expire-backup.json
Added policy `expire-backup` successfully.
$ mc admin policy set my-minio expire-backup user=expire-user
Policy expire-backup is set on user `expire-user`
$ mc admin policy info my-minio expire-backup | jq .
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
	"s3:DeleteObject",
	"s3:ListBucket"
      ],
      "Resource": [
	"arn:aws:s3:::dokku-postgres/*"
      ]
    }
  ]
}
$ mc rm my-minio/dokku-postgres/test
mc: <ERROR> Failed to remove `my-minio/dokku-postgres/test`. Insufficient permissions to access this file `https://my-minio.example.jp/dokku-postgres/test`
```

## mc --version
- `mc version RELEASE.2020-09-23T20-02-13Z`

## System information

- `minio version RELEASE.2020-09-26T03-44-56Z`
- Run as `minio gateway nas`
- `minio gateway nas` cannot use `lifecycle`. So I tried to use `mc find my-minio/dokku-postgres --older-than '90d' --exec 'mc rm {}'` instead.

**Comment by vadmeste** [comment]
@znz mc usually wants to show good error message when the S3 API is not enough to provide the context.

In your use case, an object deletion in the S3 specification returns 200 OK even when the object does not exist, but mc will stat the object first before deletion so it can provide a good error message.

I guess what we need to do here is to ignore that error and continue the removal

**Comment by harshavardhana** [comment]
Restricted access is not within the scope of `mc` - if you want to honor restricted API write your own code. `mc` is a user-friendly higher-level tool - with genuine reasons to require access to necessary APIs. 

I don't think it makes sense to add such niche fallback requirements for now. If this is very important to you feel free to write a tool yourself which satisfies your needs.
