### ISSUE TITLE
mc does not take into account passed config-dir and uses the default value

### ISSUE THREAD

**Issue by jhadjar** [minio/mc#3428]
## Expected behavior

Using `mc` with an arbitrary config-dir should return results as long as the path and config files are correct.

```bash
root@silver:/home/jugurtha# mc ls --config-dir /home/jugurtha/.mc --json miniosilver/pictures
{
 "status": "success",
 "type": "file",
 "lastModified": "2020-09-17T17:54:14.291+01:00",
 "size": 35148,
 "key": "COPYING",
 "etag": "99f786fb9c28b991dbfb88ab69af84eb",
 "url": "http://localhost:9000/pictures/",
 "versionOrdinal": 1
}
{
 "status": "success",
 "type": "folder",
 "lastModified": "2020-09-29T19:10:03.362316885+01:00",
 "size": 0,
 "key": "commons/",
 "etag": "",
 "url": "http://localhost:9000/pictures/",
 "versionOrdinal": 1
}
```

## Actual behavior

Instead, `mc` uses only the default `config-dir`. If running with user `root`, it will use `/root/.mc`. If running with user `jugurtha`, it will use `/home/.jugurtha`

```
root@silver:/home/jugurtha# mc ls --config-dir /home/jugurtha/.mc --json miniosilver/pictures
{
 "status": "error",
 "error": {
  "message": "Unable to list folder.",
  "cause": {
   "message": "Requested file `miniosilver` not found",
   "error": {
    "Path": "miniosilver"
   }
  },
  "type": "error",
  "sysinfo": {
   "host.arch": "amd64",
   "host.cpus": "12",
   "host.lang": "go1.14.7",
   "host.name": "silver",
   "host.os": "linux",
   "mem.heap.total": "66 MB",
   "mem.heap.used": "2.6 MB",
   "mem.total": "74 MB",
   "mem.used": "2.6 MB"
  }
 }
}
```

## Steps to reproduce the behavior

Run `mc` with another config directory. Example: as `root`, run `mc` with the config directory of the usual user.

## mc --version
- (paste output of `mc --version`)

```
mc version RELEASE.2020-09-23T20-02-13Z
```

## System information
```
Linux silver 5.8.0-20-generic #21-Ubuntu SMP Wed Sep 23 00:39:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Deployed MinIO with Docker image `minio/minio` with IMAGE ID: `aa416f912c09`

minio version:

```
minio version RELEASE.2020-09-26T03-44-56Z
```

**Comment by harshavardhana** [comment]
> ```shell
> root@silver:/home/jugurtha# mc ls --config-dir /home/jugurtha/.mc --json miniosilver/pictures
> ```

mc --config-dir /home/jugurtha/.mc --json ls miniosilver/pictures

**Comment by jhadjar** [comment]
> > ```shell
> > root@silver:/home/jugurtha# mc ls --config-dir /home/jugurtha/.mc --json miniosilver/pictures
> > ```
> 
> mc --config-dir /home/jugurtha/.mc --json ls miniosilver/pictures

My bad! Closing.

**Comment by jhadjar** [comment]
There are parts of the CLI help where this is unclear, for example:

```
  mc cp [FLAGS] SOURCE [SOURCE...] TARGET
```

FLAGS contains `config-dir`. Should we put `--config-dir` before or after, because the `--json` flag is working correctly.

If there is positional distinction between command flags and global flags, how to distinguish in cases like `mc` where the help states that the flags come _after_ `cp` (command)?

For reference, this is related to a Python wrapper for `mc`, and `minio` command line interfaces: https://big-mama-tech.gitlab.io/bmc/

**Comment by harshavardhana** [comment]
`--config-dir` should always be passed right after `mc` - it's not honored elsewhere, every other flag is honored everything.

**Comment by jhadjar** [comment]
Thank you again.
