### ISSUE TITLE
mc rm  doesn't delete buckets.

### ISSUE THREAD

**Issue by Win32Sector** [minio/mc#3441]
## Expected Behavior
mc rm --recursive --force --dangerous minio 
this command deletes recursively files and buckets

mc rb --force --dangerous minio
This command delertes empty buckets
## Current Behavior
first command deletes only files, second command doesn't delete buckets

## Your Environment

* Version used (`minio --version`): mc version RELEASE.2020-08-20T00-23-01Z
* Server setup and configuration: AKS

**Comment by harshavardhana** [comment]
Moved the issue here since its related to `mc`
