### ISSUE TITLE
provide '--compress' option for 'mc mirror' command

### ISSUE THREAD

**Issue by ylvmw** [minio/mc#3474]
This is a feature request. Could you provide the '--compress' option of 'mc mirror' command for in-transit compression, just like 'rsync' does? It is very useful for reducing the network overhead.

**Comment by harshavardhana** [comment]
You should compress first and then provide content to `mc mirror`.

**Comment by ylvmw** [comment]
> You should compress first and then provide content to `mc mirror`.

If I compress files first, could MINIO server decompress them on server side? You know, sometimes we need to keep them as the original.

**Comment by harshavardhana** [comment]
> If I compress files first, could MINIO server decompress them on server side? You know, sometimes we need to keep them as the original.

No we cannot @ylvmw all these are custom features MinIO cannot implement non-AWS S3 like features.

**Comment by ylvmw** [comment]
> > If I compress files first, could MINIO server decompress them on server side? You know, sometimes we need to keep them as the original.
> 
> No we cannot @ylvmw all these are custom features MinIO cannot implement non-AWS S3 like features without any prior internal requirement.

So it means that the server side doesn't support the decompression currently, right?

**Comment by klauspost** [comment]
@ylvmw You can enable transparent server compression of data. See https://github.com/minio/minio/tree/master/docs/compression#compression-guide-
