### ISSUE TITLE
mc is already used by Midnight Commander! Guys, pleas fix it,even you don't use this wonderful software :-E

### ISSUE THREAD

**Issue by vipup** [minio/mc#3477]
## Expected behavior
$ mc - should runs Midnight Commander, IS NOT some unknown software, in diff with minio
....
GNU Midnight Commander 4.8.19
...

## Actual behavior
# after test install minio my midniht commander not work anymore! give me a tipp... FTW!?

## Steps to reproduce the behavior
$ mv /usr/bin/mc /dev/null
$ apt install mc -y
 

## System information
$ uname -a
Linux master 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
https://github.com/minio/mc/blob/master/CONFLICT.md @vipup please read this

**Comment by andreyhammer** [comment]
Please correct this misunderstanding
You broke the unix world. This is disrespect to the developers of midnight commander and its users.  who decided to use this name? why didn't you use rm as the command name?
