### ISSUE TITLE
mc: <ERROR> Incorrect number of arguments for alias set command. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.

### ISSUE THREAD

**Issue by vipup** [minio/mc#3478]
## Expected behavior
https://central.portworx.com/tutorials/scenario/px-minio;title=Deploy%20Minio%20on%20Portworx%20volumes%20and%20use%20it%20for%20volume%20backups

## Actual behavior
wget -O /usr/bin/mc https://dl.minio.io/client/mc/release/linux-amd64/mc
chmod +x /usr/bin/mc
mc config host add px http://$MINIO_ENDPOINT myaccesskey mysecretkey S3v4
....
mc: <ERROR> Incorrect number of arguments for alias set command. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.

## Steps to reproduce the behavior
wget -O /usr/bin/mc https://dl.minio.io/client/mc/release/linux-amd64/mc
chmod +x /usr/bin/mc
mc config host add px http://$MINIO_ENDPOINT myaccesskey mysecretkey S3v4
....
mc: <ERROR> Incorrect number of arguments for alias set command. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.

## mc --version
mc version RELEASE.2020-10-03T02-54-56Z

## System information
https://central.portworx.com/tutorials/scenario/px-minio;title=Deploy%20Minio%20on%20Portworx%20volumes%20and%20use%20it%20for%20volume%20backups

**Comment by harshavardhana** [comment]
The docs referenced are old and outdated, use our docs to use the right CLI behavior.
