### ISSUE TITLE
"method GET is not implemented" with valid Cohesity bucket

### ISSUE THREAD

**Issue by razvan-ig** [minio/mc#3484]
## Expected behavior
List files.
The official AWS CLI works fine (ls ,cp, rm) with a command line like
`AWS_ACCESS_KEY_ID="a" AWS_SECRET_ACCESS_KEY="s" aws --endpoint-url "https://cohesity" --no-verify-ssl s3 ls s3://bucket/`

On another, identical (as far as I can tell), Cohesity instance we have around, mc works just fine all operations. The only difference, I am told, is instance that doesn't work uses server-side encryption.
To clarify, by "Cohesity" I mean https://www.cohesity.com/products/smartfiles/

## Actual behavior
minio-mc: <ERROR> Unable to list folder. HTTP method GET is not implemented

## Steps to reproduce the behavior
minio-mc --insecure ls cohesity/bucket/

## mc --version
minio-mc version RELEASE.2020-10-03T02-54-56Z

## System information
MacOS

**Comment by harshavardhana** [comment]
Provide mc --debug output

**Comment by razvan-ig** [comment]
> Provide mc --debug output

```
$ minio-mc --debug --insecure ls cohesity/bucket
minio-mc: <DEBUG> GET /bucket/?location= HTTP/1.1
Host: cohesity.local:3000
User-Agent: MinIO (darwin; amd64) minio-go/v7.0.6 minio-mc/2020-10-03T02:54:56Z
Authorization: AWS4-HMAC-SHA256 Credential=aaa/20201112/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20201112T085122Z
Accept-Encoding: gzip

minio-mc: <DEBUG> HTTP/1.1 501 Not Implemented
Content-Length: 180
Connection: keep-alive
Date: Thu, 12 Nov 2020 08:51:40 GMT
Server: CohesityS3

<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>NotImplemented</Code>
<Message>HTTP method GET is not implemented</Message>
<Resource>bucket</Resource>
</Error>
minio-mc: <DEBUG> TLS Certificate found:
minio-mc: <DEBUG>  >> Expires: 2021-10-09 23:59:59 +0000 UTC
minio-mc: <DEBUG> Response Time:  259.457762ms

minio-mc: <DEBUG> GET /bucket/?location= HTTP/1.1
Host: cohesity.local:3000
User-Agent: MinIO (darwin; amd64) minio-go/v7.0.6 minio-mc/2020-10-03T02:54:56Z
Authorization: AWS4-HMAC-SHA256 Credential=aaa/20201112/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20201112T085122Z
Accept-Encoding: gzip

minio-mc: <DEBUG> HTTP/1.1 501 Not Implemented
Content-Length: 180
Connection: keep-alive
Date: Thu, 12 Nov 2020 08:51:40 GMT
Server: CohesityS3

<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>NotImplemented</Code>
<Message>HTTP method GET is not implemented</Message>
<Resource>bucket</Resource>
</Error>
minio-mc: <DEBUG> TLS Certificate found:
minio-mc: <DEBUG>  >> Expires: 2021-10-09 23:59:59 +0000 UTC
minio-mc: <DEBUG> Response Time:  44.45176ms

minio-mc: <ERROR> Unable to list folder. HTTP method GET is not implemented
 (2) ls.go:216 cmd.doList(..) Tags: [https://cohesity.local:3000/bucket]
 (1) client-s3.go:2149 cmd.(*S3Client).listInRoutine(..) Tags: [bucket]
 (0) client-s3.go:2032 cmd.(*S3Client).bucketStat(..)
 Release-Tag:RELEASE.2020-10-03T02-54-56Z | Commit:f11ae85566fe | Host:maclon0255 | OS:darwin | Arch:amd64 | Lang:go1.14.9 | Mem:4.2 MB/74 MB | Heap:4.2 MB/66 MB
```

**Comment by harshavardhana** [comment]
> minio-mc: <DEBUG> GET /bucket/?location= HTTP/1.1
> Host: cohesity.local:3000
> User-Agent: MinIO (darwin; amd64) minio-go/v7.0.6 minio-mc/2020-10-03T02:54:56Z
> Authorization: AWS4-HMAC-SHA256 Credential=aaa/20201112/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> X-Amz-Date: 20201112T085122Z
> Accept-Encoding: gzip
> 
> minio-mc: <DEBUG> HTTP/1.1 501 Not Implemented
> Content-Length: 180
> Connection: keep-alive
> Date: Thu, 12 Nov 2020 08:51:40 GMT
> Server: CohesityS3
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <Error>
> <Code>NotImplemented</Code>
> <Message>HTTP method GET is not implemented</Message>
> <Resource>bucket</Resource>
> </Error>

Looks like Cohesity has not implemented full S3 compatibility `mc` works with fully S3 compatible services. Closing this issue its not a `mc` problem.
