### ISSUE TITLE
mc mirror Not removing empty buckets from root

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3485]
Hello,
It looks like mc mirror does not properly mirror the directory state, i've tested 2 scenarios.

*Scenario 1 EMPTY Directory*
user@debian:~$ ls -l junk/
total 0
user@debian:~$ mc mirror -a --remove --overwrite junk/ as
 0 B / ? 
suser@debian:~$ mc mirror -a --remove --overwrite junk/ as/
 0 B / ? 
suser@debian:~$ mc mirror --remove --overwrite junk/ as/
 0 B / ? 
suser@debian:~$ mc mirror --remove --overwrite junk/ as

suser@debian:~$ mc ls as | wc -l
16

In this case mc did not delete the buckets from, hence local folder folder has 0 items, but remote host still has 16 buckets

*Scenario 2*
With the same file structure as above, adding a subfolder into junk folder, creates a new bucket on the remote minio server, but does not remove the other erroneous buckets.

Thanks

mc version RELEASE.2020-10-03T02-54-56Z
minio    Version: 2020-10-28T08:16:50Z

**Comment by harshavardhana** [comment]
`mc mirror` won't remove buckets

**Comment by i0x71** [comment]
How can you do a proper mirror sync if it will not remove buckets ?

**Comment by harshavardhana** [comment]
> How can you do a proper mirror sync if it will not remove buckets ?

It will only remove objects @i0x71 we cannot remove buckets, this is per design.

**Comment by harshavardhana** [comment]
Buckets are like volumes they cannot be willy nilly deleted and recreated at whim, it may be what you want but that is not `mc mirror`' purpose. 

If you want this feature you may have to fork `mc` and add it on your own.

**Comment by i0x71** [comment]
Do you mean to say it will not remove root buckets ? Because it definitely removes buckets within buckets.

**Comment by i0x71** [comment]
Or are buckets inside of other buckets considered objects ?

**Comment by harshavardhana** [comment]
> Do you mean to say it will not remove root buckets ? Because it definitely removes buckets within buckets.

Those are not buckets they are directories or prefixes.

**Comment by i0x71** [comment]
Got it thanks, another thing to clarify, i noticed that mirror will not create empty directories on the remote end, is that expected as well ?

**Comment by harshavardhana** [comment]
> Got it thanks, another thing to clarify, i noticed that mirror will not create empty directories on the remote end, is that expected as well ?

yes @i0x71
