### ISSUE TITLE
mc should not rely on the extension to detect whether a file is json or not

### ISSUE THREAD

**Issue by AntonOfTheWoods** [minio/mc#3489]
## Expected behavior
`mc` should attempt to load (or at least peek) the file before rejecting it, rather than looking at the extension. It should not rely on the extension to believe a file is json.

## Actual behavior
`mc` rejects a perfectly valid json file with a non-".json" extension

## Steps to reproduce the behavior
`mv myconf.json myconf.json.stillgood`
`mc policy set-json myconf.json.stillgood myminio/mybucket`

## mc --version
- (paste output of `mc --version`)
`mc version RELEASE.2020-10-03T02-54-56Z`

## System information
Ubuntu 20.04

**Comment by harshavardhana** [comment]
You are free to set the content-type using `--attr` values @AntonOfTheWoods - `mc` is doing the best effort for most common scenarios. 

You wouldn't name a perfectly valid JSON file as `myfavorite.tar.gz`

**Comment by harshavardhana** [comment]
My mistake looks like our set-json is looking for silly extensions.
