### ISSUE TITLE
Object versions under a DELete marker can be removed

### ISSUE THREAD

**Issue by ebozduman** [minio/mc#3496]
## Expected behavior
Not sure if DELete marker should have been deleted together with the last object version deletion, but dangling DELete marker doesn't make sense at all. I'll check AWS S3 behavior and add it in this issue.

## Actual behavior
A dangling DELete marker is left behind.

## Steps to reproduce the behavior

```
$ mc cp --retention-mode governance --retention-duration 1d /etc/issue mm1/source/issue-copy
/etc/issue:                26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 253 B/s 0s
$ mc ls --versions mm1/source/
[2020-11-18 22:59:39 PST]    26B 2c325fa6-b884-43fe-96d6-6e14b22626b4 v1 PUT issue-copy
$ mc retention info --versions mm1/source/issue-copy 
[     GOVERNANCE     ]  2c325fa6-b884-43fe-96d6-6e14b22626b4  mm1/source/issue-copy
$ mc rm mm1/source/issue-copy --bypass
Removing `mm1/source/issue-copy`.
$ mc ls --versions mm1/source/
[2020-11-18 23:03:14 PST]     0B b9b76b28-16f6-4895-a9c6-f14e3a5a9ce1 v2 DEL issue-copy
[2020-11-18 22:59:39 PST]    26B 2c325fa6-b884-43fe-96d6-6e14b22626b4 v1 PUT issue-copy
$ mc rm mm1/source/issue-copy --bypass --vid 2c325fa6-b884-43fe-96d6-6e14b22626b4
Removing `mm1/source/issue-copy` (versionId=2c325fa6-b884-43fe-96d6-6e14b22626b4).
$ mc ls --versions mm1/source/
[2020-11-18 23:03:14 PST]     0B b9b76b28-16f6-4895-a9c6-f14e3a5a9ce1 v1 DEL issue-copy
```

## mc --version
DEVELOPMENT.2020-11-19T04-38-54Z

**Comment by harshavardhana** [comment]
> Not sure if DELete marker should have been deleted together with the last object version deletion, but dangling DELete marker doesn't make sense at all. I'll check AWS S3 behavior and add it in this issue.

Delete marker needs to be individually deleted @ebozduman - delete markers do not get purged on their own. All versions need to be deleted separately as per AWS S3 spec.
