### ISSUE TITLE
Recursively deleted objects from all buckets if bucket name not specified

### ISSUE THREAD

**Issue by miron9** [minio/mc#3497]
## Expected behavior
I just ran this command
`$ mc rm --recursive --force --dangerous s3/$BUCEKT/`
As you can see the bucket variable is misspelled and therefore what got executed was
`$ mc rm --recursive --force --dangerous s3//`
Which resulted in deletion of objects across multiple buckets in this AWS account. A not very happy place to be in to say at least.

I would expect that recursive deletion doesn't work if there is no existing bucket specified.
## Actual behavior
Object in all buckets in the account get removed.

## Steps to reproduce the behavior
Just run this again and better have a backup copy of all buckets in the account:
`$ mc rm --recursive --force --dangerous s3//`

## mc --version
mc version RELEASE.2020-11-17T00-39-14Z

## System information
N/A

**Comment by poornas** [comment]
The shell interprets `$BUCEKT` prior to passing it to mc - since this variable was not set in the env, it was substituted as empty var and executed `mc rm --recursive --force --dangerous s3//`. 

You can pass a --fake flag to `mc rm` to do a dry run to check what will be deleted prior to actually executing the operation.

**Comment by miron9** [comment]
Thanks guys for your replies but I know what happened to my data. What I'm arguing here is that it should not recursively got thorough all buckets if no bucket name is specified or at least not without explicit argument passed on to it. The `--dangerous` doesn't inform me about this behavior. I would recommend renaming this options or adding another one like "--all-buckets" ot something. 
Kind regards
