### ISSUE TITLE
mc admin trace missing client info in ipv6

### ISSUE THREAD

**Issue by armsby** [minio/mc#3500]
## Expected behavior
that I would see the full IPv6 address of the client not only the first segment

## Actual behavior
I only see the first segment, witch makes it useless

## Steps to reproduce the behavior
simple trace mc admin trace --json 
## mc --version
mc version RELEASE.2020-11-17T00-39-14Z

{
 "status": "success",
 "host": "minio",
 "time": "2020-11-24T17:10:06.901280106Z",
 "client": "216.18.217.130",
 "callStats": {
  "rx": 190,
  "tx": 1041,
  "duration": 6879148,
  "timeToFirstByte": 0
 },
 "api": "s3.ListObjectsV1",
 "path": "/folder",
 "query": "delimiter=%2F&encoding-type=url&max-keys=1000&prefix="",
 "statusCode": 200,
 "statusMsg": "OK"
}

{
 "status": "success",
 "host": "minio",
 "time": "2020-11-24T17:10:06.903212944Z",
 "client": "2a0e",
 "callStats": {
  "rx": 190,
  "tx": 1041,
  "duration": 6879148,
  "timeToFirstByte": 0
 },
 "api": "s3.ListObjectsV1",
 "path": "/folder",
 "query": "delimiter=%2F&encoding-type=url&max-keys=1000&prefix=",
 "statusCode": 200,
 "statusMsg": "OK"
}

**Comment by harshavardhana** [comment]
@armsby Trace functionality was never supported on ipv6, there is a server side fix needed here.

**Comment by armsby** [comment]
ok, I will have to find another way of locating my problem users then

**Comment by poornas** [comment]
fixed by https://github.com/minio/mc/pull/3661
