### ISSUE TITLE
mc: <ERROR> Unable to update the server. We encountered an internal error, please try again. 

### ISSUE THREAD

**Issue by tomsozolins** [minio/mc#3507]
Hello!

When i try to update MinIO using MC client using command:
`mc admin update X`

I get the following error:
`mc: <ERROR> Unable to update the server. We encountered an internal error, please try again. (Server update failed, please do not restart the servers yet: failed with rename /usr/local/bin/.minio.old /usr/local/bin/..minio.old.old: no such file or directory)`

![image](https://user-images.githubusercontent.com/48243828/100335125-4a8d8a80-2fdd-11eb-9fa1-92459f69e27f.png)
![image](https://user-images.githubusercontent.com/48243828/100335078-3a75ab00-2fdd-11eb-991d-ea39b05c3e31.png)

**Comment by vadmeste** [comment]
@tomsozolins could you paste your MinIO server version and mc version ?

**Comment by tomsozolins** [comment]
`mc version RELEASE.2020-11-25T23-04-07Z`
`RELEASE.2020-11-19T23-48-16Z`

I updated MinIO manually, because of the problem and it updated without problem:
`rm -f /usr/local/bin/minio && wget https://dl.minio.io/server/minio/release/linux-amd64/minio -P /usr/local/bin/ && sudo chmod +x /usr/local/bin/minio && sudo chown -R minio:minio /usr/local/bin/minio && systemctl restart minio`

**Comment by vadmeste** [comment]
Could you paste ls -la /usr/local/bin/ | grep minio` ?

**Comment by harshavardhana** [comment]
> `mc: <ERROR> Unable to update the server. We encountered an internal error, please try again. (Server update failed, please do not restart the servers yet: failed with rename /usr/local/bin/.minio.old /usr/local/bin/..minio.old.old: no such file or directory)`

The issue here is write access is not present at /usr/local/bin - in such a scenario just replace the binaries manually.

**Comment by tomsozolins** [comment]
> Could you paste ls -la /usr/local/bin/ | grep minio` ?

![image](https://user-images.githubusercontent.com/48243828/100345626-41a3b580-2feb-11eb-9f6a-3b9bd1acf02a.png)

**Comment by klauspost** [comment]
@harshavardhana Could this be several servers running from the same directory?

**Comment by tomsozolins** [comment]
> @harshavardhana Could this be several servers running from the same directory?

No. There are 8 servers, each running single minio process.

**Comment by melsom** [comment]
Hello,

We are experiencing the same thing. Running 9 servers in a distributed setup. Any help?

mc version:  RELEASE.2021-09-23T05-44-03Z

mc: <DEBUG> HTTP/1.1 500 Internal Server Error
Content-Length: 392
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Thu, 23 Sep 2021 12:34:15 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: no-XXXX-1
X-Amz-Request-Id: 16A772BA87E26C0D
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

{"Code":"InternalError","Message":"We encountered an internal error, please try again. (Server update failed, please do not restart the servers yet: failed with rename /usr/local/bin/.minio.old /usr/local/bin/..minio.old.old: no such file or directory)","Resource":"/minio/admin/v3/update","Region":"no-south-1","RequestId":"16A772BA87E26C0D","HostId":"bbd7798b-f730-401a-b5eb-38e7a3a5a980"}
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Let's Encrypt
mc: <DEBUG>  >> Expires: 2021-10-25 13:13:35 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Internet Security Research Group
mc: <DEBUG>  >> Expires: 2025-09-15 16:00:00 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Organization: Digital Signature Trust Co.
mc: <DEBUG>  >> Expires: 2024-09-30 18:14:03 +0000 UTC
mc: <DEBUG> Response Time:  15m19.715656275s

**Comment by vadmeste** [comment]
@melsom can you tell us what's your current MinIO version ?

**Comment by melsom** [comment]
@vadmeste The version is: RELEASE.2021-08-25T00-41-18Z

Across all servers.

**Comment by alexanderankin** [comment]
commands for doing this inside a docker container:

get inside the container

```bash
container_name=minio # e.g.
docker exec -it $container_name bash
```

run inside docker 

```bash
MINIO_FILE=/opt/bin/minio # defined by docker image
rm -f $MINIO_FILE && \
 curl https://dl.minio.io/server/minio/release/linux-amd64/minio --output $MINIO_FILE && \
 chmod +x $MINIO_FILE
```

then restart the container.

beware that this can lose data. i didn't lose my files but lost my roles and users.
