### ISSUE TITLE
'mc ls <path>' does not honor backslash at the end of path on Windows

### ISSUE THREAD

**Issue by racinmat** [minio/mc#3509]
On windows, minio client includes \ at the end of each directory listed by `mc --insecure ls <alias>/<bucket>`.

This causes lots of complications , e.g. I can't use the name of directory directly to list it's contents, e.g.
```
> mc ls play/zzzz\
> mc ls play/zzzz
[2020-11-26 08:20:21 CET]   21KiB ll.jpg
> mc ls play/zzzz/
[2020-11-26 08:20:21 CET]   21KiB ll.jpg
```
or
```
> mc ls play/testaaa
[2020-11-27 17:01:08 CET]      0B jenkins\
```
and I can't use `> mc ls play/testaaa/jenkins\`
because
```
> mc ls play/testaaa/jenkins\
mc.exe: <ERROR> Unable to list folder. Object name contains unsupported characters.
```

## Expected behavior
Expected behavior is to either not include the slash at the end of directory at all, on all platforms, or to be consistent with linux behavior and return `/` even on windows.
E.g. 
```
> mc ls play/testaaa
[2020-11-27 17:01:08 CET]      0B jenkins/
```
or 
```
> mc ls play/testaaa
[2020-11-27 17:01:08 CET]      0B jenkins
```

## Actual behavior
returning backslack at end of directory names, e.g. this
```
> mc ls play/testaaa
[2020-11-27 17:01:08 CET]      0B jenkins\
```

## Steps to reproduce the behavior

1. Run `mc ls play/testaaa` or any other example on windows using the minio client `mc.exe`

## mc --version
- mc version RELEASE.2020-09-18T00-13-21Z

## System information
Windows 10 Enterprise, Version 10.0.19041 Build 19041

**Comment by racinmat** [comment]
Has this been fixed? If not, why should it be closed?

**Comment by ebozduman** [comment]
@racinmat ,

Yes. There is a PR ready for review and we have 1 approval, but need 2 for the fix to be merged. 
I pinged the reviewer to take a look and finish his review.

**Comment by racinmat** [comment]
Please, don't close it. Doesn't anyone with approval privileges have time to take a look at it?

**Comment by ebozduman** [comment]
@vadmeste 
PTAL!

**Comment by racinmat** [comment]
Please, don't close it. Doesn't anyone with approval privileges have time to take a look at it?

**Comment by harshavardhana** [comment]
> Please, don't close it. Doesn't anyone with approval privileges have time to take a look at it?

No we do not @racinmat

**Comment by ebozduman** [comment]
@racinmat,
Sorry for having the issue keep slipping through the cracks.
It  looks like we have enough approvals now.
So, it is ready to be merged. 
Thanks for your patience,

**Comment by racinmat** [comment]
Thanks much.
