### ISSUE TITLE
mc checksum files content is not the one expected

### ISSUE THREAD

**Issue by sylvainOL** [minio/mc#3516]
## Expected behavior

```shell
$ curl -s https://dl.min.io/client/mc/release/linux-amd64/archive/mc.sha256sum
985c43f9bec8fdc4ef2ee44c63c9657e10c4cfeb5cb949179d6d693f7428c314 mc
$ curl -s https://dl.min.io/client/mc/release/linux-amd64/archive/mc.shasum
67bee8cfa2bf540e06d75edbd6b757bd4243b337 mc
```

## Actual behavior

```shell
$ curl -s https://dl.min.io/client/mc/release/linux-amd64/archive/mc.sha256sum
985c43f9bec8fdc4ef2ee44c63c9657e10c4cfeb5cb949179d6d693f7428c314 mc.RELEASE.2020-11-25T23-04-07Z
$ curl -s https://dl.min.io/client/mc/release/linux-amd64/archive/mc.shasum
67bee8cfa2bf540e06d75edbd6b757bd4243b337 mc.RELEASE.2020-11-25T23-04-07Z
```

I've rapidly check other releases (window, linux-arm, ...) and the problem is everywhere

**Comment by harshavardhana** [comment]
The actual file for you to download is `mc.RELEASE.2020-11-25T23-04-07Z` not `mc` so always download the right released ones 


Download the binary named and their corresponding files

- mc.RELEASE.2020-11-25T23-04-07Z
- mc.RELEASE.2020-11-25T23-04-07Z.sha256sum

**Comment by sylvainOL** [comment]
Hello,
I don't agree with you.
If you give a `https://dl.min.io/client/mc/release/linux-amd64/archive/mc.sha256sum`, it should be there to give sha256 of `mc`, especially as we don't know simply the release name...

So, either you don't give checksums for `mc`, either you give a valid file...

**Comment by harshavardhana** [comment]
> If you give a `https://dl.min.io/client/mc/release/linux-amd64/archive/mc.sha256sum`, it should be there to give sha256 of `mc`, especially as we don't know simply the release name...

You don't have to agree with me, @sylvainOL that doesn't change anything here. 

`mc` and `mc.RELEASE*` both binaries are the same. Ideally, you want to download the right release not blindly `archive/mc` it is kept like this on purpose. This is the way it is going to be so use it accordingly.

**Comment by sylvainOL** [comment]
so @harshavardhana, how do I see the release name before downloading?
I wanted to use ansible `get_url` task (which can check for sha256 before downloading) but :
* I don't know how to get the latest release name (`mc.RELEASE*`) (no file to download which will give the lates download name)
* if I use `mc`, I don't have a well formed sha256 file :(

So I'll download the binary every time which is time consuming and really suboptimal.

**Comment by harshavardhana** [comment]
```bash

MC_VERSION=$(curl --retry 10 -Ls -o /dev/null -w "%{url_effective}" https://github.com/minio/mc/releases/latest | sed "s/https:\/\/github.com\/minio\/mc\/releases\/tag\///")
if [ -z "$MC_VERSION" ]; then
    echo "unable to get mc version from github"
    exit 1
fi

$WGET --output-document="${test_run_dir}/mc" "https://dl.minio.io/client/mc/release/linux-amd64/mc.${MC_VERSION}"
chmod a+x "${test_run_dir}/mc"
```
