### ISSUE TITLE
mc default config path is not hardcoded

### ISSUE THREAD

**Issue by c33s** [minio/mc#3519]
## Expected behavior
it does not matter what the name of `mc` is, the config is hardcoded

## Actual behavior
mc looks up its default config by its own filename. if you rename `mc` to `minioc` you loose all your previous settings which are located `C:\Users\myuser\mc\config.json` but mc now looks under `C:\Users\myuser\minoc\config.json` (is there an environment variable for setting the config dir? i really miss a doc section with a list of all env variables)

## Steps to reproduce the behavior
```
mc alias set mys3 https://s3.amazonaws.com BKIKJAA5BMMU2RHO6IBB V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12
mc cp foo.txt mys3/mybucket
mv mc minoc # works
minioc cp foo2.txt mys3/mybucket #this fails
```

## mc --version
- RELEASE.2020-10-03T02-54-56Z

## System information
- windows

**Comment by harshavardhana** [comment]
> ```
> minioc cp foo2.txt mys3/mybucket #this fails
> ```

@c33s this is meant to provide `mc` to be repackaged as another binary name - so the config path defaults to the binary name.  If you change binary name it is expected to look for the correct config directory.

**Comment by c33s** [comment]
not sure if this behavior is the best UX. as i wrote above `mc` conflicts in debian with an existing package name. does it make sense to change the config directory people are familar with, with is also in documentations and so on, just because of renaming the file was required? if i rename my `composer.phar` to `c.phar` it doesn't suddenly change it's config path to something else.

but just sharing thoughts here. i personally had a "bad" UX with this behavior and looked for a bug as suddenly all my configs where gone.

btw this behavior is not consistent in all locations:
```
mi config add
mi: <ERROR> `add` is not a mc command. See `mc --help`.
```

**Comment by harshavardhana** [comment]
> mi config add
> mi: <ERROR> `add` is not a mc command. See `mc --help`.

that is because of hardcoded values that needs to be fixed. @c33s - those are legitimate cases to fix.

**Comment by harshavardhana** [comment]
In-fact already fixed in master 

```
~ ./mcli add config
mcli: <ERROR> `add` is not a recognized command. Get help using `--help` flag. 
```
