### ISSUE TITLE
Feature request: command `url` for quickly getting the public url of a file

### ISSUE THREAD

**Issue by c33s** [minio/mc#3520]
would be nice to have a feature to get the url for a given file.

`mc url myserver/mybucket/path/foo.txt` -> `https://example.com/mybucket/path/file.txt` for easy sharing public files on the command line. 
would maybe require a server config to define the external domain of minio

edit:
handy would also be a url flag for other commands
```
mc cp ssl-cert-check myserver/public --url
ssl-cert-check:                            33.68 KiB / 33.68 KiB [===============================] 167.55 KiB/s 0s
https://minio.example.com/public/ssl-cert-check
```

**Comment by kannappanr** [comment]
@c33s We have this available as part of `ls` command output

```
mc ls play/phh/file1 --json
{
 "status": "success",
 "type": "file",
 "lastModified": "2021-01-27T23:46:35.765-08:00",
 "size": 1631,
 "key": "file1",
 "etag": "a08b59b9877dd9cb750893039e2d9593",
 "url": "https://play.min.io/phh/file1",
 "versionOrdinal": 1
}
```
