### ISSUE TITLE
Feature request: mc mrrior provides option like "not-delete-target" when watching

### ISSUE THREAD

**Issue by inforly** [minio/mc#3523]
Is it possible that mc mirror provides an option like like "not-delete-target" when watching? It means that even we delete files on source, mc will not delete them on target. It is really needed on some scenarios like we only want to transfer files from source to target continuously.

**Comment by vadmeste** [comment]
@inforly mc mirror should not delete objects in target unless you pass --remove flag. 

Are you seeing an issue ? Could you describe how to reproduce ?

**Comment by inforly** [comment]
> @inforly mc mirror should not delete objects in target unless you pass --remove flag.
> 
> Are you seeing an issue ? Could you describe how to reproduce ?

Just run the command like `mc mirror ./local minio/bucket -w -q`, then delete some files on the local directory, the files in the minio bucket also be deleted.

**Comment by harshavardhana** [comment]
> > @inforly mc mirror should not delete objects in target unless you pass --remove flag.
> > Are you seeing an issue ? Could you describe how to reproduce ?
> 
> Just run the command like `mc mirror ./local minio/bucket -w -q`, then delete some files on the local directory, the files in the minio bucket also be deleted.

This is because @vadmeste `mc mirror --watch` also runs as active-active mode

**Comment by vadmeste** [comment]
> This is because @vadmeste `mc mirror --watch` also runs as active-active mode

ohh correct, I still don't see clearly why we have both --watch --active-active flags
