### ISSUE TITLE
mc mirror -w failed due to "too many open files" error

### ISSUE THREAD

**Issue by inforly** [minio/mc#3524]
## Expected behavior
`mc mirror -w` should work properly

## Actual behavior
mc failed with the error:
...
mc: <ERROR> Failed to copy `.../go/src/github.com/minio/mc/cmd/head-main.go`. open .../go/src/github.com/minio/mc/cmd/head-main.go: too many open files

## Steps to reproduce the behavior
run: `mc mirror ./cmd minio/test -w -q` on mac

## mc --version
mc version RELEASE.2020-10-03T02-54-56Z

Only found the bug on this version, but not found on version RELEASE.2020-10-03T02-54-56Z 

## System information
macOS 10.13.6

**Comment by harshavardhana** [comment]
what is your `ulimit -n` @inforly ?

**Comment by inforly** [comment]
> ulimit -n

It is 256. But on the same mac machine, RELEASE.2020-10-03T02-54-56Z have no such issue.

**Comment by harshavardhana** [comment]
> > ulimit -n
> 
> It is 256. But on the same mac machine, RELEASE.2020-10-03T02-54-56Z have no such issue.

256 is too low for anything meaningful for `mc mirror` to perform its copy operations, if you want to restrict concurrency then you can set GOMAXPROCS=32 

I don't think there is any bug here @inforly

**Comment by inforly** [comment]
> > > ulimit -n
> > 
> > 
> > It is 256. But on the same mac machine, RELEASE.2020-10-03T02-54-56Z have no such issue.
> 
> 256 is too low for anything meaningful for `mc mirror` to perform its copy operations, if you want to restrict concurrency then you can set GOMAXPROCS=32
> 
> I don't think there is any bug here @inforly

256 is the default value of my Mac machine. mc need to keep itself running normally even you think the value is low rather than failed, right?
I also tried your way ```GOMAXPROCS=1 ./mc mirror ./cmd minio/120712 -w -q```, the command is right? Only GOMAXPROCS=1 worked, all other values > 1 failed.
