### ISSUE TITLE
Copying or listing paths without appending slash

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3527]
Hi,
Are there any docs or something that explain the premise of having to include "/" at the end of the path when using mc cp

For example:
i0x71@debian:~/crap$ mc ls dot9/sys/pkg/clusterBuilder
[2020-12-08 11:21:42 EST]     0B clusterBuilder/
i0x71@debian:~/crap$ mc ls dot9/sys/pkg/clusterBuilder/ | wc -l
7
i0x71@debian:~/crap$ mc cp dot9/sys/pkg/clusterBuilder .
**mc: <ERROR> Unable to validate source `dot9/sys/pkg/clusterBuilder`.**

I think in this case the error doesnt really make sense.
In addition this prevents you from copying the folder entirely and instead you have to create the folder with mkdir and then use the path with / appended to copy the folder contents.

Wouldn't it make more sense to somewhat resemble behaviour of standard tools like ls, since the whole premise of mc is let user navigate folder trees and interact with files ?

Thanks

mc version RELEASE.2020-11-25T23-04-07Z
minio 2020-12-03T05:49:24Z

**Comment by harshavardhana** [comment]
> i0x71@debian:~/crap$ mc cp dot9/sys/pkg/clusterBuilder .
> **mc: Unable to validate source `dot9/sys/pkg/clusterBuilder`.**

arent' you supposed to use `mc cp -r` here? @i0x71

**Comment by i0x71** [comment]
Usually when you are missing -r it complains that it cannot copy recursively, but in this case it produces the same error as above

i0x71@debian:~/blah$ mc cp -r dot9/sys/pkg/clusterBuilder .
mc: <ERROR> Unable to validate source `dot9/sys/pkg/clusterBuilder`.

**Comment by harshavardhana** [comment]
> Usually when you are missing -r it complains that it cannot copy recursively, but in this case it produces the same error as above

Correct that looks like a bug recently introduced somewhere

**Comment by vadmeste** [comment]
@i0x71 so to summarize, are you saying that mc should show a better error message when you copy a directory without --recursive flag ? That's already fixed anyway.

**Comment by ebozduman** [comment]
> That's already fixed anyway.

@vadmeste 
What fix did you refer to?

**Comment by vadmeste** [comment]
> What fix did you refer to?

As I tested in master, `mc cp dot9/sys/pkg/clusterBuilder .` shows now that the user needs to pass --recursive flag if he needs to copy a directory.

**Comment by ebozduman** [comment]
@i0x71 ,

This is already fixed.

```
 $ mc tree -f mm1/zzz/pre/fix
mm1/zzz/pre/fix
├─ file
├─ test1
└─ test2
$
$ mc cp mm1/zzz/pre/fix/ .
mc: <ERROR> To copy a folder requires --recursive flag. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.
$
$ mc cp -r mm1/zzz/pre/fix .
...zzz/pre/fix/test1:  78 B / 78 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 1.24 KiB/s 0s
$ 
$ ls fix
file  test1  test2
```
