### ISSUE TITLE
mc not keeping permissions

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3528]
It looks like in my case mc is not keeping the exec permissions, not sure about the other permissions as i havent tested that.

i0x71@debian:~/blah$ ls -l
total 0
**-rwxr-xr-x 1 i0x71 i0x71 0 Dec  8 11:41 test**
i0x71@debian:~/blah$ mc cp test dot9/blah/test
test:          0 B / ?
i0x71@debian:~/blah$ rm test
i0x71@debian:~/blah$ mc cp -r dot9/blah/ .
 0 B / ? 
i0x71@debian:~/blah$ ls -l
total 0
**-rw-r--r-- 1 i0x71 i0x71 0 Dec  8 11:42 test**

mc version RELEASE.2020-11-25T23-04-07Z
minio 2020-12-03T05:49:24Z

**Comment by harshavardhana** [comment]
mc cp -a @i0x71

**Comment by i0x71** [comment]
Ah my bad, would it make sense to "assume" -a when copying to minio server, as one missed flag when "uploading" will cause alot of greef when getting the files back as all the permissions will be messed up.

**Comment by harshavardhana** [comment]
> Ah my bad, would it make sense to "assume" -a when copying to minio server, as one missed flag when "uploading" will cause alot of greef when getting the files back as all the permissions will be messed up.

Correct without -a @i0x71 it's not preserved, that is the entire reason for this option. 

>   --preserve, -a                     preserve filesystem attributes (mode, ownership, timestamps)

**Comment by i0x71** [comment]
Much appreciated!
