### ISSUE TITLE
Copying large files is slow and never ends 

### ISSUE THREAD

**Issue by michaeleekk** [minio/mc#3530]
## Expected behavior
After transferring 40GB of data and the loading bar is finished, the process should be ended.

## Actual behavior
The loading bar is finished but the process still hadn't ended.

## Steps to reproduce the behavior
1. `mc cp * minio/datasets` to transfer 40GB of files on the same machine as the Minio server
1. The first 3GB is super fast, and then dropped to ~15MB/s
1. After the loading bar is finished, the process is still loading, and the machine load average in `top` is >30

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2020-11-25T23-04-07Z
## System information
`uname -a`
Linux machine-1 5.8.0-28-generic #30-Ubuntu SMP Thu Nov 5 13:24:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Minio is inside k3s having the storage on a OpenEBS ZFS provisioner.

`mc` process used around 3GB memory during the transfer.

**Comment by jess-sch** [comment]
I'm experiencing a similar issue with recursive copying of a ~60GB directory (each file is ~2GB) from local storage to a MinIO server (single node, bare metal on an LVM block device).

After ~7.5GB it's dropped to ~13MiB, initially it was 60-70.

When I use mc to copy the files individually, it's fast.

**Comment by vadmeste** [comment]
@michaeleekk are you using minio server standalone FS mode ?

**Comment by thelittlebug** [comment]
same issue here. seems to be a memory leak. mc grows up to 30gbyte of ram and gets killed```
root@druid-master-0:~# ./mc cp -r station s3c/druid
...368662400.csv:  14.11 GiB / 73.98 GiB ┃▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃ 909.72 MiB/sKilled
```
and here the last lines from pmap```
00007f63571c8000    508K -----   [ anon ]
00007f6357247000    384K rw---   [ anon ]
00007ffdd96fc000    132K rw---   [ stack ]
00007ffdd9772000     12K r----   [ anon ]
00007ffdd9775000      4K r-x--   [ anon ]
ffffffffff600000      4K --x--   [ anon ]
 total         30155896K

**Comment by harshavardhana** [comment]
> same issue here. seems to be a memory leak. mc grows up to 30gbyte of ram and gets killed
> 
> root@druid-master-0:~# ./mc cp -r station s3c/druid
> ...368662400.csv: 14.11 GiB / 73.98 GiB ┃▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃ 909.72 MiB/sKilled
> 
> and here the last lines from pmap
> 00007f63571c8000 508K ----- [ anon ]
> 00007f6357247000 384K rw--- [ anon ]
> 00007ffdd96fc000 132K rw--- [ stack ]
> 00007ffdd9772000 12K r---- [ anon ]
> 00007ffdd9775000 4K r-x-- [ anon ]
> ffffffffff600000 4K --x-- [ anon ]
> total 30155896K

Set GOGC=25 or GOMAXPROCS=4 or something to reduce the overall memory usage.

**Comment by vadmeste** [comment]
@jess-sch is this a FS or erasure coding ? (how many disks do you use in you setup ?)

**Comment by jess-sch** [comment]
> @jess-sch is this a FS or erasure coding ? (how many disks do you use in you setup ?)

Sorry for the late reply. It was two disks running in LVM RAID1. The logical volume used the ext4 file system. I didn't set up any erasure coding.

**Comment by harshavardhana** [comment]
> > @jess-sch is this a FS or erasure coding ? (how many disks do you use in you setup ?)
> 
> Sorry for the late reply. It was two disks running in LVM RAID1. The logical volume used the ext4 file system. I didn't set up any erasure coding.

Then its expected FS mode concatenates objects at the end. You should use erasure coding for faster uploads of large objects.
