### ISSUE TITLE
mc diff display different state of file in the replicated bucket

### ISSUE THREAD

**Issue by pavel-z1** [minio/mc#3532]
## Expected behavior

New file in the replicated buckets must be shown as the same file by `mc diff`

## Actual behavior

I have two minio clusters and buckets with name "test" on both minio clusters.

For bucket "test" configured two way replication (active-active) between minio1 and minio2 clusters.
After upload new file to the cluster minio1 file replicated by minio to the cluster minio2.
After that `mc diff` show different information for the same file, when I check from both clusters:
```
[root@minio2]# mc diff minio2/test minio1/test
[root@minio2]#
```
```
[root@minio1]# mc diff minio1/test minio2/test
! http://minio1-host1/test/test.txt
```

At the same time stat information for this file identical on both clusters:
```
[root@minio1]# mc stat minio1/test/test.txt
Name      : test.txt
Date      : 2020-12-15 12:22:05 CET
Size      : 10 B
ETag      : 248f606636cd34d90cd775ff9b7cc6b8
VersionID : b77b67a9-674f-4090-a201-dae72635f648
Type      : file
Metadata  :
  Content-Type: text/plain
Replication Status: COMPLETE

[root@minio2]# mc stat minio2/test/test.txt
Name      : test.txt
Date      : 2020-12-15 12:22:05 CET
Size      : 10 B
ETag      : 248f606636cd34d90cd775ff9b7cc6b8
VersionID : b77b67a9-674f-4090-a201-dae72635f648
Type      : file
Metadata  :
  Content-Type: text/plain
Replication Status: REPLICA
```

And diff in the JSON format:
```
[root@minio1]# mc stat --json minio1/test/test.txt
[root@minio1]# mc diff --json minio1/test minio2/test
{
 "status": "success",
 "first": "http://minio1:9000/test/test.txt",
 "second": "http://minio2/test/test.txt",
 "diff": 7
}
```

## Steps to reproduce the behavior

1. Create two minio clusters
2. Create bucket with name "test" on both clusters
3. Configure replication from minio1/test to minio2/test
4. Configure replication from minio2/test to minio1/test
5. Upload file to the minio1/test
6. Check diiff with command `mc diff minio2/test/filename`

## mc --version
```
[root@minio1]# mc --version
mc version RELEASE.2020-12-10T01-26-17Z

[root@minio2]# mc --version
mc version RELEASE.2020-12-10T01-26-17Z
```

## System information
On both servers system software is identical:
```
[root@minio1]# cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)

[root@minio1]# uname -r
4.18.0-193.14.2.el8_2.x86_64

[root@minio1]# docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                 PORTS               NAMES
6e8e7e0a93c7        minio/minio:RELEASE.2020-12-12T08-39-07Z   "/usr/bin/docker-ent…"   4 hours ago         Up 4 hours (healthy)                       minio_server
```

**Comment by vadmeste** [comment]
@pavel-z1 thanks, I am able to reproduce this. I should be able to send a fix soon.

**Comment by pavel-z1** [comment]
Hi @harshavardhana 
Do you have any information when this fix will be in the release of the mini mc?

**Comment by harshavardhana** [comment]
> Hi @harshavardhana
> Do you have any information when this fix will be in the release of the mini mc?

There are no concrete dates @pavel-z1

**Comment by pavel-z1** [comment]
Hi @vadmeste 

I'ver updated Minio MC to the latest release RELEASE.2021-01-16T02-45-34Z
But diff is still display different versions of files in replicated buckets.

Your fix is not in the latest mc release yet?

**Comment by vadmeste** [comment]
@pavel-z1 my fix is included in the latest release, however you need to test from scratch, the published fix won't fix your current files. Could you test from scratch again and update us ?

**Comment by pavel-z1** [comment]
Hi @vadmeste , I've reuploaded 1.5 million of files.
mc diff show now 0 differents when connecting directly to the minio server.

But I've found that a lot of issues occurred when minio client connect to the minio through the Nginx Proxy with enabled cache.
I've found two possible issue, related to Proxy:

1. mc send GET and HEAD type service requests to the minio server instead of POST. By default Nginx and Varnish Cache server perform caching of GET and HEAD requests. As result this cause wrong behaviour during execution of `mc diff` and `mc mirror` commands. 
I've tried to prevent caching of HEAD requests and GET requests with service arguments, but this not always prevent issues for mc.
My partially map configuration from Nginx:
```
# I TOLD YOU NOT TO CACHE HEAD REQUESTS !@#$%
map $request_method $head_nocache {
    default 0;
    "HEAD" 1;
}

# Do not cache service minio URLs with arguments
map $args $nocache {
    default $head_nocache;
    "~continuation-token=" 1;
    "~delimiter=" 1;
}
```

2. mc mirroring with wait feature don't works correctly via Nginx Proxy at all. Even with disabled Nginx cache.
I've tried to to add this Nginx options:
` proxy_cache_convert_head off;`
`ignore_invalid_headers off;`
But mc return periodically error 'Failed to perform mirroring The request signature we calculated does not match the signature you provided. Check your key and signing method'

This is not related directly to this issue. But I want to share my experience with the minio team
The Minio client clearly has problems when working through the Nginx Proxy with the cache.  Maybe some minio developer will be interested to fix this.
