### ISSUE TITLE
AWS SSO Integration

### ISSUE THREAD

**Issue by rotten** [minio/mc#3533]
## Expected behavior
mc should work for accessing S3 buckets when authenticated with AWS SSO.

## Actual behavior
I can get the Access Key and Access Secret after I've authenticated with SSO by using `aws-sso-credential-process`.  I can easily create a little script that updates the alias with the new credentials every time I authenticate with SSO.

I end up getting this error when I use those freshly generated credentials:
```mc: <ERROR> Unable to list folder. The AWS Access Key Id you provided does not exist in our records.```

I can access the bucket with the aws cli (v2) no problem.  Just not with mc.

## Steps to reproduce the behavior

```
aws sso login --profile myprofile
* Use aws-sso-credential-process to get AccessKey and SecretAccessKey from the json. *
mc alias set s3 https://mybucket.s3.us-east-1.amazonaws.com accesskey secretkey --api S3v4
mc ls s3
```

## mc --version
mc version RELEASE.2020-12-10T01-26-17Z

## System information
Ubuntu 20.04

$ aws --version
aws-cli/2.1.3 Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.20

$ aws-sso-credential-process --version
0.3.1

**Comment by rotten** [comment]
Is there any chance the client could support the native `s3://` uri format and syntax instead of requiring `https` ?  I think I'd have an easier time getting the credentials to work if that were the case.

**Comment by rotten** [comment]
I just learned that web-static hosting is disabled on our S3 buckets, so that may be the problem with using the https syntax to access objects there.  I'm seeing if I can get it enabled, at least in dev, to prove the concept.

**Comment by vadmeste** [comment]
@rotten can you create a new profile in ~/.aws/credentials and test aws with it ?  `aws s3api --profile your-profile list-buckets`

Does aws sso login only generate access and secret keys ? no other additional credentials ?

**Comment by rotten** [comment]
`aws s3api` works great for listing buckets.

aws sso login creates an access-token as well as the key and secret.  I'm not sure if the token is interchangeable with the key/secret pair.  All three have expirations typically they expire after a few hours (as determined by the aws administrator).  The access token can be found in ~/.aws/sso/cache or from running aws-sso-credential-process.

**Comment by vadmeste** [comment]
@rotten what happens if your run this command:
```
$ export MC_HOST_s3=https://key:secret:token@s3.amazonaws.com
$ mc ls s3/
```

?

**Comment by rotten** [comment]
I get a connection refused with the generic s3.amazon.com url

When I swap out the url for one of our buckets (which still doesn't have web hosting enabled) - If I don't put a space between the `s3` and the `/` then nothing happens.  No errors, no listing.   If I put a space there, I get a listing of the root file system on my laptop.

If I leave the token out of that URL I get an invalid Access Key error.  So definitely, I think, all 3 are required.

**Comment by vadmeste** [comment]
> I get a connection refused

Most likely you have a typo

**Comment by rotten** [comment]
If I don't include the bucket name in the URL, I can list my buckets like this:

```
export MC_HOST_s3=https://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}:${AWS_SESSION_TOKEN}@s3.us-east-1.amazonaws.com
mc ls s3/my_bucket_name
```

Cool!

**Comment by rotten** [comment]
And without the bucket name in the `ls` command, I can list the buckets.

**Comment by rotten** [comment]
So, it sounds like I should use the env variable rather than the `alias` function, I should include the token in the URL, and then point to the generic s3 interface instead of the specific bucket.  I'm ok with that.  I'm back in business.  Man, that was not obvious.  I probably should have asked this question in the minio slack - I was just assuming it was broken in the with the new SSO access methods - and I have at least 15 slack forums going at the moment already...

**Comment by vadmeste** [comment]
@rotten mc is intended to be simple. By the way, you can add 'sessionToken' field as well in the alias definition in ~/.mc/config.json

**Comment by rotten** [comment]
Thanks for the help!   

I'll try the config.json update with a quick manual edit.  I suppose the `alias` argument doesn't take a parameter to pass in the session token, so I'd need to write something that could dynamically update the json in that file independently if I want to go that route long term.

I'm working pretty well at the moment, that was remarkably not-obvious.  I hope this thread helps others too.

**Comment by ChristianBrauchli** [comment]
Had the same issue, adding 'sessionToken' field to ~/.mc/config.json was the fix
