### ISSUE TITLE
mc mirror is removing files shortly after initial sync

### ISSUE THREAD

**Issue by seqizz** [minio/mc#3535]
Related with #2439 I assume:

I'm syncing a big (~4-5TB) repository to the Scaleway from the local Minio. The daemon which is always running has this command:
```
/usr/bin/ionice -c3 /usr/local/bin/mc mirror --region=nl-ams --overwrite --remove --watch local/myproj s3backup/myproj
```

After putting some new files in, I realized I couldn't reach it on Scaleway. Logs show it is removing it after initial copy for some reason.

After waiting a bit and putting other files (this might be causing another scan) puts the file back to the remote (and doesn't remove afterwards).

Logs regarding to one example file (grepped):
```
Dec 16 05:18:59 myhostname ionice[155361]: `local/myproj/data/01/01b6d275fabc73ba6c9bb1cddc5aad2eb5921d9410fb5335cdc2417a9779a685` -> `s3backup/myproj/data/01/01b6d275fabc73ba6c9bb1cddc5aad2eb5921d9410fb5335cdc2417a9779a685`
Dec 16 05:22:05 myhostname ionice[155361]: Removing `s3backup/myproj/data/01/01b6d275fabc73ba6c9bb1cddc5aad2eb5921d9410fb5335cdc2417a9779a685`.
Dec 16 08:55:48 myhostname ionice[215771]: `local/myproj/data/01/01b6d275fabc73ba6c9bb1cddc5aad2eb5921d9410fb5335cdc2417a9779a685` -> `s3backup/myproj/data/01/01b6d275fabc73ba6c9bb1cddc5aad2eb5921d9410fb5335cdc2417a9779a685`
```

## Expected behavior

Do not remove remote file, as long as the source has it

## Actual behavior

As you see above, it removes the file after few seconds

## Steps to reproduce the behavior

Should be reproducible since linked issue was closed by stale bot. Repository has a lot of small files (biggest should be less than 10Mb) so if you have a similar repo, these parameters can also give you same issue.

## mc --version

`mc version RELEASE.2020-10-03T02-54-56Z`

## System information

Linux Debian Stretch (not sure what else would be relevant here)

**Comment by harshavardhana** [comment]
> Do not remove remote file, as long as the source has it

The main reason it happened because the file doesn't exist in source, i.e it was concurrently modified on the source - either renamed, recreated etc.

> `mc version RELEASE.2020-10-03T02-54-56Z`

Please upgrade and test again.

**Comment by seqizz** [comment]
> The main reason it happened because the file doesn't exist in source, i.e it was concurrently modified on the source - either renamed, recreated etc.

Hmm, this I'd say unlikely, from the application side (restic sets name of a file as hash of the contents and it is write-once-read-many). Even in a case like this, re-sending after 3.5 hours (coincidentally, the same time I put new files into the bucket) is suspicious.

> Please upgrade and test again.

Will do and report back, thanks.

**Comment by seqizz** [comment]
Looks like I can't reproduce this, either something was off on that specific time, or new version really helped. Thanks :+1: closing.
