### ISSUE TITLE
`mc cp --preserve` does not include file creation time

### ISSUE THREAD

**Issue by stevekm** [minio/mc#3542]
## Expected behavior

File creation timestamp should be included in the object metadata when used with `mc cp --preserve`

## Actual behavior

The creation timestamp is not preserved

## Steps to reproduce the behavior

```
$ echo '1' > foo.txt

$ stat -f'access:%a modified:%m changed:%c created:%B' foo.txt
access:1608322701 modified:1608322700 changed:1608322700 created:1608322686

$ mc cp --preserve foo.txt myminio/bucket1/foo.txt

$ mc stat myminio/bucket1/foo.txt
Name      : foo.txt
Date      : 2020-12-18 15:18:20 EST
Size      : 2 B
ETag      : b026324c6904b2a9cb4b88d6d61c81d1
Type      : file
Metadata  :
  Content-Type       : text/plain
  X-Amz-Meta-Mc-Attrs: atime:1608322701#807555753/gid:20/gname:staff/mode:33188/mtime:1608322700#664844994/uid:501/uname:steve

```

The access time (`atime`) and modified time (`mtime`) are kept, but the created time is not. On filesystems that support this, its a very useful attribute to have, so it would be really helpful to have this imported as well when available. 

## mc --version
- `mc version RELEASE.2020-12-18T10-53-53Z`

## System information

- macOS 10.14

**Comment by harshavardhana** [comment]
> The access time (`atime`) and modified time (`mtime`) are kept, but the created time is not. On filesystems that support this, its a very useful attribute to have, so it would be really helpful to have this imported as well when available.

ctime is non-standard @stevekm there are no platform-independent ways to support it. Currently is out of scope for us. Feel free to send a PR yourself - if you must want this feature.
