### ISSUE TITLE
Can't parse json output

### ISSUE THREAD

**Issue by remyj38** [minio/mc#3546]
When --json flag set, mc command should return list of objects, not objects separated by "\n"

Actual output can't be parsed because this is not a correct JSON string, but a list of JSON objects.

## Expected behavior
```
mc admin user list --json minio
[{
 "status": "success",
 "accessKey": "john",
 "userStatus": "enabled"
},
{
 "status": "success",
 "accessKey": "jane",
 "userStatus": "enabled"
}]
```

## Actual behavior
```
mc admin user list --json minio
{
 "status": "success",
 "accessKey": "john",
 "userStatus": "enabled"
},
{
 "status": "success",
 "accessKey": "jane",
 "userStatus": "enabled"
}
```
## Steps to reproduce the behavior
Configure an alias and execute a command that lists many objects

## mc --version
mc version RELEASE.2020-12-18T10-53-53Z

**Comment by harshavardhana** [comment]
What we support is called ndjson or jsonlines 

https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#option---json
