### ISSUE TITLE
 <ERROR> Unable to validate source

### ISSUE THREAD

**Issue by RooyeKhat** [minio/mc#3559]
## Expected behavior
Copy file between two minio servers  
## Actual behavior
The file is available on the server, even in the folder and can download in source minio server 
but when need ./mc cp show this error

<ERROR> Unable to validate source
## Debug Log 
```
./mc cp --recursive --debug local/bucketname/fc115e3a-4d57-4b57-a6fd-55b96f321b4c/ minio/bucketname/fc115e3a-4d57-4b57-a6fd-55b96f321b4c/
mc: <DEBUG> GET /bucketname/?location= HTTP/1.1
Host: localhost
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-12-18T10:53:53Z
Authorization: AWS4-HMAC-SHA256 Credential=S3Server/20210104/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210104T101052Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 04 Jan 2021 10:10:52 GMT
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 1656FFB0E60A9DD0
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  2.699213ms


mc: <DEBUG> GET /bucketname/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=fc115e3a-4d57-4b57-a6fd-55b96f321b4c HTTP/1.1
Host: localhost
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-12-18T10:53:53Z
Authorization: AWS4-HMAC-SHA256 Credential=S3Server/20210104/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210104T101052Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 339
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 04 Jan 2021 10:12:30 GMT
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 1656FFB0E62689AF
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  1m38.462821973s

mc: <ERROR> Unable to validate source `local//bucketname/fc115e3a-4d57-4b57-a6fd-55b96f321b4c/`.


```
## mc --version
- (paste output of `mc --version`)
`mc version RELEASE.2020-12-18T10-53-53Z`
## System information
```
Linux Centos 7
Linux 3.10.0-862.el7.x86_64 #1 SMP  UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nitisht** [comment]
> mc: <ERROR> Unable to validate source `local//bucketname/fc115e3a-4d57-4b57-a6fd-55b96f321b4c/`.

Do you have two `/` in the path here ?

**Comment by RooyeKhat** [comment]
> > mc:  Unable to validate source `local//bucketname/fc115e3a-4d57-4b57-a6fd-55b96f321b4c/`.
> 
> Do you have two `/` in the path here ?

No, there is a mistake here with single / tested and this problem has occurred in substituting the name
In any case, it has the same problem with single /

**Comment by nitisht** [comment]
```
$ ./mc cp -r myminio/test/fc115e3a-4d57-4b57-a6fd-55b96f321b4c/ m2/test/fc115e3a-4d57-4b57-a6fd-55b96f321b4c/
...ed83b8897d745e83c6ea054e53e99bdd:  726.27 KiB / 726.27 KiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 180.45 KiB/s 4s
```

It works for me on master. Is there anything special you're doing here? Are both source and target MinIO servers? Can you try with latest master?

**Comment by RooyeKhat** [comment]
Hi
I found the problem.
I did not have any free disk space, so it gave this error.
To copy, save the entire folder in tempo space, then send it, so you must have enough space for this on the hard drive.

Thanks

**Comment by lozhn** [comment]
I also had this issue and my problem was that my Minio Instance was running behind Cloudflare which restricts files >100mb on a free tier 🤦‍♂️

**Comment by rothwerx** [comment]
Just to chime in here, I was having this failure in CI. The problem for me was that the CI node was 15 minutes behind everything else. Enabled NTP and then everything worked great.

**Comment by skitsanos** [comment]
`Unable to validate source` occurs also when you try to copy from an empty folder, so it doesn't skip the copying process but just throws an error.

**Comment by matm** [comment]
> `Unable to validate source` occurs also when you try to copy from an empty folder, so it doesn't skip the copying process but just throws an error.

Using `mc mirror` instead doesn't fail on empty dirs in this case.

**Comment by m0x31h0x64i** [comment]
> I also had this issue and my problem was that my Minio Instance was running behind Cloudflare which restricts files >100mb on a free tier 🤦‍♂️

how did you fix that ? i also want to use cloud flare to manage my subdomains ...

**Comment by andreimerlescu** [comment]
i actually had to stop using and paying for cloudflare. their support was rude and unhelpful to my business so we changed providers after this technically came out. ultimately they say to use s3 and not minio with their dns. literally.  Sent from Proton Mail for iOS On Mon, Nov 14, 2022 at 11:24, m0x31h0x64i ***@***.***> wrote:  

I also had this issue and my problem was that my Minio Instance was running behind Cloudflare which restricts files >100mb on a free tier 🤦‍♂️

how did you fix that ? i also want to use cloud flare to manage my subdomains ...

**Comment by m0x31h0x64i** [comment]
> i actually had to stop using and paying for cloudflare. their support was rude and unhelpful to my business so we changed providers after this technically came out. ultimately they say to use s3 and not minio with their dns. literally.  Sent from Proton Mail for iOS On Mon, Nov 14, 2022 at 11:24, m0x31h0x64i ***@***.***> wrote: I also had this issue and my problem was that my Minio Instance was running behind Cloudflare which restricts files >100mb on a free tier 🤦‍♂️ how did you fix that ? i also want to use cloud flare to manage my subdomains ... —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

then how do you manage your dns?

**Comment by andreimerlescu** [comment]
i used to work at dyn dns so i just homebrewed something myself instead and sure their waf is really easy to use and fun but their product all in all is a poor man's clone of dyn's enterprise product back in the day ;) 
------- Original Message -------
