### ISSUE TITLE
Error when adding a policy - GetBucketAcl

### ISSUE THREAD

**Issue by a1ekseev** [minio/mc#3561]
Trying to import a policy:

```
{
    "Version": "2012-10-17",
    "Id": "NexusS3BlobStorePolicy",
    "Statement": [
        {
            "Sid": "NexusS3BlobStoreAccess",
            "Effect": "Allow",
            "Principal": {
                "AWS": "nexus-user"
            },
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:GetLifecycleConfiguration",
                "s3:PutLifecycleConfiguration",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:DeleteObjectTagging",
                "s3:DeleteBucket",
                "s3:CreateBucket",
                "s3:GetBucketAcl"
            ],
            "Resource": [
                "arn:aws:s3:::nexus.docker.central"
            ]
        }
    ]
}
```

I get a parsing error:

> mc: <ERROR> Unable to parse the input policy: unsupported action 's3:GetBucketAcl'.

If removed - GetBucketAcl, everything is successfully imported.

mc version RELEASE.2020-12-18T10-53-53Z

**Comment by harshavardhana** [comment]
> > mc:  Unable to parse the input policy: unsupported action 's3:GetBucketAcl'.

We do not support `s3:GetBucketAcl`

**Comment by a1ekseev** [comment]
> > > mc:  Unable to parse the input policy: unsupported action 's3:GetBucketAcl'.
> 
> We do not support `s3:GetBucketAcl`

Thanks for the answer, where can I find a complete list of restrictions?

**Comment by harshavardhana** [comment]
> Thanks for the answer, where can I find a complete list of restrictions?

That's it all legacy APIs such as Acl's

**Comment by a1ekseev** [comment]
> > Thanks for the answer, where can I find a complete list of restrictions?
> 
> That's it all legacy APIs such as Acl's

Thanks!
