### ISSUE TITLE
unknown units in json output

### ISSUE THREAD

**Issue by beefsalad** [minio/mc#3570]
expected behavior:

$mc cp --json bar foo/bar
speed:12491285615.1241567 Bytes/second

actual behavior:
$mc cp --json bar foo/bar
speed:12491285615.1241567

**Comment by vadmeste** [comment]
We can only add documentation here which indicates the speed unit.

**Comment by beefsalad** [comment]
Please add it to your documentation, thanks for the reply.  Let me know when the documentation is done and link to the docs.  Thanks!
