### ISSUE TITLE
mc update stuck in updating TLS cluster

### ISSUE THREAD

**Issue by DAGorchakov** [minio/mc#3571]
## Actual behavior
I try to update my minio cluster to latest version with the help of `mc admin update minio` but it stuck and show nothing till I cancel it in an hour.
![image](https://user-images.githubusercontent.com/17656075/104556156-1c790e00-5650-11eb-8ab3-c4d662ba3e1a.png)
I use self sign certificate, but my host trust it:
```
[root@xx-minio-02 ~]# curl -I https://xx-minio-02.domain.com:9000
HTTP/1.1 405 Method Not Allowed
Accept-Ranges: bytes
Content-Length: 30
Server: MinIO
Vary: Origin
Date: Thu, 14 Jan 2021 07:12:40 GMT
Content-Type: text/plain; charset=utf-8

```
## mc --version
`mc version RELEASE.2021-01-05T05-03-58Z`

## System information
Linux xx-minio-02 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by harshavardhana** [comment]
> ```
> [root@xx-minio-02 ~]# curl -I https://xx-minio-02.domain.com:9000
> HTTP/1.1 405 Method Not Allowed
> Accept-Ranges: bytes
> Content-Length: 30
> Server: MinIO
> Vary: Origin
> Date: Thu, 14 Jan 2021 07:12:40 GMT
> Content-Type: text/plain; charset=utf-8
> ```

this doesn't look like correct we don't return 405 - looks like you have a load balancer here returning something.

**Comment by DAGorchakov** [comment]
@harshavardhana  thanks, but unfortunately I have not LB in front of it
```
[root@xx-minio-02 ~]# curl -I https://xx-minio-02.domain.com:9000/minio
HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Content-Length: 250
Content-Type: application/xml
Server: MinIO
Vary: Origin
Date: Thu, 14 Jan 2021 07:24:33 GMT
```
Does it possible to see logs of `mc admin update`?

**Comment by harshavardhana** [comment]
Okay I see you are doing `Head` call here - `mc admin update` would be downloading from dl.minio.io - can you access dl.minio.io?

**Comment by DAGorchakov** [comment]
It is OK if I do so: 
```
[root@xx-minio-02 ~]# curl 'https://xx-minio-02.domain.com:9000/' \
>   -H 'authority: xx-minio-02.domain.com:9000' \
>   -H 'sec-ch-ua: "Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"' \
>   -H 'sec-ch-ua-mobile: ?0' \
>   -H 'upgrade-insecure-requests: 1' \
>   -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36' \
>   -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
>   -H 'sec-fetch-site: none' \
>   -H 'sec-fetch-mode: navigate' \
>   -H 'sec-fetch-user: ?1' \
>   -H 'sec-fetch-dest: document' \
>   -H 'accept-language: ru-RU,ru;q=0.9' \
>   --compressed
<a href="/minio/">Temporary Redirect</a>.```

**Comment by harshavardhana** [comment]
> root@xx-minio-02 ~]# curl 'https://xx-minio-02.domain.com:9000/' \
> >   -H 'authority: xx-minio-02.domain.com:9000' \
> >   -H 'sec-ch-ua: "Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"' \
> >   -H 'sec-ch-ua-mobile: ?0' \
> >   -H 'upgrade-insecure-requests: 1' \
> >   -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36' \
> >   -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
> >   -H 'sec-fetch-site: none' \
> >   -H 'sec-fetch-mode: navigate' \
> >   -H 'sec-fetch-user: ?1' \
> >   -H 'sec-fetch-dest: document' \
> >   -H 'accept-language: ru-RU,ru;q=0.9' \
> >   --compressed
> <a href="/minio/">Temporary Redirect</a>.```

No I mean you should access https://dl.minio.io  @DAGorchakov can you access the DL website?

**Comment by DAGorchakov** [comment]
```
[root@xx-minio-02 ~]# curl -I https://dl.min.io/client/mc/release/linux-amd64/mc
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 19664896
Content-Type: application/octet-stream
Etag: "qmg3i2bphj4"
Last-Modified: Tue, 05 Jan 2021 05:06:02 GMT
Server: Caddy
Date: Thu, 14 Jan 2021 07:37:22 GMT
```

**Comment by harshavardhana** [comment]
> [root@xx-minio-02 ~]# curl -I https://dl.min.io/client/mc/release/linux-amd64/mc
> HTTP/1.1 200 OK
> Accept-Ranges: bytes
> Content-Length: 19664896
> Content-Type: application/octet-stream
> Etag: "qmg3i2bphj4"
> Last-Modified: Tue, 05 Jan 2021 05:06:02 GMT
> Server: Caddy
> Date: Thu, 14 Jan 2021 07:37:22 GMT

Then I think its just the download speed.

**Comment by DAGorchakov** [comment]
is it possible to do update with local file?
```
[root@vw-minio-02 ~]# wget https://dl.min.io/client/mc/release/linux-amd64/mc
--2021-01-14 10:41:23--  https://dl.min.io/client/mc/release/linux-amd64/mc
Resolving dl.min.io (dl.min.io)... 178.128.69.202
Connecting to dl.min.io (dl.min.io)|178.128.69.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19664896 (19M) [application/octet-stream]
Saving to: ‘mc’

100%[====================================================================================>] 19,664,896   283KB/s   in 3m 22s

2021-01-14 10:44:46 (94.9 KB/s) - ‘mc’ saved [19664896/19664896]

```

**Comment by harshavardhana** [comment]
yes you can replace the binary for minio server and restart all the services

**Comment by DAGorchakov** [comment]
is it possible to do 'rolling update' nodes one by one and check if everything is OK?

**Comment by harshavardhana** [comment]
> Is it possible to do 'rolling update' nodes one by one and check if everything is OK?

No rolling upgrades are not supported - you just upgrade all servers @DAGorchakov
