### ISSUE TITLE
client image permissions error on openshift

### ISSUE THREAD

**Issue by ryandawsonuk** [minio/mc#3574]
## Expected behavior

Able to run client on openshift, using image to create Pods.

## Actual behavior

mc: <ERROR> Unable to save new mc config. mkdir /.mc: permission denied.

## More Details

This has been [reported before](https://github.com/minio/mc/issues/2640#issuecomment-760792572) and there are reproduction steps there. But the [most recent report went stale](https://github.com/minio/mc/issues/3128) so opening again.

**Comment by vadmeste** [comment]
@ryandawsonuk most likely you have an unusual setup and your $HOME is not set, could you access to one of your pod and type `echo $HOME` ?

**Comment by ryandawsonuk** [comment]
It's actually not easy for me to check that as the pods execute quickly and the complete. But I am now wondering if using the `--config-dir` parameter on the commands sent to the client pods would be another way to address this.

**Comment by ryandawsonuk** [comment]
@vadmeste managed to get it to print home by putting this in a pod spec:
```
  containers:
    - name: minio
      image: minio/mc:latest
      command: [ "printenv"]
      args: ["HOME"]
```
It prints `/root`

**Comment by ryandawsonuk** [comment]
I've taken the dockerfile from https://github.com/minio/mc/pull/2734 and built `ryandawsonuk/mc:rhtest`. That does work for me on openshift.

So I guess this question is whether the project wants to revisit that PR, offer an alternative image for openshift or maybe document this? Or we can close this and this issue can serve as documentation?
