### ISSUE TITLE
Mc startup slowed down when many session files are present despite not asking for resume

### ISSUE THREAD

**Issue by aremmes** [minio/mc#3578]
It appears that mc scans the entire set of session files in ~/.mc/session/ on every startup independently of whether the command involves a session. When used in a script that calls mc multiple times per run, this results in high CPU and I/O load.

## Expected behavior
- Mc ignores session files in ~/.mc/session/ when not asked to do anything with them, and starts performing requested operation quickly.

## Actual behavior
- Mc reads session files in ~/.mc/session/ on startup, and takes an unusually long time to begin performing requested operation.

## Steps to reproduce the behavior
- Have many session files in ~/.mc/session/ (~1-2k)
- Run `mc config host ls`

## mc --version
- RELEASE.2021-01-05T05-03-58Z

## System information
- CentOS 6.9 x86_64

**Comment by vadmeste** [comment]
This is because mc tries to upgrade all sessions when it starts. Maybe we need to upgrade on the fly when mc tries to access to a particular session

**Comment by harshavardhana** [comment]
> This is because mc tries to upgrade all sessions when it starts. Maybe we need to upgrade on the fly when mc tries to access to a particular session

Also sessions older than a month can be purged as well.
