### ISSUE TITLE
Installing Minio Client via DEB package blocks further apt usage

### ISSUE THREAD

**Issue by jonathanschlue-as** [minio/mc#3585]
## Expected behavior

    $ wget https://dl.min.io/client/mc/release/linux-amd64/mc_0.0.20210116024534_amd64.deb
    $ sudo dpkg -i mc_0.0.20210116024534_amd64.deb
    $ mc --version

leads to

    mc version RELEASE.2021-01-16T02-45-34Z

## Actual behavior

    $ wget https://dl.min.io/client/mc/release/linux-amd64/mc_0.0.20210116024534_amd64.deb
    $ dpkg -i mc_0.0.20210116024534_amd64.deb

leads to

```
Selecting previously unselected package mc.
(Reading database ... 28773 files and directories currently installed.)
Preparing to unpack mc_0.0.20210116024534_amd64.deb ...
Unpacking mc (0.0.20210116024534) ...
dpkg: dependency problems prevent configuration of mc:
 findutils (4.6.0+git+20161106-2) breaks mc (<< 3:4.8.11-1) and is installed.
  Version of mc to be configured is 0.0.20210116024534.

dpkg: error processing package mc (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mc
```

After this, `apt` is in an inconsistent state, because `mc` could not be configured correctly. This results in subsequent `apt` commands being blocked.

## Steps to reproduce the behavior

* Follow Installation Instructions on https://min.io/download#/linux for **MINIO CLIENT**, **DEB**

```
$ wget https://dl.min.io/client/mc/release/linux-amd64/mc_0.0.20210116024534_amd64.deb
$ dpkg -i mc_0.0.20210116024534_amd64.deb
```

## mc --version
- mc version RELEASE.2021-01-16T02-45-34Z

## System information
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch

**Comment by harshavardhana** [comment]
This is fixed as part of the new release where package will be built indicating that it conflicts with `midnight-commander`  https://github.com/minio/pkger/blob/main/main.go#L82

**Comment by jonathanschlue-as** [comment]
> This is fixed as part of the new release where package will be built indicating that it conflicts with `midnight-commander` https://github.com/minio/pkger/blob/main/main.go#L82

Thanks for your reply. We'll try the next release then.
