### ISSUE TITLE
Installing Minio Client via DEB package blocks further apt usage (Follow-Up)

### ISSUE THREAD

**Issue by jonathanschlue-as** [minio/mc#3593]
## Expected behavior

    $ wget https://dl.min.io/client/mc/release/linux-amd64/mc_0.0.20210130005042_amd64.deb
    $ sudo dpkg -i mc_0.0.20210130005042_amd64.deb
    $ mc --version

leads to

    mc version RELEASE.2021-01-30T00-50-42Z

## Actual behavior

    $ wget https://dl.min.io/client/mc/release/linux-amd64/mc_0.0.20210130005042_amd64.deb
    $ sudo dpkg -i mc_0.0.20210130005042_amd64.deb

leads to

```
Selecting previously unselected package mc.
(Reading database ... 28773 files and directories currently installed.)
Preparing to unpack mc_0.0.20210130005042_amd64.deb ...
Unpacking mc (0.0.20210130005042) ...
dpkg: dependency problems prevent configuration of mc:
 findutils (4.6.0+git+20161106-2) breaks mc (<< 3:4.8.11-1) and is installed.
  Version of mc to be configured is 0.0.20210130005042.

dpkg: error processing package mc (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mc
```

After this, `apt` is in an inconsistent state, because `mc` could not be configured correctly. This results in subsequent `apt` commands being blocked.

## Steps to reproduce the behavior

* Follow Installation Instructions on https://min.io/download#/linux for **MINIO CLIENT**, **DEB**

```
$ wget https://dl.min.io/client/mc/release/linux-amd64/mc_0.0.20210130005042_amd64.deb
$ sudo dpkg -i mc_0.0.20210130005042_amd64.deb
```

## mc --version
- mc version RELEASE.2021-01-30T00-50-42Z

## System information
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch

**Comment by jonathanschlue-as** [comment]
This is a Follow-Up to https://github.com/minio/mc/issues/3585. 

> This is fixed as part of the new release where package will be built indicating that it conflicts with midnight-commander https://github.com/minio/pkger/blob/main/main.go#L82

- https://github.com/minio/mc/issues/3585#issuecomment-767018848

We tried the new release but received the same error.

**Comment by harshavardhana** [comment]
Will check

**Comment by mrdsam** [comment]
Suggestion: Simply rename the package to minio-client? Like in FreeBSD ports collection.

**Comment by harshavardhana** [comment]
> Suggestion: Simply rename the package to minio-client? Like in FreeBSD ports collection.

Yes that can be done good idea.

**Comment by harshavardhana** [comment]
Package renamed as `mcli` and installs as `mcli`

**Comment by Amunak** [comment]
I find it fascinating how arrogance (or is it stupidity?) causes numerous completely preventable issues and confusion just because you think you are important enough to warrant clashing with a command people have been used to for decades.

You know you could've used `mcli` in the first place and then tell people to make an alias if they want, right?

Or doing the even more standard way of using the even less ambiguous `minio-cli` command. If Redis can do it, you can too. A neat benefit of it is that it makes the commands way easier to google.
