### ISSUE TITLE
mc versioning 501 not implemented

### ISSUE THREAD

**Issue by cwitd** [minio/mc#3594]
## Expected behavior
```
mc version enable myminio/bucket
myminio/bucket versioning is enabled
```
## Actual behavior
```
mc: <DEBUG> HTTP/1.1 501 Not Implemented
Content-Length: 377
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 04 Feb 2021 10:24:59 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Amz-Bucket-Region: uk-lon1
X-Amz-Request-Id: 16608473C516964C
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><BucketName>bucket</Bucket
Name><Resource>/bucket/</Resource><Region>uk-lon1</Region><RequestId>16608473C516964C</RequestId><HostId>83a8eed5-652b-4ab5-b45c-f49523b35acd</Hos
tId></Error>mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Let's Encrypt
mc: <DEBUG>  >> Expires: 2021-04-22 12:10:34 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Organization: Digital Signature Trust Co.
mc: <DEBUG>  >> Expires: 2021-09-29 19:21:40 +0000 UTC
mc: <DEBUG> Response Time:  117.6844ms
```
## Steps to reproduce the behavior
Using go lang IDE, terminal commands for mc, below for enabling versioning on a bucket (with upcloud object storage), the info version command works, but blocks me from enabling versioning on any of my buckets.
```
mc version enable myminio/bucket
```
## mc --version
- (paste output of `mc --version`)
```
mc version DEVELOPMENT.GOGET
```
## System information
Using latest version of Go Lang IDE 
Latest update of mc

**Comment by harshavardhana** [comment]
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><BucketName>bucket</Bucket
> Name><Resource>/bucket/</Resource><Region>uk-lon1</Region><RequestId>16608473C516964C</RequestId><HostId>83a8eed5-652b-4ab5-b45c-f49523b35acd</Hos
> tId></Error>mc: <DEBUG> TLS Certificate found:

Your server doesn't support versioning.
