### ISSUE TITLE
Can't list versioned objects on GCS

### ISSUE THREAD

**Issue by viovanov** [minio/mc#3598]
## Expected behavior

On GCS, I should be able to list versioned objects.

## Actual behavior

An error occurs:

```
mc: <ERROR> Unable to list folder. unrecognized option:Marker
```

## Steps to reproduce the behavior

1. Create a bucket on GCS
2. Enable versioning for it: `gsutil versioning set on gs://my-foo-bucket`
3. List objects: `mc ls --versions gcs/my-foo-bucket/`

## mc --version
Built from source `RELEASE.2021-02-07T02-02-05Z`

## System information

linux amd64

**Comment by harshavardhana** [comment]
GCS doesn't support AWS S3 compatible versioning API @viovanov - please talk to GCS to support full S3 compatibility.

**Comment by viovanov** [comment]
@harshavardhana maybe I missed it - but it would be good to spell this out in the docs for the minio client libraries.
And fail with a more appropriate error message in `mc`.

**Comment by harshavardhana** [comment]
> @harshavardhana maybe I missed it - but it would be good to spell this out in the docs for the minio client libraries.
> And fail with a more appropriate error message in `mc`.

Listing out GCS limitations in our documentation is completely out of scope, we have always said we will work with S3 compatible implementations.

If you want to use GCS use gsutil - I don't know why you are trying to use GCS with their incomplete S3 API.
