### ISSUE TITLE
Current release deb file not retrievable via archive/ directory from downloads page

### ISSUE THREAD

**Issue by jonathanschlue-as** [minio/mc#3605]
## Expected behavior

The current release of the mcli deb Package is retrievable from both of the following locations:

* https://dl.min.io/client/mc/release/linux-amd64/ and
* https://dl.min.io/client/mc/release/linux-amd64/archive/

## Actual behavior

The current release of the mcli-Deb-Package is only retrievable from

* https://dl.min.io/client/mc/release/linux-amd64/

but not from

* https://dl.min.io/client/mc/release/linux-amd64/archive/

## Steps to reproduce the behavior

Download current release's mcli deb Packagefrfom the `archive/` directory, e.g:

```
$ wget https://dl.min.io/client/mc/release/linux-amd64/archive/mcli_20210210073257.0.0_amd64.deb
--2021-02-11 12:01:22--  https://dl.min.io/client/mc/release/linux-amd64/archive/mcli_20210210073257.0.0_amd64.deb
Resolving dl.min.io (dl.min.io)... 178.128.69.202
Connecting to dl.min.io (dl.min.io)|178.128.69.202|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-11 12:01:23 ERROR 404: Not Found.
```

## mc --version
- mc version RELEASE.2021-02-10T07-32-57Z

## System information

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by jonathanschlue-as** [comment]
Also see https://github.com/minio/minio/issues/11518

**Comment by harshavardhana** [comment]
Sure will keep a copy in archive as well.
