### ISSUE TITLE
Use mc with uri-based gateways

### ISSUE THREAD

**Issue by damianoneill** [minio/mc#3615]
Closing this as an unsupported use case... it won't work with AWS S3 signature v4 and handling custom URLs by stripping off custom prefixes is out of scope for `mc`.

_Originally posted by @harshavardhana in https://github.com/minio/mc/issues/2512#issuecomment-413037020_

**Comment by damianoneill** [comment]
Hi @harshavardhana can you explain how the mc client can be used with an API gateway?  

When running minio within a cluster, I'd like to use mc to cp content into the cluster, exposure to minio is on an API endpoint, <cluster-ip>/minio 

Do you have a solution for this? 

Thanks,
Damian.

**Comment by harshavardhana** [comment]
> Closing this as an unsupported use case... it won't work with AWS S3 signature v4 and handling custom URLs by stripping off custom prefixes is out of scope for `mc`.

It won't work @damianoneill 

> When running minio within a cluster, I'd like to use mc to cp content into the cluster, exposure to minio is on an API endpoint, /minio

S3 API is not like traditional REST calls URIs are encoded and API lands at `/`

**Comment by damianoneill** [comment]
Yes I saw your previous comment, what I don't understand is why the mc client is validating the endpoint structure and in my case therefore falling before it originates the request.  If it didn't validate this would below then not work?

mc -> gateway (xxx/minio) -> redirects to -> (xxx:port)  -> minion

Apologies if this is a stupid question, but it seems that lots of people will run minio inside a cluster and will not expose a nodeport.

**Comment by harshavardhana** [comment]
> Yes I saw your previous comment, what I don't understand is why the mc client is validating the endpoint structure and in my case therefore falling before it originates the request. If it didn't validate this would below then not work?

mc is the one generation authorization header and signature so it is its business to worry about the endpoint

**Comment by harshavardhana** [comment]
> Apologies if this is a stupid question, but it seems that lots of people will run minio inside a cluster and will not expose a nodeport.

You don't have to your ingress should have `/` point to MinIO not `/minio`

**Comment by damianoneill** [comment]
> > Apologies if this is a stupid question, but it seems that lots of people will run minio inside a cluster and will not expose a nodeport.
> 
> You don't have to your ingress should have `/` point to MinIO not `/minio`

Thanks @harshavardhana, but this assumes that minio is the only ingress, we have a few applications hanging off / all routed via a sub-resource.

**Comment by harshavardhana** [comment]
> Thanks @harshavardhana, but this assumes that minio is the only ingress, we have a few applications hanging off / all routed via a sub-resource.

Correct @damianoneill MinIO is the storage layer unlike your other applications and has S3 API requirements so unfortunately it's not possible.

**Comment by damianoneill** [comment]
Thanks @harshavardhana
