### ISSUE TITLE
mc mirror does not transfer empty directories

### ISSUE THREAD

**Issue by GreatBahram** [minio/mc#3620]
## Expected behavior
It's quite interesting that **I can create empty** directories using `mc mb`, but **the mirror subcommand refuses to transfer empty directories**. I think this is some sort of inconsistency, and it's better to treat empty directories in the same way in different cases.

```shell
# First case
mc mb myminio/bucket/dir_a/dir_b

# Second scenario
mc mirror --watch mydir myminio/mydir &

# Why it does not transfer the empty directory?
mkdir mydir/emptydir
```

From my point of view, when a user can create an empty directory using `mc mb`, then `mc mirror` should also follow this principle. In my case, I'm using `mc mirror` somewhat similar to the Dropbox cloud service, and I want my users to be able to have empty directories. Probably, as there is some argument on both sides, it is better to have an option for this, developers who think it is strange to have empty directories inside object storage don't use this option, others, on the other hand, can enjoy this functionality.

Here is [another evidence](https://github.com/minio/mc/issues/2612) that the community asks for this feature.

Thank you very much

**Comment by ebozduman** [comment]
@GreatBahram ,

Team discussed your support request, but we are still at the same position.

```
@harshavardhana wrote in issue# 2612:
This is simply a matter of choice, it is discouraged creating empty
 directories - they are frivolous operation on Object Storage. Since
 object storage is a flat namespace it is better to create a namespace
 entry when there is an object rather than having a list of empty directories
 which are practically not useful. mc mirror is implemented with these
 requirements in mind.
```
