### ISSUE TITLE
minio client sync bucket error

### ISSUE THREAD

**Issue by fanglichun** [minio/mc#3622]
## Expected behavior
k8s cluster:
4 minio service instance

storage alias:
 minio_wuhan：server A-server A 
minio_shenzhen ：server A -server B

1.mc mirror -w minio_wuhan/artifacts minio_shenzhen 

2.mc mirror --remove --overwrite --watch  minio_wuhan minio_shenzhen  

## Actual behavior
1.error: 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <ERROR> Failed to perform mirroring A specified event is not supported for notifications.

2.error:mc: <ERROR> Failed to perform mirroring readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<ListAllMyB|..., bigger context ...|<ListAllMyBucketsResult xmlns="http://s3.amazonaws.|...

debug show information：
[root@i-a0ip9jy5 artifacts]# mc mirror -remove  -overwrite -w --debug  minio_wuhan minio_shenzhen
 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> GET / HTTP/1.1
Host: 103.21.118.92:31099
User-Agent: MinIO (linux; amd64) minio-go/v7.0.9 mc/RELEASE.2021-02-14T04-28-06Z
Authorization: AWS4-HMAC-SHA256 Credential=coding/20210224/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210224T015341Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1272
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 24 Feb 2021 01:53:41 GMT
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 16668C285F7E0902
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  115.43817ms

 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> GET / HTTP/1.1
Host: 43.254.54.84:31099
User-Agent: MinIO (linux; amd64) minio-go/v7.0.9 mc/RELEASE.2021-02-14T04-28-06Z
Authorization: AWS4-HMAC-SHA256 Credential=coding/20210224/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210224T015341Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1272
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 24 Feb 2021 01:53:41 GMT
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 16668C285F189593
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  183.991863ms

 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> GET / HTTP/1.1
Host: 103.21.118.92:31099
User-Agent: MinIO (linux; amd64) minio-go/v7.0.9 mc/RELEASE.2021-02-14T04-28-06Z
Authorization: AWS4-HMAC-SHA256 Credential=coding/20210224/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210224T015341Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1272
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 24 Feb 2021 01:53:41 GMT
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 16668C286AFAD7AE
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  119.778535ms

 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> GET /artifacts/?location= HTTP/1.1
Host: 103.21.118.92:31099
User-Agent: MinIO (linux; amd64) minio-go/v7.0.9 mc/RELEASE.2021-02-14T04-28-06Z
Authorization: AWS4-HMAC-SHA256 Credential=coding/20210224/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210224T015341Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 24 Feb 2021 01:53:41 GMT
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 16668C287233FF6F
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  5.512587ms

mc: <DEBUG> GET /artifacts/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&metadata=true&prefix= HTTP/1.1
Host: 103.21.118.92:31099
User-Agent: MinIO (linux; amd64) minio-go/v7.0.9 mc/RELEASE.2021-02-14T04-28-06Z
Authorization: AWS4-HMAC-SHA256 Credential=coding/20210224/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210224T015341Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1694
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 24 Feb 2021 01:53:41 GMT
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 16668C28728FC672
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  19.787807ms

 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> GET /?events=s3%3AObjectCreated%3A%2A&events=s3%3AObjectRemoved%3A%2A&events=s3%3ABucketCreated%3A%2A&events=s3%3ABucketRemoved%3A%2A&prefix=&suffix= HTTP/1.1
Host: 43.254.54.84:31099
User-Agent: MinIO (linux; amd64) minio-go/v7.0.9 mc/RELEASE.2021-02-14T04-28-06Z
Authorization: AWS4-HMAC-SHA256 Credential=coding/20210224/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210224T015341Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1272
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 24 Feb 2021 01:53:41 GMT
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 16668C286A8350F3
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  259.96101ms

mc: <ERROR> Failed to perform mirroring readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<ListAllMyB|..., bigger context ...|<ListAllMyBucketsResult xmlns="http://s3.amazonaws.|...
 (1) mirror-main.go:435 cmd.(*mirrorJob).monitorMirrorStatus(..)
 (0) client-s3.go:783 cmd.(*S3Client).Watch.func1(..)
 Release-Tag:RELEASE.2021-02-14T04-28-06Z | Commit:7672841f8c58 | Host:i-a0ip9jy5 | OS:linux | Arch:amd64 | Lang:go1.15.7 | Mem:7.9 MB/75 MB | Heap:7.9 MB/66 MB

## Steps to reproduce the behavior
only contains --watch args，happen to error.
## mc --version
mc version RELEASE.2021-02-14T04-28-06Z

## System information
Linux i-a0ip9jy5 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by E-Kolotilko** [comment]
Got same error. Happens only with --watch argument, otherwise "mirror" works fine.

**Comment by ebozduman** [comment]
@fanglichun,

Could you please let us know  MinIO versions running on each one of your servers?
We need to make sure your servers are all running with the same MinIO build/release.

Just like @E-Kolotilko wrote above, this could be due to mismatching server versions.

I guess, the best thing to do at this point is to upgrade all your servers to the same, latest MinIO release and give it another try.

Let us know if you can still reproduce the same error when all your servers are running with the same version.
Meanwhile, I'll be also trying to reproduce the problem.

**Comment by ebozduman** [comment]
@fanglichun ,

I don't see any problem when I tried, so I cannot reproduce it.
Waiting for your reply...

**Comment by ebozduman** [comment]
Closing this issue assuming no response means no problem and also we cannot reproduce it.
