### ISSUE TITLE
mcli should respect XDG basedirs for storing its configuration

### ISSUE THREAD

**Issue by ddevault** [minio/mc#3627]
**Is your feature request related to a problem? Please describe.**

mcli should not store its configuration in the `~/.*` namespace on Unix systems.

**Describe the solution you'd like**

mcli should respect the [XDG basedirs spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html), using `$XDG_CONFIG_HOME/mcli` if set, and falling back to `~/.config/mcli` if not. It can read `~/.mcli` as a last resort to avoid breaking the config for users who have already set it up, but it should not create new files there by default anymore.

**Comment by klauspost** [comment]
This will require moving the config to not break existing installs on update.

**Comment by vadmeste** [comment]
> This will require moving the config to not break existing installs on update.

Maybe we can do as a fallback better. I mean the last check will be ~/.mc/

**Comment by ddevault** [comment]
Don't run bots like that, jeesh

**Comment by renich** [comment]
phew... I'm also waiting for this one.

**Comment by ddevault** [comment]
Don't run bots like that, jeesh

**Comment by vadmeste** [comment]
I sent a PR for this. But I am not sure if we are going to merge it.

> Don't run bots like that, jeesh

We receive a lot of issues and we cannot process all of them. It makes sense that a bot helps us here :)

**Comment by ddevault** [comment]
Those bots are an anti-feature which communicates a lack of investment from maintainers in their community. You should triage issues and close them when you know they're not a good idea, and otherwise leave them open. Having a lot of open issues is not a mark of shame.

**Comment by harshavardhana** [comment]
> Those bots are an anti-feature which communicates a lack of investment from maintainers in their community. You should triage issues and close them when you know they're not a good idea, and otherwise leave them open. Having a lot of open issues is not a mark of shame.

How we manage the issues is our internal requirement, bots will run as per our requirement.
