### ISSUE TITLE
mc does not fails when server is not even up

### ISSUE THREAD

**Issue by sgandon** [minio/mc#3630]
## Expected behavior
when doing an mc command to check the status of a server like this
`MC_HOST_benchmarks=http://foo:bar@127.0.0.1:1200 ./mc --debug --config-dir . admin info benchmarks`
I would expect it returns with an error right away if the server is not even up.

## Actual behavior
It returns an error after 2 minutes ! (and this is the same for all other commands I believe)

## Steps to reproduce the behavior
cd to a directory with mc and run this 
`MC_HOST_benchmarks=http://foo:bar@127.0.0.1:1234 ./mc --debug --config-dir . admin info benchmarks`

## mc --version
mc --version
mc version RELEASE.2021-02-19T05-34-40Z

**Comment by ebozduman** [comment]
@sgandon 

What other commands do you experience the same problem?

I checked and verified that `mc admin info <alias>` gives up in my setup after 1 min 45 seconds, (close to 2 mins like you said) and spits out the `"connection refused"` error message.

**Comment by vadmeste** [comment]
@ebozduman I guess we retry "connection refused" error in minio/minio/pkg/madmin/ package, I think we don't have to do that. We can throw an error right away when we see it.

**Comment by sgandon** [comment]
You would have the same behaviour with `user info` `policy info` `user list` `policy list` and may be more.

**Comment by sgandon** [comment]
May be the retry and timeout could be some command line option to give the user the ability to choose to timeout quickly.

**Comment by vadmeste** [comment]
> May be the retry and timeout could be some command line option to give the user the ability to choose to timeout quickly.

I think that's not needed. Connection refused will be returned quickly anyway. I think we need to check if i/o timeout is retried and disable that as well.

**Comment by ebozduman** [comment]
@sgandon ,
So, it is all about `admin info`. Good!

@vadmeste,

I think the retries are good in a flaky network environment. But it doesn't need to be this long. I'll be looking into it.

**Comment by ebozduman** [comment]
Fixed by #11809 and merged.
