### ISSUE TITLE
Feature Request: mc --color to force colorized output

### ISSUE THREAD

**Issue by mrdsam** [minio/mc#3632]
## Expected behavior
It should be possible to force 'mc' using color output, even if output is a pipe. In addition to the `--no-color` flag, there should be a `--color` flag, too.

## Actual behavior
'mc' switches to no-color-output automatically when output is a pipe --- and there is no flag to influence this behavior.

## Steps to reproduce the behavior
`mc  admin trace  -a s3/ | less -R`  displays no color, although `less -R` is capable to do so.

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2021-02-10T07-32-57Z
## System information
FreeBSD 12.2  bash command line

## Workaround
Use `screen` and log screen output

**Comment by harshavardhana** [comment]
> It should be possible to force 'mc' using color output, even if output is a pipe. In addition to the `--no-color` flag, there should be a `--color` flag, too.

Feel free to send a PR yourself @mrdsam - closing this issue on our end.  Currently we have no plans on adding this.
