### ISSUE TITLE
mc rb issue

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3637]
Somehow i am unable to remove a folder "configs", rb command returns both error and success at the same time, running ls right after shows that folder is still there.

Running latest version of mc and minio
mc version RELEASE.2021-02-19T05-34-40Z
 Version: 2021-03-04T00:53:13Z

Details below:

i0x71@debian:~$ mc ls dot9/sys/
[2021-03-05 09:05:35 EST]     0B conf/
[2021-03-05 09:05:35 EST]     0B configs/
[2021-03-05 09:05:35 EST]     0B notes/
[2021-03-05 09:05:35 EST]     0B pkg/
[2021-03-05 09:05:35 EST]     0B scripts/
[2021-03-05 09:05:35 EST]     0B yg/
i0x71@debian:~$ mc rb --force dot9/sys/configs
mc: <ERROR> Failed to remove `dot9/sys/configs`, continuing.. cannot delete prefixes with `mc rb` command - Use `mc rm` instead
Removed `dot9/sys/configs` successfully.
i0x71@debian:~$ mc ls dot9/sys/
[2021-03-05 09:05:46 EST]     0B conf/
[2021-03-05 09:05:46 EST]     0B configs/
[2021-03-05 09:05:46 EST]     0B notes/
[2021-03-05 09:05:46 EST]     0B pkg/
[2021-03-05 09:05:46 EST]     0B scripts/
[2021-03-05 09:05:46 EST]     0B yg/
i0x71@debian:~$ mc rb --force dot9/sys/configs/
mc: <ERROR> Failed to remove `dot9/sys/configs/`, continuing.. cannot delete prefixes with `mc rb` command - Use `mc rm` instead
Removed `dot9/sys/configs/` successfully.
i0x71@debian:~$ mc ls dot9/sys/
[2021-03-05 09:06:38 EST]     0B conf/
[2021-03-05 09:06:38 EST]     0B configs/
[2021-03-05 09:06:38 EST]     0B notes/
[2021-03-05 09:06:38 EST]     0B pkg/
[2021-03-05 09:06:38 EST]     0B scripts/
[2021-03-05 09:06:38 EST]     0B yg/

**Comment by vadmeste** [comment]
@ebozduman do you know why mc tries to continue if rb fail ? It doesn't make sense to me.

**Comment by ebozduman** [comment]
@vadmeste,

It is implemented this way, most probably because we wanted to have a complete list of issues in one shot/run for the whole bucket content.

So, the problem here is the fact that if an object in the bucket can be removed, we remove it right away. When a problem is encountered and an object cannot be removed, then an error message is displayed and we continue with the next object. After the last object is processed, since the function reaches the end, the successful message is displayed.

**Comment by vadmeste** [comment]
> The problem here is the fact that if an object in the bucket can be removed, we remove it right away. When a problem is encountered and an object cannot be removed, then an error message is displayed and we continue with the next object.

I really don't think this is needed. I mean, if mc fails to remove any object for any reason, policy denying it or some locking preventing it, we will never be able to remove the bucket. I guess we need to quit right away (also to show an error and not flooding the user with a lot of errors).

**Comment by ebozduman** [comment]
@iox71
This issue has been addressed in PR #3616 as a response to issue #3387. 
You can try with the latest mc release which has the fix. 
So, closing this issue as `fixed` and `duplicate` of #3387.
