### ISSUE TITLE
Upload to AWS S3 fails

### ISSUE THREAD

**Issue by llamafilm** [minio/mc#3645]
## Expected behavior
Uploading a file to AWS S3

## Actual behavior
It tries several times and then fails with error: 
```
mc: <ERROR> Failed to copy `ASSETMAP.xml`. Put "https://temp.s3.dualstack.us-west-1.amazonaws.com/minio/ASSETMAP.xml": 301 response missing Location header
```

## Steps to reproduce the behavior
I added my bucket alias
```
# mc alias ls demo
demo
  URL       : https://s3-us-west-1.amazonaws.com
  AccessKey : xxxx
  SecretKey : xxxxx
  API       : s3v4
  Path      : auto
```

## mc --version
mc version RELEASE.2021-03-12T03-36-59Z

## System information
Amazon Linux 2
4.14.219-161.340.amzn2.x86_64
Running on EC2 instance in us-west-1

## More details
For some reason, the debug output shows the response says I should use us-east-1.  But I'm 100% sure this bucket is located in us-west-1.
```
# mc cp ASSETMAP.xml demo/temp/minio/ --debug
mc: <DEBUG> GET /?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&max-keys=1&prefix=minio HTTP/1.1
Host: temp.s3.dualstack.us-west-1.amazonaws.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-03-12T03-36-59Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20210313/us-west-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210313T023756Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 301 Moved Permanently
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Sat, 13 Mar 2021 02:37:56 GMT
Server: AmazonS3
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: O0yhIABXIQYL3XF03EllaCj64RvSmlhzt52iPAoKC/mIrVVxGrLtXqeDTRCpsmU4mOldI8jmNo0=
X-Amz-Request-Id: H1D2MJJYSV57MYT0

1c2
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Endpoint>s3.dualstack.us-east-1.amazonaws.com</Endpoint><Bucket>temp</Bucket><RequestId>H1D2MJJYSV57MYT0</RequestId><HostId>O0yhIABXIQYL3XF03EllaCj64RvSmlhzt52iPAoKC/mIrVVxGrLtXqeDTRCpsmU4mOldI8jmNo0=</HostId></Error>
0

mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: DigiCert Inc
mc: <DEBUG>  >> Expires: 2021-08-04 12:00:00 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: IE
mc: <DEBUG>  >> Organization: Baltimore
mc: <DEBUG>  >> Expires: 2025-05-10 12:00:00 +0000 UTC
mc: <DEBUG> Response Time:  52.099209ms
```

I verified that my IAM role has permission for GetBucketLocation.
```
$ aws s3api get-bucket-location --bucket altsystemsdemo
{
    "LocationConstraint": "us-west-1"
}
```

**Comment by harshavardhana** [comment]
> # mc cp ASSETMAP.xml demo/temp/minio/ --debug
> mc: <DEBUG> GET /?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&max-keys=1&prefix=minio HTTP/1.1
> Host: temp.s3.dualstack.us-west-1.amazonaws.com
> User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-03-12T03-36-59Z
> Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20210313/us-west-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> X-Amz-Date: 20210313T023756Z
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 301 Moved Permanently
> Transfer-Encoding: chunked
> Content-Type: application/xml
> Date: Sat, 13 Mar 2021 02:37:56 GMT
> Server: AmazonS3
> X-Amz-Bucket-Region: us-east-1
> X-Amz-Id-2: O0yhIABXIQYL3XF03EllaCj64RvSmlhzt52iPAoKC/mIrVVxGrLtXqeDTRCpsmU4mOldI8jmNo0=
> X-Amz-Request-Id: H1D2MJJYSV57MYT0

your bucket is in us-east-1 i.e `temp` here so you should appropriate bucket from the right region if you are using us-west-1 URL

**Comment by llamafilm** [comment]
As I said before, this bucket is in us-west-1.  I included the AWS CLI output to prove it.

**Comment by harshavardhana** [comment]
> As I said before, this bucket is in us-west-1. I included the AWS CLI output to prove it.

Your `mc ls` command says otherwise and returned value from AWS S3 

> X-Amz-Bucket-Region: us-east-1

Read properly @llamafilm what you pasted.

**Comment by llamafilm** [comment]
Oh my bad!  I forgot to include the bucket name, I see this is trying to use a bucket called temp.  Thanks for pointing that out.
I would have expected to get AccessDenied error since I don't have permission for a bucket called temp.

**Comment by harshavardhana** [comment]
> Oh my bad! I forgot to include the bucket name, I see this is trying to use a bucket called temp. Thanks for pointing that out.
> I would have expected to get AccessDenied error since I don't have permission for a bucket called temp.

We would love to throw that error if AWS returned such an error.
