### ISSUE TITLE
Enabling notify_redis fails with Error: ReadMapCB

### ISSUE THREAD

**Issue by shuckc** [minio/mc#3651]
## Expected behavior
Per https://docs.min.io/docs/minio-bucket-notification-guide.html "Publish MinIO events via Redis"
`$ mc admin config set local/ notify_redis:1 ...` 
should trigger an ARN (after server restart) that can be used to later enable notifications
 
## Actual behavior

Client logs an error
```
sh-4.4$ mc --insecure admin config set local/ notify_redis:1 address="127.0.0.1:6379" format="namespace" key="bucketevents" password="yoursecret" queue_dir="" queue_limit="0"
mc: <ERROR> Unable to set 'notify_redis:1 address=127.0.0.1:6379 format=namespace key=bucketevents password=yoursecret queue_dir= queue_limit=0' to server. We encountered an internal error, please try again. (ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|version":"","credent|..., bigger context ...|{"version":"","credential":{"expiration":"0001-01-01T00:00:00Z|...).
```

Simultaneously server logs loads of Errors, does not enable notifications:
```
API: SetConfigKV()
Time: 16:29:27 UTC 03/17/2021
DeploymentID: eac6762c-8990-47cd-887d-07a448076f80
RequestID: 166D2E22A5FA5E31
RemoteHost: 127.0.0.1
Host: localhost:9000
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2021-02-19T05-34-40Z
Error: ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|version":"","credent|..., bigger context ...|{"version":"","credential":{"expiration":"0001-01-01T00:00:00Z|... (*errors.errorString)
       5: cmd/api-errors.go:2009:cmd.toAPIErrorCode()
       4: cmd/admin-handlers.go:992:cmd.toAdminAPIErrCode()
       3: cmd/admin-handlers.go:1048:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-config-kv.go:130:cmd.adminAPIHandlers.SetConfigKVHandler()
       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()

API: SetConfigKV()
Time: 16:29:28 UTC 03/17/2021
DeploymentID: eac6762c-8990-47cd-887d-07a448076f80
RequestID: 166D2E22C98C0F3C
RemoteHost: 127.0.0.1
Host: localhost:9000
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2021-02-19T05-34-40Z
Error: ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|version":"","credent|..., bigger context ...|{"version":"","credential":{"expiration":"0001-01-01T00:00:00Z|... (*errors.errorString)
       5: cmd/api-errors.go:2009:cmd.toAPIErrorCode()
       4: cmd/admin-handlers.go:992:cmd.toAdminAPIErrCode()
       3: cmd/admin-handlers.go:1048:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-config-kv.go:130:cmd.adminAPIHandlers.SetConfigKVHandler()
       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()

API: SetConfigKV()
Time: 16:29:29 UTC 03/17/2021
DeploymentID: eac6762c-8990-47cd-887d-07a448076f80
RequestID: 166D2E230FCDF952
RemoteHost: 127.0.0.1
Host: localhost:9000
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2021-02-19T05-34-40Z
Error: ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|version":"","credent|..., bigger context ...|{"version":"","credential":{"expiration":"0001-01-01T00:00:00Z|... (*errors.errorString)
       5: cmd/api-errors.go:2009:cmd.toAPIErrorCode()
       4: cmd/admin-handlers.go:992:cmd.toAdminAPIErrCode()
       3: cmd/admin-handlers.go:1048:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-config-kv.go:130:cmd.adminAPIHandlers.SetConfigKVHandler()
       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
```

## Steps to reproduce the behavior
Failure above occurs on linux. My docker images contain minio, with a built in mc.
Server is using TLS certificates, however the client is running over loopback so uses `--ignore` to avoid hostname mismatch
minio server is started with `/usr/bin/docker-entrypoint.sh minio server /export`.

$ minio --version
minio version RELEASE.2021-02-24T18-44-45Z
$ mc --version
mc version RELEASE.2021-02-19T05-34-40Z

However tried to reproduce on mac, confirmed working under:
mc version RELEASE.2021-02-19T05-34-40Z
minio version RELEASE.2021-02-14T04-01-33Z

**Comment by harshavardhana** [comment]
> However tried to reproduce on mac, confirmed working under:
> mc version RELEASE.2021-02-19T05-34-40Z
> minio version RELEASE.2021-02-14T04-01-33Z

This looks like something is corrupted on your drives or your drives are returning incorrect content.

**Comment by shuckc** [comment]
Yes you are right, I deleted the contents of `/export/.minio.sys` and bounced the pod and it now works.

**Comment by harshavardhana** [comment]
> Yes you are right, I deleted the contents of `/export/.minio.sys` and bounced the pod and it now works.

Thanks closing the issue.

**Comment by shuckc** [comment]
Is there a nicer technique to fetch the configured notification ARNs from `mc`? It seems like a missing admin command, and pulling them from out from the console log from `minio` process (using `timeout` and `mc admin console`) is fairly ugly. Ended up with this in the unattended setup script: 

```
# log filesystem events to redis queue
if ! mc --insecure admin config get local/ notify_redis:1 | grep bucketevents; then
	echo "enabling notify_redis"
	mc --insecure admin config set local/ notify_redis:1 address="porl-redis:6379" format="access" key="bucketevents" password="HXPm..." queue_dir="" queue_limit="0"
	mc --insecure admin service restart local/
	sleep 5
fi

ARNS=$(timeout 1s mc --insecure admin console local/ | grep "SQS ARN")
ARNS=$(echo $ARNS | cut -f 2- -d : | tr -d "[:space:]")
echo "Got ARNS: $ARNS"

# enable logging for buckets
mc --insecure event add local/bucket-public $ARNS
```
 It's. less than ideal as the console log could cause the SQS log line to be out of the recent history, and the timeout to prevent the tail isn't very good. It would be better if there was a flag to trigger exit on completion/non-blocking.

**Comment by harshavardhana** [comment]
> Is there a nicer technique to fetch the configured notification ARNs from `mc`? It seems like a missing admin command, and pulling them from out from the console log from `minio` process (using `timeout` and `mc admin console`) is fairly ugly. Ended up with this in the unattended setup script:

mc admin info --json alias/ has the information @shuckc

**Comment by shuckc** [comment]
Great - indeed it does. 
```
$ mc --insecure admin info --json local/ | grep -Eo 'arn:minio:sqs:[a-zA-z0-9-]+:[0-9]+:redis'
arn:minio:sqs:eu-west-1:1:redis
```
