### ISSUE TITLE
Provide an --include option for the mirror command

### ISSUE THREAD

**Issue by lucasbasquerotto** [minio/mc#3652]
This is a **feature request**. I don't know if this is the right place to ask, because it's not a bug, but I don't think it's support either, because I don't think there's this (or an equivalent) feature.

Please, provide a way to sync a single file with a bucket, not uploading if the file is unchanged, which would be useful for big backup files (to avoid unneccessary uploads when comparing with `cp`), and also for directories with lots of files (to not try to sync each one individually). Using `cp` would upload every time in my understanding, and mirroring would mirror the entire directory (I tried specifying the file but returned an error saying that it must be a directory). For now I will mirror the directory.

I would expect an option similar to `awscli s3 --include`, just like there is already an equivalent `--exclude` option.

## mc --version
- mc version RELEASE.2021-03-12T03-36-59Z

## System information
- Docker container (minio/mc)

**Comment by dvaldivia** [comment]
I believe we compare etags when mirror is copying a prefix (which could be the object you want to copy), have you tried it? if soure and target etag are the same, no copying should happen

**Comment by lucasbasquerotto** [comment]
@dvaldivia Do you mean, retrieve the etag of the local and of the remote object, compare and, if different, run `cp`?

I don't see much documentation about etag in the docs. Searching for `site:https://docs.min.io etag` using Google I found only a `stat` command that returned, among other data, the `Etag`.

Running for the local and remote files, I get only the etag of the remote file (I don't know if the local file should have an etag):

```bash
sh-4.4# mc stat /var/log/main/bg/backup.20210318.211628.18073.log 
Name      : backup.20210318.211628.18073.log
Date      : 2021-03-18 21:18:00 UTC 
Size      : 112 KiB 
Type      : file 
Metadata  :
  Content-Type       : text/plain 
  X-Amz-Meta-Mc-Attrs: atime:1616102342#717811700/gid:1000/mode:33188/mtime:1616102280#347811700/uid:1000 

sh-4.4# mc stat backup/mybucket-myapp-backup/log/app/bg/backup.20210318.211628.18073.log 
Name      : backup.20210318.211628.18073.log
Date      : 2021-03-18 23:55:51 UTC 
Size      : 112 KiB 
ETag      : 74c5835fd40c73ae286420da6f83fdad 
Type      : file 
Metadata  :
  Content-Type: text/plain 
```

**Comment by dvaldivia** [comment]
@lucasbasquerotto the etags are only present when inside a MinIO server, as you can see, you should mirror a single file, in this case your log, and check if both endup with the same etag, that will confirm you that `mc mirror --watch` won't copy it again after it resumes

**Comment by lucasbasquerotto** [comment]
@dvaldivia Thanks for the reply. you said:

> as you can see, you should mirror a single file, in this case your log

**Comment by malveo** [comment]
This was already a feature request: https://github.com/minio/mc/issues/2859

**Comment by lucasbasquerotto** [comment]
@malveo Oh, I see! (I must have searched only opened issues)

In any case, the last non-bot answer was posted by _deekoder_:

> we will work on this feature and make it available in the subsequent releases of mc. Thanks for this suggestion!

But then, it was closed and the title has **wontfix**. Is it that there's no intent in adding the `include` option? Or something else?

**Comment by mqu** [comment]
would be interested with this option to : having a directory with logs files and I would like to include or exclude some files :

- I would like to mirror only JSON files, having this in source directory:

```
root@gitlab:/var/log/gitlab/gitlab-rails# ls -alt application*  | grep -v 2021
-rw-r--r-- 1 git git   32974 juil. 29 11:00 application_json.log
-rw------- 1 git git   15713 juil. 29 11:00 application.log
-rw-r--r-- 1 git git 1645804 juil. 28 12:52 application_json.log.1.gz
-rw------- 1 git git  633077 juil. 28 12:52 application.log.1.gz
-rw-r--r-- 1 git git 2683180 juil. 25 00:17 application_json.log.2.gz
-rw------- 1 git git  991049 juil. 25 00:17 application.log.2.gz
-rw-r--r-- 1 git git 2053537 juil. 18 00:16 application_json.log.3.gz
-rw------- 1 git git  654301 juil. 18 00:16 application.log.3.gz
-rw-r--r-- 1 git git 2670027 juil. 11 00:15 application_json.log.4.gz
-rw------- 1 git git  852140 juil. 11 00:15 application.log.4.gz
-rw-r--r-- 1 git git 2776310 juil.  4 00:00 application_json.log.5.gz
-rw------- 1 git git  861715 juil.  4 00:00 application.log.5.gz
-rw-r--r-- 1 git git 2342526 juin  27 00:59 application_json.log.6.gz
-rw------- 1 git git  722244 juin  27 00:59 application.log.6.gz
```
- this is a Gitlab/rails directory with some logs. There is application, api, production, audit log files
- logs files a duplicated : raw format and json.
