### ISSUE TITLE
User Access Key is truncated if longer than 20 characters when running mc admin user list

### ISSUE THREAD

**Issue by theo-pnv** [minio/mc#3657]
## Expected behavior
Running `mc admin user list ALIAS` with user access keys longer than 20 characters outputs the whole access keys.

## Actual behavior
Running `mc admin user list ALIAS` is truncating the user access keys longer than 20 characters. It's appending `...` from the 17th character. I don't know much about go, but it looks like it's related to [this line](https://github.com/minio/mc/blob/d4fbfb597501a672c8165784ab82d5f1f5de39f6/cmd/admin-user-add.go#L95). Which makes me think the truncation is intended. If so, what is the purpose of truncating long access keys, and could there be an option to override the max length?

Not knowing the whole access key makes it very difficult to remove users for example (I don't know how to remove the users other than deleting the minio instance).

## Steps to reproduce the behavior
```
shell> mc admin user add <ALIAS> 123456789012345678901234567890 secretkey
Added user `123456789012345678901234567890` successfully.

shell> mc admin user list <ALIAS>
enabled    12345678901234567...
```
^ Access key is truncated.

## mc --version
```
shell> mc --version
mc version RELEASE.2021-03-10T05-59-20Z
```

## System information
Windows10 (20H2 - 19042.867)
AMD Ryzen 5 3600 6-Core Processor                 3.60 GHz
16GB RAM

I'm using the mc command on Windows to interact with a minio container.

**Comment by kannappanr** [comment]
@theo-pnv 

you can use the `json` flag

```
$ mc admin user list myminio 
enabled    minio12345minio12...  readwrite           
$ mc admin user list myminio --json
{
 "status": "success",
 "accessKey": "minio12345minio12345minio",
 "policyName": "readwrite",
 "userStatus": "enabled"
}
```

**Comment by harshavardhana** [comment]
Only the list output is truncated, since these are longer keys. Keeping access keys more 20 characters is a bit of a misnomer and quite useless.

Access keys are public entities keeping them complex is rather meaningless. Invest your efforts on stronger secret keys instead.
