### ISSUE TITLE
mc mirror doesn't copy versionId

### ISSUE THREAD

**Issue by to-ny** [minio/mc#3658]
## Context
We have two isolated MinIO instances.
We would like to copy the content of one instance to the other.
Our major constraint is: **We need to keep the same version IDs on the target as the source.**
We tried using `mc mirror`, `mc copy`, `rclone`, etc. but none of them preserve the same version ID.

## Expected behavior

Having the same version ID on the target as the source for each file version.

## Actual behavior

The version IDs are different (re-generated I presume).

## Steps to reproduce the behavior

1. Spin up 2 independent MinIO instances (source and target)

```bash
docker run --name minio_source -d  \
   -p 9000:9000 \
   -e "MINIO_ACCESS_KEY=minio" \
   -e "MINIO_SECRET_KEY=minio123" \
   minio/minio:RELEASE.2020-10-18T21-54-12Z server /data{1...4}
docker run --name minio_target -d  \
   -p 9001:9000 \
   -e "MINIO_ACCESS_KEY=minio" \
   -e "MINIO_SECRET_KEY=minio123" \
   minio/minio:RELEASE.2020-10-18T21-54-12Z server /data{1...4}
```

2. Create a bucket with versioning enabled on source and target then upload a file in source's bucket

```bash
docker run -it --rm --entrypoint=/bin/sh --network host minio/mc
mc alias set source http://localhost:9000 minio minio123
mc alias set target http://localhost:9001 minio minio123
mc mb source/test
mc version enable source/test
mc mb target/test
mc version enable target/test
mc cp ~/.bashrc source/test
```

3. Execute `mc mirror` between source and target

```bash
# see versionId on source
mc ls --versions source/test

# perform mirroring
mc mirror source/test target/test

# see versionId on target (expected = same, actual = different)
mc ls --versions target/test
```

## mc --version
- mc version RELEASE.2021-02-14T04-28-06Z

## System information
Our 2 MinIO instances are running the version `RELEASE.2020-10-18T21-54-12Z`.
They both have one bucket with versioning enabled.

## Additionnal information
I imagine the scenario I submit may be out of scope for the purpose of the `mirror` command.
If that's the case, could you please advice us on the best approach to achieve our goal?

Thank you for your help.

**Comment by to-ny** [comment]
Additional observation: I can't manage to copy the different versions of the objects from one place to another.

I'm starting to think I'm doing this the wrong way. Should I copy the actual folders and metadata from the filesystem directly instead of going through the S3 API? 

I have the impression that would be the only way to preserve the versions and the version IDs.

**Comment by harshavardhana** [comment]
To preserve versionIds you should use server side replication @to-ny https://docs.min.io/docs/minio-bucket-replication-guide.html
