### ISSUE TITLE
[Low Priority / Security / HTTP Best Practices] Missing "Accept" Header on Requests to MinIO via client

### ISSUE THREAD

**Issue by teward** [minio/mc#3659]
When running with a WAF in place that enables Apache/WebServer Best Practices per Apache2 or OWASP guidelines, `mc admin` commands and potentially other commands trigger certain WAF rules which match the "Request Missing Accept Header" policy.

What this means is when you execute a command that triggers on this, and the WAF is enforcing mode, you may get a 403 error and an HTML response that's not expected.

The ideal fix is to add a header to the HTTP request sent to the MinIO server that is essentially `Accept: */*` unless we expect *certain* types of output to be returned, in which case set the `Accept:` header with the correct MIME type header.

## Steps to reproduce the behavior

    mc admin policy add minio user-ro user-ro.json

or some kind of "set" command that expects a response and you are on an WAF enforcing the "Missing Accept Header" policy.

## Expected behavior

    Added policy `user-ro` successfully.

## Actual behavior

Errors out with an invalid response:

    mc: <ERROR> Unable to add new policy. Failed to parse server response: invalid character '<' looking for beginning of value.

## mc --version

`mc version RELEASE.2020-10-03T02-54-56Z`

## System information

MinIO server running latest on ubuntu 20.04.

MinIO client running as above on ubuntu 20.04.

**IF REQUIRED, I can set up a lab instance of MinIO behind such a WAF if testing is required.  If this is the case, please let me know on the thread here and I'll get the lab env set up.**

**Comment by harshavardhana** [comment]
> When running with a WAF in place that enables Apache/WebServer Best Practices per Apache2 or OWASP guidelines, `mc admin` commands and potentially other commands trigger certain WAF rules which match the "Request Missing Accept Header" policy.

mc talks to the S3 endpoint, it is never to handle all these ad-hoc uses. Ask AWS SDK to first implement it then we will follow. .
