### ISSUE TITLE
`mc ilm import` no longer accepting JSON, fails with documentation examples

### ISSUE THREAD

**Issue by teward** [minio/mc#3660]
## Expected behavior
`mc ilm import <<EOF ...` will actually import JSON per the documentation at https://docs.min.io/docs/minio-bucket-lifecycle-guide.html

## Actual behavior
Hard-fail errors:

    mc: <ERROR> Unable to set new lifecycle rules. The XML you provided was not well-formed or did not validate against our published schema.

## Steps to reproduce the behavior

Follow documentation at https://docs.min.io/docs/minio-bucket-lifecycle-guide.html using any of the examples provided there (I used the 3.2 example to remove delete markers)

Attempt to apply ILM.  It hard-fails.  No JSON seems to be supported, even valid examples.

## mc --version
- (paste output of `mc --version`)
```$ mc --version
mc version RELEASE.2020-10-03T02-54-56Z```

## System information
Client: Ubuntu 20.04 amd64, latest minio Client.
Server: Ubuntu 20.04 amd64, latest minio Server.

**Comment by harshavardhana** [comment]
> mc version RELEASE.2020-10-03T02-54-56Z```

Upgrade to latest @teward and let us know.

**Comment by teward** [comment]
> > mc version RELEASE.2020-10-03T02-54-56Z```
> 
> Upgrade to latest @teward and let us know.

That fixed that, but now i'm getting what seems to be inconsistency between something on the Server side.  Pretty sure Ravind is digging into things and bringing up the concerns internally heh.

**Comment by ravindk89** [comment]
As a minor TL;DR for anyone else who has a similar issue - it *looks* like the minio server thought it was running in filesystem mode. Clearing the underlying data disks and restarting appears to have resolved that error and allowed issuing the ILM commands as expected.
