### ISSUE TITLE
 default part size to 16MiB

### ISSUE THREAD

**Issue by izznogood** [minio/mc#3668]
## Expected behavior
Hello,
In the new release of minio client( RELEASE.2021-03-23T05-46-11Z), there is this changelog:

- reduce default part size to 16MiB (#3654) (03/19/21) (Harshavardhana)

@Harshavardhana, you explain this:
```
part size moved from 128MiB to 16MiB as default to avoid memory build up in mc - let mc calculate the necessary multipart size for bigger files on its own.

@vadmeste has another PR to reduce memory usage by limiting concurrency along with this PR and @vadmeste should sufficiently cover large memory usage in mc.
```
I thought that this size would remain important in the case of large files
or is it possible to change this via an option (e.g. -metadata) or via a system parameter.

## Actual behavior

after this change, we had completely different behaviors depending on the servers on which we use it.

The point for which we have the most problem is when the size is calculated by default to 16MiB, we can not then send files larger than 15.66GB (~) to providers such as OVH which does not accept more than 1000 Chunks.

The only workaround we found for the moment is to stay on the old release.

## Steps to reproduce the behavior

dd if=/dev/zero of=18G.bin bs=1024 count=0 seek=$[1024*1024*18]
./mc cp 18G.bin ovh/test/

mc: <ERROR> Failed to copy `/test/18G.bin`. Part number must be an integer between 1 and 1000, inclusive
Total: 0 B, Transferred: 15.68 GiB, Speed: 32.54 MiB/s

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2021-03-23T05-46-11Z
## System information
- Ubuntu 20.04.2 LTS
- Ubuntu 20.04.2 LTS

**Comment by harshavardhana** [comment]
> The point for which we have the most problem is when the size is calculated by default to 16MiB, we can not then send files larger than 15.66GB (~) to providers such as OVH which does not accept more than 1000 Chunks.

This is an incorrect implementation of S3 API  by OVH. Although default is 16MiB if a higher part size is needed it's automatically picked to be higher by MinIO based in the S3 API requirement for 10000 parts.

You should ask OVH to fix their limitation we can't do anything here. I can upload 15GiB to AWS S3 properly.

**Comment by smiba** [comment]
Same issue on scaleway, wish there was an option to configure the part size as this is a deal breaker for using this software.

**Comment by harshavardhana** [comment]
> Same issue on scaleway, wish there was an option to configure the part size as this is a deal breaker for using this software.

You should move away from Scaleway if this is the most basic thing that doesn't work on their object storage offering. 

These parts of S3 API are expected to be compliant.

**Comment by smiba** [comment]
I think the issue is a bit more nuanced like that, there was no issue with MinIO Client while it was using 128MiB part size

On a 10Gbps connection the upload speed was easily 250% higher as well, as small part sizes where bottlenecking the actual upload process. I think not just scaleway/OVH users would benefit from a configurable part size, other S3 users that do not suffer from this error could get a speed improvement.

**Comment by harshavardhana** [comment]
> I think the issue is a bit more nuanced like that, there was no issue with MinIO Client while it was using 128MiB part size
> 
> On a 10Gbps connection the upload speed was easily 250% higher as well, as small part sizes are bottlenecking the actual upload process. I think not just scaleway/OVH users would benefit from a configurable part size, other S3 users that do not suffer from this error could get a speed improvement.

That doesn't make any sense. S3 spec allows default part size from 5MiB and why is there a 1000 part limit no idea. S3 spec clearly allows 10,000 parts per multipart operation. If this cannot be supported you need to ask your vendor why are they not compliant with most basic thing in S3 API.

There is no issue in mc here please ask your vendor to fix their implementation. mc works fine with MinIO and AWS S3 within the guidelines of the S3 spec.

**Comment by harshavardhana** [comment]
> I think the issue is a bit more nuanced like that, there was no issue with MinIO Client while it was using 128MiB part size
> 
> On a 10Gbps connection the upload speed was easily 250% higher as well, as small part sizes are bottlenecking the actual upload process. I think not just scaleway/OVH users would benefit from a configurable part size, other S3 users that do not suffer from this error could get a speed improvement.

If you want to manually use a workaround you can set 

> MC_UPLOAD_MULTIPART_SIZE=128MiB mc cp ...

Now with this setting - setting correct part size is your responsibility. So you should calculate this before upload. To have a generic approach and proper behavior my suggestion would to be ask your vendor to start complying with S3 spec. 

They shouldn't ask applications to diverge from the spec guidelines, unless it's niche requirement.  Here it's the most basic implementation detail that has been overlooked.

**Comment by smiba** [comment]
> If you want to manually use a workaround you can set
> 
> > MC_UPLOAD_MULTIPART_SIZE=128MiB mc cp ...
> 
> Now with this setting - setting correct part size is your responsibility. So you should calculate this before upload. To have a generic approach and proper behavior my suggestion would to be ask your vendor to start complying with S3 spec.

Much appreciated! This helps me out for now :)

I understand you want them to change, but with these "budget" providers you usually just have to go with the flow. I don't nearly store enough data with them to be worth their time.
