### ISSUE TITLE
"mc cat" and other subcommands waste numerous network roundtrips

### ISSUE THREAD

**Issue by occasionallydavid** [minio/mc#3672]
## Expected behavior

Running `mc cat alias/bucket/foo` produces one `GET` request when object `foo` exists in `bucket` of `alias`

If fetching `foo` fails, optionally issue additional requests to diagnose the cause, but preferably fail immediately.

## Actual behavior

mc validates the bucket exists (`HEAD /bucket?location=`), then validates the object exists (`HEAD /bucket/foo`), then finally fetches the object (`GET /bucket/foo`)

## Steps to reproduce the behavior

Observe mc much slower over a WAN than expected, run `mc` with `--debug` and notice wasteful networking

## mc --version

  RELEASE.2021-03-23T05-46-11Z

## System information

49ms WAN

**Comment by harshavardhana** [comment]
It's not waste `mc cat` predicts a few things about your object etc..

So whatever exists today is based on what we want `mc cat` to do. 

Such as 

- Get bucket location needs to be done to get the region to perform the request.
- it needs to validate if a user is trying to access the object is readable and is also not a directory.
- then it performs the get request.

Closing this issue as won't fix.

**Comment by occasionallydavid** [comment]
If either round-trip were necessary, they would also be performed by the clients produced by Amazon.  Mentally applying a `wontuse` label to `mc`, if this is the attitude towards 3x higher latency than expected in what is typically the most common operation in the S3 protocol, what else might I encounter later when attempting to depend on it?
