### ISSUE TITLE
MC_SECRET_$ALIAS is ignored

### ISSUE THREAD

**Issue by KizzyCode** [minio/mc#3675]
## Expected behavior
`mc` uses the `user:secret`-combination from the `MC_SECRET_$ALIAS` environment variable where `$ALIAS` is the remote alias as [suggested here](https://github.com/minio/mc/pull/1622)

## Actual behavior
`mc` ignores those environment variables

## Steps to reproduce the behavior
```
export MC_SECRET_filehorst="user:secret"
mc cp MyFile filehorst/my_bucket/
```

## mc --version
`mc version RELEASE.2021-02-19T05-34-40Z`

## System information
 - OS: `macOS Big Sur 11.2.3 (20D91)`
 - `mc` was installed via `brew install minio-mc`

**Comment by harshavardhana** [comment]
There is no MC_SECRET_ALIAS its called MC_HOST_ALIAS https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#specify-temporary-host-configuration-through-environment-variable

**Comment by Cajga** [comment]
@harshavardhana the link is dead and I cannot find the relevant docs. Could you please help out here? Thanks
