### ISSUE TITLE
Unable to setup monitoring endpoint. listen tcp: address 8081: missing port in address.

### ISSUE THREAD

**Issue by allebacco** [minio/mc#3693]
## Expected behavior

When executing the `mirror` command, I need to enable the Prometheus monitoring with the `--monitoring-port 8081`.

I expect that the `mc` tool starts the mirroring process and I can monitor it with HTTP requests to the `http://127.0.0.1:8081/metrics` URL. 

## Actual behavior

The MinIO client fails with the following error:
```text
mc: <ERROR> Unable to setup monitoring endpoint. listen tcp: address 8081: missing port in address.
```

## Steps to reproduce the behavior

The following command will reproduce the problem:
```bash
# Download the mc client and create an empty tmp folder
./mc mirror --watch --monitoring-port 8081  play/test1 ./tmp
```

## mc --version

```text
mc version RELEASE.2021-03-23T05-46-11Z
```

## System information

Linux Ubuntu 20.04.

**Comment by allebacco** [comment]
The mirroring with monitor is working as expected using the `--monitoring-port :8081` argument. I suspect that the problem could be in the https://github.com/minio/mc/blob/78e3c94f5a5c5d3541375ca17d6bf9e75c24e92d/cmd/mirror-main.go#L975 or in line 972.

The [ListenAndServe](https://golang.org/pkg/net/http/#ListenAndServe) method expect and address, not a port, while the documentation of the `--monitoring-port` is not clear about setting the entire listening address or only the port.

**Comment by harshavardhana** [comment]
> ```shell
> ```shell
> ./mc mirror --watch --monitoring-port 8081  play/test1 ./tmp
> ```
> ```

You need to provide `--monitoring-port :8081` due to parsing logic, it is better for us to change the command to `--monitoring-address` where correct value can be provided..
