### ISSUE TITLE
mc config get mqtt output is too cryptic when --json is used

### ISSUE THREAD

**Issue by GreatBahram** [minio/mc#3696]
## Expected behavior
Return a human-readable JSON output

## Actual behavior
It prints some gibberish output:
```bash
root@server# ./mc admin config get myminio/ notify_mq
notify_mqtt broker=tcp://localhost:1883 topic=minio password= username= qos=1 keep_alive_interval=0s reconnect_interval=0s queue_dir= queue_limit=0 
notify_mqtt:1 broker=tcp://localhost:1883 topic=minio password= username= qos=1 keep_alive_interval=0s reconnect_interval=0s queue_dir= queue_limit=0 

root@server# ./mc admin config get myminio/ notify_mq --json
{
 "status": "success",
 "value": "bm90aWZ5X21xdHQgYnJva2VyPXRjcDovL2xvY2FsaG9zdDoxODgzIHRvcGljPW1pbmlvIHBhc3N3b3JkPSB1c2VybmFtZT0gcW9zPTEga2VlcF9hbGl2ZV9pbnRlcnZhbD0wcyByZWNvbm5lY3RfaW50ZXJ2YWw9MHMgcXVldWVfZGlyPSBxdWV1ZV9saW1pdD0wIApub3RpZnlfbXF0dDoxIGJyb2tlcj10Y3A6Ly9sb2NhbGhvc3Q6MTg4MyB0b3BpYz1taW5pbyBwYXNzd29yZD0gdXNlcm5hbWU9IHFvcz0xIGtlZXBfYWxpdmVfaW50ZXJ2YWw9MHMgcmVjb25uZWN0X2ludGVydmFsPTBzIHF1ZXVlX2Rpcj0gcXVldWVfbGltaXQ9MCAK"
}
```
## mc --version
mc version RELEASE.2021-01-16T02-45-34Z

**Comment by harshavardhana** [comment]
> ## Expected behavior
> Return a human-readable JSON output
> 
> ## Actual behavior
> It prints some gibberish output:
> 
> ```shell
> root@server# ./mc admin config get myminio/ notify_mq
> notify_mqtt broker=tcp://localhost:1883 topic=minio password= username= qos=1 keep_alive_interval=0s reconnect_interval=0s queue_dir= queue_limit=0 
> notify_mqtt:1 broker=tcp://localhost:1883 topic=minio password= username= qos=1 keep_alive_interval=0s reconnect_interval=0s queue_dir= queue_limit=0 
> 
> root@server# ./mc admin config get myminio/ notify_mq --json
> {
>  "status": "success",
>  "value": "bm90aWZ5X21xdHQgYnJva2VyPXRjcDovL2xvY2FsaG9zdDoxODgzIHRvcGljPW1pbmlvIHBhc3N3b3JkPSB1c2VybmFtZT0gcW9zPTEga2VlcF9hbGl2ZV9pbnRlcnZhbD0wcyByZWNvbm5lY3RfaW50ZXJ2YWw9MHMgcXVldWVfZGlyPSBxdWV1ZV9saW1pdD0wIApub3RpZnlfbXF0dDoxIGJyb2tlcj10Y3A6Ly9sb2NhbGhvc3Q6MTg4MyB0b3BpYz1taW5pbyBwYXNzd29yZD0gdXNlcm5hbWU9IHFvcz0xIGtlZXBfYWxpdmVfaW50ZXJ2YWw9MHMgcmVjb25uZWN0X2ludGVydmFsPTBzIHF1ZXVlX2Rpcj0gcXVldWVfbGltaXQ9MCAK"
> }
> ```
> 
> ## mc --version
> mc version RELEASE.2021-01-16T02-45-34Z

Yes we need to address this..

**Comment by GreatBahram** [comment]
Sorry for the delay

`mc version RELEASE.2021-01-16T02-45-34Z`
