### ISSUE TITLE
mc mirror watch command is not working

### ISSUE THREAD

**Issue by mznet** [minio/mc#3700]
When I tried to mirror data from minio to another minio using `mc mirror --watch` command, the task was failed with the following error message:

```
 0 B / ?  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓ 
mc: <ERROR> Failed to perform mirroring readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<ListAllMyB|..., bigger context ...|<ListAllMyBucketsResult xmlns="http://s3.amazonaws.|...
```
But, When I tried mirroring without `--watch` command, It was okay. Is the problem occurring because the minio server version is too old?

I found the same issue(https://github.com/minio/mc/issues/3622). But I re-issue the problem because the issue had been closed without resolving the problem.

---
minio server version : 2019-10-12T01:39:57Z
Both minio servers are running on linux centos7

## Expected behavior
Continuously synchronizes the source and destination buckets and objects without error messages

## Actual behavior
Mirroring was failed with error message

## Steps to reproduce the behavior
`mc mirror --watch`

## mc --version
mc version RELEASE.2021-04-22T17-40-00Z

## System information
macOS Big Sur 11.2.2

**Comment by klauspost** [comment]
Upgrade your server or use an mc version that matches more closely.

**Comment by mznet** [comment]
@klauspost So, Is this problem occurring because of the stale minio server version?

**Comment by mirrornight** [comment]
mc mirror --watch minio to local not working
