### ISSUE TITLE
Unable to validate source / Signature does not match

### ISSUE THREAD

**Issue by Fabb111** [minio/mc#3705]
## Expected behavior
When using a `^` in the secret, it should work as with every other secret, too. In the Windows version everything works as expected.

## Actual behavior
The following response is sent:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><BucketName>example</BucketName><Resource>/example/</Resource><RequestId>EXAMPLE_REQUEST_ID</RequestId><HostId>EXAMPLE_HOST_ID</HostId></Error>
```

## Steps to reproduce the behavior
Have a `^` in your secret (e.g. `mc ls minio`)

- `mc alias set example https://s3.example.com exampleuser ex4mple!se^cret --api s3v4`
- `mc ls example`

## mc --version
`mc version RELEASE.2021-04-22T17-40-00Z`

## System information
Linux based distros (Debian as well as macOS)

**Comment by klauspost** [comment]
I think you may have it the other way around. On Windows the `^` is ignored when passed as a param:

```Go
package main

import (
	"flag"
	"fmt"
)

func main() {
	flag.Parse()
	fmt.Println("Hello, playground", flag.Args(), []byte(flag.Args()[0]))
}
```

Produces:

```
(Windows)
e:\temp\main>go run main.go abc^def
Hello, playground [abcdef] [97 98 99 100 101 102]

(Linux)
$ go run main.go abc^def
Hello, playground [abc^def] [97 98 99 94 100 101 102]
```

I suspect your secret doesn't contain the `^`.
