### ISSUE TITLE
mc windows connection forcibly closed

### ISSUE THREAD

**Issue by druid-matt** [minio/mc#3707]
## Expected behavior
Copying multiple large files from S3 to MinIO running in datacenter. Expected to see files copied quickly and without error.
## Actual behavior
Copying is very slow and I'm seeing pages and pages of errors. 
```
mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-200911.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-200911.csv.gz?partNumber=7&uploadId=1a3f9207-4f66-4b0a-87dc-42f700386d5c": write tcp 10.0.0.209:51022->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201310.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201310.csv.gz?partNumber=2&uploadId=e1ecf00c-769f-4f7e-82b0-fa5c77df910e": write tcp 10.0.0.209:51259->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201603.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201603.csv.gz?partNumber=2&uploadId=22b59d38-fff1-43da-baee-6c09c1e32282": write tcp 10.0.0.209:51510->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201602.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201602.csv.gz?partNumber=1&uploadId=089ecc66-e568-46cc-a820-af950fd3174e": write tcp 10.0.0.209:51518->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201609.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201609.csv.gz?partNumber=2&uploadId=0651e58b-1ae7-4d8d-a754-a0d41c916b96": write tcp 10.0.0.209:51563->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201605.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201605.csv.gz?partNumber=3&uploadId=92b6a5f4-c358-4554-bbc5-78a5bf91cf54": write tcp 10.0.0.209:51515->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201509.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201509.csv.gz?partNumber=5&uploadId=8b2bde9b-f9f7-42fb-af08-015b5b3063c5": write tcp 10.0.0.209:51371->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201611.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201611.csv.gz?partNumber=7&uploadId=3f336820-7ad1-4d62-8ac4-f7eecc58a36e": write tcp 10.0.0.209:51560->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
```

## Steps to reproduce the behavior
mc --insecure cp -r s3/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/ altinity/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2021-04-22T17-40-00Z
## System information
Windows 10 Pro

**Comment by harshavardhana** [comment]
@druid-matt this closure is from AWS S3 not MinIO 

> mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-200911.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-200911.csv.gz?partNumber=7&uploadId=1a3f9207-4f66-4b0a-87dc-42f700386d5c": write tcp 10.0.0.209:51022->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
> mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201310.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201310.csv.gz?partNumber=2&uploadId=e1ecf00c-769f-4f7e-82b0-fa5c77df910e": write tcp 10.0.0.209:51259->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
> mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201603.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201603.csv.gz?partNumber=2&uploadId=22b59d38-fff1-43da-baee-6c09c1e32282": write tcp 10.0.0.209:51510->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
> mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201602.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201602.csv.gz?partNumber=1&uploadId=089ecc66-e568-46cc-a820-af950fd3174e": write tcp 10.0.0.209:51518->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
> mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201609.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201609.csv.gz?partNumber=2&uploadId=0651e58b-1ae7-4d8d-a754-a0d41c916b96": write tcp 10.0.0.209:51563->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
> mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201605.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201605.csv.gz?partNumber=3&uploadId=92b6a5f4-c358-4554-bbc5-78a5bf91cf54": write tcp 10.0.0.209:51515->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
> mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201509.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201509.csv.gz?partNumber=5&uploadId=8b2bde9b-f9f7-42fb-af08-015b5b3063c5": write tcp 10.0.0.209:51371->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.
> mc.exe: <ERROR> Failed to copy `https://s3.amazonaws.com/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201611.csv.gz`. Put "https://minio-k8s1.min.io:30303/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/data-201611.csv.gz?partNumber=7&uploadId=3f336820-7ad1-4d62-8ac4-f7eecc58a36e": write tcp 10.0.0.209:51560->64.71.151.66:30303: wsasend: An existing connection was forcibly closed by the remote host.

@druid-matt ^^

**Comment by harshavardhana** [comment]
> mc --insecure cp -r s3/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/ altinity/altinity-clickhouse-data/nyc_taxi_rides/data/tripdata/

Also better to use `mc mirror` instead of `mc cp -r`
