### ISSUE TITLE
Failed to perform mirroring 

### ISSUE THREAD

**Issue by andrescodas** [minio/mc#3711]
## Expected behavior

no mirroring, see the logs below

## Actual behavior

I get the error `The request signature we calculated does not match the signature you provided` only with the mirror command.  Other commands work. See [here](https://github.com/minio/mc/files/6436912/mc.txt) the output of:

- cat ~/.mc/config.json 
- mc ls COS/my-bucket-name/mnt/disk2/user/project/experiments/noreg_noise_batch_4
- mc mirror --debug --overwrite -w COS/my-bucket-name/mnt/disk2/user/project/experiments/noreg_noise_batch_4 noreg_noise_batch_4

## Steps to reproduce the behavior

I don't know how to reproduce it in a public environment.  Please let me know if I can provide more debug information

## mc --version
- (paste output of `mc --version`)

$ mc --version
mc version RELEASE.2021-04-22T17-40-00Z

## System information

$ uname -a
Linux 367e42a20b59 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andrescodas** [comment]
I just saw this issue https://github.com/minio/mc/issues/3203#issuecomment-624154347

I'm not sure if it is relevant to my case.  If it is, then the error information could be better informative

**Comment by harshavardhana** [comment]
> * mc mirror --debug --overwrite -w COS/my-bucket-name/mnt/disk2/user/project/experiments/noreg_noise_batch_4 noreg_noise_batch_4

You cannot use `--watch` or `-w` with Cleversafe its MinIO only functionality - remove `-w` and it will work fine. 

```
mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 3526
Accept-Ranges: bytes
Content-Type: application/xml
Date: Thu, 06 May 2021 17:43:58 GMT
Server: Cleversafe
X-Amz-Request-Id: eee52e9d-adaa-45e4-a8b8-2b7a57b18062
X-Clv-Request-Id: eee52e9d-adaa-45e4-a8b8-2b7a57b18062
X-Clv-S3-Version: 2.5
```

**Comment by andrescodas** [comment]
thanks for the prompt response!.  I suggest to provide this information on incompatibility in the error information

**Comment by harshavardhana** [comment]
> thanks for the prompt response!. I suggest to provide this information on incompatibility in the error information

There is no way for us to know that if the S3 server responds back with generic errors @andrescodas
