### ISSUE TITLE
mc du should do a single listing

### ISSUE THREAD

**Issue by klauspost** [minio/mc#3712]
## Expected behavior

`mc du myminio/mybucket` performs one recursive listing and accumulates results based on the returned values.

## Actual behavior

`mc du myminio/mybucket` performs separate calls per prefix (recursively) which is many, times (typical several order of magnitudes) slower than a single call.

## Steps to reproduce the behavior

Compare performance of a large bucket with and without this patch:

```
diff --git a/cmd/du-main.go b/cmd/du-main.go
index 249b8881..6d371523 100644
--- a/cmd/du-main.go
+++ b/cmd/du-main.go
@@ -124,7 +124,7 @@ func du(urlStr string, timeRef time.Time, withVersions bool, depth int, encKeyDB
 	contentCh := clnt.List(globalContext, ListOptions{
 		TimeRef:           timeRef,
 		WithOlderVersions: withVersions,
-		Recursive:         false,
+		Recursive:         true,
 		ShowDir:           DirFirst,
 	})
 	size := int64(0)
@@ -145,7 +145,7 @@ func du(urlStr string, timeRef time.Time, withVersions bool, depth int, encKeyDB
 			continue
 		}
 
-		if content.Type.IsDir() {
+		if false && content.Type.IsDir() {
 			depth := depth
 			if depth > 0 {
 				depth--
```

## mc --version

`master`

## System information

Not relevant.

**Comment by vadmeste** [comment]
@klauspost this should be fixed with this PR, https://github.com/minio/mc/pull/3737.

Closing
