### ISSUE TITLE
mc seems capped at 300MB/s on NVMe drives

### ISSUE THREAD

**Issue by idealtech-i3dlabs** [minio/mc#3713]
## Expected behavior
MinIO is not capped at 300 MB/sec when copying objects

## Actual behavior
mc cp is capped at 300 MB/sec for some reason. 
warp client (S3 benchmarking) works as intended, I get very good numbers in the GB/s.

## Steps to reproduce the behavior
mc cp <some_file>
some_file can be :
- random data
- /dev/zero data
To create the file, I tried :
fallocate -l 100G <some_file>
truncate -s 100G <some_file>

## mc --version
- RELEASE.2021-04-22T17-40-00Z

## minio server version
RELEASE.2021-04-22T15-44-28Z

## System information
Ubuntu 20.04
Bare-metal
MinIO one instance, not distributed
512GB ram
12 disks x 16T, micron 9300 (3.4GB/s write when using dd)
25Gbps NICs (but network is not involved in this setup)

mc runs on localhost
minio server runs on localhost

## Troubleshooting
Tested couple of things with @eco-minio @ravindk89 on Slack (Thanks guys!)
At this point, I feel it may be an OS configuration problem or a MinIO client issue.

I am available to test additional things if you need me to and make MinIO even better, and I'm intrigued if other people have seen this behavior?
I am testing out (in the meantime) the Go SDK to see if using that to copy objects might be working as fast as "warp" tool.

**Comment by klauspost** [comment]
@idealtech-i3dlabs Are you comparing with `-concurrent=1`?  I was unable to find your thread on Slack. Could you share a link for background?

**Comment by ravindk89** [comment]
@klauspost https://minio.slack.com/archives/C3NDUB8UA/p1620238198366100

We're not currently documenting the `--concurrent` argument, so it didn't come up during troubleshooting.

**Comment by klauspost** [comment]
@harshavardhana I am talking `--concurrent` parameter on warp. I don't know what else you are talking about ;)

**Comment by ravindk89** [comment]
@idealtech-i3dlabs so @harshavardhana is speaking to `mc cp` behavior for single-file. From some internal discussion, the summary is that S3 isn't necessarily built for single-file performance. Distributed multi-file read/write is more the expected workload, as I understand it.

_However_, it might be worth trying `mc cp --disable-multipart` and see what happens by writing the file as one large block. If you could give that a shot it would be good.

It might also be good to re-run warp with the `--concurrent 1` param as @klauspost mentioned to see what benchmarks look like with single-file workloads.

**Comment by harshavardhana** [comment]
> 4 node cluster, bare-metal:
> 
> mc cp --disable-multipart file100g ALIAS/path
> (mc is remote on another server, same subnet)
> 100 MB/s
> 
> With the flag on:
> 150MB/s
> 
> Unfortunately this hinders performances by a lot

Its a single stream performance, what you need is to upload multiple parts in parallel if your disk can handle it.

We may plan to add that in future. If you want to increase the speed of your single stream upload you will have to use an SDK and configure the concurrency yourself.

**Comment by idealtech-i3dlabs** [comment]
Thank you. Any chance you've got examples on how to configure concurrency ? 
Go or Python would be awesome...

**Comment by klauspost** [comment]
@idealtech-i3dlabs [PutObjectOptions](https://pkg.go.dev/github.com/minio/minio-go/v7#PutObjectOptions) allows you to control Multipart (on/off) and part sizes as well as the number of concurrent uploads `NumThreads`.
