### ISSUE TITLE
mc mirror ignores tags

### ISSUE THREAD

**Issue by patrickrad** [minio/mc#3717]
## Expected behavior
'mc mirror' should copy tags belonging to an object

## Actual behavior
'mc mirror' copies the object data, and the meta data attributes but not the object tags

## Steps to reproduce the behavior
>mc cp --attr "MYATTR1=123" --tags "MYTAG1=456" ~/tmp/abc.txt  m1/bucket1/

>mc tag list  m1/bucket1/abc.txt
Name   : http://127.0.0.1:10001/bucket1/abc.txt ()
MYTAG1 : 456

> mc mirror --watch --remove   m1/  m2/

>mc tag list  m2/bucket1/abc.txt
Name : http://127.0.0.1:10002/bucket1/abc.txt ()
No tags found

## mc --version
mc version RELEASE.2021-05-12T03-10-11Z

## System information
>uname -a
Linux lnxpatrickr1 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

**Comment by vadmeste** [comment]
Well, unfortunately, we need an additional network call to get tags of a specific object, which can make mirroring slow.

Only GetObject returns 'x-amz-tagging-count' header. So we might call GetObjectTagging only in that case.

**Comment by klauspost** [comment]
@vadmeste Maybe, additionally it should be possible to disable with a flag if implemented.

**Comment by vadmeste** [comment]
> @vadmeste Maybe, additionally it should be possible to disable with a flag if implemented.

We have --preserve as well, maybe we can use it to copy expensive information such as tagging.

**Comment by kpostekk** [comment]
Is there any updates on implementing this feature?
