### ISSUE TITLE
mc pipe not working

### ISSUE THREAD

**Issue by ricosega** [minio/mc#3718]
## Expected behavior
mc pipe should work

## Actual behavior
whatever I do I get the following error:
```
mc: <ERROR> Unable to parse --attr value: specified metadata should be of form key1=value1;key2=value2;... and so on.
```
## Steps to reproduce the behavior
Any kind of mc pipe command:
```
cat file | mc pipe destination
mongodump | mc pipe destination
```

## mc --version
```
mc version RELEASE.2021-05-12T03-10-11Z
```

## System information
```
Linux mininuc 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
> cat file | mc pipe destination

Just specify `--attr` as a work-around @ricosega

**Comment by ricosega** [comment]
@harshavardhana this was working in previous release **RELEASE.2021-04-22T17-40-00Z** so I prefer to use it instead of changing code.
It is planned to be solved?
