### ISSUE TITLE
mc admin policy info --json returns b64-encoded Policy

### ISSUE THREAD

**Issue by ravindk89** [minio/mc#3721]
## Expected behavior

Prior to the 2021-05-12 release, issuing `mc admin policy info ALIAS/POLICYNAME --json` would return a full JSON representation of the policy metadata + the actual JSON policy.

```sh
mc-RELEASE.2021-04-22T17-40-00Z]$ ./mc admin policy info play readwrite --json
{
 "status": "success",
 "policy": "readwrite",
 "policyJSON": {
  "Version": "2012-10-17",
  "Statement": [
   {
    "Effect": "Allow",
    "Action": [
     "s3:GetObject",
     "s3:ListAllMyBuckets",
     "s3:ListBucket",
     "s3:PutObject",
     "s3:DeleteObject",
     "s3:GetBucketLocation"
    ],
    "Resource": [
     "arn:aws:s3:::*"
    ]
   }
  ]
 },
 "isGroup": false
}

```

## Actual behavior

The `--json` output of the command returns the base64-encoded representation of the policy:

```sh
mc admin policy info play consoleAdmin --debug --json
mc: <DEBUG> GET /minio/admin/v3/info-canned-policy?name=consoleAdmin HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.2021-05-13T14-24-55Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20210513//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210513T144359Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: text/plain; charset=utf-8
Date: Thu, 13 May 2021 14:44:00 GMT
Server: nginx/1.14.0 (Ubuntu)
Vary: Origin
X-Amz-Request-Id: 167EA775C699641C
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Let's Encrypt
mc: <DEBUG>  >> Expires: 2021-07-23 21:19:40 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Organization: Digital Signature Trust Co.
mc: <DEBUG>  >> Expires: 2021-09-29 19:21:40 +0000 UTC
mc: <DEBUG> Response Time:  261.772308ms

{
 "status": "success",
 "policy": "consoleAdmin",
 "policyJSON": "eyJWZXJzaW9uIjoiMjAxMi0xMC0xNyIsIlN0YXRlbWVudCI6W3siRWZmZWN0IjoiQWxsb3ciLCJBY3Rpb24iOlsiYWRtaW46KiJdfSx7IkVmZmVjdCI6IkFsbG93IiwiQWN0aW9uIjpbInMzOioiXSwiUmVzb3VyY2UiOlsiYXJuOmF3czpzMzo6OioiXX1dfQo=",
 "isGroup": false
}
```

This likely occured as part of the madmin migration [commit](https://github.com/minio/mc/commit/6c3ac00e1812c77fda38ec7e97fe8731c5e9de9a#diff-5b1788f1fc45e86883221460259ab10c80013476cc4f89789aa339368415a6aaL76-L88) the `mc admin policy info` command changed the madmin endpoint.

## Steps to reproduce the behavior

Issue `mc admin policy info ALIAS/POLICYNAME --json` . The output of `policyJSON` is b64 encoded instead of an embedded JSON document.

## mc --version

RELEASE.2021-05-12 and later

## System information

Operating System: Manjaro Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.10.26-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: AMD Radeon RX 5700 XT

**Comment by harshavardhana** [comment]
This is fixed here https://github.com/minio/mc/pull/3731
