### ISSUE TITLE
XAmzContextSHA256Mismatch when PUTing to an AWS Signature Version 4 Endpoint with STREAMING-AWS4-HMAC-SHA256-PAYLOAD

### ISSUE THREAD

**Issue by thurse93** [minio/mc#3723]
We use minoc to mirror tenants between two object stores (CEPH). For that we alias source and target tenant:

```
mc alias set <source/target> <host> <access-key> <secret> --api s3v4
```

and mirror it like so:

```
mc mirror <source> <target> --json --overwrite --remove
```

## Expected behavior

We expect the mirror operation to complete without errors

## Actual behavior

Mirroring fails on PUT requests to <target> with *X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD* and a non-zero *X-Amz-Decoded-Content-Length*:

```http
 minioc: <DEBUG> PUT /tenant-id-3417/objekte/einstellungen HTTP/1.1
Host: vxzpcephrgwp02:8080
User-Agent: MinIO (linux; amd64) minio-go/v7.0.9 minioc/RELEASE.2021-02-14T04-28-06Z
Content-Length: 193
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20210427/arch/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=**REDACTED**
Content-Type: application/octet-stream
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20210427T090606Z
X-Amz-Decoded-Content-Length: 20
Accept-Encoding: gzip

minioc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 232
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Type: application/xml
Date: Tue, 27 Apr 2021 09:06:07 GMT
X-Amz-Request-Id: tx0000000000000000438ca-006087d3fe-1cfcc63-dev

<?xml version="1.0" encoding="UTF-8"?><Error><Code>XAmzContentSHA256Mismatch</Code><BucketName>tenant-id-3417</BucketName><RequestId>tx0000000000000000438ca-006087d3fe-1cfcc63-dev</RequestId><HostId>1cfcc63-dev-arch</HostId></Error>minioc: <DEBUG> Response Time:  87.010561ms
```

When we use *--api s3v2* on the target, it works without an issue.

## Steps to reproduce the behavior

see above

## mc --version
```
mc version RELEASE.2021-02-14T04-28-06Z
```

**Comment by harshavardhana** [comment]
@thurse93 this is not a bug in `mc` it's a bug in Ceph's implementation of `STREAMING-AWS4-HMAC-SHA256-PAYLOAD`.  

> Mirroring fails on PUT requests to with _X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD_ and a non-zero _X-Amz-Decoded-Content-Length_:

mc mirror is well tested across many object storage implementations MinIO, AWS S3, Wasabi etc.
