### ISSUE TITLE
dl.min.io doesn't offer FreeBSD mc releases

### ISSUE THREAD

**Issue by Funzinator** [minio/mc#3724]
## Expected behavior
https://min.io/download and https://dl.min.io/client/mc list current releases for mc.

## Actual behavior
The latest build I was able to find was from 2017: https://dl.min.io/client/mc/freebsd-amd64.tar.gz

## Steps to reproduce the behavior
Check https://dl.min.io/client/mc/release/ for a freebsd-amd64 release (or arm for that matter because arm is tier one since FreeBSD 13).

Adding it to the releases page is probably just an entry to the list of releases and the build will just succeed. I was able to build it from source using `go get -u` (like for almost every Go application).

## mc --version
n/a

## System information
n/a

**Comment by harshavardhana** [comment]
We had stopped this a long time ago @Funzinator - FreeBSD builds on its own 

- https://www.freshports.org/www/minio for MinIO
- https://www.freshports.org/www/minio-client for MinIO client

**Comment by Funzinator** [comment]
Thanks. You are right. I've overlooked the minio-client package.
