### ISSUE TITLE
mc mb --region=cn-north-1 minio/mybucket1

### ISSUE THREAD

**Issue by AIlvxiaobu** [minio/mc#3726]
## Expected behavior
Setting the region parameter correctly(cn-north-1)
## Actual behavior
default `us-east-1`
## Steps to reproduce the behavior
mac@MacdeMacBook-Pro ~ % mc mb --region=cn-north-1 minio/mybucket1
Bucket created successfully `minio/mybucket1`.
mac@MacdeMacBook-Pro ~ % mc stat minio/mybucket1
Name      : mybucket1/
Size      : 0 B    
Type      : folder 
Metadata  :
  Versioning: Un-versioned
  Location: us-east-1
  Policy: none

## mc --version
- (paste output of `mc --version`)
mac@MacdeMacBook-Pro ~ % mc --version
mc version RELEASE.2021-05-18T03-39-44Z
## System information
Darwin MacdeMacBook-Pro.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
> mac@MacdeMacBook-Pro ~ % mc mb --region=cn-north-1 minio/mybucket1

The same credentials used in the US and rest are not available for China region - you cannot create china region buckets from  https://s3.amazonaws.com endpoint. 

You need to configure alias such that your endpoint is china region endpoint.
