### ISSUE TITLE
A Buggy autocomplete with fish shell

### ISSUE THREAD

**Issue by karmicdude** [minio/mc#3727]
## Actual behavior
![mino-client](https://i.imgur.com/kpg4Cht.png)
Autocomplete substitutes parameter + description as commandline

## Steps to reproduce the behavior
```
➜ mcli --autocompletion
mcli: Your shell is set to '/usr/bin/fish', by env var 'SHELL'.
mcli: enabled autocompletion in your 'fish' rc file. Please restart your shell.
```

```
➜ cat completions/mcli.fish

function __complete_mcli
    set -lx COMP_LINE (commandline -cp)
    test -z (commandline -ct)
    and set COMP_LINE "$COMP_LINE "
    /usr/bin/mcli
end
complete -f -c mcli -a "(__complete_mcli)"
```

`mcli [tab]` or `mcli --[tab]`
## mc --version
```                                                                                                                                                                      
mcli version RELEASE.2021-02-19T05-34-40Z
```
## System information
```
fish, version 3.2.2
Archlinux  5.12.6-arch1-1
```

**Comment by karmicdude** [comment]
I tested this further on the official docker container with the fish installation and on alpine edge, testing repository. The behavior is exactly the same there.

**Comment by harshavardhana** [comment]
our support for fish shell comes from https://pkg.go.dev/github.com/posener/complete looks like that is where the issue is..

**Comment by lnchan** [comment]
This bug is still present. Copyright information is now even proposed as a suggestion, and subcommands have no autocompletion whatsoever. Could we re-open this issue?

**Comment by arthurlt** [comment]
Seconded re-opening issue

**Comment by klauspost** [comment]
You can ask upstream: https://github.com/posener/complete
