### ISSUE TITLE
mc admin info report incorrect cluster usage info 

### ISSUE THREAD

**Issue by MoonJustry** [minio/mc#3728]
## Expected behavior
show correct usage info, Used should more than 100GiB， buckets count is 3， and objects more than 30.

`mc du mycluster/big-bucket`
![image](https://user-images.githubusercontent.com/12591294/119757562-ae830400-bed7-11eb-932b-1f499ac4bb43.png)

It seems that when there are not so many objects in the bucket, everything is normal. When the number is large, the exception is displayed

## Actual behavior
`mc admin info mycluster`
![image](https://user-images.githubusercontent.com/12591294/119757665-db371b80-bed7-11eb-9c10-bb66cb42ad95.png)

## Steps to reproduce the behavior
upload enough objects，then execute `mc admin info <alias>`

## mc --version
- (paste output of `mc --version`)
```shell
mc --version
mc version RELEASE.2021-03-23T05-46-11Z
```

## System information
minio cluster based on release-2021-04-18, 4 nodes and a 4TB disk per node

**Comment by harshavardhana** [comment]
> upload enough objects，then execute `mc admin info <alias>`

Usage calculation takes its own time to populate the usage value, it is not supposed to be instantaneous right after you upload objects. 

It runs in probabilistic cycles that would calculate the usage as the scanner completes its various runs.

**Comment by MoonJustry** [comment]
But I can’t understand why the number of buckets is calculated incorrectly, it was correct before then.

**Comment by MoonJustry** [comment]
> > upload enough objects，then execute `mc admin info <alias>`
> 
> Usage calculation takes its own time to populate the usage value, it is not supposed to be instantaneous right after you upload objects.
> 
> It runs in probabilistic cycles that would calculate the usage as the scanner completes its various runs.

I found the default data scanner cycle is 1 minute，but 9 hours later，the admin info has not been updated.
