### ISSUE TITLE
mc should allow copying recursively the entire bucket in order to change attributes

### ISSUE THREAD

**Issue by matthewdarwin** [minio/mc#3735]
## Expected behavior

```mc cp --recursive -attr x-amz-acl=public-read host/bucket/ host/bucket/```

This would set the `public-read` permission on **all** objects within the bucket (Note: copy from/to the same bucket)

## Actual behavior

```mc: <ERROR> Copying a folder into itself is not allowed. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.```

If you copy using one object at a time within the bucket, or using a prefix it works as expected. For example, you can copy objects starting with "s"

```mc cp --recursive -attr x-amz-acl=public-read host/bucket/s host/bucket```

## Steps to reproduce the behavior

```mc version RELEASE.2021-05-26T19-19-26Z```

**Comment by harshavardhana** [comment]
> `mc cp --recursive -attr x-amz-acl=public-read host/bucket/ host/bucket/`

We do not support x-amz-acl @matthewdarwin in `--attr` we only support this for `x-amz-meta-<key>`

**Comment by matthewdarwin** [comment]
Still `mc cp` does not allow attribute changes for all objects in the bucket.

**Comment by harshavardhana** [comment]
> Still `mc cp` does not allow attribute changes for all objects in the bucket.

@matthewdarwin for that use `mc mirror` instead of `mc cp`

**Comment by matthewdarwin** [comment]
In my testing `mc mirror --overwrite --attr x-amz-acl=public-read host/bucket/ host/bucket/` doesn't do anything.  (it runs very quickly).  Also tried without the --overwrite flag.

**Comment by harshavardhana** [comment]
> In my testing `mc mirror --overwrite --attr x-amz-acl=public-read host/bucket/ host/bucket/` doesn't do anything. (it runs very quickly). Also tried without the --overwrite flag.

As I said we do not support `x-amz-acl` header @matthewdarwin

**Comment by matthewdarwin** [comment]
`x-amz-acl` does work on 'mc cp'.
