### ISSUE TITLE
mc admin info not updated

### ISSUE THREAD

**Issue by sumarnaz** [minio/mc#3741]
Hello.
I removed a lot of buckets from our minio, but the command:
`mc admin info <service>`
still shows the original number of buckets and occupied space
## Expected behavior
the mc command should show updated informations
## Actual behavior
the mc command shows old informations
## mc --version
- (paste output of `mc --version`)
`mc version RELEASE.2021-06-08T01-29-37Z`

**Comment by harshavardhana** [comment]
> I removed a lot of buckets from our minio, but the command:
> `mc admin info <service>`
> still shows the original number of buckets and occupied space

This is not reflected in real time - this is updated lazily as the usage scanner picks up the 
change in namespace. This is not a bug an expected behavior.

**Comment by sumarnaz** [comment]
Hello.
thanks for your answer.
I removed the buckets yesterday. How often the scanner updates this info?
Thanks

**Comment by harshavardhana** [comment]
> I removed the buckets yesterday. How often the scanner updates this info?

It can be days depending on the namespace, speed, hardware. There is no one way to know..

**Comment by sumarnaz** [comment]
Ok, so how can I know how many buckets and storage is used?
I don't need "real-time" stats, but somehow I need to know if I'm running out-of-space or how many Gb/Tb a given tenant is using on my system.
Can you suggest some other method?
Thanks

**Comment by harshavardhana** [comment]
> Ok, so how can I know how many buckets and storage is used?
> I don't need "real-time" stats, but somehow I need to know if I'm running out-of-space or how many Gb/Tb a given tenant is using on my system.

You need to manage that externally @sumarnaz by setting up node_exporter and monitor your disk usage patterns - it will be more accurate.  Usage is a metrics calculation it can be fast depending on the speed of the hardware. 

You can make scanner more aggressive by tuning the scanner parameters `mc admin config set alias/ scanner `

**Comment by sumarnaz** [comment]
Ok.
Thank you very much.
Regards
