### ISSUE TITLE
mirror --watch --remove not working

### ISSUE THREAD

**Issue by rombat** [minio/mc#3744]
## Expected behavior
`mirror --watch --remove` is supposed to remove files of the target if they've been removed from the source

## Actual behavior
I's not. And if i rename a file on source (ex: A.jpg > B.jpg), it's uploaded in target but the initial file is still here in target. So both of them are in target (A.jpg and B.jpg)

## Steps to reproduce the behavior
i'm running `mc mirror -w -a --remove -sc GLACIER sourcefolder target`.
If i kill the process, delete some folders and rerun it, files are not removed either.

## mc --version
- RELEASE.2021-06-08T01-29-37Z

## System information
Windows 7 64bit
target: Scaleway C14 Cold Storage (S3 compatible)

**Comment by kannappanr** [comment]
I tried to repro it against MinIO with latest mc on Windows 10 and was unable to repro the issue

**Comment by harshavardhana** [comment]
> I tried to repro it against MinIO with latest mc on Windows 10 and was unable to repro the issue

The user is using it against Scaleway, we may just close the issue it mc works with AWS S3 and MinIO.
