### ISSUE TITLE
mc: <ERROR> Unable to enable auto encryption: `SetEncryption` is not supported for `filesystem`.

### ISSUE THREAD

**Issue by ravisankarit** [minio/mc#3745]
## Expected behavior

 I am following the documentation and trying to setup https://docs.min.io/docs/minio-kms-quickstart-guide.html encryption for the bucket.

when i am executing command  " mc encrypt set sse-s3 myminio/bucket/ "

Encryption should be set on the bucket.

## Actual behavior

I have tried using Mac os and centos i am getting the same error

i am getting the error 

mc: <ERROR> Unable to enable auto encryption: `SetEncryption` is not supported for `filesystem`.

## Steps to reproduce the behavior

installed MINIO and followed the steps  given in https://docs.min.io/docs/minio-kms-quickstart-guide.html

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2021-04-22T17-40-00Z

**Comment by harshavardhana** [comment]
> when i am executing command " mc encrypt set sse-s3 myminio/bucket/ "

You need to first create `mc alias set myminio ... `  please read the help from `mc alias set --help`

**Comment by ravisankarit** [comment]
I have setup alias and tried to create still it is same
please find the log below.

INML2D1HLVCG:Project ravi$ mc alias set myminio http://127.0.0.1:9000 minio minio123
Added `myminio` successfully.
INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio
mc: <ERROR> Unable to enable auto encryption. Bucket name cannot be empty.
INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio /Users/ravi/Documents/teststore/london
mc: <ERROR> Unable to enable auto encryption: `SetEncryption` is not supported for `filesystem`.
INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio /Users/ravi/Documents/teststore/test
mc: <ERROR> Unable to enable auto encryption: `SetEncryption` is not supported for `filesystem`.
INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio /Users/ravi/Documents/teststore/test
mc: <ERROR> Unable to enable auto encryption: `SetEncryption` is not supported for `filesystem`.
INML2D1HLVCG:Project ravi$
