### ISSUE TITLE
Issue with setting the encryption on the bucket

### ISSUE THREAD

**Issue by ravisankarit** [minio/mc#3746]
## Expected behavior
I am following the documentation and trying to setup https://docs.min.io/docs/minio-kms-quickstart-guide.html encryption for the bucket.

when i am executing command " mc encrypt set sse-s3 myminio/bucket/ "

Encryption should be set on the bucket.

## Actual behavior

I have setup alias and tried to set encryption
please find the log below.

 mc alias set myminio http://127.0.0.1:9000 minio minio123
Added myminio successfully.
INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio
mc: Unable to enable auto encryption. Bucket name cannot be empty.
INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio /Users/ravi/Documents/teststore/london
mc: Unable to enable auto encryption: SetEncryption is not supported for filesystem.
INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio /Users/ravi/Documents/teststore/test
mc: Unable to enable auto encryption: SetEncryption is not supported for filesystem.
INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio /Users/ravi/Documents/teststore/test
mc: Unable to enable auto encryption: SetEncryption is not supported for filesystem.
INML2D1HLVCG:Project ravi$

## Steps to reproduce the behavior

mc alias set myminio http://127.0.0.1:9000 minio minio123

mc encrypt set sse-s3 myminio /Users/ravi/Documents/teststore/london

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2021-06-13T17-48-22Z

**Comment by harshavardhana** [comment]
> mc alias set myminio http://127.0.0.1:9000 minio minio123
> Added myminio successfully.
> INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio
> mc: Unable to enable auto encryption. Bucket name cannot be empty.
> INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio /Users/ravi/Documents/teststore/london
> mc: Unable to enable auto encryption: SetEncryption is not supported for filesystem.
> INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio /Users/ravi/Documents/teststore/test
> mc: Unable to enable auto encryption: SetEncryption is not supported for filesystem.
> INML2D1HLVCG:Project ravi$ mc encrypt set sse-s3 myminio /Users/ravi/Documents/teststore/test
> mc: Unable to enable auto encryption: SetEncryption is not supported for filesystem.
> INML2D1HLVCG:Project ravi$

@ravisankarit you seem to not reading the docs at all on how to use these commands.  Please refer to the documentation here https://docs.min.io/docs/minio-client-complete-guide

and also `mc encrypt set sse-s3 --help`  the alias needs to point to bucket in this manner `mc encrypt set sse-s3 myminio/<your-bucketname>`
