### ISSUE TITLE
[documentation] command mc config is `missing from readme

### ISSUE THREAD

**Issue by ComeBurguburu** [minio/mc#3749]
## Expected behavior
mc config should be in the list of Readme's mc command

## Actual behavior
config is not in the list of mc command

## Steps to reproduce the behavior
search config in Readme

**Comment by harshavardhana** [comment]
There is no `mc config` command - there is `mc admin config` - its right here https://github.com/minio/mc/blob/master/docs/minio-admin-complete-guide.md#config

**Comment by ComeBurguburu** [comment]
`
$ mc config
NAME:
  mc config - configure MinIO client

USAGE:
  mc config COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  host  add, remove and list hosts in configuration file

FLAGS:
  --config-dir value, -C value  path to configuration folder (default: "/home/cburgu/.mc")
  --quiet, -q                   disable progress bar display
  --no-color                    disable color theme
  --json                        enable JSON lines formatted output
  --debug                       enable debug output
  --insecure                    disable SSL certificate verification
  --help, -h                    show help`

**Comment by harshavardhana** [comment]
> `
> $ mc config
> NAME:
> mc config - configure MinIO client
> 
> USAGE:
> mc config COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]
> 
> COMMANDS:
> host add, remove and list hosts in configuration file
> 
> FLAGS:
> --config-dir value, -C value path to configuration folder (default: "/home/cburgu/.mc")
> --quiet, -q disable progress bar display
> --no-color disable color theme
> --json enable JSON lines formatted output
> --debug enable debug output
> --insecure disable SSL certificate verification
> --help, -h show help`

This has been renamed to `mc alias` - `mc config` is long deprecated.
