### ISSUE TITLE
GetObject does not support zip option

### ISSUE THREAD

**Issue by xuzikun2003** [minio/mc#3753]
On the minio website, a folder can be downloaded as a zip
![image](https://user-images.githubusercontent.com/25806935/124369220-38806400-dc1e-11eb-8f17-35b4302c712d.png)

However, the class GetObjectArgs provided by the SDK does not provide a zip option
https://minio-java.min.io/io/minio/GetObjectArgs.html

I am wondering why the SDK cannot support zip download but the web UI can support.

**Comment by harshavardhana** [comment]
There is no such API in S3, download as zip is an application behavior - you should implement this yourself.

This is not meant for `mc`
