### ISSUE TITLE
set-json doesn't allow Action `s3:*`

### ISSUE THREAD

**Issue by charlie-ht** [minio/mc#3763]
## Expected behavior
`mcli policy set-json $traces_policy_file minio/traces`

should work, where traces_policy_file is

```
traces_policy_file=$(mktemp 'tmp.XXXXX.json')
cat <<EOF >$traces_policy_file
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}",
        "arn:aws:s3:::${aws:username}/*"
      ]
    }
  ]
}
EOF
```

## Actual behavior

`mcli: <ERROR> Unable to set-json policy `tmp.zdgSD.json` for `local/traces`. unsupported action 's3:*'.`

## Steps to reproduce the behavior

```
traces_policy_file=$(mktemp 'tmp.XXXXX.json')
cat <<EOF >$traces_policy_file
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}",
        "arn:aws:s3:::${aws:username}/*"
      ]
    }
  ]
}
EOF
mcli policy set-json $traces_policy_file minio/traces
rm $trace_policy_file
```

## mc --version
`mcli version RELEASE.2021-06-08T01-29-37Z`

**Comment by harshavardhana** [comment]
This is on purpose anonymous access needs to define required actions not everything. 

It is done to avoid rookie mistakes by allowing all S3 calls for buckets.
