### ISSUE TITLE
Use AWS EC2 IAM policy to access S3 bucket

### ISSUE THREAD

**Issue by graphik55** [minio/mc#3767]
Hello,

I like to ask if it is possible to use Minio MC on an EC2 instance with an attached IAM policy?
Similar to Mino Gateway: https://docs.min.io/docs/minio-gateway-for-s3.html

Kind regards,
graphik

**Comment by harshavardhana** [comment]
@graphik55 no it is not possible - you need to wrap it around in another shell script by fetching credentials and pass it to mc using the environment variable

https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#rotating-credentials
