### ISSUE TITLE
Error when mc connect admin console (XML syntax error on line 1: invalid character entity &display (no semicolon).)

### ISSUE THREAD

**Issue by BaoDevFS** [minio/mc#3773]
## Expected behavior
Anyone help me.
## Actual behavior
mc: <ERROR> Unable to initialize new alias from the provided credentials. XML syntax error on line 1: invalid character entity &display (no semicolon).
![image](https://user-images.githubusercontent.com/43994589/129487603-6c490fd6-5b3e-47a7-8281-57ad05c0d746.png)

## Steps to reproduce the behavior
1: ./minio server ./data --console-address :9002 &
2: ./mc alias set myminio/ http://127.0.0.1:9002 admin admin
3: mc error
## mc --version
mc version RELEASE.2021-07-27T06-46-19Z

minio version RELEASE.2021-08-05T22-01-19Z
## System information
ubuntu 20.4

**Comment by kannappanr** [comment]
@BaoDevFS You cannot connect to console using mc. Please use port 9000.
