### ISSUE TITLE
FEATURE: Add directory watch support to move commands

### ISSUE THREAD

**Issue by sjdrc** [minio/mc#3774]
## Desired behavior
I would like to use `mc` in a one way push to s3 solution for data archival purposes. For context, we have an application on a remote server that generates hundreds of gigabytes of data per day, and that all needs to be moved off server for long term storage, and after copy, disk space needs to be freed up for the next day of local storage.

`mc mirror --watch` _almost_ does what I want, but does not remove the local source files after copy.

It would be fantastic if `mc mv` had `--watch` support, so that I could simply set up job running a command like:
```
mc mv --recursive --watch /my/local/folder s3/mybucket
```
and any new files dropped into the folder structure will be automatically uploaded, and then removed locally after successful upload is confirmed.

I would likely use a systemd service to manage the running of this command

## Current solution
I currently have a workaround solution to run a cronjob hourly to perform the upload. This is the script:
```bash
flock --exclusive --nonblock /tmp/datasync.lock mc mv --recursive --continue --preserve /my/local/folder s3/mybucket
```
I lock a file when the upload is running to prevent multiple instances from spinning up and treading on each other

## Steps to reproduce the behavior
N/A

## mc --version
- (paste output of `mc --version`)
`mc version RELEASE.2021-07-27T06-46-19Z`

## System information
Ubuntu 18.04 server

Also - sorry for using the bug report form for a feature request. I posted in the MinIO slack about this and was asked to post here, but there is only a template for bug reports.

**Comment by k-five** [comment]
I saw your issue on Slack and it can be a good feature to have with `mc` .
Just wanted to say you can have a better workaround with the issue.

**1**
You can use `mc mirror` as usual and at the same time watch your bucket and `PUT` method , so when the file is uploaded and finished `mc watch` notifies you, with which you can delete that file 

**2**
You can **mount** your S3 storage or a bucket and just use simple `mv` in your server (mv to the mounted path in your server == upload && delete)

**Comment by sjdrc** [comment]
Can this please be reopened? I think this is a valid feature request.

**Comment by harshavardhana** [comment]
> Can this please be reopened? I think this is a valid feature request.

No we do not time for these feature requests @sjdrc - feel free to send a PR if this is an important requirement for you.
