### ISSUE TITLE
mc rb --force is enough for site-wide removal of buckets

### ISSUE THREAD

**Issue by rluetzner** [minio/mc#3776]
## Expected behavior

As I understand the code in rb-main.go a site-wide removal (e.g. `mc rb <alias>`) should require both the `--force` and `--dangerous` options.

## Actual behavior

It is possible to simply use `mc rb --force <alias>` to remove all buckets the aliased user has access to.

## Steps to reproduce the behavior

1. Run minio as a local S3 server: `./minio server ./data`
2. Setup a `mc alias` for the local S3 server: `./mc alias set local http://localhost:9000 minioadmin minioadmin`
3. Create some buckets and upload objects, e.g.
    ```bash
    for i in {0..5}; do ./mc mb "local/new$i"; ./mc cp mc "local/new$i"; done
    ```
4. Execute `./mc rb --force local`.

## mc --version
- mc version RELEASE.2021-07-27T06-46-19Z

## System information

- Using an openSUSE-Leap-15.2 WSL2 instance on Windows.

**Comment by kannappanr** [comment]
@rluetzner Thanks for filing the info and the reproducer. Will send a PR to fix the issue.
