### ISSUE TITLE
minio client killed due to out-of-memory when using `mc mirror` when mirroring many files

### ISSUE THREAD

**Issue by torjuskd** [minio/mc#3781]
Use case: Trying to copy a large volume of files (large both in number and size, size total about 8Ti),
From one Kubernetes/GlusterFS persistent volume claim to another.
We want to use the `mc mirror`-command since there are live file changes that
we'd like reflected in the destination.
Additionally, the files have to be copied to the larger pvc before the current one runs
full/runs out of inodes (whichever comes first) as we have to store an increasing amount
of files for our users.

Running `GOMAXPROCS=1; mc mirror --preserve --watch --exclude "*minio.sys*" /a/bucket1 /b/bucket1`
On large buckets consumes a lot of memory (>20Gi) and results in mc being killed by `oom_reaper`
(similar to the problem stated in this issue https://github.com/minio/minio/issues/11780)

## Expected Behavior

Mirroring large buckets consumes less than 20Gi memory and the process is not killed by `oom_reaper`.

## Current Behavior

1. `mc` is rutinely killed for consuming large amounts of memory.
2. Output from the `mc mirror`-command is:
` 0 B / ? ____________________________________________________________________`

So it seems that `mc` is unable to determine the size of the bucket (presumably because it is large).
Furthermore, there is no indication of any progress in mirroring/copying files.

## Possible Solution

- Could there be any parameters that work better with mirroring large amounts of files?
- Would `mc mirror` behave better if we eg. run `mc copy` to copy most/all of the files before running `mc mirror`?
- Suggestions for fixes or workarounds are much appreciated.
- (Because of resource-limitations, we are not able to assign 50-60GB ram as was done in this issue (https://github.com/minio/minio/issues/11780))

## Steps to Reproduce (for bugs)

"Pseudo-description":
1. Create two large storage volumes for storing minio-files and buckets
2. Fill one of the buckets with a high amount of files (eg. one bucket with 300 000 document-files (pdfs))
2. Attempt to use `mc mirror` to mirror the files from source to destination.

## Context

How has this issue affected you? What are you trying to accomplish?:
We are unable to mirror the desired files. If we don't find a solution for
copying the files from the current location, storage will run out and minio
will become unstable/unusable.

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2020-06-14T18-32-17Z`
* Server setup and configuration: minio docker image running on kubernetes cluster, GlusterFS PVCs
* Operating System and version (`uname -a`): Linux minio-75d675d567-zwswc 3.10.0-1160.31.1.el7.x86_64 minio/minio#1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 Linux

**Comment by vadmeste** [comment]
@torjuskd we have this PR, https://github.com/minio/mc/pull/3629/files, which should fix the issue.

Meanwhile, can you try with:
```
export GOMAXPROCS=1
export MC_UPLOAD_MULTIPART_THREADS=1
```

**Comment by torjuskd** [comment]
@vadmeste That's interesting, thank you!

I will try setting those and initiate another run after we are done with some planned downtime the coming week.

**Comment by torjuskd** [comment]
Tried it again, running `mc mirror` for every bucket, with 36 buckets total. Unfortunately ran into the same issue.
Would it be better to run one for the entire area (all buckets)? Are there other things we can try?

**Comment by mrsrvman** [comment]
+1
You are using the VirtualMemory function from the library https://github.com/shirou/gopsutil
This function just reads /proc/meminfo.
This file does not use cgroup and displays information from the host.

Solution options
1. Check for presence of "guest" in host.Virtualization (gopsutil) and use the CgroupMem function.
2. Make the environment variable MAXMEMORY, which explicitly limit the maximum available memory.

**Comment by mrsrvman** [comment]
https://github.com/shirou/gopsutil/pull/996

**Comment by torjuskd** [comment]
Hi,
we solved this some time ago by effectively disallowing writes/creates/deletes for a period and using `mc cp` which perfomed vastly better both in terms of time to complete and memory consumption (as might be expected, given the differences between the operations).
Thanks a lot for the help and activity on the issue! Will close now as I have nothing more to add.

**Comment by mlazowik** [comment]
@torjuskd hi, could you reopen this issue? IMO it's still valid, `mc cp` is a workaround, not an actual solution
