### ISSUE TITLE
mc: <ERROR> Unable to get service status. Failed to parse server response: invalid character '<' looking for beginning of value.

### ISSUE THREAD

**Issue by waem14** [minio/mc#3784]
## Expected behavior

Run "mc admin info [service]" should return service health

## Actual behavior

`mc: <ERROR> Unable to get service status. Failed to parse server response: invalid character '<' looking for beginning of value. (0) admin-info.go:83 cmd.clusterStruct.String(..)`

## mc --version
- (paste output of `mc --version`)

mc version RELEASE.2021-07-27T06-46-19Z

## System information
[monadmin@sg-bimon-6001 .mc]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by waem14** [comment]
It caused by the DNS. If I used full hostname like below. It won't have an issue.

mc alias set biminpoc_intern http://sg-minpoc-6004.serv1.serv.local:9000 minioadmin minioadmin

**Comment by deajan** [comment]
Got the same issue, was caused by a web server responding on the url instead of minio.
A `curl https://my.domain.tld` showed that.
