### ISSUE TITLE
Missing download for latest release

### ISSUE THREAD

**Issue by halkyon** [minio/mc#3789]
There is a missing download for RELEASE.2021-07-27T06-46-19Z here: https://dl.minio.io/client/mc/release/linux-amd64/

There are downloads for RELEASE.2021-09-02T09-21-27Z but that is only a tag, not latest release on Github.

As a result, the mc mint install steps are broken:

```
++ curl --retry 10 -Ls -o /dev/null -w '%{url_effective}' https://github.com/minio/mc/releases/latest
++ sed 's/https:\/\/github.com\/minio\/mc\/releases\/tag\///'
+ MC_VERSION=RELEASE.2021-07-27T06-46-19Z
+ '[' -z RELEASE.2021-07-27T06-46-19Z ']'
+ test_run_dir=/mint/run/core/mc
+ wget --quiet --no-check-certificate --output-document=/mint/run/core/mc/mc https://dl.minio.io/client/mc/release/linux-amd64/mc.RELEASE.2021-07-27T06-46-19Z
The command '/bin/sh -c ./build/mc/install.sh' returned a non-zero code: 8
```

**Comment by harshavardhana** [comment]
Latest release is not 07-27 https://github.com/minio/mc/releases/tag/RELEASE.2021-09-02T09-21-27Z

@kannappanr release notes are missing

**Comment by harshavardhana** [comment]
Fixed and added release notes.

**Comment by halkyon** [comment]
Thank you!
