### ISSUE TITLE
`ls` is to greedy, actual result for alias/bucket/dirname/basename is  alias/bucket/dirname/basename.*

### ISSUE THREAD

**Issue by hillar** [minio/mc#3791]
## Expected behavior

https://github.com/minio/mc#shell-aliases
>You may add shell aliases to override your common Unix tools.
>> alias ls='mc ls'

https://github.com/minio/mc/blob/f661334f3d61c870fdf55f1db238ea7268175ad5/docs/minio-client-complete-guide.md#5-everyday-use
> Everyday Use
>> You may add shell aliases to override your common Unix tools.
>>> alias ls='mc ls'

mc ls alias/bucket/dirname/basename returns only exact match 

```
# mc ls alias/bucket/dirname/basename
[2021-09-07 22:07:06 BST]  22MiB basename
```

## Actual behavior

mc ls alias/bucket/dirname/basename returns greedy * match 

```
# mc ls alias/bucket/dirname/basename
[2021-09-07 22:07:06 BST]  22MiB basename
[2021-09-07 22:07:06 BST]  2MiB basename.foo
[2021-09-07 22:07:06 BST]  1MiB basename.bar
[2021-09-07 22:07:06 BST]  1MiB basenamewhatever
```

## mc --version
- mc version RELEASE.2021-09-02T09-21-27Z

**Comment by harshavardhana** [comment]
@hillar S3 API provides prefix matches for all objects matching the same prefix. This is an expected behavior although `ls` will behave as expected on POSIX.   S3 API behavior is different. 

We simply comply with whatever is returned for the `ls` call.   The current behavior is the "expected" behavior here.

**Comment by hillar** [comment]
ok, it is ""expected"" if you look from S3 side, 
however you are advertising it as **"You may add shell aliases to override your common Unix tools."**
So please be laud in your documentation, that it is is actually not so. 



`ls`will match prefix and break your shell scritps and `ls`will not exit with error, if object does not exist and ...
