### ISSUE TITLE
Error backup if filename length >= 244b

### ISSUE THREAD

**Issue by replikonio** [minio/mc#3809]
## Expected behavior
No error.
it can not add a suffix but copy it to a temporary directory and then move it

## Actual behavior
Error like this:
September 24th 2021, 02:00:14.830        mc: <ERROR> Failed to copy `http://***.**.***.***:9000/inquiries/inquiry-13088/reasoned-judgment/FW ╨б╨╛╨│╨╗╨░╤Б╨╛╨▓╨░╨╜╨╕╨╡  ╨┐╨╗╨░╤В╨╡╨╢╨╡╨╣  ╨Ю╨Ю╨Ю ╨У╨Ъ ╨Р╨╗╤М╤П╨╜╤Б ╨╕╨╜╨╜ 7801562100_14 ╤И╤В  ╨╛╤В 01.03.2021.msg`. open /mnt/backup/dump/inquiries/inquiry-13088/reasoned-judgment/FW ╨б╨╛╨│╨╗╨░╤Б╨╛╨▓╨░╨╜╨╕╨╡  ╨┐╨╗╨░╤В╨╡╨╢╨╡╨╣  ╨Ю╨Ю╨Ю ╨У╨Ъ ╨Р╨╗╤М╤П╨╜╤Б ╨╕╨╜╨╜ 7801562100_14 ╤И╤В  ╨╛╤В 01.03.2021.msg.part.minio: file name too long

## Steps to reproduce the behavior
create filename with length name 255butes
Due to the fact that the .part.minio suffix is added to the file when copying, the file name length becomes more than 255 bytes, and this is a limitation of the file system.

**Comment by harshavardhana** [comment]
This is unfortunate - this is similar to browsers that cannot allow certain file lengths. Unfortunately, this is not possible, please fix your file names.
