### ISSUE TITLE
Minio client is not able to get the minio tenant info 

### ISSUE THREAD

**Issue by Bhagi33** [minio/mc#3817]
Hi Team,
I have deployed minio operator with 4.2.8 version.
And I have tenant deployed .. trying to do LDAP configuration with mc client.. 

i configured the mc client successfully..
But “mc admin info minio” is not working as expected 
Error:
Unable to get service status 

please can you help me to resolve this issue..

**Comment by Bhagi33** [comment]
./mc admin info testme
mc: <ERROR> Unable to get service status. Failed to parse server response: invalid character 'C' looking for beginning of value.

**Comment by klauspost** [comment]
@Bhagi33 What does `./mc admin info --debug testme` print?

**Comment by Bhagi33** [comment]
PLease find the attached screenshot.
![image](https://user-images.githubusercontent.com/68953135/135970600-bcce9375-7379-4dc4-9adb-e220ab99c12d.png)

**Comment by harshavardhana** [comment]
If you are going to talk to MinIO instance that is configured with HTTPS and the endpoint you are providing is HTTP - how is this supposed to work? 

Make sure to use the `https://` for the endpoint when you are using `mc alias set` and also make sure to add `--insecure` flag to trust the certs from your deployment.

**Comment by Bhagi33** [comment]
Hi Harsh,

even https --insecure flag also not working. can you help me. minio cluster is using inbuilt available certs only.

![image](https://user-images.githubusercontent.com/68953135/135976897-9b38c58f-49a6-49b0-8921-d498918e7917.png)

**Comment by harshavardhana** [comment]
Add `--insecure` flag for all your commands.

**Comment by Bhagi33** [comment]
Thanks harsh its working
