### ISSUE TITLE
Mc client unable to get service details of minio cluster

### ISSUE THREAD

**Issue by Bhagi33** [minio/mc#3821]
Hi Team,

i configured mc client and trying to do administration tasks with mc client.
But mc client is not able to get the details from cluster.
Please support on priority to fix the issue

![image](https://user-images.githubusercontent.com/68953135/135970275-1d194fa8-a80e-4868-9df1-e11df36ce352.png)
![image](https://user-images.githubusercontent.com/68953135/135970772-17a64c6a-1cb1-4b1a-a9d2-696e67bdc762.png)

**Comment by klauspost** [comment]
@Bhagi33 You have probably set up your load balancer wrong or you are connecting to the wrong port. Closing as this is not an issue with mc.

If you need more detailed help look into our [subscription options](https://min.io/pricing).

**Comment by harshavardhana** [comment]
> Hi Team,
> 
> i configured mc client and trying to do administration tasks with mc client. But mc client is not able to get the details from cluster. Please support on priority to fix the issue
> 
> ![image](https://user-images.githubusercontent.com/68953135/135970275-1d194fa8-a80e-4868-9df1-e11df36ce352.png) ![image](https://user-images.githubusercontent.com/68953135/135970772-17a64c6a-1cb1-4b1a-a9d2-696e67bdc762.png)

Well the error is clear 'mc' is configured with http when server expects https.
