### ISSUE TITLE
can not update using a private mirror server

### ISSUE THREAD

**Issue by erfantkerfan** [minio/mc#3828]
## Expected behavior
mc client could be updated using a private mirror server

## Actual behavior
looks like this arg is not available 

## Steps to reproduce the behavior
mc update [mirrot_url]

## mc --version
mc version RELEASE.2021-10-07T04-19-58Z

**Comment by erfantkerfan** [comment]
could you please take notice of this feature?

**Comment by harshavardhana** [comment]
> could you please take notice of this feature?

@erfantkerfan not a priority at the moment.

**Comment by harshavardhana** [comment]
This is already fixed..  and supported in latest releases

```
mc update https://dl.minio.io/client/mc/hotfixes/linux-amd64/archive/mc.RELEASE.2022-03-03T21-12-24Z.hotfix.12ad456a.sha256sum
```

**Comment by erfantkerfan** [comment]
Thanks
This helps a lot in airtight servers.
