### ISSUE TITLE
mc du doesn't report the correct size (return double the actual value) when called at the root (for S3 endpoints)

### ISSUE THREAD

**Issue by geobeau** [minio/mc#3836]
Hello, when `mc du` is run on the topest part of an endpoint, the final result is multiplied by two.

The reason is related to #3737. Basically by default `du` is called with `depth=1` (the cli configure 0 but it's changed in `mainDu`. The issue is that there is two way to handle recursiveness in `mc du`, one is handled by the client and the other one is in the logic of the du function itself. When depth is equal to 1, the client is configured to perform a recursive listing:
```
	// No disk usage details below this level,
	// just do a recursive listing
	recursive := depth == 1

	contentCh := clnt.List(ctx, ListOptions{
		TimeRef:           timeRef,
		WithOlderVersions: withVersions,
		Recursive:         recursive,
		ShowDir:           DirFirst,
	})
```
The result generate by this call is then recursed again (by the du code). This leads to all the files being size being counted twice. Forcing `Recursive:         recursive,` to false solves the issue. 

## Expected behavior

```
mc du minio-test/ -r         
24MiB   test-bucket/somefolder
24MiB   test-bucket
24MiB
```

## Actual behavior

```
mc du minio-test/                                
48MiB
```

## Steps to reproduce the behavior

```
docker run -p 9000:9000 -d -e "MINIO_ACCESS_KEY=9PWM3PGAOU5TESTINGKEY" -e "MINIO_SECRET_KEY=p4KQAm5cLKfW2QoJG8SI5JOI3gYSECRETKEY" minio/minio server /data
mc alias set minio-test http://localhost:9000
mc mb minio-test/test-bucket
dd if=/dev/zero of=test.file  bs=24m  count=1\n
mc cp test.file minio-test/test-bucket/somefolder/test.file
mc du minio-test/
mc du minio-test/test-bucket/
mc du minio-test/ -r
```

## mc --version
mc version RELEASE.2021-10-07T04-19-58Z
Master as well

**Comment by harshavardhana** [comment]
Please update to latest `mc du` is fixed
