### ISSUE TITLE
Unable to detect minio failure, exit code always return 0.

### ISSUE THREAD

**Issue by AmbroxMr** [minio/mc#3852]
I am using docker to start a minio service in Python. For minio failure detection, I am using the container's exit code ('StatusCode'). I cannot seem to be able to detect any error as exit code doesn't return any value other than `0`.

## Expected Behavior
When there is any minio-related failure, exit code is expected to return `1`. E.g. credentials are not valid.

## Current Behavior
Currently, the exit code is always `0`, regardless of whether the credentials are valid or not.

## Some code

```py
        result = self.run_container(
            image="minio/mc", volumes=volumes, environment=environment, entrypoint="", command=command
        )
```

```python
            container = client.containers.run(
                image=image,
                volumes=volumes,
                entrypoint=entrypoint,
                command=command,
                environment=environment,
                remove=False,
                detach=True,
                tty=True,
            )

            r = container.wait()
```

```python
            status_code = r.get("StatusCode")
            print(status_code)
            if status_code != 0:    # Bug? It always return 0!
                raise DockerException
```

**Comment by AmbroxMr** [comment]
@vadmeste 
```
        command = [
            "/bin/sh",
            "-c",
            "mc alias set minio ${{MINIO_HOST}} ${{MINIO_ACCESS_KEY}} ${{MINIO_SECRET_KEY}}; mc mb minio/{remote_dir_path}; mc mirror /data minio/{remote_dir_path}".format(
                remote_dir_path=remote_dir_path
            ),
        ]
```

**Comment by vadmeste** [comment]
@AmbroxMr better to use `&&` instead of `;` so your command will exit early with a code error after executing `mc alias set` command

```
mc alias set minio ${{MINIO_HOST}} ${{MINIO_ACCESS_KEY}} ${{MINIO_SECRET_KEY}} && mc mb minio/{remote_dir_path} && mc mirror /data minio/{remote_dir_path}
```

The thing is that if configuring a new alias is failed, mc mb minio/bucket will create a bucket in the local filesystem, that is why it returned successfully.
