### ISSUE TITLE
mc policy issue

### ISSUE THREAD

**Issue by spbho** [minio/mc#3854]
## Expected behavior
Should be able to set policy for an user to generate temporary credentials using LDAP credentials
## Actual behavior
I am able to use LDAP credentials for console login, I want to set policy so that temporary credentials would be generated using LDAP credentials but while setting alias I am facing issue. I have tried these two ways
./mc alias set minio http://Loadbalancerip:9000 LDAPusername LDAPpassword
mc: Unable to initialize new alias from the provided credentials. Get "http://LBIP:9000/probe-bucket-sign-/?location=": dial tcp LBIP:9000: connect: no route to host.
./mc alias set minio http://Loadbalancerip:serviceport LDAPusername LDAPpassword
mc: Unable to initialize new alias from the provided credentials. XML syntax error on line 1:  element <link> closed by </head>.

minioAPIPort: "9000"
minioConsolePort: "9001"

Loadbalancer service is on different port

I have referred these:
https://docs.min.io/minio/baremetal/security/ad-ldap-external-identity-management/AssumeRoleWithLDAPIdentity.html#minio-sts-assumerolewithldapidentity
https://github.com/minio/minio/blob/master/docs/sts/ldap.md#sample-post-request

Need guidance to resolve this issue. 
## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2021-07-27T06-46-19Z
Minio version-RELEASE.2021-10-13T00-23-17Z

**Comment by harshavardhana** [comment]
> ./mc alias set minio http://Loadbalancerip:9000 LDAPusername LDAPpassword

You cannot use `mc` with LDAP - `mc` can be only used with the service accounts generated after you successfully log in with LDAP on the console UI.

https://docs.min.io/minio/baremetal/security/ad-ldap-external-identity-management/external-authentication-with-ad-ldap-identity-provider.html#minio-external-identity-management-ad-ldap 

Read about it here.

**Comment by spbho** [comment]
I am able to set alias for hostname with default username and password given in helm chart but for setting policy getting issue
./mc alias set minio2 http://hostname:port admin admin(host is accessible when browser is set with Ingresscontroller ip and port)
Added `minio2` successfully.
 ./mc admin policy set minio2 readwrite user='uid=,ou=,dc=,dc=' (same lookup bind dn from LDAP)
mc: <ERROR> Unable to set the policy. Failed to parse server response: invalid character 'd' looking for beginning of value.
Is this not the correct approach?
