### ISSUE TITLE
mc: <ERROR> Unable to get bucket object lock configuration from `mys3/aaa/b/c`. Object Lock configuration does not exist for this bucket

### ISSUE THREAD

**Issue by ysjjovo** [minio/mc#3867]
## Expected behavior
Set retention successfully!
## Actual behavior
Failed!
## Steps to reproduce the behavior
This is my script.
```
#!/bin/sh
S3_ENDPOINT=http://xxx:9000
S3_ACCESS_KEY=xxxx
S3_SECURITY_KEY=xxxxx
S3_BUCKET=aaa
S3_FILEPATH=b
BAK_FILE_NAME=c
S3_FILE_EXPIRE_DAYS=1
mc alias set mys3 $S3_ENDPOINT $S3_ACCESS_KEY $S3_SECURITY_KEY
mc mb -l mys3/$S3_BUCKET
mc cp ./s3.sh mys3/$S3_BUCKET/$S3_FILEPATH/$BAK_FILE_NAME
mc retention set governance ${S3_FILE_EXPIRE_DAYS}d mys3/$S3_BUCKET/$S3_FILEPATH/$BAK_FILE_NAME
```
Save as 's3.sh' and run it .Get some output.
```
Added `mys3` successfully.
mc: <ERROR> Unable to make bucket `mys3/aaa`. A header you provided implies functionality that is not implemented
./s3.sh:                                449 B / 449 B  3.29 KiB/s 0s
mc: <ERROR> Unable to get bucket object lock configuration from `mys3/aaa/b/c`. Object Lock configuration does not exist for this bucket.
```

## mc --version
- mc version RELEASE.2021-11-05T10-05-06Z

## System information
WSL2
➜  note cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

**Comment by vadmeste** [comment]
@ysjjovo most likley your MinIO server does not support object locking. It needs to be erasure coded.

**Comment by harshavardhana** [comment]
> Added `mys3` successfully.
> mc: <ERROR> Unable to make bucket `mys3/aaa`. A header you provided implies functionality that is not implemented
> ./s3.sh:                                449 B / 449 B  3.29 KiB/s 0s
> mc: <ERROR> Unable to get bucket object lock configuration from `mys3/aaa/b/c`. Object Lock configuration does not exist for this bucket.

Running `mc` against single drive setup - object locking is not supported.

**Comment by ysjjovo** [comment]
> > Added `mys3` successfully.
> > mc:  Unable to make bucket `mys3/aaa`. A header you provided implies functionality that is not implemented
> > ./s3.sh:                                449 B / 449 B  3.29 KiB/s 0s
> > mc:  Unable to get bucket object lock configuration from `mys3/aaa/b/c`. Object Lock configuration does not exist for this bucket.
> 
> Running `mc` against single drive setup - object locking is not supported.

Thanks very much!Dose multiple  drivers support?

**Comment by harshavardhana** [comment]
> Thanks very much!Dose multiple drivers support?

https://docs.min.io/docs/distributed-minio-quickstart-guide.html
