### ISSUE TITLE
Wrong license declared at https://minio.github.io/mc/

### ISSUE THREAD

**Issue by de-jcup** [minio/mc#3872]
## Expected behavior
https://minio.github.io/mc/ shall mention AGPL and provide a link to the license file
e.g. "mc - Minio Client for S3 Compatible Object Storage released under AGPL"

## Actual behavior
https://minio.github.io/mc/ mentions :
"mc - Minio Client for S3 Compatible Object Storage released under Apache license v2."
Also the link does not work

## Steps to reproduce the behavior
Open https://minio.github.io/mc/
- read (wrong written)
- click link (not working)

**Comment by harshavardhana** [comment]
All fixed here https://minio.github.io/mc/
