### ISSUE TITLE
Cannot set multiple tags using cp or tag

### ISSUE THREAD

**Issue by jsabater** [minio/mc#3880]
I am trying to use the console client to set up multiple tags on an object, either when copying it or using the specific command. I have attempted the following:

```
~# mcli cp --tags "country=USA,period=WWII" /tmp/wallpapers/image.jpg minio1/wallpapers/
file.jpg:  60.70 KiB / 60.70 KiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 4.13 MiB/s 0s
~# mcli tag set minio1/wallpapers/file.jpg "country=USA,period=WWII"
Tags set for https://minio1.mydomain.com:9000/wallpapers/file.jpg.
```

In both cases the end result is one tag with key "country" and value "USA,period=WWII":

```
~# mcli tag list minio1/wallpapers/file.jpg
Name    : https://minio1.mydomain.com:9000/wallpapers/file.jpg ()
country : USA,period=WWII
```

As per the documentation [here](https://docs.min.io/minio/baremetal/reference/minio-cli/minio-mc/mc-cp.html) and [here](https://docs.min.io/minio/baremetal/reference/minio-cli/minio-mc/mc-tag.html), and also as per the built-in command help, it should have created two tags.

Just in case, I also tried passing the `--tags` parameter twice to `mcli cp` but only the second set was saved.

I am using these versions:

```
~# mcli --version
mcli version RELEASE.2021-11-16T20-37-36Z
~# minio --version
minio version RELEASE.2021-11-24T23-19-33Z
```
In the end I used the web UI to set up the two tags, which worked perfectly but doesn't allow me to automate tasks:

```
~# mcli tag list minio1/wallpapers/file.jpg
Name    : https://minio1.mydomain.com:9000/wallpapers/file.jpg ()
country : USA
period  : WWII
```
Thanks in advance.

**Comment by vadmeste** [comment]
@jsabater you actually need to use '&' instead of '.' to send multiple tags for the object.

**Comment by jsabater** [comment]
Thank you very much for the reply. That worked both for `mcli cp --tags` and `mcli tag set`. Where should I post this so that the documentation gets updated?

**Comment by klauspost** [comment]
https://github.com/minio/mc/pull/3881

**Comment by harshavardhana** [comment]
> Thank you very much for the reply. That worked both for `mcli cp --tags` and `mcli tag set`. Where should I post this so that the documentation gets updated?

Documentation is updated as part of `--help` for each of those commands.
