### ISSUE TITLE
Managing ldap groups with spaces fail

### ISSUE THREAD

**Issue by heino** [minio/mc#3888]
## Expected behavior
Adding policies to LDAP groups that include spaces should be valid.

## Actual behavior
mc fails, when group names contain spaces.

## Steps to reproduce the behavior
`mc admin policy set target readwrite group='CN=aaa,OU=bb b,DC=domain,DC=tld'` (NB. Notice the space character!)  returns help text is returned - as if the command was invalid.

`mc admin policy set target readwrite group='CN=aaa,OU=bbb,DC=domain,DC=tld'` (no space) is accepted, but then the group is of cause not correct...

## mc --version
RELEASE.2021-12-10T00-14-28Z (unmodified image at Docker Hub)

**NB. This issue does _not_ relate to the binary, which works fine**

## System information
Ubuntu 21.10 in WSL v2

**Comment by heino** [comment]
I see a few `"$@"` in the bottom of docker-entrypoint.sh, so perhaps this is just an issue with quotes disappearing.

**Comment by harshavardhana** [comment]
> Yes, it is likely a quoting issue as it works fine with the binary. Could you explain how this issue triggered?

I think it is incorrect use @donatello one just needs to use `"` instead of `'`  - As pointed out by @klauspost

**Comment by donatello** [comment]
Yes it depends on which quotes only when the shell can do something to the string inside. Double quotes allow substitution and single quotes do not:

```
$ a='ab c'
$ b="ab c"
$ echo $a
ab c
$ echo $b
ab c
$ echo "$a"
ab c
$ echo '$a'
$a
```

We just need more info here.

**Comment by donatello** [comment]
Specifically this already works (single quotes) on the shell:

```
$ mc admin policy set myminio readwrite group='CN=aaa,OU=bb b,DC=domain,DC=tld'
Policy `readwrite` is set on group `CN=aaa,OU=bb b,DC=domain,DC=tld`
```

**Comment by harshavardhana** [comment]
Perhaps there is an issue with `docker-entrypoint` @donatello - can you run with `docker run --net=host --rm minio/mc admin policy set myminio readwrite group='CN=aaa,OU=bb b,DC=domain,DC=tld'`

**Comment by donatello** [comment]
Yep, that works fine too:

```
$ docker run --net=host --rm --env 'MC_HOST_myminio=http://minio:minio123@localhost:9000' \
    minio/mc admin policy set myminio readwrite group='CN=aaa,OU=bb b,DC=domain,DC=tld'
Policy `readwrite` is set on group `CN=aaa,OU=bb b,DC=domain,DC=tld`
$ docker run --net=host --rm --env 'MC_HOST_myminio=http://minio:minio123@localhost:9000' \
    minio/mc admin policy set myminio readwrite group="CN=aaa,OU=bb b,DC=domain,DC=tld"
Policy `readwrite` is set on group `CN=aaa,OU=bb b,DC=domain,DC=tld`

```
