### ISSUE TITLE
Problem with 'mc mirror ...'

### ISSUE THREAD

**Issue by reiner1959-coder** [minio/mc#3889]
## Expected behavior
-> 'mc mirror --insecure .\DBInstall\ <minio-server>/swlibrary/ImageManagement' should just mirror content between a local Server 2016 directory and MinIO latest version: Version 2021-12-10T23:03:39Z running on a Raspy 4 8GB
## Actual behavior
-> After few moments it stops with an error: uploads=": read tcp 10.221.212.37:59367->82.165.102.46:443: wsarecv: An existing connection was forcibly closed by the remote host.
-> command: 'mc cp -r --insecure .\DBInstall\ <minio-server>/swlibrary/ImageManagement' works good. 
## Steps to reproduce the behavior
-> mc mirror --insecure .\DBInstall\ <minio-server>/swlibrary/ImageManagement
## mc --version
- mc version RELEASE.2021-12-10T00-14-28Z
## System information
Windows Server 2016 latest patches & Raspberry 4 8GB on Ubuntu 20.04

**Comment by vadmeste** [comment]
@reiner1959-coder MinIO server probably crashed in your Raspberry, could you double check ?

**Comment by reiner1959-coder** [comment]
I did a closer investigation. MinIO server was still running. Treafik stopped working but I could not see any error reported form Traefik. After restart Treafik it was back.
