### ISSUE TITLE
mirror --watch process is so slow

### ISSUE THREAD

**Issue by zkryakgul** [minio/mc#3895]
## Expected behavior
I got two standalone minio server (server1,server2). And i migrating my production data from server1 to server2. Server1 still in use in production so i need to keep sync two server until the operation day. Server1 got almost 3.4TB data in it. Two servers conected to each other over 20G LACP network. I started the mirror process a day ago(more than 24 hours have passed) and my expectaion was that the mirroring process would be finished today.

## Actual behavior
When i check the status i see just 150GB data copied to server2.

## Steps to reproduce the behavior
Create two diffrent minio standalone in k8s cluster with the versions above and mirror old to new.

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2021-12-10T00-14-28z

## System information
```
Server1:
     Env: Running in a STS in K8s cluster
     Minio container image: minio/minio:RELEASE.2020-08-07T01-23-07Z
     Minio mode:  Standalone
     Disk setup: Connected trough HBA to 3Par Storage equiped with NLSAS disk(RAID6 Volume) 
Server2:
     Env: Running in a STS in same K8s cluster with Server1
     Minio container image: minio/minio:RELEASE.2021-12-10T23-03-39Z
     Minio mode:  Standalone
     Disk setup: Local SAS disks RAID6
```

**Comment by harshavardhana** [comment]
What is the total object count? And what is your backend disk here local drives?

**Comment by zkryakgul** [comment]
> What is the total object count? And what is your backend disk here local drives?

I updated my question for disks. When i run `mc stat my-minio-alias/my-bucket` its not giving me any info about object count. How can i get it?

**Comment by harshavardhana** [comment]
> > What is the total object count? And what is your backend disk here local drives?
> 
> I updated my question for disks. When i run `mc stat my-minio-alias/my-bucket` its not giving me any info about object count. How can i get it?

Your 3PAR backend is the culprit here and it's terribly slow. 

You can verify this by simply uploading some random content to your server2.

We expect that you use local disks with MinIO not some fancy SAN vendors.

They are known to be terrible at concurrent performance.

**Comment by zkryakgul** [comment]
Hmm, ok i get it. Then there is no other option except wait for the mirror process finished in this situation i think, right? Or is there anything else you can suggest me?

Im running mc in my server2.
