### ISSUE TITLE
mc mirror copies a subdir on every run

### ISSUE THREAD

**Issue by reiner1959-coder** [minio/mc#3900]
## Expected behavior
mc mirror should just ignore files if they are in the bucket.
## Actual behavior
It copies to following directory every time: 
'c:\Spectrum\Rel12\Release_12.3.0\Spectrum'
I just played around and when I rename it like: 'c:\Spectrum\Rel12\Release_12.3.0\spectrum' or 'c:\Spectrum\Rel12\Release_12.3.0\Spectrum-PGM' it works as expected. 
In the folder: 'c:\Spectrum\Rel12\Release_12.3.0' there are 20 more subdirs they are all good. Non of them will be copied if they are in the bucket. 
## Steps to reproduce the behavior
Create a similar dir structure and call: 
'mc mirror --md5 --overwrite --remove C:\Spectrum\Rel12\Release_12.3.0 s3/test/Spectrum/Rel12/Release_12.3.0'
## mc --version
mc version RELEASE.2021-12-20T23-43-34Z
## System information
W11 as client.

**Comment by harshavardhana** [comment]
Directories are always copied @reiner1959-coder there is no directory object on destination.
