### ISSUE TITLE
--continue flag for resumable downloads does not seem to have an effect

### ISSUE THREAD

**Issue by drewm1980** [minio/mc#3902]
## Expected behavior
Running mc cp --continue ...  with the other flags unchanged should continue a failed download from a previous invocation.

## Actual behavior
The file download starts from scratch, whether or not the --continue flag was passed in the previous failed transfer.

The documentation for this flag is just "create or resume copy session", which is not enough to know what guarantees I should actually be expecting.

## Steps to reproduce the behavior
1. Start a "mc cp" file download on a large file, with or without the --continue flag
2. Observe that some data has been downloaded successfully.
3. Kill the transfer via Ctrl-C
4. Restart the same command with the --continue flag
5. Observe that the amount of data transferred started over from zero, and the total file size also started from zero.

## mc --version

mc version RELEASE.2021-10-07T04-19-58Z

## System information
I was downloading from a minio instance on a kubernetes-managed corporate cluster.

**Comment by klauspost** [comment]
It continues copying a number of files. Individual files are downloaded from scratch.
