### ISSUE TITLE
mc find --exec stopping when it encounters a space in the path.

### ISSUE THREAD

**Issue by ScionOfDesign** [minio/mc#3906]
## Expected behavior
`mc find minio/releases --exec "mc tag list {}"` should list the tags of ALL objects found, even those with spaces in the path.

## Actual behavior
The command stops as soon as it encounters a space in the name.

## Steps to reproduce the behavior
Upload some files like the following:
```
minio/releases/App1/App1.apk --tags version=1.0
minio/releases/App1/App1_Linux.zip --tags version=1.0
minio/releases/App1/App1_OSX.zip --tags version=1.0
minio/releases/App1/App1_Windows.zip --tags version=1.0
minio/releases/App2/App 2.apk --tags version=1.0
minio/releases/App2/App2_Linux.zip --tags version=1.0
minio/releases/App2/App2_Windows_32bit.zip --tags version=1.0
```
`mc find minio/releases/` displays all the files correctly.
`mc tag list "minio/releases/App2/App 2.apk"` should list the correct tag.
`mc find minio/releases/ --exec "mc tag list {}"` however, only displays the following output:

```
Name    : https://minio1.studiowhy.net/releases/App1/App1.apk ()
version : 1.0
Name    : https://minio1.studiowhy.net/releases/App1/App1_Linux.zip ()
version : 1.0
Name    : https://minio1.studiowhy.net/releases/App1/App1_OSX.zip ()
version : 1.0
Name    : https://minio1.studiowhy.net/releases/App1/App1_Windows.zip ()
version : 1.0
Name    : https://minio1.studiowhy.net/releases/App1/App1_Windows_32bit.zip ()
version : 1.0
```

## mc --version
- RELEASE.2021-12-29T06-52-55Z

## System information
Windows 10

**Comment by klauspost** [comment]
Could you try `--exec 'mc tag list {""}'` to have file names quoted?

**Comment by ScionOfDesign** [comment]
Thanks for responding. It throws an error:
> mc: <ERROR> Unable to fetch tags for {"}: `GetObjectTagging` is not supported for `filesystem`.

**Comment by klauspost** [comment]
@ScionOfDesign I think you are missing a quote. Either way, added #3907 which should make it more robust.

**Comment by ScionOfDesign** [comment]
Thanks for the fix, but this was the exact command I ran: `mc find minio/releases --exec 'mc tag list {""}'`
I do not know why the output only had one quotation mark.

**Comment by klauspost** [comment]
With the fix:
```
$ ./mc find play/test123/ --exec="./mc tag list {}"
Name    : https://play.min.io/test123/Docker Fundamentals for Absolute beginners.png ()
version : 2.0
Name    : https://play.min.io/test123/javascript.jpg ()
version : 1.0
```

Before, no output...
