### ISSUE TITLE
mc mirror times out after about 40 minutes

### ISSUE THREAD

**Issue by multinerd** [minio/mc#3912]
## Expected behavior
run a mirror command and expect it to finish

## Actual behavior
after about 40-45 minutes, nginx returns a gateway error and exits

```
PS C:\> ./mc.exe mirror --overwrite minio/timeclock minionew/timeclock
 0 B / ? [                                                                                                           =]
mc.exe: <ERROR> Unable to list comparison retrying.. <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.19.2</center>
</body>
</html>
 0 B / ? [                                                                                                     =] 40m2s
PS C:\>
```

## Steps to reproduce the behavior

`mc.exe mirror --overwrite minio/timeclock minionew/timeclock`

I've ran this command 3 times and it timed out consistently, though im not sure its enough to 'reproduce the behavior'
`minio` is an old single node docker instance (RELEASE.2021-12-29T06-49-06Z)
`minionew` is a distributed node docker instance (RELEASE.2021-12-29T06-49-06Z)
`timeclock` folder is used for a timeclock application that persist employee images using this structure `{employeeId}/Punches/{punchId}/[employee|manager].png` and contains over 10000 items

## mc --version
- mc version RELEASE.2021-12-29T06-52-55Z

## System information
Both instances are hosted in docker for windows v4.3.2 on windows 10 21h1

The command is being executed on the same machine, using `localhost:port` as the alias url for both instances so i dont think its a networking issue.

**Comment by klauspost** [comment]
Your nginx load balancer has a timeout. Configure nginx without timeouts.

**Comment by multinerd** [comment]
Im using this config from minio

https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/nginx.conf

do i remove `keepalive_timeout  65;` or `proxy_connect_timeout 300;`
