### ISSUE TITLE
cp -r is copying more than what is expected

### ISSUE THREAD

**Issue by AlexisEspinosaGayosso** [minio/mc#3918]
## Background
I have the following files and directories in my local posix filesystem:
```
local> ls -l
total 0
drwxr-xr-x 2 root root 64 Jan 11 00:18 alcohol
-rw------- 1 root root  0 Jan 11 00:17 alexis.txt
-rw------- 1 root root  0 Jan 11 00:18 anthony.jpg
```

And then I execute:
```
local> mc cp -r a storage/mybucket
```

## Expected behavior
I would expect an error message as there is no `a` file or folder to copy.

## Actual behavior
But no error message pops up. And, indeed a recursive copy of everything starting with `a` is performed. So, if I check the content of the bucket after executing the command:
```
local> mc ls storage/mybucket
[2022-01-11 00:34:20 UTC]     0B alexis.txt
[2022-01-11 00:34:19 UTC]     0B anthony.jpg
[2022-01-11 00:34:23 UTC]     0B alcohol/
```
## Steps to reproduce the behavior
Have some files and folders with names starting with the same character, then perform the command.

## mc --version
mc version RELEASE.2022-01-07T06-01-38Z

## System information
This happens in my two linux boxes. Not related to my systems.

**Comment by harshavardhana** [comment]
> ```
> local> mc cp -r a storage/mybucket
> ```

We do prefix-based listing to be compatible with S3 behavior like this, so we allow prefix-based copying. So all files match `a` gets copied.

```
~ mc ls R
[2022-01-10 18:46:34 PST]  19KiB README.md
```

So what you are seeing is actually a feature of `mc` @AlexisEspinosaGayosso

**Comment by AlexisEspinosaGayosso** [comment]
Then, the command without recursive is giving error:
```
local> mc cp a storage/mybucket
mc: <ERROR> Unable to validate source `a`.
```
So, for plain copy you do not apply prefix-based listing?

**Comment by harshavardhana** [comment]
> So, for plain copy you do not apply prefix-based listing?

Of course not because `-r` is for prefix listing not just `a`

**Comment by AlexisEspinosaGayosso** [comment]
Thank you very very much @harshavardhana .
Now I see that --recursive (-r) will treat the "origin" argument of the copy command as the prefix of a prefix-listing.

In my opinion, prefixes should not be considered as prefixes unless there is really a "complete" prefix with the last character of the prefix being "/".

While trying to replicate the same behaviour but with amazon/aws-cli (which I guess is also S3 compatible) this other tool seems to behave as I expect. In the case of aws-cli, an error message is indeed provided:

```
local> aws s3 cp a s3://mybucket/ --recursive
The user-provided path a does not exist.
```

And the intended recursive copy only works when trying to copy a real local posix directory (alcohol in this case):
```
local> aws s3 cp alcohol s3://mybucket/ --recursive
upload: alcohol/tequila.txt to s3://mybucket/tequila.txt
```
But fails otherwise, even when trying to copy recursively an existing file, as a file is indeed not a prefix. As you said, --recursive implies a prefix listing
```
local> aws s3 cp alexis.txt s3://mybucket/ --recursive
warning: Skipping file /myDir/alexis.txt/. File does not exist.
```

So, as said above, I do believe that `cp -r` should only copy local directories. And only copy them when the given prefix matches with the names of a directory and not every match of files and directories. And never as I reported with a match of the first character. That decision is not in my hands, but I hope developers may consider it. Also taking into account that the amazon tool behaves as I (and my colleagues) expect.

By the way, have you documented the current behaviour of minio/mc with the `cp -r` command? As current behaviour is really not as expected, I hope you have it documented to the public eye. Although I would prefer a decision to change that not intuitive behaviour.

By the way, yes, aws-cli does behave as mc when listing contents (prefix listing):
```
local> aws ls s3://mybucket/a
                           PRE alcohol/
2022-01-11 04:39:22          0 alexis.txt
2022-01-11 04:39:22          0 anthony.jpg
```
(But not for recursive copies as said).
Thanks

**Comment by harshavardhana** [comment]
> Thank you very very much @harshavardhana .
> Now I see that --recursive (-r) will treat the "origin" argument of the copy command as the prefix of a prefix-listing.
> 
> In my opinion, prefixes should not be considered as prefixes unless there is really a "complete" prefix with the last character of the prefix being "/".
> 
> While trying to replicate the same behaviour but with amazon/aws-cli (which I guess is also S3 compatible) this other tool seems to behave as I expect. In the case of aws-cli, an error message is indeed provided:
> 
> ```
> local> aws s3 cp a s3://mybucket/ --recursive
> The user-provided path a does not exist.
> ```
> 
> And the intended recursive copy only works when trying to copy a real local posix directory (alcohol in this case):
> ```
> local> aws s3 cp alcohol s3://mybucket/ --recursive
> upload: alcohol/tequila.txt to s3://mybucket/tequila.txt
> ```
> But fails otherwise, even when trying to copy recursively an existing file, as a file is indeed not a prefix. As you said, --recursive implies a prefix listing
> ```
> local> aws s3 cp alexis.txt s3://mybucket/ --recursive
> warning: Skipping file /myDir/alexis.txt/. File does not exist.
> ```
> 
> So, as said above, I do believe that `cp -r` should only copy local directories. And only copy them when the given prefix matches with the names of a directory and not every match of files and directories. And never as I reported with a match of the first character. That decision is not in my hands, but I hope developers may consider it. Also taking into account that the amazon tool behaves as I (and my colleagues) expect.
> 
> By the way, have you documented the current behaviour of minio/mc with the `cp -r` command? As current behaviour is really not as expected, I hope you have it documented to the public eye. Although I would prefer a decision to change that not intuitive behaviour.
> 
> By the way, yes, aws-cli does behave as mc when listing contents (prefix listing):
> ```
> local> aws ls s3://mybucket/a
>                            PRE alcohol/
> 2022-01-11 04:39:22          0 alexis.txt
> 2022-01-11 04:39:22          0 anthony.jpg
> ```
> (But not for recursive copies as said).
> Thanks

Sorry that ship has sailed.
