### ISSUE TITLE
How to understand when the mirror command is completed?

### ISSUE THREAD

**Issue by mehdishakki** [minio/mc#3922]
## Expected behavior
mc mirror [FLAGS] SOURCE TARGET . how to understand when the mirror command is completed?

And we do not want to use the copy command.
Because the bucket is in change and we want to stay in sync. But when it was complete, there was no push change. Give success output.
## Actual behavior
When this command is opened in the console, it never ends.
Is there a way to complete the command after output and have output?

## mc --version
- mc version RELEASE.2021-11-05T10-05-06Z

**Comment by harshavardhana** [comment]
> When this command is opened in the console, it never ends.

`mc mirror` needs to list first and compare - it is perhaps listing your namespace? and you server is slow here?

**Comment by mehdishakki** [comment]
> > When this command is opened in the console, it never ends.
> 
> `mc mirror` needs to list first and compare - it is perhaps listing your namespace? and you server is slow here?

No.
I want it to end when the command mirror is finished, like command cp.
Or set the flag, which was from an idle time, to end.

**Comment by harshavardhana** [comment]
> > > When this command is opened in the console, it never ends.
> > 
> > 
> > `mc mirror` needs to list first and compare - it is perhaps listing your namespace? and you server is slow here?
> 
> No. I want it to end when the command mirror is finished, like command cp. Or set the flag, which was from an idle time, to end.

That is how it behaves by default, did you add any extra flags to `mc mirror` command ?

**Comment by mehdishakki** [comment]
> 

No.
I want to know when the mirror work is finished.
That is, in addition to the synchronizes state, it is a state whose end is specified.

**Comment by harshavardhana** [comment]
> > 
> 
> No. I want to know when the mirror work is finished. That is, in addition to the synchronizes state, it is a state whose end is specified.

If you run `mc mirror alias1/ alias2/` it compares, mirrors the missing entries and exits.

Not sure what else are you looking for.

**Comment by mehdishakki** [comment]
> > > 
> > 
> > 
> > No. I want to know when the mirror work is finished. That is, in addition to the synchronizes state, it is a state whose end is specified.
> 
> If you run `mc mirror alias1/ alias2/` it compares, mirrors the missing entries and exits.
> 
> Not sure what else are you looking for.

Suppose I want to run a command mirror in a nodejs program.
Now I want to have exec output when the mirror is done and I can make a decision.
But because the mirror works in synchronization, the command never ends.

**Comment by harshavardhana** [comment]
> > > > 
> > > 
> > > 
> > > No. I want to know when the mirror work is finished. That is, in addition to the synchronizes state, it is a state whose end is specified.
> > 
> > 
> > If you run `mc mirror alias1/ alias2/` it compares, mirrors the missing entries and exits.
> > Not sure what else are you looking for.
> 
> Suppose I want to run a command mirror in a nodejs program. Now I want to have exec output when the mirror is done and I can make a decision. But because the mirror works in synchronization, the command never ends.

Command always ends, it simply waits on both ends to compare and give output.

So I am not sure why would it not complete. Only if you are using flags like --watch `mc mirror` will never exit.

I don't see any issue here, and it's working as expected.
