### ISSUE TITLE
mc admin bucket remote bandwidth myminio/bk1     nothing

### ISSUE THREAD

**Issue by xnat9** [minio/mc#3923]
## Expected behavior

show bucket bandwidth info

## Actual behavior
nothing
![image](https://user-images.githubusercontent.com/10725411/149715736-1008e5ce-5a8a-43e5-b7c4-9ef050091d38.png)

## Steps to reproduce the behavior
mc admin bucket remote bandwidth myminio/bk1

## mc --version

mc version RELEASE.2022-01-05T23-52-51Z

## System information
minio version RELEASE.2022-01-04T07-41-07Z

**Comment by harshavardhana** [comment]
It will not show anything if there is no data to show @xnat9 you need to configure `bandwidth` first for a replication target and then this replication target should be configured to use to remote target.

Without that there is no bandwidth usage available.
