### ISSUE TITLE
mc mirror is not synchronizing when downloading from s3 repo into local posix disc

### ISSUE THREAD

**Issue by AlexisEspinosaGayosso** [minio/mc#3924]
## Expected behaviour
To syncronize only those files that are missing in the local directory (compared to the object storage bucket). In the extreme case when all the files are already present in the local directory, one expects that mc mirror does nothing and just send a message saying directories are already in sync.

(By the way, when using mirror in the opposite direction, the expected behaviour indeed happens. When files are already in the object storage, then mirror does not overwrites and simply tries to upload just the missing files.)

## Actual behavior
When syncronizing into a local posix directory, mc mirror downloads and overwrites all files even if they already exist in the local directory.

## Steps to reproduce the behavior
```
mc mirror my-storage/my-bucket ./my-local-dir
```
and repeat the same command to see that the overwrite is happening every execution

## mc --version
mc version RELEASE.2022-01-07T06-01-38Z

## System information
any linux

**Comment by vadmeste** [comment]
@AlexisEspinosaGayosso thanks for reporting this. Yes I was able to reproduce. A current workaround would be using a full path of './'. I will send a fix shortly.

**Comment by harshavardhana** [comment]
> ```
> mc mirror my-storage/my-bucket ./my-local-dir
> ```

You need to provide absolute paths @AlexisEspinosaGayosso
