### ISSUE TITLE
"mc ls --incomplete" does not show any result

### ISSUE THREAD

**Issue by Feiniu6ABC** [minio/mc#3926]
## Expected behavior
"mc ls --incomplete" shows the incomplete uploads
## Actual behavior
"mc ls --incomplete" does not show any thing
## Steps to reproduce the behavior
1. create alias using command 
` mc alias set minio http://192.168.50.12:9000 minioadmin minioadmin
`
2. use dd command to create a test file
`dd if=/dev/zero of=test bs=1M count=5000
`
3. make a bucket and copy the test file to designated bucket
`
mc mb minio/bucket1
`
`
mc cp test minio/bucket1
`
4. stop file upload by ctrl+c
5. use "mc ls --incomplete minio/bucket1" to llist the files
`mc ls --incomplete minio/bucket1
`

## mc --version
- (paste output of `mc --version`)
mc.2022-01-20T03-07-02Z
## System information
Ubuntu 20.04.3 LTS

**Comment by harshavardhana** [comment]
It will only show result if you provide the exact object name, otherwise it doesn't list anything it's by design.

ListMultipartUpload implementation is simplified on MinIO.

**Comment by Feiniu6ABC** [comment]
Thanks for your reply!
