### ISSUE TITLE
"mc mb" never gives an error. Or, how can I check for the existence or correct creation of a real bucket on a S3 storage?

### ISSUE THREAD

**Issue by AlexisEspinosaGayosso** [minio/mc#3952]
## Problem
When trying to create a bucket in my ceph-S3 storage, I had a typo on my command. So, instead of typing the correct alias (`espinosa-feb`) I typed `espinosa-febr`. Problem is that when typing the INCORRECT alias, the command still succeeds and works fine, because the commands goes for plan B and behaves as `mkdir -p` in my local filesystem.

## Expected behavior
I would expect the command to fail when I incorrectly type the alias.
I understand that by design `mc mb` behaves like `mkdir -p`, but ideally we should be able to catch errors. So, in my opinion, there should be, at least, an option (like, for example, `--no-mkdir`) which forces the command to only work as a object storage client and not as a mkdir on the local filesystem. Then, if the creation of the intended bucket fails, we indeed receive an error.

So, my intended behaviour would be (assuming that `espinosa-febr` is NOT the alias of any object storage):
```
$ mc mb --no-mkdir espinosa-febr/bucket1
mc: <ERROR> Unable to make bucket, please use `mc mb --no-mkdir <correct-alias>/<your-bucket-name>`. Or remove the `--no-mkdir` if your intention is to create a directory in your local filesystem.
success=1
```

And, if we still use `mc mb` to create a local directory, then the message should be different to that of a bucket creation. So, my expected behaviour would be:
```
$ ls ; success=$?; echo "success=$success"
success=0

$ mc mb espinosa-febr/bucket01; success=$?; echo "success=$success"
Warning: Local filesystem directory created successfully `espinosa-febr/bucket01`.
success=0

ls ; success=$?; echo "success=$success"
espinosa-febr
success=0
```
To be honest, in my opinion, the mutation to behave as `mkdir -p` should be removed from the command completely and then report an error when buckets can be created as buckets.

## Actual behavior

When using an incorrect alias, user does not notice if the intended action happened. If the intended action was to create a bucket on an object storage, then user does not receive an error, but a successful message and exitcode. And, if the intended action was to indeed create a local subdirectory, then the user is receiving a successful message of a bucket created. Then user will not catch possible errors with respect to the intended action.

```
$ mc ls; success=$?; echo "success=$success"
success=0
$ mc mb espinosa-febr/bucket01; success=$?; echo "success=$success"
Bucket created successfully `espinosa-feb/bucket01`.
success=0
$ mc ls; success=$?; echo "success=$success"
[2022-02-03 13:26:33 AWST] 4.0KiB espinosa-febr/
success=0

$ mc ls espinosa-feb/; success=$?; echo "success=$success"
success=0
$ mc mb espinosa-feb/bucket01; success=$?; echo "success=$success"
Bucket created successfully `espinosa-feb/bucket01`.
success=0
$ mc ls espinosa-feb/; success=$?; echo "success=$success"
[2022-02-03 13:35:08 AWST]     0B bucket01/
success=0
```

## Additional question
Lets say I have the typo in my script, but I still want to check if I successfully created a real bucket in the ceph-S3 storage. And let's say that I want to check this today, with the current version of mc. How can i do it? How can I verify if the created bucket is indeed a bucket and not a "faulty" directory created in my local file system?

## Steps to reproduce the behavior
Same as in explanation above
## mc --version
mc version RELEASE.2022-01-29T01-03-27Z

## System information
linux

**Comment by harshavardhana** [comment]
Unfortunately this cannot be changed. This is expected and it is working as advertised.

**Comment by AlexisEspinosaGayosso** [comment]
Many thanks @harshavardhana,
I understand this is your design. But, can you modify creation messages? Or add the `--no-mkdir` option to the command?
Also, is there any way to check that a bucket is indeed a bucket? With any of the current other commands?
Thanks a lot for your tool.

**Comment by harshavardhana** [comment]
> I understand this is your design. But, can you modify creation messages? Or add the `--no-mkdir` option to the command?
> Also, is there any way to check that a bucket is indeed a bucket? With any of the current other commands?

It is not going to change - there are many who rely on it with the way its implemented. Adding an option perhaps might be possible but right now we do not have the necessary bandwidth. 

Feel free to send a PR we will review it.
