### ISSUE TITLE
mc ls doesn't work well with ListObjects (no V2)

### ISSUE THREAD

**Issue by deantvv** [minio/mc#3962]
## Expected behavior
mc ls with server only support ListObjects also works

## Actual behavior
Not working

## Detail
This issue is almost the same as #3073 but on different server implementation.
#3101 solved #3073 by checking host url with google and use `ListObjects` for google only.
In reality, there exists other implementation that only support `ListObjects` (but not V2 variant) which still suffer from this issue.

## Possible solution
Maybe we could add a key to config like `UseLegacyListObject` to instruct `mc` to use `ListObjects` in ls?

**Comment by klauspost** [comment]
@deantvv That is not something we are planning to support. You are welcome to send a pull request and we can discuss the feature there if it is implemented non-intrusively.
