### ISSUE TITLE
listing service accounts for ldap users show blank results

### ISSUE THREAD

**Issue by titansmc** [minio/mc#3974]
## Expected behavior
would list existing accounts
## Actual behavior
empty result

```
mc admin user svcacct ls minio-test/

NAME:
  mc admin user svcacct ls - List services accounts

USAGE:
  mc admin user svcacct ls ALIAS TARGET-ACCOUNT

TARGET-ACCOUNT:
  Could be a MinIO user, STS or LDAP account.
```

this command's usage shows that given an alias and a target account, it will list the svcacct for an LDAP account.

## Steps to reproduce the behavior
 mc admin user svcacct ls ALIAS TARGET-ACCOUNT
## mc --version
- mc version RELEASE.2022-01-25T21-02-01Z

## System information
Ubuntu 20.04

**Comment by harshavardhana** [comment]
You need to provide 

```
mc admin user svcacct ls minio-test/ <target_account>
```

**Comment by titansmc** [comment]
right, as you can see here, the output is blank: 
![image](https://user-images.githubusercontent.com/8192096/153360210-f168d581-a273-4a97-a232-5860a72719c9.png)

`moscardo` is the user I type for login via console.

**Comment by harshavardhana** [comment]
If you are using LDAP user then you need to make sure that user is an LDAP user-DN not just a simple name. @titansmc

**Comment by titansmc** [comment]
it works, right. What I didn't manage is to get the same functionality with Keycloak, so the root account would be able to list the `svcacct` of every keycloak user.

**Comment by harshavardhana** [comment]
> it works, right. What I didn't manage is to get the same functionality with Keycloak, so the root account would be able to list the `svcacct` of every keycloak user.

Keycloak it won't work @titansmc - you cannot use a simple name for keyclaok you need to use the specific format that we generate internally which is not exposed.

```
        // Since issFromToken can have `/` characters (it is typically the
        // provider URL), we hash and encode it to base64 here. This is needed
        // because there will be a policy mapping stored on drives whose
        // filename is this parentUser: therefore, it needs to have only valid
        // filename characters and needs to have bounded length.
        {
                h := sha256.New()
                h.Write([]byte("openid:" + subFromToken + ":" + issFromToken))
                bs := h.Sum(nil)
                cred.ParentUser = base64.RawURLEncoding.EncodeToString(bs)
        }
```

Currently, only Console UI allows this - you need for wait for new changes that we will bring to make it available in `mc` in future.
