### ISSUE TITLE
mc on window memory can't reuse

### ISSUE THREAD

**Issue by qw4285632q** [minio/mc#3997]
## Expected behavior
memory can limit  below 1G
## Actual behavior
![image](https://user-images.githubusercontent.com/27714601/155284380-b42079b8-eaed-41be-82ae-dafad83bd396.png)
## mc --version
RELEASE.2022-02-13T23-26-13Z

## System information
winserver 2008r2

**Comment by harshavardhana** [comment]
related to #3990
