### ISSUE TITLE
mc anonymous does not work with --insecure flag

### ISSUE THREAD

**Issue by nagyv** [minio/mc#4008]
## Expected behavior

`mc anonymous get --insecure play/testnotebooks/test1.ipynb` returns the same as `mc anonymous get play/testnotebooks/test1.ipynb`

## Actual behavior

It returns `mc anonymous --help`

## Steps to reproduce the behavior

1. (optional) Find a file using `mc ls -r play`. I picked `testnotebooks/test1.ipynb`
2. Check its permissions with `mc anonymous get play/testnotebooks/test1.ipynb`. The check works.
3. Check its permissions with `mc anonymous get --insecure play/testnotebooks/test1.ipynb`
4. The check fails

## mc --version

Checked both:

- `mc version RELEASE.2022-02-16T05-54-01Z`
- `mc version RELEASE.2022-02-26T03-58-31Z`

## System information

MacOS. `mc` installed using `brew install minio/stable/mc`

**Comment by vadmeste** [comment]
@nagyv the command should be `mc anonymous --insecure get play/testnotebooks/test1.ipynb` as the help message indicates.

@harshavardhana it looks like rewriting anonymous to use  cli command styles instead of manually parsing the command should fix it.

**Comment by nagyv** [comment]
@vadmeste Tested and it works. Feel free to close it as it seems to be invalid.
