### ISSUE TITLE
mc support perf put 0 obj

### ISSUE THREAD

**Issue by AdheipSingh** [minio/mc#4013]
## Expected behavior
- I am trying to benchmark minio using k8s exposed LB vs sidekick LB
## Actual behavior
- When trying to run various tests, using ```mc support perf ```
- I often come across a benchmark 
```
root@mc-5df4fd877f-gqgd8:/# ./mc support perf object tenant-1 --duration 20s --size 128MiB -v

        THROUGHPUT      IOPS         
PUT     461 MiB/s       3 objs/s
GET     1.2 GiB/s       9 objs/s

Speedtest: MinIO 2022-02-24T22:12:01Z, 4 servers, 4 drives, 128 MiB objects, 6 threads

PUT:
   * http://minio-tenant-lb-pool-0-0.minio-tenant-lb-hl.tenant-1.svc.cluster.local:9000: 115 MiB/s 0 objs/s
   * http://minio-tenant-lb-pool-0-1.minio-tenant-lb-hl.tenant-1.svc.cluster.local:9000: 115 MiB/s 0 objs/s
   * http://minio-tenant-lb-pool-0-2.minio-tenant-lb-hl.tenant-1.svc.cluster.local:9000: 115 MiB/s 0 objs/s
   * http://minio-tenant-lb-pool-0-3.minio-tenant-lb-hl.tenant-1.svc.cluster.local:9000: 115 MiB/s 0 objs/s
GET:
   * http://minio-tenant-lb-pool-0-0.minio-tenant-lb-hl.tenant-1.svc.cluster.local:9000: 314 MiB/s 2 objs/s
   * http://minio-tenant-lb-pool-0-1.minio-tenant-lb-hl.tenant-1.svc.cluster.local:9000: 307 MiB/s 2 objs/s
   * http://minio-tenant-lb-pool-0-2.minio-tenant-lb-hl.tenant-1.svc.cluster.local:9000: 250 MiB/s 1 objs/s
   * http://minio-tenant-lb-pool-0-3.minio-tenant-lb-hl.tenant-1.svc.cluster.local:9000: 320 MiB/s 2 objs/s
   ```
  - why do i get 0 obj/s ?
  - is this behaviour expected ? 
  - Also i get this only when run with 128 MiB object size.
 
## mc --version
- (paste output of `mc --version`)
- latest mc

**Comment by harshavardhana** [comment]
> * why do i get 0 obj/s ?

0 is because its not divisible by 4 nodes since it was perhaps only 3 objects it could write. 


> * is this behaviour expected ?

not expected the output should be fixed.



> * Also i get this only when run with 128 MiB object size.

yes because your disks have peaked and there are no other IOPS left in the system.

**Comment by AdheipSingh** [comment]
@harshavardhana thanks for the reply

I'll revisit my scripts and wait for a pause per command, seems like running scripts continuously is choking the cluster.
