### ISSUE TITLE
Does not handle AWS 301 redirect when using the s3.amazonaws.com endpoint

### ISSUE THREAD

**Issue by wrouesnel** [minio/mc#4018]
## Expected behavior

```
mc --debug ls s3/some-bucket-in-ap-southeast-2
``` 
should produce a list of objects in the bucket

## Actual behavior

```
$ mc --debug ls s3/some-bucket-in-ap-southeast-2
mc: <ERROR> Unable to list folder. Head "https://some-bucket-in-ap-southeast-2.s3.dualstack.us-east-1.amazonaws.com/": 301 response missing Location header
```

## Steps to reproduce the behavior

1. Create an S3 bucket in a non us-east-1 AWS region
2. Try to access the bucket with a host configured as `MC_HOST_s3=<access key>:<secret key>@s3.amazonaws.com`

## mc --version
- `mc version RELEASE.2021-09-23T05-44-03Z`

## System information
* Ubuntu 21.10

## Note

The problem seems to be that mc doesn't recognize the use of `X-Amz-Bucket-Region` header which replaces the Location header for this type of response from AWS.

**Comment by vadmeste** [comment]
> mc version RELEASE.2021-09-23T05-44-03Z

Can you upgrade an test again ?

**Comment by wrouesnel** [comment]
Fixed in the latest version - `mc version RELEASE.2022-03-13T22-34-00Z`
