### ISSUE TITLE
Confusing help docs for defaults in `replicate add`'s `--replicate` option 

### ISSUE THREAD

**Issue by schemacs** [minio/mc#4020]
`mc replicate add` will not enable `existing-objects` feature(as the help docs say with regard to `default: ...`), but `mc replicate add --replicate existing-objects` will.

## Expected behavior
` --replicate value             comma separated list to enable replication of soft deletes, permanent deletes, existing objects and metadata sync (valid options are: "delete-marker,delete,existing-objects,metadata-sync"`

## Actual behavior
` --replicate value             comma separated list to enable replication of soft deletes, permanent deletes, existing objects and metadata sync (default: "delete-marker,delete,existing-objects,metadata-sync"`

`ExistingObjectReplication`'s Status is `Disabled`.
```
 mc replicate export AlphaReplication/src-bucket
{
 "Rules": [
  {
   "ID": "c8opc98b5u56ic6mij10",
   "Status": "Enabled",
   "Priority": 0,
   "DeleteMarkerReplication": {
    "Status": "Disabled"
   },
   "DeleteReplication": {
    "Status": "Disabled"
   },
   "Destination": {
    "Bucket": "arn:minio:replication::7b92ad2c-9d6f-4d84-a005-8049a960b009:dst-bucket"
   },
   "Filter": {
    "And": {},
    "Tag": {}
   },
   "SourceSelectionCriteria": {
    "ReplicaModifications": {
     "Status": "Enabled"
    }
   },
   "ExistingObjectReplication": {
    "Status": "Disabled"
   }
  }
 ],
 "Role": ""
}
```

## Steps to reproduce the behavior

`mc replicate add --help`
## mc --version
mc version RELEASE.2022-03-03T21-12-24Z

## System information
```
$ sw_vers
ProductName: Mac OS X
ProductVersion: 10.15.7
BuildVersion: 19H1615
```

**Comment by harshavardhana** [comment]
well this is mainly because of one issue in the code it expects that you provide `--replicate`  as the flag and the code is expecting that it is set. 

so as a workaround specifiy `--replicate existing-objects,delete,delete-marker,metadata-sync`
