### ISSUE TITLE
is ACCESSKEY filesystem case sensitivity dependent?

### ISSUE THREAD

**Issue by schemacs** [minio/mc#4022]
I am not sure if this is a bug or should be documented somewhere. Just close it if is not.

## Expected behavior
Report it to the user if the access_key(may be in different case, maybe xxX) already exists.

## Actual behavior
Always return `Added user `xxX` successfully.` 

## Steps to reproduce the behavior
```bash
$ nohup minio server /tmp/minio/data{1...4} &
$ mc config host add myminio http://127.0.0.1:9000 minioadmin minioadmin
$ mc admin user add myminio admiN LongRandomSecretKey
Added user `admiN` successfully.
$ mc admin user list myminio
enabled    admiN
$ ls /tmp/minio/data1/.minio.sys/config/iam/users
admiN
$ mc admin user add myminio admin LongRandomSecretKey
Added user `admin` successfully.
$ mc admin user remove myminio admin
mc: <ERROR> Unable to remove admin. The specified user does not exist. (Specified user does not exist).
$ ls /tmp/minio/data1/.minio.sys/config/iam/users
admiN
```

## mc --version
mc version RELEASE.2022-03-03T21-12-24Z

## System information
```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1715
$ diskutil info /|grep -i 'File System Personality' -A 2
   File System Personality:   APFS
   Type (Bundle):             apfs
   Name (User Visible):       APFS
```

**Comment by harshavardhana** [comment]
Everything is case-sensitive towards what can be stored on the backend drives in MinIO.

**Comment by schemacs** [comment]
But access_key or username depending on backend filesystem case sensitivity is a bit of a surprise to me. I found another related issue to access_key/username in minio/minio#11126  .

**Comment by schemacs** [comment]
In this [commit](https://github.com/minio/docs/commit/11ad3d57c4e5e777c805051def2d4e888c91851d#diff-a84e2811eba8a2755427aa6116e1aa8c52c32bac2637be9644e26c19c843a483R365), This user added as `bakerReplicationAdmin` in this command `mc alias set BakerReplication HOSTNAME BakerReplicationAdmin LongRandomSecretKey` will not be found if the backend drivesr are case-sensitive.

**Comment by schemacs** [comment]
@harshavardhana You may also look into minio/docs#435 .

**Comment by harshavardhana** [comment]
> In this [commit](https://github.com/minio/docs/commit/11ad3d57c4e5e777c805051def2d4e888c91851d#diff-a84e2811eba8a2755427aa6116e1aa8c52c32bac2637be9644e26c19c843a483R365), This user added as `bakerReplicationAdmin` in this command `mc alias set BakerReplication HOSTNAME BakerReplicationAdmin LongRandomSecretKey` will not be found if the backend drivesr are case-sensitive.

We ask you not to use such filesystems if you expect seamless production experience use Linux filesystems.
