### ISSUE TITLE
mc support perf

### ISSUE THREAD

**Issue by AdheipSingh** [minio/mc#4028]
## Expected behavior
- i am trying to run parallel benchmarks on minio using ```mc support perf```, drawing comparison between sidekick vs k8s lb.
- while running mc support perf, i dont see any bucket created.
- is it correct to assume, that if i run ```mc support perf``` commands in parallel on same tenant, multiple buckets are created each using client ?

**Comment by klauspost** [comment]
`mc support perf` is not meant for parallel execution. It uses internal placement of files.

Use [warp](https://github.com/minio/warp) if you want to do [distributed benchmarking](https://github.com/minio/warp#distributed-benchmarking)

**Comment by AdheipSingh** [comment]
@klauspost thank you
