### ISSUE TITLE
JSON output not valid JSON

### ISSUE THREAD

**Issue by lionelg3** [minio/mc#4035]
## Expected behavior

When running "mc" with "--json" option, the output is not valid JSON.

## Actual behavior

The current output is not a valid JSON but a array of JSON item.

## Steps to reproduce the behavior

    $ mc --no-color --json admin user svcacct add play/ bob
    {
     "status": "success",
     "accessKey": "J5740WQM37YAMPPUC8BS",
     "secretKey": "FIxKxLo+Ia8b0MmPiK4SODbdKY5XHwgV+3i32qBP",
     "accountStatus": "enabled"
    }
    $ mc --no-color --json admin user svcacct add play/ bob
    {
     "status": "success",
     "accessKey": "263TVRDE51QZLVB6OS4E",
     "secretKey": "2K07SHHgeM38UvD8G3KqwyAffTelJwMD62FieziN",
     "accountStatus": "enabled"
    }

The following command output is not a valid JSON output.

    $mc --no-color --json admin user svcacct list play/ bob
    {
     "status": "success",
     "accessKey": "J5740WQM37YAMPPUC8BS"
    }
    {
     "status": "success",
     "accessKey": "263TVRDE51QZLVB6OS4E"
    }

## mc --version

      mc --version
      mc version RELEASE.2021-12-20T23-43-34Z

## System information

Linux and Mac.

**Comment by harshavardhana** [comment]
JSON output if JSON lines 

```
mc  | grep json
  --json                        enable JSON lines formatted output
```

https://jsonlines.org/
