### ISSUE TITLE
S3 URL with "s3" and virtual host style incorrectly parses bucket

### ISSUE THREAD

**Issue by martinrohrbach** [minio/mc#4036]
## Expected behavior
Given an S3 config such as this:

```
"s3test": {
        "url": "http://ns12.s3.domain.com",
        "accessKey": "accessKey",
        "secretKey": "secretKey",
        "api": "s3v4",
        "path": "off"
}
```

the Minio client should not interpret "ns12" as a bucket name. 

My client is using a Dell EMC ECS system for S3 storage and the "ns12" refers to a namespace within the system, hence it is an integral part of the URL, i.e. the correct target URL for accessing a bucket should be \<bucket>.\<namespace>.s3.domain.com.

## Actual behavior

Given the config above, the Minio client interprets everything in front of the "s3" as a bucket name which fails:

```
user@host:~$ mc --debug ls s3test
mc: <DEBUG> GET /ns12/?location= HTTP/1.1
Host: ns12.s3.domain.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-03-10T05-59-20Z
Authorization: AWS4-HMAC-SHA256 Credential=accessKey/20220401/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220401T145946Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 01 Apr 2022 14:59:46 GMT
Date: Fri, 1 Apr 2022 14:59:46 GMT
Server: ViPR/1.0
X-Amz-Id-2: 
X-Amz-Request-Id: 0af901a4:17f555e9db2:3bae5:b00

<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message><Resource>prod</Resource><RequestId>0af901a4:17f555e9db2:3bae5:b00</RequestId></Error>
```

However, if we setup an additional endpoint and replace the "s3" with "t4" such as this:

```
"t4test": {
        "url": "http://ns12.t4.domain.com",
        "accessKey": "accessKey",
        "secretKey": "secretKey",
        "api": "s3v4",
        "path": "off"
}
```

Everything works as expected, i.e. no bucket is parsed and assumed:

```
user@host:~$ mc --debug ls t4test
mc: <DEBUG> GET / HTTP/1.1
Host: ns12.t4.domain.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-03-10T05-59-20Z
Authorization: AWS4-HMAC-SHA256 Credential=accessKey/20220401/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220401T150213Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 434
Connection: keep-alive
Content-Type: application/xml
Date: Fri, 01 Apr 2022 15:02:13 GMT
Server: ViPR/1.0
X-Amz-Id-2: 
X-Amz-Request-Id: 0af901a4:17f555e9db2:3bb25:1ff
```

We strongly suspect this piece of code to be the culprit:
https://github.com/minio/mc/blob/master/cmd/client-s3.go#L1653

However, we feel that this behaviour cannot be as intended and should be fixed.

## Steps to reproduce the behavior

As described above.

## mc --version
mc version RELEASE.2022-03-31T04-55-30Z

## System information
S3 Storage: Dell EMC ECS v3.6.1.0
Client: Minio Client on Ubuntu 18.04

**Comment by vadmeste** [comment]
@martinrohrbach mc needs to have the endpoint without a bucket name, then you set path to 'on'

**Comment by martinrohrbach** [comment]
@vadmeste 
Sorry, with all due respect, but that makes no sense. 

We WANT virtual domain style so I deliberately set path to off. 

The endpoint does NOT contain the bucket, of course. If you are refering to the "ns12" then that is not a bucket as explained above. Minio client assumes that "s3" must always be the start of the base URL which is simply not true. 

(the AWS client handles this scenario just fine but I obviously would rather use Minio which is why I'm raising this here ;)

**Comment by vadmeste** [comment]
Oh yeah I was a little bit confused.

I think I understand what you mean now, let me try it.

**Comment by vadmeste** [comment]
@martinrohrbach yes, I am able to reproduce this. We will send a fix for this.
