### ISSUE TITLE
Feature Request - MC Client has no throttling

### ISSUE THREAD

**Issue by jamesarbrown** [minio/mc#4045]
## Expected behavior
Set max_con or rate or both, so when copying local S3 Minio to a cloud backup it can be slow and not upset all other traffic. work around with Qos but that affects normal S3 traffic too and not just backups.

## Actual behavior
Opens up lots and lots of uplinks at max rate

## Steps to reproduce the behavior
N/A

## mc --version
minio/mc:RELEASE.2022-03-17T20-25-06Z

## System information
Kubernetes on Ubuntu 20

**Comment by harshavardhana** [comment]
you throttle it outside my friend @jamesarbrown using techniques like 

```
  annotations:
    kubernetes.io/ingress-bandwidth: 500m
    kubernetes.io/egress-bandwidth: 500m
```

https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/

**Comment by jamesarbrown** [comment]
Thanks..... I will investigate more as I can not see that is migrating from a cronjob to a job to a pod. So not working for me.

My main point was a limit to the spawning of the connections. Mc client is spawning many many connections and that can not be controlled with Kubernetes techniques.

**Comment by baryluk** [comment]
Could this be revisited please?

Not everybody uses Kubernetes or CNI that supports bandwidth limits.

The CNI bandwidth limits are also experimental at the moment. The bandwidth limits on container level also are not perfect either, as they usually adjust speed by dropping packets and use TCP to limit its speed, and that is a bit choppy.


I often use `mc` manually directly from hosts (outside of docker or kubernetes), and lack of `mc` control for download and upload is very problematic. No such issues with `aws s3 cp`, `s3cmd` or `rsync` which all supports this out of the box.

**Comment by harshavardhana** [comment]
> Could this be revisited please?
> 
> Not everybody uses Kubernetes or CNI that supports bandwidth limits.
> 
> The CNI bandwidth limits are also experimental at the moment. The bandwidth limits on container level also are not perfect either, as they usually adjust speed by dropping packets and use TCP to limit its speed, and that is a bit choppy.
> 
> I often use `mc` manually directly from hosts (outside of docker or kubernetes), and lack of `mc` control for download and upload is very problematic. No such issues with `aws s3 cp`, `s3cmd` or `rsync` which all supports this out of the box.

You are free to use those tools, we consider this outside `mc` scope.

You use traffic control if you don't use it yet https://man7.org/linux/man-pages/man8/tc.8.html

Has been around 2 decades.

**Comment by baryluk** [comment]
> You use traffic control if you don't use it yet https://man7.org/linux/man-pages/man8/tc.8.html

It requires root, and cannot be adjusted dynamically per-process invocation.  `tc` is absolutely unsuitable for this task.

**Comment by harshavardhana** [comment]
There are enough alternatives out there. This is not something mc will do at the moment.

**Comment by harshavardhana** [comment]
> I often use `mc` manually directly from hosts (outside of docker or kubernetes), and lack of `mc` control for download and upload is very problematic. No such issues with `aws s3 cp`, `s3cmd` or `rsync` which all supports this out of the box.

We revisited this topic and it is implemented https://github.com/minio/mc/pull/4388
