### ISSUE TITLE
--preserve with mirror doesn't seem to work as expected

### ISSUE THREAD

**Issue by darrepac** [minio/mc#4058]
## Expected behavior
Preserve timestamps

## Actual behavior
mc stat on remote:
Name      : fdcf5962-d587-4b94-a939-e492df211cf7.fit
Date      : 2022-04-20 17:59:30 CEST
Size      : 161 KiB
ETag      : 043bdcf583c0c8e732e6d4706b4e8f05
Type      : file
Metadata  :
Content-Type: application/octet-stream

stat on local system:

  File: fdcf5962-d587-4b94-a939-e492df211cf7.fit
  Size: 165035          Blocks: 328        IO Block: 4096   regular file
Device: 25h/37d Inode: 1240023     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-04-21 02:03:35.941984249 +0200
Modify: 2022-04-21 02:03:36.071985223 +0200
Change: 2022-04-21 02:03:36.072985230 +0200
 Birth: -

**2022-04-20 17:59:30 CEST is lost...**

## Steps to reproduce the behavior
I am doing `mc mirror --overwrite --preserve` 
## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2022-04-16T21-11-21Z

## System information
Linux ubuntu1 4.4.180+ #42218 SMP Mon Oct 18 19:16:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You need to have first synced from local to object store for the store back to local to work.

The mtime on object store is not what is preserved on the filesystem.

**Comment by darrepac** [comment]
I don’t get you. My objects are on the store and I want to have a local copy, what you would like me to do?

if the time is not preserved, what is preserved with —preserve option?

**Comment by DipalPrajapati** [comment]
Same question ! This --preserve is not working

**Comment by klauspost** [comment]
Custom tags, locks. None of which apply to local files.
