### ISSUE TITLE
unable to add ilm policy to aws s3 buckets

### ISSUE THREAD

**Issue by Akshaykadam66** [minio/mc#4063]
I want to set retention of 110 days for the objects stored on aws s3  buckets, while trying to do this using minio mc, i am facing `mc: <ERROR> Unable to fetch lifecycle rules for myminio/demo15.receive. A header you provided implies functionality that is not implemented.`  error.
The mc command i am using is : ` mc ilm add --expiry-days 110 myminio/demo15.receive` where myminio is my alias set to minio endpoint and demo15.receive is my s3 bucket
I am succesfully able to list the contents of demo15.receive s3 bucket using command : `mc find myminio/demo15.receive --name "*.json"` but not able to add Lifecycle configuration for object 

Any help/suggestions would be appreciated , thanks in advance

**Comment by kannappanr** [comment]
This functionality is not supported in Gateway

**Comment by Akshaykadam66** [comment]
@kannappanr May i know more about this , what exactly has to be done to make it working, as i am new to these things not completely sure about these things
