### ISSUE TITLE
Feature request: minio sso login

### ISSUE THREAD

**Issue by bruno-villa** [minio/mc#4077]
## Expected behavior
This is not a bug but a feature request, for which there was no template. Please let me know if this is not the correct place for request discussions. 
Ideally mc would offer a `login` command for oidc authentication through the STS. Currently, it is possible to log in with a federated IdP to the Console UI. It would be handy to also be able to run `mc` commands without an explicit user in MinIO. That is running something like
```
mc login --sso --alias myalias
```
which would open a browser window for the user to log in with the IdP and automatically store the temporary access/secret keys in an alias in the credentials file after a successful login. 
This would be similar to how e.g. ArgoCD does it with `argocd login $ARGOCD_SERVER --sso`. 

## Actual behavior
Afaik any user wanting to run `mc` commands must be registered as a user in MinIO and be provided a set of credentials (access/secret keys). 

## Steps to reproduce the behavior
n.a. 

## mc --version
- mc version RELEASE.2022-05-04T06-07-55Z

## System information
n.a.

**Comment by harshavardhana** [comment]
You do not need SSO login for mc,  mc is supposed to be headless and automated your job is to generate service accounts for your SSO login through Console UI.

Use those service accounts to talk to MiniO. 

If you wish to use temporary credentials then generate one programmatically for short term access and provide them as temporary values in 

https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#rotating-credentials

mc infact already supports SSO, just that it has no business doing SSO auth flow it is purely a credentials driven tool.

**Comment by bruno-villa** [comment]
@harshavardhana I see - was not aware that the user has the ability to create service accounts from the console. That makes it clear then. Thank you.
