### ISSUE TITLE
Missing "mc support" documentation

### ISSUE THREAD

**Issue by mshanmu** [minio/mc#4078]
## Expected behavior

https://docs.min.io/docs/minio-client-complete-guide.html has information on "mc support" command

## Actual behavior

No documentation found. 

## mc --version
- (paste output of `mc --version`)

**Comment by ravindk89** [comment]
https://github.com/minio/docs/issues/438

This work is being handled in a separate commit and will be documented on docs.min.io/minio/baremetal

There is also an ongoing IA project to fully move away from the contents of docs.min.io

Please track the issue above for resolution on `mc support` web docs. In the meantime you can always use `mc support --help` in the CLI for a quick reference.
