### ISSUE TITLE
Rename objects prefix

### ISSUE THREAD

**Issue by vincent-herlemont** [minio/mc#4081]
## Context

- Minio Standalone
- Concern about performance for this action
   - 10 Millon files
   - Between 1K to 1G
   - 10 To

## Expected behavior

I would like to update prefix object bulk. For example I would rename the `prefix_2`to `prefix_3` from
```bash
[2022-05-06 16:45:34 UTC] 6.4KiB STANDARD prefix_1/filename_1
[2022-05-06 16:45:34 UTC] 1.8KiB STANDARD prefix_1/filename_2
[2022-05-06 16:45:34 UTC] 121KiB STANDARD prefix_2/filename_3
[2022-05-06 16:45:34 UTC] 121KiB STANDARD prefix_2/filename_4
```
Expected result: 
```bash
[2022-05-06 16:45:34 UTC] 6.4KiB STANDARD prefix_1/filename_1
[2022-05-06 16:45:34 UTC] 1.8KiB STANDARD prefix_1/filename_2
[2022-05-06 16:45:34 UTC] 121KiB STANDARD prefix_3/filename_3
[2022-05-06 16:45:34 UTC] 121KiB STANDARD prefix_3/filename_4
```

## Actual behavior / Steps to reproduce the behavior

I try to use the combinaison of [`mc mv`](https://docs.min.io/minio/baremetal/reference/minio-mc/mc-mv.html) and [`mc mb`](https://docs.min.io/minio/baremetal/reference/minio-mc/mc-mb.html#command-mc.mb) to achieve that.
```bash
# Create `test_3` prefix
$> mc mb minio/bucket/test_3
# Move objects
$>  mc mv --recursive minio/bucket/test_2/ minio/bucket/test_3/
```

That works :heavy_check_mark:  but ...

## Questions

- Regarding the concern about performance in the section context of this issue.
Is there a better solution than these two actions  [`mc mv`](https://docs.min.io/minio/baremetal/reference/minio-mc/mc-mv.html) and [`mc mb`](https://docs.min.io/minio/baremetal/reference/minio-mc/mc-mb.html#command-mc.mb) ?
- There is any concerns about  [`mc mv`](https://docs.min.io/minio/baremetal/reference/minio-mc/mc-mv.html) in minio? Decrease performance? Increase the size of the buckets etc?

## System information

- Docker image latest [minio/mc](https://hub.docker.com/r/minio/mc/)
- Docker image latest [minio/minio](https://hub.docker.com/r/minio/minio)

**Comment by klauspost** [comment]
There is no move/rename functionality in S3, so an operation like this will always be rather expensive, and you shouldn't rely on this for everyday tasks.
