### ISSUE TITLE
The mc mirror command is missing sone basic functionality

### ISSUE THREAD

**Issue by Ronald1962** [minio/mc#4085]
## Expected behavior
mc mirror should have options to 1. only mirror files that do not exist on the target yet (like the rsync --ignore-existing option), or 2. mirror files not existing on the target yet + files that have a modification time on the source that is greater than the modification time on the target (like the rsync --update option). Also an --ignore-error option would be welcome to skip files that cannot be synchronized, instead of immediately ending with an exception.

## Actual behavior
We miss a few options that other synchronization tools have (but those tools do not work on object stores).

## mc --version
mc version RELEASE.2022-05-09T04-08-26Z

## System information
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

**Comment by harshavardhana** [comment]
> mc mirror should have options to 1. only mirror files that do not exist on the target yet (like the rsync --ignore-existing option), or 2. mirror files not existing on the target yet + files that have a modification time on the source that is greater than the modification time on the target (like the rsync --update option). Also an --ignore-error option would be welcome to skip files that cannot be synchronized, instead of immediately ending with an exception.

mc mirror -a is what you want to `--update` - `--ignore-existing` is default behavior without `-a` @Ronald1962 if you use `--watch`  along with `-a` `mc mirror` will forever keep it running watching for new changes on the source, while also ignoring any errors on the source.

**Comment by Ronald1962** [comment]
Thanks for answering, but I tried `-a` (`--preserve`) and it seems rather to do the very opposite of --update and --ignore-existing. I have some files om my target that are newer then on my source. There seems to be no way that I can mirror a source to a target without overwriting newer files with older versions. And also with `--preserve` the mirroring just crashes when encountering a problem with any file.
