### ISSUE TITLE
mc client is not work...

### ISSUE THREAD

**Issue by Livenux** [minio/mc#4098]
## Expected behavior
`mc ls play` -> reponse buckets
`mc cp direcory/bucket play/bucket`  -> upload to bucket
`mc ls play/bucket` -> list bucket item

## Actual behavior
`mc ls play` ->  empty reponse
`mc cp direcotry/object play/bucket` ->  create local direcotry and cp object  
`mc ls play/bucket` ->  mc: <ERROR> Unable to list folder. Requested file `/local/path/play/bucket` not found

## Steps to reproduce the behavior
`mc ls play`  
`mc cp direcotry/object play/bucket`
`mc ls play/bucket`

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2022-05-09T04-08-26Z

## System information
ubuntu 20.04 x86-64

**Comment by vadmeste** [comment]
> mc ls play -> reponse buckets

I must have a local directory called 'play'. If it exists, then mc will prioritize it over the S3 alias.
