### ISSUE TITLE
Speedtest for network fnd objects doesn't work in distributed setup

### ISSUE THREAD

**Issue by AlexZIX** [minio/mc#4103]
## Expected behavior
Got right results for speedtest of minio distributed instance.

## Actual behavior
When I run the speedtest I got zeros when testing speed for objects  and infinite speedtest in case of network testing.

C:\Users\Aleksey Pletnev>mc support perf object minio-hot

        THROUGHPUT      IOPS
PUT     0 B/s           0 objs/s
GET     0 B/s           0 objs/s

Speedtest: MinIO 2022-05-19T18:20:59Z, 3 servers, 6 drives, 64 MiB objects, 41 threads

## Steps to reproduce the behavior
Run speedtest for duistributed minio instance.

## mc --version
mc version RELEASE.2022-05-09T04-08-26Z

## System information
MinIO version: 2022-05-19T18:20:59Z
OS version: Linux minio-1 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Instance: 3 nodes with 2 NVME SSD disks on each

**Comment by AlexZIX** [comment]
At the same time I got right results for drive tests.

C:\Users\Aleksey Pletnev>mc support perf drive minio-hot
┌────────────────────────┬─────────────┬───────────┬───────────┐
│ Node                   │ Path        │ Read      │ Write     │
│ minio-2.bazis.net:9000 │ /disks/ssd1 │ 2.1 GiB/s │ 214 MiB/s │
│ minio-2.bazis.net:9000 │ /disks/ssd2 │ 2.1 GiB/s │ 213 MiB/s │
└────────────────────────┴─────────────┴───────────┴───────────┘
┌────────────────────────┬─────────────┬───────────┬───────────┐
│ Node                   │ Path        │ Read      │ Write     │
│ minio-3.bazis.net:9000 │ /disks/ssd1 │ 2.5 GiB/s │ 175 MiB/s │
│ minio-3.bazis.net:9000 │ /disks/ssd2 │ 2.3 GiB/s │ 182 MiB/s │
└────────────────────────┴─────────────┴───────────┴───────────┘
┌────────────────────────┬─────────────┬────────────┬──────────┐
│ Node                   │ Path        │ Read       │ Write    │
│ minio-1.bazis.net:9000 │ /disks/ssd1 │ 952 MiB/s  │ 64 MiB/s │
│ minio-1.bazis.net:9000 │ /disks/ssd2 │ 1019 MiB/s │ 61 MiB/s │
└────────────────────────┴─────────────┴────────────┴──────────┘

**Comment by harshavardhana** [comment]
On a real NVMe setup here is what the performance will be  - you need to really fix your setup.

```
mc support perf all-nodes/

        THROUGHPUT      IOPS           
PUT     31 GiB/s        497 objs/s
GET     45 GiB/s        717 objs/s

Speedtest: MinIO 2022-05-19T18:20:59Z, 7 servers, 70 drives, 64 MiB objects, 72 threads
```

```
mc support perf net all-nodes/
https://all-nodes-ss-0-0.all-nodes-hl.ns-1.svc.cluster.local:9000 TX: 9.7 GiB/s RX: 9.5 GiB/s
https://all-nodes-ss-0-1.all-nodes-hl.ns-1.svc.cluster.local:9000 TX: 9.9 GiB/s RX: 9.5 GiB/s
https://all-nodes-ss-0-2.all-nodes-hl.ns-1.svc.cluster.local:9000 TX: 9.8 GiB/s RX: 9.6 GiB/s
https://all-nodes-ss-0-3.all-nodes-hl.ns-1.svc.cluster.local:9000 TX: 9.5 GiB/s RX: 9.7 GiB/s
https://all-nodes-ss-0-5.all-nodes-hl.ns-1.svc.cluster.local:9000 TX: 9.4 GiB/s RX: 9.8 GiB/s
https://all-nodes-ss-0-6.all-nodes-hl.ns-1.svc.cluster.local:9000 TX: 9.7 GiB/s RX: 9.6 GiB/s
https://all-nodes-ss-0-4.all-nodes-hl.ns-1.svc.cluster.local:9000 TX: 9.5 GiB/s RX: 9.5 GiB/s
```

**Comment by klauspost** [comment]
Yes, that is expected. Please refer to my previous message for further assistance.
