### ISSUE TITLE
Certificate on dl.minio.io is expired

### ISSUE THREAD

**Issue by Dam-Buty** [minio/mc#4134]
## Expected behavior

Installing mc from homebrew should work

## Actual behavior

Download crashes because of an expired certificate

![image](https://user-images.githubusercontent.com/1461760/175326477-133dc8ee-d550-4c1d-8690-6f2708379d2b.png)

![image](https://user-images.githubusercontent.com/1461760/175326530-1b7410a7-208a-4d65-b577-4c3ad4ce8a4e.png)

## Steps to reproduce the behavior

`brew install minio/stable/mc`

## mc --version
- N/A as i can't install

## System information

MacOs 12.2.1

**Comment by harshavardhana** [comment]
Its already @Dam-Buty

**Comment by Dam-Buty** [comment]
wow that was fast, thanks @harshavardhana !
