### ISSUE TITLE
HTTP request error failed to copy to S3 with mc mirror

### ISSUE THREAD

**Issue by coopzilla** [minio/mc#4138]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
we are trying to copy images from a local minio instance to S3.  We get failures with the mc mirror command thinking the length is zero:
![image](https://user-images.githubusercontent.com/74570068/176261047-e8cb1338-a807-4cab-a0cf-656dd70a2652.png)
we can see that the image size is not zero
![image](https://user-images.githubusercontent.com/74570068/176261207-e60e8269-4e4f-4ae8-b6dc-d98b0b1dac3b.png)

This happen very often.  I have seen other posts for this
https://github.com/minio/mc/issues/3965

But they found a workaround with tar'ing the whole file set.

## Current Behavior
We try to run a backup from local minio to S3 nightly.  We see the above error

## Steps to Reproduce (for bugs)
![image](https://user-images.githubusercontent.com/74570068/176261846-b0652666-ca14-44fc-b1d6-49e52e55893c.png)

## Context
We are replicating local storage nightly.  And this will fail every night.

## Your Environment
We run minio in a docker container
we run the backupscript in a separate container
Linux ubuntu 18.04

**Comment by MrScruffyish** [comment]
Any progress on this one? 
I ran mc mirror as a systemd service and got the error in the log

`mc: <ERROR> Failed to copy `https://some.place/bucket/file`. Put "https://some.place.else>`

but mc seem to have continued fine with other files, and this one was not copied.

Isn't mc supposed to retry the operation? 
Will mc quietly ignore the error after retrying a few times and continue with other files. Can this behaviour be changed (with an option to crash on error perhaps)?

Restarting the service worked and the file was synced.

**Comment by vadmeste** [comment]
I would say most likely this is not an mc issue and you should have an error in MinIO servers log

**Comment by harshavardhana** [comment]
> Any progress on this one? I ran mc mirror as a systemd service and got the error in the log
> 
> `mc: <ERROR> Failed to copy `[https://some.place/bucket/file`](https://some.place/bucket/file%60). Put "[https://some.place.else>`](https://some.place.else%3E%60)
> 
> but mc seem to have continued fine with other files, and this one was not copied.
> 
> Isn't mc supposed to retry the operation? Will mc quietly ignore the error after retrying a few times and continue with other files. Can this behaviour be changed (with an option to crash on error perhaps)?
> 
> Restarting the service worked and the file was synced.

Not all errors are retriable @MrScruffyish

**Comment by MrScruffyish** [comment]
If that was a min-retriable error, should not mc quit with error status?
Or should one run mc mirror by looping until you dont see any error (you better not miss any errors then). 
Since the file that gave the non retriable error was synced when I re-ran mc, I guess it does not re-try those, ever, until you re-start mc. 

Have I misunderstood how to use mc mirror or is there a need for some options on error handling for mc?

**Comment by harshavardhana** [comment]
> If that was a non-retriable error, should not mc quit with error status?

No we do not - it is best effort copy the rest and deal with what is not copied later @MrScruffyish

**Comment by harshavardhana** [comment]
To monitor `mc mirror` we have Prometheus metrics exposed

```
cmd/mirror-main.go:             Name: "mc_mirror_total_s3ops",
cmd/mirror-main.go:             Name: "mc_mirror_total_s3uploaded_bytes",
cmd/mirror-main.go:             Name: "mc_mirror_failed_s3ops",
cmd/mirror-main.go:             Name: "mc_mirror_total_restarts",
cmd/mirror-main.go:                     Name:    "mc_mirror_replication_duration",
```

**Comment by harshavardhana** [comment]
Let's verify if this was indeed a non-retriable error @MrScruffyish can you paste the exact error?

**Comment by MrScruffyish** [comment]
Sep 29 10:44:10 minioclient minio_replication_job[1252171]: mc:  Failed to copy `https://minioserver1/bucket1/file.foo`. Put "https://s3server/bucket2/file.foo": net/http: HTTP/1.x transport connection broken: http: ContentLength=192 with Body length 0

That is the complete message I got (redacted)


By the way, is there any documentation (except for the source code) where I can read more about the inner workings of mc mirror?  Like, how does it detect new files, how often does it check for new files, how does it detect changes in existing files, how does it keep track of what is at the receiving end?

**Comment by MrScruffyish** [comment]
@harshavardhana 
> No, we do not it is not desirable - it is best effort copy the rest and deal with what is not copied later @MrScruffyish

What does later mean in this context? We have hade mc mirror running for a few days and we have a file that has not been retried for 6 hours

**Comment by harshavardhana** [comment]
> By the way, is there any documentation (except for the source code) where I can read more about the inner workings of mc mirror? Like, how does it detect new files, how often does it check for new files, how does it detect changes in existing files, how does it keep track of what is at the receiving end?

Everything that it does exist `cmd/difference.go`  any result returned via "Two site difference" simply means `mirror` it.

**Comment by harshavardhana** [comment]
> Sep 29 10:44:10 minioclient minio_replication_job[1252171]: mc: Failed to copy `https://minioserver1/bucket1/file.foo`. Put "https://s3server/bucket2/file.foo": net/http: HTTP/1.x transport connection broken: http: ContentLength=192 with Body length 0

This is a non-retryable error since something happened to the incoming stream that was being uploaded. It looks like something to do with your LB that seems to close connections here on a regular interval.

**Comment by justinfx** [comment]
Sorry to ping a stale issue, but I found this one to be close to something I am investigating right now.
@harshavardhana you made a point about the Bad Request PUT operation being possibly related to a load balancer closing the stream in a way that results in a non retryable error.
I'm using Minio Sidekick to front the request to 3 Minio nodes. I can repro a situation where I run an `mc cp` in a loop, and then kill one of the minio nodes. When I bring the node back up, I will see Sidekick start routing requests to it and the first ones will fail the same way as the previous example listed. The client gets a 502 Bad Gateway from Sidekick, and the Minio says 400 http error.
What I'm wondering is whether the error would normally be retryable if the client went right to the given node, but is Sidekick handling the error to the client in a way that it isn't retryable?
Ultimately I am trying to determine why it isn't safe to cycle minio nodes in a way where it won't fail the client requests through Sidekick (without retry). I would expect it to be more transparent.
