### ISSUE TITLE
Healing summary is inaccurate

### ISSUE THREAD

**Issue by haslersn** [minio/mc#4139]
On a MinIO cluster where a drive failed, 10 hours after replacing the drive, we have the following summary printed by `mc admin heal alias --verbose`:

```
Objects Healed: 128,246/646,714 (19.8%), 630 GB/3.6 TB (17.6%)
Heal rate: 1 obj/s, 27 KiB/s
Estimated Completion: 5 days 
```

## Expected Behavior

The displayed heal rate should be around 3.6 obj/s and 17.5 MB/s. The displayed estimated completion should be around 1-2 days.

## Your Environment

* Version used: 2022-06-20T23:13:45Z

**Comment by klauspost** [comment]
```
		bytesHealedPerSec := float64(uint64(time.Second)*bytesHealed) / float64(accumulatedElapsedTime)
		itemsHealedPerSec := float64(uint64(time.Second)*itemsHealed) / float64(accumulatedElapsedTime)
```

@vadmeste When you accumulate time for each set and use that for the rate you are no accounting for overlapping time.

To get the rate you must calculate the rate for each set and add it together (without division). That will at least give a more precise time.

It doesn't account for different start times, but it will at least give the total average rate for all running sets.

**Comment by vadmeste** [comment]
@haslersn can you double check your mc version ? (there is no 2022-06-20T23:13:45Z version for mc)

**Comment by vadmeste** [comment]
@haslersn can you do `mc admin heal <alias> --json` and upload the output here?

**Comment by haslersn** [comment]
> there is no 2022-06-20T23:13:45Z version for mc

That is the MinIO version. For results with a current mc version, see my previous comment.

> Could you post `mc admin heal --json alias`?

[heal.txt](https://github.com/minio/mc/files/9018474/heal.txt)

**Comment by vadmeste** [comment]
@haslersn 
 ```
  minio-old-zone0-1.minio-old.s3.svc.cluster.local:9000:                                                                                                                                                    
  +  /disks/disk0 : OK                                                                                                                                                                                      
  |__  Capacity: 525 GiB/1.8 TiB                                                                                                                                                                            
  +  /disks/disk1 : HEALING                                                                                                                                                                                 
  |__ Estimated: now                                                                                                                                                                                        
  |__  Capacity: 2.2 TiB/15 TiB                                                                                                                                                                             
  +  /disks/disk2 : OK                                                                                                                                                                                      
  |__  Capacity: 525 GiB/1.8 TiB                                                                                                                                                                            
  +  /disks/disk3 : OK                                                                                                                                                                                      
  |__  Capacity: 525 GiB/1.8 TiB  
  ```
  
 @haslersn the disk that you are healing shows unexpected information, can you double check why it has 2.2 TiB ?

**Comment by vadmeste** [comment]
@klauspost the code was changed very recently. Now, the completion estimation time is the highest estimation time among all sets. (this was simplified)

For the rate calculation, what the code is doing, it accumlates the number of objects healed in all sets, it accumulates the time being spent in healing for each set separately, and then calculates the estimation. I don't think there is overlapping here.

**Comment by haslersn** [comment]
> @haslersn the disk that you are healing shows unexpected information, can you double check why it has 2.2 TiB ?

These are virtual disks. The physical disk where it's on has 2.1 TiB used in a different subfolder.

**Comment by haslersn** [comment]
I think this might be similar to a setup with DirectPV. AFAIK DirectPV also creates a subfolder per volumes. Though I'm not sure, because I never really used DirectPV.

**Comment by harshavardhana** [comment]
> I think this might be similar to a setup with DirectPV. AFAIK DirectPV also creates a subfolder per volume. Though I'm not sure, because I never really used DirectPV.

DirectPV uses xfsprj quota - which does not face the same limitations of simple subdir @haslersn

**Comment by vadmeste** [comment]
I don't think anything is pending here. This ticket was originally fixed by this https://github.com/minio/mc/pull/4124
