### ISSUE TITLE
mc alias set error

### ISSUE THREAD

**Issue by winlong** [minio/mc#4146]
## the error message:
`mc: <ERROR> Unable to initialize new alias from the provided credentials. XML syntax error on line 1: unquoted or missing attribute value in element.`

## mc --version
- mc version RELEASE.2022-06-26T18-51-48Z (commit-id=40ee1a4ed60f3b2f618c4eef282ff8b29ace7045)
Runtime: go1.18.3 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by vadmeste** [comment]
@winlong I doubt the endpoint that you passed points to MinIO API. Can you run the same command with --debug flag ?
