### ISSUE TITLE
Unable to Login with Minio Console

### ISSUE THREAD

**Issue by manjuangadi** [minio/mc#4167]
## Expected behavior
Minio Console login should be successful for the root user credentials "minioadmin:minioadmin"

## Actual behavior
Http 401 is received for the root user, with Authentication Failed error.

## Steps to reproduce the behavior
1. brew install minio/stable/minio
2. minio server /opt/minio/data (my own path)

## mc --version
mc version RELEASE.2022-07-24T02-25-13Z (commit-id=015134b2b730f3b8edd1e481d080a87e07b21df3)
Runtime: go1.18.4 darwin/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
on MAC OS - Montere 12.4

**Comment by kannappanr** [comment]
@manjuangadi Why is this an mc issue? Can you please open the issue in minio/console repo?

**Comment by harshavardhana** [comment]
You might have typed your credentials wrong at the login page, just tested vanilla install its working fine.

**Comment by manjuangadi** [comment]
@harshavardhana - I have my credentials right and its the same credentials i used "minioadmin:minioadmin" which is displayed on the server startup.

If it is working for you, its definitely to do with MAC OS version ! please do check.
