### ISSUE TITLE
mc rb --force throws an error message despite of deleting the bucket.

### ISSUE THREAD

**Issue by bh4t** [minio/mc#4174]
## Expected behavior
There should be no error message. Should display a message saying the bucket is deleted.

## Actual behavior
The bucket and the objects within are removed, however there is an error message that is displayed:

mc: <ERROR> Failed to remove `myminio/firstbucket/mirrormirror`. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.

## Steps to reproduce the behavior
- Create a bucket on the server.
- Copy an object within the bucket.
- Run ./mc rb --force myminio/firstbucket/mirrormirror

## mc --version
RELEASE.2022-07-24T02-25-13Z

**Comment by dormanze** [comment]
I don't think this is a problem.
If you want to delete an object, You should run `./mc myminio/firstbucket/mirrormirror`.
If you want to delete an bucket, You should run `./mc rb --force myminio/firstbucket`.

**Comment by harshavardhana** [comment]
The error message can be more clear here - it doesn't indicate what is "invalid" about the arguments.
