### ISSUE TITLE
Error message for admin user policy can be more clear.

### ISSUE THREAD

**Issue by bh4t** [minio/mc#4179]
## Expected behavior
Error message could be "Policy not found for the user  username"

## Actual behavior
The current error message is displayed as below:

./mc admin user policy myminio preeti2
mc: <ERROR> Unable to fetch user policy document. Only a single policy may be specified here.

## Steps to reproduce the behavior
- Create a user
- Run the command admin user policy myminio username

## mc --version
RELEASE.2022-07-29T19-17-16Z

**Comment by kannappanr** [comment]
fixed by #4206
