### ISSUE TITLE
panic when transport channel was closed accidently

### ISSUE THREAD

**Issue by chipitsine** [minio/mc#4202]
## Expected behavior

not to panic

## Actual behavior

mc.exe mirror x/x y/y )
...x.docx:  1001.13 MiB / 1001.13 MiB [===================================================================================] 1.78 MiB/smc.exe: <ERROR> Failed to copy `http://x/x.docx`. Put "https://storage.yandexcloud.net/....x.docx": net/http: HTTP/1.x transport connection broken: http: ContentLength=12059 with Body length 0
panic: send on closed channel

goroutine 3117 [running]:
github.com/minio/minio-go/v7.(*Object).doGetRequest(_, {{0xc0035b4000, 0x8000, 0x8000}, 0x1e0000, 0x0, 0x1, 0x0, 0x1, 0x0, ...})
        github.com/minio/minio-go/v7@v7.0.31/api-get-object.go:319 +0xdc
github.com/minio/minio-go/v7.(*Object).Read(0xc000a28a80, {0xc0035b4000?, 0x793dd4?, 0xc000a2bc00?})
        github.com/minio/minio-go/v7@v7.0.31/api-get-object.go:399 +0x248
io.(*LimitedReader).Read(0xc0007b4000, {0xc0035b4000?, 0x8000?, 0x8000?})
        io/io.go:476 +0x45
github.com/minio/minio-go/v7.(*hookReader).Read(0xc001b142c0, {0xc0035b4000, 0x0?, 0x8000})
        github.com/minio/minio-go/v7@v7.0.31/hook-reader.go:76 +0xc9
io.(*LimitedReader).Read(0xc0007b4120, {0xc0035b4000?, 0x8000?, 0x8000?})
        io/io.go:476 +0x45
io.copyBuffer({0x1e124cf11e0, 0xc000a2bc00}, {0x1427020, 0xc0007b4120}, {0x0, 0x0, 0x0})
        io/io.go:426 +0x1b2
io.Copy(...)
        io/io.go:385
net/http.persistConnWriter.ReadFrom({0xc00095c018?}, {0x1427020?, 0xc0007b4120?})
        net/http/transport.go:1775 +0x5b
bufio.(*Writer).ReadFrom(0xc001bbac80, {0x1427020, 0xc0007b4120})
        bufio/bufio.go:768 +0x1ab
io.copyBuffer({0x1424e80, 0xc001bbac80}, {0x1427020, 0xc0007b4120}, {0x0, 0x0, 0x0})
        io/io.go:412 +0x14b
io.Copy(...)
        io/io.go:385
net/http.(*transferWriter).doBodyCopy(0xc003486960, {0x1424e80?, 0xc001bbac80?}, {0x1427020?, 0xc0007b4120?})
        net/http/transfer.go:411 +0x4d
net/http.(*transferWriter).writeBody(0xc003486960, {0x1424e80, 0xc001bbac80})
        net/http/transfer.go:369 +0x3d5
net/http.(*Request).write(0xc0000d6c00, {0x1424e80, 0xc001bbac80}, 0x0, 0x0, 0x0)
        net/http/request.go:698 +0xb46
net/http.(*persistConn).writeLoop(0xc002deec60)
        net/http/transport.go:2395 +0x185
created by net/http.(*Transport).dialConn
        net/http/transport.go:1751 +0x1791

(mc.exe mirror x/x y/y )
...x.png:  1.37 MiB / 1.37 MiB [====================================================================================] 416.49 KiB/s 3s

## Steps to reproduce the behavior

I ran "mirror" for many files on unstable internet connection, which accidently gets broken

## mc --version

mc.exe --version
mc version RELEASE.2022-08-05T08-01-28Z (commit-id=351d021b924b4d19f1eb716b9e2bd74644c402d8)
Runtime: go1.18.5 windows/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information

windows 10

**Comment by harshavardhana** [comment]
This requires minio-go update we will do that today.

**Comment by chipitsine** [comment]
I understand that issue may be fixed already in master branch. I use windows mc.exe, I'm too lazy to build it from master :)
feel free to close issue if it is known/fixed already
