### ISSUE TITLE
Recursive Copy fails to resume previous session

### ISSUE THREAD

**Issue by thebetauser** [minio/mc#4213]
## Expected behavior
When executing a copy command with the --continue flag the client should resume the upload from the previously failed file

## Actual behavior
After an upload fails, issuing the same command does not resume the upload but starts from the beginning. 

Edit: I was able to actually resume a previously failed session, so this seems to be intermittent issue. I'm going to see if I can track it down some more

## Steps to reproduce the behavior

1. `mc cp --continue --recursive "F:\Pictures" minio/pictures/`
2. Error: mc: <ERROR> Failed to copy 'F:\Pictures\Videos\video1.mpg'. A timeout exceeded while waiting to proceed with the request, please reduce your request rate
3. mc: <ERROR> Command terminated safely. Run this command to resume copy again.
4. Re-issue command from step 1 and the upload starts from the beginning

## mc --version
- mc version RELEASE.2022-08-11T00-30-48Z (commit-id=c2c2ab4299bbb243c55644984392f1c39af499cf)
Runtime: go1.18.5 windows/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
Release-Tag:RELEASE.2022-08-11T00-30-48Z | Commit:c2c2ab4299bb | Host:LAPTOP | OS:windows 11 (21H2) | Arch:amd64 | Lang:go1.18.5 | Mem:323 MB/1.6 GB | Heap:323 MB/1.5 GB

**Comment by thebetauser** [comment]
I can confirm this is not a implementation bug but more of a visual issue. 

When resuming a saved session there is no notification/output to let's the user know that the current process is comparing local/remote files. I wrongfully assumed the progress indicator showed a new upload session because it started from 0 and went through the entire set of files to upload.

If it is deemed no changes need to be made to notify the user of the resume process you can go ahead and close out this issue.

**Comment by shtripat** [comment]
Is it supposed better if an additional message shown during command `mc --continue --recursive cp` to mention that `Resuming copy from <current size copied> / <total size to  be copied>` ?

**Comment by harshavardhana** [comment]
> Is it supposed better if an additional message shown during command `mc --continue --recursive cp` to mention that `Resuming copy from <current size copied> / <total size to be copied>` ?

A first line shown with this message would be a good idea and the second line to show the progress bar.

**Comment by shtripat** [comment]
Resolved as part of https://github.com/minio/mc/pull/4454. Closing.
