### ISSUE TITLE
net/http: HTTP/1.x transport connection broken: http: ContentLength=334173 with Body length 0

### ISSUE THREAD

**Issue by dingsongjie** [minio/mc#4231]
When i use mc mirror command to sync files between to bucket ,i saw some errors ,and files with this error will not be synced.

mc: <ERROR> Failed to copy `http://xxx:9000/erp-prd/ProductPic/2022/08/31/630f231a327ffa0002db475c.png`. Put "https:/xxxx/2022/08/31/630f231a327ffa0002db475c.png": net/http: HTTP/1.x transport connection broken: http: ContentLength=334173 with Body length 0

**Comment by vadmeste** [comment]
@dingsongjie do this happen always with the same object name ? if not then it is just a simple networking issue

**Comment by dingsongjie** [comment]
> @dingsongjie do this happen always with the same object name ? if not then it is just a simple networking issue

The object of the problem is random, but I think when there is a network problem, there needs to be a retry function internally, otherwise the object will not be able to synchronize

**Comment by harshavardhana** [comment]
> The object of the problem is random, but I think when there is a network problem, there needs to be a retry function internally, otherwise the object will not be able to synchronize

Retry is automatically attempted this is a case where it cannot be retried and `mc` gives up.

**Comment by dingsongjie** [comment]
Why did `mc` give up ，if it is a network problem, it should be recovered quickly, and according to the log, within a few seconds, mc has successfully uploaded multiple pictures, but this picture was not uploaded successfully, which can prove that there is no long-term network failure.
![image](https://user-images.githubusercontent.com/10933723/188354552-7bde5f20-d0f4-4f00-8c12-597be8d548a7.png)

**Comment by dingsongjie** [comment]
> > The object of the problem is random, but I think when there is a network problem, there needs to be a retry function internally, otherwise the object will not be able to synchronize
> 
> Retry is automatically attempted this is a case where it cannot be retried and `mc` gives up.

Why did mc give up ，if it is a network problem, it should be recovered quickly, and according to the log, within a few seconds, mc has successfully uploaded multiple pictures, but this picture was not uploaded successfully, which can prove that there is no long-term network failure.
image

**Comment by dingsongjie** [comment]
> > The object of the problem is random, but I think when there is a network problem, there needs to be a retry function internally, otherwise the object will not be able to synchronize
> 
> Retry is automatically attempted this is a case where it cannot be retried and `mc` gives up.

Why did mc give up ，if it is a network problem, it should be recovered quickly, and according to the log, within a few seconds, mc has successfully uploaded multiple pictures, but this picture was not uploaded successfully, which can prove that there is no long-term network failure.
![image](https://user-images.githubusercontent.com/10933723/188354733-7e31a6f4-d8fa-4128-884d-885160fe7722.png)

**Comment by harshavardhana** [comment]
> Why did `mc` give up ，if it is a network problem, it should be recovered quickly, and according to the log, within a few seconds, `mc` has successfully uploaded multiple pictures, but this picture was not uploaded successfully, which can prove that there is no long-term network failure.

`mc` gave up because this is an unrecoverable error - it cannot be retried since the connection was broken mid-flight during the socket read @dingsongjie 

you need to figure out who is closing an active connection on your end. Go doesn't designate this error as "retry" friendly since it is not an expected network error. 

You should perhaps figure this out on your end why here is a problem.

**Comment by binnie268** [comment]
Okay thanks I was able to list the files, but cannot read them: mc ls --zip --recursive minio/data-uploads/test.zip/test_bbs_[1].csv gives: **"zsh: no matches found: minio/data-uploads/test.zip/test_bbs_[1].csv"**
