### ISSUE TITLE
'mc mirror' is very slow

### ISSUE THREAD

**Issue by 1714574383** [minio/mc#4251]
## Steps to reproduce the behavior
I'm commanding the ' mc mirror' to synchronize the uploads bucket from A to B cluster. In first 12 hours the transfer rate could reach 600 Mbps, but suddenly it dropped to 1Mbps.
I had about 6TB of data and 3M files, and I had 5TB of data and 2.5M files synced when the transfer rate went down.
I had checked over the network including commanding the 'mc mirror' synchrnize the subdirectory of the uploads, the transfer rate was still very fast.
![1663146127799](https://user-images.githubusercontent.com/23066429/190111738-5c445c43-962e-4171-9aff-3088c9da1b02.jpg)
![1663146127819](https://user-images.githubusercontent.com/23066429/190111763-d2789771-b94b-4502-a9dd-fa8f92c41089.jpg)
![1663146127812](https://user-images.githubusercontent.com/23066429/190111788-0f18b998-f555-4181-9129-e01b191fcb2a.jpg)
![1663146127827](https://user-images.githubusercontent.com/23066429/190111806-a08180d1-08b0-40dd-be12-fc3cba08eb8b.jpg)

## mc --version
mc version RELEASE.2022-08-28T20-08-11Z
## System information
minio version RELEASE.2022-06-25T15-50-16Z

**Comment by tiansiyuan** [comment]
quay.io/minio/minio:RELEASE.2022-02-12T00-51-25Z

$ mc --version
mc version RELEASE.2023-11-20T16-30-59Z (commit-id=937b34616f012ad30e1cd6fd61e1da25ff931648)
Runtime: go1.21.4 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

$ mc admin info minio/
●  127.0.0.1:9000
   Uptime: 30 minutes 
   Version: 2022-02-12T00:51:25Z


8.0 MiB Used, 6 Buckets, 2 Objects

# to backup to a local dir

$ mc mirror --watch  minio/ backup

Takes over night.

**Comment by shokh-y** [comment]
@1714574383 hi, were u able to sort this out?
