### ISSUE TITLE
mc cp to copy from minio to GCS doesn't work without error message

### ISSUE THREAD

**Issue by ammubharatram** [minio/mc#4252]
Hi everyone!
I have an issue without an error message:
I am using Kubeflow locally with minio client . I am able to set alias to a google cloud bucket using this command where access key and secret key are my credentials for GCS:
`mc alias set myGCS https://storage.googleapis.com/ ACCESS_KEY SECRET_KEY`
I am amazed that I can set alias for GCS as well as AWS S3 which worked earlier. I see that the documentation says:
"The mc commandline tool is built for compatibility with the AWS S3 API and is tested MinIO and AWS S3 for expected functionality and behavior. MinIO provides no guarantees for other S3-compatible services, as their S3 API implementation is unknown and therefore unsupported. While mc commands may work as documented, any such usage is at your own risk."
I tried to copy my Machine learning model object from minio to Google storage bucket using this command:
`mc cp local/mlpipeline/artifacts/first-pipeline-hprqw/2022/08/29/first-pipeline-hprqw-1127242770/random-forest-classifier-Rf_best.tgz gs://nso_fcrr/rf_best.tgz`
It shows no error as seen in the screenshot attached. However, there is no file copied to my GCS bucket 'nso_fcrr'. I am surprise that there is no error message. Any idea on what the issue is here? Thanks in advance :)

## mc --version
mc version RELEASE.2022-05-09T04-08-26Z

## System information
Windows 11 PC
![image (2)](https://user-images.githubusercontent.com/27764519/190217641-6e008edc-ab8f-4f48-b1d6-643602ec5cb5.png)

**Comment by harshavardhana** [comment]
> `mc cp local/mlpipeline/artifacts/first-pipeline-hprqw/2022/08/29/first-pipeline-hprqw-1127242770/random-forest-classifier-Rf_best.tgz gs://nso_fcrr/rf_best.tgz`

where have we documented that you can us `gs://` ?

**Comment by ammubharatram** [comment]
okay I see. Two comments:
1. Why do you have documentation for mc alias for GCS if minio client doesn't 'intend' to support 'cp' command even? See here this command:
https://docs.min.io/docs/minio-client-quickstart-guide.html 
mc alias set gcs  https://storage.googleapis.com BKIKJAA5BMMU2RHO6IBB V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12
2. I see that in documentation that MinIO provides no guarantees for other S3-compatible services, as their S3 API implementation is unknown and therefore unsupported. However, since I see the copy action happening (as one can see in my screenshot), that is where I was hoping if mc cp could work with 'gs://'. 
If that is not at all expected, I request you to kindly give some insight on whether it worked unexpectedly or perhaps if there is another way to make mc cp command work with GCS. (as mentioned in the mc quickstart guide for usage with GCS). Thanks in advance!

**Comment by harshavardhana** [comment]
> okay I see. Two comments:
> 
> 1. Why is there have documentation for mc alias for GCS if minio client doesn't 'intend' to support 'cp' command even? I see here this command:
>    https://docs.min.io/docs/minio-client-quickstart-guide.html
>    mc alias set gcs  https://storage.googleapis.com BKIKJAA5BMMU2RHO6IBB V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12

if you configured this use `mc cp local/bucket/filename gcs/bucket/filename`

> 2. I see that in documentation that MinIO provides no guarantees for other S3-compatible services, as their S3 API implementation is unknown and therefore unsupported. However, since I see the copy action happening (as one can see in my screenshot), that is where I was hoping if mc cp could work with 'gs://'.

No, you didn't do this you somehow went ahead and assumed things on your own - we can't help you with your preconceived assumptions - it's not written anywhere to use `gs://` `mc` is not gsutil. 

>    If that is not at all expected, I request you to kindly give some insight on whether it worked unexpectedly or perhaps if there is another way to make mc cp command work with GCS. (as mentioned in the mc quickstart guide for usage with GCS). Thanks in advance!

GCS works in its S3 API in the limited sense it is nowhere a replacement for AWS S3 or MinIO so use it accordingly, `mc` makes it possible in the best way it can to support GCS target via their S3 implementation but it cannot be considered anywhere complete. 

https://gist.github.com/harshavardhana/5d4d7410afb02ec9837e2b4d82a932e7 is a non-exhaustive list of things GCS doesn't work with when it comes to S3 API. 

Here you go works like charm MinIO -> GCS bucket. 

```
~  mc cp play/bucket/object-name gcs/harsharepro/
...play.min.io/bucket/object-name: 11 B / 11 B ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22 B/s 0s
```

**Comment by ammubharatram** [comment]
Thank you for suggestions. Following worked for me, where 'myGCS' is the alias that has been set. 
`mc cp local/mlpipeline/artifacts/first-pipeline-hprqw/2022/08/29/first-pipeline-hprqw-1127242770/random-forest-classifier-Rf_best.tgz myGCS/nso_fcrr/rf_best.tgz`

Only works because of the alias used earlier:

`mc alias set myGCS https://storage.googleapis.com/ ACCESS_KEY SECRET_KEY`
