### ISSUE TITLE
mc mirror --watch deletes file on S3

### ISSUE THREAD

**Issue by itulga** [minio/mc#4258]
## Expected behavior

mirror command correctly uses --remove flag. But cannot use --watch flag together. Sync local and S3 files and deleted some files from local folder. Expected behavior:

mc mirror --watch /local/folder s3://bucket/ (not delete S3 file)
mc mirror --watch --remove /local/folder s3://bucket/ (must delete S3 file)

## Actual behavior

mc mirror --watch /local/folder s3://bucket/ (S3 file deleted automatically)
mc mirror --watch --remove /local/folder s3://bucket/ (S3 file deleted automatically)

Both command worked same. There was discussion 2 years ago and decision looks --remove flag should be used to delete target file, otherwise remote files should not deleted -> https://github.com/minio/mc/issues/3413

## mc --version
mc version RELEASE.2022-09-16T09-16-47Z (commit-id=ad4441ef2b4b1d0a6b90b5dd0d71d0423952e417)
Runtime: go1.18.6 linux/amd64

## System information
Debian 10.3

**Comment by yee379** [comment]
could i propose something like

```
mc rsync --watch [--delete]
```

to match the behavior that rsync performs (and is the most obvious implementation imo)
