### ISSUE TITLE
du should not limit itself to folders

### ISSUE THREAD

**Issue by comunidadio** [minio/mc#4265]
The current limitation seems very artificial as there is no "folders" on S3 API and even regular local files du command do support such use case (using * wildcard as suffix).

## Expected behavior
Calculate and display cumulative size of objects according to prefix

## Actual behavior
mc: <ERROR> Source `alias/bucket/dumps/20220926` is not a folder. Only folders are supported by 'du' command. 

## Steps to reproduce the behavior
mc du alias/bucket/dumps/20220926
or
mc du -r alias/bucket/dumps/20220926
or 
mc du "alias/bucket/dumps/20220926*"

## mc --version
mc version RELEASE.2022-09-16T09-16-47Z (commit-id=ad4441ef2b4b1d0a6b90b5dd0d71d0423952e417)
Runtime: go1.18.6 darwin/arm64

**Comment by harshavardhana** [comment]
`*` wildcard is interpreted by the shell before we get control, there is only a `prefix` that is possible '*' has really no meaning. 

There are folders in S3 API that are called 'common prefixes' that are hierarchical parents to your objects.  Looks like you are unaware of S3 API properly. 

The current implementation is as per requirement.

**Comment by comunidadio** [comment]
> * wildcard is interpreted by the shell before we get control,
Not if you use quotes as I did. Anyways the wildcard was just an example and is not the main point.

Consider the below mc command:
"mc ls alias/bucket/dumps/20220926"

This returns all objects starting with the prefix "alias/bucket/dumps/20220926".

It doesn't look consistent, or expected, that "du" would not proceed regularly with this prefix and return an artificial error based on "folders" or "common prefixes".

**Comment by harshavardhana** [comment]
It is written to satisfy S3 APIs usecase be it a prefix match being an opaque string or a folder is your choice. We cannot over-engineer this anymore to make it POSIXish. 

It is what it is under the bounds of the S3 API.
