### ISSUE TITLE
minio cli 0 bytes folders

### ISSUE THREAD

**Issue by migs35323** [minio/mc#4267]
## Expected behavior
when we use commands like `mc ls server` that it shows folder sizes accordingly 

## Actual behavior

when we use any command it lists folders as 0 bytes

## mc --version
- (paste output of `mc --version`)
mcli version RELEASE.2022-09-16T09-16-47Z (commit-id=ad4441ef2b4b1d0a6b90b5dd0d71d0423952e417)
Runtime: go1.18.6 linux/amd64

**Comment by vadmeste** [comment]
@migs35323 MinIO follows the S3 specification, which doesn't list size for folders.

**Comment by klauspost** [comment]
To extend a bit, S3 does not keep track of or return sizes of "folders" (actually prefixes). Calculating it is a very expensive operation and can take hours with many objects/versions.

You can use `mc du` for this.
