### ISSUE TITLE
Modify admin policy command

### ISSUE THREAD

**Issue by kannappanr** [minio/mc#4272]
Change the `add` sub-command to `create`

Output of `mc admin policy --help` will be as follows.
```
create     create a new IAM policy
list          list all IAM policies
info        show info on an IAM policy
remove  remove an IAM policy
```
Also, add examples to create a policy and assign it to a user/group in the help of `mc admin policy create`

Also, `set`, `unset` and `upate` sub-commands will be removed and moved under `mc admin user policy` and `mc admin group policy` commands

**Comment by dormanze** [comment]
May I fix this issue?

**Comment by taran-p** [comment]
@dormanze I will be fixing the issue

**Comment by sathieu** [comment]
While I understand cleaning up the CLI, why are you removing the old command *at the same time*?

**Comment by wobrycki** [comment]
We also have problems migrating to the newest syntax after breaking changes were inroduced.
The old syntax is not available anymore, and other ongoing issues related to the new syntax, have not been resolved yet:
https://github.com/aminueza/terraform-provider-minio/issues/116 This 'admin' API is not supported by server in 'mode-server-fs
With the old syntax working, we probably still would have a working `mc admin policy`, now we have to go through a time-consuming downgrading process.

Example:
old one `mc admin policy set data_lake_connection $MINIO_USER user=$MINIO_USER` was working
new one `mc admin policy attach data_lake_connection $MINIO_USER  --user=$MINIO_USER` does not work and throws This 'admin' API is not supported by server in 'mode-server-fs'.
FYI @taran-p

**Comment by harshavardhana** [comment]
> new one `mc admin policy attach data_lake_connection $MINIO_USER --user=$MINIO_USER` does not work and throws This 'admin' API is not supported by server in 'mode-server-fs'.

You are on legacy deployment @wobrycki you need to migrate away from FS mode. To use the newer `mc` you need to upgrade your server as well or stick to the older version that works and do not need to use the newer `mc` with the older server.
