### ISSUE TITLE
Add sub-commands under admin user policy

### ISSUE THREAD

**Issue by kannappanr** [minio/mc#4273]
Add sub-commands under `mc admin user policy`

`mc admin user policy [attach | detach | list]`
```
attach     attach an IAM policy to a user
detach   detach an IAM policy from a user
list  list all IAM policies attached to a user
```
Also, add examples to create a user and attach a policy to the user. This needs to be done as part of help under `mc admin user policy` and `mc admin user add`

**Comment by taran-p** [comment]
For the list command, should it act as admin user policy works now and give json, or should it just list the policy names?
