### ISSUE TITLE
mc --help changes the command prompt so arrow keys no longer scroll

### ISSUE THREAD

**Issue by LeeBear35** [minio/mc#4285]
## Expected behavior

- Display the message and return to the command prompt with normal keyboard processing

## Actual behavior

- Display the message but the up and down keys no longer scroll up and down in the commands instead they display key encoding

## Steps to reproduce the behavior

- mc --help
`C:\x>mc --help

C:\x>^[[A`
## mc --version
mc version RELEASE.2022-10-06T01-20-06Z (commit-id=1a832ed01811a035b7855b9578c9b66d83269fcd)
Runtime: go1.18.7 windows/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=AMD64 Family 25 Model 1 Stepping 1, AuthenticAMD
PROCESSOR_LEVEL=25
PROCESSOR_REVISION=0101

**Comment by klauspost** [comment]
Works fine in cmd and powershell. 

BUT I did end up in a similar state in powershell once, but it doesn't reproduce. 

If you can provide a reliable reproducer it would be easier to help, though it seems like a powershell issue.
