### ISSUE TITLE
Timestamp displayed twice under mc replicate diff

### ISSUE THREAD

**Issue by bh4t** [minio/mc#4286]
## Expected behavior
Timestamp should be displayed once
## Actual behavior
Timestamp is displayed twice.

## Steps to reproduce the behavior
1 set up 2 Minio instance
2 Try uploading an object on source whille remote target is off
3 Run mc replicate diff SOURCE --arn value

![image](https://user-images.githubusercontent.com/109562845/194399747-495fe0ac-6230-48bc-93e3-205bb57f9f79.png)

## mc --version
version RELEASE.2022-10-06T01-20-06Z

**Comment by poornas** [comment]
The first is the timestamp when object was created, the second is the timestamp of last attempt to replicate

**Comment by kannappanr** [comment]
should a header be added to explain each column?
