### ISSUE TITLE
mc update fails: unsupported protocol scheme

### ISSUE THREAD

**Issue by tholu** [minio/mc#4294]
## Expected behavior

`mc update` runs without problems.

## Actual behavior

```
~# mc update

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of mc released 1 week ago ┃
┃ Update: ./mc.RELEASE.2022-10-09T21-10-59Z                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
mc: <ERROR> Unable to update ‘mc’. Get "./mc.RELEASE.2022-10-09T21-10-59Z": unsupported protocol scheme ""
```

## Steps to reproduce the behavior

Run `mc update` with version RELEASE.2022-10-01T07-56-14Z.

## mc --version

mc version RELEASE.2022-10-01T07-56-14Z (commit-id=f73adff2383976d6b5644668bbd491b0551a1c96)
Runtime: go1.18.6 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information

Debian 10.13

**Comment by tholu** [comment]
Fixed this for myself by manually updating to the latest version:

```zsh
curl https://dl.min.io/client/mc/release/linux-amd64/mc \
 --create-dirs \
 -o /usr/local/bin/mc
```

which does not have an update available yet:

```
~# mc update
You are already running the most recent version of ‘mc’.
```

**Comment by harshavardhana** [comment]
This is already fixed,  and going forward it will work fine as before. 

```
commit a7dd2810aec9961f7ef1d8cf2d7766cddc09292c
Author: Harshavardhana <harsha@minio.io>
Date:   Mon Oct 3 15:00:41 2022 -0700

    fix: updateURL when customURL is not passed (#4279)
```
