### ISSUE TITLE
Batch replication fails to replicate object versions on the target

### ISSUE THREAD

**Issue by bh4t** [minio/mc#4299]
## Expected behavior
Multiple versions of the object should be replicated on the target.
Also, the delete marker seems to be not getting replicated on the target. Assuming its the same issue.
## Actual behavior
Only one version of the object is replicated on the target
## Steps to reproduce the behavior
1. Turn on versioning on the source bucket myminio/hellotest
2. Start batch replication from source myminio to target myminio2 - mc batch start myminio ./replication.yaml

![image](https://user-images.githubusercontent.com/109562845/195438277-5624e0f4-d15d-40ed-8ae2-fa77e4bf7f15.png)
![image](https://user-images.githubusercontent.com/109562845/195438397-0f39ec17-9aac-4a0a-887d-6db3295d1c77.png)

## mc --version
RELEASE.2022-10-09T21-10-59Z

**Comment by harshavardhana** [comment]
This is already fixed in latest releases of MinIO.
