### ISSUE TITLE
Latest minio cli release has broken zip commands

### ISSUE THREAD

**Issue by binnie268** [minio/mc#4307]
## Expected behavior
mc ls --zip --recursive test.zip/ should list all the files inside the zip

## Actual behavior
Returns nothing
## Steps to reproduce the behavior
Upload any zip with files inside
run mc ls --zip --recursive test.zip/
## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2022-10-09T21-10-59Z (commit-id=27322636ae33611cf193a0fe4b5de18f3b096549)
Runtime: go1.18.7 darwin/arm64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
## System information
M1 Mac 14''

**Comment by harshavardhana** [comment]
@binnie268 you are missing providing an alias. --zip commands with a server running not your local disk

**Comment by binnie268** [comment]
Okay thanks I was able to list the files, but cannot read them: mc ls --zip --recursive minio/data-uploads/test.zip/test_bbs_[1].csv gives: **"zsh: no matches found: minio/data-uploads/test.zip/test_bbs_[1].csv"**
