### ISSUE TITLE
Not able to read csvs inside zip

### ISSUE THREAD

**Issue by binnie268** [minio/mc#4309]
Expected behavior
mc cat--zip --recursive minio/data-uploads/test.zip/test_bbs_[1].csv shuld return contents of zip

Actual behavior
mc cat--zip --recursive minio/data-uploads/test.zip/test_bbs_[1].csv gives: **"zsh: no matches found: minio/data-uploads/test.zip/test_bbs_[1].csv"**

Steps to reproduce the behavior
Upload any zip with files inside
run mc cat--zip --recursive minio/data-uploads/test.zip/test_bbs_[1].csv

mc --version
(paste output of mc --version)
mc version RELEASE.2022-10-09T21-10-59Z (commit-id=27322636ae33611cf193a0fe4b5de18f3b096549)
Runtime: go1.18.7 darwin/arm64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 https://www.gnu.org/licenses/agpl-3.0.html

_Originally posted by @binnie268 in https://github.com/minio/mc/issues/4307#issuecomment-1282854618_

**Comment by harshavardhana** [comment]
> Actual behavior
> mc cat--zip --recursive minio/data-uploads/test.zip/test_bbs_[1].csv gives: **"zsh: no matches found: minio/data-uploads/test.zip/test_bbs_[1].csv"**

This is because your ZSH is parsing the `[1]` value you need to escape this for your shell.

**Comment by binnie268** [comment]
That worked after escaping, thanks. Also https://blog.min.io/small-file-archives/ still references:
mc cat --zip -–recursive play/test/test.zip/file.txt

It should be: mc cat --zip play/test/test.zip/file.txt

**Comment by klauspost** [comment]
Post updated.
