### ISSUE TITLE
Different versions of the program are differently copy the same file

### ISSUE THREAD

**Issue by Nikitin-Alexandr** [minio/mc#4312]
I have two version MinioClient:
```
	mc version RELEASE.2022-01-07T06-01-38Z
	and 
	mc version RELEASE.2022-10-09T21-10-59Z (commit-id=27322636ae33611cf193a0fe4b5de18f3b096549)
```

The first (2022-01-07) copies the file and does not give any errors, but the second (2022-10-09) when copying the same file to the same directory (in this directory there is no this file before copying) gives an error:
`This request does not support content`

The file size is 145 GB, but if, using the split, I will divide it into two parts, then both of them are accumulated without problems.

Here are the final part of the display of the copy mode launched with the --debug option:
```
mc: <DEBUG> HTTP/1.1 204 No Content
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Wed, 19 Oct 2022 03:44:24 GMT
Server: nginx/1.20.2
X-Host: hb-front9
X-Req-Id: KsFuEvrZ

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: BE
mc: <DEBUG>  >> Organization: GlobalSign nv-sa
mc: <DEBUG>  >> Expires: 2023-08-14 09:43:54 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Organization: GlobalSign
mc: <DEBUG>  >> Expires: 2028-11-21 00:00:00 +0000 UTC
mc: <DEBUG> Response Time:  71.172214ms

mc: <ERROR> Failed to copy `/var/lib/postgresql/backups/2022-10-14-weekly/kz.custom`. This request does not support content
 (3) cp-main.go:601 cmd.doCopySession(..) Tags: [/var/lib/postgresql/backups/2022-10-14-weekly/kz.custom]
 (2) common-methods.go:611 cmd.uploadSourceToTargetURL(..) Tags: [/var/lib/postgresql/backups/2022-10-14-weekly/kz.custom]
 (1) common-methods.go:341 cmd.putTargetStream(..) Tags: [cs_backup, https://.../2022-10-14-weekly/kz.custom]
 (0) client-s3.go:1112 cmd.(*S3Client).Put(..)
 Release-Tag:RELEASE.2022-10-09T21-10-59Z | Commit:27322636ae33 | Host:db8 | OS:linux | Arch:amd64 | Lang:go1.18.7 | Mem:48 MB/255 MB | Heap:48 MB/233 MB
```

I downloaded the last available version (mc version RELEASE.2022-10-12T18-12-50Z (commit-id=3fe6778ee739504b169743cf43fa7b3010e05b99)) and received the same mistake:
`mc: <ERROR> Failed to copy `/var/lib/postgresql/backups/2022-10-18-daily/kz.custom`. This request does not support content`

**Comment by harshavardhana** [comment]
@Nikitin-Alexandr can you provide full `--debug` output?

**Comment by klauspost** [comment]
@Nikitin-Alexandr What server are you sending this to? Could you send the request from the debug output as well?

**Comment by Nikitin-Alexandr** [comment]
The file turned out to be quite large, I took the lines from head and tail.
[debug.log](https://github.com/minio/mc/files/9820525/debug.log)

**Comment by klauspost** [comment]
Looks like a non-compatible S3 server on the other end.

We are adding a workaround for these. So until the next release go back a couple of versions of mc.

**Comment by Nikitin-Alexandr** [comment]
Thank you!
