### ISSUE TITLE
mc stat --rewind flag isnt working intended

### ISSUE THREAD

**Issue by bh4t** [minio/mc#4315]
## Expected behavior
mc stat --rewind flag should display objects created before the specified date.
## Actual behavior
mc stat --rewind flag sint displaying any results
## Steps to reproduce the behavior
Have multiple objects created prior to the below mentioned date.
mc stat --rewind 2022.10.15 --versions myminio/hellotest/

Another thing that I noticed, when you use the --rewind flag with ls it seems to be working.

![image](https://user-images.githubusercontent.com/109562845/196772794-d64b4293-0e06-49e3-bd4b-6fa457ea8fd6.png)

## mc --version
mc version RELEASE.2022-10-12T18-12-50Z

**Comment by dormanze** [comment]
I findthis problem in this pr #4147
