### ISSUE TITLE
Client ls command on S3-compatible storage (Oracle object store) does nto support region value

### ISSUE THREAD

**Issue by alekstr** [minio/mc#4329]
## Expected behavior
`
> mc -C /tmp/mc config host add dest https://frrjzkngligm.compat.objectstorage.me-jeddah-1.oraclecloud.com KEY  SECRET --api "s3v4"
Added `dest` successfully.
> mc -C /tmp/mc ls dest/some-bucket
List of output
`
## Actual behavior
`
> mc -C /tmp/mc config host add dest https://frrjzkngligm.compat.objectstorage.me-jeddah-1.oraclecloud.com KEY  SECRET --api "s3v4"
Added `dest` successfully.
> mc -C /tmp/mc ls dest/some-bucket
[List of output](mc: <ERROR> Unable to list folder. The secret key required to complete authentication could not be found. The region must be specified if this is not the home region for the tenancy.)

mc: <DEBUG> GET /some-bucket/?location= HTTP/1.1
Host: frrjzkngligm.compat.objectstorage.me-jeddah-1.oraclecloud.com
User-Agent: MinIO (darwin; amd64) minio-go/v7.0.41 mc/RELEASE.2022-10-22T03-39-29Z
Authorization: AWS4-HMAC-SHA256 Credential=SECRET_HERE/20221027/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20221027T115823Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
`
Issue seems to be related to wrong default region us-east-1 since Credentials should be formatted like:
Authorization: AWS4-HMAC-SHA256 Credential=SECRET_HERE/20221027/me-jeddah-1/s3/aws4_request

Where `mc mb` command support region option and works fine https://min.io/docs/minio/linux/reference/minio-mc/mc-mb.html#mc.mb.-region

## Steps to reproduce the behavior
* Use oracle cloud;
* create tokens and users for non us-east-1 region;
* Try to use bucket

## mc --version
- (paste output of `mc --version`)
`
mc version RELEASE.2022-10-22T03-39-29Z (commit-id=88796ea618092bb27368c00e2b387857945357fb)
Runtime: go1.19.2 darwin/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
`

**Comment by vadmeste** [comment]
@alekstr the purpose of this call `GET /some-bucket/?location=` is to get the bucket region when you do not know it already. 'us-east-1' is accepted as per S3 spec.

**Comment by robo-cap** [comment]
You will need to set an environment variable before you execute the command:
`export AWS_REGION=<oci_region>` or
`export MC_REGION=<oci_region>`
