### ISSUE TITLE
The XML you provided was not well-formed or did not validate against our published schema

### ISSUE THREAD

**Issue by qdupuy** [minio/mc#4334]
Hello,

When I want to push my backups to my bucket s3 scaleway, I get the following error : 

```
== rsync-to-s3.sh 2022-10-31T15:10:08Z Copy of local data to s3
`/tmp/x.backup.tar.gz` -> `s3/x/name/serveurs/mail/x.31_10_2022__14_52_03.backup.tar.gz`
mc: <ERROR> Failed to copy `/tmp/x.backup.tar.gz`. The XML you provided was not well-formed or did not validate against our published schema.
Total: 0 B, Transferred: 7.29 GiB, Speed: 23.39 MiB/s
```

## Steps to reproduce the behavior

create a s3 profile and push a large file to the bucket 

## mc --version
- (paste output of `mc --version`)

```
mc --version
mc version RELEASE.2022-10-29T10-09-23Z (commit-id=929062c86be50d7f6350ab2da929585720f4fe74)
Runtime: go1.19.2 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## System information

Ubuntu 20.04 LTS

**Comment by harshavardhana** [comment]
scaleway doesn't support trailing header CheckSums properly.. and instead returns an unexpected error.

**Comment by qdupuy** [comment]
But still?

/reopen

**Comment by klauspost** [comment]
@qdupuy No. This will be fixed with next update of the `minio-go` library, so it will be fixed.

Meanwhile you are welcome to ask scaleway why they are rejecting valid XML. They must upgrade if they want to be S3 compatible.
