### ISSUE TITLE
`mc ilm ls` doesn't support `NewerNoncurrentVersions` ilm rule

### ISSUE THREAD

**Issue by Timost** [minio/mc#4343]
Hi,
First of all thank you for minio 🙏❤.

I think `mc ilm ls` doesn't support `NoncurrentVersionExpiration.NewerNoncurrentVersions` ilm rule in its output.

I think there are several functions that need to be modified to add support, for example:
- https://github.com/minio/mc/blob/master/cmd/ilm/tabular_info.go#L249
- https://github.com/minio/mc/blob/master/cmd/ilm/tabular_info.go#L273

## Expected behavior
With a `NoncurrentVersionExpiration.NewerNoncurrentVersions` rule, `mc ilm ls` shoud output:
```
          ID          |    Type    |   Version    |      Tier        | Date/Days    |     Prefix     |  Enabled   |          Tags
----------------------|------------|--------------|------------------|--------------|----------------|------------|------------------------
 Keep only most r..   |  Expiry    | Non-Current  |                  |     (?)      |                |    ✔       |
----------------------|------------|--------------|------------------|--------------|----------------|------------|------------------------
```

## Actual behavior
`mc ilm ls myminio/bucket` outputs unknown type and version:
```
          ID          |    Type    |   Version    |      Tier        | Date/Days    |     Prefix     |  Enabled   |          Tags
----------------------|------------|--------------|------------------|--------------|----------------|------------|------------------------
 Keep only most r..   |  Unknown   |   Unknown    |                  |              |                |    ✔       |
----------------------|------------|--------------|------------------|--------------|----------------|------------|------------------------
```

## Steps to reproduce the behavior
1. Add an ilm rule using `mc ilm import`
```json
{
    "Rules": [
        {
            "ID": "Keep only most recent 4 noncurrent versions",
            "Status": "Enabled",
            "NoncurrentVersionExpiration": {
                "NewerNoncurrentVersions": 4
            }
        }
    ]
}
```
2. run `mc ilm ls myminio/bucket`
## mc --version
```
mc version RELEASE.2022-10-01T07-56-14Z (commit-id=f73adff2383976d6b5644668bbd491b0551a1c96)
Runtime: go1.18.6 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## System information
- mc installed from https://dl.min.io/client/mc/release/linux-amd64/archive/

**Comment by krisis** [comment]
@Timost thanks for bringing this to our attention. I have a [PR](https://github.com/minio/mc/pull/4262) that addresses this. I expect this to be merged soon. Meanwhile, it would be great if you could test this PR and provide feedback.

**Comment by Timost** [comment]
Hi @krisis,
Thank you for the quick reply and the changes 👍, I'll try to test it on my side ASAP.

**Comment by kannappanr** [comment]
The above mentioned PR has been merged and is part of mc release 2022-11-17T21-20-39Z
