### ISSUE TITLE
mc admin replicate edit allows endpoints that are not part of the same deployment

### ISSUE THREAD

**Issue by rluetzner** [minio/mc#4349]
## Expected behavior

Given the following setup with two separate MinIO clusters:

```text
$ mc admin replicate info alias1
SiteReplication enabled for:

Deployment ID                        | Site Name       | Endpoint
1ec18eca-61d1-4830-8694-f6d9d85cb9e5 | alias1          | http://localhost:9000
c0c78716-73df-48c4-aad8-0c1706f7afa7 | alias2          | http://localhost:9001
``` 

When I run

```bash
mc admin replicate edit alias1 --deployment-id 1ec18eca-61d1-4830-8694-f6d9d85cb9e5 --endpoint http://localhost:9001
```

mc should fail because the target at http://localhost:9001 is not part of the deployment with ID 1ec18eca-61d1-4830-8694-f6d9d85cb9e5.

## Actual behavior

Executing the command lets me replace a replication target with any MinIO cluster that has the same root user and password.

```bash
$ mc admin replicate info alias1
SiteReplication enabled for:

Deployment ID                        | Site Name       | Endpoint
1ec18eca-61d1-4830-8694-f6d9d85cb9e5 | alias1          | http://localhost:9001
c0c78716-73df-48c4-aad8-0c1706f7afa7 | alias2          | http://localhost:9001
```

## Steps to reproduce the behavior

Run `mc admin replicate edit <alias> --deployment-id <id> --endpoint <new-endpoint>` with
* <id> of an existing deployment
* <new-endpoint> is a MinIO target that is part of another deployment, but uses the same root user and password.

## mc --version
- `mc version RELEASE.2022-10-01T07-56-14Z (commit-id=f73adff2383976d6b5644668bbd491b0551a1c96)`

## System information

Irrelevant, but I can provide it if necessary.

**Comment by rluetzner** [comment]
This is related to https://github.com/minio/minio/issues/15998

**Comment by poornas** [comment]
This is already fixed by https://github.com/minio/minio/pull/16000. mc does not need any changes
