### ISSUE TITLE
mc mirror can't read config-dir in supervisor

### ISSUE THREAD

**Issue by luolingchun** [minio/mc#4354]
## Expected behavior

Run successfully

## Actual behavior

mc: <ERROR> Unable to stat source `minio129`. Requested file `/minio129` not found.

## Steps to reproduce the behavior

```bash
root@440:/data/bakup$ mc config host ls
gcs     
  URL       : https://storage.googleapis.com
  AccessKey : YOUR-ACCESS-KEY-HERE
  SecretKey : YOUR-SECRET-KEY-HERE
  API       : S3v2
  Path      : dns

local   
  URL       : http://localhost:9000
  AccessKey : 
  SecretKey : 
  API       : 
  Path      : auto

minio129
  URL       : http://xxx.xx.xx.xxx:9000
  AccessKey : minio
  SecretKey : minio123
  API       : s3v4
  Path      : auto

play    
  URL       : https://play.min.io
  AccessKey : Q3AM3UQ867SPQQA43P2F
  SecretKey : zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  API       : S3v4
  Path      : auto

s3      
  URL       : https://s3.amazonaws.com
  AccessKey : YOUR-ACCESS-KEY-HERE
  SecretKey : YOUR-SECRET-KEY-HERE
  API       : S3v4
  Path      : dns
```

supervisor config:
```conf
[program:minio]
command = mc mirror --remove --overwrite --watch --config-dir /home/casia/.mc minio129 /data/bakup/minio/
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile = /data/bakup/minio-bak.log
stopasgroup = true
killasgroup = true
```

Exception infomation:

```
mc: <ERROR> Unable to stat source `minio129`. Requested file `/minio129` not found.
```

## mc --version
mc version RELEASE.2022-10-29T10-09-23Z (commit-id=929062c86be50d7f6350ab2da929585720f4fe74)
Runtime: go1.19.2 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
ubuntu 20.04

**Comment by vadmeste** [comment]
@luolingchun does 'cat /home/casia/.mc/config.json | grep minio129` show anything ?

**Comment by luolingchun** [comment]
Yes! I have config.json. As same as `mc config host ls` output.

It's runnig successful Without supervisor.

**Comment by vadmeste** [comment]
@luolingchun most like your supervisor script does not have access to /home/casia/.mc/config.json with the alias that you need. You can double check by running this:
```
command = cat /home/casia/.mc/config.json
```

and check the std output here, /data/bakup/minio-bak.log

**Comment by luolingchun** [comment]
@vadmeste I tried `command = cat /home/casia/.mc/config.json` in supervisor and it's worked.


/etc/supervisor/conf.d/minio.conf:

```conf
[program:minio]
command = mc mirror --remove --overwrite --config-dir /home/casia/.mc minio129 /data/bakup/minio/
#command =  cat /home/casia/.mc/config.json
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile = /data/bakup/minio-bak.log
stopasgroup = true
killasgroup = true
```
/data/bakup/minio-bak.log:

![image](https://user-images.githubusercontent.com/22740403/200717287-20e6ebd0-fbb0-4983-b1d7-331315c0afd5.png)

**Comment by harshavardhana** [comment]
> command = mc mirror --remove --overwrite --config-dir /home/casia/.mc minio129 /data/bakup/minio/

The issue is this  - you need to move the `--config-dir` option

```
command = mc  --config-dir /home/casia/.mc mirror --remove --overwrite minio129 /data/bakup/minio
```

**Comment by luolingchun** [comment]
@harshavardhana Thank you so much, it's worked.

**Comment by harshavardhana** [comment]
@vadmeste we need to see why position matters for global flags
