### ISSUE TITLE
mc policy command should not produce a zero return code

### ISSUE THREAD

**Issue by ykuksenko** [minio/mc#4355]
## Expected behavior
running `mcli policy` should return a non zero return code.
Since the command was removed it should behave like an invalid command. 

## Actual behavior
return code is zero while a message is printed that should probably be at error level instead of just info.
```
$ mcli policy
mcli: Please use 'mc anonymous'
$ echo $?
0

```
## Steps to reproduce the behavior
run `mcli policy`
followed by `echo $?`
## mc --version
- (paste output of `mc --version`)
```
mcli version RELEASE.2022-10-22T03-39-29Z (commit-id=88796ea618092bb27368c00e2b387857945357fb)
Runtime: go1.19.2 linux/amd64
Copyright (c) 2015-0000 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```
## related code change
[4276](https://github.com/minio/mc/pull/4276)
## System information
archlinux.

**Comment by harshavardhana** [comment]
That's because the command itself is not wrong it simply tells you what to do further.  The command is `mc anonymous` that you need to use.
