### ISSUE TITLE
"mc diff" print different : "mc diff A B" and "mc diff B A"

### ISSUE THREAD

**Issue by hepengju** [minio/mc#4356]
## Expected behavior
"mc diff A B" and "mc diff B A" result should be same except "< >"

## Actual behavior
print all files in local folder with "!"
![image](https://user-images.githubusercontent.com/26279882/200783286-688c5750-cdb9-40ce-b6fd-50adbfebeb1a.png)
![image](https://user-images.githubusercontent.com/26279882/200784054-c39b1350-1f80-43a7-9df7-fbe7efa4afc7.png)

## Steps to reproduce the behavior
mc mirror --overwrite folderA bucketB
mc diff folderA  bucketB
mc diff bucketB folderA 

## mc --version
mc version RELEASE.2022-09-16T09-16-47Z (commit-id=ad4441ef2b4b1d0a6b90b5dd0d71d0423952e417)
Runtime: go1.18.6 windows/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
win11 and centos7

**Comment by harshavardhana** [comment]
The reason for this is that when you reverse the time stamp on the object MinIO (lastModified) is different than LastModified on the Drive. 

This is entirely expected behavior since object storage is not preserving your local disk filesystem modified time.
