### ISSUE TITLE
`mc admin tier add s3` for fully private bucket

### ISSUE THREAD

**Issue by brsolomon-deloitte** [minio/mc#4365]
[Unable to use Slack due to corporate restrictions.]

We are attempting to set up [Transition of Objects from MinIO to S3](https://min.io/docs/minio/linux/administration/object-management/transition-objects-to-s3.html).

Our S3 bucket has permission setting _Block all public access_=_on_.

What `--endpoint` can we pass to `mc admin tier add s3` to point MinIO to the private bucket?

Secondly, is `--use-aws-role` expecting that an IAM role be attached to the `mc` client machine or to the node from which `minio` is being run/served?

**Comment by krisis** [comment]
I am not familiar with how public access on AWS S3 works. Did you try `mc admin tier add s3 ...` with the standard endpoint? 
If so, could you paste the errors from `mc` here?

> Secondly, is --use-aws-role expecting that an IAM role be attached to the mc client machine or to the node from which minio is being run/served?

IAM role should be attached to those nodes where MinIO server is running.

**Comment by brsolomon-deloitte** [comment]
It seems like we have this half-working but with some issues.

We did the following:

```bash
cat << EOF > LifecycleManagementAdmin.json
{
   "Version": "2012-10-17",
   "Statement": [
      {
            "Action": [
               "admin:SetTier",
               "admin:ListTier"
            ],
            "Effect": "Allow",
            "Sid": "EnableRemoteTierManagement"
      },
      {
            "Action": [
               "s3:PutLifecycleConfiguration",
               "s3:GetLifecycleConfiguration"
            ],
            "Resource": [
                        "arn:aws:s3:::*"
            ],
            "Effect": "Allow",
            "Sid": "EnableLifecycleManagementRules"
      }
   ]
}

mc admin policy add minio LifecycleAdminPolicy LifecycleManagementAdmin.json
mc admin user add minio alphaLifecycleAdmin [REDACTED]
mc admin policy set minio LifecycleAdminPolicy user=alphaLifecycleAdmin
mc admin tier add s3 minio COLD_TIER \
    --endpoint https://s3.amazonaws.com \
    --bucket redacted_alias-pcap \
    --use-aws-role \
    --region redacted_region \
    --storage-class STANDARD
mc ilm add minio/redacted_alias-pcap \
    --tier COLD_TIER \
    --transition-days 1
```

After doing this we notice that objects are successfully transitioned to S3; however, we have two issues:

1. They are not removed from MinIO. They still show up in the MinIO console for a period beyond 1 day ago.
2. The MinIO logs are littered with the error below despite trying the recommended `mc admin config history <redacted>/ --clear`

```
API: SYSTEM()
Time: 12:24:22 UTC 11/16/2022
DeploymentID: 41736590-redacted
Error: unknown type of IAM file listed: config/tier-config.bin (*errors.errorString)
       5: cmd/iam-object-store.go:452:cmd.(*IAMObjectStore).listAllIAMConfigItems()
       4: cmd/iam-object-store.go:460:cmd.(*IAMObjectStore).loadAllFromObjStore()
       3: cmd/iam-store.go:436:cmd.(*IAMStoreSys).LoadIAMCache()
       2: cmd/iam.go:196:cmd.(*IAMSys).Load()
       1: cmd/iam.go:406:cmd.(*IAMSys).watch()
```

**Comment by krisis** [comment]
@brsolomon-deloitte Objects which have transitioned remain in the namespace. i.e you can access them like regular objects. What is different is that their data is moved to the remote tier configured. So, it is expected that you can see transitioned objects listed on MinIO console.
As for the errors you see in MinIO logs, could you share the output of `ls -la .minio.sys/config/` and `ls -la .minio.sys/config/iam` from inside one of the drive directories given to MinIO? These error logs shouldn't affect normal operations in your setup. But I would like to confirm that after looking at the outputs requested.

**Comment by brsolomon-deloitte** [comment]
> Objects which have transitioned remain in the namespace. i.e you can access them like regular objects. What is different is that their data is moved to the remote tier configured. So, it is expected that you can see transitioned objects listed on MinIO console.

Understood, thanks for clarifying.

> As for the errors you see in MinIO logs, could you share the output of ls -la .minio.sys/config/ and ls -la .minio.sys/config/iam from inside one of the drive directories given to MinIO?

Yes. I realize these may not affect other functionality, but they are frequent enough that they inhibit our ability to use the MinIO logs for other purposes.

```
bash-4.4$ ls -la /data/.minio.sys/config
total 20
drwxrwsr-x 5 minio minio 4096 Nov 14 18:35 .
drwxrwsr-x 9 minio minio 4096 Sep 30 17:14 ..
drwxrwsr-x 2 minio minio 4096 Mar 28  2022 config.json
drwxrwsr-x 7 minio minio 4096 Nov 16 13:34 iam
drwxr-sr-x 2 minio minio 4096 Nov 14 18:35 tier-config.bin
bash-4.4$ ls -la /data/.minio.sys/config/iam
total 28
drwxrwsr-x 7 minio minio 4096 Nov 16 13:34 .
drwxrwsr-x 5 minio minio 4096 Nov 14 18:35 ..
drwxrwsr-x 2 minio minio 4096 Mar 28  2022 format.json
drwxr-sr-x 3 minio minio 4096 Nov 14 18:30 policies
drwxr-sr-x 3 minio minio 4096 Nov 14 18:33 policydb
drwxrwsr-x 4 minio minio 4096 Mar 29  2022 service-accounts
drwxr-sr-x 3 minio minio 4096 Nov 14 18:31 users
```

**Comment by harshavardhana** [comment]
@brsolomon-deloitte you need to update your MinIO version you are using unsupported builds from a third party that we won't be able to help you with.

Please use our official releases https://github.com/minio/minio/issues/16078

**Comment by brsolomon-deloitte** [comment]
> Please refer my advice https://github.com/minio/minio/issues/16078

I've seen your advice and disagree with using it as an excuse to trigger-finger close issues without further investigation. We use a [security-hardened image](https://repo1.dso.mil/dsop/opensource/minio/minio/-/blob/development/Dockerfile) which otherwise makes very few changes to `minio/minio` as base image.

**Comment by harshavardhana** [comment]
> I've seen your advice and disagree with using it as an excuse to trigger-finger close issues without further investigation. We use a [security-hardened image](https://repo1.dso.mil/dsop/opensource/minio/minio/-/blob/development/Dockerfile) which otherwise makes very few changes to `minio/minio` as base image.

First of all, you are not heeding our advice and on top of that, you making us look like we are not helping. That is disingenuous on your part - you are using AGPLv3 source without a subscription you are in violation of the license.   

I would suggest you contact your legal on the implications here.

The log message you are seeing is already fixed you haven't upgraded, so I do not need to further investigate anything here.

We are the authors of MinIO we know what is hardened and what is not.  Using some random builds and calling it hardened doesn't make your case any strong here.
