### ISSUE TITLE
mc quiet mode (not so quiet) #3699 locked tyrannically without proper discussion

### ISSUE THREAD

**Issue by shoce** [minio/mc#4380]
@weisdd @abperiasamy

## Expected behavior
Expected behavior is to keep sane discussion and not just close issues with excused like "i did my best at the time and not going to reconsider this now"

## Actual behavior
The issue #3699 was locked as off-topic tho the issue is a real *technical* issue as the language used is misleading. The last message from @abperiasamy says

 "The idea behind the quiet flag was to turn off chatty animations and color control chars for primitive terminals. I couldn't find a better/familiar flag name than quiet. To completely turn off the output, there is always /dev/null redirection."

which is not an expected behavior when there are people who are reporting an issue. Closing it asking for more information would be ok. But LOCKING the issue is just disrespectful.

In my opinion #3699 is not an off-topic and is a real technical issue because the function is labeled wrongly probably because of lack of @abperiasamy's language experience. In my opinion the flag should be renamed to `--no-color` and the real `--quiet` flag provided that would really make the output minimal which cannot be achieved by redirecting the output to /dev/null.

Please reopen the issue #3699 for further discussion.

**Comment by klauspost** [comment]
@shoce There is nothing to discuss. The matter has been decided. This is open source, you are free to fork your own implementation if you don't like the decision. We are not going to entertain more bikeshedding on this topic.

If your problem is as big as you describe, you can redirect stdout to dev/null.
