### ISSUE TITLE
mcli: <ERROR> Unable to export bucket metadata. Failed to parse server response (unexpected end of JSON input):.

### ISSUE THREAD

**Issue by 4GOT10v2** [minio/mc#4409]
## Expected behavior
Command (mc admin cluster bucket export ALIAS) from https://min.io/docs/minio/macos/operations/install-deploy-manage/migrate-fs-gateway.html guide creates a cluster-metadata.zip file with metadata for each bucket.

## Actual behavior
Got an error: mcli: <ERROR> Unable to export bucket metadata. Failed to parse server response (unexpected end of JSON input):.

## Steps to reproduce the behavior
I had minio deployment with minio server version: 2020-04-15T19:42:18Z and with 500gb data in 5 buckets. Then i changed minio server file with another one version: 2021-09-24T00:24:24Z. Afterwards i changed minio server file again, now with version RELEASE.2022-07-24T17-09-31Z (go1.18.4 linux/amd64). All that time i was trying to exec command: mcli admin cluster bucket export minio1 and got the same error with every version. 

## mc --version
- (paste output of `mc --version`)
mcli version RELEASE.2022-11-17T21-20-39Z (commit-id=2770f13a73c5e98ae1a0665c76cf099f5f578a13)
Runtime: go1.19.3 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
OS: Debian stretch

**Comment by philaris** [comment]
Hi all, and thanks for the nice software @harshavardhana.

I have the same issue with minio server version RELEASE.2022-07-30T05-21-40Z (go1.18.4 linux/amd64) running in a docker container (the docker image id is d581b37c49f5) in an Ubuntu 22.10 server. The URL of the server is http (not https). I tried with clients in Ubuntu and macOS.

```
$ mcli --version
mcli version RELEASE.2022-06-17T02-52-50Z (commit-id=0e44ad30db7ee58386117f9bed143418c79d2980)
Runtime: go1.18.3 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
Licence AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

$ mcli admin cluster bucket export mocdevhost
mcli: <ERROR> Unable to export bucket metadata. Failed to parse server response (unexpected end of JSON input):.
```

```
~ mc --version
mc version RELEASE.2022-12-13T00-23-28Z (commit-id=4b4cab0441f000db100c5b5d9329221181bf61f2)
Runtime: go1.19.4 darwin/amd64
Copyright (c) 2015-0000 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

~ mc admin cluster bucket export mocdevhost
mc: <ERROR> Unable to export bucket metadata. Failed to parse server response (unexpected end of JSON input):.
```

**Comment by philaris** [comment]
Hi @4GOT10v2 , I see that we both had server versions from the end of July 2022. I updated the server to the last version that supports standalone/file system mode (RELEASE.2022-10-24T18-35-07Z) and the bucket metadata export seems to work!
```
$ docker image pull minio/minio:RELEASE.2022-10-24T18-35-07Z
[...]
$ mcli admin cluster bucket export mocdevhost
mcli: Bucket metadata successfully downloaded as allbuckets-metadata.zip
```

**Comment by poornas** [comment]
@4GOT10v2 , are you running minio in filesystem mode or erasure/distributed setup here?

**Comment by 4GOT10v2** [comment]
@poornas, Filesystem mode

**Comment by philaris** [comment]
The latest release for which the issue appears is RELEASE.2022-08-02T23-59-16Z. From RELEASE.2022-08-05T23-27-09Z and on, bucket metadata is exported correctly.

**Comment by 4GOT10v2** [comment]
@philaris, yes, it's working now, thanks a lot.
