### ISSUE TITLE
mc share list upload/download doesn’t show shared objects from web console

### ISSUE THREAD

**Issue by alexv305** [minio/mc#4414]
## Expected behavior
Show objects shared from web console / gui
## Actual behavior
When you enter command mc share list download, it only shows objects shared by using cli command mc share download alias/bucket/object 
## Steps to reproduce the behavior
Spin up new instance in docker using latest version, create a bucket, upload a file and share using the gui
Then add an Alias via Minio client cli and use command mc share list download 
## mc --version
- (paste output of `mc --version`)
latest version as of 12/16 downloaded binary from main website 
## System information
Running Minio server latest on docker CE latest on Debian 11

**Comment by harshavardhana** [comment]
They are not meant to, mc only shows mc generated links.
