### ISSUE TITLE
Support timestamp for newer-than/older-than

### ISSUE THREAD

**Issue by Tobias-08** [minio/mc#4421]
## Expected behavior

- `--newer-than` and `--older-than` support both duration and timestamp (like `--rewind` does)

## Actual behavior

- `--newer-than` and `--older-than` support only duration (as documented)
- duration-only makes (scripted) execution difficult as behavior depends on the execution time

## Steps to reproduce the behavior

- run any command that supports `--newer-than` or `--older-than`, e. g. `mc rm`

## mc --version
RELEASE.2022-12-13T00-23-28Z

## System information
Windows

**Comment by harshavardhana** [comment]
They are meant to be duration on purpose, dates are flimsy to use and flaky.
