### ISSUE TITLE
How to use MC command to create and delete directories in bucket

### ISSUE THREAD

**Issue by 592774447** [minio/mc#4432]
How to use MC command to create and delete directories in bucket
I tried to create another bucket under the bucket by creating a bucket, but the created directory seems to have problems
Here are the commands I used:
    mc mb alias/bucket/mydir
    mc mb /data/minio/bucket/mydir
    mc rb alias/bucket/mydir
    mc rb /data/minio/bucket/mydir

**Comment by klauspost** [comment]
There is no concept of "directories" in S3.

You simply upload object with the path+name you want, and prefixes (that look look directories) will be created.
