### ISSUE TITLE
Failure when trying to set a list of policies

### ISSUE THREAD

**Issue by sheromon** [minio/mc#4440]
## Expected behavior
Can assign multiple policies to a user using a comma-separated list of policy names as documented here: https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-policy.html#apply-a-policy-to-a-user-or-group

## Actual behavior
Command fails with the message ```mc: <ERROR> Unable to set the policy. The canned policy does not exist. (Specified canned policy does not exist).```

## Steps to reproduce the behavior
```bash
# create two policies
mc admin policy add myminio anteater-rw anteater-rw.json
mc admin policy add myminio badger-rw badger-rw.json
# create a user
mc admin user add myminio user1 abcdefgh
# setting just one policy by itself works fine
mc admin policy set myminio anteater-rw user=user1
# setting the other policy by itself works fine
mc admin policy set myminio badger-rw user=user1
# setting two policies results in the error message
mc admin policy set myminio anteater-rw,badger-rw user=user1
```

## mc --version
mc version RELEASE.2022-12-24T15-21-38Z (commit-id=176072dee43de613569aaa56061eba9d6d550290)
Runtime: go1.19.4 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
Running in Docker using an image based on Ubuntu 18.04

**Comment by vadmeste** [comment]
@sheromon I am not able to reproduce with that mc version. Does it work if you replace 'myminio' with 'play' ?

**Comment by harshavardhana** [comment]
> Command fails with the message `mc: <ERROR> Unable to set the policy. The canned policy does not exist. (Specified canned policy does not exist).`

You need to upgrade your server as well @sheromon

**Comment by sheromon** [comment]
@harshavardhana Ohhhhhhh, that makes so much sense. Thanks to you and @vadmeste for taking a look.

**Comment by sheromon** [comment]
I updated the version of the MinIO Docker image I'm using to `RELEASE.2023-01-06T18-11-18Z`, and now it works great.
