### ISSUE TITLE
mc sql : mc: <ERROR> Unable to run sql Invalid data source type. Only CSV, JSON, and Parquet are supported.

### ISSUE THREAD

**Issue by EvanCarroll** [minio/mc#4449]
## Expected behavior
According to the docs, this should work

```
❯ mc sql --recursive --query "select * from S3Object" minio
```

It's a copy from the `mc sql --help`

## Actual behavior

What I actually get is an error,

```
❯ mc sql --recursive --query "select * from S3Object" minio
mc: <ERROR> Unable to run sql Invalid data source type. Only CSV, JSON, and Parquet are supported.
mc: <ERROR> Unable to run sql Invalid data source type. Only CSV, JSON, and Parquet are supported.
mc: <ERROR> Unable to run sql Invalid data source type. Only CSV, JSON, and Parquet are supported.
mc: <ERROR> Unable to run sql Invalid data source type. Only CSV, JSON, and Parquet are supported.
mc: <ERROR> Unable to run sql Invalid data source type. Only CSV, JSON, and Parquet are supported.
mc: <ERROR> Unable to run sql Invalid data source type. Only CSV, JSON, and Parquet are supported.
mc: <ERROR> Unable to run sql Invalid data source type. Only CSV, JSON, and Parquet are supported.
```

## Steps to

**Comment by harshavardhana** [comment]
@EvanCarroll you need to provide a file name, otherwise this command would list all files and run queries on each file.

You have many files that are neither csv,JSON and parquet.

Blindly running SQL queries on random files won't yield any results

**Comment by EvanCarroll** [comment]
It would be nice to have an MVE of how `mc sql` is supposed to work. It's not at all clear from the example. I have this command which looks for all `job.log` flies and then greps to see if the content contains a `Client.Timeout`. Would something like this be a candidate for `mc sql`? Does mc sql get executed on the client or the server?

```
# In the example below, I'm looking for failures that contain Client.Timeout
mc find minio/artifacts \
  --name 'job.log'      \
  --exec 'sh -c "mc cat {} | grep Client\.Timeout | xargs -r echo {time} {}; exit 0"' \
  | tee /tmp/client_timeout.log
```

**Comment by harshavardhana** [comment]
> It would be nice to have an MVE of how `mc sql` is supposed to work. It's not at all clear from the example. I have this command which looks for all `job.log` flies and then greps to see if the content contains a `Client.Timeout`. Would something like this be a candidate for `mc sql`? Does mc sql get executed on the client or the server?
> 
> ```
> # In the example below, I'm looking for failures that contain Client.Timeout
> mc find minio/artifacts \
>   --name 'job.log'      \
>   --exec 'sh -c "mc cat {} | grep Client\.Timeout | xargs -r echo {time} {}; exit 0"' \
>   | tee /tmp/client_timeout.log
> ```

mc sql provides enough examples and explanation on what it is 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-glacier-select-sql-reference-select.html

You are asking for some generic grep, that is not what it is meant for.

**Comment by harshavardhana** [comment]
There is also wonderfully written docs https://min.io/docs/minio/linux/reference/minio-mc/mc-sql.html

It is unfortunate that you are not reading them.

**Comment by EvanCarroll** [comment]
Literally, this issue is an attempt to run [this example from the docs](https://min.io/docs/minio/linux/reference/minio-mc/mc-sql.html#select-all-columns-in-all-objects-in-a-bucket), which I said explicitly in the issue. To which you responded.

> you need to provide a file name, otherwise this command would list all files and run queries on each file. You have many files that are neither csv,JSON and parquet.

Guess what's not in the docs.... any of that... The command I ran is right under,

> The following command queries all objects in the mydata bucket on the myminio MinIO deployment:

Notice, "the mydata bucket" lacking any qualification for _"csv, JSON, or parquet"_. It's also not clear that,

* This SQL abstraction is only to search _within_ a bucket and not merely for a specific bucket.
* an "input format" is the same as "the bucket" contents.
* in `--recursive`, anything NOT in a supported "input format" will generate an error.
* What exactly the `WHERE` clause can do, as in....
    * Can I write something like `WHERE file_name LIKE '%foo.csv'` when running a `--recursive` query.

**Comment by harshavardhana** [comment]
> Literally, this issue is an attempt to run [this example from the docs](https://min.io/docs/minio/linux/reference/minio-mc/mc-sql.html#select-all-columns-in-all-objects-in-a-bucket), which I said explicitly in the issue. To which you responded.
> 
> > you need to provide a file name, otherwise this command would list all files and run queries on each file. You have many files that are neither csv,JSON and parquet.
> 
> Guess what's not in the docs.... any of that... The command I ran is right under,
> 
> > The following command queries all objects in the mydata bucket on the myminio MinIO deployment:
> 
> Notice, "the mydata bucket" lacking any qualification for _"csv, JSON, or parquet"_. It's also not clear that,
> 
> * This SQL abstraction is only to search _within_ a bucket and not merely for a specific bucket.
> * an "input format" is the same as "the bucket" contents.
> * in `--recursive`, anything NOT in a supported "input format" will generate an error.
> * What exactly the `WHERE` clause can do, as in....
>   
>   * Can I write something like `WHERE bucket_name LIKE '%foo.csv'` when running a `--recursive` query.

I don't think this going anywhere constructive. Closing the conversation.
