### ISSUE TITLE
`mc mirror` from local drive to bucket creates folders instead of .jpg files

### ISSUE THREAD

**Issue by Limezy** [minio/mc#4461]
## Expected behavior
I would expect `mc mirror` to create `.jpg` objects from the original .jpg files stored on local drive

## Actual behavior
Instead of creating `.jpg` objects, `mc mirror` is creating .jpg folders, with a `xl.meta` file inside
<img width="694" alt="image" src="https://user-images.githubusercontent.com/24638389/216069523-c2fce8fc-b23a-4ee4-b5ca-169f15303cbf.png">

## Steps to reproduce the behavior
`mc mirror /yourPath/YourLocalDriveFile ALIAS/YourBucket`
## mc --version
`mc version RELEASE.2023-01-28T20-29-38Z (commit-id=2e95a70c98fb9c2629cd89817b8759bfa109a4d0)`

## System information
Debian 11

**Comment by klauspost** [comment]
This is how MinIO stores objects.

**Comment by Limezy** [comment]
Sorry for disturbing... 
I got confused because when I use the MinIO console, I can upload a .jpg file, and in the browser it will be shown as a "real" file, and I can even preview it. Any idea of why `mc mirror` acts differently ? Thanks for your help and time.

**Comment by klauspost** [comment]
`mc mirror` does not behave differently. These are the files you are uploading - the backend data instead of the original files.
