### ISSUE TITLE
Skip corrupted files during mc mirror operation

### ISSUE THREAD

**Issue by AlexZIX** [minio/mc#4468]
There was an issue few years ago (https://github.com/minio/mc/issues/1693) where topic starter asked to add option --skip-mising. The minio team answers that minio should process all abnormal situations. Today I've started migrating of data from my old minio instance to the new one. And once in 5 minutes I've got following error which stops mirroring process:

mc: <ERROR> Failed to copy `http://minio-1.bazis.net:9001/10/48/1048076.b3db`. We encountered an internal error, please try again.: cause(s2: corrupt input)

I know that few files becomes broken because of another minio issue year ago and now I want to just bypass such files but can't do that. I think it's a good idea to add option like --skip-errors which allows to copy everything what possible and log what wasn't copied and the reason of it.

## mc --version
mc version RELEASE.2023-01-28T20-29-38Z (commit-id=2e95a70c98fb9c2629cd89817b8759bfa109a4d0)

**Comment by jiuker** [comment]
@AlexZIX Which commond do you use? `mc mirror` ?
