### ISSUE TITLE
coreutils find is missing in docker image

### ISSUE THREAD

**Issue by snpefk** [minio/mc#4469]
## Expected behavior
Run `find` inside docker execute command 

## Actual behavior
`bash: find: command not found`

## Steps to reproduce the behavior
1. `docker run --rm -it --entrypoint "bash" mc:latest`
2. call `find`

## mc --version
```
mc version RELEASE.2023-01-28T20-29-38Z (commit-id=2e95a70c98fb9c2629cd89817b8759bfa109a4d0)
Runtime: go1.19.4 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

**Comment by harshavardhana** [comment]
Use `mc find` not sure why you need unix find inside the container

**Comment by snpefk** [comment]
Yeah, thanks!

I Just find it weird that `grep` and all others coreutils that minio can emulate (`cp`, `ls` and so on) is available, but `find` is somehow missing.
