### ISSUE TITLE
Unable to initialize new alias from the provided credentials

### ISSUE THREAD

**Issue by myysophia** [minio/mc#4480]
## my init log
`
mc --debug alias set myminio/ http://chot-minio-api.prod.com:32100
Enter Access Key: 8W9U1EzdaXc8S01d
Enter Secret Key:
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://chot-minio-api.prod.com:32100/probe-bucket-sign-u1arm1opbi0f/?location=": dial tcp 23.108.55.152:32100: i/o timeout
 (5) alias-set.go:343 cmd.mainAliasSet(..) Tags: [myminio/, http://chot-minio-api.prod.com:32100]
 (4) alias-set.go:259 cmd.BuildS3Config(..) Tags: [http://chot-minio-api.prod.com:32100, 8W9U1EzdaXc8S01d, oGPFpuv0aJ9gE4bDjtRQOVIhMwrrqIN0, , auto]
 (3) alias-set.go:229 cmd.probeS3Signature(..) Tags: [s3v4, s3v2]
 (2) alias-set.go:221 cmd.probeS3Signature.func1(..) Tags: [s3v2]
 (1) client-s3.go:1586 cmd.(*S3Client).Stat(..) Tags: [probe-bucket-sign-u1arm1opbi0f]
 (0) client-s3.go:2137 cmd.(*S3Client).bucketStat(..)
 Release-Tag:RELEASE.2023-02-16T19-20-11Z | Commit:54e2edd1be94 | Host:ninesun | OS:linux | Arch:amd64 | Lang:go1.19.6 | Mem:4.4 MiB/19 MiB | Heap:4.4 MiB/7.6 MiB.

`
I exposed minio api using ingress, i copy Enter Access Key and Enter Secret Key on my minio-web. 
I am not sure whether my understanding of the commands provided by this official website is correct:
 **mc alias set myminio/ http://MINIO-SERVER MYUSER MYPASSWORD**
MINIO-SERVER: my ingress api url
MYUSER： Enter Access Key:
MYPASSWORD： Enter Secret Key

### here is my config.json
`
more /root/.mc/config.json
{
        "version": "10",
        "aliases": {
                "gcs": {
                        "url": "https://storage.googleapis.com",
                        "accessKey": "YOUR-ACCESS-KEY-HERE",
                        "secretKey": "YOUR-SECRET-KEY-HERE",
                        "api": "S3v2",
                        "path": "dns"
                },
                "local": {
                        "url": "http://localhost:9000",
                        "accessKey": "",
                        "secretKey": "",
                        "api": "S3v4",
                        "path": "auto"
                },
                "play": {
                        "url": "https://play.min.io",
                        "accessKey": "Q3AM3UQ867SPQQA43P2F",
                        "secretKey": "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
                        "api": "S3v4",
                        "path": "auto"
                },
                "s3": {
                        "url": "https://s3.amazonaws.com",
                        "accessKey": "YOUR-ACCESS-KEY-HERE",
                        "secretKey": "YOUR-SECRET-KEY-HERE",
                        "api": "S3v4",
                        "path": "dns"
                }
        }
}

`
### a question of mine
I tried mc alias .. set on other hosts. Why is this ip? 
`
dial tcp 23.108.55.152:32100:

`

## mc --version
` 
mc --version
mc version RELEASE.2023-02-16T19-20-11Z (commit-id=54e2edd1be94831eab8dc62b4d0b048825ff5cc3)
Runtime: go1.19.6 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.

`

**Comment by vadmeste** [comment]
@myysophia this doesn't look like a MinIO or mc issue. i/o timeout simply means mc was not able to reach the server. Most likely, your ingress is not configured correctly.

**Comment by myysophia** [comment]
thank you for your reply:)
My k8s cluster cannot be connected to the Internet. Why does 23.108.55.152 appear? 
```
I tried mc alias .. set on other hosts. Why is this ip? 
dial tcp 23.108.55.152:32100
```
I guess the default. configuration of mc is wrong?

**Comment by dormanze** [comment]
> 

``23.108.55.152`` looks like the result of domain name resolution.
you can try to execute ``nslookup  chot-minio-api.prod.com`` on the installation node of minio.

**Comment by harshavardhana** [comment]
Its because your DNS is pointing to a public IP that cannot be routed to your local cluster. You need to fix that first.

**Comment by Vinodh010** [comment]
I am facing the same issue. What was the fix provided in your case?

**Comment by harshavardhana** [comment]
> I am facing the same issue. What was the fix provided in your case?

Open new issues and stop conversations on year-old GitHub issues.
