### ISSUE TITLE
is exclude really working for mc mirror?

### ISSUE THREAD

**Issue by airdogvan** [minio/mc#4487]
Sorry to bring this back after so many years but I do have a problem.  Maybe something I don't do correctly??  [See this](https://github.com/minio/mc/issues/2343#issue-284326281)

## Expected behavior
Not copy the directories under the flag "exclude"
## Actual behavior
said directories are NOT excluded.

## Steps to reproduce the behavior
mc mirror --watch --exclude "/home/user/Downloads/" --exclude "/home/user/VirtualBox\ VMs/" --exclude "/home/user/.local/*"  /home/user bucket/home

The directory ".local" is not being excluded no matter what syntax I try ( home/user/.local or "home/user/.local" or home/user/local/*, etc....

## mc --version
- (paste output of `mc --version`)
- 
mc version RELEASE.2023-02-28T00-12-59Z (commit-id=5fbe8c26bab5592f0bc521db00665f8670a0fb31)
Runtime: go1.19.6 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information

Ubuntu 22.04 LTS

**Comment by JavierCCC** [comment]
+1

**Comment by thebearingedge** [comment]
was this user error or a bug?
