### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by 13567436138** [minio/mc#4489]
## Steps to reproduce the behavior
root@cluster3-159:~# mc
Segmentation fault (core dumped)

download from
http://dl.minio.org.cn/client/mc/release/linux-amd64/

## mc --version
- (paste output of `mc --version`)

## System information
root@cluster3-159:~# uname -a
Linux cluster3-159 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
We have no association with `minio.org.cn`. 

I will not speculate what it is you are downloading. Official releases are on https://min.io/download#/linux
