### ISSUE TITLE
Feature request for a "summarize" option

### ISSUE THREAD

**Issue by Geertsky** [minio/mc#4492]
## Expected behavior
I'm using mc mirror from a `systemd` service. This causes a "copy" or "remove" line for each changed object. 
I'm currently wrapping the `mc` binary to modify this behavior with `awk` but it would be better when `mc` would have a `--summarize`  option.

```
mc --summarize mirror --remove --overwrite <source>/<bucket> <destination>/<bucket>
Total: 0 B, Transferred: 0 B, Speed: 0 B/s
Copied: 1000 Removed: 999
```

## Actual behavior

```
mc -q mirror --remove --overwrite <source>/<bucket> <destination>/<bucket>
`<source>/<bucket>/file0001` -> `<destination>/<bucket>/file0001`
...
`<source>/<bucket>/file1000` -> `<destination>/<bucket>/file1000`
Removed `<destination>/<bucket>/otherfile001`.
...
Removed `<destination>/<bucket>/otherfile999`.
Total: 0 B, Transferred: 0 B, Speed: 0 B/s
```
## mc --version
- (paste output of `mc --version`)
```
mc version RELEASE.2023-02-28T00-12-59Z (commit-id=5fbe8c26bab5592f0bc521db00665f8670a0fb31)
Runtime: go1.19.6 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

**Comment by vadmeste** [comment]
I guess we can add what you suggested and we don't really need a specific flag for this.

**Comment by Geertsky** [comment]
> I guess we can add what you suggested and we don't really need a specific flag for this.

That would be great!
