### ISSUE TITLE
MC SQL to correctly parse ndjson files with extension .ndjson

### ISSUE THREAD

**Issue by christownsend-f3** [minio/mc#4518]
## Expected behavior

files in minio
`chris/2023-02-28/myfile.ndjson`

`mc sql --recursive --query "select * from S3Object s where s.id = '987654321'" mybucket/chris/2023-02-28 --json-input type=lines`

Returns:
```json
{"id":"987654321","mydata":"1"}
{"id":"987654321","mydata":"2"}
```
## Actual behavior
returns empty

We can force this to work by modifying the data type of the file to `.json` but ideally we would like not have to do this due to the default export file from cockroachdb changefeed is `.ndjson`.

Note: 
We think it might be a case of just adding the type to this [file](https://github.com/minio/pkg/blob/main/mimedb/db.go#L1623-L1626), but not 100% sure, and maybe someone with a bit more familarity with `mc` would know? 

## Steps to reproduce the behavior
- Add some .ndjson files to minio
- execute queries using `mc sql` 
- no results returned unless extension is `.json`

## mc --version
mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
Runtime: go1.19.4 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by christownsend-f3** [comment]
Will give this a go and feedback. Thanks

**Comment by christownsend-f3** [comment]
@klauspost this didn't resolve our issue. It still unable to read a file with the extension `.ndjson`

**Comment by christownsend-f3** [comment]
@klauspost thanks for trying this out. Could you try the same but not the specific file, just the directory?

If we explicitly state the file it works, but our use case needs to traverse all the files inside a directory

**Comment by jiuker** [comment]
You should upload your file with `content-type`
