### ISSUE TITLE
Run "mc --help" for a long time, no response

### ISSUE THREAD

**Issue by xulongZheng** [minio/mc#4522]
![1679911344065](https://user-images.githubusercontent.com/93906456/227914997-8edd33a7-ea79-473c-a2c9-37df0d6fc348.png)

Run "mc --help" for a long time, no response。
None of the commands running the mc are answered。
I am implementing ssm-kms encryption，kes server has been built，vaule server has been built，There was a problem using the mc。

**Comment by vadmeste** [comment]
@xulongZheng from where did you download mc binary ?

**Comment by xulongZheng** [comment]
> @xulongZheng from where did you download mc binary ?

![1679914247590](https://user-images.githubusercontent.com/93906456/227921451-4aea2057-2b76-4db3-9578-08e323230357.png)
The mc binary file is downloaded from the tutorial on the official website

**Comment by xulongZheng** [comment]
> @xulongZheng可以粘贴和？`uname -a``file $(which mc)`

![微信图片_20230327191501](https://user-images.githubusercontent.com/93906456/227926337-90803051-9101-474d-931c-3809bf54989d.jpg)

Is this the right one?

**Comment by vadmeste** [comment]
@xulongZheng what about `export CI=1; mc -h` ? does mc -h show something now ?

**Comment by xulongZheng** [comment]
> export CI=1; mc -h

![微信图片_20230327191501](https://user-images.githubusercontent.com/93906456/227927483-9295abc6-313f-4e6c-b5cf-6389894f529c.jpg)

**Comment by xulongZheng** [comment]
> @xulongZheng呢？MC -H 现在显示什么吗？`export CI=1; mc -h`

Is that it?

![微信图片_20230327191501](https://user-images.githubusercontent.com/93906456/227928053-76d5daad-40cd-4f36-9cfb-96202e6526e8.jpg)

**Comment by vadmeste** [comment]
@xulongZheng what terminal is this ?

**Comment by xulongZheng** [comment]
> @xulongZheng这是什么终端？
> 
> 目前，您需要在运行 mc 命令之前设置 CI=1，作为一种解决方法

Thank you, but now I have a new problem。

![1679919530024](https://user-images.githubusercontent.com/93906456/227939905-09bd9ebe-3151-44f5-835d-66c0a7746f19.png)

**Comment by klauspost** [comment]
Your mc is using the wrong port.
