### ISSUE TITLE
mc: <ERROR> Unable to restart the server. S3 API Requests must be made to API port.

### ISSUE THREAD

**Issue by xulongZheng** [minio/mc#4523]
Why is that?

![微信图片_20230327212104](https://user-images.githubusercontent.com/93906456/227949836-b2634801-33b6-449b-ad82-a7300d93d208.png)
![微信图片_20230327212113](https://user-images.githubusercontent.com/93906456/227949894-1d3ad687-3477-4786-b493-ec26550f25ce.png)
![微信图片_20230327212340](https://user-images.githubusercontent.com/93906456/227950161-f8dac2a4-b321-44d9-b9cf-7e57995717e0.jpg)

**Comment by klauspost** [comment]
You used the console port and not the api port.

**Comment by xulongZheng** [comment]
> You used the console port and not the api port.

Sorry, I don't quite understand. Could you explain it in detail or mark it in the screenshot?

**Comment by harshavardhana** [comment]
Your API port is 9090 not 9000 @xulongZheng
