### ISSUE TITLE
 dial tcp 127.0.0.1:9090: connect: connection refused.

### ISSUE THREAD

**Issue by xulongZheng** [minio/mc#4524]
Why does port "9090" refuse to connect but port "9000" does? Shouldn't you use api ports?

![1679968796472](https://user-images.githubusercontent.com/93906456/228107772-92df3e28-6ddb-46e0-a9a0-7ed9d3062162.jpg)
![1679968884649](https://user-images.githubusercontent.com/93906456/228107787-8f7cec19-1f4d-4566-9368-dabf140c2340.jpg)

**Comment by harshavardhana** [comment]
By default containers don't expose ports to host system, you need to ask for this in docker via -p 9090:9090

**Comment by xulongZheng** [comment]
> 默认情况下，容器不会向主机系统公开端口，您需要在 docker 中通过 -p 9090：9090 请求这一点

My execution steps are based on https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore，Why is the KMS not configured?

![1679970989364](https://user-images.githubusercontent.com/93906456/228112796-1f76794c-eb23-43e3-a481-0e517a5e028a.jpg)

**Comment by xulongZheng** [comment]
> By default containers don't expose ports to host system, you need to ask for this in docker via -p 9090:9090

My execution steps are based on [https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore](https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore) , Why is the KMS not configured?

![1679970989364](https://user-images.githubusercontent.com/93906456/228113605-492fea92-9e06-4ce3-ae73-5ba8bddd4818.jpg)

**Comment by klauspost** [comment]
@xulongZheng We do not provide general support here.

You can ask on [slack](https://slack.min.io/), [minio q+a](https://github.com/minio/minio/discussions/categories/q-a) or get a [subscription](https://min.io/pricing)
