### ISSUE TITLE
Server side encryption specified but KMS is not configured.

### ISSUE THREAD

**Issue by xulongZheng** [minio/mc#4525]
My execution steps are based on https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore , and [https://min.io/docs/minio/linux/administration/server-side-encryption/server-side-encryption-sse-kms.html#minio-encryption-sse-kms-quickstart](https://min.io/docs/minio/linux/administration/server-side-encryption/server-side-encryption-sse-kms.html#minio-encryption-sse-kms-quickstart) Why is the KMS not configured?

![1679970989364](https://user-images.githubusercontent.com/93906456/228120352-c0dc30b1-c278-4c95-b3ea-58f925f9f683.jpg)

**Comment by jiuker** [comment]
You should config the env and start minio. If you only config the server and start minio without 
```env
export MINIO_KMS_KES_ENDPOINT=https://play.min.io:7373
export MINIO_KMS_KES_KEY_FILE=root.key
export MINIO_KMS_KES_CERT_FILE=root.cert
export MINIO_KMS_KES_KEY_NAME=my-minio-sse-kms-key
```
The issue will happen @xulongZheng
