### ISSUE TITLE
Google Cloud Storage mc cp fails after upgrade to 2023-04-12 with error "Unable to validate source "

### ISSUE THREAD

**Issue by retoo** [minio/mc#4547]
We do a `mc cp` during an initContainer of a k8s service. We are downloading files from a Google Cloud Storage (GCS) bucket. 

This morning we suddenly started seeing problems where the error `"Unable to validate source" `was reported during startup (see full error bellow). 

We determined, that the latest version of minio/mc is causing that issue:

- `RELEASE.2023-04-12T02-21-51Z`  seems to be broken
  - **--version:** `mc version RELEASE.2023-04-12T02-21-51Z (commit-id=1843717c57fb87612469b7610344a7d49d97a497)`
  - **Docker image**: `docker.io/minio/mc@sha256:1336f0994d5caad9106f273cfccee986a49cb23655b5a3c48cd5d19c05abb108
`
- `RELEASE.2023-04-06T16-51-10Z` seems to work
  - **--version:**  `mc version RELEASE.2023-04-06T16-51-10Z (commit-id=1c6f4f48aba72b4c9770d911e95225f9de6e9488)`
  -  **Docker Image**: `docker.io/minio/mc@sha256:6bb24bf3bf60f464e4f545fcaeb7dca1344e86780cd9597750e3f9c95c9facda
`

## Workaround

Fall back to RELEASE.2023-04-06T16-51-10Z

## Expected behavior
download works without problems

## Actual behavior

 mc: <ERROR> Unable to validate source `GCS/XXXX-translations/XXX/XXXX: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.

## Steps to reproduce
* Copy a file from a GCS Bucket

**Comment by vadmeste** [comment]
It should be fixed with this minio-go PR, https://github.com/minio/minio-go/commit/0bf84b37b1553b5233d14c4d04ce2480b2cf5264
