### ISSUE TITLE
Build from git results in mc missing the od command

### ISSUE THREAD

**Issue by pelahi** [minio/mc#4573]
## Expected behavior
Pulling the executable from latest (https://dl.min.io/client/mc/release/linux-amd64/mc) gives a mc executable which can run the od command, that is measure single stream upload and download.

## Actual behavior
When built from source using spack for version [RELEASE.2023-05-04T18-10-16Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-05-04T18-10-16Z), the resulting mc executable does not recognize the od command

```
mc od
mc: <ERROR> `od` is not a recognized command. Get help using `--help` flag.
```

## Steps to reproduce the behavior
Build from git repo using [spack](https://github.com/spack/spack) with this [recipe](https://github.com/PawseySC/pawsey-spack-config/blob/main/repo/packages/miniocli/package.py). 

## mc --version
- For version missing the od command, `mc version DEVELOPMENT.GOGET`
- For executable downloaded from latest, `mc version RELEASE.2023-05-04T18-10-16Z (commit-id=5a0d5116f4936f25b7a1a67c8119cdcad6112cce)`

## System information
Linux OS: Ubuntu/20.04 and SUSE Linux 15SP2.

**Comment by shtripat** [comment]
@pelahi recipe file seems to have `2022-05-04` version and not for `RELEASE.2023-05-04T18-10-16Z`.

**Comment by shtripat** [comment]
With below additional entry in recipe file and fresh build I can see `mc od` option

```
    version(
        '2023-05-04',
        sha256='c7f32ff38746fc0b267bca16ab35e7e427c6326f02be7736a035e94218937e29',
        url="https://github.com/minio/mc/archive/RELEASE.2023-05-04T18-10-16Z.tar.gz",
    )
```

**Comment by pelahi** [comment]
Hi @shtripat , the default version in the recipe is an older version but I simply invoked spack to build the newer version `spack install miniocli@2023-05-04T18-10-16Z`. But I will see if a recipe update somehow fixes the issue. Can you let me know what version of spack you used, what architecture did you build it for?

**Comment by shtripat** [comment]
I have used `0.20.0.dev0 (dcfcc03497f24bb18fde8e4e3f51d5d7a6037155)` and on a fedora-38 box `6.2.15-300.fc38.x86_64`.
