### ISSUE TITLE
bucket versions are not listed

### ISSUE THREAD

**Issue by techtug-a** [minio/mc#4587]
## Expected behavior
Should list the existing versions in the bucket

## Actual behavior
mc: <ERROR> Unable to list folder. unrecognized option:Tenant

The normal ls command works normally. Versioning is enabled on the bucket.
mc version info s3/bucket_name/
s3/bucket_name/ versioning is enabled

## Steps to reproduce the behavior
mc ls --versions s3/bucket_name/
mc: <ERROR> Unable to list folder. unrecognized option:Tenant

## mc --version
mc --version
mc version RELEASE.2023-05-26T23-31-54Z (commit-id=9cb069e7afaa45c64c45b7b59ba65c0441019efd)
Runtime: go1.19.9 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
Debian 10
S3 Compatible Storage

**Comment by klauspost** [comment]
> S3 Compatible Storage

My guess is this is your problem - and it isn't as compatible as you think ;)

**Comment by techtug-a** [comment]
Hi Klaus,
thanks for your response. 
Yes unfortunately seems like there is some incompatibility in the s3 storage. 
Br
