### ISSUE TITLE
Autocompletion of directory and file names in a bucket

### ISSUE THREAD

**Issue by fatimalkaus** [minio/mc#4592]
# Enhancement
## Expected behavior
I want to tap \<TAB\> to autocomplete file names and dirs in bucket. 
## Example
mc cp minio/my-bucket/my-di\<TAB\>/fi\<TAB\> /dst/path/

**Comment by shtripat** [comment]
Have you tried `mc --autocompletion` to enable auto completion for your shell?

**Comment by FatimaAlKaus** [comment]
> Have you tried `mc --autocompletion` to enable auto completion for your shell?

Yep. Doesn't auto completion only work for mc commands?

**Comment by harshavardhana** [comment]
It works for alias and bucket and objects as well

**Comment by PetraSX** [comment]
Just installed mc on MacOs. I'm using zsh and the autocomplete for objects and buckets doesn't work. Any fix / ideea?
