### ISSUE TITLE
mc cp --continue doesn't work

### ISSUE THREAD

**Issue by jflambert** [minio/mc#4593]
## Expected behavior

I'm fairly new to minio and mc. I expected `mc cp --continue minio/bucket/filename .` to continue if I ctrl+c during the download, or if my connection gets reset by peer, etc.

## Actual behavior

I'm trying to resume downloading a 10GB and it always restarts from 0

## Steps to reproduce the behavior

1. put a decently large file in a minio bucket (10GB in my case)
2. `mc cp --continue minio/bucket/file.gz .`
3. ctrl+c during download, after downloading some percentage of the file
4. rerun command from step 2
5. "Resuming copy from 0B / 10GB"

## mc version

mc version RELEASE.2023-05-30T22-41-38Z (commit-id=ca1d00741b954210c264effb576ef1ed8567722c)
Runtime: go1.19.9 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information

MinIO VERSION 2022-03-05T06:32:39Z
Ubuntu 22.04

**Comment by harshavardhana** [comment]
mc cp --continue is not meant for single file uploads. It is meant to resume a collection of objects.
