### ISSUE TITLE
`mediaType in manifest list` error on docker pull

### ISSUE THREAD

**Issue by teunis90** [minio/mc#4603]
Was there a change in how Docker images get created and uploaded to Docker Hub? Since the last image build our CICD pipelines are failing with this error:

## Actual behavior

```
$ docker pull registry.selfhosted-harbor-server.com/nextpertise-proxy/minio/mc:RELEASE.2023-06-06T13-48-56Z
Error response from daemon: mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'

$ docker pull registry.selfhosted-harbor-server.com/nextpertise-proxy/minio/mc:latest
Error response from daemon: mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'
```

## Expected behavior

We can still download the previous images via our proxy server.

```
$ docker pull registry.selfhosted-harbor-server.com/nextpertise-proxy/minio/mc:RELEASE.2023-05-30T22-41-38Z
RELEASE.2023-05-30T22-41-38Z: Pulling from nextpertise-proxy/minio/mc
28ff5ee6facb: Pull complete
c2c48cd3fefe: Pull complete
b8469d91ead6: Pull complete
2d52f9163abc: Pull complete
Digest: sha256:6dfa7bfb80fcf2afa6f67f3650810febab6d58026ffc1d96f3b1ef67b1005920
Status: Downloaded newer image for registry.selfhosted-harbor-server.com/nextpertise-proxy/minio/mc:RELEASE.2023-05-30T22-41-38Z
registry.selfhosted-harbor-server.com/nextpertise-proxy/minio/mc:RELEASE.2023-05-30T22-41-38Z
```

We proxy cache our images with Harbor Registry, only the `minio/mc:latest` and `minio/mc:RELEASE.2023-06-06T13-48-56Z` have this issue. Other Docker hub images can be accessed, same for older `minio/mc` images.

I do not see any Docker related changes in the changelog: https://github.com/minio/mc/compare/RELEASE.2023-05-30T22-41-38Z...RELEASE.2023-06-06T13-48-56Z

There is no issue when we skip the cache and directly invoke Docker hub: `docker pull minio/mc:RELEASE.2023-06-06T13-48-56Z`. I'm clueless what happens here. The only thing I can think of is that the Docker image is differently build which causes this error.

Any ideas? I see that the Docker images are pushed by https://hub.docker.com/u/imdonatello, but unfortunately can't find a GH username to tag in this issue.

In case other people hit this bug as well, we run a fairly old version of Harbor, version `v2.2.1`. For now I've made a workaround in our CICD file that we use `minio/mc:RELEASE.2023-05-30T22-41-38Z` instead. My colleague who manages the Harbor server is on vacation. When he's back I'll ask him to upgrade and see if this would resolve the issue.

**Comment by dayantrivani** [comment]
I came to the same error while pulling a Docker image from my Harbor (version 2.4.1) configured with proxy cache. The error message was the same as yours: "Error response from daemon: mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'".

After upgrading Harbor to version 2.6.4, I can now pull the same image without any errors. Everything is functioning normally.
