### ISSUE TITLE
Mirror watch doesn't cope on jsoniter error

### ISSUE THREAD

**Issue by hrenard** [minio/mc#4611]
Hi,

I'm runnig `mc mirror --watch --remove --overwrite alias /path` to backup my cluster. The other day, I updated my MinIO cluster and `mc` logged :
```
<ERROR> Failed to perform mirroring readObjectStart: expect { or n, but found
, error found in #3 byte of ...|   |..., bigger context ...|   |...
```
## Expected behavior
I expected either the activity to continue as usual or the process to exit.

## Actual behavior
Well nothing happened since. The process is running without activity.

## Steps to reproduce the behavior
I didn't try to reproduce yet. But, my guess is :
1. Run `mc mirror --watch`.
2. Restart the cluster.

## mc --version
mc version DEVELOPMENT.2023-04-28T02-52-06Z (commit-id=a7e729fd385e369373dd8f56724532b4617149f6)
Runtime: go1.20.3 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
The MinIO cluster runs on Kubernetes via the MinIO operator.

(The error is similar to https://github.com/minio/mc/issues/4002, but it's not the same context).

**Comment by r-scheele** [comment]
Hi @hrenard, please provide the following details to allow us look into the issue.
1. minio version
2. old mc version, i'm guessing the mc version you provided is the current version, if not please provide it.

Also, can you try to highlight the steps to reproduce the error?

**Comment by harshavardhana** [comment]
@hrenard this requires upgrade of `mc` you are not using latest and also upgrade your MinIO deployment.
