### ISSUE TITLE
Two separate minio synchronize data when one minio delete object Caused endless loop

### ISSUE THREAD

**Issue by kksh3ll** [minio/mc#4627]
## Expected behavior
   
   When two separate minios use MC to synchronize data, no matter what operations are performed on one of them, such as uploading or deleting, the data can be synchronized correctly.

## Actual behavior

    Two separate minios use MC to synchronize data, when deleting an object, one of them listens to the other's s3:ObjectRemoved:Delete event and performs a remove operation on its own minio. Similarly, the other will also be affected by the same event, forming a endless loop. The direct result is that the same object is failed to upload and the cpu heavily consumed.

## Steps to reproduce the behavior
1. Two minio server (A: 192.168.1.1, B: 192.168.1.2) running normally.
2. Running mc .
   A: mc config host add master http://192.168.1.1:9000 admin ws-123456 && mc config host add slave http://192.168.1.2:9000 admin ws-123456 && mc mirror --overwrite --remove --watch master slave

   B: mc config host add master http://192.168.1.2:9000 admin ws-123456 && mc config host add slave http://192.168.1.1:9000 admin ws-123456 && mc mirror --overwrite --remove --watch master slave
3. Upload file to minio, then delete file.
4.  minio process consumes a large amount of CPU( 37%~ 40%), Failed to upload the same file.

## mc --version
mc version RELEASE.2023-07-07T05-25-51Z (commit-id=1b992864ee0682b8be6a590ccbda080475dcadd3)
Runtime: go1.19.10 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by harshavardhana** [comment]
Only way to safely do this is via `mc mirror --active-active` - closing this issue.

**Comment by kksh3ll** [comment]
@klauspost @harshavardhana I can try this , thx~
