### ISSUE TITLE
--exclude option in mc mirror command

### ISSUE THREAD

**Issue by JavierCCC** [minio/mc#4630]
## Expected behavior
mc mirror --exclude ".*" --exclude "*.temp" --watch /dir minio/dir
This command shoud exclude files starting with a dot character, or files with file extension "temp" 

## Actual behavior
All files are mirrored, the command ignores the excludes.

## Steps to reproduce the behavior
1) try to mirror a dir with a bucket
2) set exclusions in command
4) run command
3) create files in source to match exclusions
4) files will be copied to the bucket anyway

## mc --version
mc version RELEASE.2023-07-07T05-25-51Z (commit-id=1b992864ee0682b8be6a590ccbda080475dcadd3)
Runtime: go1.19.10 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
OEL 8.7 / amd64

**Comment by dormanze** [comment]
You should try :
`mc mirror --exclude "*." --exclude "*.temp" --watch /dir minio/dir`

**Comment by dmmartins** [comment]
does the exclude option work for folders? I'm trying to sync my data folder to s3 and I want to skip `.minio.sys` but this doesn't work
```
mc mirror --watch --exclude "/data/.minio.sys/*" /data "s3/${S3_BUCKET_NAME}/minio"
```

I also tired this, but still syncs `/data/.minio.sys` to s3
```
mc mirror --watch --exclude "/data/.minio.sys/**/*" /data "s3/${S3_BUCKET_NAME}/minio"
```

**Comment by timmychan97** [comment]
I am having the same issue

Non of the following syntax worked for me.

`mc mirror --watch --exclude "/data/.*" /data "s3/${S3_BUCKET_NAME}/minio"`
`mc mirror --watch --exclude "data/.*" /data "s3/${S3_BUCKET_NAME}/minio"`
`mc mirror --watch --exclude "/.*" /data "s3/${S3_BUCKET_NAME}/minio"`
`mc mirror --watch --exclude ".*" /data "s3/${S3_BUCKET_NAME}/minio"`



```
>>> mc mirror --watch --exclude "k8s-minio/.*" /k8s-minio target_minio/minio-test

`/k8s-minio/.minio.sys/backend-encrypted` -> `target_minio/minio-test/.minio.sys/backend-encrypted`
`/k8s-minio/.ash_history` -> `target_minio/minio-test/.ash_history`
`/k8s-minio/.minio.sys/buckets/000003675/b.pdf/fs.json` -> `target_minio/minio-test/.minio.sys/buckets/000003675/b.pdf/fs.json`
`/k8s-minio/.minio.sys/buckets/.tracker.bin` -> `target_minio/minio-test/.minio.sys/buckets/.tracker.bin`
`/k8s-minio/.minio.sys/buckets/000003675/x.pdf/fs.json` -> `target_minio/minio-test/.minio.sys/buckets/000003675/x.pdf/fs.json`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf066a9]
goroutine 43 [running]:
github.com/minio/mc/cmd.uploadSourceToTargetURL({_, _}, {{{0x0, 0x0}, 0xc00245a180, {0xc00077e020, 0xc}, 0xc002f3be00, 0x2, 0x671, ...}, ...})
	github.com/minio/mc/cmd/common-methods.go:493 +0x10a9
github.com/minio/mc/cmd.(*mirrorJob).doMirror(0xc000024000, {0x14c8660?, 0xc0023a42d0}, {{0x0, 0x0}, 0xc00245a180, {0xc00077e020, 0xc}, 0xc002f3be00, 0x2, ...})
	github.com/minio/mc/cmd/mirror-main.go:496 +0x768
github.com/minio/mc/cmd.(*mirrorJob).startMirror.func1()
	github.com/minio/mc/cmd/mirror-main.go:817 +0x78
github.com/minio/mc/cmd.(*ParallelManager).addWorker.func1()
	github.com/minio/mc/cmd/parallel-manager.go:105 +0x6b
created by github.com/minio/mc/cmd.(*ParallelManager).addWorker in goroutine 1
	github.com/minio/mc/cmd/parallel-manager.go:94 +0x76
```
