### ISSUE TITLE
mirror on bucket ~ 10 times slower than rclone sync

### ISSUE THREAD

**Issue by philipkozeny** [minio/mc#4660]
## Expected behavior

I am syncing a bucket with ~ 1.9 million files (700 GB in total) between an OVH Object Storage (High Performance) and a local minio installation (docker, 4 disks, ssds). I expect that `mc` and `rclone` achieve similar results when syncing that bucket.

## Actual behavior

```
root@storage:/home/user# time mc mirror --overwrite --remove --json ovh/live local/live                                 |
                                                                                                                                          |
{                                                                                                                                         |
 "status": "success",                                                                                                                     |
 "total": 0,                                                                                                                              |
 "transferred": 0,                                                                                                                        |
 "speed": 0                                                                                                                               |
}                                                                                                                                         |
                                                                                                                                          |
real    54m56.469s                                                                                                                        |
user    2m30.552s                                                                                                                         |
sys     0m17.831s                                                                                                                         |


root@storage:/home/user# time rclone sync -c --progress ovh:live local:live                                             |
Transferred:              0 B / 0 B, -, 0 B/s, ETA -                                                                                      |
Checks:           1877696 / 1877696, 100%                                                                                                 |
Elapsed time:      9m25.2s                                                                                                                |
                                                                                                                                          |
real    9m25.362s                                                                                                                         |
user    2m49.661s                                                                                                                         |
sys     0m10.360s                                                                                                                         |

root@storage:/home/user# time mc mirror --overwrite --remove --json --md5 ovh/live local/live

{
 "status": "success",
 "total": 0,
 "transferred": 0,
 "speed": 0
}

real    54m51.008s
user    2m37.841s
sys     0m18.994s

```

I have tried different setups (one disk vs 4 disks, XFS vs ext4) but the result is more or less the same.

## Steps to reproduce the behavior

Bucket with millions of small files, sync with rclone and mc.

## mc --version
`mc version RELEASE.2023-08-08T17-23-59Z (commit-id=01fb7c5a96ccc8bab434d1210847279710c8ae93)`

## System information

`Minio: Version: RELEASE.2023-08-09T23-30-22Z (go1.19.12 linux/amd64)` running on an Debian 12 VM (4 Core, 8 GB Ram)

**Comment by philipkozeny** [comment]
Slow requests happen here from time to time.

```
mc: <DEBUG> GET /live/?continuation-token=xyz&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix= HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.61 mc/RELEASE.2023-08-08T17-23-59Z
Authorization: AWS4-HMAC-SHA256 Credential=xxx/20230814/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: xxxx
X-Amz-Date: 20230814T194233Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 354300
Accept-Ranges: bytes
Content-Type: application/xml
Date: Mon, 14 Aug 2023 19:43:08 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: xxx
X-Amz-Request-Id: xxx
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  35.120445013s
```

**Comment by jiuker** [comment]
@harshavardhana rclone use `ListObjectsV1Handler`, mc use `ListObjectsV2Handler` , hope that's useful to you

**Comment by harshavardhana** [comment]
> Slow requests happen here from time to time.
> 
> ```
> mc: <DEBUG> GET /live/?continuation-token=xyz&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix= HTTP/1.1
> Host: 127.0.0.1:9000
> User-Agent: MinIO (linux; amd64) minio-go/v7.0.61 mc/RELEASE.2023-08-08T17-23-59Z
> Authorization: AWS4-HMAC-SHA256 Credential=xxx/20230814/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: xxxx
> X-Amz-Date: 20230814T194233Z
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 200 OK
> Content-Length: 354300
> Accept-Ranges: bytes
> Content-Type: application/xml
> Date: Mon, 14 Aug 2023 19:43:08 GMT
> Server: MinIO
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Vary: Origin
> Vary: Accept-Encoding
> X-Amz-Id-2: xxx
> X-Amz-Request-Id: xxx
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> 
> mc: <DEBUG> Response Time:  35.120445013s
> ```

Yeah this is because your local setup is slower here.

Can you do `mc admin trace -a` and see where you spend your most of the time ?

**Comment by philipkozeny** [comment]
Taking a quick look I don't see any specific calls that take longer than the rest, what I see though: an endless loop of calls like

```
...
2023-08-15T19:56:55.518 [OS] os.OpenFileR 127.0.0.1:9000 /mnt/data/live/49/5733d6cc-a027-420d-a90e-890606b39787 54.933µs
2023-08-15T19:56:55.518 [OS] os.OpenFileR 127.0.0.1:9000 /mnt/data/live/49/5733d6cc-a027-420d-a90e-890606b39787/xl.meta 16.641µs
2023-08-15T19:56:55.518 [SCANNER] scanner.ScanObject 127.0.0.1:9000 /mnt/data live/49/5733d6cc-a027-420d-a90e-890606b39787/xl.meta 2.504105ms
2023-08-15T19:56:55.516 [SCANNER] scanner.ScanFolder 127.0.0.1:9000 /mnt/data live/49/5733d6cc-a027-420d-a90e-890606b39787 10.373466ms
...
```

this kind of calls never stop, even after hours of running and aborting the original mc mirror command.  Any reasons for that or is that something unrelated?

**Comment by harshavardhana** [comment]
> ...
> 2023-08-15T19:56:55.518 [OS] os.OpenFileR 127.0.0.1:9000 /mnt/data/live/49/5733d6cc-a027-420d-a90e-890606b39787 54.933µs
> 2023-08-15T19:56:55.518 [OS] os.OpenFileR 127.0.0.1:9000 /mnt/data/live/49/5733d6cc-a027-420d-a90e-890606b39787/xl.meta 16.641µs
> 2023-08-15T19:56:55.518 [SCANNER] scanner.ScanObject 127.0.0.1:9000 /mnt/data live/49/5733d6cc-a027-420d-a90e-890606b39787/xl.meta 2.504105ms
> 2023-08-15T19:56:55.516 [SCANNER] scanner.ScanFolder 127.0.0.1:9000 /mnt/data live/49/5733d6cc-a027-420d-a90e-890606b39787 10.373466ms
> ...

this is normal @philipkozeny unrelated to `mc mirror` - if there are no other latencies are > 1s then you are not limited by the disks - however the slowness is at the top layer.

I suspect you are mostly facing this problem https://github.com/minio/minio/pull/17855

**Comment by harshavardhana** [comment]
Feel free to upgrade the server and let us know how it goes, there is nothing actionable on `mc`.
