### ISSUE TITLE
Minio 'cp' slows down over time

### ISSUE THREAD

**Issue by bwhartlove** [minio/mc#4680]
## Expected behavior
While uploading 2GB files, I'd expect to see a relatively stable connection, given the box being used to upload is connected to my Minio cluster with a 10 gig line. Using [warp](https://github.com/minio/warp), I can consistently get speeds over 1000MiB/s:

`----------------------------------------
Operation: PUT. Concurrency: 20
* Average: 1104.69 MiB/s, 0.54 obj/s

Throughput, split into 73 x 1s:
 * Fastest: 1106.3MiB/s, 0.54 obj/s
 * 50% Median: 1104.2MiB/s, 0.54 obj/s
 * Slowest: 1095.3MiB/s, 0.53 obj/s`

## Actual behavior
When uploading with minio cp, the upload starts at over 1GiB/s, but quickly plummets to roughly 320MiB/s, and remains there the rest of the upload.

## Steps to reproduce the behavior
1. Created a directory with 20x2GB files
2. Used the below mc command to upload:
`mc cp --recursive --insecure testdir/ mytenant/mybucket/`

## mc --version
`mc version RELEASE.2023-07-21T20-44-27Z (commit-id=1c17ff4c995d772c97eed8c5a269f2074a9425fe)
Runtime: go1.19.11 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>`

## System information
- Box using for uploading --> Rocky 8.7
- 10 Gig wired connection between box using to upload and Minio cluster
- Minio deployed using Kubernetes operator version 5.0.7

**Comment by mdcrank** [comment]
Commenting for visibility.

**Comment by r-scheele** [comment]
Hi @bwhartlove getting a consistent speed with warp makes sense because it's a benchmarking tool.

**Comment by r-scheele** [comment]
> Wanted to follow up on this. I dug into the GO Minio SDK and code bases for both mc cp and warp, but as a newer GO developer, I was struggling to discern any major differences between the two implementations that would cause such a stark difference in upload speeds. Any info would be greatly appreciated. Thanks!

The implementation between the two differs, because mc is meant to interact with your minio cluster while warp tests for performance.

**Comment by r-scheele** [comment]
the upload speed is dependent on how fast your local drive is at testdir/  so even if you have 100's of gigs of bandwidth on the server, you are still limited by the performance of the local drive.

**Comment by bwhartlove** [comment]
Roger that. I believe the drive being used was the bottleneck. Moving it to another drive seemed to create a more stable upload environment. Thanks!
