### ISSUE TITLE
mc cp -r, creates multiple folder

### ISSUE THREAD

**Issue by C1ph3R-s** [minio/mc#4695]
Hi,

I would like to have a little guidance: so I have to upload a folder structure to s3 with minio, and i used this command below:

```
mc cp -r < foldername > s3/< bucket name >/
mc cp -r test1 s3/test_bucket/
```
(I have tried with --disable-multipart and --md5 options too)

my local structure is:

```
test1/
└── test2
    └── test3
        └── test.txt
```
 
and i got this after the upload 
```
mc tree s3/test_bucket/

├─ test1
│  ├─ test2
│  │  ├─ test3
│  │  ├─ test3
│  │  ├─ test3
│  │  ├─ test3
│  │  ├─ test3
│  │  ├─ test3
```

Could u give me a solution for this pls or what is the reason of that? (i also tried mirror but the result was the same)

Thanks

**Comment by harshavardhana** [comment]
Is S3 here AWS S3 ?

**Comment by C1ph3R-s** [comment]
Openshift S3 bucket

**Comment by harshavardhana** [comment]
> @harshavardhana thanks for your reply :) Openshift S3 bucket

What is an Openshift S3 bucket? Who is vendor here ?

**Comment by C1ph3R-s** [comment]
Yes it is an RedHat Openshift S3 Object BucketClaim. Do u have any suggestion?

**Comment by klauspost** [comment]
Sounds like a problem with Openshift. It is tagged as "Technology Preview", so my guess is you found a bug. I suggest you reach out to them.

**Comment by C1ph3R-s** [comment]
@klauspost  I do not really understand wh you closed this issue, Redhat S3 handle folders well, except when I use minio. So I know minio does not create folder it just upload them, but as I see it upload the same folder multiple time if it contains a file.

**Comment by klauspost** [comment]
@C1ph3R-s As I said, there is nothing mc can do wrong with regard to "folders" (prefixes). They are created as objects with keys that have shared prefixes are uploaded.

Shared prefixes are to be returned by ListObject - and it seems the server is returning the same prefix several time.

Either way, it is not a client-side (mc) issue, so there is nothing we can do on our side.
