### ISSUE TITLE
Mirroring old minio version to a newer version  with a lot of files ( over 10 million)

### ISSUE THREAD

**Issue by kingprimex** [minio/mc#4707]
## Expected behavior
Command used to copy:
mc mirror --debug minio_data/bucket/bigdirectory new_minio/bucket/bigdirectory
Expected the mirror to start
## Actual behavior
After 51 minutes it shutsoff the mirror command with no information transmitted 
## Steps to reproduce the behavior
upload about 15 million files each about 100kb in size (pdf) and then try to copy the files from one cluster to the other
## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2020-07-31T23-34-13Z
## System information
Source Cluster: 8 nodes, each with 8 CPU and 32 GB RAM ( virtual) 
source minio : RELEASE.2020-07-31T03-39-05Z

Dest Cluster: 8 nodes, each with 8 CPU and 32 GB RAM( virtual) 
dest minio:      RELEASE.2023-09-30T07-02-29Z
[minio_big_directory.docx](https://github.com/minio/mc/files/12800311/minio_big_directory.docx)

**Comment by kingprimex** [comment]
bump

**Comment by klauspost** [comment]
> RELEASE.2020-07-31T23-34-13Z

Don't use an ancient version.
