### ISSUE TITLE
Can't access Minio community support Slack

### ISSUE THREAD

**Issue by timgent** [minio/mc#4708]
## Expected behavior

That I can access the [Minio Slack](https://minio.slack.com/signup#/domain-signup) with a non-minio email address

## Actual behavior

Requires an email address with a minio domain

## Steps to reproduce the behavior

Go to the sign-up link above

## mc --version

n/a

## System information

n/a

**Comment by harshavardhana** [comment]
This is fixed.

**Comment by hendramaulana-infoterkini** [comment]
can't signup again with a non-minio email address
<img width="423" alt="Screen Shot 2024-04-19 at 08 14 44" src="https://github.com/minio/mc/assets/132988100/4590c8af-bcbf-4ba9-ad98-9198ba47c88e">
