### ISSUE TITLE
Can't stop all Minio servers

### ISSUE THREAD

**Issue by timgent** [minio/mc#4709]
## Expected behavior

I should be able to run:

`mc admin service stop`

To stop all minio services so that it no longer uses port 9000.

## Actual behavior

I can only stop them by name, and even stopping every service listed in `mc alias list` doesn't free up the port.

## Steps to reproduce the behavior

See above

## mc --version
- (paste output of `mc --version`)
```bash
mc version RELEASE.2023-08-15T23-03-09Z (commit-id=df68f5cf897d30203bfa3003c0882b3f76edcdd7)
Runtime: go1.21.0 darwin/arm64
Copyright (c) 2015-0000 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## System information
M1 Mac
OS: 13.3.1 (a) (22E772610a)

**Comment by shtripat** [comment]
`mc admin service stop ALIAS` is meant to stop all MinIO services under one deployment. If you have multiple deployments listed under `mc alias ls` then have to be stopped one by one.
Don't confuse a deployment with MinIO instance. A deployment is like a MinIO cluster involving multiple nodes (each running one instance of MinIO service) and `mc admin service stop` would stop all the instance of this one cluster.

**Comment by timgent** [comment]
> mc admin service stop ALIAS is meant to stop all MinIO services under one deployment. If you have multiple deployments listed under mc alias ls then have to be stopped one by one.

I've tried stopping them one by one, but the port is still in use. Is that expected?

**Comment by klauspost** [comment]
Sounds like something is restarting them.

**Comment by harshavardhana** [comment]
If you run your service via launcher which is true if you installed via `brew install` - it will restart the service upon stop() by an external signal.
