### ISSUE TITLE
no response executing the command

### ISSUE THREAD

**Issue by boot1992** [minio/mc#4711]
## Expected behavior
execute the command successfully
## Actual behavior
no response
## Steps to reproduce the behavior
follow the quickstart:
curl https://dl.min.io/client/mc/release/linux-amd64/mc \
  --create-dirs \
  -o $HOME/minio-binaries/mc

chmod +x $HOME/minio-binaries/mc
export PATH=$PATH:$HOME/minio-binaries/

mc --help
## mc --version
- (paste output of `mc --version`)
no response
## System information
CentOS Linux release 7.9.2009 (Core)

i tried different linux server, none wored.  but  the windows version works well. 

![image](https://github.com/minio/mc/assets/66160101/cd2a2338-131f-40ee-97d1-b5bfa85aaf1e)

**Comment by harshavardhana** [comment]
you need to do `./mc --help`

**Comment by boot1992** [comment]
> you need to do `./mc --help`

i tried this, it doesn't work
