### ISSUE TITLE
mc cp bug

### ISSUE THREAD

**Issue by donatello** [minio/mc#4734]
## Expected behavior

With files in the current directory like:

```
internal/
internal.tar
```

```
mc cp -r internal play/test
```

should copy only the `internal/` directory recursively.

## Actual behavior

`internal.tar` is also being copied by mc.

## Steps to reproduce the behavior

As described above.

## mc --version

Current master

## System information

Linux.

**Comment by harshavardhana** [comment]
this is not a bug @donatello its called prefix match you need to copy the directory you need to add `/` at the end.
