### ISSUE TITLE
Multiple --ignore params don't work with mc find

### ISSUE THREAD

**Issue by slax81** [minio/mc#4743]
## Expected behavior
Would like to ignore several file name patterns.

## Actual behavior
Does not ignore the files

## Steps to reproduce the behavior
`mc find "${mc_alias}/bak" --path "*/dbs/*" --older-than 45d \
        --ignore "*${YYY}-01-01*" --ignore "*${YYY}-02-01*" --ignore "*${YYY}-03-01*" \
        --ignore "*${YYY}-04-01*" --ignore "*${YYY}-05-01*"  --exec "mc rm {}"`

Where $YYY is current year "2023"

## mc --version
mc version RELEASE.2023-03-23T20-03-04Z (commit-id=81453d7c8fcc7621f976cfd8e8a72e78f4d243c7)
Runtime: go1.19.7 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
Running on gitlab pipeline

**Comment by slax81** [comment]
It ignores files --older-than 45d, but no patterns are used. Not sure if this is normal behavior?

**Comment by vadmeste** [comment]
> It ignores files --older-than 45d, but no patterns are used. Not sure if this is normal behavior?

--ignore is a single flag type, specifying multiple flags doesn't have the desired effect
