### ISSUE TITLE
mc anonymous doc is incorrect for set-json

### ISSUE THREAD

**Issue by vincib** [minio/mc#4761]
## Expected behavior

when you type "mc anonymous" it explains the following : 

`  mc anonymous [FLAGS] set-json TARGET FILE`

## Actual behavior

the anonymous command line take the file THEN the target, not the other way around ;) 

note: the online doc here is good though https://min.io/docs/minio/linux/reference/minio-mc/mc-anonymous-set-json.html

## mc --version

mc version RELEASE.2023-11-10T21-37-17Z (commit-id=56803d21674f9cb9960b86381fe2c527f51fb07b)
Runtime: go1.21.4 linux/amd64

**Comment by shtripat** [comment]
Resolved through https://github.com/minio/mc/pull/4745
