### ISSUE TITLE
gzip-compressed files are unexpectedly decompressed while copying out of a bucket

### ISSUE THREAD

**Issue by cstavish** [minio/mc#4769]
## Expected behavior

A gzip-encoded file copied into a bucket using mc is identical to the file later copied out of the bucket using mc. This is how mc behaves in versions 2023-08-01 and earlier (although this expected behavior may also be present in versions later than 2023-08-01) but not as of 2023-11-20.

## Steps to reproduce the behavior

1. Copy a file containing gzip-compressed data to a bucket: `mc cp test.json local/bucket/test.json --attr 'content-type=json; content-encoding=gzip'` EDIT: there should be no space between between the attributes, e.g. `--attr 'content-type=json;content-encoding=gzip'`
2. Verify that Content-Type and Content-Encoding are set to json and gzip respectively: `mc stat local/bucket/test.json`
3. Copy file out of the bucket to current directory: `mc cp local/bucket/test.json .`

Size of the local file created in Step 3 is the same as the file originally copied into the bucket, as well as the size of the file within the bucket, but is plain text, not gzip, and therefore is an incomplete JSON file because only the first portion of the file (corresponding to the original, gzipped, file length) is written.

## mc --version

> mc version RELEASE.2023-11-20T16-30-59Z (commit-id=937b34616f012ad30e1cd6fd61e1da25ff931648)
Runtime: go1.21.4 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"

**Comment by vadmeste** [comment]
@cstavish what version of MinIO server are you using ?

**Comment by klauspost** [comment]
@vadmeste OP is messing with stuff that he shouldn't really be messing with. I doubt this will work with AWS. 

For MinIO, if there is a `Content-Length` returned it should not decompress, since it is not server-side compressed. However, I think AWS will likely return both values and lead to most clients decompressing.

**Comment by vadmeste** [comment]
@klauspost yes agree; mc should disallow setting content-encoding in the first place; but the ticket says it was working before and wanted to gather more information

**Comment by harshavardhana** [comment]
If the `mc` says Accept-Encoding: identity - this would almost always work @vadmeste

**Comment by cstavish** [comment]
Thank you all for your responses! My intention in raising this issue is to prevent other users from encountering data loss or corruption while performing actions like `mc mirror --preserve...`, which 

> @cstavish what version of MinIO server are you using ?
@vadmeste, for Minio, I am running `minio/minio:RELEASE.2023-03-09T23-16-13Z` with docker compose. I also tested with [latest](https://hub.docker.com/layers/minio/minio/latest/images/sha256-108829b9e36765cf4106e8468b37ac9cfb26bb33c54398c1d43132b8404406d4?context=explore) with the same results.

> @vadmeste OP is messing with stuff that he shouldn't really be messing with. I doubt this will work with AWS.
@klauspost I'm not sure I understand what I'm doing incorrectly here, can you please elaborate? My use-case is to compress a JSON file before storing it into Minio, and have the content-encoding attribute set to gzip, so that when a web browser later downloads the file from Minio, the browser downloads the gzipped file from the server and automatically decompresses it client-side. Although this issue has nothing to do with AWS S3, I have followed the identical pattern successfully in AWS S3.

**Comment by harshavardhana** [comment]
> @klauspost I'm not sure I understand what I'm doing incorrectly here, can you please elaborate? My use-case is to compress a JSON file before storing it into Minio, and have the content-encoding attribute set to gzip, so that when a web browser later downloads the file from Minio, the browser downloads the gzipped file from the server and automatically decompresses it client-side. Although this issue has nothing to do with AWS S3, I have followed the identical pattern successfully in AWS S3.

So you want to automatically decompress it client side then that's what `mc` is doing?

**Comment by cstavish** [comment]
> > @klauspost I'm not sure I understand what I'm doing incorrectly here, can you please elaborate? My use-case is to compress a JSON file before storing it into Minio, and have the content-encoding attribute set to gzip, so that when a web browser later downloads the file from Minio, the browser downloads the gzipped file from the server and automatically decompresses it client-side. Although this issue has nothing to do with AWS S3, I have followed the identical pattern successfully in AWS S3.
> 
> So you want to automatically decompress it client side then that's what `mc` is doing?

@harshavardhana I encountered this issue while using `mc mirror` to replicate a bucket from one Minio instance to another. I found that the gzip-compressed JSON files, stored with attribute content-encoding:gzip in the source bucket were corrupted in the destination bucket, specifically in that the files in the destination bucket were plain text, not gzip, and the file size was the same as the source gzipped file (i.e. the file was decompressed and truncated to the original compressed length, resulting in a truncated and corrupted JSON file). I attempted to distill the problem further by replicating the decompress-truncation behavior with a single `mc copy` command, which I could do in mc version RELEASE.2023-11-20T16-30-59Z but not the earlier 2023-08-01 mc release.

**Comment by harshavardhana** [comment]
> @harshavardhana I encountered this issue while using `mc mirror` to replicate a bucket from one Minio instance to another. I found that the gzip-compressed JSON files, stored with attribute content-encoding:gzip in the source bucket were corrupted in the destination bucket, specifically in that the files in the destination bucket were plain text, not gzip, and the file size was the same as the source gzipped file (i.e. the file was decompressed and truncated to the original compressed length, resulting in a truncated and corrupted JSON file). I attempted to distill the problem further by replicating the decompress-truncation behavior with a single `mc copy` command, which I could do in mc version RELEASE.2023-11-20T16-30-59Z but not the earlier 2023-08-01 mc release.

You meant newer one has the problem?

**Comment by cstavish** [comment]
> > @harshavardhana I encountered this issue while using `mc mirror` to replicate a bucket from one Minio instance to another. I found that the gzip-compressed JSON files, stored with attribute content-encoding:gzip in the source bucket were corrupted in the destination bucket, specifically in that the files in the destination bucket were plain text, not gzip, and the file size was the same as the source gzipped file (i.e. the file was decompressed and truncated to the original compressed length, resulting in a truncated and corrupted JSON file). I attempted to distill the problem further by replicating the decompress-truncation behavior with a single `mc copy` command, which I could do in mc version RELEASE.2023-11-20T16-30-59Z but not the earlier 2023-08-01 mc release.
> 
> You meant newer one has the problem?

Yes, that's correct.

**Comment by harshavardhana** [comment]
yeah then its a simpler problem, its mostly `mc` issue

**Comment by harshavardhana** [comment]
This is because of this  

```
if g.withGzip && asciiEqualFold(resp.Header.Get("Content-Encoding"), "gzip") {
```

https://github.com/klauspost/compress/blob/80ba1298e66a8203795532a40de6135f00de2fdf/gzhttp/transport.go#L87

This is causing auto-decompression.

**Comment by harshavardhana** [comment]
Now why did it work in earlier releases? because we never used gzhttp.Transport for S3 API it was a recent introduction - introduced in #4755 a harmless change but introduced this problem.

It looks like gzhttp.Trasnport can't be used with S3 API.

**Comment by klauspost** [comment]
@harshavardhana We can add a response header that indicates the object was stored with a custom `Content-Encoding`.

**Comment by harshavardhana** [comment]
> @harshavardhana Yes, but that also removes server-side compression `mc admin config set ALIAS api gzip_objects=on` - and really doesn't fix the issue.

That feature is never used, I do not see anyone using it since it's not even documented.

```
mc admin config set play/ api 2>&1 | grep gzip_objects
```

Not sure if we even need this on the server side.

**Comment by harshavardhana** [comment]
> Well, then maybe it should be documented, since it is a great feature to reduce bandwidth cost and improve speed for slow connections, and frankly should be used instead of this hack.

We need to support S3 API behavior first, everything else comes after that.

If we enable things underneath that is not part of S3 API such as compression on the wire, then we will break S3 clients and sdks.

All sdks expect a content-length an unending stream won't make sense. That's why I fixed it only for mc GetObject where it's useful due to content-encoding.

Since we are specifically saying that we want an uncompressed stream.
