### ISSUE TITLE
mc mirror and mc ls don't work but mc cp does

### ISSUE THREAD

**Issue by E1v1s** [minio/mc#4775]
## Expected behavior
I can mirror from/to s3 to localhost or minio local storage 
## Actual behavior
mc mirror and mc ls not working but mc cp does

## Steps to reproduce the behavior
i got alias
`mc alias ls`
MyS3
  URL       : https://somebucket.s3.eu-central-1.amazonaws.com
  AccessKey : someaccesskey
  SecretKey : someasecretkey
  API       : s3v4
  Path      : auto

and my version is

mc version RELEASE.2023-11-20T16-30-59Z (commit-id=937b34616f012ad30e1cd6fd61e1da25ff931648)
Runtime: go1.21.4 darwin/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

If i try to copy
`mc cp tmp/1.txt myS3/test` working, directory created
another way with renaming too 
`mc cp  myS3/test/1.txt tmp/11.txt`
but when i try to mirror or list objects
`mc mirror --overwrite  tmp/ myS3/test`
Failed to perform mirroring The specified key does not exist.
Same cmd with debug 
`mc mirror --debug --overwrite  tmp/ myS3/test
 0 B / ? ━┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉━━mc: <DEBUG> GET /test/?location= HTTP/1.1
Host: sport-infra-backups-stage.s3.eu-central-1.amazonaws.com
User-Agent: MinIO (darwin; amd64) minio-go/v7.0.63 mc/RELEASE.2023-11-20T16-30-59Z
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20231128/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20231128T123325Z

mc: <DEBUG> HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 28 Nov 2023 12:33:24 GMT
Server: AmazonS3
X-Amz-Id-2: zprUNXHPo+vtJpz37zSFeKIteSlK4MFHSnLZ2eMDr/WhkZ/+BKG3THERf1EpRtudglkPgRgVNyM=
X-Amz-Request-Id: PZENWMFEHSK2NBYS

173
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1'</Message><Region>eu-central-1</Region><RequestId>PZENWMFEHSK2NBYS</RequestId><HostId>zprUNXHPo+vtJpz37zSFeKIteSlK4MFHSnLZ2eMDr/WhkZ/+BKG3THERf1EpRtudglkPgRgVNyM=</HostId></Error>
0

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Amazon
mc: <DEBUG>  >> Expires: 2024-08-12 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Amazon
mc: <DEBUG>  >> Expires: 2030-08-23 22:21:28 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Starfield Technologies, Inc.
mc: <DEBUG>  >> Expires: 2037-12-31 01:00:00 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Starfield Technologies, Inc.
mc: <DEBUG>  >> Expires: 2034-06-28 17:39:16 +0000 UTC
mc: <DEBUG> Response Time:  188.571707ms

 0 B / ? ━┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉━━mc: <DEBUG> GET /test/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix= HTTP/1.1
Host: sport-infra-backups-stage.s3.eu-central-1.amazonaws.com
User-Agent: MinIO (darwin; amd64) minio-go/v7.0.63 mc/RELEASE.2023-11-20T16-30-59Z
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20231128/eu-central-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20231128T123325Z

mc: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 28 Nov 2023 12:33:24 GMT
Server: AmazonS3
X-Amz-Delete-Marker: true
X-Amz-Id-2: z/mZlF87xFG99ySgilAMVAqJxUcsrNRNgofDecbs4m3W4kv1zJGroW61ujlnzLe7744OuTZKvrQ=
X-Amz-Request-Id: PZEHRA6C1KSK2N7W
X-Amz-Version-Id: null

114
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>test/</Key><RequestId>PZEHRA6C1KSK2N7W</RequestId><HostId>z/mZlF87xFG99ySgilAMVAqJxUcsrNRNgofDecbs4m3W4kv1zJGroW61ujlnzLe7744OuTZKvrQ=</HostId></Error>
0

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Amazon
mc: <DEBUG>  >> Expires: 2024-08-12 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Amazon
mc: <DEBUG>  >> Expires: 2030-08-23 22:21:28 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Starfield Technologies, Inc.
mc: <DEBUG>  >> Expires: 2037-12-31 01:00:00 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Starfield Technologies, Inc.
mc: <DEBUG>  >> Expires: 2034-06-28 17:39:16 +0000 UTC
mc: <DEBUG> Response Time:  158.41141ms

mc: <ERROR> Failed to perform mirroring The specified key does not exist.
 (2) mirror-main.go:548 cmd.(*mirrorJob).monitorMirrorStatus(..)
 (1) difference.go:244 cmd.differenceInternal(..) Tags: [/git/tmp/, https://sport-infra-backups-stage.s3.eu-central-1.amazonaws.com/test/]
 (0) client-s3.go:2442 cmd.(*S3Client).listRecursiveInRoutine(..)
 Release-Tag:RELEASE.2023-11-20T16-30-59Z | Commit:937b34616f01 | Host:MAC-559709 | OS:darwin | Arch:amd64 | Lang:go1.21.4 | Mem:3.8 MiB/15 MiB | Heap:3.8 MiB/7.2 MiB`
and 
`mc ls myS3` just with empty responce
the same with debug
`mc ls myS3 --debug
mc: <DEBUG> GET / HTTP/1.1
Host: sport-infra-backups-stage.s3.eu-central-1.amazonaws.com
User-Agent: MinIO (darwin; amd64) minio-go/v7.0.63 mc/RELEASE.2023-11-20T16-30-59Z
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20231128/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20231128T123440Z

mc: <DEBUG> HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 28 Nov 2023 12:34:40 GMT
Server: AmazonS3
X-Amz-Bucket-Region: eu-central-1
X-Amz-Id-2: gbPRf6dux4ldMKhJs0Fc4Qvmmhn6SBSJKauMsMoiONN4TDigIrYboqFGfHYw+WPguL2LGMzufIfFHHxq3z573w==
X-Amz-Request-Id: VN1FX1DAKSD3TF1N

17f
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1'</Message><Region>eu-central-1</Region><RequestId>VN1FX1DAKSD3TF1N</RequestId><HostId>gbPRf6dux4ldMKhJs0Fc4Qvmmhn6SBSJKauMsMoiONN4TDigIrYboqFGfHYw+WPguL2LGMzufIfFHHxq3z573w==</HostId></Error>
0

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Amazon
mc: <DEBUG>  >> Expires: 2024-08-12 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Amazon
mc: <DEBUG>  >> Expires: 2030-08-23 22:21:28 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Starfield Technologies, Inc.
mc: <DEBUG>  >> Expires: 2037-12-31 01:00:00 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Starfield Technologies, Inc.
mc: <DEBUG>  >> Expires: 2034-06-28 17:39:16 +0000 UTC
mc: <DEBUG> Response Time:  193.743272ms

mc: <DEBUG> GET / HTTP/1.1
Host: sport-infra-backups-stage.s3.eu-central-1.amazonaws.com
User-Agent: MinIO (darwin; amd64) minio-go/v7.0.63 mc/RELEASE.2023-11-20T16-30-59Z
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20231128/eu-central-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20231128T123440Z

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 28 Nov 2023 12:34:42 GMT
Server: AmazonS3
X-Amz-Bucket-Region: eu-central-1
X-Amz-Id-2: 6wPnpS0Q3vRRGpPalGHqaWEENc02wWnF9NM8CI/cY4vR61C+CJdee7zL+gNNYCilEh0OmPnKXTqhyrorPu/DUQ==
X-Amz-Request-Id: VN1FM6ZV9AK8WVTX

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Amazon
mc: <DEBUG>  >> Expires: 2024-08-12 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Amazon
mc: <DEBUG>  >> Expires: 2030-08-23 22:21:28 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Starfield Technologies, Inc.
mc: <DEBUG>  >> Expires: 2037-12-31 01:00:00 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Starfield Technologies, Inc.
mc: <DEBUG>  >> Expires: 2034-06-28 17:39:16 +0000 UTC
mc: <DEBUG> Response Time:  186.444029ms`

My bucket policy is 
`{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Action": "s3:*",
			"Resource": [
				"arn:aws:s3:::sport-infra-backups-stage/*",
				"arn:aws:s3:::sport-infra-backups-stage"
			]
		}
	]
}`
My goal is to sync objects from s3 to minio bucket local storage, but i'm stuck with simple mirror to s3

**Comment by harshavardhana** [comment]
your configuration must only have endpoint not bucketname as part of endpoint

```
URL : https://s3.eu-central-1.amazonaws.com/
AccessKey : someaccesskey
SecretKey : someasecretkey
API : s3v4
Path : auto
```

**Comment by E1v1s** [comment]
Thanks!
