### ISSUE TITLE
unable to delete file in gcs

### ISSUE THREAD

**Issue by sherlant** [minio/mc#4778]
Hi,
 i use minio client and i have a problem with google cloud storage bucket. I want to create/list/remove objects on bucket, all are good expect remove. When i try, i've got this error :
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NotImplemented</Code><Message>A header or query you provided requested a function that is not implemented.</Message><Details>POST ?delete is not implemented for objects.</Details></Error>
```
I can create and list. Anyone can help me ?

**Comment by klauspost** [comment]
As mentioned on Slack, they probably don't implement [DeleteObjects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html)

We don't have any intention of supporting partial S3 implementations.

- thanks for the link you provided: https://cloud.google.com/storage/docs/migrating?hl=en#methods-comparison
