### ISSUE TITLE
mc mirror --watch  执行以后报错

### ISSUE THREAD

**Issue by joh-zhang** [minio/mc#4782]
## Expected behavior
I deployed a minio 5.0.11 cluster in k8s by helm, and I want to continuously synchronize the data of this minio cluster to another minio 5.0.11 cluster of the same version through mc mirror --watch.

## Actual behavior
mc mirror --watch minio-source minio-dest
During synchronization, an error is reported:
mc: <ERROR> Failed to perform mirroring readObjectStart: expect { or n, but found <, error found in #1 byte of ...

## Steps to reproduce the behavior
mc mirror --watch minio-source minio-dest

## mc --version
mc version RELEASE.2023-12-02T02-03-28Z (commit-id=f5f7147b9ec4cf78eb67f1cdc91b63d191852e6a)
Runtime: go1.21.4 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by joh-zhang** [comment]
Is it because minio version 5.0.11 can't support the mc mirror --watch command?

**Comment by joh-zhang** [comment]
I didn't use K8S's load balancer, and the above synchronization operation was done through K8S's SVC exposing the minio port

**Comment by joh-zhang** [comment]
![image](https://github.com/minio/mc/assets/86047608/4a4cb9ad-5891-4ca1-9f63-dd058e64afb5)

**Comment by joh-zhang** [comment]
helm install minio-source --set persistence.enabled=true  --set accessKey=minio --set secretKey=minio123 --set persistence.size=1Gi --set resources.requests.memory=500Mi --set persistence.storageClass=minio-nas --set mode=distributed,replicas=4 .

Here's how I installed the minio cluster

**Comment by joh-zhang** [comment]
helm install minio-source --set persistence.enabled=true --set accessKey=minio --set secretKey=minio123 --set persistence.size=1Gi --set resources.requests.memory=500Mi --set persistence.storageClass=minio-nas --set mode=distributed,replicas=4 .

Here's how I installed the minio cluster
@harshavardhana

**Comment by harshavardhana** [comment]
k8s service export does not support proper event stream payload properly.

You need to use a real load balancer like nginx to get that support.
