### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by USMortality** [minio/mc#4785]
## Expected behavior
No error.

## Actual behavior
mirror command fails:

`mc mirror minio/data/mortality minio/data/mortality-bak --overwrite`

Error:
```
panic: runtime error: integer divide by zero

goroutine 67 [running]:
github.com/minio/minio-go/v7.calculateEvenSplits(0xffffffffffffffff, {{0xc000bb4bd1, 0x4}, {0xc000bb4bd6, 0x23}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
	github.com/minio/minio-go/v7@v7.0.65-0.20231130060928-54e115c40e66/api-compose-object.go:579 +0x138
github.com/minio/minio-go/v7.(*Client).ComposeObject(_, {_, _}, {{0xc000a62475, 0x4}, {0xc000a6247a, 0x27}, {0x0, 0x0}, 0xc0004c4420, ...}, ...)
	github.com/minio/minio-go/v7@v7.0.65-0.20231130060928-54e115c40e66/api-compose-object.go:505 +0x1258
github.com/minio/mc/cmd.(*S3Client).Copy(0xc000352300, {0x1010cde48, 0xc000040f00}, {0xc000bb4bd0, 0x29}, {{0x0, 0x0}, 0x49dda3d, {0x0, 0x0}, ...}, ...)
	github.com/minio/mc/cmd/client-s3.go:1046 +0x7c5
github.com/minio/mc/cmd.copySourceToTargetURL({0x1010cde48, 0xc000040f00}, {0xc0005a42e0, 0x5}, {0xc000a62410, 0x47}, {0xc000bb4bd0, 0x29}, {0x0, 0x0}, ...)
	github.com/minio/mc/cmd/common-methods.go:369 +0x2d5
github.com/minio/mc/cmd.uploadSourceToTargetURL({0x1010cde48, 0xc000040f00}, {{0xc000048168, 0x5}, 0xc000a5e480, {0xc0005a42e0, 0x5}, 0xc000620a80, 0x2, 0x908a3ba, ...}, ...)
	github.com/minio/mc/cmd/common-methods.go:518 +0x25f6
github.com/minio/mc/cmd.(*mirrorJob).doMirror(0xc0000fa000, {0x1010cde48, 0xc000040f00}, {{0xc000048168, 0x5}, 0xc000a5e480, {0xc0005a42e0, 0x5}, 0xc000620a80, 0x2, ...})
	github.com/minio/mc/cmd/mirror-main.go:478 +0x6bd
github.com/minio/mc/cmd.(*mirrorJob).startMirror.func1()
	github.com/minio/mc/cmd/mirror-main.go:782 +0x78
github.com/minio/mc/cmd.(*ParallelManager).addWorker.func1()
	github.com/minio/mc/cmd/parallel-manager.go:105 +0x6b
created by github.com/minio/mc/cmd.(*ParallelManager).addWorker in goroutine 1
	github.com/minio/mc/cmd/parallel-manager.go:94 +0x76
```
## mc --version
```
mc version RELEASE.2023-12-02T02-03-28Z (commit-id=f5f7147b9ec4cf78eb67f1cdc91b63d191852e6a)
Runtime: go1.21.4 darwin/amd64
Copyright (c) 2015-0000 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## System information
Software:

    System Software Overview:

      System Version: macOS 14.1.2 (23B92)
      Kernel Version: Darwin 23.1.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3 days, 3 hours, 4 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,1
      Model Number: MK183LL/A
      Chip: Unknown
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.41.12
      OS Loader Version: 10151.41.12
      Activation Lock Status: Enabled
```

The same happens on Linux CI server.

Any ideas? Thx!

**Comment by klauspost** [comment]
Content Length is not being returned. Presumably the file is pre-compressed, so AWS removes the Content-Length

@vadmeste Similar to our previous discussion. We need to deal with this.

**Comment by USMortality** [comment]
Possibly because here I’m copying from one folder to another in the same bucket, but I have gzip enabled via nginx?!

**Comment by harshavardhana** [comment]
> Possibly because here I’m copying from one folder to another in the same bucket, but I have gzip enabled via nginx?!

If you enable gzip via nginx we won't know the size of the stream. This will not work disable gzip at the nginx layer.
