### ISSUE TITLE
MinIO Client (mc) Version 2023-11-20: No Output When Running `mc version`

### ISSUE THREAD

**Issue by xi-xi-jun** [minio/mc#4793]
**Issue Description**
I encountered an issue with the MinIO client (mc) released on November 20, 2023. When I attempt to execute the `mc version `command, there is no output in the terminal, and the cursor just continuously blinks in the blank space. In contrast, the version information displays normally with the mc client version from 2021.

**Steps to Reproduce**
Use the mc client version from 2023-11-20.
Execute the command in a Linux terminal: `mc version`
Observe that there is no output, only a blinking cursor in the blank space.

**Expected Behavior**
I expect the` mc version` command to display versioninformation as it does in the 2021 version of the mc client.
![image](https://github.com/minio/minio/assets/113566654/e0e08703-0b51-43a2-ad75-b5911771f640)

**Actual Behavior**
After executing` mc version`, there is no output, and the terminal cursor blinks in a blank space.
![image](https://github.com/minio/minio/assets/113566654/22af0814-6c4c-4f4f-870c-93277f7c0115)

**Environment Information**
MinIO Client version: 2023-11-20
Operating System: [linux centos7.6]

**Attempted Resolutions**

Confirmed compatibility between the system environment and mc client
Checked for logs and error messages
Tested in different terminals and Linux distributions
Searched GitHub and MinIO community forums without finding related reports

I recently planned to try out the new version, but for some reason, when I execute the mc command in the new version, the terminal does not provide feedback on the command execution. Is this a bug?

**Comment by xi-xi-jun** [comment]
Thank you very much for suggesting setting the CI=true environment variable before running the mc --help command. This solution was extremely effective in my environment, which includes a CentOS terminal created through VMware and a cloud server. The idea of setting the CI=true variable hadn't occurred to me, and most of the tutorials I found online were for versions before 2022, so this issue was rarely mentioned. I am very grateful for your solution and appreciate your help.

**Comment by harshavardhana** [comment]
It looks your terminal doesn't support some new requirements that our terminal libraries require.

CI=true 

is a good workaround.
