### ISSUE TITLE
What is the principle of mc mirror monitoring local file changes?

### ISSUE THREAD

**Issue by DengLZ** [minio/mc#4805]
## Operating procedures
I execute the command to synchronize the data in the local aa directory to the s3 bucket. I terminated the command after the data synchronization was completed. Then I modified the contents of the /tmp/aaa directory. After 20 minutes I restarted the command. The modifications I made after terminating the command were still synchronized to the s3 bucket.

mc mirror -w --overwrite --remove --preserve /tmp/aa obs_sys-test1/sys-test1/aa

## My Question
I would like to know how the mc client implements this function. Why can only modified information be synced without a full sync.

Is it because the mc client records the status information of local files?
Or the mc client can only detect changes within a period of time?

## mc --version
- (paste output of `mc --version`)
# mc --version
mc version RELEASE.2023-12-23T08-47-21Z (commit-id=c27ddd4adf534e671b3dd629d1ccf2574760c784)

## System information
centos 7.9

**Comment by vadmeste** [comment]
@DengLZ I tried to replicate your setup, modifying a file with an editor will successfully replicate a file. The code uses this library https://github.com/rjeczalik/notify to get notified about changes in a file before replicating them.
