### ISSUE TITLE
mc mirror abs path problem

### ISSUE THREAD

**Issue by zhujing3** [minio/mc#4806]
## Expected behavior

Keep using it the same way

## Actual behavior

1. create some dir/files on local
![image](https://github.com/minio/mc/assets/11979531/08fa1024-7385-43b2-8147-ae5b387daddf)

2. call mirror sync to bucket user1

![image](https://github.com/minio/mc/assets/11979531/ae13308b-9c03-4505-993e-a7268cbae3b1)

3. it's ok use abs path ,but when i touch a new file on local dir
![image](https://github.com/minio/mc/assets/11979531/840ae0ef-6113-470d-aaa8-ce78914e64ce)

![image](https://github.com/minio/mc/assets/11979531/b5b93969-19d8-479e-9564-b1a9d55523ba)

Why are relative paths used instead of absolute paths?

## mc --version
[root@dev203 ccc]# mc -version
mc version RELEASE.2023-12-14T00-37-41Z (commit-id=8da737f8fd63de58dc475bf88eb9e285d206e3ae)
Runtime: go1.21.5 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
[root@dev203 ccc]# 

## System information
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: RELEASE.2023-12-20T01-00-02Z (go1.21.5 linux/amd64)

**Comment by shtripat** [comment]
Resolved through https://github.com/minio/mc/pull/4807
