### ISSUE TITLE
mc mirror exclude option for folders not working

### ISSUE THREAD

**Issue by chenshi5012** [minio/mc#4841]
mc mirror 
--exclude value                    exclude object(s) that match specified object name pattern 

[https://github.com/minio/mc/issues/2343](https://github.com/minio/mc/issues/2343)

check this  , not working..  

## Expected behavior

--exclude  folders  or  folder/*  to mirror unexpect files 

## Actual behavior

--exclude option can only support the  **object name . can not support folders**

## Steps to reproduce the behavior

![image](https://github.com/minio/mc/assets/10794822/01af0002-07a5-4e7e-81b5-e77eb7148020)

## mc --version
- (paste output of `mc --version`)
~
[minio@minio-0 /]$ mc --version
mc version RELEASE.2023-10-12T07-08-21Z (commit-id=5d7d6f70aeb710a2345d58e61cb2e809bf48d58f)
Runtime: go1.19.6 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
[minio@minio-0 /]$
~

**Comment by jiuker** [comment]
fix by https://github.com/minio/mc/pull/4825
