### ISSUE TITLE
mc admin info  TARGET not work

### ISSUE THREAD

**Issue by EtachGu** [minio/mc#4851]
## Expected behavior
mc admin info  TARGET
show the information of alias
## Actual behavior
the specificed bucket is not exist
## mc --version
- (paste output of `mc --version`)
mc.RELEASE.2024-02-16T11-05-48Z

**Comment by EtachGu** [comment]
## solution

choose the match version between minio server and mc

for my case:
minio server Version: 2019-10-12T01:39:57Z then  choose mc [mc.RELEASE.2019-10-09T22-54-57Z](https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2019-10-09T22-54-57Z)

minio server Version: 2019-06-13T01:41:13Z  then choose [mc.RELEASE.2019-06-19T22-39-53Z](https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2019-06-19T22-39-53Z)

**Comment by harshavardhana** [comment]
Please upgrade.
