### ISSUE TITLE
'mc mirror' Error

### ISSUE THREAD

**Issue by joh-zhang** [minio/mc#4860]
## Expected behavior
I deployed a minio 5.0.11 cluster in k8s by helm, and I want to continuously synchronize the data of this minio cluster to another minio 5.0.11 cluster of the same version through mc mirror
## Actual behavior
time mc mirror production test-dest  
...6b30135482bf5a1858a8.info: 44.20 GiB / 44.20 GiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.12 MiB/smc: <ERROR> Unable to list comparison retrying.. Get "http://nm-files-minio.test:9000/root-minio-production/?continuation-token=Y2E5ZDIxNjI3MzBjNmIzMDEzNTQ4MmJmNWExODU4YTguaW5mbw%3D%3D&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=": read tcp 172.18.43.161:58162->10.0.25.225:9000: i/o timeout
...6b30135482bf5a1858a8.info: 44.20 GiB / 44.20 GiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.12 MiB/s 5h55m32s
real	355m32.406s
user	6m54.186s
sys	2m14.512s

## Steps to reproduce the behavior
time mc mirror production test-dest 

## mc --version
mc version RELEASE.2023-12-02T02-03-28Z (commit-id=f5f7147b9ec4cf78eb67f1cdc91b63d191852e6a)
Runtime: go1.21.4 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 https://www.gnu.org/licenses/agpl-3.0.html

## System information
K8S container

**Comment by zveinn** [comment]
From what I can tell this is a network error, the connection timed out after 5+ hours. Are there any other logs to suggest that there might be something else going on ?

**Comment by joh-zhang** [comment]
Thank you for the response, and based on the provided logs, it seems that there are no other indications of a different issue.

Regarding your question about the connection timeout, if a connection times out, the mc command will automatically retry and continue syncing until it eventually completes.
