### ISSUE TITLE
mc du don't display results similar values ​​on the minio console.

### ISSUE THREAD

**Issue by vedricopane** [minio/mc#4879]
## Expected behavior
mc du display results similar values ​​on the minio console.
Example : in console size bucketA = 2 TiB, in mc du size bucketA = 2 TiB

## Actual behavior
mc du display wrong results.
Example : in console size bucketA = 2 TiB, in mc du size bucketA = 11 GiB, sometimes 4 GiB.

## Steps to reproduce the behavior
`mc du alias/bucketA`

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2024-03-09T06-43-06Z (commit-id=1ec55a5178d701b1f4349930632c2b80884b46c0)
Runtime: go1.21.8 linux/amd64

**Comment by harshavardhana** [comment]
Console UI relies on scanner to provide the usage updates - `mc du` calculates what is currently on the namespace. 

If the scanner has to updated the usage yet the information will be lower.

**Comment by vedricopane** [comment]
> Console UI relies on scanner to provide the usage updates - `mc du` calculates what is currently on the namespace.
> 
> If the scanner has to updated the usage yet the information will be lower.

So what can i do to calculate size from mc tools ?
