### ISSUE TITLE
Mirror fails with "Cannot create a file when that file already exists."

### ISSUE THREAD

**Issue by opax7** [minio/mc#4886]
## Expected behavior
Mirror command downloads Bucket contents without error

## Actual behavior
Mirror begins to download contents. At some random point fails with 
```
<ERROR> Failed to copy '<Source>/path'. mkdir <Destination>/path: Cannot create a file when that file already exists.
```

It seems to occur after `mc` performs a stat of sorts. The directory it fails on does not previously exist when the error occurs. However, as `mc` is checking for directories is when a file with the same name as the directory shows up, but the file is not deleted before it can resume. I can see that other files with directory names are created and deleted quickly, but then it suddenly does not delete one, and that is when this error occurs.

### Workaround
If I delete the file, sometimes the same error will occur against the same directory, as `mc` will create the file again and not delete it. However, if I delete the file, then create the directory empty with the same name, it will proceed past the offending directory.

### Setup alias
`mc config host add my_alias https://s3.amazonaws.com $env:AWS_ACCESS_KEY_ID $env:AWS_SECRET_ACCESS_KEY`

### Perform the mirror operation
`mc mirror my_alias\$env:AWS_BUCKET\$path "$downloadDest\$path"`

## mc --version
```
mc version RELEASE.2024-03-13T23-51-57Z (commit-id=2508db9c560c10be0ed2203eaa585134235b6907)
Runtime: go1.21.8 windows/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## System information
Windows 11

**Comment by jiuker** [comment]
`--overwrite`
