### ISSUE TITLE
Debian package for the latest version is not available

### ISSUE THREAD

**Issue by ciffelia** [minio/mc#4887]
## Expected behavior

Debian package `mcli_20240320210729.0.0_amd64.deb` can be downloaded by following instruction in the download page.

https://min.io/download#/agpl-linux

## Actual behavior

The URL in the download page returns 404.

https://dl.min.io/client/mc/release/linux-amd64/mcli_20240320210729.0.0_amd64.deb

## Steps to reproduce the behavior

Click the URL above.

## mc --version

- N/A

## System information

Firefox 124.0.1 on Windows

**Comment by harshavardhana** [comment]
This is fixed manually, we will fix the release process. 

> https://dl.min.io/client/mc/release/linux-amd64/mcli_20240320210729.0.0_amd64.deb

This is not latest release btw. https://dl.min.io/client/mc/release/linux-amd64/mcli_20240325164114.0.0_amd64.deb
