### ISSUE TITLE
No LDAP after minio server upgrade 

### ISSUE THREAD

**Issue by paramazo** [minio/mc#4897]
## Expected behavior
Login via LDAP should work as expected

## Actual behavior
After upgrade Minio via .deb package from RELEASE.2023-03-20T20-16-18Z to RELEASE.2024-04-06T05-26-02Z, the ldap logins do not work anymore

## Steps to reproduce the behavior
Upgrade the version

## mc --version
`Version: RELEASE.2024-04-06T05-26-02Z (go1.21.9 linux/amd64)`

## System information
Debian 11.5

**Comment by harshavardhana** [comment]
> Any known breaking changes to LDAP between the versions i mentioned? 

Yes LDAP DN normalization is a change that has happened however need to know how is the policy mapping associated, have you retried remapping the policies?.

> Where we could get support for our minio instance?

Support subscribe here https://min.io/pricing

**Comment by harshavardhana** [comment]
> You want to receive 48000 $ to get support of your bugs?

Sure why not @paramazo ? - you don't want us to live?

**Comment by harshavardhana** [comment]
@paramazo okay I think there is no reason to help you anymore.
