### ISSUE TITLE
Accept colons in `mc alias` commands

### ISSUE THREAD

**Issue by supriyo-biswas** [minio/mc#4903]
As it stands, there is no differentiation between local paths and remote paths in minio client, which makes it difficult to distinguish commands that are meant to run locally vs. on a remote server.

The workaround I personally use is to add colons in aliases listed in the `~/.mc/config.json`, such as:

```
{
	"aliases": {
		"minio:": {
		    // ...
		}
	}
}
```

Which allows me to do stuff like `mc cp minio:/foo/bar.txt ./`

However, I cannot use the `mc alias set` command to set up aliases with colons, because:

```
$ mc alias set minio: http://localhost:9000 <access key> <secret key>
mc: <ERROR> Invalid alias. Alias `minio:` should have alphanumeric characters such as [helloWorld0, hello_World0, ...] and begin with a letter.
```

I would like to request that such aliases ending with colons be accepted.

I can send in a PR, if desired.

**Comment by harshavardhana** [comment]
Not accepting `:` is on purpose. Please use simple names. This must work with environment values as well, such as

MC_HOST_minio: 

if it works, we can see if we can make this exception.

**Comment by supriyo-biswas** [comment]
Would it be possible to gate this "feature" behind something like `--allow-colon-suffix` or something? I'd really like to have something for my local workflow that differentiates remote paths.

A `:` in environment variables can be technically set, but not from the shell. Hence the request.

```
$ export MC_HOST_minio:=foo
-bash: export: `MC_HOST_minio:=foo': not a valid identifier

$ python -q
>>> import subprocess
>>> subprocess.run(['python3', '-c', 'print(__import__("os").getenv("MC_HOST_minio:"))'], env={'MC_HOST_minio:': 'foo'})
foo
CompletedProcess(args=['python3', '-c', 'print(__import__("os").getenv("MC_HOST_minio:"))'], returncode=0)
```

**Comment by klauspost** [comment]
> `--allow-colon-suffix`

We don't add parameters unless they serve a common, clear purpose. This does not IMO.
