### ISSUE TITLE
`/usr/bin/mc` is not readable by non-root in docker image

### ISSUE THREAD

**Issue by thesuperzapper** [minio/mc#4932]
## Expected behavior

So that users can run the `minio/mc` docker image as a non-root user, the `/usr/bin/mc` file should be readable by non root users.

Users might want to read the file to copy the mc binary, or run a SHA verification.

All other executables in the `/usr/bin` folder are `755` or `555`, the `mc` binary is the only one which is `711`.

## Actual behavior

It is only readable by `root`.

## Steps to reproduce the behavior

1. Run `docker run -it --entrypoint /bin/bash minio/mc:RELEASE.2024-04-29T09-56-05Z`
2. Run `ls -l /usr/bin`
3. Observe the following line: `-rwx--x--x 1 root root 25296896 Apr 29 17:33  mc`

## mc --version

```
mc version RELEASE.2024-04-29T09-56-05Z (commit-id=5b7b2223717a32ff01d63d57c2d040a719ca581e)
Runtime: go1.21.9 linux/arm64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## System information

Docker

**Comment by thesuperzapper** [comment]
@harshavardhana can we try and support a non-root container version at least?

Many organizations won't let you run root containers.

**Comment by harshavardhana** [comment]
@thesuperzapper just deploy it in k8s with relevant securityContext, treating containers like OS and having /etc/passwd is not our goal. 

You specify your config via k8s secrets `mc --config-dir` or via ENV `MC_CONFIG_DIR=/tmp/mymc`
