### ISSUE TITLE
mc cp bug

### ISSUE THREAD

**Issue by cnsino** [minio/mc#4933]
## Expected behavior （Copy to code.zip）
`mc cp -r minio/assets/asset-20240425082735/abc.zip /asset-20240425082735/code.zip && cd /asset-20240425082735 && unzip code.zip `
## Actual behavior
However, the final copied path is:/asset-20240425082735/code.zip/abc.zip
## mc --version
- RELEASE.2024-05-09T17-04-24Z (commit-id=fdb36acbb1d793b6cca622a55e6292f0d52309f0)
## System information
`minio/assets/asset-20240425082735/abc.zip` ->  `asset-20240425082735/code.zip/abc.zip`

**Comment by klauspost** [comment]
S3 has no concept of directories, so `minio/assets/asset-20240425082735/abc.zip` is a *prefix*, which can return many results. So we cannot just write it to a single file.

Either way we cannot change this behavior.
