### ISSUE TITLE
An error occurred with mc mirror/cp: read: connection reset by peer.

### ISSUE THREAD

**Issue by xigua88-66** [minio/mc#4936]
I have saved some folder data in a Huawei Cloud OBS bucket, which includes files such as .git, index, .idea, and .DS_Store. When I use mc to synchronize the folder from the bucket to my local system, an error is reported. I have retried several times, and each time the error occurs with the .DS_Store file, ruling out network issues. Similarly, I have encountered this problem with these hidden files: .git, .idea, .git/index, .DS_Store. Below is an example of the error details, where the file that caused the error is .DS_Store.

I have tried both the mirror and cp commands, and both failed at the .DS_Store file.

This is the version information of mc."
[root@7e84ce8349cd tmp]# mc -v
mc version RELEASE.2023-09-13T23-08-58Z (commit-id=e561bc770e9ba6659a13a094e08a530a9685748c)
Runtime: go1.21.1 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

[root@7e84ce8349cd /]# mc mirror minio_center/obs-isf/model_warehouse_tmp/travel_graded_alarmV1.0/plugins/t_b_graded_alarm /tmp/travel_graded_alarmV1.0/t_b  --overwrite --debug
mc: <DEBUG> GET /obs-isf/?location= HTTP/1.1
Host: obs.cn-north-4.myhuaweicloud.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.63 mc/RELEASE.2023-09-13T23-08-58Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20240511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240511T081132Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 211
Connection: keep-alive
Content-Type: application/xml
Date: Sat, 11 May 2024 08:15:56 GMT
Server: OBS
X-Amz-Id-2: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSyXtPIRj+hARZJXaM1B4eAoJ5yrMOXb
X-Amz-Request-Id: 0000018F66B913CC44CB40B908B93F0D
X-Reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc

mc: <DEBUG> Response Time:  233.50212ms

mc: <DEBUG> HEAD /obs-isf/model_warehouse_tmp/travel_graded_alarmV1.0/plugins/t_b_graded_alarm HTTP/1.1
Host: obs.cn-north-4.myhuaweicloud.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.63 mc/RELEASE.2023-09-13T23-08-58Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20240511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240511T081132Z

mc: <DEBUG> HTTP/1.1 404 Not Found
Connection: close
Date: Sat, 11 May 2024 08:15:56 GMT
Server: OBS
X-Amz-Error-Code: NoSuchKey
X-Amz-Error-Detail-Key: model_warehouse_tmp/travel_graded_alarmV1.0/plugins/t_b_graded_alarm
X-Amz-Error-Message: The specified key does not exist.
X-Amz-Id-2: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCS2lmikmhi1T3Fl8rDTrHb69r2NbUyeF
X-Amz-Request-Id: 0000018F66B9143E44CB40B908B93F12
X-Reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc
Content-Length: 0

mc: <DEBUG> Response Time:  28.793045ms

mc: <DEBUG> GET /obs-isf/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&max-keys=1&prefix=model_warehouse_tmp%2Ftravel_graded_alarmV1.0%2Fplugins%2Ft_b_graded_alarm%2F HTTP/1.1
Host: obs.cn-north-4.myhuaweicloud.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.63 mc/RELEASE.2023-09-13T23-08-58Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20240511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240511T081132Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1084
Connection: keep-alive
Content-Type: application/xml
Date: Sat, 11 May 2024 08:15:56 GMT
Server: OBS
X-Amz-Bucket-Region: cn-north-4
X-Amz-Id-2: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSr+kBlGGzPCstEfWvWIWJrw/awF4e6J
X-Amz-Request-Id: 0000018F66B914DE44CCEA4C143274BE
X-Reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc

mc: <DEBUG> Response Time:  168.980267ms

 0 B / ? ━┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉━━mc: <DEBUG> GET /obs-isf/?continuation-token=VjItQUFBQUFnQUFBQUFBQUFCbEFBQUFBUUFBQUFuMnpGOEFyNStEQWV2bXg3ME1ZL2x4azNONTN0UkF3cVc2d09kQkFBQUFBQUVBQUFFQUFBQUFBQUFBWG5INDNDTWVTMWI5eG9Vbi9pU0djQzJuSk5aMnQvMnVmYWVXalZEVGNZL1V6TzRKdmcvZmt2eVRTanlEMTkrdDQreHVjcXRzMTVZSGh1c3p2b1ZVdzEzSlVQbDU4UkN1Rnk0d0cxRDlxS3hjdlFEcWxRQkdENHFHWlg5ZGlhcz0%3D&delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&max-keys=1&prefix=model_warehouse_tmp%2Ftravel_graded_alarmV1.0%2Fplugins%2Ft_b_graded_alarm%2F HTTP/1.1
Host: obs.cn-north-4.myhuaweicloud.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.63 mc/RELEASE.2023-09-13T23-08-58Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20240511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240511T081132Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1213
Connection: keep-alive
Content-Type: application/xml
Date: Sat, 11 May 2024 08:15:56 GMT
Server: OBS
X-Amz-Bucket-Region: cn-north-4
X-Amz-Id-2: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSUj6NiaQGwJfE2DlSn9O87a7dfFKEh8
X-Amz-Request-Id: 0000018F66B9150344CCEA4C143274C0
X-Reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc

mc: <DEBUG> Response Time:  28.463518ms

mc: <DEBUG> GET /obs-isf/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=model_warehouse_tmp%2Ftravel_graded_alarmV1.0%2Fplugins%2Ft_b_graded_alarm%2F HTTP/1.1
Host: obs.cn-north-4.myhuaweicloud.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.63 mc/RELEASE.2023-09-13T23-08-58Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20240511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240511T081132Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 6908
Connection: keep-alive
Content-Type: application/xml
Date: Sat, 11 May 2024 08:15:56 GMT
Server: OBS
X-Amz-Bucket-Region: cn-north-4
X-Amz-Id-2: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSGl8eId6YGs4Nu+SgoDvo0icNJCTL7f
X-Amz-Request-Id: 0000018F66B9151F44CCEA4C143274C1
X-Reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc

mc: <DEBUG> Response Time:  57.572566ms

 6.00 KiB / 6.00 KiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.78 KiB/smc: <DEBUG> GET /obs-isf/?continuation-token=VjItQUFBQUFnQUFBQUFBQUFCbEFBQUFBUUFBQUFuMnpGOEFyNStEQVI0RmV0V1RPNCtNK2gwaTFvTGdLU0hNcFJvV0FBQUFBQUVBQUFFQUFBQUFBQUFBYUlKeHhQaTd4UXAzTFdueXpTTGZBb0JFZk9EYmM5WGpWbXlkUndac3NHbHpjdm5JalV3cEw5bVp6UjZneTNkb0VaL2M4MjkyRUprVDJnZXpDaWlnNXc3V3dnZVM3c3NINkxuSzVGdVdVcHRFUUU2WU9rQXVFSmptNFhzZTB0bFlobU5xUHBzTERISHM%3D&delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&max-keys=1&prefix=model_warehouse_tmp%2Ftravel_graded_alarmV1.0%2Fplugins%2Ft_b_graded_alarm%2F HTTP/1.1
Host: obs.cn-north-4.myhuaweicloud.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.63 mc/RELEASE.2023-09-13T23-08-58Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20240511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240511T081132Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1430
Connection: keep-alive
Content-Type: application/xml
Date: Sat, 11 May 2024 08:15:56 GMT
Server: OBS
X-Amz-Bucket-Region: cn-north-4
X-Amz-Id-2: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSXGp0+qDvZNNwMPXv32RYr7FcRhFwMR
X-Amz-Request-Id: 0000018F66B9153F44CCEA4C143274C2
X-Reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc

mc: <DEBUG> Response Time:  63.504194ms

...s/t_b_graded_alarm/.DS_Store: 6.00 KiB / 6.00 KiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.40 KiB/smc: <ERROR> Failed to copy `http://obs.cn-north-4.myhuaweicloud.com/obs-isf/model_warehouse_tmp/travel_graded_alarmV1.0/plugins/t_b_graded_alarm/.DS_Store`. Head "http://obs.cn-north-4.myhuaweicloud.com/obs-isf/model_warehouse_tmp/travel_graded_alarmV1.0/plugins/t_b_graded_alarm/.DS_Store": read tcp 172.23.0.2:34144->49.4.112.113:80: read: connection reset by peer
 (3) mirror-main.go:506 cmd.(*mirrorJob).monitorMirrorStatus(..) Tags: [http://obs.cn-north-4.myhuaweicloud.com/obs-isf/model_warehouse_tmp/travel_graded_alarmV1.0/plugins/t_b_graded_alarm/.DS_Store]
 (2) common-methods.go:563 cmd.uploadSourceToTargetURL(..) Tags: [http://obs.cn-north-4.myhuaweicloud.com/obs-isf/model_warehouse_tmp/travel_graded_alarmV1.0/plugins/t_b_graded_alarm/.DS_Store]
 (1) common-methods.go:253 cmd.getSourceStream(..) Tags: [minio_center, http://obs.cn-north-4.myhuaweicloud.com/obs-isf/model_warehouse_tmp/travel_graded_alarmV1.0/plugins/t_b_graded_alarm/.DS_Store]
 (0) common-methods.go:253 cmd.getSourceStream(..)
 Release-Tag:RELEASE.2023-09-13T23-08-58Z | Commit:e561bc770e9b | Host:7e84ce8349cd | OS:linux | Arch:amd64 | Lang:go1.21.1 | Mem:5.9 MiB/24 MiB | Heap:5.9 MiB/15 MiB
...s/t_b_graded_alarm/.DS_Store: 6.00 KiB / 6.00 KiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.40 KiB/s 4s[

**Comment by xigua88-66** [comment]
I attempted to use the rclone command and found that the same file was the source of the error.
![image](https://github.com/minio/mc/assets/54090607/a2e8258d-93fb-40de-b4de-85507101e2fa)

**Comment by klauspost** [comment]
Seems like "Huawei Cloud OBS" crashes. I can't really see what we can do here.
