### ISSUE TITLE
mc ls --json does not return valid JSON or JSON lines

### ISSUE THREAD

**Issue by nirs** [minio/mc#4941]
## Expected behavior

`--json` argument return valid JSON that can be consumed by a JSON parser.

Or based on the help message:

    --json    enable JSON lines formatted output

return [JSON lines](https://jsonlines.org/), where every line is a valid JSON document that can be parsed with JSON parser.

Example valid json lines outoput:

```
{"status": "success", "type": "folder", "lastModified": "2024-05-23T14:19:29+03:00", "size": 0, "key": "odrbucket-69b196796bb1/", "etag": "", "url": "https://s3-openshift-storage.apps.xxx.example.com/", "versionOrdinal": 1}
{"status": "success", "type": "folder", "lastModified": "2024-05-23T14:03:14+03:00", "size": 0, "key": "first.bucket/", "etag": "", "url": "https://s3-openshift-storage.apps.xxx.example.com/", "versionOrdinal": 1}
```

This is trivial to parse with any JSON parser - line by line.

In both cases make it easy to use mc by another program.

## Actual behavior

The command returns data not in JSON or JSON lines format:

```
$ mc ls xxx --insecure --json
{
 "status": "success",
 "type": "folder",
 "lastModified": "2024-05-23T14:19:29+03:00",
 "size": 0,
 "key": "odrbucket-69b196796bb1/",
 "etag": "",
 "url": "https://s3-openshift-storage.apps.xxx.example.com/",
 "versionOrdinal": 1
}
{
 "status": "success",
 "type": "folder",
 "lastModified": "2024-05-23T14:03:14+03:00",
 "size": 0,
 "key": "first.bucket/",
 "etag": "",
 "url": "https://s3-openshift-storage.apps.xxx.example.com/",
 "versionOrdinal": 1
}
```

## Steps to reproduce the behavior

    mc ls ALIAS --json

    $ mc ls xxx --insecure --json | python -m json.tool
    Extra data: line 2 column 1 (char 219)    

## mc --version

```
$ mc --version
mc version RELEASE.2022-08-11T00-30-48Z (commit-id=c2c2ab4299bbb243c55644984392f1c39af499cf)
Runtime: go1.18.5 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## System information

Fedora 39

**Comment by harshavardhana** [comment]
> $ mc ls xxx --insecure --json | python -m json.tool
> Extra data: line 2 column 1 (char 219)

python json.tool doesn't support json lines use sensible tools like `jq`

**Comment by harshavardhana** [comment]
> This is trivial to parse with any JSON parser - line by line.

No that is wrong. 

You expect a line after `{}` each such entries. Again use sensible implementations like Go's `json.NewDecoder`, `jq` and many others.

**Comment by nirs** [comment]
@harshavardhana mc does not generate jsonlines output, try to validate the output here:
https://jsonlines.org/validator/

The fact that jq accept the output does not make it valid.

**Comment by nirs** [comment]
Here is example validation of mc output:
![Screenshot from 2024-05-23 23-52-55](https://github.com/minio/mc/assets/395026/01d85bdb-20fc-40de-b211-6983b289c0a5)

**Comment by harshavardhana** [comment]
> The fact that jq accept the output does not make it valid.

Use `mc` if you can, if you can't you can use other tools.

**Comment by harshavardhana** [comment]
> Here is example validation of mc output: ![Screenshot from 2024-05-23 23-52-55](https://private-user-images.githubusercontent.com/395026/333337959-01d85bdb-20fc-40de-b211-6983b289c0a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTgyNjQsIm5iZiI6MTcxNjQ5Nzk2NCwicGF0aCI6Ii8zOTUwMjYvMzMzMzM3OTU5LTAxZDg1YmRiLTIwZmMtNDBkZS1iMjExLTY5ODNiMjg5YzBhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMDU5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjI0MWQwMDgzZGUwNzk4ODAwMzc2YTM0ODBkNWNjYjE0YTgyNjhlODBhOWQzOWQ0NTY2YTNiNDhkMjc5M2Q5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dJ9TpNlMKOEII2o-E_GPa7r5ycURQSeoe8jpG323Vhg)

Their validator is BS. It thinks a perfectly valid JSON output via `jq`, picked from their own docs, is apparently wrong.

![image](https://github.com/minio/mc/assets/622699/8f38a8bf-2707-4dfa-a6b5-72281114cf87)

![image](https://github.com/minio/mc/assets/622699/5b52aaa1-2e1c-4e68-a650-891cf992e391)

**Comment by klauspost** [comment]
Redirect the output to get one object per line. When printing to the console it will format it.
