### ISSUE TITLE
`mc rm --dryrun  ...` fails while the help menu and the doc lists the option as `--dryrun`

### ISSUE THREAD

**Issue by ebozduman** [minio/mc#4956]
## Expected behavior
The working option name is `--fake`, not `--dryrun`, but the doc and the command help menu lists the option as `--dryrun`
Which one is the correct one? 
Assuming the implementation is correct, then the doc and the command help menu needs to be updated.
Otherwise, the implementation needs to be fixed.

## Actual behavior
When `mc rm --dryrun ...` option is used, remove operation fails and the remove command help menu shows up, which lists the option as `--dryrun`.
However, the command runs successfully with `--fake` option.

`mc rm --fake...` command output is:
```
$ mc rm --fake play/mybucket/
DRYRUN: Removing `play/mybucket/`.
```
The working option is `--fake` but the output shows `DRYRUN`.
I guess it is better to match the option name and what is called in the output, IMHO.

## Steps to reproduce the behavior
Run `mc rm` command with `--dryrun` and `--fake options.

## mc --version
$ mc  -v
mc version RELEASE.2024-06-10T16-44-15Z (commit-id=7a0a8f54d901fe3ee7b8854347025f54ce3ebbfc)
Runtime: go1.22.4 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by klauspost** [comment]
`-dry-run` with a dash. https://min.io/docs/minio/linux/reference/minio-mc/mc-rm.html#mc.rm.-dry-run
