### ISSUE TITLE
It is recommended to add a failure retry function to the mc cp subcommand.

### ISSUE THREAD

**Issue by DengLZ** [minio/mc#4958]
## Expected behavior
Use command: mc cp -r cos/${bucket1_name}/${DIR}/ obs/${bucket2_name}/${DIR}/
To copy data, the following error message appears for individual files during the copy process
"mc: <ERROR> Failed to copy `https://cos.ap-beijing.myqcloud.com//${bucket1_name}/${DIR}/${object_file}`. read tcp ${IP1}:${PORT1}->${IP2}:443: read: connection reset by peer"
After the copy fails, the mc client does not copy the failed file again. Can the retry parameter be added to the mc cp subcommand?

## Steps to reproduce the behavior
When copying a large number of files, an error message appears. This problem is not easy to reproduce.
read: connection reset by peer
## mc --version
mc version RELEASE.2024-03-30T15-29-52Z (commit-id=9f8147bf0e037730077a1b3baef25e53181099b0)
Runtime: go1.21.8 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
centos7.9

**Comment by hikarika** [comment]
seems there is a default newRetryTimer channel in "github.com/minio/minio-go/v7" api.go#637 for almost every http method except certain method

![image](https://github.com/minio/mc/assets/43913604/f639952a-5374-4d86-8a79-7becbeff2080)

**Comment by zveinn** [comment]
The `mc cp` command does have a retry mechanism. It actually uses the newRetryTimer you mentioned above. It just has a limit to how many tries it will do. 

I will not print every try, rather just the final failure.

**Comment by DengLZ** [comment]
I understand thanks for replying！
