### ISSUE TITLE
mc diff returns inconsistent result

### ISSUE THREAD

**Issue by taind772** [minio/mc#4968]
## Expected behavior
mc diff A B ~ mc diff B A

## Actual behavior
![image](https://github.com/minio/mc/assets/49815011/6b7175ec-2bcb-4c31-8ae2-00dc30cbb407)

## Steps to reproduce the behavior
- Mirror some files from a server to S3
- Make some changes
- Diff

![image](https://github.com/minio/mc/assets/49815011/8a1443c2-251a-444c-8fd4-4b86b5221321)

## mc --version
```
mc version RELEASE.2024-06-24T19-40-33Z (commit-id=3548007d5bd1ba8e2ed98f35d95c4776dd9a7ff9)
Runtime: go1.22.4 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```
## System information
A container based on [minio/mc:RELEASE.2024-06-24T19-40-33Z](https://hub.docker.com/layers/minio/mc/RELEASE.2024-06-24T19-40-33Z/images/sha256-a5a442284b7832f85ae997d1e854d8e2ae70ed38a5293360bd5cd54799cb6bac?context=explore) running in Kubernetes (linux).

```
bash-5.1# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.4 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.4 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
```

S3 backend: Ceph v17, API: s3v4

**Comment by klauspost** [comment]
`diff: 7 is differInAASourceMTime, meaning the destination returned a modtime with either regular modtime or `X-Amz-Meta-Mm-Source-Mtime`, that is earlier than the source. So parameter order matters:

```
λ mc diff --json play/testbucket/prefix ./prefix/
{
 "status": "success",
 "first": "https://play.min.io/testbucket/prefix/file.txt",
 "second": "\\prefix\\file.txt",
 "diff": 7
}

λ mc diff --json ./prefix/ play/testbucket/prefix

λ

```
