### ISSUE TITLE
mc find --metadata can't query Chinese

### ISSUE THREAD

**Issue by KirigiriSuzumiya** [minio/mc#4997]
## Expected behavior
```
# query Chinese value in metadata
mc find --metadata mykey=汉字 myhost
```
want to get correct object
## Actual behavior

works well when query none-chinese value.

But returns nothing when value contains chinese

## Steps to reproduce the behavior

I know that chinese is not supported in metadata, so I upload it in this way:
```
self.s3_cli.upload_file(file_path, self.config.bkt, key, 
                                    Callback=self.__callbackFunc,
                                    ExtraArgs={'Metadata': metadata})
```
while metadata is a dict(), generated by:
```
        out_dict = {k: urllib.parse.quote(v) for k, v in out_dict.items()}
```
after uploaded, Chinese is shown correctly at minio WebUI.
but  I can't query it using `mc find --metedata`

## mc --version
- (paste output of `mc --version`)
```
mc version RELEASE.2024-07-22T20-02-49Z (commit-id=58c42bc91bbab04e4073bd8d018b0420ccb21591)
Runtime: go1.22.5 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

**Comment by romanchechyotkin** [comment]
Hello, i put objec with your key, then i did ```find``` command and i got it
![image](https://github.com/user-attachments/assets/f0f1ba09-20e1-4b00-8cc1-be1b08ec5c38)
![image](https://github.com/user-attachments/assets/8d857c75-af9b-4118-9d5a-6d60f3717bc3)

**Comment by KirigiriSuzumiya** [comment]
Thanks for quick response! Maybe there is something getting wrong with terminal encoding format? BTW my terminal is in UTF-8, would you mind show me yours? Then I can have a try again. @romanchechyotkin

**Comment by romanchechyotkin** [comment]
The second screenshot, how you can see, my windows terminal cant print chinese characters, but anyway it works for finding objects with key where were those characters

**Comment by KirigiriSuzumiya** [comment]
this is my case, I have no idea what's going on.

![2024-07-29_15-24](https://github.com/user-attachments/assets/c66ec019-8518-44a0-bee0-9ef07e82527e)

![2024-07-29_15-25](https://github.com/user-attachments/assets/4dbe2462-d5c0-4be8-a597-0ebabee8d50f)

**Comment by klauspost** [comment]
My best guess is that the values have different encoding and therefore doesn't match.

#5006 runs both returned results and the regex through NFC normalization.
