### ISSUE TITLE
mc admin service stop not in top level command help

### ISSUE THREAD

**Issue by feorlen** [minio/mc#5009]
## Expected behavior

`mc admin service` should show help text for `stop` along with the other options

## Actual behavior

`mc admin service` only has `restart` and `unfreeze`, must do `mc admin service stop` to get help text for `stop`

## Steps to reproduce the behavior

```
./mc --dp admin service
NAME:
  mc admin service - restart, stop and unfreeze a MinIO cluster

USAGE:
  mc admin service COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  restart   restart a MinIO cluster
  unfreeze  unfreeze S3 API calls on MinIO cluster
```
```
./mc --dp admin service stop
NAME:
  mc admin service stop - stop a MinIO cluster

USAGE:
  mc admin service stop TARGET
```

## mc --version
- dev build 
```
$ go install -v github.com/minio/mc@master
go: downloading github.com/minio/mc v0.0.0-20240806014527-3cb570ff5632
```

## System information

```
Darwin Andreas-MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64
```

**Comment by harshavardhana** [comment]
Yes, it is on purpose, @feorlen. Once `mc admin service stop` is invoked, there is no way to start the service back remotely. 

To avoid "fat finger" mistakes, it is undocumented and doesn't need to be documented.

**Comment by feorlen** [comment]
@harshavardhana should its command line docs be removed entirely then?
