### ISSUE TITLE
mc mirror --watch doesn't replicate site replication events

### ISSUE THREAD

**Issue by the-glu** [minio/mc#5021]
## Expected behavior

`mc mirror --watch` is supposed to watch and copy files as soon as they arrive.

When having two minio cluster with site replication, only modification on the cluster where mc mirror is connected are replicated. Modifications on the second cluster are not replicated through mc mirror.

## Actual behavior

![image](https://github.com/user-attachments/assets/b03a0a73-8095-4aed-9326-9c96f0d9e0d2)

In that scenario, uploading a file on cluster A lead to file present on cluster A, B and C.
Uploading a file on cluster B lead to file present on cluster A and B.

## mc --version

mc version RELEASE.2024-06-12T14-34-03Z (commit-id=e7c9a733c680fe62066d24e8718f81938b4f6606

(minio servers, both source and target: minio version RELEASE.2024-06-13T22-53-53Z)

**Comment by harshavardhana** [comment]
mc mirror has nothing to do with server side behavior
