### ISSUE TITLE
Windows arms release

### ISSUE THREAD

**Issue by gedw99** [minio/mc#5035]
would it be possible to release a windows arm64 version ?

https://dl.min.io/client/mc/release/ does not have it and thats where I normally grab it from.

But goreleaser seems to have it in this repo.

Windows on ARM is really a thing there days, especially with the new Qualcomm hardware partnership and Surface hardware.

**Comment by harshavardhana** [comment]
Just build it yourself. `go install github.com/minio/mc@latest`

**Comment by harshavardhana** [comment]
No sir we won't be building binaries, source is available please compile it yourself.
