### ISSUE TITLE
The mc rm command lacks an explanation for the --purge parameter.

### ISSUE THREAD

**Issue by cobolbaby** [minio/mc#5063]
## Actual behavior

I found that `mc rm --force` occasionally fails to delete some empty directories; only by adding --purge can they be removed. However, there is no related explanation in mc rm --help.

## mc --version

```
mc version RELEASE.2024-10-08T09-37-26Z (commit-id=cf128de2cf42e763e7bd30c6df8b749fa94e0c10)
Runtime: go1.22.8 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

**Comment by prakashsvmx** [comment]
The flag is hidden and not to be used without guidance from MinIO engineers.
