### ISSUE TITLE
mc version mc.RELEASE.2024-10-08T09-37-26Z download is missing for linux-arm and other

### ISSUE THREAD

**Issue by Tob1as** [minio/mc#5071]
The current version [mc.RELEASE.2024-10-08T09-37-26Z](https://github.com/minio/mc/releases/tag/RELEASE.2024-10-08T09-37-26Z) is missing in https://dl.min.io/client/mc/release/linux-arm/ for download.  Also for mips64 and s390x. For amd64 and arm64 the version is available.

**Comment by harshavardhana** [comment]
We have stopped building arm32 builds, compile from source please.
