### ISSUE TITLE
upgrade the api version to S3v4 on aarch64 architecture

### ISSUE THREAD

**Issue by clcc2019** [minio/mc#5088]
## Expected behavior
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/a9786d3f-b8de-4059-b312-9f50f321ee48">

## mc --version

mc version DEVELOPMENT.2024-10-29T15-34-59Z (commit-id=9f4659884dd45dca726ba38ee6bfacb2bf776eb8)
Runtime: go1.22.9 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by clcc2019** [comment]
The issue lies in the incorrect password. The default v4 signature fails, but when specifying the API version, the host can still be added successfully despite the incorrect password.

**Comment by klauspost** [comment]
Open an issue, where you actually *describe* what your issue is, instead of just pasting a random screenshot and trying to have us guess what the issue is.  Commenting with "hints" is not really useful.
