### ISSUE TITLE
mc admin accesskey: --expiry-duration accepts only time units (up to hours)

### ISSUE THREAD

**Issue by trilga** [minio/mc#5100]
## Expected behavior
As per documentation, --expiry-duration should accept also days (--expiry-duration)

## Actual behavior
When passing 30d, the parameter is ignored:
```
mc admin accesskey create myminio/ minio_user --expiry-duration 30d
Access Key: PYWZXA0Y4H33NZFQ9TXJ
Secret Key: uWXlQJ24YtoXrNi0Hp+hjxuVzuXbJpLcAbjTGERc
Expiration: NONE
Name:
Description:
```

Though it works well with hours, for example:
```
mc admin accesskey create myminio/ minio_user --expiry-duration 30h
Access Key: T2FZHTFM82DL0Q2IARB7
Secret Key: fMypggp3wDkHiMChNR+FLlq1Ay3zaNyFBQXgpcjZ
Expiration: 2024-12-31 19:37:16 +0000 UTC
Name:
Description:
```

## Steps to reproduce the behavior
Run `mc admin accesskey create myminio/ minio_user --expiry-duration 30d`

## mc --version
- mc version RELEASE.2024-10-08T09-37-26Z (commit-id=cf128de2cf42e763e7bd30c6df8b749fa94e0c10)
Runtime: go1.22.8 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by harshavardhana** [comment]
You specify 720hr, 30d is not a time.Duration supported format - thats why the flag says `--expiry-duration`

**Comment by harshavardhana** [comment]
> As per documentation, --expiry-duration should accept also days (--expiry-duration)

where is it documented?

**Comment by trilga** [comment]
@harshavardhana https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-accesskey-create.html#command-mc.admin.accesskey.create:~:text=expiry%2Dduration.-,%2D%2Dexpiry%2Dduration,-Optional

**Comment by harshavardhana** [comment]
> @harshavardhana https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-accesskey-create.html#command-mc.admin.accesskey.create:~:text=expiry%2Dduration.-,%2D%2Dexpiry%2Dduration,-Optional

@ravindk89 we need to fix this, valid time units for duration are always

```
Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
```

**Comment by ravindk89** [comment]
https://github.com/minio/docs/commit/fff6e87c037c4f2532de3a21d21394c5b086721b
