### ISSUE TITLE
Add documentation about HTTP Proxy support

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#685]

**Comment by harshavardhana** [comment]
http://golang.org/src/net/http/transport.go?s=4805:4862#L126 - here we go

**Comment by harshavardhana** [comment]
Golang already supports this properly with HTTP_PROXY bash variable, so we are good with that. Closing this

**Comment by felixbuenemann** [comment]
@harshavardhana Have you actually tested it?

I haven't had any luck with this and [tinyproxy](https://www.banu.com/tinyproxy/) on port 8888:

```
http_proxy=http://127.0.0.1:8888 mc ls s3/my-bucket-name
```

The tinyproxy log shows no requests through the proxy.

If I use the same environment var with `curl` or `rclone` (also go net/http-based), I can see that the proxy is used. I also tried with `https_proxy` and the upcased variants.

One thing I did see in the [rclone code](https://github.com/ncw/rclone/blob/b35123ba48efacdb1c663a216a44b8728ad0400a/fs/http.go#L102), is that they are passing in `http.ProxyFromEnvironment` as a proxy function. Maybe something similar needs to be done in the minio client.

**Comment by harshavardhana** [comment]
It could be a regression @felixbuenemann we will fix it.

**Comment by felixbuenemann** [comment]
Thanks, I've tested with the latest `mc` from homebrew:

```
Version: 2016-12-09T18:23:19Z
Release-tag: RELEASE.2016-12-09T18-23-19Z
Commit-id: 64166319eeaed70cdb0e1a24ea97416a9600052e
```

**Comment by vadmeste** [comment]
> Thanks, I've tested with the latest mc from homebrew:
> 
> Version: 2016-12-09T18:23:19Z
> Release-tag: RELEASE.2016-12-09T18-23-19Z
> Commit-id: 64166319eeaed70cdb0e1a24ea97416a9600052e

@felixbuenemann, the last master fixed the issue, can you test again ?

**Comment by felixbuenemann** [comment]
@vadmeste I installed the latest version via `go get -u github.com/minio/mc` and with that version proxy support is working fine. Thanks for the quick fix!

**Comment by zicklag** [comment]
I am behind a Squid proxy that requires authentication and I can't get it to go through. My environment variable is in the format: `http_proxy=http://user:password@server:port`. Is this unsupported?

**Comment by AndyBan** [comment]
Yes the you can only give host:port in the proxy definition:

http_proxy=server:port

**Comment by harshavardhana** [comment]
This is a Go net/http limitation @zicklag @AndyBan please open issue upstream
