### ISSUE TITLE
本語

### ISSUE THREAD

**Issue by mattn** [minio/mc#817]
What is `本語`? If you mean `Japanese`, it's `日本語` not `日本`.

**Comment by harshavardhana** [comment]
> What is 本語? If you mean Japanese, it's 日本語 not 日本.

Is it Japanese? i thought it was chinese. I picked it up from one of the Go's examples i think.

**Comment by mattn** [comment]
ah, sorry. there is meaning of chinese language for `本語`.

**Comment by harshavardhana** [comment]
> ah, sorry. there is meaning of chinese language for 本語.

No problem.
