### ISSUE TITLE
Low priority: Name collision with Midnight Commander

### ISSUE THREAD

**Issue by richarson** [minio/mc#873]
Just wanted to point out that Midnight Commander (http://www.midnight-commander.org/) also uses mc as its binary name (which is not that bad because I can rename Minio client's binary) and older versions (e.g. as found on CentOS 5) also use ~/.mc as config directory (which could be a problem but it's mostly messy).

Is there any chance of renaming Minio's client, or have some switch at compile time?
Or maybe permanently pointing it to a different config file?

TIA

Note: I've been using Midnight Commander extensively for 10 years but I'm in no way affiliated with the project.

**Comment by abperiasamy** [comment]
You have a point. Even though user can rename mc binary name, config dir still conflicts. We have two options here:
1) mc will automatically assume config path to ~/.($BINARY_NAME)/ or support -C /path/to/config
2) Change the name of the project. We struggled with this. It is really hard to find a name shorter and sweeter than "mc" :(

**Comment by abperiasamy** [comment]
Commit #874 adds support for custom config path. Thanks Richarson for your contribution.

**Comment by richarson** [comment]
@abperiasamy Au contraire, thank you for the quick solution!

**Comment by dR3b** [comment]
This is my solution: 
```bash
~ % mv ./mc mcli
```
Problem solved ;)

**Comment by guettli** [comment]
you think this is a solution:

    mv ./mc mcli

This is creating work for everybody - let's fight unemployment.  (joke)

This is just a work-around.

Please provide a unique name from upstream.

The current name `mc` creates confusion and will lead to several solution. DistroX will call it "foo" and distroY will call it "bar", abcBSD will call it "blabla".


The midnight commander was here before.

If you want a sane solution, then please give it a unique name from upstream and create a shell alias for you.
